### PR TITLE
Fix inputs of GeneratePluginDescriptors

### LINKED ISSUE #20033: Plugin Development plugin declares inputs with custom equals()
```
> Task :nebula-code-quality:pluginDescriptors
Using objects as inputs that have a different serialized form but are equal has been deprecated. This is scheduled to be removed in Gradle 8.0. Type 'org.gradle.plugin.devel.PluginDeclaration' has a custom implementation for equals(). Declare the property as @Nested instead to expose its properties as inputs. See https://docs.gradle.org/7.4/userguide/upgrading_version_7.html#equals_up_to_date_deprecation for more details.
```

### Your Environment
Gradle 7.4

### PR DESCRIPTION
**Pull request by wolfs**
Instead of using the serialized form of `PluginDeclaration` as an input, the task now only considers the relevant parts. The PR also fixes `PluginDeclaration.equals()`, which didn't consider the new fields. This is only necessary for backwards compatibility if other tasks would be using `PluginDeclaration` as an input directly.

`PluginDeclaration` shouldn't be `Serializable` either, though removing the interface would be a breaking change. Maybe we can remove then interface in 8.0.

Fixes #20033

### CODE REVIEW

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java [hunk 1]
```diff
@@ -30,7 +30,9 @@
  * @see org.gradle.plugin.devel.plugins.JavaGradlePluginPlugin
  * @since 2.14
  */
-public class PluginDeclaration implements Named, Serializable {
+public class PluginDeclaration implements Named,
+    // TODO: Shouldn't be serializable, remove the interface in Gradle 8.0.
+    Serializable {
```
Comment (lptr) [inline subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java:35]: How are we going to find this in 8.0? Shall we create the PR already?

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/GeneratePluginDescriptors.java [hunk 2]
```diff
@@ -41,15 +45,20 @@
...
     private final DirectoryProperty outputDirectory;
 
     public GeneratePluginDescriptors() {
         ObjectFactory objectFactory = getProject().getObjects();
         declarations = objectFactory.listProperty(PluginDeclaration.class);
         outputDirectory = objectFactory.directoryProperty();
+        implementationClassById = getDeclarations().map(declarations -> declarations.stream()
+            .collect(Collectors.toMap(PluginDeclaration::getId, PluginDeclaration::getImplementationClass, (a, b) -> b, LinkedHashMap::new))
+        );
+        getInputs().property("implementationClassById", implementationClassById);
```
Comment (lptr) [inline subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/GeneratePluginDescriptors.java:58]: Why expose this via the runtime API and not via a getter?

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java (hunk 1 above)
Comment (wolfs) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java:35]: Yes, I think it makes sense to create a PR for 8.0 after this one has been merged.

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/GeneratePluginDescriptors.java (hunk 2 above)
Comment (wolfs) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/GeneratePluginDescriptors.java:58]: Exposing this via a getter is a little bit strange:
- I need to declare it in the acceptedAPI changes, although I declared it `protected`.
- Other tasks/plugins could start using it, and this is purely an internal thing.

So I opted for using the runtime API, since this hides the property from the API of the task. Any objections?

Comment (lptr) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/GeneratePluginDescriptors.java:58]: Would using package private instead of `protected` solve these problems?

**Review by lptr — APPROVED** [review]
LGTM

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/GeneratePluginDescriptors.java (hunk 2 above)
Comment (wolfs) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/GeneratePluginDescriptors.java]: I change this to use package private.

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java (hunk 1 above)
Comment (wolfs) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java:35]: See https://github.com/gradle/gradle/pull/20097

Comment (TWiStErRob) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java:35]: @lptr @wolfs Can you add a deprecation warning for this? e.g. via one/all of:
```java
private void readObject(ObjectInputStream ois) throws IOException, ClassNotFoundException {
    // emit warning about serialization
    ois.defaultReadObject();
}
private void writeObject(ObjectOutputStream oos) throws IOException, ClassNotFoundException {
    // emit warning about serialization
    oos.defaultWriteObject();
}
private Object readResolve()  {
    // emit warning about serialization
    return this;
}
```

Comment (wolfs) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java:35]: That is a good idea! I tried it here: https://github.com/gradle/gradle/pull/20125

There is currently a problem that the deprecation warning also is emitted when using configuration caching, so I am not sure I can include the deprecation.

Comment (TWiStErRob) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java:35]: Continued here: https://github.com/gradle/gradle/pull/20125/files#r822429036
