### PR TITLE
Fix build cache expiry reported to Build Scans

### LINKED ISSUE #30260: Local build cache configuration shown in build scans does not match actual configuration
### Current Behavior

When you set the local build cache configuration via `buildCache.local` in `settings.gradle`, the build scan correctly shows the configured value for `buildCache.local.removeUnusedEntriesAfterDays`.  With https://github.com/gradle/gradle/pull/28521 however, we allow this value to default to the value configured in the more general cache settings (i.e. `caches.buildCache.removeUnusedEntriesAfterDays`) from an init script.  But the value provided to build scans is always the value from `buildCache.local` even if the underlying cache is configured to use the value from `caches.buildCache`.

This is because we set the value in the describer for the local build cache _before_ we calculate the actual value used for the underlying persistent cache ([see here](https://github.com/gradle/gradle/blob/f52a62045174134b5cafee64a9d79123fb4400e0/subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheServiceFactory.java#L88)).

### Expected Behavior

The value for entry retention for local build cache in build scans should reflect the actual value used and not the value from the settings local build cache configuration object.

### Context (optional)

This is misleading because it appears as if the values in `caches.buildCache` are having no effect when they actually are being used.

### Steps to Reproduce

Using an init.gradle that sets the overall cache value:
```
beforeSettings { settings ->
    println "setting up caches"
    settings.caches {
        buildCache.removeUnusedEntriesAfterDays = 2
    }
}
```

run `gradle -I init.gradle --scan help`

The build scan produced will show `removeUnusedEntriesAfter` is 7 days under performance/build-cache, which is the default value for `buildCache.local.removeUnusedEntriesAfterDays`.  However, debugging this shows that the actual value being used for the cache is 2 days.

If you set the value in the legacy build cache configuration in settings.gradle:
```
buildCache {
    local {
        removeUnusedEntriesAfterDays = 3
    }
}
```
The build scan shows the correct value.

### Gradle version

8.10

### Build scan URL (optional)

https://scans.gradle.com/s/s4ieevs4osaoe/performance/build-cache

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by bigdaz**
Fixes #30260 

### Context
When using an init-script to configure Build Cache cleanup and expiry, Gradle currently reports the wrong value for 'removeUnusedEntriesAfter'. This incorrect value is then rendered in Build Scans. 

This PR fixes this issue by reporting on the value that is actually used to determine TTL for build cache entries, whether it is configured via the (deprecated) `DirectoryBuildCache.removeUnusedEntriesAfterDays` or via an [init-script that configures cache cleanup](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home:configure_cache_cleanup).

If the cache-cleanup init-script is used in the usual manner to configure cache expiry as a number of days, we now correct render the expiry as "after X days". ([Example scan](https://scans.gradle.com/s/rm4cegnccryfs/performance/build-cache#local-cache-remove-unused-entries))
If the cache-cleanup init-script uses an internal property to set the cache expiry time to a timestamp we render this as "at DDDD-MM-YY HH:MM:SS UTC". ([Example scan](https://scans.gradle.com/s/kmehjltxqg46a/performance/build-cache#local-cache-remove-unused-entries))

Note that the second scenario is currently used by the `setup-gradle` action in order to minimise the number of entries retained in the local build cache.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Review by facewindu — APPROVED** [review]

File: subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpiration.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+
+    public DirectoryBuildCacheEntryExpiration(DirectoryBuildCache directoryBuildCache, CacheConfigurationsInternal cacheConfigurations) {
+        @SuppressWarnings("deprecation")
+        int deprecatedRemoveUnusedEntriesAfter = directoryBuildCache.getRemoveUnusedEntriesAfterDays();
+
+        // Use the deprecated retention period if configured on `DirectoryBuildCache`, or use the core 'buildCache' cleanup configuration if not.
+        // If the deprecated property remains at the default, we can safely use the central value (which has the same default).
+        if (deprecatedRemoveUnusedEntriesAfter == CacheConfigurationsInternal.DEFAULT_MAX_AGE_IN_DAYS_FOR_BUILD_CACHE_ENTRIES) {
+            this.expiryTime = cacheConfigurations.getBuildCache().getRemoveUnusedEntriesOlderThanAsSupplier();
+            long expiryDuration = System.currentTimeMillis() - this.expiryTime.get();
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpiration.java:40]: 🤔 I find it somewhat strange that the configuration value seems to depend on the current timestamp. I suppose it does depend a lot on how you configure the new parameter.

File: subprojects/core/src/test/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpirationTest.groovy [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+import org.gradle.caching.BuildCacheServiceFactory
+import org.gradle.caching.local.DirectoryBuildCache
+import spock.lang.Specification
+
+import java.util.concurrent.TimeUnit
+
+import static org.gradle.internal.time.TimestampSuppliers.daysAgo
+import static org.gradle.internal.time.TimestampSuppliers.inThePast
+
+class DirectoryBuildCacheEntryExpirationTest extends Specification {
```
Comment (wolfs) [inline subprojects/core/src/test/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpirationTest.groovy:30]: I think we should have an integration test here that checks the build operation, not just a unit test.

File: subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpiration.java [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+                this.description = TimeFormatting.formatDurationTerse(expiryDuration);
+            }
+        } else {
+            this.expiryTime = TimestampSuppliers.daysAgo(deprecatedRemoveUnusedEntriesAfter);
+            this.description = deprecatedRemoveUnusedEntriesAfter + " days";
+        }
+
+    }
+
+    public Supplier<Long> getRemoveUnusedEntriesAfter() {
```
Comment (ghale) [inline subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpiration.java:54]: Nitpick: I would use something less ambiguous, like `removeUnusedEntriesPriorTo()` or `removeUnusedEntriesOlderThan()` or even `retainUsedEntriesCreatedAfter()`.  I find `removeUnusedEntriedAfter()` to cause some mental gymnastics given it's in fact a timestamp.  It makes sense for a number of days, where we're always calculating back from the present, but when we're talking about a timestamp in the past, "after" seems to imply the wrong direction.

File: subprojects/core/src/test/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpirationTest.groovy (hunk 2 above)
Comment (ghale) [reply subprojects/core/src/test/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpirationTest.groovy:30]: Agreed.  I reckon we could make it a part of [this test](https://github.com/gradle/gradle/blob/3c455091da1c78144e43f37ecc843136165b2aa7/platforms/core-execution/build-cache/src/integTest/groovy/org/gradle/caching/internal/BuildCacheBuildOperationsIntegrationTest.groovy#L37).  I think `FinalizeBuildCacheConfigurationBuildOperationType` is the build operation type you'd be looking for.

**Review by ghale — APPROVED** [review]
I left a (very) minor comment and I think @wolfs suggestion for a build operation integration test is a good one.  But I think the basic fix here is good to merge.

File: subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpiration.java (hunk 1 above)
Comment (bigdaz) [reply subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpiration.java:40]: Yes, the expiry can still be configured as `removeUnusedEntriesAfterDays(5)`, but we wanted to be flexible and allow an arbitrary timestamp to be configured.

So we're effectively converting the "number of days" to a timestamp, and then reverse engineering this to present a human-consumable value to Build Scans.

Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpiration.java:40]: Is the configuration re-run on a configuration cache hit? Or is the value stored as is in the configuration cache? If it isn't re-run, then `removeUnusedEntriesAfterDays(5)` might mean `removeUnusedEntriesAfterDays(10)` if you had configuration cache hits for 5 consecutive days.

> So we're effectively converting the "number of days" to a timestamp, and then reverse engineering this to present a human-consumable value to Build Scans.

It would be good if the configuration exposes whether the timestamp is supposed to be relative or absolute. Though I am not sure how hard that would be to implement. Build Scans do not rely on name of the key, so we could also change the key if that makes it better. IMO it would be good if the configuration by build scans doesn't change if the user doesn't change the configuration.

Comment (bigdaz) [reply subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpiration.java:40]: > Is the configuration re-run on a configuration cache hit? Or is the value stored as is in the configuration cache?

We do the translation of user configuration to timestamp when constructing the BuildCache service, so I'm pretty confident the timestamp itself won't be persisted in the configuration cache. But I will test this.

> It would be good if the configuration exposes whether the timestamp is supposed to be relative or absolute.

I don't think I understand. The timestamp is an instant expressed in milliseconds since epoch. It's always going to be absolute.

The idea was that we don't tie our internal infrastructure to the configuration API: we should be able to provide other configuration mechanisms (eg `removeEntriesUnusedSinceStartOfBuild()`) and have these converted to a timestamp for the infrastructure to deal with.

> Build Scans do not rely on name of the key, so we could also change the key if that makes it better. IMO it would be good if the configuration by build scans doesn't change if the user doesn't change the configuration.

Can you clarify how you'd like to see things expressed in Build Scans, assuming that there may be different ways of configuring the expiry in the future? We could simply render the timestamp directly (`removeEntriesNotUsedSince`) but I think this won't be better for users.

Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpiration.java:40]: > I don't think I understand. The timestamp is an instant expressed in milliseconds since epoch. It's always going to be absolute.
>
> The idea was that we don't tie our internal infrastructure to the configuration API: we should be able to provide other configuration mechanisms (eg removeEntriesUnusedSinceStartOfBuild()) and have these converted to a timestamp for the infrastructure to deal with.

Yes, the timestamp is absolute, though the configuration API allows you to provide relative timestamps. And you expect for every build that the relative timestamp (aka older than 5 days) to be re-evaluated to an absolute timestamp. I'd somewhat expect whatever we send to scans to reflect the semantic meaning of the configuration API, not the internal value. And if we add something new to the configuration we could reflect that in scans as well.

Though like I said, I am fine to use what we do in this PR.

Comment (bigdaz) [reply subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryExpiration.java:40]: Actually, the [configuration API only allows you to specify number of days](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home:configure_cache_cleanup), just like the deprecated mechanism on `DirectoryBuildCache`.
This value is [immediately converted to a timestamp](https://github.com/gradle/gradle/blob/31a349ecf6827ba52baa59c9f1340de493883822/subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java#L245), which makes me wonder about the impact of configuration-cache on these settings.

I'll investigate.

File: subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryRetention.java [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+            long expiryDays = TimeUnit.MILLISECONDS.toDays(entryRetentionMillis);
+            if (expiryDays >= 2) {
+                return "after " + expiryDays + " days";
+            } else {
+                return "after " + TimeFormatting.formatDurationTerse(entryRetentionMillis);
+            }
+        }
+
+        // Always render the timestamp in UTC
+        return "at " + Instant.ofEpochMilli(entryRetentionMillis).atZone(ZoneId.of("UTC")).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z"));
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryRetention.java:73]: 🤔 Do we do some time rendering somewhere else? What pattern do we use there?

**Review by wolfs — APPROVED** [review]

File: subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryRetention.java (hunk 4 above)
Comment (bigdaz) [reply subprojects/core/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheEntryRetention.java:73]: Yes, but nothing consistent. For Build Scans it's important that we include the TZ because the date could be viewed in a different location to where the build executes.

**Review by ghale — APPROVED** [review]
LGTM
