### PR TITLE
Include the implementation field in auto-provisioned JDK archive file names

### LINKED ISSUE #19383: Changes to toolChain implementation are ignored
When the `java.toolchain` specification is changed by adding/removing/changing the `implementation`, this change is ignored and the previously configured toolchain will be used.

This problem is presumably because the download file name does not encode this information.

Note that a similar issue occurs with Gradle 7.4 nightly, when changing the `vendor` from `ADOPTIUM` to `IBM_SEMERU`.

### Expected Behavior
The specified toolchain should be downloaded, provisioned and used.

### Current Behavior
The change to toolchain spec is ignored.

### Steps to Reproduce 
1. Checkout the `main` branch of https://github.com/bigdaz/gradle-toolchain-issues
2. Run `./gradlew -g HOME build` : the build should fail as described in #19382 
3. Change the `build.gradle` file to comment out the `implementation` set on the Java toolchain spec.
4. Run `./gradlew -g HOME build` again : the same error will occur.
5. `rm -rf HOME` to start with a clean Gradle User Home
6. Run `./gradlew -g HOME build` again : this time the toolchain is successfully extracted.

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #19383

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle RFM

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Review by ljacomet — APPROVED** [review]

**Comment by ljacomet** [comment]
@jbartok This is good to go but needs to be in `release`!

**Comment by jbartok** [comment]
@bot-gradle test and merge

File: subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkRemoteBinary.java [hunk 1]
```diff
@@ -113,8 +113,17 @@ private String determineImplementation(JavaToolchainSpec spec) {
         return "hotspot";
     }
 
+    private String determineVendor(JavaToolchainSpec spec) {
+        DefaultJvmVendorSpec vendorSpec = (DefaultJvmVendorSpec) spec.getVendor().get();
+        if (vendorSpec == DefaultJvmVendorSpec.any()) {
+            return "adoptium";
```
Comment (mlopatkin) [inline subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkRemoteBinary.java:119]: It is a minor optimization but it might be beneficial to take `implementation` into account too. If `J9` is involved then it is possible to end up with two copies - `semeru-openj9` for specs with an explicit vendor and `adoptium-openj9` for the rest.
