### PR TITLE
Fix missing `buildTreePath` on tasks of `BuildInvocations` and `CppProject`

### LINKED ISSUE #26899: Build tree path is not available for all models exposing the Task type
We recently introduced a `getBuildTreePath()` method on the `Task` Tooling API model, among others.

However, it seems that in a number of places where the model interfaces expose the `Task` types, the underlying implementation does not provide a value for the build tree path.

Some of the model implementations use the `ToolingModelBuilderSupport.buildFromTask` method to configure an instance of the `LaunchableGradleTask` that structurally implements the `Task` model. However, not in all places where this method is call it is followed by a call to `setBuildTreePath`. This leads me to believe that those instances keep the build tree path unassigned.

This seems to happen at least in:
- `BuildInvocationsBuilder`
- `CppModelBuilder`

Possibly, there are more instances of this.

It also appears that there is no test coverage at the moment that documents this behavior.

### PR DESCRIPTION
**Pull request by reinsch82**
Fix #26899

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by reinsch82** [comment]
@alllex I didn't add `setBuildTreePath` to `buildFromTask` because [this](https://github.com/gradle/gradle/blob/376f4a10f196252298c7139cc679994acdbddd90/platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/GradleProjectBuilder.java#L101) uses another way of figuring out the `buildTreePath`.
I didn't understand the ramifications well enough to change that.

**Comment by alllex** [comment]
I think `setBuildTreePath` call should definitely be moved into `buildFromTask`. The other place that uses the different logic should be refactored, which I was planning to do anyway in [another PR](https://github.com/gradle/gradle/pull/26950/files#diff-41cbdb2660a747d91e926d91efdf3b2dc8deaba716adeebd652134b6f7925ad0L108-R106). The task's identity path is by definition the build tree path, so it is safe to use it.

File: platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/BuildInvocationsBuilder.java [hunk 1]
```diff
@@ -71,11 +73,11 @@ public DefaultBuildInvocations buildAll(String modelName, Project project) {
         for (String selectorName : selectorsByName.keySet()) {
             LaunchableGradleTaskSelector selector = selectorsByName.get(selectorName);
             selectors.add(selector.
-                    setName(selectorName).
-                    setTaskName(selectorName).
-                    setProjectIdentifier(projectIdentifier).
-                    setDisplayName(selectorName + " in " + project + " and subprojects.").
-                    setPublic(visibleTasks.contains(selectorName)));
+                setName(selectorName).
```
Comment (alllex) [inline platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/BuildInvocationsBuilder.java:76]: 🎉  Kudos for reformatting this. I would go one step further and also replace "trailing dots" with "leading dots" like
```
.setName(selectorName)
```

I think we consistently use the latter across the codebase except for some older places

File: platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/BuildInvocationsBuilder.java [hunk 2]
```diff
@@ -94,11 +96,13 @@ private DefaultProjectIdentifier getProjectIdentifier(Project project) {
...
     private List<LaunchableGradleTask> tasks(Project project, DefaultProjectIdentifier projectIdentifier) {
-        List<LaunchableGradleTask> tasks = Lists.newArrayList();
-        for (Task task : taskLister.listProjectTasks(project)) {
-            tasks.add(buildFromTask(new LaunchableGradleTask(), projectIdentifier, task));
-        }
-        return tasks;
+        return taskLister.listProjectTasks(project).stream()
+            .map(task -> {
+                LaunchableGradleTask launchableGradleTask = buildFromTask(new LaunchableGradleTask(), projectIdentifier, task);
+                launchableGradleTask.setBuildTreePath(((TaskInternal) task).getIdentityPath().getPath());
```
Comment (alllex) [inline platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/BuildInvocationsBuilder.java:102]: ❌  This call should be moved into `buildFromTask`

I would also suggest extracting the task creation lambda into a separate method call, so that the stream mapping chain is easier to read.

File: platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/BuildInvocationsBuilder.java [hunk 3]
```diff
@@ -112,7 +116,7 @@ private void findTasks(Project project, Map<String, LaunchableGradleTaskSelector
             // this way, for each task selector, its description will be the one from the selected task with the 'smallest' path
             if (!taskSelectors.containsKey(task.getName())) {
                 LaunchableGradleTaskSelector taskSelector = new LaunchableGradleTaskSelector().
-                        setDescription(task.getDescription()).setPath(task.getPath());
+                    setDescription(task.getDescription()).setPath(task.getPath());
```
Comment (alllex) [inline platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/BuildInvocationsBuilder.java:119]: 💅  We should move the dot to the next line

File: platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r82/FetchBuildInvocationsTasks.java [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+import org.gradle.tooling.model.Task;
+import org.gradle.tooling.model.gradle.BuildInvocations;
+
+import java.util.List;
+
+import static java.util.stream.Collectors.toList;
+
+public class FetchBuildInvocationsTasks implements BuildAction<List<Task>> {
+    @Override
+    public List<Task> execute(final BuildController controller) {
```
Comment (alllex) [inline platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r82/FetchBuildInvocationsTasks.java:30]: 💅  We should be able to drop `final` here

File: subprojects/tooling-native/src/main/java/org/gradle/language/cpp/internal/tooling/CppModelBuilder.java [hunk 5]
```diff
@@ -94,30 +97,37 @@ private List<DefaultCppBinaryModel> binariesFor(CppComponent component, Iterable
...
-                LaunchableGradleTask createTaskModel = ToolingModelBuilderSupport.buildFromTask(new LaunchableGradleTask(), projectIdentifier, staticLibrary.getLinkFileProducer().get());
+                LaunchableGradleTask createTaskModel = buildLaunchableTask(projectIdentifier, staticLibrary.getLinkFileProducer().get());
                 DefaultLinkageDetails linkageDetails = new DefaultLinkageDetails(createTaskModel, staticLibrary.getLinkFile().get().getAsFile(), Collections.<String>emptyList());
                 binaries.add(new DefaultCppStaticLibraryModel(binary.getName(), cppBinary.getIdentity().getName(), binary.getBaseName().get(), compilationDetails, linkageDetails));
             }
         }
         return binaries;
     }
 
+    @Nonnull
```
Comment (alllex) [inline subprojects/tooling-native/src/main/java/org/gradle/language/cpp/internal/tooling/CppModelBuilder.java:124]: ❌  We should not use JetBrains'es nullability annotations. I think we can just drop it here, no need to annotate the method.

File: subprojects/tooling-native/src/main/java/org/gradle/language/cpp/internal/tooling/CppModelBuilder.java [hunk 6]
```diff
@@ -94,30 +97,37 @@ private List<DefaultCppBinaryModel> binariesFor(CppComponent component, Iterable
...
+    private static LaunchableGradleTask buildLaunchableTask(DefaultProjectIdentifier projectIdentifier, Task task) {
```
Comment (alllex) [inline subprojects/tooling-native/src/main/java/org/gradle/language/cpp/internal/tooling/CppModelBuilder.java:125]: 🎉  Kudos for extracting a method!

**Comment by alllex** [comment]
@bot-gradle test without pts

**Review by alllex — CHANGES_REQUESTED** [review]
This already looks very good! I think the main thing left to do is to actually move the build tree path setting inside the helper method, and we are good to go.

I also left some more smaller comments.

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test this

File: subprojects/tooling-native/src/main/java/org/gradle/language/cpp/internal/tooling/CppModelBuilder.java (hunk 5 above)
Comment (reinsch82) [reply subprojects/tooling-native/src/main/java/org/gradle/language/cpp/internal/tooling/CppModelBuilder.java:123]: this is `javax.annotations.Nonnull`

Comment (alllex) [reply subprojects/tooling-native/src/main/java/org/gradle/language/cpp/internal/tooling/CppModelBuilder.java:123]: My bad, I got too used to IntelliJ inserting wrong annotations when I extract a method via refactoring.

Still, I would remove it from here, because I don't think it's helping much. It's better to later annotate the whole package as non-null.

File: platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/BuildInvocationsBuilder.java [hunk 7]
```diff
@@ -94,11 +95,9 @@ private DefaultProjectIdentifier getProjectIdentifier(Project project) {
...
     // build tasks without project reference
     private List<LaunchableGradleTask> tasks(Project project, DefaultProjectIdentifier projectIdentifier) {
-        List<LaunchableGradleTask> tasks = Lists.newArrayList();
-        for (Task task : taskLister.listProjectTasks(project)) {
-            tasks.add(buildFromTask(new LaunchableGradleTask(), projectIdentifier, task));
-        }
-        return tasks;
+        return taskLister.listProjectTasks(project).stream()
+            .map(task -> buildFromTask(new LaunchableGradleTask(), projectIdentifier, task))
+            .collect(toList());
```
Comment (alllex) [inline platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/BuildInvocationsBuilder.java:100]: ❌ Collecting a stream into a list with a `Collectors.toList` does not guarantee that the returned list is serializable (see javadoc of the method).
Since we are going to serialize the list, we need to make sure this won't break when running in future versions of Java. I presume it currently works, because current JDKs do return a serializable list.

I suggest to not fix it here, but instead make an immutable copy of the task list when we assign it into the field here:
https://github.com/gradle/gradle/blob/1295becbd5d1c33eb88d9baf8153a8073a7c4ee0/platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/model/DefaultBuildInvocations.java#L43
->
https://github.com/gradle/gradle/blob/35a9b833a1185c500bb9b90379aebe3a50a63875/platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/model/DefaultGradleProject.java#L128

**Review by alllex — CHANGES_REQUESTED** [review]
I noticed one more thing. Also, when rebasing please check that we don't end up calling `setBuildTreePath` twice in `GradleProjectBuilder`.

**Review by alllex — APPROVED** [review]
LGTM! 
Thanks for bringing this to the finish line, and improving the code around 👍

**Comment by reinsch82** [comment]
@bot-gradle merge
