### PR TITLE
Input artifact should only be an incremental input

### LINKED ISSUE #19003: Gradle 7.4 nightly breaks artifact transforms
Scan: https://ge.androidx.dev/s/ao3lcr3kfuauk/failure#1

To reproduce:
- repo: https://github.com/androidx/androidx repository branch `gradle74`
- `cd navigation`
- `./gradlew :hilt:hilt-navigation-fragment:hiltAggregateDepsDebugUnitTest`
- results in https://ge.androidx.dev/s/m5rzjpyd2iah2

### PR DESCRIPTION
**Pull request by wolfs**
but not a primary input. We don't know how to reconstruct the result when the input artifact is empty.

Fixes #19003

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test QFL

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java [hunk 1]
```diff
@@ -376,7 +376,7 @@ public void visitIdentityInputs(InputVisitor visitor) {
         @Override
         @OverridingMethodsMustInvokeSuper
         public void visitRegularInputs(InputVisitor visitor) {
-            visitor.visitInputFileProperty(INPUT_ARTIFACT_PROPERTY_NAME, PRIMARY,
+            visitor.visitInputFileProperty(INPUT_ARTIFACT_PROPERTY_NAME, INCREMENTAL,
```
Comment (lptr) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java:379]: IIUC, this changes the behavior from the primary input always being `@SkipWhenEmpty` to never being `@SkipWhenEmpty`. Would it make sense for some transforms to allow marking their primary input as `@SkipWhenEmpty` even if the default is the opposite?

Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java:379]: It doesn't change the behavior, since the execution engine didn't handle skip when empty before. So transforms never supported this. It slipped in accidentally with the other PR.

Comment (lptr) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java:379]: I see. Still, do we want to (eventually) support `@SkipWhenEmpty` for primary transform inputs? If so, I think we should add an issue for this. Otherwise let's ship this.

**Review by lptr — APPROVED** [review]
LGTM.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java (hunk 1 above)
Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java:379]: > Still, do we want to (eventually) support @SkipWhenEmpty for primary transform inputs?

We could, that would mean that we would create an empty results file (aka empty list of files) when the sources are empty. Though I can't come up with a good use-case now, so I wouldn't even add an issue for it.

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge
