### PR TITLE
Fix regression with null-message containing assumption failures

### LINKED ISSUE #33157: Support for skipped tests can cause failure to write test report
### Current Behavior

With the following test:

```
    @Test public void testAborted() {
        System.out.println("aborted");
        throw new org.opentest4j.TestAbortedException();
    }
```

Gradle will fail to write the test report

### Expected Behavior

Gradle should not fail to write the test report.

### Context (optional)

This is caused by the added support for skipped tests (see #5511). Not that with 8.13, there is no issue because there is no skipped information in the test results.

### Self-contained Reproducer Project

Skipped

### Gradle version

8.14 RC1

### Gradle version that used to work

8.13

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by big-guy**
fixes #33157 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: testing/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/HtmlTestExecutionResult.groovy [hunk 1]
```diff
@@ -236,10 +237,14 @@ class HtmlTestExecutionResult implements TestExecutionResult {
...
             if (!testCase.messages.isEmpty()) {
-                String possibleText = testCase.getMessages().first()
-                String[] stacktraceMessage = possibleText.readLines().first().split(":", 2)
-                assert stacktraceMessage.length == 2 // sanity check that we're parsing something that looks like an exception stacktrace
-                skippedExecutionResult = new SkippedExecutionResult(stacktraceMessage[1].trim(), stacktraceMessage[0], possibleText)
+                List<String> possibleText = CollectionUtils.single(testCase.messages).readLines()
+                // In the HTML report, the format is:
+                // message
+                // <newline>
+                // exception toString()
```
Comment (octylFractal) [inline testing/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/HtmlTestExecutionResult.groovy:244]: This is more correct I think:
```suggestion
                // exception getStackTrace()
```

File: platforms/software/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/ClassPageRenderer.java [hunk 2]
```diff
@@ -120,12 +120,7 @@ protected void renderIgnoredTests(SimpleHtmlWriter htmlWriter) throws IOExceptio
                 .startElement("a").attribute("name", test.getId().toString()).characters("").endElement() //browsers dont understand <a name="..."/>
                 .startElement("h3").attribute("class", test.getStatusClass()).characters(test.getDisplayName()).endElement();
             for (SerializableFailure failure : test.getFailures()) {
-                String message;
-                if (GUtil.isTrue(failure.getMessage()) && !failure.getStackTrace().contains(failure.getMessage())) {
-                    message = failure.getMessage() + SystemProperties.getInstance().getLineSeparator() + SystemProperties.getInstance().getLineSeparator() + failure.getStackTrace();
-                } else {
-                    message = failure.getStackTrace();
-                }
+                String message = failure.getMessage() + SystemProperties.getInstance().getLineSeparator() + SystemProperties.getInstance().getLineSeparator() + failure.getStackTrace();
```
Comment (octylFractal) [inline platforms/software/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/ClassPageRenderer.java:123]: Minor nit, but can this line separator call be pulled out to a variable outside the loop? Seems wasteful to refetch it over and over.

**Review by octylFractal — APPROVED** [review]

File: platforms/jvm/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/jupiter/JUnitJupiterAssumptionFailureIntegrationTest.groovy [hunk 3]
```diff
@@ -75,6 +75,62 @@ class JUnitJupiterAssumptionFailureIntegrationTest extends AbstractIntegrationSp
...
+        """
+        when:
+        succeeds("test")
+        then:
+        outputContains("Assumption failure: ")
+        def testResult = new DefaultTestExecutionResult(testDirectory)
+        testResult.testClass("com.example.MyTest").assertTestSkipped("theTest") {
+            assert it.message == "(no message)"
+            assert it.type == "org.opentest4j.TestAbortedException"
+            assert !it.text.empty
```
Comment (tresat) [inline platforms/jvm/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/jupiter/JUnitJupiterAssumptionFailureIntegrationTest.groovy:130]: 💭 Should this verify what specific text is expected?

**Review by tresat — APPROVED** [review]
