### PR TITLE
Make task preCompileJsps compatible with configuration cache 

### LINKED ISSUE #21808: CCH22-11: Adjust the `snippets/dependencyManagement/definingUsingConfigurations-custom` sample for configuration cache
The sample project located under [`subprojects/docs/src/snippets/dependencyManagement/definingUsingConfigurations-custom`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/dependencyManagement/definingUsingConfigurations-custom) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-dependency-management-defining-using-configurations-custom_groovy_custom-configuration.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-defining-using-configurations-custom_groovy_custom-configuration.sample)
    ```
    Could not get unknown property 'configurations' for task ':preCompileJsps' of type org.gradle.api.DefaultTask.
    ```

* `snippet-dependency-management-defining-using-configurations-custom_kotlin_custom-configuration.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-defining-using-configurations-custom_kotlin_custom-configuration.sample)
    ```
    Task `:preCompileJsps` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-dependency-management-defining-using-configurations-custom_groovy_custom-configuration.sample" \
    --tests "*snippet-dependency-management-defining-using-configurations-custom_kotlin_custom-configuration.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_dependencies.adoc`;

### PR DESCRIPTION
**Pull request by bacecek**
Fixes #21808

### CODE REVIEW

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

File: subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesDefiningUsingConfigurationsIntegrationTest.groovy [hunk 1]
```diff
@@ -34,7 +33,6 @@ class SamplesDefiningUsingConfigurationsIntegrationTest extends AbstractIntegrat
     }
 
     @UsesSample("dependencyManagement/definingUsingConfigurations-custom")
-    @ToBeFixedForConfigurationCache(iterationMatchers = ".*kotlin dsl")
```
Comment (bacecek) [inline subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesDefiningUsingConfigurationsIntegrationTest.groovy:37]: I found this test and decided that this change is important because test was failing when launching from Intellij. Let me know if it's wrong and I should not touch it.

Comment (abstratt) [reply subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesDefiningUsingConfigurationsIntegrationTest.groovy:37]: Indeed, and good catch!

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge
