### PR TITLE
DefaultDeleter now deletes read-only files on Windows

### LINKED ISSUE #26539: Support deleting windows files with read-only attribute
### Expected Behavior

Gradle `clean` task should be able to delete windows files with read-only attribute. 

### Current Behavior (optional)

Currently, Gradle `clean` task can't delete windows files with read-only attribute.

### Context

In Gradle there're some `version-control` integration tests that generate read-only git blob files, like this:

```
tcagent1@WINDOWS238 C:\tcagent1\work\f63322e10dd6b396>attrib C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git\objects\pack\pack-a88a85c0b3bd27ed028ec4b02524810d7687f74a.pack
A    R               C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAn
droidBuild\.git\objects\pack\pack-a88a85c0b3bd27ed028ec4b02524810d7687f74a.pack
```

The `R` attribute means it's a windows read-only file. They can be deleted by `del /f` but not `del` or `./gradlew clean`:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':performance:clean'.
java.io.IOException: Unable to delete directory 'C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git\objects\pack\pack-a88a85c0b3bd27ed028ec4b02524810d7687f74a.idx
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git\objects\pack\pack-a88a85c0b3bd27ed028ec4b02524810d7687f74a.pack
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git\objects\pack
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git\objects
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild
```

We need to call `File.setAccessible()` first: https://stackoverflow.com/questions/2877106/java-unmark-file-is-read-only

We have to workaround this issue by https://github.com/gradle/gradle/pull/26523

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Resolves #26539 and #26912 

Needs proper test coverage and Platform check for better performance

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/core-runtime/files/src/test/groovy/org/gradle/internal/file/impl/DefaultDeleterTest.groovy [hunk 1]
```diff
@@ -78,6 +79,21 @@ class DefaultDeleterTest extends Specification {
         didWork
     }
 
+    @Issue("https://github.com/gradle/gradle/issues/26912")
```
Comment (oleg-nenashev) [inline platforms/core-runtime/files/src/test/groovy/org/gradle/internal/file/impl/DefaultDeleterTest.groovy:82]: This test should be enough as a smoke one

**Review by cobexer — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@bot-gradle merge
