### PR TITLE
Let precompiled script plugins with CRLF line separators find its accessors

### LINKED ISSUE #12248: Precompiled script plugin fails to build on Windows if script is saved with CRLF (accessors not resolved)
### Expected Behavior

The precompiled script plugin should compile on all major platforms no matter which ends of lines the file has.

### Current Behavior

If `my-plugin.gradle.kts` is saved with CRLF ends-of-lines, the plugin can't be compiled on Windows.

This sounds super strange, but I can reproduce it reliably.

The workaround is to ensure `.gradle.kts` is saved with LF, so I add `src/main/kotlin/**/*.gradle.kts text eol=lf` to my `.gitignore`.

### Context

I want to split build logic to a precompiled plugin, however, it leads to an extremely hard to understand failure :(

### Steps to Reproduce 

Note: it requires Windows. I can't reproduce the failure in my macOS.

`build.gradle.kts`:

```kotlin
plugins {
    `kotlin-dsl`
}

repositories {
    mavenCentral()
}

configure<KotlinDslPluginOptions> {
    experimentalWarning.set(false)
}
```

`src\main\kotlin\my-plugin.gradle.kts`:

```kotlin
plugins {
    `java-library`
}

// compileJava is a generated accessor
// However, Gradle fails to resolve it if .gradle.kts is written with CRLF end-of-lines :(
tasks.compileJava {
}
```

`gradlew.bat build`:

```
\src\main\kotlin\my-plugin.gradle.kts: (5, 7): Unresolved reference: compileJava
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details
```

### Your Environment

Gradle 6.1.1

Sample failure in GitHub Actions (note that both Linux and macOS builds work there, while Windows fails to build `buildSrc`): https://github.com/weisJ/darklaf/runs/448020434?check_suite_focus=true#step:4:26

### PR DESCRIPTION
**Pull request by bamboo**
By normalising the line separators in the script text before computing its hash.

Fixes #12248

### CODE REVIEW

File: subprojects/base-services/src/main/java/org/gradle/util/TextUtil.java [hunk 1]
```diff
@@ -61,8 +62,16 @@ public static String getPlatformLineSeparator() {
...
+    public static String convertLineSeparators(@Nullable String str, String sep) {
+        return str == null ? null : replaceLineSeparatorsOf(str, sep);
+    }
+
+    /**
+     * Converts all line separators in the specified non-null string to the specified line separator.
+     */
+    public static String replaceLineSeparatorsOf(CharSequence string, String bySeparator) {
+        return Pattern.compile("\r\n|\r|\n").matcher(string).replaceAll(bySeparator);
     }
```
Comment (lptr) [inline subprojects/base-services/src/main/java/org/gradle/util/TextUtil.java]: Doing this ends up replacing correct separators, too (with the same separator), resulting in a lot of unnecessary string concatenation. In most cases what we want is `convertLineSeparatorsToUnix()` where we could be more opinionated and not match `\n` at all. WDYT?

Comment (bamboo) [reply subprojects/base-services/src/main/java/org/gradle/util/TextUtil.java]: Thanks, @lptr. That's a good idea, will do 👍

Comment (bamboo) [reply subprojects/base-services/src/main/java/org/gradle/util/TextUtil.java]: @lptr, I've gone a little further and made it avoid all the allocations when the `\r` character doesn't appear in the input string.

Comment (lptr) [reply subprojects/base-services/src/main/java/org/gradle/util/TextUtil.java]: I don't think you need the explicit `indexOf()` call—if the `replaceAll()` regex doesn't match, it will return the original string.

What you could do to speed things up a bit and avoid unnecessary work is to pre-compile the `Pattern`.

Comment (bamboo) [reply subprojects/base-services/src/main/java/org/gradle/util/TextUtil.java]: Right, it would return the original string after compiling the pattern and doing at least one unnecessary allocation.

I'm ambivalent on this one so I'll go with your suggestion and just precompiled the pattern. The code is simpler that  way. Thanks.
