### PR TITLE
Remove 'trim' in BaseForkOptions.setJvmArgs

### LINKED ISSUE #27385: It's not possible to set '-Dline.separator=\n' via 'forkOptions.jvmArgs'
### Current Behavior

Setting `-Dline.separator=\n` for a forked compiler sets `line.separator` to an empty value leading to an `IndexOutOfBounds` exception in Gradle's internals.

```
tasks.withType<JavaCompile>().configureEach {
    options.isFork = true
    options.compilerArgs = listOf("-verbose") // let the compiler log something
    options.forkOptions.jvmArgs = listOf("-Dline.separator=\n")
}
```

The problem is the `trim()` here that removes newlines or whitespaces that might be valid values for a system property:
https://github.com/gradle/gradle/blob/master/platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java#L94

I think the `trim()` should be removed.

### Expected Behavior

The above configuration sets `line.separator` in the compiler daemon process to `\n`.

### Context (optional)

I would like to set the default line ending for the compiler, and the _annotation processors_ it runs, to a reproducible (platform independent) value. To circumvent issues like this one: https://github.com/google/auto/issues/1656

### Steps to Reproduce

- Create a Gradle project with `plugins { id("java-library") }` and  the above configuration code
- Add one `.java` source file
- run: `gradle compileJava`

### Gradle version

8.5

### Build scan URL (optional)

https://scans.gradle.com/s/mb7daw3qcbmuw

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by jjohannes**
### Context
Fixes #27385

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- ~Update User Guide, DSL Reference, and Javadoc for public-facing changes.~
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by jvandort** [comment]
Thank you for your contribution!

This PR has a valid DCO and tests. The relevant team for this area will confirm the design of the implementation choices.

File: platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java [hunk 1]
```diff
@@ -96,7 +96,6 @@ public List<String> getJvmArgs() {
     public void setJvmArgs(@Nullable List<String> jvmArgs) {
         this.jvmArgs = jvmArgs == null ? null : jvmArgs.stream()
             .filter(Objects::nonNull)
-            .map(String::trim)
             .filter(string -> !string.isEmpty())
```
Comment (octylFractal) [inline platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java:99]: Can this be changed to a `org.apache.commons.lang3.StringUtils#isBlank` call instead? The intention of this code (introduced to fix https://github.com/gradle/gradle/issues/11490) is to filter out bogus empty/blank arguments. This would still let your property setting work without also breaking situations similar to the original issue.

File: platforms/jvm/language-jvm/src/integTest/groovy/org/gradle/api/tasks/compile/ForkOptionsIntegrationTest.groovy [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+                sourceCompatibility = '1.8'
+                targetCompatibility = '1.8'
+                classpath = files()
+                source = 'src'
+                destinationDirectory = layout.buildDirectory.dir('classes')
+            }
+        """
+    }
+
+    def "The system line.separator of the forked compiler process can be configured"() {
```
Comment (octylFractal) [inline platforms/jvm/language-jvm/src/integTest/groovy/org/gradle/api/tasks/compile/ForkOptionsIntegrationTest.groovy:36]: I think this should more clearly state what I think is being tested here, rather than that we want to configure a specific property:
```suggestion
    def "a property of the forked compiler process can be configured with a 'blank' value"() {
```

File: platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java (hunk 1 above)
Comment (jjohannes) [reply platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java]: I changed this as suggested and adjusted the
`BaseForkOptionsTest.JVM options are filtered properly even with bad input`
test to reflect the expected behavior.

File: platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java [hunk 3]
```diff
@@ -26,6 +26,8 @@
 import java.util.Objects;
 import java.util.stream.Collectors;
 
+import static org.apache.commons.lang3.StringUtils.isBlank;
```
Comment (octylFractal) [inline platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java:29]: 💅 Nitpick, I don't think we tend to use static imports in this codebase -- this might be confusing.

**Review by octylFractal — APPROVED** [review]

File: platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java (hunk 3 above)
Comment (jjohannes) [reply platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java]: Removed static import.
