### PR TITLE
Fix issue with buildscript classpath state being discarded

### LINKED ISSUE #27521: Substitution rules for the build script classpath are not applied after the initial resolution
### Current Behavior

After the buildscript classpath configuration is resolved, in order to release heap, we discard the resolution result and we also discard the substitution rules.  However, if the classpath configuration is resolved again (for instance by the buildEnvironment task) we no longer have the substitution rules and the configuration is resolved differently.

### Expected Behavior

The buildscript classpath configuration should resolve exactly the same, even if it is resolved again after it is discarded.

### Context (optional)

_No response_

### Steps to Reproduce

Add a substitution rule of some sort to the buildscript classpath, for instance:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.github.spotbugs:spotbugs-annotations:4.8.3'
    }
    configurations.all { config ->
        config.getResolutionStrategy().eachDependency { dep ->
            if (dep.getRequested().getName() == "spotbugs-annotations") {
                dep.useTarget("com.github.spotbugs:spotbugs-annotations:4.8.1")
                dep.because("Because I said so")
            }
        }
    }
}

```

### Gradle version

8.5

### Gradle version that used to work

7.5.x

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by ghale**
This prevents the state required for resolving the buildscript classpath from being discarded when we discard the resolution results.  This allows the `buildEnvironment` task to correctly re-resolve the buildscript classpath later.

Fixes #27521 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

**Comment by ghale** [comment]
@bot-gradle test this

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java [hunk 1]
```diff
@@ -864,9 +864,19 @@ public TransformUpstreamDependenciesResolverFactory getDependenciesResolverFacto
     }
 
     @Override
-    public void resetResolutionState() {
+    public <T> T withResetResolutionState(Factory<T> factory) {
         warnOnInvalidInternalAPIUsage("resetResolutionState()", ProperMethodUsage.RESOLVABLE);
```
Comment (octylFractal) [inline platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java:868]: The string here should be changed to the new name as well.

File: subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptHandler.java [hunk 2]
```diff
@@ -99,9 +100,12 @@ public ClassPath getScriptClassPath() {
...
             if (classpathConfiguration != null) {
-                resolvedClasspath = buildLogicBuilder.resolveClassPath(classpathConfiguration, dependencyHandler, configContainer);
-                if (!getBoolean(DISABLE_RESET_CONFIGURATION_SYSTEM_PROPERTY)) {
-                    ((ResettableConfiguration) classpathConfiguration).resetResolutionState();
+
+                Factory<ClassPath> classPathFactory = () -> buildLogicBuilder.resolveClassPath(classpathConfiguration, dependencyHandler, configContainer);
+                if (getBoolean(DISABLE_RESET_CONFIGURATION_SYSTEM_PROPERTY)) {
+                    resolvedClasspath = classPathFactory.create();
+                } else {
+                    resolvedClasspath = ((ResettableConfiguration) classpathConfiguration).withResetResolutionState(classPathFactory);
```
Comment (octylFractal) [inline subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptHandler.java:108]: Do I understand correctly that this change keeps the dependency substitution data alive in all cases, not just when `buildEnvironment` is used?

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java (hunk 1 above)
Comment (ghale) [reply platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java]: Good catch.  Fixed.

File: subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptHandler.java (hunk 2 above)
Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptHandler.java:108]: Yes, that's the case.  We keep the substitution rules for the buildscript classpath configuration only, in case it is re-resolved by something (which may be `buildEnvironment` but could be anything else that tries to resolve the classpath configuration for some reason).  However, once something else resolves the classpath configuration, we treat it like any other configuration at that point and cache the resolution results, discard the substitution rules, etc.

**Review by octylFractal — APPROVED** [review]

File: subprojects/core/src/main/java/org/gradle/api/internal/initialization/ResettableConfiguration.java [hunk 3]
```diff
@@ -47,6 +52,7 @@ public interface ResettableConfiguration extends Configuration {
      * @implSpec Usage: This method should only be called on resolvable configurations and should throw an exception if
      * called on a configuration that does not permit this usage.
      */
-    void resetResolutionState();
+    @Nullable
+    <T> T withResetResolutionState(Factory<T> factory);
```
Comment (jvandort) [inline subprojects/core/src/main/java/org/gradle/api/internal/initialization/ResettableConfiguration.java:56]: Changing this method to accept a factory seems more complicated than I would have thought necessary. 

Why not just call `setResolutionShouldBeFinal(false)` specifically for the `classpath` configuration when creating that configuration? Then I don't think this method would need to change at all

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolutionStrategyInternal.java [hunk 4]
```diff
@@ -30,6 +30,14 @@ public interface ResolutionStrategyInternal extends ResolutionStrategy {
      */
     void discardStateRequiredForGraphResolution();
 
+    /**
+     * Sets whether or not any configuration resolution is final and the state required for resolution can be
+     * discarded.  Setting this to false implies that the configuration may be re-resolved again in the future.
+     *
+     * Defaults to true.
+     */
+    void setResolutionShouldBeFinal(boolean resolutionShouldBeFinal);
```
Comment (octylFractal) [inline platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolutionStrategyInternal.java:39]: Rename property to `keepStateRequiredForGraphResolution` to indicate it is related to the `discard...` function above.

File: subprojects/core/src/main/java/org/gradle/api/internal/initialization/ResettableConfiguration.java (hunk 3 above)
Comment (octylFractal) [inline subprojects/core/src/main/java/org/gradle/api/internal/initialization/ResettableConfiguration.java:56]: Rename to `callAndResetResolutionState`.

**Comment by ghale** [comment]
@bot-gradle test this

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolutionStrategyInternal.java (hunk 4 above)
Comment (ghale) [reply platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolutionStrategyInternal.java]: Done

File: subprojects/core/src/main/java/org/gradle/api/internal/initialization/ResettableConfiguration.java (hunk 3 above)
Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/ResettableConfiguration.java]: Done

Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/ResettableConfiguration.java]: Per our conversation, this is partly because `ResolutionStrategyInternal` is not visible from `core` and partly so that we don't have to always manage both things when resetting the resolution state - instead, there is just one method that takes care of everything properly.

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultResolutionStrategy.java [hunk 5]
```diff
@@ -81,6 +81,7 @@ public class DefaultResolutionStrategy implements ResolutionStrategyInternal {
     private boolean verifyDependencies = true;
     private final Property<Boolean> useGlobalDependencySubstitutionRules;
     private boolean returnAllVariants = false;
+    private boolean keepStateRequiredForGraphResolution = true;
```
Comment (octylFractal) [inline platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultResolutionStrategy.java:84]: The name and the flag are backwards now -- it should be default `false`, and the `if` below should invert it.

**Review by octylFractal — CHANGES_REQUESTED** [review]

**Comment by ghale** [comment]
@bot-gradle test this

**Review by octylFractal — APPROVED** [review]

**Comment by ghale** [comment]
@bot-gradle test and merge
