### PR TITLE
Fix invalid class generated when extracting ABI from enum type

### LINKED ISSUE #31436: Invalid class generated when extracting ABI from enum type
### Current Behavior

This is another problem with ASM calculating the number of runtime visible parameter annotations to put into the class file, similar to https://github.com/gradle/gradle/issues/31416.

This time the issue is with enum constructors having implicit `name` and `ordinal` parameters that cannot be annotated, and this shouldn't be listed.

### Expected Behavior

Extracted ABI classes should contain the right number of annotated parameters, and thus be possible to compile against.

### Context (optional)

The problem is caused by this ASM issue: https://gitlab.ow2.org/asm/asm/-/issues/318023.

### Self-contained Reproducer Project

Given an enum like this:

```java
public enum MyEnum {
    VALUE("meta");

    MyEnum(@RuntimeVisible @RuntimeInvisible String metadata) {
        // Constructor
    }
}
```

...currently the generated class causes the following compilation error:

```text
In /Main.java:4: error: cannot access MyEnum
                        System.out.println("Hello " + MyEnum.class.getName());
                                                      ^
  bad class file: /var/folders/mt/w8xt125171b77qvh3q10jhd00000gn/T/spock_can_compile_against_0_temporaryFolder8504945895062116062/api-stubs/MyEnum.class
    bad RuntimeInvisibleParameterAnnotations attribute: MyEnum(java.lang.String)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
In /Main.java:4: error: cannot access java.lang.Byte
                        System.out.println("Hello " + MyEnum.class.getName());
                                                    ^
```

### Gradle version

8.11

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by lptr**
Fixes #31436

This fixes the problem with annotated enum constructors where the constructor would end up having one more `RuntimeVisibleAnnotations` entry recorded, causing compilation errors when trying to compile against the extracted class.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java [hunk 1]
```diff
@@ -108,6 +109,22 @@ public void writeMethod(/* Nullable */ InnerClassMember declaringInnerClass, Met
         mv.visitEnd();
     }
 
+    private static Optional<Integer> calculateNonAnnotableParameterCount(ClassMember classMember, /* Nullable */ InnerClassMember declaringInnerClass, MethodMember method) {
+        if (method.getName().equals("<init>")) {
+            if ((classMember.getAccess() & ACC_ENUM) == ACC_ENUM) {
+                // Enum constructors have an implicit String and int parameter containing
+                // the name and ordinal of the value that is non-annotable.
+                return Optional.of(2);
```
Comment (lptr) [inline build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java:117]: 💭 This is the main change in the PR: we are now also handling enum constructors.
