### PR TITLE
Fix resources being deleted even if they shouldn't

### LINKED ISSUE #14808: Incremental compilation wipes out aggregating processor file in Gradle 6.7
When you alter a java class that does not participate in the creation of file generated by an aggregating annotation processor the generated file is deleted. This behaviour did not occur in 6.6

See https://github.com/micronaut-projects/micronaut-core/issues/4277 for steps to reproduce.

### Expected Behavior

The file should not be deleted.

### Current Behavior

The file is deleted.

### Context

This has broken incremental compilation support in Micronaut and is a critical issue for us. See https://github.com/micronaut-projects/micronaut-core/issues/4277

### Steps to Reproduce 

See https://github.com/micronaut-projects/micronaut-core/issues/4277

### Your Environment

    Operating System: macOs
    Micronaut Version: 2.1.0
    Gradle: 6.7 rc4
    JDK Version: openjdk version "11.0.2" 2019-01-15

### PR DESCRIPTION
**Pull request by melix**
The logic to delete stale files wasn't taking into account the
fact that the modified file may not participate in annotation
processing at all. As a consequence, generated resources would
be deleted if an unrelated file was modified.

Fixes #14808

Fixes #?

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 1]
```diff
@@ -103,8 +103,8 @@ public DependentsSet getRelevantDependents(String className, IntSet constants) {
         if (!constants.isEmpty()) {
             return DependentsSet.dependencyToAll();
         }
-        Set<String> classesDependingOnAllOthers = annotationProcessingData.getGeneratedTypesDependingOnAllOthers();
-        Set<GeneratedResource> resourcesDependingOnAllOthers = annotationProcessingData.getGeneratedResourcesDependingOnAllOthers();
+        Set<String> classesDependingOnAllOthers = Sets.union(annotationProcessingData.getAggregatedTypes(), annotationProcessingData.getGeneratedTypesByOrigin().keySet()).contains(className) ? annotationProcessingData.getGeneratedTypesDependingOnAllOthers() : Collections.emptySet();
```
Comment (ljacomet) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:106]: This seems to be done in a loop. Should we cache the union in `annotationProcessingData`?

**Review by ljacomet — APPROVED** [review]
👍 Nice find

One question:

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java (hunk 1 above)
Comment (melix) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:106]: I don't think it's a big deal here since it's a live set, not an actual computation of union.

**Comment by melix** [comment]
@bot-gradle test this

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java (hunk 1 above)
Comment (melix) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java]: Updated in any case.
