### PR TITLE
Restore full incrementality for Micronaut annotation processor

### LINKED ISSUE #17746: Performance regression for multi-stage incremental annotation processors
The changes in https://github.com/gradle/gradle/commit/5f6aa44665389f1e703bb24d788ad5ee305404db fixed a couple of problems with additions/deletions when using aggregating processors. However, this change also broke the performance of multi-stage processors like Micronaut. That particular processor does all the costly dependency injection logic in an isolating processor and then only writes a service descriptor file in an aggregating processor, which takes the outputs of the first processor as its input. This optimization was made so that the we don't have to reprocess all the injection points on every compile.

We should undo https://github.com/gradle/gradle/commit/5f6aa44665389f1e703bb24d788ad5ee305404db and find a less costly fix for the problems that it addressed. I'm already working on this.

### PR DESCRIPTION
**Pull request by oehme**
Fixes #17746

See individual commits for more details. I stumbled over lots of inconsistencies in the code so I also did some simplifications and fixes on the way.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 1]
```diff
@@ -244,11 +205,28 @@ private void processTransitiveDependentClasses(Set<String> visitedClasses,
             }
             accessibleResultClasses.add(accessibleDependentClass);
             DependentsSet currentDependents = getDependents(accessibleDependentClass);
-            if (!currentDependents.isDependencyToAll()) {
+            if (currentDependents.isDependencyToAll()) {
+                return currentDependents.getDescription();
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:209]: These full recompile reasons were lost before, which meant that things like changing a constant used by `module-info` did not lead to the expected full recompile. Instead, special-case code for `module-info` had been added further down. With this fix, that code could now be removed. This probably also fixes other issues, since `module-info` is not the only full recompile reason, just the most prominent one.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 2]
```diff
@@ -244,11 +205,28 @@ private void processTransitiveDependentClasses(Set<String> visitedClasses,
...
+            } else {
                 resultResources.addAll(currentDependents.getDependentResources());
+                privateResultClasses.addAll(currentDependents.getPrivateDependentClasses());
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:212]: These were lost before and we even had a unit test that asserted this loss of information. After removing all the other special-case code, I could confirm that at least one integration test fails if this line is not here. I've corrected the unit test to assert the right behavior.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 3]
```diff
@@ -207,35 +180,23 @@ public boolean isDependencyToAll(String className) {
...
-            privateResultClasses.add(privateDependentClass);
-            DependentsSet currentDependents = getDependents(privateDependentClass);
-            if (!currentDependents.isDependencyToAll()) {
-                resultResources.addAll(currentDependents.getDependentResources());
-            }
+    private String processDependentClasses(Set<String> visitedClasses,
+                                           Set<String> privateResultClasses,
+                                           Set<String> accessibleResultClasses,
+                                           Set<GeneratedResource> resultResources) {
+        String fullRecompileReason = processTransitiveDependentClasses(visitedClasses, accessibleResultClasses, privateResultClasses, resultResources);
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:187]: Previously, we did the non-transitives first, which meant that they were in `visitedClasses` and would prevent them from being processed by the transitive analysis. Since classes can be both private and accessible dependents, it is important to check accessible first.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 4]
```diff
@@ -258,37 +236,27 @@ private DependentsSet getDependents(String className) {
...
-                continue;
-            }
-            accessibleConstantDependents.add(accessibleDependentClass);
-            DependentsSet constantDependents = compilerApiData.getConstantDependentsForClass(accessibleDependentClass);
-            privateConstantDependents.addAll(constantDependents.getPrivateDependentClasses());
-            remainingAccessibleDependentClasses.addAll(constantDependents.getAccessibleDependentClasses());
+        if (annotationProcessingClassDeps.isEmpty() && annotationProcessingResourceDeps.isEmpty() && constantDependents.isEmpty()) {
+            return dependents;
         }
+        ImmutableSet.Builder<String> privateDependents = ImmutableSet.builder();
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:246]: All the different sources of dependencies are now handled consistently in this method, rather than being spread out over different code paths.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java [hunk 5]
```diff
@@ -16,38 +16,140 @@
...
+import java.util.Collection;
+import java.util.Collections;
+import java.util.EnumMap;
 import java.util.HashSet;
 import java.util.List;
 import java.util.Locale;
+import java.util.Map;
 import java.util.Set;
 
 abstract class AbstractRecompilationSpecProvider implements RecompilationSpecProvider {
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java:43]: I've fully aligned this class so that there is no longer any difference between Groovy and Java, expect for the file extension and whether we need a full recompile on resource changes.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java [hunk 6]
```diff
@@ -16,38 +16,140 @@
...
+            if (changedClasses.isEmpty() && !isIncrementalOnResourceChanges(current)) {
+                spec.setFullRebuildCause(rebuildClauseForChangedNonSourceFile(fileChange));
+            }
+            sourceFileChangeProcessor.processChange(changedClasses, spec);
+        }
+    }
+
+    protected abstract boolean isIncrementalOnResourceChanges(CurrentCompilation currentCompilation);
+
+    private void prepareFilePatterns(Collection<String> staleClasses, PatternSet filesToDelete, PatternSet sourceToCompile, SourceFileClassNameConverter sourceFileClassNameConverter) {
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java:142]: By using the sourceFileClassNameConverter here, I could reduce the include patterns to an absolute minimum, which makes this part easier to understand and slightly more efficient.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpec.java [hunk 7]
```diff
@@ -23,14 +23,10 @@
...
 import java.util.Set;
 
-import static org.gradle.api.internal.tasks.compile.incremental.recomp.WellKnownSourceFileClassNameConverter.isModuleInfo;
-import static org.gradle.api.internal.tasks.compile.incremental.recomp.WellKnownSourceFileClassNameConverter.isPackageInfo;
-
 public class RecompilationSpec {
     private final Set<String> classesToCompile = new LinkedHashSet<>();
     private final Collection<String> classesToProcess = new LinkedHashSet<>();
     private final Collection<GeneratedResource> resourcesToGenerate = new LinkedHashSet<>();
-    private final Set<String> relativeSourcePathsToCompile = new LinkedHashSet<>();
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpec.java:33]: This is no longer needed, we now use the SourceToClassName converter consistently for everything.

File: subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/ServiceRegistryProcessorFixture.groovy [hunk 8]
```diff
@@ -23,62 +23,59 @@ import javax.tools.StandardLocation
...
  * A processor that collects all types annotated with the @Service annotation
- * and generates a single ServiceRegistry class from them. The registry has
- * one getter for each annotated type, which calls the no-argument constructor
- * of that type.
+ * and generates a single ServiceRegistryResource.txt file from them.
+ * Also creates a class called ServiceRegistry which does not reference any of the
+ * other classes, but could simply serve as an entry point for reading the resource file.
  */
 @CompileStatic
 class ServiceRegistryProcessorFixture extends AnnotationProcessorFixture {
```
Comment (oehme) [inline subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/ServiceRegistryProcessorFixture.groovy:31]: This is now much closer to what Micronaut does and will hopefully prevent future regressions. Also see the commit message for why this no longer creates an aggregating class file.

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy [hunk 9]
```diff
@@ -254,7 +253,7 @@ class AggregatingIncrementalAnnotationProcessingIntegrationTest extends Abstract
         run "compileJava"
 
         then:
-        outputs.recompiledFiles("A", "ServiceRegistry", "ServiceRegistryResource.txt")
+        outputs.recompiledFiles("A", "ServiceRegistry", "ServiceRegistryResource.txt", "Dependent")
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy:256]: This assert had been broken a while ago and was missed during review. The test was no longer asserting what its descriptions says. I only noticed this because my simplifications fixed the behavior again.

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy [hunk 10]
```diff
@@ -146,7 +145,7 @@ class AggregatingIncrementalAnnotationProcessingIntegrationTest extends Abstract
         run "compileJava"
 
         then:
-        outputs.recompiledFiles("AHelper", "B", "BHelper", "ServiceRegistry", "ServiceRegistryResource.txt")
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy:149]: This change and the one below are the important parts - They ensure that the minimal set of classes is reprocessed by Micronaut.

File: subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/GroovyJavaJointIncrementalCompilationIntegrationTest.groovy [hunk 11]
```diff
@@ -61,15 +61,15 @@ class GroovyJavaJointIncrementalCompilationIntegrationTest extends AbstractJavaG
...
-        'Remove Java files in joint compilation'    | ['G', 'J']            | ['G']                         | 'non-Groovy file'                                        | ['G', 'G_G']                  | 'Incremental compilation of '
-        'Remove Groovy files in joint compilation'  | ['G', 'J']            | ['J']                         | 'UP-TO-DATE'/*None of the classes needs to be compiled*/ | ['J', 'G']                    | 'G.groovy has been added'
-        'Add Groovy files to joint file set'        | ['G', 'J']            | ['G', 'J', 'G_G']             | 'Incremental compilation of'                             | ['G', 'J', 'G_G']             | 'UP-TO-DATE'
-        'Change root Groovy files '                 | ['G', 'G_G', 'J_G_G'] | ['G.changed', 'G_G', 'J_G_G'] | 'unable to find source file of class J_G_G'              | ['G.changed', 'G_G', 'J_G_G'] | 'UP-TO-DATE'
+        scenario                                    | initialSet            | firstChange                   | firstBuildMessage            | secondChange                  | secondBuildMessage
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/GroovyJavaJointIncrementalCompilationIntegrationTest.groovy:64]: Everything incremental now :tada:

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 12]
```diff
@@ -115,180 +110,101 @@ public ClassSetDiff findChangesSince(ClassSetAnalysis other) {
...
-     */
-    private void processDependentClasses(Set<String> visitedClasses,
-                                         Set<String> privateResultClasses,
-                                         Set<String> accessibleResultClasses,
-                                         Set<GeneratedResource> resultResources,
-                                         Iterable<String> privateDependentClasses,
-                                         Iterable<String> accessibleDependentClasses) {
-
-        for (String privateDependentClass : privateDependentClasses) {
-            if (!visitedClasses.add(privateDependentClass)) {
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:218]: This broke any dependents that were both private and accessible - They were processed here first and then ignored in the transitive dependency analysis further down, because they were already in `visitedClasses`.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 13]
```diff
@@ -115,180 +110,101 @@ public ClassSetDiff findChangesSince(ClassSetAnalysis other) {
...
-        }
-
-        while (!remainingAccessibleDependentClasses.isEmpty()) {
-            String accessibleDependentClass = remainingAccessibleDependentClasses.pop();
-            if (!visitedClasses.add(accessibleDependentClass)) {
-                continue;
-            }
-            accessibleResultClasses.add(accessibleDependentClass);
-            DependentsSet currentDependents = getDependents(accessibleDependentClass);
-            if (!currentDependents.isDependencyToAll()) {
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:247]: This was swallowing dependencies to all. All the "processConstantDependents" code futher down was a workaround trying to get those dependents back. None of it is necessary anymore now that the algorithm returns dependencyToAll when one is found.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 14]
```diff
@@ -115,180 +110,101 @@ public ClassSetDiff findChangesSince(ClassSetAnalysis other) {
...
-     * Computes the transitive dependents of a changed class.
-     * If the class had any changes to inlineable constants, these need to be provided as the second parameter.
-     */
-    public DependentsSet findTransitiveDependents(String className, IntSet constants) {
-        String fullRebuildCause = annotationProcessingData.getFullRebuildCause();
-        if (fullRebuildCause != null) {
-            return DependentsSet.dependencyToAll(fullRebuildCause);
-        }
-
-        DependentsSet deps = getDependents(className);
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:156]: This was unnecessarily complicated, basically unrolling the first iteration of the transitive dependency detection loop.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 15]
```diff
@@ -115,180 +109,81 @@ public ClassSetDiff findChangesSince(ClassSetAnalysis other) {
...
+            if (dependents.isDependencyToAll()) {
+                return dependents;
             }
-            accessibleResultClasses.add(accessibleDependentClass);
-            DependentsSet currentDependents = getDependents(accessibleDependentClass);
-            if (!currentDependents.isDependencyToAll()) {
-                resultResources.addAll(currentDependents.getDependentResources());
-                remainingAccessibleDependentClasses.addAll(currentDependents.getAccessibleDependentClasses());
+            for (String dependentClass : dependents.getAllDependentClasses()) {
+                remaining.addAll(classDependenciesFromAnnotationProcessing.get(dependentClass));
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:168]: This was missing from the previous algorithm, which meant that recompile chains would often abruptly end at annotation processing boundaries. It now keeps going across these boundaries, assuming that any change that affects the annotated class could potentially result in a completely different API on the generated classes. I've added an integration test to keep this from regressing.

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy [hunk 16]
```diff
@@ -392,7 +390,7 @@ class AggregatingIncrementalAnnotationProcessingIntegrationTest extends Abstract
         succeeds "compileJava"
 
         then:
-        with(operations[':compileJava'].result.annotationProcessorDetails as List<CompileJavaBuildOperationType.Result.AnnotationProcessorDetails>) {
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy:395]: This type wasn't actually true - The List contains JSON objects that have the same structure, but different types than the real build operations. I've adjusted it to make that clear and get rid of a compiler warning telling me that we were comparing incompatible types (String vs. Enum)

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy [hunk 17]
```diff
@@ -109,13 +151,14 @@ class IsolatingIncrementalAnnotationProcessingIntegrationTest extends AbstractIn
...
         then:
-        outputs.recompiledFiles("A", "AHelper", "AHelperResource.txt")
+        outputs.recompiledFiles("A", "AHelper", "AHelperResource.txt", "Dependent")
     }
 
     def "source file is recompiled when dependency of generated file changes"() {
         given:
         withProcessor(new OpaqueDependencyProcessor())
         java "@Thingy class A {}"
+        java "class Unrelated {}"
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy:161]: This test wasn't actually testing incremental processing, because the processor was not marked as incremental. It just did a full recompile, so it would have passed even if we completely broke the relevant logic. Inserting this unrelated class here ensures that we really had an incremental compilation.

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy [hunk 18]
```diff
@@ -154,7 +154,7 @@ class IsolatingIncrementalAnnotationProcessingIntegrationTest extends AbstractIn
         outputs.recompiledFiles("A", "AHelper", "AHelperResource.txt", "Dependent")
     }
 
-    def "source file is recompiled when dependency of generated file changes"() {
+    def "source file is reprocessed when dependency of generated file changes"() {
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy:157]: This was unnecessarily inefficient.

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy [hunk 19]
```diff
@@ -63,6 +61,73 @@ class IsolatingIncrementalAnnotationProcessingIntegrationTest extends AbstractIn
...
+
+        when:
+        util.text = "class Util { public void foo() {} }"
+        run "compileJava"
+
+        then:
+        outputs.recompiledFiles("Util", "A", "AHelper", "AHelperResource.txt", "Dependent")
+    }
+
+    def "classes depending on generated files are not recompiled when annotated file's implementation is affected by a change"() {
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy:107]: My assumption here is that a change to a private implementation detail won't realistically affect the ABI of any generated types (since these generated types have no way of accessing these internals in the source class).

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 20]
```diff
@@ -115,180 +84,88 @@ public ClassSetDiff findChangesSince(ClassSetAnalysis other) {
...
         }
-
-        DependentsSet deps = getDependents(className);
-        if (deps.isDependencyToAll()) {
-            return deps;
-        }
-        if (!constants.isEmpty() && !compilerApiData.isSupportsConstantsMapping()) {
-            return DependentsSet.dependencyToAll("an inlineable constant in '" + className + "' has changed");
-        }
-        Set<String> classesDependingOnAllOthers = annotationProcessingData.participatesInClassGeneration(className) ? annotationProcessingData.getGeneratedTypesDependingOnAllOthers() : Collections.emptySet();
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:163]: There shouldn't have been any `if` here, they are called "depending on all others" for a good reason, since they can be affected by newly added files.

**Comment by wolfs** [comment]
@oehme Groovy incremental compilation seems to have gotten a little bit slower with this change: https://builds.gradle.org/repository/download/Gradle_Master_Check_PerformanceTestTestLinux_Trigger/44875658:id/performance-test-results.zip!/report/index.html. Do you have an explanation for this?

**Comment by oehme** [comment]
I'll rerun that scenario with the profiler and see if something sticks out.

**Comment by oehme** [comment]
The adhoc scenario was inconclusive and nothing stands out in the flamegraph diffs: https://builds.gradle.org/buildConfiguration/Gradle_Master_Util_Performance_AdHocPerformanceScenarioLinux/45043775?buildTab=artifacts#%2Fresults%2Fperformance%2Fbuild%2Ftest-results-largeMonolithicGroovyProjectPerformanceAdHocTest.zip!%2Fassemble-for-non-abi-change%2F7.3-20210723132200%2B0000%2Fdiffs. It marks a regression in the "Copy" task, which wasn't touched by this PR.

**Review by wolfs — COMMENTED** [review]
The changes look pretty good and there is a lot of simplification!

I left some comments, mostly questions and some improvement suggestions.

**Comment by wolfs** [comment]
@oehme Is this still true after your changes? In other words, does the incremental Groovy compiler now support Java annotation processing?

https://github.com/gradle/gradle/blob/ade90b458c8b883a8beee992119b88c8435441bd/subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java#L241-L243

**Comment by wolfs** [comment]
@oehme Another comment: I think with your recent changes, the incremental compiler will be broken when using the CLI compiler, since the whole patterns are not as exhaustive as before. I suppose we would need to disable incremental compilation in those cases, right?

**Comment by wolfs** [comment]
I suppose this PR fixes https://github.com/gradle/gradle/issues/9903.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java [hunk 21]
```diff
@@ -16,38 +16,140 @@
...
+        for (String staleClass : staleClasses) {
+            for (String sourcePath : sourceFileClassNameConverter.getRelativeSourcePaths(staleClass)) {
+                filesToDelete.include(sourcePath);
+                sourceToCompile.include(sourcePath);
+            }
+            filesToDelete.include(staleClass.replaceAll("\\.", "/").concat(".class"));
```
Comment (wolfs) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java:148]: I think if we don't have `compilerApiData`, then we need to add the old post-fixes here as well, right? I don't see how this would work without having the mappings file from the Java compiler plugin.

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy (hunk 19 above)
Comment (oehme) [reply subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy:107]: The processor can't access these details unless it already violates the processing contract and uses Javac-internal classes. We already say that incremental processors aren't allowed to do so.

File: subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/ApiGroovyCompiler.java [hunk 22]
```diff
@@ -249,7 +249,10 @@ public boolean apply(File file) {
                         }));
 
                         try {
-                            javaCompiler.execute(spec);
+                            WorkResult javaCompilerResult = javaCompiler.execute(spec);
```
[the remark this answers is not in the document]
Comment (oehme) [reply subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/ApiGroovyCompiler.java:252]: Forked compilation with a custom executable is incremental too. So there's no difference there, it's just inherently less safe because we can miss certain source/class relationships in that case. Which is why we don't recommend using a custom javac executable.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java [hunk 23]
```diff
@@ -16,38 +16,140 @@
...
+            sourceFileChangeProcessor.processChange(changedClasses, spec);
+        }
+    }
+
+    protected abstract boolean isIncrementalOnResourceChanges(CurrentCompilation currentCompilation);
+
+    private void prepareFilePatterns(Collection<String> staleClasses, PatternSet filesToDelete, PatternSet sourceToCompile, SourceFileClassNameConverter sourceFileClassNameConverter) {
+        for (String staleClass : staleClasses) {
+            for (String sourcePath : sourceFileClassNameConverter.getRelativeSourcePaths(staleClass)) {
+                filesToDelete.include(sourcePath);
```
[the remark this answers is not in the document]
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java:145]: Correct, previously we had a bunch of ad-hoc regexes that effectively did the same thing.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java (hunk 21 above)
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java:148]: We run the same tests for CLI and daemon compiler and they all pass with this. I'll have to check for missing coverage then.

File: subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/ServiceRegistryProcessorFixture.groovy (hunk 8 above)
Comment (oehme) [reply subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/ServiceRegistryProcessorFixture.groovy:31]: I'll try what happens with a class file, would be worth the additional coverage. Micronaut writes a [resource file](https://github.com/micronaut-projects/micronaut-core/blob/a949a27c69ff00fe50fa751adf0501540aee79b2/inject/src/main/java/io/micronaut/inject/writer/AbstractClassWriterOutputVisitor.java#L99).

**Comment by oehme** [comment]
>  does the incremental Groovy compiler now support Java annotation processing?

Not yet. But we're not far from it now.

> I suppose this PR fixes #9903.

Indeed.

> I think with your recent changes, the incremental compiler will be broken when using the CLI compiler, since the whole patterns are not as exhaustive as before. I suppose we would need to disable incremental compilation in those cases, right?

I'll have to double-check the test coverage. I was sure we have tests for that and that we run them for both compiler types. But maybe we're missing some.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java (hunk 21 above)
Comment (wolfs) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java:148]: I am really suprised that the inner classes are removed when we remove them from the source file without having the `$*.class` extra include. Do they reference the class and that is why we remove them nontheless?

Comment (wolfs) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java:148]: I played a little bit around and it seems like we find inner and anonymous classes as dependents of the actual classes. That is why this works I suppose.

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy (hunk 19 above)
Comment (wolfs) [reply subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy:107]: 👍

File: subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/ServiceRegistryProcessorFixture.groovy (hunk 8 above)
Comment (oehme) [reply subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/ServiceRegistryProcessorFixture.groovy:31]: Same happens with a class file, which makes sense since class files can be annotation-processed. You get a warning that a class was generated in the last round and no other code can reference that class.

**Comment by oehme** [comment]
@wolfs sorry I just force-pushed and lost your commit in the process, can you push it up again?

**Comment by wolfs** [comment]
> sorry I just force-pushed and lost your commit in the process, can you push it up again?

Done.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@oehme Did you already review the test coverage? Do you plan to add more changes to the PR?

**Comment by oehme** [comment]
Yes, we have several tests dealing with nested classes, as well as your newly added test which shows that renaming cleans up stale ones, so I think we're good. I've also debugged that test to make sure it works for the right reason and not accidentally. The nested class is detected as "affected" by the transitive dependency analysis, because nested classes reference their containing class in the bytecode.

I'm happy with the changes now.

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by graemerocher** [comment]
Awesome, thanks so much for your work on this @oehme !
