### PR TITLE
Ignore "java.awt.headless" in the configuration cache

### LINKED ISSUE #19710: Configuration cache captures system property value set by the build logic causing no cache hits afterward
Gradle 7.4-rc1 Configuration Cache will incorrectly detect `java.awt.headless` as changed.

### Expected Behavior
`java.awt.headless` is not set (null). Configuration cache should NOT be busted when re-running.

### Current Behavior
Gradle 7.4-rc1 will 100% of the time bust configuration cache due to `java.awt.headless` being null.

### Context
Regression in 7.4-rc1, reverted back to 7.3.3 and works as intended, does not get busted for every run.
Configurations are not being cached, this is regression in performance
This might be related to common user gradle plugin - but I belive that is a redherring as that does not even track that property

### Steps to Reproduce 
- Enable configuration-cache
- Run `./gradlew tasks` see cache be stored
- Run `./gradlew tasks` again, Gradle will complain about `java.awt.headless` changing and recompile cache

### Your Environment
Gradle 7.4-rc1, Java 17 (Zulu) - Linux (Ubuntu)

Enterprise server, please reach out for build scan

### PR DESCRIPTION
**Pull request by mlopatkin**
Some popular plugins modify this property at runtime. This breaks
configuration caching if some other plugin reads the modified value -
the fingerprint check at the next run expects the property to have
the modified value so it fails and invalidates the cache.

This change doesn't fix the issue completely but reverts to the old
behavior: use the default (unmodified) value of the property for the
cached run. It is incorrect but for this particular case seems to be
an acceptable compromise. The proper fix is being tracked at #18432.

Fixes #19710.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test RfM, ACC

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test RfM, ACC

**Comment by blindpirate** [comment]
@bot-gradle test RfM, ACC

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy [hunk 1]
```diff
@@ -403,6 +403,29 @@ class UndeclaredBuildInputsIntegrationTest extends AbstractConfigurationCacheInt
         EnvVariableRead.getEnvContainsKey("CI")             | "false"    | "defined" | "true"
     }
 
+    @Issue("https://github.com/gradle/gradle/issues/19710")
+    def "modification of allowed properties do not invalidate cache"() {
+        buildFile("""
+            System.setProperty("java.awt.headless", "true")
+
+            // Attempt to capture the modified property value.
+            println("java.awt.headless=\${System.getProperty("java.awt.headless")}")
```
Comment (bamboo) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy:412]: ⭕ I'd move the printing to an ad-hoc task so its output can be asserted on each run. Asserting on the output would serve to document the expected behavior more explicitly (it would be 'true' on the first run and 'null' on the second?)

**Review by bamboo — CHANGES_REQUESTED** [review]

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy (hunk 1 above)
Comment (mlopatkin) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy]: I'm not a big fan of asserting incorrect behavior but I don't have strong objections, so I've added the printing task. However, the property has to be captured at the configuration time too, this is the very essence of the reproducer.

> it would be 'true' on the first run and 'null' on the second?

Yes, `null` is consistent with what we've had at 7.3 but incorrect, of course.

**Review by bamboo — APPROVED** [review]

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy (hunk 1 above)
Comment (bamboo) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy]: I understand the reluctance but in my opinion is better than to leave the reader wondering what the behavior would be in this case. Thanks!
