### PR TITLE
Disable execution optimizations for invalid work

### LINKED ISSUE #15305: Disable execution optimizations for invalid work
Gradle software checks user code in several ways, e.g. if the necessary input/output
annotations are present, if there are overlapping outputs etc. When such problems occur, some
of the optimizations in Gradle software are not safe and may result in incorrect build results.
We can enforce work validity by punishing invalid work items by:

- disable caching for them (load or store),
- disable incremental execution,
- ignore the state of their inputs and outputs and run them every time,
- prevent other work from running in parallel with invalid work,
- invalidate the whole VFS before invalid work is executed.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by lptr**
Implements most of #15305

- [x] disable caching for them (load or store),
- [x] disable incremental execution,
- [x] ignore the state of their inputs and outputs and run them every time,
- [x] invalidate the whole VFS before invalid work is executed.

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
OK, I think this is taking shape nicely. Caching, up-to-date checks and incremental execution are all disabled now, and the VFS is invalidated. I've added some tests to confirm these. I'm having some trouble with `CachedCustomTaskExecutionIntegrationTest.invalid tasks are not cached` that tries to check for a multi-line string in the output and only fails on CI. 🤷

What's not done at all yet is disabling parallel execution. This has a few issues.

We need to move validation to somewhere close to `DefaultExecutionPlan.canRunWithCurrentlyExecutedNodes()` to make the decision there.

This means that we'll be validating earlier, which in turn means validating things that we don't currently validate. This might have a small performance impact, but there's a perhaps more important aspect, too.

The last time I tried to validate earlier it became apparent that Gradle builds today have a lot of invalid tasks that are skipped because their sources are empty or some similar reason. These would now show up as invalid, and would be prevented from running in parallel with others. We'll need to figure out what to do with them if they are still around.

One potential way to work around this might be to only validate the type in `DefaultExecutionPlan`, and let properties be validated during the actual execution, as they are now.

Another issue is that `DefaultExecutionPlan` uses the `SystemRegistry` to get to the few services it actually needs to resolve properties etc. This in turn means that the associated tests use `ProjectBuilder` which makes services very hard to customize. And we need to customize them because we must force the `TypeAnnotationMetadataStore` to ignore Spock mock methods (`ISpockMock`), otherwise we get validation errors for all the mock task types in the tests. 😞 I think the best course of action here will be to rewrite `DefaultExecutionPlan` to explicitly inject the services it requires, but this will be some work.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test this please.

**Comment by lptr** [comment]
I've fixed the test, let's do the remaining disabling in a separate PR.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java [hunk 1]
```diff
@@ -68,7 +83,55 @@ public R execute(UnitOfWork work, C context) {
                     .collect(Collectors.toList())
             );
         }
-        return delegate.execute(work, context);
+
+        if (!warnings.isEmpty()) {
+            LOGGER.info("Invalidating VFS because of invalid work {}", work.getDisplayName());
```
Comment (wolfs) [inline subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java:88]:
```suggestion
            LOGGER.info("Invalidating VFS because {} failed validation", work.getDisplayName());
```

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java [hunk 2]
```diff
@@ -68,7 +83,55 @@ public R execute(UnitOfWork work, C context) {
...
+            virtualFileSystem.invalidateAll();
```
Comment (wolfs) [inline subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java:89]: Instead of invalidating all of the VFS, shall we maybe only invalidate the VFS associated with the root project or the project root for tasks?

Moreover, can you add an integration test for invalidating the VFS? Probably asserting the info log.

**Review by wolfs — CHANGES_REQUESTED** [review]
Looks good overall. I left some comments.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveCachingStateStep.java [hunk 3]
```diff
@@ -69,6 +71,8 @@ public CachingResult execute(UnitOfWork work, BeforeExecutionContext context) {
         CachingState cachingState;
         if (!buildCache.isEnabled() && !buildScansEnabled) {
             cachingState = BUILD_CACHE_DISABLED_STATE;
+        } else if (context.getValidationProblems().isPresent()) {
+            cachingState = VALIDATION_FAILED_STATE;
```
[the remark this answers is not in the document]
Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveCachingStateStep.java:75]: I don't think that'd be for the better. We already logged the validation problems as deprecation warnings. There might be multiple validation problems, too, and merging those is not nice.

File: subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveCachingStateStepTest.groovy [hunk 4]
```diff
@@ -37,9 +37,23 @@ class ResolveCachingStateStepTest extends StepSpec<BeforeExecutionContext> {
         then:
         _ * buildCache.enabled >> false
         _ * context.beforeExecutionState >> Optional.empty()
-        1 * delegate.execute(work, _ as CachingContext) >> { UnitOfWork work, CachingContext context ->
-            assert context.cachingState.disabledReasons.get(0).category == CachingDisabledReasonCategory.BUILD_CACHE_DISABLED
-        }
+        1 * delegate.execute(work, { CachingContext context ->
+            context.cachingState.disabledReasons*.category == [CachingDisabledReasonCategory.BUILD_CACHE_DISABLED]
+            context.cachingState.disabledReasons*.message == ["Build cache is disabled"]
```
[the remark this answers is not in the document]
Comment (lptr) [reply subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveCachingStateStepTest.groovy:42]: I did actually test this and it works as it is now: if either of the conditions fail, it gets reported, like so:

```
Too few invocations for:

1 * delegate.execute(work, { CachingContext context ->
            context.cachingState.disabledReasons*.category != [CachingDisabledReasonCategory.BUILD_CACHE_DISABLED]
            context.cachingState.disabledReasons*.message == ["Build cache is disabled"]
        })   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * delegate.execute(Mock for type 'UnitOfWork' named 'work', <org.gradle.internal.execution.steps.ResolveCachingStateStep$1@6e34d749 val$cachingState=org.gradle.internal.execution.caching.CachingState$1@1a789e6a val$context=Mock for type 'BeforeExecutionContext' this$0=org.gradle.internal.execution.steps.ResolveCachingStateStep@94b5b22>)
One or more arguments(s) didn't match:
0: <matches>
1: Condition not satisfied:
   
   context.cachingState.disabledReasons*.category != [CachingDisabledReasonCategory.BUILD_CACHE_DISABLED]
   |       |            |                |        |   |
   |       |            |                |        |   class org.gradle.internal.execution.caching.CachingDisabledReasonCategory
   |       |            |                |        false
   |       |            |                [BUILD_CACHE_DISABLED]
   |       |            [Build cache is disabled (BUILD_CACHE_DISABLED)]
   |       <org.gradle.internal.execution.caching.CachingState$1@1a789e6a val$reasons=[Build cache is disabled (BUILD_CACHE_DISABLED)]>
   <org.gradle.internal.execution.steps.ResolveCachingStateStep$1@6e34d749 val$cachingState=org.gradle.internal.execution.caching.CachingState$1@1a789e6a val$context=Mock for type 'BeforeExecutionContext' this$0=org.gradle.internal.execution.steps.ResolveCachingStateStep@94b5b22>
```

That's actually what the documentation you linked to says, too. The example just shows that you can _also_ use `verifyAll()`, but you don't have to.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java (hunk 2 above)
Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java:89]: Good point about the integration test, will add it.

What would be the point of not invalidating the whole VFS?

Comment (wolfs) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java:89]: > What would be the point of not invalidating the whole VFS?

The penalty would be a little bit smaller since we don't invalidate things in the Gradle user home.

File: subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveCachingStateStepTest.groovy (hunk 4 above)
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveCachingStateStepTest.groovy:42]: Ah, you are right!

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveCachingStateStep.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveCachingStateStep.java:75]: I am thinking how the user is going to find out what validation failed when caching (or incremental build) has been disabled. The message "Validation failed" doesn't give me any hint. If I don't use a build scan and run without `--info`, then I won't get any information at all that there has been a validation problem. If I use build scans, then I'll see the `Validation failed` message, though I won't know that I need to find the message on the deprecations page, nor how to find the task in question on the deprecations page.

This task emits a deprecation warning: https://ge.gradle.org/s/hn56auiathetk/timeline?details=75dpsv4ioedm2
You can't see from the documentation page which deprecation it is: https://ge.gradle.org/s/hn56auiathetk/deprecations

It seems to me very cheap to add the failed validations to the caching disabled reason and the out-of-date message and it would make it much better for the user.

I am not sure what we should do for users which don't use build scans. Printing another summary at the end seems redundant, since we already have the deprecation warnings summary. Maybe we could print a different summary text when the deprecations affected performance?

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java (hunk 2 above)
Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java:89]: The performance penalty is very severe regardless of how much of the VFS we invalidate. The sentiment here is that we don't trust the given piece of work, so it makes sense to invalidate everything. Therefore I'd leave this as is.

I've added the integration test.

**Comment by lptr** [comment]
@bot-gradle test QF please.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java (hunk 2 above)
Comment (wolfs) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java:89]: 👍

**Review by wolfs — APPROVED** [review]
LGTM! Can you add the issue about better reporting the disabling of the optimizations?

**Comment by lptr** [comment]
Yes, will do as soon as I figured out what to do with the now failing K9 and Android Large performance tests...

**Comment by lptr** [comment]
These are the tasks broken for the K9 test:

- `checkDebugManifest`
- `createDebugCompatibleScreenManifests`
- `extractDebugAnnotations`
- `generateDebugRFile`
- `mergeDebugResources`
- `packageDebug`
- `packageDebugResources`
- `processDebugManifest`
- `processDebugResources`
- `signingConfigWriterDebug`
- `transformClassesAndResourcesWithSyncLibJarsForDebug`
- `transformClassesWithDexBuilderForDebug`
- `transformNativeLibsWithIntermediateJniLibsForDebug`
- `transformNativeLibsWithSyncJniLibsForDebug`

**Comment by lptr** [comment]
And these are the ones failing for K9:

- `checkDebugManifest`
- `compileDebugAidl`
- `compileDebugJavaWithJavac`
- `compileDebugRenderscript`
- `extractDebugAnnotations`
- `generateDebugRFile`
- `packageDebug`
- `processDebugManifest`
- `processDebugResources`
- `splitsDiscoveryTaskDebug`
- `transformClassesAndResourcesWithPrepareIntermediateJarsForDebug`
- `transformClassesAndResourcesWithSyncLibJarsForDebug`
- `transformClassesWithDexBuilderForDebug`
- `transformDexArchiveWithDexMergerForDebug`
- `transformDexArchiveWithExternalLibsDexMergerForDebug`
- `transformNativeLibsWithIntermediateJniLibsForDebug`
- `transformNativeLibsWithMergeJniLibsForDebug`
- `transformNativeLibsWithSyncJniLibsForDebug`
- `transformResourcesWithMergeJavaResForDebug`

**Comment by lptr** [comment]
@bot-gradle test this please.

**Comment by lptr** [comment]
@bot-gradle test this please.
