### PR TITLE
Don't share dependency resolution listeners list when copying configuration

### LINKED ISSUE #6985: DefaultConfiguration#createCopy shouldn't share mutable listener list
`DefaultConfiguration#createCopy` [replaces](https://github.com/gradle/gradle/blob/b4d8d5d170bb4ba516e88d7fe5647e2323d791dd/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L792) the fresh anonymous broadcaster (`dependencyResolutionListeners`) that each new configuration gets with the one from the copied configuration.

This in conjunction with the fact that after resolve, [the listener set is cleared](https://github.com/gradle/gradle/blob/b4d8d5d170bb4ba516e88d7fe5647e2323d791dd/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L544), means that only one of the original and copied configrations will get a non-empty listener, depending on which one is resolved first.

### Expected Behavior

Each configuration, whether copied or not, should have its own independent `dependencyResolutionListeners` that will get called with that configuration's `ResolvableDependencies` instance.

If preserving the original listeners is important, then the listener set should be shallow-copied into a new set that the copied configuration owns.

### Current Behavior

Only one of the configurations gets to trigger the listeners for both configurations.
This leads to confusion and hacks like [what nebula.dependency-recommender does](https://github.com/nebula-plugins/nebula-gradle-interop/blob/master/src/main/kotlin/com/netflix/nebula/interop/configurations.kt) (that function called [here](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/blob/a8ad219cd8cc4c323327db85902a7b6af0bfb992/src/main/groovy/netflix/nebula/dependency/recommender/DependencyRecommendationsPlugin.java#L91)).

### Context

I am trying to `copyRecursive` the `default` configuration in all subprojects, such that I can resolve them from a root project configuration and afterwards add constraints on the original subprojects' `default` configurations.
This doesn't work with `nebula.dependency-recommender` (it never gets applied to the copied configurations) because it will never have its listener called with the correct `ResolvableDependencies` for the copied configuration.

### Steps to Reproduce (for bugs)

```gradle
configurations {
  foo
}

def fooCopy = configurations.foo.copyRecursive()
configurations.add(fooCopy)

configurations.foo.incoming.beforeResolve { incoming ->
  println("beforeResolved for foo called with: " + incoming)
}

fooCopy.incoming.beforeResolve { incoming ->
  println("beforeResolved for fooCopy called with: " + incoming)
}
```

Will print:

```
> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

foo
beforeResolved for foo called with: dependencies ':foo'
beforeResolved for fooCopy called with: dependencies ':foo'
No dependencies

fooCopy
No dependencies
```

### Your Environment

 * Build scan URL: https://gradle.com/s/az7lcdu766rfk

### PR DESCRIPTION
**Pull request by dansanduleac**
### Context

This change allows a copied configuration (whether copied recursively or not) to have its own list of dependency resolution listeners. This is important because, on resolution, this list (a `ListenerBroadcast`, which is mutable) gets cleared, so any copied configurations will henceforth see the same empty list. Please see the issue for more details.

One main use case is that `nebula.dependency-recommender` will now work on copied configurations, because it relies on `beforeResolve` which is implemented through a dependency resolution listener.

The copied configuration still inherits the existing listeners on the original configuration, to preserve current behaviour that might have been relied on.

Edit: in response to https://github.com/gradle/gradle/issues/6985#issuecomment-430065597 we're now also copying over the `withDependencies` actions to the new configuration.

Fixes #6985 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java [hunk 1]
```diff
@@ -858,7 +857,8 @@ private DefaultConfiguration createCopy(Set<Dependency> dependencies, Set<Depend
         copiedConfiguration.description = description;
 
         copiedConfiguration.defaultDependencyActions = defaultDependencyActions;
-        copiedConfiguration.dependencyResolutionListeners = dependencyResolutionListeners;
+        copiedConfiguration.withDependencyActions = withDependencyActions;
```
Comment (dansanduleac) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java]: Actually - I wonder if it's ok that we just share this (and the above).
It might be unexpected that additional actions on any of the configurations (after copying) seep into the other one.

In fact, don't these get cleared upon resolution too, meaning they have the same bug that this PR fixed for `dependencyResolutionListeners`? :(
