### PR TITLE
Remove suppression of standard output messages

### LINKED ISSUE #33288: Behavior change in TestKit's GradleRunner.withArguments
### Current Behavior

It looks like `GradleRunner.withArguments` ignores all tasks but the first being passed to it.

### Expected Behavior

`GradleRunner.withArguments` executes all tasks being passed to it.

### Context (optional)

One of the tests in the GradleX reproducible builds project starts failing when we try to update the project to 8.14. It looks like the build executed by TestKit [here](https://github.com/gradlex-org/reproducible-builds/blob/efa19a03c443b53d2eefe01f343f1ac82a1b607b/src/test/java/org/gradlex/reproduciblebuilds/EncodingFuncTest.java#L126) only runs `build` but not `run` which makes the test fail. It also looks like GroovyDoc started to log an additional line with 8.14:

```
Resource org/apache/groovy/docgenerator/groovy.ico not found so skipped
```

Not sure what that is about. Was there a Groovy update in 8.14?

### Self-contained Reproducer Project

Checkout https://github.com/gradlex-org/reproducible-builds/pull/30 and see the test failing. It works on `main` branch which is on Gradle 8.13.

### Gradle version

8.14

### Gradle version that used to work

8.13

### Build scan URL (optional)

https://scans.gradle.com/s/n77fqn5p5tvw4

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by ghale**
In 8.14, we made GroovyDoc use the Worker API, so it can now run in parallel with other tasks in the same project.  This exacerbates #27897 and causes more output to potentially be lost.

Fixes #33288 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

File: platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/groovy/GroovyDocIntegrationTest.groovy [hunk 1]
```diff
@@ -170,6 +170,36 @@ class GroovyDocIntegrationTest extends MultiVersionIntegrationSpec {
...
+        file("src/main/groovy/pkg/Thing.groovy") << """
+            package pkg
+
+            class Thing {}
+        """
+
+        when:
+        buildFile << """
+            task('foo') {
+                doLast {
```
Comment (jvandort) [inline platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/groovy/GroovyDocIntegrationTest.groovy:184]: Does it make sense to add a dependsOn groovydoc here? Or do we use the CLI task ordering as a constraint for task scheduling? If so, can we add an assertion that the tasks were executed in the order we expected?

**Review by jvandort — APPROVED** [review]

File: platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/groovy/GroovyDocIntegrationTest.groovy (hunk 1 above)
Comment (ghale) [reply platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/groovy/GroovyDocIntegrationTest.groovy:190]: Actually, we don't want a `dependsOn` relationship because the problem occurs when `GroovyDoc` runs in parallel with other tasks.  I wrote (and named) the test before I fully understood what was happening.  I updated the test name to better reflect this.

To answer your question about task ordering being a constraint, it isn't a "constraint", per se, but it's _exactly_ the same as using a `shouldRunAfter`.  In other words, `shouldRunAfter` simply orders the tasks in the graph such that the task that "should run after" is inserted in the graph after the other (which is the same as ordering them on the command line in the same way).

Having said all of that, I updated the test to ensure that these tasks execute in parallel.  It was triggering the problem pretty much 100% of the time before, but this will future-proof the test and _require_ the two tasks to execute concurrently.
