### PR TITLE
Capture after evaluation exceptions when Kotlin DSL classpath mode is activated

### LINKED ISSUE #18637: Kotlin DSL "classpath mode" leniency doesn't capture after evaluation exceptions
During Gradle/Idea sync, intellij will pass the `org.gradle.kotlin.dsl.provider.mode=classpath` option to Gradle. Now, obviously any exception happening during project configuration will not fail the configuration, but will be stored in the `ClassPathModeExceptionCollector` (see `KotlinScriptEvaluator.withOptions` in the Kotlin IntelliJ Plugin).

In such cases, plugins with after evaluation hooks now see a half-configured model. For example the Kotlin Gradle Plugin runs some “post evaluate” assertions on the Project to see if it was configured correctly. This validation then fails but the thrown exception isn't captured by the `ClassPathModeExceptionCollector`, thus fails the build.

The IntelliJ Kotlin Plugin sync has been changed to not use the "classpath mode" anymore during sync as it proven to be an annoyance. This can be tracked here https://youtrack.jetbrains.com/issue/KTIJ-19823. Target is 2021.3.

The "classpath mode" will still be used by the `LoadConfigurationAction` which is responsible of loading the script context for a single script. This can be triggered by the user by clicking the corresponding button. This leniency is useful to get a good enough content assist in the editor in face of a broken build, or when editing scripts outside the build. This issue is about making that leniency better.

### Expected Behavior

When in "classpath mode" the build shouldn't fail on configuration problems, including after evaluation.

### Current Behavior

When in "classpath mode" the build will fail if an exception is thrown from an after evaluate callback.

### Potential solutions

- not running after evaluation callbacks when in classpath mode
- capturing after evaluation callbacks exceptions when in classpath mode

### PR DESCRIPTION
**Pull request by donat**
Fixes #18637

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test QuickFeedbackLinux

**Comment by donat** [comment]
@bot-gradle test QuickFeedbackLinux

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ClassPathModeExceptionCollector.kt [hunk 1]
```diff
@@ -16,15 +16,16 @@
...
+import org.gradle.internal.service.scopes.ExceptionCollector
 
 
-open class ClassPathModeExceptionCollector : Stoppable {
+open class ClassPathModeExceptionCollector(val suppressor: ExceptionCollector) : Stoppable {
 
     private
     val collection = mutableListOf<Exception>()
 
     val exceptions: List<Exception>
```
Comment (donat) [inline subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ClassPathModeExceptionCollector.kt:27]: Since this is a public API I could not move it to a single service.

File: subprojects/core/src/main/java/org/gradle/internal/service/scopes/ToolingServices.java [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+public class ToolingServices extends AbstractPluginServiceRegistry {
+
+    @Override
+    public void registerBuildServices(ServiceRegistration registration) {
+        registration.addProvider(new ExceptionServices());
+    }
+
+    static class ExceptionServices {
+        public ExceptionCollector createExceptionCollector() {
+            String classpathMode = System.getProperty("org.gradle.kotlin.dsl.provider.mode");
```
Comment (donat) [inline subprojects/core/src/main/java/org/gradle/internal/service/scopes/ToolingServices.java:30]: @eskatos This code belongs to the kotlin-dsl submodule, but it might not be worth the complexity to extract the code.

**Comment by donat** [comment]
@bot-gradle test QuickFeedbackLinux

**Comment by donat** [comment]
@bot-gradle test rFM

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ClassPathModeExceptionCollector.kt (hunk 1 above)
Comment (eskatos) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ClassPathModeExceptionCollector.kt:27]: It is not public API, but it is effectively now used by the Kotlin Gradle Plugin so we need to keep it around a little while.

Another approach would have been to keep this service with it's current API but change it so that it delegates to a new actual implementation.

File: subprojects/core/src/main/java/org/gradle/internal/service/scopes/ToolingServices.java [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+
+public class ToolingServices extends AbstractPluginServiceRegistry {
+
+    @Override
+    public void registerBuildServices(ServiceRegistration registration) {
+        registration.addProvider(new ExceptionServices());
+    }
+
+    static class ExceptionServices {
+        public ExceptionCollector createExceptionCollector() {
```
Comment (eskatos) [inline subprojects/core/src/main/java/org/gradle/internal/service/scopes/ToolingServices.java:29]: It might be worth to wire a NOOP implementation instead of a disabled one when not in classpath mode.

Comment (donat) [reply subprojects/core/src/main/java/org/gradle/internal/service/scopes/ToolingServices.java:60]: Done

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ClassPathModeExceptionCollector.kt (hunk 1 above)
Comment (donat) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ClassPathModeExceptionCollector.kt:24]: I went with the delegation approach.

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@eskatos ptal

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ClassPathModeExceptionCollector.kt [hunk 4]
```diff
@@ -16,22 +16,20 @@
...
 
 import org.gradle.internal.concurrent.Stoppable
+import org.gradle.internal.service.scopes.ExceptionCollector
 
 
-open class ClassPathModeExceptionCollector : Stoppable {
-
-    private
-    val collection = mutableListOf<Exception>()
+open class ClassPathModeExceptionCollector(val delegate: ExceptionCollector) : Stoppable {
```
Comment (eskatos) [inline subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ClassPathModeExceptionCollector.kt:22]: The ctor argument should be private
```suggestion
open class ClassPathModeExceptionCollector(private val delegate: ExceptionCollector) : Stoppable {
```

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/tooling/BuildServices.kt [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+    @Suppress("unused")
+    fun createExceptionCollector(): ExceptionCollector {
+        val classpathMode = System.getProperty("org.gradle.kotlin.dsl.provider.mode")
+        val expressionsSuppressed = classpathMode != null && classpathMode.contains("classpath")
+        return if (expressionsSuppressed) DefaultExceptionCollector() else NOOP_COLLECTOR
+    }
+}
+
+
+class DefaultExceptionCollector() : ExceptionCollector {
```
Comment (eskatos) [inline subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/tooling/BuildServices.kt:48]: :x: please move this to a dedicated `DefaultExceptionCollector.kt` file in the `org.gradle.kotlin.dsl.provider` package

Alongside with the action/closure classes and the NOOP implementation.

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/tooling/BuildServices.kt [hunk 6]
```diff
@@ -0,0 +1,99 @@
...
+    val NOOP_COLLECTOR: ExceptionCollector = object : ExceptionCollector {
+        override fun stop() {}
+        override fun getExceptions(): List<Exception> = emptyList()
+        override fun addException(e: Exception) {}
+        override fun <T> decorate(action: Action<T>): Action<T> = action
+        override fun <T> decorate(closure: Closure<T>): Closure<T> = closure
+    }
+
+    @Suppress("unused")
+    fun createExceptionCollector(): ExceptionCollector {
```
Comment (eskatos) [inline subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/tooling/BuildServices.kt:40]: :x: this can be moved to `org.gradle.kotlin.dsl.provider.BuildServices` and there's no need for a new `.tooling` package nor for a new service provider type

**Review by eskatos — CHANGES_REQUESTED** [review]

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ClassPathModeExceptionCollector.kt (hunk 4 above)
Comment (donat) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ClassPathModeExceptionCollector.kt]: ty

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/tooling/BuildServices.kt (hunk 6 above)
Comment (donat) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/tooling/BuildServices.kt:40]: Thanks for showing me the way. I'm less comfortable with the .kt codebase in gradle/gradle.

**Comment by donat** [comment]
Getting there @eskatos, please take yet another look.

**Review by eskatos — APPROVED** [review]
:100: good stuff!

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

File: subprojects/tooling-api/src/main/java/org/gradle/tooling/model/kotlin/dsl/KotlinDslModelsParameters.java [hunk 7]
```diff
@@ -28,9 +30,9 @@
 
     public static final String CORRELATION_ID_GRADLE_PROPERTY_NAME = "org.gradle.kotlin.dsl.provider.cid";
 
-    public static final String PROVIDER_MODE_SYSTEM_PROPERTY_NAME = "org.gradle.kotlin.dsl.provider.mode";
+    public static final String PROVIDER_MODE_SYSTEM_PROPERTY_NAME = ToolingBuildServices.PROVIDER_MODE_SYSTEM_PROPERTY_NAME;
 
-    public static final String CLASSPATH_MODE_SYSTEM_PROPERTY_VALUE = "classpath";
+    public static final String CLASSPATH_MODE_SYSTEM_PROPERTY_VALUE = ToolingBuildServices.CLASSPATH_MODE_SYSTEM_PROPERTY_VALUE;
 
     public static final String STRICT_CLASSPATH_MODE_SYSTEM_PROPERTY_VALUE = "strict-classpath";
```
Comment (eskatos) [inline subprojects/tooling-api/src/main/java/org/gradle/tooling/model/kotlin/dsl/KotlinDslModelsParameters.java:37]: I would move this one alongside the other ones above, for consistency

File: subprojects/core/src/main/java/org/gradle/internal/service/scopes/DefaultExceptionCollector.java [hunk 8]
```diff
@@ -0,0 +1,109 @@
...
+
+import groovy.lang.Closure;
+import org.gradle.api.Action;
+
+import java.util.Arrays;
+import java.util.Collections;
+import java.util.List;
+import java.util.concurrent.CopyOnWriteArrayList;
+
+public class DefaultExceptionCollector implements ExceptionCollector {
```
Comment (eskatos) [inline subprojects/core/src/main/java/org/gradle/internal/service/scopes/DefaultExceptionCollector.java:27]: I would name this class `KotlinDslExceptionCollector` given it is wired as a service only if the kotlin-dsl specific property is set

File: subprojects/core/src/main/java/org/gradle/internal/service/scopes/ToolingBuildServices.java [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.gradle.internal.service.scopes;
+
+public class ToolingBuildServices {
+
+    public static final String PROVIDER_MODE_SYSTEM_PROPERTY_NAME = "org.gradle.kotlin.dsl.provider.mode";
+    public static final String CLASSPATH_MODE_SYSTEM_PROPERTY_VALUE = "classpath";
```
Comment (eskatos) [inline subprojects/core/src/main/java/org/gradle/internal/service/scopes/ToolingBuildServices.java:22]: I would move those constant declarations to `KotlinDslExceptionCollector`

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
OK, the latest version passed CI. I'll squash my commits and start "test and merge".

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@bot-gradle test and merge
