### PR TITLE
Do not publish stale signature files

### LINKED ISSUE #5136: Stale artifacts should not be published
When publishing a publication, all artifacts are uploaded regardless of whether the task that creates them was skipped.

### Scenario

1. run `gradle publish`
1. change a tasks that creates one of the publication's artifacts to be published to be skipped, e.g. `tasks.withType(Sign) { enabled = false }`.
1. run `gradle publish`

### Expected Behavior

Publishing either fails because the signature artifacts are stale or succeeds without uploading the old signature files.

### Current Behavior

Instead, the stale signature files are uploaded.

### Context

Other tasks, e.g. `jar` might also get skipped in which case publishing should fail.

### PR DESCRIPTION
**Pull request by melix**
This commit fixes the publication of stale signature files:
prior to this change it was possible that a signature generated
in a previous build for a different artifact was uploaded even
if no signature was generated during the build, which would
lead to inconsistent publications.

In addition, it makes it an error to publish something which
doesn't have the main artifact created (or, at least up-to-date)
in this build. In other words, if the task which generates the
main artifact is disabled, it's an error to publish.

Other stale artifacts are going to be ignored.

Fixes #5136

### CODE REVIEW

**Comment by melix** [comment]
The code is a bit convoluted because of a lot of background assumptions, like when errors should be thrown, or the fact that publications can be configured at any time...

File: subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishIssuesIntegTest.groovy [hunk 1]
```diff
@@ -62,4 +62,106 @@ public class IvyPublishIssuesIntegTest extends AbstractIvyPublishIntegTest {
...
+
+        then:
+        file("build/repo/org.gradle/test/1.0/test-1.0-javadoc.jar").exists()
+        file("build/repo/org.gradle/test/1.0/test-1.0-javadoc.jar.sha1").exists()
+        file("build/repo/org.gradle/test/1.0/test-1.0-javadoc.jar.sha256").exists()
+        file("build/repo/org.gradle/test/1.0/test-1.0-javadoc.jar.sha512").exists()
+
+        when:
+        file("build/repo").deleteDir()
+        succeeds "publish", "-PjavadocEnabled=false"
```
Comment (jjohannes) [inline subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishIssuesIntegTest.groovy]: :o: In this example, this leads to illegal module metadata that is published. The metadata still includes the reference to "test-1.0-javadoc.jar" in the "javadocElements" variant.

I am not sure if this was already broken before or if it would have failed, maybe this can be easily fixed by validating that the files exist before writing the module metadata?

If it is more involved, we can also do a follow up PR for 6.2 as well.

Comment (melix) [reply subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishIssuesIntegTest.groovy]: fixed

Comment (jjohannes) [reply subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishIssuesIntegTest.groovy]: Great! That fix was simple than expected. :)
