### PR TITLE
exclusiveContent can be used in build script block

### LINKED ISSUE #12452: exclusiveContent API does not work with Kotlin Gradle DSL
### Expected Behavior 
It does not crash

### Current Behavior
It crashes with this message:

```
Build file '/Users/zsweers/dev/android/personal/CatchUp/build.gradle.kts' line: 34

Cannot mutate content repository descriptor after repository has been used
```

for this snippet in kotlin gradle DSL

```kotlin
buildscript {
  repositories {
    exclusiveContent {
      forRepository {
        // For R8/D8 releases
        maven("https://storage.googleapis.com/r8-releases/raw")
      }
      filter {
        includeModule("com.android.tools", "r8")
      }
    }
  }
}
```

### Context
This API works fine from groovy but does not work when applied via kotlin gradle DSL

### Steps to Reproduce 
Here is a repro branch/project: https://github.com/ZacSweers/CatchUp/tree/z/exlusiveContentBug

Demo commit: https://github.com/ZacSweers/CatchUp/commit/fe2bec6d3bd36f5131b93aa704da5e8f8a42ac08

### Your Environment
Cannot perform a build scan due to failure

### PR DESCRIPTION
**Pull request by bmuskalla**
Fixes #12452

### Context
This adds the plugin repository before we resolve the plugin requests. This allows filters on other repos (e.g. `includeModule`) to be applied to the plugin repository (e.g. as exclude) before the repositories are used.

### CODE REVIEW

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java [hunk 1]
```diff
@@ -41,10 +41,15 @@
...
+    private String repositoryName;
+
+    public DefaultRepositoryContentDescriptor(String repositoryName) {
+        this.repositoryName = repositoryName;
+    }
 
     private void assertMutable() {
         if (locked) {
-            throw new IllegalStateException("Cannot mutate content repository descriptor after repository has been used");
+            throw new IllegalStateException(String.format("Cannot mutate content repository descriptor '%s' after repository has been used", repositoryName));
```
Comment (melix) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java]: :o: You can use good old concatenation here, the VM is smart enough to optimize. Not a big deal since it only occurs in an exception case.

File: subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/DeployedPortalIntegrationSpec.groovy [hunk 2]
```diff
@@ -154,4 +154,41 @@ class DeployedPortalIntegrationSpec extends AbstractPluginIntegrationTest {
...
+                }
+            }
+
+            plugins {
+                id "$HELLO_WORLD_PLUGIN_ID" version "$HELLO_WORLD_PLUGIN_VERSION"
+            }
+        """
+
+        then:
+        succeeds("helloWorld")
```
Comment (melix) [inline subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/DeployedPortalIntegrationSpec.groovy]: :x: I would probably add a test case where resolution fails, otherwise you don't really prove the filter is applied.

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java [hunk 3]
```diff
@@ -86,6 +86,9 @@ public void applyPlugins(final PluginRequests requests, final ScriptHandlerInter
 
         final PluginResolver effectivePluginResolver = wrapInAlreadyInClasspathResolver(classLoaderScope);
 
+        if (!requests.isEmpty()) {
+            addPluginArtifactRepositories(scriptHandler.getRepositories());
```
Comment (melix) [inline subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java]: I'm confused why this isn't a problem already...

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java [hunk 4]
```diff
@@ -141,34 +132,34 @@ public void addFromDifferentLoader(PluginImplementation<?> plugin) {
         }
 
         defineScriptHandlerClassScope(scriptHandler, classLoaderScope, pluginImplsFromOtherLoaders.values());
+        applyLegacyPlugins(target, legacyActualPluginIds);
```
Comment (melix) [inline subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java]: :+1:

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java (hunk 1 above)
Comment (bmuskalla) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java]: Ah interesting, I wasn't even considering performance but rather readability. I'm used to MessageFormat but doing a quick search revealed that we tend to prefer String.format. Any objections?

Comment (melix) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java]: or just use good string concatenation, it will have some sweet advantages when we move to Java 9+ (uses `invokedynamic` internally)

File: subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/DeployedPortalIntegrationSpec.groovy (hunk 2 above)
Comment (bmuskalla) [reply subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/DeployedPortalIntegrationSpec.groovy]: Added another test that fails resolution enforced by the content filters. Please let me know if there are better ways to write such tests without hitting maven central.

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java (hunk 3 above)
Comment (bmuskalla) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java]: I think the main problem is that it interacts with the plugin repository which is only present when you declare these repo filters within the buildscripts block

File: subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/DeployedPortalIntegrationSpec.groovy (hunk 2 above)
Comment (ljacomet) [reply subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/DeployedPortalIntegrationSpec.groovy]: I have example tests for locking that deal with buildscript classpath dependencies and do not require a remote hit. Have a look at `UsingLockingOnNonProjectConfigurationsIntegrationTest` and we can discuss if needed.

Comment (bmuskalla) [reply subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/DeployedPortalIntegrationSpec.groovy]: Thanks!

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java (hunk 1 above)
Comment (bmuskalla) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java]: Ah interesting, wasn't aware of http://openjdk.java.net/jeps/280 Thanks for the pointer

**Comment by bmuskalla** [comment]
@melix Can you have another look please?
