### PR TITLE
Don't exclude test with non-standard `TestSource` directly, but allow filtering on their containing class

### LINKED ISSUE #19352: Gradle JUnit Platform support doesn't support non-standard test descriptors with filter patterns
When Gradle's JUnit Platform support is configured to exclude some test pattern, then all non-standard test descriptors will be ignored, even if they have no relation to the filter.

Take for example

```
test {
  useJUnitPlatform()
  filter {
    excludeTestsMatching "*IT"
  }
}
```

and the [ArchUnit test engine](https://www.archunit.org/userguide/html/000_Index.html#_junit_5). Furthermore, take a test 

```
@AnalyzeClasses(packages = "example")
public class SomeArchTest {
    @ArchTest
    public static final ArchRule example = classes().should().bePublic();
}
```

### Expected Behavior

The specified filter pattern should not exclude the rule `example` from being run, since it's neither in a class ending with `IT` nor a test name ending with `IT`.

### Current Behavior

The rule `example` is skipped.

### Context

I'm trying to solve the following issue on the ArchUnit issue tracker: https://github.com/TNG/ArchUnit/issues/743

### Steps to Reproduce 

I pushed the example here: https://github.com/codecholeric/issue-743
The project shows the described setup, i.e. activates JUnit Platform support, a filter for tests and one JUnit Jupiter and one JUnit ArchUnit test, of which only the Jupiter test is run when the pattern is active.

### Your Environment

Build scan URL: https://gradle.com/s/a2b2afnrgtojy

### Responsible Gradle Code

Within `org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.ClassMethodNameFilter` I can see the following code:

```
private boolean shouldRun(TestDescriptor descriptor) {
    Optional<TestSource> source = descriptor.getSource();
    if (!source.isPresent()) {
        return true;
    }

    if (source.get() instanceof MethodSource) {
        MethodSource methodSource = (MethodSource) source.get();
        return matcher.matchesTest(methodSource.getClassName(), methodSource.getMethodName());
    } else if (source.get() instanceof ClassSource) {
        for (TestDescriptor child : descriptor.getChildren()) {
            if (shouldRun(child)) {
                return true;
            }
        }
        if (descriptor.getChildren().isEmpty()) {
            String className = ((ClassSource) source.get()).getClassName();
            return matcher.matchesTest(className, null)
                    || matcher.matchesTest(className, descriptor.getLegacyReportingName());
        }
    }

    return false;
}
```

ArchUnit however uses a custom `TestSource` for the arch rule `@ArchTest example`, namely a [`FieldSource`](https://github.com/TNG/ArchUnit/blob/main/archunit-junit/junit5/engine-api/src/main/java/com/tngtech/archunit/junit/FieldSource.java). Unfortunately, the fallback behavior will decide to exclude this "unknown" type of source, even though it's not matched by the pattern.

I can try to provide some PR to fix this if you want, but I want to discuss first what the desired behavior is here. And what the reasoning behind the current implementation is. Spontaneously I could for example imagine to examine the sections of the test descriptor as fallback, and apply the pattern to each section? 
Or at least let tests run if their source is unknown instead of just skipping them? That would at least be consistent with the behavior when there is no source present... :thinking: However, applying the pattern to the test descriptor would have the advantage that the DSL would work for descriptors like ArchUnit's rule fields as well, instead of just silently ignoring those tests when applying the pattern.

### PR DESCRIPTION
**Pull request by tresat**
Fixes #19352 

Based on https://github.com/gradle/gradle/pull/19433

### CODE REVIEW

**Comment by tresat** [comment]
@test QFL

**Comment by tresat** [comment]
@bot-gradle test QFL

File: subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformFilteringIntegrationTest.groovy [hunk 1]
```diff
@@ -132,4 +134,114 @@ class JUnitPlatformFilteringIntegrationTest extends JUnitPlatformIntegrationSpec
...
+
+        then:
+        new DefaultTestExecutionResult(testDirectory)
+            .assertTestClassesExecuted('DeclaresTestsAsFieldsNotMethodsTest')
+            .testClass('DeclaresTestsAsFieldsNotMethodsTest')
+            .assertTestCount(1, 0, 0)
+            .assertTestPassed('example')
+    }
+
+    def 'does not exclude tests with a non-standard test source if filter matches field name'() {
```
Comment (marcphilipp) [inline subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformFilteringIntegrationTest.groovy:176]: In case we later go back to this, I think we should document here that this test documents the status quo but it would be desirable to change the behavior if we add support for handling fields.

**Review by marcphilipp — APPROVED** [review]

**Comment by eriwen** [comment]
This is related to https://github.com/gradle/test-retry-gradle-plugin/issues/93 which prevents Kotest from using the test-retry plugin.

File: subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformFilteringIntegrationTest.groovy (hunk 1 above)
Comment (tresat) [reply subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformFilteringIntegrationTest.groovy:176]: I'll add a note before I merge this.  Thanks for the reviews!

**Comment by tresat** [comment]
@bot-gradle test and merge
