### PR TITLE
Restore binary compatibility with the protobuf plugin

### LINKED ISSUE #15500: Gradle 6.8 breaks protobuf plugin
Gradle 6.8 seems to have removed a method that the protobuf plugin [relies on](https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/KtDslCompatibilityUtils.java).

This leads to the following error:

``` 
java.lang.NoSuchMethodError: 'org.gradle.api.NamedDomainObjectContainer org.gradle.kotlin.dsl.NamedDomainObjectContainerExtensionsKt.invoke(org.gradle.api.NamedDomainObjectContainer, kotlin.jvm.functions.Function1)'
        at com.google.protobuf.gradle.KtDslCompatibilityUtils.configureNamedDomainObjectContainer(KtDslCompatibilityUtils.java:32)
        at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1.invoke(ProtobufConfiguratorExts.kt:90)
        at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1.invoke(ProtobufConfiguratorExts.kt)
        at org.gradle.kotlin.dsl.KotlinClosure1.doCall(GroovyInteroperability.kt:97)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:148)
        at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:142)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:91)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:38)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:103)
        at org.gradle.util.ConfigureUtil$configure.call(Unknown Source)
        at com.google.protobuf.gradle.ProtobufConfigurator.plugins(ProtobufConfigurator.groovy:88)
        at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt.plugins(ProtobufConfiguratorExts.kt:89)
        at Build_gradle$4.invoke(build.gradle.kts:53)
        at Build_gradle$4.invoke(build.gradle.kts:6)
        at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt.protobuf(ProtobufConfiguratorExts.kt:30)

```

### PR DESCRIPTION
**Pull request by bamboo**
By reintroducing `NamedDomainObjectContainer<T>.invoke(NamedDomainObjectContainerScope<T>.() -> Unit)`, removed in 593001e74f21a67ecc8d6f6c6174818f02eab007, as a hidden extension.

Fixes #15500

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt [hunk 1]
```diff
@@ -41,6 +41,21 @@ inline operator fun <T : Any, C : NamedDomainObjectContainer<T>> C.invoke(
...
 
 
+/**
+ * Allows the container to be configured via an augmented DSL.
+ *
+ * @param configuration The expression to configure this container with
+ * @return The container.
+ */
+@Suppress("nothing_to_inline")
+@Deprecated(level = DeprecationLevel.HIDDEN, message = "For backward compatibility only")
```
Comment (eskatos) [inline subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt:51]: ❓ Shouldn't we set a removal version and nag? We don't want to carry over such members indefinitely.

Comment (eskatos) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt:51]: See my suggestion in https://github.com/gradle/gradle/pull/15514

**Comment by bamboo** [comment]
@bot-gradle test this

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt (hunk 1 above)
Comment (bamboo) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt:53]: Merged. Thanks!

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt [hunk 2]
```diff
@@ -41,6 +43,26 @@ inline operator fun <T : Any, C : NamedDomainObjectContainer<T>> C.invoke(
...
+inline operator fun <T : Any, C : NamedDomainObjectContainer<T>> C.invoke(
+    configuration: NamedDomainObjectContainerScope<T>.() -> Unit
+): C = apply {
+    DeprecationLogger.deprecateInvocation("NamedDomainObjectContainer<T>.invoke(kotlinLambda)")
+        .withAdvice("Recompile your plugin against Gradle >= 6.8")
+        .willBeRemovedInGradle8()
+        .undocumented()
```
Comment (big-guy) [inline subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt:60]: Can we add a short note in the upgrade guide and link to that here instead of adding an undocumented deprecation?

Comment (bamboo) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt:60]: It feels like undue cost to me.

Comment (bamboo) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt:60]: I take it back. This will start showing up for protobuf plugin users so it makes sense to have an explanation somewhere.

Comment (bamboo) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt]: Done. PTAL, @big-guy.

**Comment by bamboo** [comment]
@bot-gradle test this

File: subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy [hunk 3]
```diff
@@ -321,11 +321,16 @@ abstract class AbstractSmokeTest extends Specification {
...
+            assert !containsDeprecationWarning(line), "Found an unexpected deprecation warning on line ${lineIndex + 1}: $line"
         }
         assert remainingWarnings.empty, "Expected ${remainingWarnings.size()} deprecation warnings, found ${foundDeprecations} deprecation warnings:\n${remainingWarnings.collect { " - $it" }.join("\n")}"
     }
 
+    private static boolean containsDeprecationWarning(String line) {
+        line.contains("has been deprecated and is scheduled to be removed in Gradle") ||
+            line.contains("has been deprecated. This is scheduled to be removed in Gradle")
+    }
+
```
Comment (eskatos) [inline subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy:333]: 👍

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt [hunk 4]
```diff
@@ -41,6 +43,26 @@ inline operator fun <T : Any, C : NamedDomainObjectContainer<T>> C.invoke(
...
+ */
+@Suppress("nothing_to_inline")
+@Deprecated(level = DeprecationLevel.HIDDEN, message = "For backward compatibility only")
+inline operator fun <T : Any, C : NamedDomainObjectContainer<T>> C.invoke(
+    configuration: NamedDomainObjectContainerScope<T>.() -> Unit
+): C = apply {
+    DeprecationLogger.deprecateInvocation("NamedDomainObjectContainer<T>.invoke(kotlin.Function1)")
+        .withAdvice("Recompile your plugin against Gradle >= 6.8")
+        .willBeRemovedInGradle8()
+        .withUpgradeGuideSection(6, "using_NamedDomainObjectContainer_invoke_kotlin_Function1")
```
Comment (eskatos) [inline subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt:60]: 👍

**Review by eskatos — APPROVED** [review]
