### PR TITLE
fix init split java library

### LINKED ISSUE #34165: gradle init - split Java library project doesn't build right away
### Current Behavior

When I create a project with
`gradle init --type java-library --project-name example --split-project --package org.example.gradleinit --dsl kotlin`

and run a subsequent `gradle build`, the build fails with

```
* What went wrong:
Execution failed for task ':lib:compileJava'.
> Could not resolve all files for configuration ':lib:compileClasspath'.
   > Cannot resolve external dependency org.apache.commons:commons-math3:3.6.1 because no repositories are defined.
     Required by:
         project :lib
   > Cannot resolve external dependency com.google.guava:guava:32.1.3-jre because no repositories are defined.
     Required by:
         project :lib
```

Reason being, apparently, lib/build.gradle.kts is missing

```
plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("buildlogic.java-library-conventions") // <--- THIS
}
```

This *does not* happen with --no-split-project (As the project structure is different).

### Expected Behavior

The build succeeds directly with the generated example project.

### Context (optional)

_No response_

### Self-contained Reproducer Project

The template can be created by calling gradle init.

### Gradle version

7.6.6, 8.14.3

### Build scan URL (optional)

_No response_

### Your Environment (optional)

Devuan Linux

```
$ uname -a
Linux devuanPc 6.1.0-37-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.140-1 (2025-05-22) x86_64 GNU/Linux
```

```
$ gradle --version

------------------------------------------------------------
Gradle 8.14.3
------------------------------------------------------------

Build time:    2025-07-04 13:15:44 UTC
Revision:      e5ee1df3d88b8ca3a8074787a94f373e3090e1db

Kotlin:        2.0.21
Groovy:        3.0.24
Ant:           Apache Ant(TM) version 1.10.15 compiled on August 25 2024
Launcher JVM:  21.0.7 (Eclipse Adoptium 21.0.7+6-LTS)
Daemon JVM:    /home/uvok/Downloads/jdk-21.0.7+6 (no JDK specified, using current Java home)
OS:            Linux 6.1.0-37-amd64 amd64
```

### PR DESCRIPTION
**Pull request by reinsch82**
Fixes #34165

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/software/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitPluginIntegrationTest.groovy [hunk 1]
```diff
@@ -60,6 +61,18 @@ class BuildInitPluginIntegrationTest extends AbstractInitIntegrationSpec {
...
     }
 
+    @SuppressWarnings('GroovyAssignabilityCheck')
+    def "init can be run with arguments #args and built afterwards"() {
+        expect:
+        succeeds(args)
+        succeeds 'build'
+
+        where:
+        args << [
```
Comment (ghale) [inline platforms/software/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitPluginIntegrationTest.groovy]: ❓ Why is this an iteration?  Did you intend to add more?  I'd suggest we either add more iterations here or collapse it into the test and change the name to be more descriptive.  It's a little awkward as it is now.

**Review by ghale — APPROVED** [review]
This looks fine, although I think we could clean up the test a little.  But that doesn't need to block the fix.
