### PR TITLE
Reuse cached content when hashing scripts

### LINKED ISSUE #7992: Old version of build.gradle used
Unfortunately I have no idea how to reproduce this, but I just had a very strange behavior that I feel the urge to report anyway.

I modified a build script and wanted to build, but Gradle uses the old version of the build script.
I can see this from the build result and also from debugging into relevant code and seeing that the script is the old version.

Neither adding `--recompile-scripts`, nor deleting `<project>/.gradle` or restarting the daemon had any effect, it was always the old version of the script used.

The only way to make it use the new version of the script was to modify it. I added an arbitrary space character, then the new version was used. Now if I remove that space character again, again the old version of the build script is used, so I guess it is something in `~/.gradle` that is borked and I find no way to fix it besides maybe deleting things in `~/.gradle` which I didn't do yet to maybe be able to debug the problem further if you can tell me where to look at.

### PR DESCRIPTION
**Pull request by oehme**
This ensures that the hash and the compiled script are taken from
the same source code and neither picks up any changes that the user
does during the build.

Fixes #7992

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptSourceHasher.java [hunk 1]
```diff
@@ -37,22 +37,34 @@ public DefaultScriptSourceHasher(FileHasher fileHasher) {
     }
 
     @Override
-    public HashCode hash(ScriptSource scriptSource) {
+    public HashCode
+    hash(ScriptSource scriptSource) {
```
Comment (marcphilipp) [inline subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptSourceHasher.java]: This line break doesn't look like it was intended, was it?

File: subprojects/core/src/test/groovy/org/gradle/groovy/scripts/internal/DefaultScriptSourceHasherTest.groovy [hunk 2]
```diff
@@ -44,23 +49,47 @@ class DefaultScriptSourceHasherTest extends Specification {
...
+        }
+        def script = Stub(ScriptSource) {
+            getResource() >> resource
+        }
+
+        when:
+        def result = scriptHasher.hash(script)
+
+        then:
+        result == HashCode.fromString("6448f0e21a54bd0519552bd538b03fef")
```
Comment (marcphilipp) [inline subprojects/core/src/test/groovy/org/gradle/groovy/scripts/internal/DefaultScriptSourceHasherTest.groovy]: Can we make it more obvious that this is the hash code of `alma`?

File: subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptSourceHasher.java (hunk 1 above)
Comment (oehme) [reply subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptSourceHasher.java]: Done

File: subprojects/core/src/test/groovy/org/gradle/groovy/scripts/internal/DefaultScriptSourceHasherTest.groovy (hunk 2 above)
Comment (oehme) [reply subprojects/core/src/test/groovy/org/gradle/groovy/scripts/internal/DefaultScriptSourceHasherTest.groovy]: Done
