### PR TITLE
Prohibit BuildServiceProviders in configuration cache fingerprint

### LINKED ISSUE #22337: Disallow BuildServices to be used as inputs to ValueSources obtained at configuration time
A `ValueSource` can take parameters in the form of Properties. A `BuildService` is obtained as a `Provider`. This `Provider` can be wired to the input `Property` of the ValueSource. It works well without the configuration cache. However, when the configuration cache is enabled and the ValueSource is obtained at the configuration time, things go wrong. The cache cannot be reused, as the fingerprinting routine cannot restore the `BuildService`; the build fails with a cryptic exception.

### Expected Behavior
Either of two options are expected:
1. If Gradle is not going to support this use case: provide an error with a clear message that this use is unsupported, preferably when storing the cache
2. Otherwise, this should just work, and the service instance should be available for the ValueSource computation.

### Current Behavior
The build fails when trying to check the cache validity:
```
org.gradle.api.GradleException: Could not load the value of field `__service__` of `ServiceValueSource$Params` bean found in field `parameters` of `org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$DefaultObtainedValue` bean found in field `obtainedValue` of `org.gradle.configurationcache.fingerprint.ConfigurationCacheFingerprint$ValueSource` bean found in Gradle runtime.
  	at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:108)
  	at org.gradle.configurationcache.serialization.beans.BeanPropertyReader.readStateOf(BeanPropertyReader.kt:67)
  	at org.gradle.configurationcache.serialization.codecs.BeanCodec.readBeanOf(BeanCodec.kt:72)
  	at org.gradle.configurationcache.serialization.codecs.BeanCodec.decode(BeanCodec.kt:47)
  	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$decodeLoop$1.invokeSuspend(Combinators.kt:165)
  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
  	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1.decodeLoop(Combinators.kt:166)
  	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1.decode(Combinators.kt:130)
  	at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
  	at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:259)
  	at org.gradle.configurationcache.fingerprint.ConfigurationCacheFingerprintChecker.checkBuildScopedFingerprint(ConfigurationCacheFingerprintChecker.kt:58)
  	at org.gradle.configurationcache.fingerprint.ConfigurationCacheFingerprintController.checkBuildScopedFingerprint(ConfigurationCacheFingerprintController.kt:243)
  	at org.gradle.configurationcache.DefaultConfigurationCache$checkBuildScopedFingerprint$1.invokeSuspend(DefaultConfigurationCache.kt:461)
  	at org.gradle.configurationcache.DefaultConfigurationCache$readFingerprintFile$1$1.invokeSuspend(DefaultConfigurationCache.kt:480)
  	at org.gradle.configurationcache.ConfigurationCacheIO$withReadContextFor$1$1$1$1.invokeSuspend(ConfigurationCacheIO.kt:248)
  	at org.gradle.configurationcache.serialization.RunningKt$runReadOperation$2.invokeSuspend(Running.kt:34)
  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
  	at org.gradle.configurationcache.serialization.RunningKt.runToCompletion(Running.kt:56)
  	at org.gradle.configurationcache.serialization.RunningKt.runReadOperation(Running.kt:33)
  	at org.gradle.configurationcache.ConfigurationCacheIO.withReadContextFor$configuration_cache(ConfigurationCacheIO.kt:247)
  	at org.gradle.configurationcache.DefaultConfigurationCache.readFingerprintFile(DefaultConfigurationCache.kt:478)
  	at org.gradle.configurationcache.DefaultConfigurationCache.checkBuildScopedFingerprint(DefaultConfigurationCache.kt:459)
  	at org.gradle.configurationcache.DefaultConfigurationCache.checkFingerprintAgainstLoadedProperties(DefaultConfigurationCache.kt:441)
  	at org.gradle.configurationcache.DefaultConfigurationCache.checkFingerprint(DefaultConfigurationCache.kt:429)
  	at org.gradle.configurationcache.DefaultConfigurationCache.access$checkFingerprint(DefaultConfigurationCache.kt:53)
  	at org.gradle.configurationcache.DefaultConfigurationCache$checkFingerprint$1.invoke(DefaultConfigurationCache.kt:278)
  	at org.gradle.configurationcache.DefaultConfigurationCache$checkFingerprint$1.invoke(DefaultConfigurationCache.kt:271)
  	at org.gradle.configurationcache.ConfigurationCacheRepository$StoreImpl$useForStateLoad$2.invoke(ConfigurationCacheRepository.kt:164)
  	at org.gradle.configurationcache.ConfigurationCacheRepository$StoreImpl$useForStateLoad$2.invoke(ConfigurationCacheRepository.kt:163)
  	at org.gradle.configurationcache.ConfigurationCacheRepository$withExclusiveAccessToCache$1.create(ConfigurationCacheRepository.kt:244)
  	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:90)
  	at org.gradle.cache.internal.DefaultCacheAccess.withFileLock(DefaultCacheAccess.java:191)
  	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:188)
  	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:209)
  	at org.gradle.configurationcache.ConfigurationCacheRepository.withExclusiveAccessToCache(ConfigurationCacheRepository.kt:242)
  	at org.gradle.configurationcache.ConfigurationCacheRepository.access$withExclusiveAccessToCache(ConfigurationCacheRepository.kt:46)
  	at org.gradle.configurationcache.ConfigurationCacheRepository$StoreImpl.useForStateLoad(ConfigurationCacheRepository.kt:163)
  	at org.gradle.configurationcache.DefaultConfigurationCache.checkFingerprint(DefaultConfigurationCache.kt:271)
  	at org.gradle.configurationcache.DefaultConfigurationCache.determineCacheAction(DefaultConfigurationCache.kt:221)
  	at org.gradle.configurationcache.DefaultConfigurationCache.initializeCacheEntry(DefaultConfigurationCache.kt:114)
  	at org.gradle.configurationcache.ConfigurationCacheBuildTreeLifecycleControllerFactory.createRootBuildController(ConfigurationCacheBuildTreeLifecycleControllerFactory.kt:54)
  	at org.gradle.composite.internal.DefaultRootBuildState.<init>(DefaultRootBuildState.java:73)
  	at org.gradle.composite.internal.BuildStateFactory.createRootBuild(BuildStateFactory.java:66)
  	at org.gradle.composite.internal.DefaultIncludedBuildRegistry.createRootBuild(DefaultIncludedBuildRegistry.java:91)
...
Caused by: java.lang.IllegalArgumentException: Could not find build ':'
  	at org.gradle.composite.internal.DefaultIncludedBuildRegistry.getBuild(DefaultIncludedBuildRegistry.java:147)
  	at org.gradle.configurationcache.serialization.codecs.BuildServiceProviderCodec.buildServiceRegistryOf(ProviderCodecs.kt:188)
  	at org.gradle.configurationcache.serialization.codecs.BuildServiceProviderCodec.decode(ProviderCodecs.kt:183)
  	at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
  	at org.gradle.configurationcache.serialization.codecs.FixedValueReplacingProviderCodec.decodeValue(ProviderCodecs.kt:134)
  	at org.gradle.configurationcache.serialization.codecs.FixedValueReplacingProviderCodec.decodeProvider(ProviderCodecs.kt:116)
  	at org.gradle.configurationcache.serialization.codecs.PropertyCodec.decode(ProviderCodecs.kt:269)
  	at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
  	at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:259)
  	at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:102)
```

### Context
My goal was to invalidate the configuration cache with the value obtained through the BuildService (with a side effect): the service is starting a web server on a random port, the URL of the server is used to configure some tasks. The build service then stops the server when closed.

The use case is not very compelling, as the lifecycle of the service is unclear in case the cache is actually invalidated - is the service used at fingerprint check time going to be discarded?

### Steps to Reproduce 
See #22338.

### PR DESCRIPTION
**Pull request by mlopatkin**
Fixes #22337

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy [hunk 1]
```diff
@@ -513,49 +515,206 @@ class ConfigurationCacheBuildServiceIntegrationTest extends AbstractConfiguratio
...
+        """)
+
+        when:
+        configurationCacheFails()
+
+        then:
+        outputContains("Configuration cache entry discarded with 1 problem.")
+        problems.assertFailureHasProblems(failure) {
+            totalProblemsCount = 1
+            withProblem("Build file 'build.gradle': " +
```
Comment (bamboo) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy:642]: 👍

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt [hunk 2]
```diff
@@ -427,7 +427,7 @@ class DefaultConfigurationCache internal constructor(
     fun cacheFingerprintWriterContextFor(outputStream: OutputStream): DefaultWriteContext {
         val (context, codecs) = cacheIO.writerContextFor(outputStream, "fingerprint")
         return context.apply {
-            push(IsolateOwner.OwnerHost(host), codecs.userTypesCodec())
+            push(IsolateOwner.OwnerHost(host), codecs.fingerprintTypesCodec())
```
Comment (bamboo) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt:430]: 👍

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/UnsupportedTypesCodecs.kt [hunk 3]
```diff
@@ -135,3 +141,24 @@ fun BindingsBuilder.unsupportedTypes() {
...
+object UnsupportedFingerprintBuildServiceProviderCodec : Codec<BuildServiceProvider<*, *>> {
+    override suspend fun WriteContext.encode(value: BuildServiceProvider<*, *>) {
+        logUnsupported("serialize",
+            documentationSection = DocumentationSection.NotYetImplementedBuildServiceInFingerprint,
+            unsupportedThings = {
+                text(" BuildServiceProvider of service ")
+                reference(value.serviceDetails.implementationType)
+                text(" with name ")
+                reference(value.serviceDetails.name)
+                text(" used at configuration time")
```
Comment (bamboo) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/UnsupportedTypesCodecs.kt:156]: 🟡 I think _used at configuration time_ is too generic and it might become a source of confusion but I don't have a better suggestion right now.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt [hunk 4]
```diff
@@ -252,6 +275,33 @@ class Codecs(
...
+     * Returns a Codec for Provider implementations supported in the fingerprinting context. For example, BuildServiceProviders are not supported.
+     */
+    private
+    fun nestedProviderCodecForFingerprint(
+        valueSourceProviderFactory: ValueSourceProviderFactory,
+        flowProviders: FlowProviders
+    ) = FixedValueReplacingProviderCodec(
+        ValueSourceProviderCodec(valueSourceProviderFactory),
+        UnsupportedFingerprintBuildServiceProviderCodec,
+        FlowProvidersCodec(flowProviders)
```
Comment (bamboo) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt:302]: I think we should disallow flow providers as well.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt [hunk 5]
```diff
@@ -119,103 +119,129 @@ class Codecs(
...
+        }
     }
 
-    fun userTypesCodec(): Codec<Any?> = userTypesBindings.append {
+    private
+    fun Bindings.completeWithReentrantBeanCodec() = append {
         // This protects the BeanCodec against StackOverflowErrors but
         // we can still get them for the other codecs, for instance,
         // with deeply nested Lists, deeply nested Maps, etc.
+        // The reentrant codec is stateful, and cannot be cached because of it.
```
Comment (bamboo) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt:232]: 👍

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt [hunk 6]
```diff
@@ -119,103 +119,129 @@ class Codecs(
...
-        bind(unsupported<Externalizable>(NotYetImplementedJavaSerialization))
-        bind(JavaObjectSerializationCodec(javaSerializationEncodingLookup))
-
-        bind(BeanSpecCodec)
+    val userTypesBindings: Bindings
+    private
+    val fingerprintUserTypesBindings: Bindings
+
+    init {
+        fun makeUserTypeBindings(providersBlock: BindingsBuilder.() -> Unit) = Bindings.of {
```
Comment (bamboo) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt:127]: 🎨 I think it would be cleaner to have this function in a companion object and use field initializers instead of `init`.

Comment (mlopatkin) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt:127]: I decided to go with the nested function, because it captures ~20 constructor arguments. Without it it either becomes 20-parameter function or we have to store all services passed to constructor in the `Codecs` instance, even though we only need them once.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt (hunk 4 above)
Comment (mlopatkin) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt:302]: I don't think you can have `RequestedTasksResultProvider` as part of the fingerprint, as it cannot be isolated at configuration time (yet?), but why not, I can add it just in case

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/UnsupportedTypesCodecs.kt (hunk 3 above)
Comment (mlopatkin) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/UnsupportedTypesCodecs.kt:156]: I don't think it is possible to hit this without going through a ValueSource, but I might be missing something here, so I went with a generic term. "Fingerprinting" would be more precise, but we don't have it as a user-facing concept,AFAIK.

**Comment by mlopatkin** [comment]
@bot-gradle test ACC

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt (hunk 4 above)
Comment (bamboo) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt]: Thanks, Mike!

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt (hunk 6 above)
Comment (bamboo) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt:127]: I see 😅

**Review by bamboo — APPROVED** [review]
🎉

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

File: subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc [hunk 7]
```diff
@@ -1094,3 +1094,13 @@ include::sample[dir="snippets/configurationCache/topLevel/kotlin",files="build.g
 <2> Define the variable in a smaller scope.
 
 See link:{gradle-issues}22879[gradle/gradle#22879].
+
+[[config_cache:not_yet_implemented:build_services_in_fingerprint]]
+=== Using build services to invalidate the configuration cache
+
+Currently, it is not possible to use a `BuildServiceProvider` or provider derived of it with `map` or `flatMap` as a parameter for the `ValueSource`, if the value of the `ValueSource` is accessed at configuration time.
```
Comment (hythloda) [inline subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc:1101]: 💄 
```suggestion
Currently, it is impossible to use a `BuildServiceProvider` or provider derived from it with `map` or `flatMap` as a parameter for the `ValueSource`, if the value of the `ValueSource` is accessed at configuration time.
```

File: subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc [hunk 8]
```diff
@@ -1094,3 +1094,13 @@ include::sample[dir="snippets/configurationCache/topLevel/kotlin",files="build.g
...
+The same applies such `ValueSource` is obtained in a task that executes as part of configuration phase, for example tasks of the `buildSrc` build or included builds contributing plugins.
```
Comment (hythloda) [inline subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc:1102]: 💄 
```suggestion
The same applies such as `ValueSource` is obtained in a task that executes as part of the configuration phase, for example, tasks of the `buildSrc` build or included builds contributing plugins.
```

Comment (mlopatkin) [reply subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc:1102]: @hythloda thank you for the review, I'll apply your suggestions in a follow-up PR.

Regarding this one, I missed a conjunction here, and intended to write "The same applies when such a ValueSource". Is it correct?
