### PR TITLE
Fix concurrency issue with ZipFileTree class

### LINKED ISSUE #22685: Race condition in org.gradle.api.internal.file.archive.ZipFileTree.DetailsImpl#getFile
The [`org.gradle.api.internal.file.archive.ZipFileTree.DetailsImpl#getFile`](https://github.com/gradle/gradle/blob/3a78b35de8a1aa2f169dae38006986d89385976f/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipFileTree.java#L161) method contains a race condition problem when it's accessed from two or more concurrent tasks accessing the same archive

```mermaid
stateDiagram-v2
  [*] --> Task1
  Task1 --> !fileExists
  !fileExists --> expandFile
  expandFile --> useFile

  [*] --> Task2
  Task2 --> fileExists
  fileExists --> useFile
```

### Expected Behavior
All the accessing tasks should get properly expanded to a temporary directory file from an archive

### Current Behavior
While the `Task1` doesn't finished to expand the file, `Task2` may decide that the file already exists and read it incorrectly

### Context
The issue causes problems with configuration cache in the [Kotlin project](https://github.com/JetBrains/kotlin/) due to ability to execute tasks from the same project in parallel.
https://ge.jetbrains.com/s/g2cmfvr55ckpg/failure#1

### Steps to Reproduce 

1. Checkout the [Kotlin project](https://github.com/JetBrains/kotlin/) at the b6eb2b362014446b68def84037a1e186f3e81b14 revision
2. Invoke `./gradlew install --configuration-cache`
3. Make changes to any `.kt` files under the `libraries/tools/kotlin-gradle-statistics/src/common` and `libraries/tools/kotlin-gradle-plugin/src/common` directories
4. Invoke `./gradlew install --configuration-cache`
5. Repeat steps 3 and 4 until you get a build failure caused by `ArrayIndexOutOfBoundsException`

### PR DESCRIPTION
**Pull request by tresat**
When multiple threads are using the getFile method, it is possible for thread 2 to begin reading the file before thread 1 has finished expanding it from the zip.

This adds test to reproduce to issue reliably (I think), and fixes the issue by using a cache to mangae the expansion of zip files using this class's inner DetailsImpl.

This should allow for correct operation, even if multiple Gradle processes are working with the same archive file; or if multiple tasks in different projects work with the file simultaneously.

This fixes both `ZipFileTree` and `TarFileTree`.

Fixes #22685

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java [hunk 1]
```diff
@@ -21,10 +21,36 @@
...
+
 public abstract class AbstractArchiveFileTree implements FileSystemMirroringFileTree, TaskDependencyContainer {
+    private static final String EXPANSION_CACHE_KEY = "compressed-file-expansion";
+    private static final String EXPANSION_CACHE_NAME = "Compressed Files Expansion Cache";
+
+    protected final PersistentCache expansionCache;
+
+    protected AbstractArchiveFileTree(CacheFactory cacheFactory, GradleUserHomeDirProvider userHomeDirProvider) {
+        CacheScopeMapping cacheScopeMapping = new DefaultCacheScopeMapping(new GlobalCacheDir(userHomeDirProvider).getDir(), GradleVersion.current());
+        CacheRepository cacheRepository = new DefaultCacheRepository(cacheScopeMapping, cacheFactory);
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java:47]: I think this is injectable as a service in the daemon. It isn't (or wasn't) available in the worker process, so instead of carrying around `CacheFactory` and `GradleUserHomeDirProvider`, I think you should be able to get an existing `CacheRepository` service.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java [hunk 2]
```diff
@@ -21,10 +21,36 @@
...
+        this.expansionCache = cacheRepository.cache(EXPANSION_CACHE_KEY)
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java:48]: We may want to consider making this a cross-version cache so that once we've extracted a given archive, we don't extract it again with a different version of Gradle.

**Review by big-guy — COMMENTED** [review]
I haven't looked at everything, but I realize now I may have sent you down a troublesome path.

Using the `PersistentCache` introduces a sync point for all extracted archives. We can only extract one file at a time. I don't know if we're introducing a perf overhead by locking the cache, extracting a single file and unlocking. I made the suggestion to move this locking outside of the visitor, but I think this might just move the problem around so that we're now locking while extracting the entire archive vs a single file.

Since we are using a single cache for everything, the subdirectories under the cache are important. This PR re-uses the same convention as the existing code (file name + hash of file), but we could make this just the hash of the file so we don't need to extract the same contents if only the file name is different. We could also make this cache cross-version so we don't need to re-extract an archive if the Gradle version changes.

With the cache shared across builds and projects vs being inside buildDir, this could lead to a few weird things due to the shared expanded directory.

Imagine you had two projects that did something like:
```
// some task in project A
tree = zipTree("/path/to/the.zip")
tree.visit { file ->
    if (file.name == "foo") {
        file.text = "foo"
    }
}

// some task in project B
tree = zipTree("/path/to/the.zip")
tree.visit { file ->
    if (file.name == "foo") {
        file.text = "not foo"
    }
}
```

With existing behavior, this produces two separate expand directories where `foo` has the contents "foo" in project A and "not foo" in project B. 
With this PR, the contents of `foo` would depend on which task ran first, I think.

There might be other things that you can do with the file visitor that might subtly break things. e.g., you can call `stopVisiting()` in a file visitor and the contents of the expanded directory will be incomplete. Is there some way that someone would get the root directory of the expanded dir and expect the incomplete extraction?

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java (hunk 1 above)
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java:47]: I'll give this a try.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java (hunk 2 above)
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java:48]: I don't think this matters, now that we'll be moving it to be per project under the buildDir.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java [hunk 3]
```diff
@@ -21,10 +21,36 @@
...
+                .withDisplayName(EXPANSION_CACHE_NAME)
+                .withLockOptions(mode(FileLockManager.LockMode.OnDemand))
```
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java:50]: I don't think this matters, now that we'll be moving it to be per project under the buildDir.

**Comment by tresat** [comment]
> We can only extract one file at a time. I don't know if we're introducing a perf overhead by locking the cache, extracting a single file and unlocking. I made the suggestion to move this locking outside of the visitor, but I think this might just move the problem around so that we're now locking while extracting the entire archive vs a single file.

Do we need to be able to extract multiple files simultaneously?  This seems like it typically wouldn't offer any performance gains, as it would be limited by the file system.

> but we could make this just the hash of the file so we don't need to extract the same contents if only the file name is different.

OK

> We could also make this cache cross-version so we don't need to re-extract an archive if the Gradle version changes.

OK

> With the cache shared across builds and projects vs being inside buildDir...

I'll change this to use a per-project cache under the buildDir then.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTreeElement.java [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+    }
+
+    /**
+     * Returns a safe name for the name of a file contained in the archive.
+     * @see org.gradle.util.internal.ZipSlip#safeZipEntryName(String)
+     */
+    protected abstract String safeEntryName();
+
+    private File expandToCache(String entryName) {
+        return expansionCache.useCache(() -> {
```
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTreeElement.java]: I locked per archive, but doubled down on the new type - there was even more common functionality in there once I took a closer look.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/persistent-cache/src/main/java/org/gradle/cache/scopes/ProjectScopedCache.java [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+package org.gradle.cache.scopes;
+
+import org.gradle.internal.service.scopes.Scopes;
+import org.gradle.internal.service.scopes.ServiceScope;
+
+/**
+ * Factory for creating project scoped caches. These typically live under the ~/build directory of a project.
+ */
+@ServiceScope(Scopes.Project.class)
+public interface ProjectScopedCache extends ScopedCache {
```
Comment (tresat) [inline subprojects/persistent-cache/src/main/java/org/gradle/cache/scopes/ProjectScopedCache.java:26]: Shouldn't this fail `sanityCheck` without an `@Incubating` annotation and a `since`?

File: subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestInMemoryCacheFactory.java [hunk 6]
```diff
@@ -149,7 +149,10 @@ public <T> T useCache(Factory<? extends T> action) {
         @Override
         public void useCache(Runnable action) {
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestInMemoryCacheFactory.java:150]: ❗ I'm pretty sure not synchronizing here was a bug, which I noticed when my zip file tree unit (not integration) tests suddenly started breaking.

Seems like the `useCache(Runnable action)` overload here would need the same internal synchronization logic as the other overload above it, for the same reason.

I haven't noticed this breaking any other unrelated tests yet, fortunately.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test and merge
