### PR TITLE
Version catalog builders should not accept multiple `toml` files

### LINKED ISSUE #20383: Version catalog builders should not accept multiple `toml` files
Meanwhile reproducing #20282, a new issue came up: multiple `toml` files can be imported into a single version catalog.
@ljacomet affirmed that this was the old behavior of the version catalog, and now it should not accept any form of multi-file import.

### Expected Behavior
Version catalog definitions should not accept more than one `toml` file import.

### Current Behavior
The issue relates to calling the `from` method with multiple files.
Calling the method multiple times is yielding the expected behavior.

### Steps to Reproduce 
(An all-in-one gist is here: https://gist.github.com/hegyibalint/472f9968df054b514ed855dbce322a41)
The core issue is the following, when applied in a `settings.gradle[.kts]`:
```kotlin
dependencyResolutionManagement {
    repositories { mavenCentral() }
    versionCatalogs {
        create("testLibs") {
            from(files("gradle/a.versions.toml", "gradle/b.versions.toml"))
        }
    }
}
```

### Your Environment
```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.15 (Oracle Corporation 11.0.15+3)
OS:           Linux 5.17.1-zen1-1-zen amd64
```

### PR DESCRIPTION
**Pull request by hegyibalint**
Fixes #20383

### CODE REVIEW

**Comment by hegyibalint** [comment]
@bot-gradle test RFM

**Comment by hegyibalint** [comment]
There is a question hanging out there: should we fail if the `from` notation is called with empty files?

The current behavior is to do so, but it might be too defensive.

**Comment by hegyibalint** [comment]
@bot-gradle test RFM

**Comment by hegyibalint** [comment]
@bot-gradle test RFM

**Comment by hegyibalint** [comment]
@bot-gradle test RFM

File: subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/catalog/problems/VersionCatalogErrorMessages.groovy [hunk 1]
```diff
@@ -485,4 +497,59 @@ ${solution}
...
+"""
+        }
+
+        @Override
+        String build() {
+            """${intro}  - Problem: In version catalog ${catalog}, no files are resolved to be imported.
+
+    Reason: The imported dependency doesn't resolve into any file.
+
+    Possible solution: Check if the import statement, it should be resolvable into a file.
```
Comment (ljacomet) [inline subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/catalog/problems/VersionCatalogErrorMessages.groovy:513]: Looks like an extra "if" in there

File: subprojects/docs/src/docs/userguide/troubleshooting/version_catalog_problems.adoc [hunk 2]
```diff
@@ -163,3 +163,48 @@ This error indicates that an alias builder was created, but never registered wit
 you didn't call `.version()` or `.withoutVersion()` on the builder.
 
 The solution is to call whichever version method is appropriate.
+
+[[too_many_import_invocation]]
+== Too many import invocations
+
+This error indicates that an import statement (e.g. link:{javadocPath}/org/gradle/api/initialization/dsl/VersionCatalogBuilder.html#from-java.lang.Object-[from(Object notation)]) was called more than once.
+
+A version catalog can only be imported from a single source. To prevent the import of multiple sources, some methods will throw an exception when called more than once.
```
Comment (ljacomet) [inline subprojects/docs/src/docs/userguide/troubleshooting/version_catalog_problems.adoc:172]: Please stick to a sentence per line in docs.

**Review by ljacomet — CHANGES_REQUESTED** [review]
Looks good overall, a few clean up items though:

**Review by ljacomet — APPROVED** [review]
LGTM!

One thing to add for the release is an entry in the upgrade guide as this ends up being a breaking change for some users.

**Comment by ljacomet** [comment]
@hegyibalint I would aim to have this on `release` so it can be included in 7.5 and not wait until 7.6

**Comment by hegyibalint** [comment]
> LGTM!
> 
> One thing to add for the release is an entry in the upgrade guide as this ends up being a breaking change for some users.

Yep, I was thinking about that it's missing from there.

**Comment by hegyibalint** [comment]
@ljacomet can you have a final peek at the upgrade docs?

File: subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc [hunk 3]
```diff
@@ -38,6 +38,12 @@ Some plugins will break with this new version of Gradle, for example because the
 
 === Potential breaking changes
 
+==== Version catalog only accepts a single TOML import file
+
+Only a single file will be accepted when using a `from` import method.
+We advise users with this use case to use a code-based version catalog.
```
Comment (ljacomet) [inline subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc:44]: I would not highlight an alternative to handle this. I would instead clarify that this was possible only when passing multiple files in a single `from` call, so that most folks know they can ignore this point.

**Review by ljacomet — CHANGES_REQUESTED** [review]

File: subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc [hunk 4]
```diff
@@ -328,6 +328,13 @@ include::sample[dir="snippets/dependencyManagement/catalogs-toml/groovy/buildSrc
 include::sample[dir="snippets/dependencyManagement/catalogs-toml/kotlin/buildSrc",files="settings.gradle.kts[tags=import_main_catalog]"]
 ====
 
+[WARNING]
+====
+Only a single file will be accepted when using the link:{javadocPath}/org/gradle/api/initialization/dsl/VersionCatalogBuilder.html#from-java.lang.Object-[VersionCatalogBuilder.from(Object dependencyNotation)] method. This means that notations like link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:files(java.lang.Object++[]++)[Project.files(java.lang.Object...)] must refer to a single file, otherwise the build will fail.
```
Comment (ljacomet) [inline subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc:333]: 💄 Use the convention of having a single sentence per line

**Review by ljacomet — APPROVED** [review]
LGTM, with a minor comment, see below
