### PR TITLE
Fix issue with excluding test by class

### LINKED ISSUE #37539: `filter.excludeTest` doesn't filter JUnit5 nested test classes and excluding top-level class also excludes nested classes
### Current Behavior

A test in class `A$B` is not excluded when test task is configured with a `filter.excludeTest("A$B", null)`, while using `filter.excludeTest("A", null)` will exclude tests in `A$B` and `A$B$C` as well.
Running tasks `:testExcludeAll :testExcludeAllNested :testExcludeTopLevel :testExcludeFirstLevelNested :testExcludeSecondLevelNested` in the reproducer project gives following result:
```
> Task :testExcludeAll
===========================================
===========================================

> Task :testExcludeAllNested
===========================================
test()
firstLevelNestedTest()
secondLevelNestedTest()
===========================================

> Task :testExcludeTopLevel
===========================================
===========================================

> Task :testExcludeFirstLevelNested
===========================================
test()
firstLevelNestedTest()
secondLevelNestedTest()
===========================================

> Task :testExcludeSecondLevelNested
===========================================
test()
firstLevelNestedTest()
secondLevelNestedTest()
===========================================
```
Only `:testExcludeAll` behaves as expected. Compare to the output in https://github.com/gradle/gradle/issues/31304 where only `:testExcludeSecondLevelNested` gives unexpected results.

### Expected Behavior

`filter.excludeTest("A$B", null)` excludes tests in `A$B`
`filter.excludeTest("A", null)` excludes tests in `A`, but not in `A$B` and `A$B$C`

### Context (optional)

TeamCity uses excludes when [running tests in parallel](https://www.jetbrains.com/help/teamcity/parallel-tests.html) to determine which tests are run in which batch. Tests are included/excluded by test classes. When running Gradle 8, we made a workaround for https://github.com/gradle/gradle/issues/31304 which disabled tests that weren't excluded by Gradle.
After upgrading Gradle, if the test class `A` was excluded in batch 1, and test class `A$B` was excluded in batch 2, the tests from `A$B` didn't run in batch 1 since excluding `A` excluded them too, and didn't run in batch 2 since the workaround made up for ignored exclude entry. In the end, the tests from nested class weren't run at all.
Disabling the workaround helps, but
1) running the reproducer gives different results on different versions of Gradle (e. g. on 9.3.0 excluding nested classes works but excluding top-level class also excludes nested classes) so I'm not sure what will happen after next upgrade,
2) having tests run in the batch where the class is formally excluded is confusing when debugging.

### Self-contained Reproducer Project

[test-filter-bug-gradle-9.4.1.zip](https://github.com/user-attachments/files/26748489/test-filter-bug-gradle-9.4.1.zip)
The project is practically the same as provided in https://github.com/gradle/gradle/issues/31304, so the results can be compared, but modified to run on Gradle 9.

### Gradle version

9.4.1

### Gradle version that used to work

8.11 (except for the bug https://github.com/gradle/gradle/issues/31304)

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by ghale**
Calling filter.excludeTest("SampleTest", null) didn't just exclude `SampleTest` — it also silently excluded all of its `@Nested` children.  Compounding this, the test that should have caught this regression was broken in such a way that it continued to pass even though the behavior was wrong. 
                                                                                                                                                                                                                 
Three interacting bugs were responsible:                                                                                                                          
   
- Scan-time over-pruning. Excluded outer classes were dropped before JUnit Platform discovery. Because JUnit Platform discovers `@Nested` children through their outer class as a selector, dropping the outer left no way to reach the nested tests.
- Ancestor walk-up re-inclusion. The post-discovery filter's walk up the descriptor chain treated any non-excluded ancestor as sufficient to include a test, so a nested  class exclude could be bypassed by its non-excluded enclosing class.                                                                                                      
- Fuzzy exclude matching. The exclude-match heuristic treated a pattern like SampleTest$NestedTestClass as also matching SampleTest.  This was accidentally patching over the walk-up bug in some cases.                                   
                                                            
Fixing any single bug in isolation moves the failures around, so a correct fix involved fixing all three together.                                                           
                                                            
The following fixes were made:
- The test that should have caught this regression was rewritten to be more resilient.                                                                                                                                                                    
- Stopped pruning excluded classes at scan time that have nested classes. Excluded outer classes remain available as discovery selectors; filtering moves to post-discovery where it can be correct.  
- Rewrote the walk-up so that an exclude on a nested class is never bypassed by its enclosing class, while unrelated ancestors may still re-include.                                                                                                                                                         
- Added an exact-match exclude query distinct from the existing fuzzy heuristic. The exact query is used where a definitive "this class is excluded" answer is required; the fuzzy one is retained for the JUnit 4 filter, which relies on it to drill into individual methods.                                                                    

Fixes #37539 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

File: platforms/jvm/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/filters/ClassMethodNameFilter.java [hunk 1]
```diff
@@ -54,24 +54,40 @@ private boolean shouldRun(TestDescriptor descriptor) {
...
-        return parent.isPresent() && shouldRun(parent.get(), true);
+        return true;
     }
 
     private boolean shouldRun(TestDescriptor descriptor, boolean checkingParent, ClassSource classSource) {
+        String className = classSource.getClassName();
+        if (matcher.matchesExcludeClass(className)) {
+            // This class exactly matches an exclude pattern (not merely a fuzzy may-match).
+            // Don't let children-recursion re-include the container. Ancestors that are
+            // themselves included by pattern (e.g. a test suite) are handled by classMatch.
```
Comment (octylFractal) [inline platforms/jvm/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/filters/ClassMethodNameFilter.java:88]: 💅 This comment seems a little off, wdyt?
```suggestion
            // This class exactly matches an exclude pattern.
            // Return immediately to prevent children from re-including the container. Ancestors that are
            // themselves included by pattern (e.g. a test suite) are handled by classMatch.
```

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java [hunk 2]
```diff
@@ -29,17 +29,34 @@
...
  * <ul>
- * <li>Judge whether a test class might be included. For example, class 'org.gradle.Test' can't
- * be included by pattern 'org.apache.Test'
- * <li>Judge whether a test method is matched exactly.
+ *   <li><strong>Permissive scan-time check</strong> ({@link #mayIncludeClass(String)}) — may this
+ *       class possibly contribute tests that match the includes? Used to prune scanning; false
+ *       positives are acceptable, false negatives are not.</li>
+ *   <li><strong>Combined test-level check</strong> ({@link #matchesTest(String, String)}) — the
+ *       AND of {@link #matchesIncludeTest(String, String)} and the negation of
+ *       {@link #matchesExcludeTest(String, String)}. What most callers want for a leaf test.</li>
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:41]:
```suggestion
 *       result of {@link #matchesIncludeTest(String, String)} ANDed with the negation of
 *       {@link #matchesExcludeTest(String, String)}. What most callers want for a leaf test.</li>
```

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java [hunk 3]
```diff
@@ -29,17 +29,34 @@
...
 /**
- * This class has two responsibilities:
+ * Class-and-method pattern matcher used by {@link TestSelectionMatcher}.
  *
+ * <p>Separates three kinds of queries:
  * <ul>
- * <li>Judge whether a test class might be included. For example, class 'org.gradle.Test' can't
- * be included by pattern 'org.apache.Test'
- * <li>Judge whether a test method is matched exactly.
+ *   <li><strong>Permissive scan-time check</strong> ({@link #mayIncludeClass(String)}) — may this
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:36]: ❓ Why is this separated from the "Separated include / exclude queries"?

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java [hunk 4]
```diff
@@ -29,17 +29,34 @@
...
+ *       class possibly contribute tests that match the includes? Used to prune scanning; false
+ *       positives are acceptable, false negatives are not.</li>
+ *   <li><strong>Combined test-level check</strong> ({@link #matchesTest(String, String)}) — the
+ *       AND of {@link #matchesIncludeTest(String, String)} and the negation of
+ *       {@link #matchesExcludeTest(String, String)}. What most callers want for a leaf test.</li>
+ *   <li><strong>Separated include / exclude queries</strong>
+ *       ({@link #matchesIncludeTest(String, String)} / {@link #matchesExcludeTest(String, String)}
+ *       / {@link #matchesExcludeClass(String)}) — lets callers reason about include and exclude
+ *       semantics independently. Needed by walkers that must distinguish "excluded at this
+ *       descriptor" from "include matched via a non-excluded ancestor".</li>
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:46]: ❌ I think the extra sentence here is just noisy.
```suggestion
 *       semantics independently.</li>
```

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java [hunk 5]
```diff
@@ -29,17 +29,34 @@
...
  * </ul>
  *
- * In both cases, if the pattern starts with an upper-case letter, it will be used to match
- * the simple class name;
- * otherwise, it will be used to match the fully qualified class name.
+ * <p>Pattern interpretation:
+ * <ul>
+ *   <li>A pattern that starts with an upper-case letter matches the simple class name.</li>
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:51]: 💭 Maybe not for now, but we should formalize exactly what locale we use to determine "upper-case", as currently it's based on the default locale. It should probably just use ASCII?

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java [hunk 6]
```diff
@@ -29,17 +29,34 @@
...
+ *   <li>Otherwise, it matches the fully qualified class name.</li>
+ *   <li>{@link #matchesExcludeTest(String, String)} applies a fuzzy {@code mayMatchClass}
+ *       heuristic at the class level (when method name is null), so callers that iterate
+ *       into individual methods can still find exact exclude matches without giving up the
+ *       entire class prematurely.</li>
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:56]: ❓ I don't quite understand this, if it only applies when `null`, how does iterating into individual methods relate? What does "giving up the entire class prematurely" mean in this context?

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java [hunk 7]
```diff
@@ -29,17 +29,34 @@
...
  * </ul>
  *
- * In both cases, if the pattern starts with an upper-case letter, it will be used to match
- * the simple class name;
- * otherwise, it will be used to match the fully qualified class name.
+ * <p>Pattern interpretation:
+ * <ul>
+ *   <li>A pattern that starts with an upper-case letter matches the simple class name.</li>
+ *   <li>Otherwise, it matches the fully qualified class name.</li>
+ *   <li>{@link #matchesExcludeTest(String, String)} applies a fuzzy {@code mayMatchClass}
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:53]: :x: This should be explaining exactly what "fuzzy" means here. Referencing `mayMatchClass` is pointless in Javadoc since it's private, so someone viewing the Javadoc can't read the implementation.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java [hunk 8]
```diff
@@ -59,17 +76,38 @@ private static List<ClassTestPattern> prepareClassBasedPatternList(Collection<St
             .collect(Collectors.toList());
     }
 
-
+    /**
+     * Returns true if the given (className, methodName) pair matches the include patterns and is not excluded by the
+     * exclude patterns.
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:81]: 💅 For this and others, this pattern gives a proper `@return` with the same text otherwise:
```suggestion
     * {@return true if the given (className, methodName) pair matches the include patterns and is not excluded by the
     * exclude patterns}
```

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java [hunk 9]
```diff
@@ -59,17 +76,38 @@ private static List<ClassTestPattern> prepareClassBasedPatternList(Collection<St
...
-            && !matchesExcludePattern(className, methodName);
+            && matchesPattern(commandLineIncludePatterns, className, methodName);
+    }
+
+    /**
+     * Returns true if the given (className, methodName) pair matches any exclude pattern.
+     *
+     * <p>An empty exclude set returns false. Include patterns are not consulted.</p>
+     */
+    public boolean matchesExcludeTest(String className, @Nullable String methodName) {
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:104]: :x: I think this method's Javadoc should mention the special behavior called out in the class Javadoc.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java [hunk 10]
```diff
@@ -125,6 +147,23 @@ private boolean matchesExcludePattern(String className, @Nullable String methodN
         return matchesClassAndMethod(buildScriptExcludePatterns, className, methodName);
     }
 
+    /**
+     * Returns true if the class name exactly matches an exclude pattern's class component.
+     *
+     * <p>Unlike {@link #matchesExcludeTest(String, String)}, this does <em>not</em> consult
+     * the fuzzy {@code mayMatchClass} heuristic: pattern {@code Parent} does not match
+     * class {@code Parent$Nested} here. Used by callers that need a definitive
+     * "is this class excluded?" answer rather than a "might this class match?" hint.</p>
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:156]: :x: I don't think this extra sentence is needed.
```suggestion
     * class {@code Parent$Nested} here.</p>
```

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java [hunk 11]
```diff
@@ -125,6 +147,23 @@ private boolean matchesExcludePattern(String className, @Nullable String methodN
...
+     */
+    public boolean matchesExcludeClass(String className) {
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:158]: 💭 Perhaps this should be called `matchesExcludeClassExactly`? Or some other term to differentiate it more.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java [hunk 12]
```diff
@@ -24,22 +24,31 @@
 import java.util.Collections;
 
 /**
- * This class has three public APIs:
+ * Entry point for matching test descriptors against include and exclude patterns.
  *
+ * <p>Provides the following queries:
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java:29]: :x: I don't think listing these here is useful. Javadoc already lists all the methods with a short summary.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java [hunk 13]
```diff
@@ -81,6 +90,36 @@ public boolean matchesTest(String className, @Nullable String methodName) {
         return classTestSelectionMatcher.matchesTest(className, methodName);
     }
 
+    /**
+     * Returns true if the given class and method matches the include patterns (build-script and command-line).
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java:94]: :x: Mentioning "build-script and command-line" feels like a violation of the abstraction here. This class doesn't even own those fields, they're in the `classTestSelectionMatcher`.

File: platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy [hunk 14]
```diff
@@ -257,6 +258,71 @@ class TestSelectionMatcherTest extends Specification {
         ['org.gradle.FooTest*'] | ['*org.gradle.BarTest*']        | 'org.gradle.FooTest'  | true
     }
 
+    def "matchesIncludeTest ignores exclude patterns"() {
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy:261]: :x: This test name is confusing, it contains cases with no `excludes` at all.

File: platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy [hunk 15]
```diff
@@ -257,6 +258,71 @@ class TestSelectionMatcherTest extends Specification {
...
+        where:
+        includes           | excludes           | className         | methodName       | match
+        []                 | []                 | "FooTest"         | "aaa"            | true
+        []                 | ["FooTest"]        | "FooTest"         | "aaa"            | true
+        ["FooTest"]        | []                 | "FooTest"         | "aaa"            | true
+        ["FooTest"]        | ["FooTest"]        | "FooTest"         | "aaa"            | true
+        ["FooTest"]        | []                 | "BarTest"         | "aaa"            | false
+    }
+
+    def "matchesIncludeTest combines build-script and command-line includes"() {
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy:274]: :x: Should be explicit about combining meaning "AND"
```suggestion
    def "matchesIncludeTest returns the AND of build-script and command-line includes"() {
```

File: platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy [hunk 16]
```diff
@@ -257,6 +258,71 @@ class TestSelectionMatcherTest extends Specification {
...
+        buildScript        | commandLine       | className         | match
+        []                 | []                | "FooTest"         | true
+        ["FooTest"]        | []                | "FooTest"         | true
+        []                 | ["FooTest"]       | "FooTest"         | true
+        ["FooTest"]        | ["FooTest"]       | "FooTest"         | true
+        ["FooTest"]        | ["BarTest"]       | "FooTest"         | false
+        ["FooTest"]        | ["BarTest"]       | "BarTest"         | false
+    }
+
+    def "matchesExcludeTest ignores include patterns"() {
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy:288]: :x: This also contains tests with no `includes`, which doesn't make sense to me.

File: platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy [hunk 17]
```diff
@@ -257,6 +258,71 @@ class TestSelectionMatcherTest extends Specification {
...
+        []                 | ["FooTest"]                | "BarTest"                        | null               | false
+        ["BarTest"]        | ["FooTest"]                | "BarTest"                        | null               | false
+        []                 | ["FooTest.doThing"]        | "FooTest"                        | "doThing"          | true
+        ["BarTest"]        | ["FooTest.doThing"]        | "FooTest"                        | "doThing"          | true
+        []                 | ["FooTest.doThing"]        | "FooTest"                        | "doOther"          | false
+        ["BarTest"]        | ["FooTest.doThing"]        | "FooTest"                        | "doOther"          | false
+    }
+
+    @Issue("https://github.com/gradle/gradle/issues/37539")
+    def "matchesExcludeClass is exact and does not treat parent pattern as matching nested class"() {
```
Comment (octylFractal) [inline platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy:306]: :x: This seems like it should be two tests, one for the exactness, and one for the nested class handling.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java (hunk 3 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:36]: Because `mayIncludeClass` is used fundamentally differently than the others.  This is used at scan time to do a cheap "should we even look at this class at all" check.  In other words, "if we already know the includes don't match the class, we can just omit it from the set of classes we send to the worker".  We don't look at excludes or try to understand the hierarchy of nested tests or anything, we just exclude things that don't match the includes.  Then at execution time, in the worker, the separate include/exclude queries are used to do a more exact check of whether a given test that was discovered should be executed or not.   

I think it makes sense for this to be called out separately.  Do you disagree?

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java (hunk 6 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java]: I don't _think_ this can occur with JUnit5, but for JUnit4, you can potentially create tests that have `ClassSource` descriptors without children.  However, they can stuff the "method name" into legacyReportingName, so you have a bunch of `ClassSource` descriptors with different legacy names.  So we return false only when 1) there are no excludes, 2) method is not null and we don't have an exact match on method and class name or 3) method _is_ null, but we're sure the class can't still match an exclude on a method name.

If we returned false when the method is null and we think it could still match an exclude based on method name, we would "accept" the test and never get to the check against legacy reporting name (which would exclude it).

I find this all hard to reason about (lots of double negatives) and the verbiage in the javadoc is admittedly confusing.  I've attempted to write this more clearly.  Let me know if you think it needs further polishing.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java (hunk 7 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java]: See https://github.com/gradle/gradle/pull/37578#discussion_r3125064208.  I've rewritten this - hopefully it's a little better now.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java (hunk 9 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:107]: Good point.  Done.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java (hunk 11 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java]: Yeah, I like that.  Done.  Same for `TestSelectionMatcher`.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java (hunk 12 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java]: Fair enough.  Removed.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java (hunk 13 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java]: Removed.

File: platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy (hunk 14 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy:193]: Well, the idea was to show that it behaves the same with excludes and without, but I see your point.  I've removed the non-exclude iterations and added a few more iterations to be comprehensive.

File: platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy (hunk 15 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy]: Done.

File: platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy (hunk 16 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy:251]: Same as above.  I' ve split this into two tests - one to test `matchesExcludeTest()` in isolation and another to test just that it ignores excludes.

File: platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy (hunk 17 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy:274]: I think I prefer seeing all the cases together where it's clear what will and will not be excluded given each exclude.

However, I don't feel strongly about it.  If you do, then I don't mind changing this.  But if not, I'd rather just keep it the way it is.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java (hunk 5 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:50]: Agreed, but I think this is outside of the scope of this change.

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java (hunk 6 above)
Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java]: Maybe as a follow up we could ask an agent to analyze this and try to simplify it all.  I suspect it _can_ be simplified, but I don't currently see a clear path to doing so.  I think this should be done as follow up work, though, and we should confine the scope of this PR as much as possible (i.e. it already introduces some substantial changes).

File: platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java (hunk 3 above)
Comment (octylFractal) [reply platforms/software/testing-base-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/filter/ClassTestSelectionMatcher.java:36]: I guess it's fine. I think I take issue with the name being too close but that's not new in this PR, so I'll leave it.

File: platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy (hunk 17 above)
Comment (octylFractal) [reply platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy:274]: It's mostly that I find `true`/`false` in these tests to be hard to read. If you want to point out what will and won't match, I think it would be clearer with `excludePattern | matchingClassNames | unmatchingClassNames`, so each `excludePattern` is just listed once.

Comment (ghale) [reply platforms/software/testing-base-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy:274]: Great idea.  I think it makes these tests much easier to reason about.  I've updated all of the tests to use this pattern since this is a good general improvement and it keeps the pattern consistent.

**Review by octylFractal — APPROVED** [review]
