### PR TITLE
Fix using modifiers with version catalogs

### LINKED ISSUE #25828: Test suits dependencies block fails when adding a platform defined in Version Catalog
### Expected Behavior

Using libraries defined in the version catalog can be used as platforms in the `dependencies` block of Test Suits.

```
testing.suites {
    val test by getting(JvmTestSuite::class) {
        useJUnitJupiter()
        dependencies {
            implementation(platform(libs.junit.bom))
        }
    }
}
```

### Current Behavior

The build fails with an error:

```
Could not determine the dependencies of task ':test'.
Could not resolve all dependencies for configuration ':testRuntimeClasspath'.
> Minimal dependencies are immutable.
```

### Context (optional)

_No response_

### Steps to Reproduce

Reproducer project: https://github.com/alllex/gradle-repro-test-suits-with-platform-deps/tree/kotlin-dsl

### Gradle version

8.3-rc-1

### Build scan URL (optional)

https://scans.gradle.com/s/mfnrzmq52xym4

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by octylFractal**
Because version catalog dependencies are immutable, the modifiers need to sometimes copy the dependency to modify it.

In order to make this work, we copy the dependencies regardless of implementation.

Fixes #25828

### CODE REVIEW

File: subprojects/core-api/src/main/java/org/gradle/api/plugins/jvm/PlatformDependencyModifiers.java [hunk 1]
```diff
@@ -72,10 +72,9 @@ abstract class PlatformDependencyModifier implements DependencyModifier {
          * Selects the platform variant of the given dependency.
          */
         @Override
-        public <D extends ModuleDependency> D modify(D dependency) {
+        public void modifyImpl(ModuleDependency dependency) {
```
Comment (big-guy) [inline subprojects/core-api/src/main/java/org/gradle/api/plugins/jvm/PlatformDependencyModifiers.java:75]: ❓ This should still be protected?

File: subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyModifier.java [hunk 2]
```diff
@@ -88,18 +96,37 @@ default Provider<? extends MinimalExternalModuleDependency> modify(ProviderConve
...
+
+    /**
+     * Modify the given dependency.
+     *
+     * @param dependency the dependency to modify
      * @implSpec This method must be implemented.
+     * @since 8.4
      */
-    <D extends ModuleDependency> D modify(D dependency);
+    protected abstract void modifyImpl(ModuleDependency dependency);
```
Comment (big-guy) [inline subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyModifier.java:130]: ❌ We need to update the class-level docs here to explain how to implement a modifier since you no longer override the `modify(D)` and you don't need to avoid implementing the default methods.

💭 I would also consider a slightly different name:
- `doModify` - this is similar to what we use internally
- `modifyImplementation` - this describes this as the "implementation of modify(...)"
- `modifyDependency` - this is what it does

File: subprojects/core-api/src/main/java/org/gradle/api/plugins/jvm/PlatformDependencyModifiers.java [hunk 3]
```diff
@@ -114,15 +113,12 @@ abstract class EnforcedPlatformDependencyModifier implements DependencyModifier
          * Selects the enforced platform variant of the given dependency.
          */
         @Override
-        public <D extends ModuleDependency> D modify(D dependency) {
+        public void modifyImpl(ModuleDependency dependency) {
```
Comment (big-guy) [inline subprojects/core-api/src/main/java/org/gradle/api/plugins/jvm/PlatformDependencyModifiers.java:116]: ❓ same here

File: subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/TestFixturesDependencyModifiers.java [hunk 4]
```diff
@@ -55,25 +55,26 @@ public interface TestFixturesDependencyModifiers {
...
-    abstract class TestFixturesDependencyModifier implements DependencyModifier {
+    abstract class TestFixturesDependencyModifier extends DependencyModifier {
         /**
          * {@inheritDoc}
          *
          * Selects the test fixtures variant of the given dependency.
          */
         @Override
-        public <D extends ModuleDependency> D modify(D dependency) {
+        public void modifyImpl(ModuleDependency dependency) {
```
Comment (big-guy) [inline subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/TestFixturesDependencyModifiers.java:65]: ❓ same here

File: subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/TestFixturesDependencyModifiers.java [hunk 5]
```diff
@@ -55,25 +55,26 @@ public interface TestFixturesDependencyModifiers {
      * @see #modify(ModuleDependency)
```
Comment (big-guy) [inline subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/TestFixturesDependencyModifiers.java:55]: ❓ I think this needs to link to modifyImplementation now? All of the modifiers have this identical javadoc.

**Review by big-guy — CHANGES_REQUESTED** [review]

**Review by big-guy — APPROVED** [review]

**Comment by big-guy** [comment]
@bot-gradle test and merge
