### PR TITLE
Make it an error to not handle duplicates explicitly

### LINKED ISSUE #15594: Fail for duplicates in copy specs for default duplicates strategy
We emit the deprecation warning here: https://github.com/gradle/gradle/blob/5cd77b034c98c47d6bfa7e532462373902d74373/subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java#L48-L55

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by melix**
Previous Gradle releases used a default 'include' strategy for
copy specs: if a duplicate was found, then Gradle would silently
include the duplicate, potentially overwriting the previous entry.

In Gradle 5, we introduced a warning whenever duplicates are found
and that no explicit deduplication strategy is set. With Gradle 7,
this now becomes an error.

Closes #15594

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy [hunk 1]
```diff
@@ -1467,30 +1471,29 @@ class CopyTaskIntegrationSpec extends AbstractIntegrationSpec {
...
+        fails 'copy'
 
         then:
-        file('dest').assertHasDescendants('path/file.txt')
-        file('dest/path/file.txt').text == 'f2'
+        failure.assertHasCause "Entry path/file.txt is a duplicate but no duplicate handling strategy has been set. Please refer to ${DOCUMENTATION_REGISTRY.getDslRefForProperty(CopySpec.class, "duplicatesStrategy")} for details."
 
         when:
-        run 'copy'
+        file('dir2/path/file.txt').text = 'new'
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:1480]: I think we can skip running the build on a change, given that the task won't be up-to-date since it failed.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java [hunk 2]
```diff
@@ -100,8 +102,8 @@ public DefaultFileOperations(
             fileResolver,
             patternSetFactory,
             fileSystem,
-            instantiator
-        );
+            instantiator,
+            documentationRegistry);
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java:106]: Nit: I think the closing braket should stay on a new line.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopyActionExecuter.java [hunk 3]
```diff
@@ -24,17 +25,19 @@
...
         this.reproducibleFileOrder = reproducibleFileOrder;
+        this.documentationRegistry = documentationRegistry;
     }
 
     public WorkResult execute(final CopySpecInternal spec, CopyAction action) {
         final CopyAction effectiveVisitor = new DuplicateHandlingCopyActionDecorator(
-                new NormalizingCopyActionDecorator(action, fileSystem)
-        );
+                new NormalizingCopyActionDecorator(action, fileSystem),
+            documentationRegistry);
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopyActionExecuter.java:40]: Nit: the indenting seems to be off here.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopier.java [hunk 4]
```diff
@@ -45,15 +47,16 @@ public FileCopier(
         FileResolver fileResolver,
         Factory<PatternSet> patternSetFactory,
         FileSystem fileSystem,
-        Instantiator instantiator
-    ) {
+        Instantiator instantiator,
+        DocumentationRegistry documentationRegistry) {
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopier.java:51]: Nit: Please keep the newlines before `) {`

File: subprojects/tooling-api/build.gradle.kts [hunk 5]
```diff
@@ -6,6 +6,10 @@ plugins {
 
 gradlebuildJava.usedInToolingApi()
 
+tasks.named<Jar>("sourcesJar") {
+    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
```
Comment (wolfs) [inline subprojects/tooling-api/build.gradle.kts:10]: Do we have duplicate sources here? If we have, can you add a comment which ones?

**Review by wolfs — COMMENTED** [review]
The change looks good overall. I left some comments.

**Review by wolfs — COMMENTED** [review]
LGTM!
