### PR TITLE
Preserve task dependencies for transformed incoming elements

### LINKED ISSUE #29147: FileCollection.elements fail under load.
### Current Behavior

When using the Large-Android project (which is our synthetic large android project with 1000s of modules), the `FileCollection.elements` API fails to carry the tasks dependencies attached to the underlying `FileCollection` instance.

For instance, say a `FileCollection` instance depends on some other project's output, when using the `FileCollection.elements` to get a `Provider<List<FilesystemLocation>>>` will fail to carry the tasks dependency and eventually, when that `Provider` is resolved by calling `files()` on it, you will get a failure like : 

```
* What went wrong:
Execution failed for task ':module07:module052:module2:debugReproduceIssue'.
> Failed to calculate the value of task ':module07:module052:module2:debugReproduceIssue' property 'input'.
   > Could not resolve all files for configuration ':module07:module052:module2:debugUnitTestRuntimeClasspath'.
      > Failed to transform module1.jar (project :module07:module354:module1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=17, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
         > Execution failed for IdentityTransform: /usr/local/google/home/jedo/bugs/Large-Android/module07/module354/module1/build/libs/module1.jar.
            > File/directory does not exist: /usr/local/google/home/jedo/bugs/Large-Android/module07/module354/module1/build/libs/module1.jar
      > Failed to transform module4.jar (project :module07:module594:module4) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=17, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
         > Execution failed for IdentityTransform: /usr/local/google/home/jedo/bugs/Large-Android/module07/module594/module4/build/libs/module4.jar.
            > File/directory does not exist: /usr/local/google/home/jedo/bugs/Large-Android/module07/module594/module4/build/libs/module4.jar

```

The key thing here is that if you do use use the `FileCollection.files` instead of `FileCollection.elements`, it works fine so it seems to be related to the `elements` API. Also this is only reproducible in the Large-Android project, I tried to repro in smaller projects but that worked fine. 

So say you have a FileCollection coming from a Configuration, something like : 

```
val configurationOfInterest = project.configurations.getByName("debugUnitTestRuntimeClasspath")
val incoming = configurationOfInterest.incoming
incoming.attributes.attribute(
    Attribute.of("artifactType", String::class.java),
    "android-classes-jar"
)
```

and a Task defined like : 

```
abstract class FileCollectionElementsTask: DefaultTask() {

    @get:Classpath
    abstract val input: ListProperty<FileSystemLocation>

    @TaskAction
    fun taskAction() {
      input.get().map {
        println("Got from elements ${it.asFile.absolutePath}")
      }
    }
}
```

wired with : 

```
project.tasks.register<FileCollectionElementsTask>(taskName) {
    input.set(incoming.files.elements)
}
```

and you will get the exception above. 

However if you use that task : 

```
abstract class FileCollectionTask: DefaultTask() {

    @get:Classpath
    abstract val input: ConfigurableFileCollection

    @TaskAction
    fun taskAction() {
        input.files.map {
            println("Got file ${it.absolutePath}")
        }
    }
}
```

wired with : 

```
project.tasks.register<FileCollectionTask>(taskName) {
    input.setFrom(incoming.files)
}
```

then it will just works fine ! 

To reproduce the issue, you can just take the attached project (careful, it's big), unzip the file.

In `build-logic`, you will find a custom plugin, in particular a `CustomPlugin.kt` which sets up both functional and dysfunctional tasks so you can experience both the failure and success whether you use the `FileCollection` directly or the `FileCollection.elements`. 

To reproduce the issue, just run : 
```
gradlew clean DebugReproduceIssue 
```

if you want to experience the successful run using the `FileCollection` in the task, just run 
```
gradlew clean DebugReproduceIssue -PmakeItWork

```

Obviously, using `FileCollection` is a workaround, the issue though is that our `Variant` API is relying on `RegularFile` and `Directory` types for type safety. So we need to transforms incoming `FileCollection` instances into `Provider<List<RegularFile>>` and `Provider<List<Directory>>` using the `FileCollection.elements`. 

### Expected Behavior

it should work wether you use `FileCollection.files()` or `FileCollection.elements.files()` APIs.

### Context (optional)

_No response_

### Steps to Reproduce

download the repro project from [here](https://drive.google.com/file/d/1KTLO8pAzQ0nQmSG7JOI779gkT_vnTCs8/view?usp=drive_link)

unzip the zip, in the project folder, run 
```
gradlew clean DebugReproduceIssue 
```

### Gradle version

8.7

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by bamboo**
By making `ValueProducer` extend `TaskDependencyContainer` so all types of producer dependencies, including transforms, can be properly taken into account.

Also make `BuildableBackedProvider` expect and compute dependencies via a given `TaskDependencyContainer`.

This PR doesn't address all situations in which `incoming.elements` dependencies could be lost (for example, when the `incoming.elements` provider is combined with another provider via `orElse`), that work is being tracked as part of #29528. 

Fixes #29147

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test

File: platforms/core-configuration/file-collections/src/integTest/groovy/org/gradle/api/file/FileCollectionIntegrationTest.groovy [hunk 1]
```diff
@@ -513,7 +512,6 @@ class FileCollectionIntegrationTest extends AbstractIntegrationSpec implements T
             " Consult the upgrading guide for further information: https://docs.gradle.org/current/userguide/upgrading_version_7.html#file_collection_to_classpath")
     }
 
-    @ToBeImplemented
```
Comment (abstratt) [inline platforms/core-configuration/file-collections/src/integTest/groovy/org/gradle/api/file/FileCollectionIntegrationTest.groovy:516]: 👍
