### PR TITLE
Visit known configurations

### LINKED ISSUE #35571: ConcurrentModificationException determining task dependencies in Gradle 9.2.0
### Current Behavior

Trying to upgrade from Gradle 9.1.0 to 9.2.0, we are seeing ConcurrentModificationExceptions in our tests, for example https://github.com/quarkusio/quarkus/pull/50848#issuecomment-3488609934

### Expected Behavior

No errors expected.

### Context (optional)

_No response_

### Self-contained Reproducer Project

https://github.com/aloubyansky/playground/tree/gradle-9.2-concurrent-modification

### Gradle version

9.2.0

### Gradle version that used to work

9.1.0

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by big-guy**
fixes #35571 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainer.java [hunk 1]
```diff
@@ -114,15 +115,15 @@ protected NamedDomainObjectProvider<Configuration> createDomainObjectProvider(St
     @Override
     public void visitConsumable(Consumer<ConfigurationInternal> visitor) {
         // Visit all configurations which are known to be consumable
-        withType(ConsumableConfiguration.class).forEach(configuration ->
+        Collection<ConsumableConfiguration> availableConsumableConfigurations = new ArrayList<>(withType(ConsumableConfiguration.class));
```
Comment (jvandort) [inline platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainer.java:119]: Can we add a comment here explaining why we copy before visiting?

I'd like there to be enough info that someone looking at this code understands why we are doing this extra step.

My immediate reaction seeing this code without context would be to "fix" it

File: platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ExclusiveVariantsIntegrationTest.groovy [hunk 2]
```diff
@@ -18,8 +18,32 @@ package org.gradle.integtests.resolve.attributes
 
 
 import org.gradle.integtests.fixtures.AbstractIntegrationSpec
+import spock.lang.Issue
 
 class ExclusiveVariantsIntegrationTest extends AbstractIntegrationSpec {
+    @Issue("https://github.com/gradle/gradle/issues/35571")
```
Comment (jvandort) [inline platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ExclusiveVariantsIntegrationTest.groovy]: I'd prefer to not use `outgoingVariants` as the reproducing task here, as it does not use the "real" resolution path to realize configurations. 

This here does reproduce the problem though, and uses real resolution to do so:
```
    @Issue("https://github.com/gradle/gradle/issues/35571")
    def "can realize configurations as a side-effect of visiting variants of a project component"() {
        buildFile("""
            def myTask = tasks.register("myTask") {
                configurations.getByName("zzz")
            }
            configurations {
                create("trigger") {
                    dependencies.add(dependencyFactory.create(project))
                }
                resolvable("zzz")
                consumable("bbb")
                // This must be named something that's alphabetically before the other consumable configurations
                // to trigger the failure
                consumable("aaa") {
                    attributes {
                        attributeProvider(Attribute.of("taskValue", String), myTask.map { "from task value" })
                    }
                }
            }

            tasks.register("resolve") {
                dependsOn(configurations.trigger)
            }
        """)

        expect:
        succeeds("resolve")
    }
```

File: platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ExclusiveVariantsIntegrationTest.groovy [hunk 3]
```diff
@@ -18,8 +18,32 @@ package org.gradle.integtests.resolve.attributes
 
 
 import org.gradle.integtests.fixtures.AbstractIntegrationSpec
+import spock.lang.Issue
 
 class ExclusiveVariantsIntegrationTest extends AbstractIntegrationSpec {
```
Comment (jvandort) [inline platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ExclusiveVariantsIntegrationTest.groovy:22]: `LazyConfigurationResolveIntegrationTest` may be a better fit for this test
