### PR TITLE
Disable ktlint for generated code for now

### LINKED ISSUE #8687: 5.3-rc-1 generated kotlin code causes ktlint check to fail
We use the `org.jlleitschuh.gradle.ktlint` for linting our kotlin code. When updating our build to 5.3-rc-1 we see the many of this type of error messages for kotlin code generated by the kotlin-dsl:

```
PluginSpecBuildersFor$9d9adc59b7a01e47b29d4c8119edba55.kt:33:1: Needless blank line(s) (cannot be auto-corrected)
``` 

### Expected Behavior
Generated kotlin code should pass ktlint checks

### Current Behavior
Generated kotlin code does not pass ktlint checks

### Your Environment

 * Build scan URL: Not available as it happens in buildSrc

### PR DESCRIPTION
**Pull request by big-guy**
fixes #8687

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by big-guy** [comment]
I'm going to merge this and get a nightly going for internal testing.

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/codegen/SourceFileHeader.kt [hunk 1]
```diff
@@ -37,6 +37,8 @@ fun fileHeaderFor(packageName: String) =
     "ObjectPropertyName"
 )
 
+/* ktlint-disable */
+
```
Comment (eskatos) [inline subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/codegen/SourceFileHeader.kt]: Good move @big-guy!
