### PR TITLE
Fix issue with double quotes when launching java processes on windows 

### LINKED ISSUE #6072: Exception when passing outer system proprties into JavaExec or Spring bootRun task
This is a problem I noticed in Spring Boot Gradle plugin when calling bootRun task from command line. In my build.gradle I have configured the task to use System.properties as properties:

```
configure(bootRun) {
    systemProperties System.properties
}
```

The task fails to run with an exception that it did not find the main class "Corporation", which is not the main class of my project at all. With gradle --debug flag I could see that the generated command line to run the Spring-Boot application took all the system properties and set them with -`D` parameters, but not in quotes, which causes the command line to fail roughly at
```
[...] -Djava.specification.vendor=Oracle Corporation -Djava.specification.version=10 [...]
                                         ^
```

### Expected Behavior
Strings with spaces are properly escaped to the needs of the terminal
### Current Behavior
Strings are printed into the command line regardless of content.

### Context
the aim is to forward -D[property]=[value] parameters from the CLI call into spring bootRun task but also generally into all Java executions of my builds
### Steps to Reproduce (for bugs)
- Check your system properties if there are any properties with spaces, add one if necessary to the environment. Tested only under Windows.
- Set up a gradle project with the `org.springframework.boot` extension, add the scriptlet above to its build.gradle, add whatever is needed to pass javaCompile phase and 
- execute `gradle bootRun`.

### Your Environment
Windows 10 64bit
Oracle JDK 10.0.2
Gradle 4.9
```
plugins {
    id 'org.springframework.boot' version '2.0.3.RELEASE'
    id "com.energizedwork.webdriver-binaries" version "1.4"
}
```

 * Build scan URL:

### PR DESCRIPTION
**Pull request by wheeleme**
Fixes #6072 

### Context
User encountered issue where Java process on Windows would drop double quotes in Java Processes. This PR checks for double quotes and escapes them so Windows interprets them correctly. 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: subprojects/core/src/test/java/org/gradle/api/internal/attributes/MyNamed.java [hunk 1]
```diff
@@ -28,6 +28,7 @@
 public final class MyNamed implements Named, Serializable {
 
     private final String name;
+    private String noname;
```
Comment (ljacomet) [inline subprojects/core/src/test/java/org/gradle/api/internal/attributes/MyNamed.java]: ❓ Leftover or part of attempting to add a unit test?

File: subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java [hunk 2]
```diff
@@ -368,7 +379,7 @@ public List<String> getAllArguments() {
     private List<String> getAllArguments(FileCollection realClasspath) {
         List<String> arguments = new ArrayList<>(getAllJvmArgs(realClasspath));
         arguments.addAll(execHandleBuilder.getAllArguments());
-        return arguments;
+        return escapeQuotes(arguments);
```
Comment (ljacomet) [inline subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java:381]: 🤔 While this seems to fix the specific issue, are there other places where a similar handling should be applied?

File: subprojects/core/src/test/java/org/gradle/api/internal/attributes/MyNamed.java (hunk 1 above)
Comment (wheeleme) [reply subprojects/core/src/test/java/org/gradle/api/internal/attributes/MyNamed.java]: Most likely leftover. Will remove.

File: subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java (hunk 2 above)
Comment (wheeleme) [reply subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java:381]: Not 100% sure but I would say potentially. I will do some investigation.

**Comment by wheeleme** [comment]
@bot-gradle test this

**Comment by wheeleme** [comment]
@bot-gradle test this

**Comment by wheeleme** [comment]
@bot-gradle test this

**Comment by wheeleme** [comment]
@bot-gradle test this

**Comment by wheeleme** [comment]
@bot-gradle help

**Comment by wheeleme** [comment]
@bot-gradle test this

**Comment by wheeleme** [comment]
@bot-gradle clear

File: subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java (hunk 2 above)
Comment (wheeleme) [reply subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java:381]: @ljacomet After investigating further, we've found that there are instances where you don't want to escape quotes. For example, after moving the code to a parent class, CI failed several tests (only on Windows) with similar errors to the following: 

` Error:
  '\"gradle -i --daemon --gradle-user-home C:\tcagent1\work\f63322e10dd6b396\intTestHomeDir\distributions-full --warning-mode=all -Porg.gradle.java.installations.auto-download=false -Porg.gradle.java.installations.auto-detect=false\"' is not recognized as an internal or external command,
  operable program or batch file.`

If you notice at the beginning of the error, the double quote is being escaped, when in fact it should not be. So it appears that in Java arguments, you do want to escape quotes, but not in certain other arguments. 

I've moved the escapeQuotes code back to the original proposed location. Let me know if you have further questions.

**Comment by wheeleme** [comment]
@bot-gradle clean

**Comment by wheeleme** [comment]
@bot-gradle test this

**Comment by wheeleme** [comment]
@ljacomet Could you take a second look when you have a chance?

**Review by ljacomet — APPROVED** [review]
