### PR TITLE
Fix incorrect and duplicate links in deprecation warnings

### LINKED ISSUE #20517: Implicit Dependency deprecation warning links to default "Authoring Tasks" in Build Scans
It seems that, when running a Build Scan with an Implicit Dependency deprecation warning, the deprecations page points to the generic Authoring Tasks documentation, rather than the specific Implicit Dependencies Validation Problems documentation. This is believed to be a Gradle Build Tool issue since that is what sets the problem information for a deprecation validation issue.

### Expected Behavior
The build scan should link to [Validation Problems - Implicit dependencies between tasks](https://docs.gradle.org/7.4.2/userguide/validation_problems.html#implicit_dependency).

### Current Behavior
The build scan links to the default [Authoring Tasks - Up-to-date checks](https://docs.gradle.org/7.4.2/userguide/more_about_tasks.html#sec:up_to_date_checks)

### Context

This was observed in a build scan for the [detekt](https://github.com/detekt/detekt) project. The `:code-coverage-report:jacocoMergedReport` task was showing "Caching has been disabled to ensure correctness. Please consult deprecation warnings for more details." Because the deprecation link did not go to the expected documentation page, the documentation could be potentially confusing to the user.

### Steps to Reproduce 
In the [detekt](https://github.com/detekt/detekt) project, run `./gradlew :code-coverage-report:jacocoMergedReport :detekt-generator:generateDocumentation`. Originally observed at commit `683e696375fa5e99fec7e8677c46b0925436454d`.

### Your Environment
Build scan URL: https://scans.gradle.com/s/3bfsfew4vg5uk

### PR DESCRIPTION
**Pull request by jvandort**
In deprecation warnings created by TaskValidaitonProblems, we ensure the
documentation links from the problems themselves are used for the
deprecation warning and are not included in the message.

Fixes #20517

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle help

**Comment by big-guy** [comment]
@bot-gradle test and merge

File: subprojects/core/src/main/java/org/gradle/execution/DefaultWorkValidationWarningRecorder.java [hunk 1]
```diff
@@ -16,37 +16,42 @@
...
 
     private final AtomicInteger workWithFailuresCount = new AtomicInteger();
 
     @Override
-    public void recordValidationWarnings(UnitOfWork work, Collection<String> warnings) {
+    public void recordValidationWarnings(UnitOfWork work, Collection<TypeValidationProblem> warnings) {
         workWithFailuresCount.incrementAndGet();
-        Set<String> uniqueSortedWarnings = ImmutableSortedSet.copyOf(warnings);
+
+        ImmutableSet<String> uniqueWarnings = warnings.stream().map(warning -> convertToSingleLine(renderMinimalInformationAbout(warning, true, false))).collect(ImmutableSet.toImmutableSet());
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/execution/DefaultWorkValidationWarningRecorder.java:43]: It looks like you dropped the sorting here. Is this intentional?
