### PR TITLE
Disable GMM publication if custom pattern is used

### LINKED ISSUE #12339: GenerateModuleMetadata writes wrong file names in case of customized artifact publications.
### Expected Behavior

The file names available in `*.module` should match the file names created by an actual publication, even if that and the repo-layout have been (slightly) customized.

### Current Behavior

The file names available in `*.module` seem to always use the name of the artifact in combination with its revision, even if the publication removed the latter by purpose. The publication creates a file named `some_lib.jar`, while `*.module` references the same files as `some_lib-0.1.0.jar`. That latter file doesn't exist in the repo and because Gradle's metadata is preferred by default, builds fail.

### Context

I'm using a slightly customized Ivy-publication with a slightly customized repo-layout NOT combining artifact and revision name into one file name. The layout is the following:

    [organization]/[module]/[revision]/[artifact](-[classifier]).[ext]

That worked pretty well for Gradle 5.6, files have been created as expected. While those files are still being created exactly the same way as before, with `GenerateModuleMetadata` the content of `*.module` is preferred over the available `ivy.xml` and builds fail, because the former file references not existing file names.

I additionally didn't find any way to influence how `GenerateModuleMetadata` generates file names. Looking at the source, it seems publications itself render file names, but that leads to different results for some reason in my case.

    private void writeArtifact(PublicationInternal publication, PublishArtifact artifact, JsonWriter jsonWriter) throws IOException {
        if (artifact instanceof PublishArtifactInternal) {
            if (!((PublishArtifactInternal) artifact).shouldBePublished()) {
                return;
            }
        }
        PublicationInternal.PublishedFile publishedFile = publication.getPublishedFile(artifact);

        jsonWriter.beginObject();
        jsonWriter.name("name");
        jsonWriter.value(publishedFile.getName());
        jsonWriter.name("url");
        jsonWriter.value(publishedFile.getUri());

        jsonWriter.name("size");
        jsonWriter.value(artifact.getFile().length());
        writeChecksums(artifact, jsonWriter);

        jsonWriter.endObject();
    }

### Steps to Reproduce 

The attached archive contains an example publishing things into `${HOME}/Downloads/ghi` using `gradlew publish` , which can be changed in `buildSrc\src\main\gradle\publish\ams_ivy\CurrUser.gradle`. That creates an IVY-repo containing a `gradle.module` containing the unexpected file names.

[de.am_soft.build.gradle.zip](https://github.com/gradle/gradle/files/4249742/de.am_soft.build.gradle.zip)
Clipboard03

### Your Environment

gradlew 6.2.1

### PR DESCRIPTION
**Pull request by melix**
This commit works around issue #12339 by disabling publication
of Gradle Module Metadata if using a non standard Ivy repository
layout.

Fixes #12339

### CODE REVIEW

File: subprojects/publish/src/main/java/org/gradle/api/publish/tasks/GenerateModuleMetadata.java [hunk 1]
```diff
@@ -71,6 +71,7 @@
     private final ListProperty<Publication> publications;
     private final RegularFileProperty outputFile;
     private final ChecksumService checksumService;
+    private Supplier<Boolean> enabledIf;
```
Comment (ljacomet) [inline subprojects/publish/src/main/java/org/gradle/api/publish/tasks/GenerateModuleMetadata.java]: ❌  This field is unused.

File: subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java [hunk 2]
```diff
@@ -156,10 +169,49 @@ private void createGenerateMetadataTask(final TaskContainer tasks, final IvyPubl
...
         });
         publication.setModuleDescriptorGenerator(generatorTask);
     }
 
+    private void disableGradleMetadataGenerationIfCustomLayout(NamedDomainObjectList<IvyArtifactRepository> repositories, GenerateModuleMetadata generateTask) {
+        AtomicBoolean didWarn = new AtomicBoolean();
+        Spec<? super Task> checkStandardLayout = task -> {
+            boolean standard = repositories.stream().allMatch(this::hasStandardPattern);
+            if (!standard && !didWarn.getAndSet(true)) {
+                LOGGER.warn("Publication of Gradle Module Metadata is disabled because you have configured an Ivy repository with a non-standard layout");
```
Comment (ljacomet) [inline subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java]: This is worth a mention in the upgrade notes IMO

Comment (melix) [reply subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java]: Does it? It's broken today...

Comment (ljacomet) [reply subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java]: What is broken is consumption. So not all users may have realized it. I think that having an indication of the change is valuable.

Comment (melix) [reply subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java]: I understand that but there's no actionable item here. The upgrade guide explains how to upgrade. Here there's no action to take: upgrade and you get a bugfix...

Comment (ljacomet) [reply subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java]: Ah, you just made me realize that it could be an issue after all.
Say you have a regular remote Ivy repo to which you publish. But you also have a local one, with custom layout (say simpler layout) that you use for validating your publication artifacts.

With this change, the real publication will lose the GMM while it was perfectly valid.

Makes sense?

Comment (melix) [reply subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java]: It does, but you'd still get the warning. Or we need to change how GMM generation works for Ivy repos. And back to square one.

Comment (ljacomet) [reply subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java]: Sorry, should have been clearer: my scenario makes it worth mentioning as a potential breaking change IMO.

File: subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc [hunk 3]
```diff
@@ -38,7 +38,8 @@ Some plugins will break with this new version of Gradle, for example because the
 
 === Potential breaking changes
 
-There were no breaking changes between Gradle 6.3 and 6.4.
+Gradle versions from 6.0 to 6.3.x included could generate bad Gradle Module Metadata when publishing on an Ivy repository which had a custom repository layout.
```
Comment (ljacomet) [inline subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc]: Please add a section header
