### PR TITLE
Print clearer error when copying duplicate file from compressed archive with copy task and strategy = fail

### LINKED ISSUE #20935: Show full explanation for duplicate failures with zipTree
### Expected Behavior
Using a `zipTree` in a copy with `duplicatesStrategy = DuplicatesStrategy.FAIL` should give a clear error when encountering duplicates.

### Current Behavior
The error only lists a generic failure. There is a more specific cause, but it requires `-s` to be seen.
Example:
```
* What went wrong:
Execution failed for task ':worldedit-mod:jar'.
> Could not expand ZIP '/home/octy/Documents/GitHub/WorldEdit/worldedit-forge/build/libs/worldedit-forge-mc1.18.2-7.3.0-SNAPSHOT-dist.jar'.
```

### Context
This has confused others on the project because it seems like an issue with the ZIP itself, instead of showing the intended restriction against duplicates.

### PR DESCRIPTION
**Pull request by tresat**
Fixes #20935.

Addresses zip and tar file trees.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java [hunk 1]
```diff
@@ -23,4 +23,8 @@ public interface FileCopyDetailsInternal extends FileCopyDetails {
     boolean isDefaultDuplicatesStrategy();
 
     CopySpecResolver getSpecResolver();
+
+    String getDisplayName();
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java:27]: This is already implemented by all implementors, but wasn't present on the interface.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java [hunk 2]
```diff
@@ -43,6 +43,8 @@
 import java.util.concurrent.atomic.AtomicBoolean;
 
 public class TarFileTree extends AbstractArchiveFileTree {
+    public static final String TAR_ENTRY_PREFIX = "tar entry";
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java:46]: Extracting these constants turned out to not be necessary, but I left them as a cleanup.

File: subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFileHelper.groovy [hunk 3]
```diff
@@ -291,8 +291,8 @@ class TestFileHelper {
         }
     }
 
-    private static boolean isUnix() {
-        return !System.getProperty('os.name').toLowerCase().contains('windows')
+    private static boolean isWindows() {
```
Comment (tresat) [inline subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFileHelper.groovy:294]: This method's name confused me a little on MacOS.  It's checking for Windows, so let's name it that and invert the tests.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy [hunk 4]
```diff
@@ -2239,4 +2242,121 @@ class CopyTaskIntegrationSpec extends AbstractIntegrationSpec {
         "rename(Transformer)"       | "rename(org.gradle.internal.Transformers.noOpTransformer())"
     }
 
+    // region duplicates in compressed files
+    def "encountering duplicates in a zipTree vs an unzipped dir with DuplicateStrategy.FAIL should give a clear error"() {
+        given: "a directory with a file"
+        TestFile unzippedDir = file("before/files")
+        unzippedDir.file("sub/c.txt").createFile()
```
Comment (big-guy) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:2249]: 💭 Style wise, I think `def`s look better here and `touch()` looks more familiar than `createFile()`

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy [hunk 5]
```diff
@@ -2239,4 +2242,121 @@ class CopyTaskIntegrationSpec extends AbstractIntegrationSpec {
...
+
+        and: "a zip file containing it"
+        TestFile zipFile = file("before/files.zip")
+        unzippedDir.zipTo(zipFile)
+
+        and: "a copy task that copies from both of these, failing on duplicates"
+        buildFile << """
+            task (copy, type: Copy) {
+                from '${separatorsToUnix(unzippedDir.path)}'
+                from zipTree('${separatorsToUnix(zipFile.path)}')
```
Comment (big-guy) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:2259]: I think it's OK to duplicate the file paths here vs having to normalize the paths.  We really only normalize paths like this when they must be absolute in the build script or some output will produce them. 

```suggestion
                from 'before/files'
                from zipTree('before/files.zip')
```

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy [hunk 6]
```diff
@@ -21,11 +21,14 @@ import org.gradle.api.plugins.ExtensionAware
 import org.gradle.integtests.fixtures.AbstractIntegrationSpec
 import org.gradle.integtests.fixtures.TestResources
 import org.gradle.integtests.fixtures.ToBeFixedForConfigurationCache
+import org.gradle.test.fixtures.file.TestFile
 import org.gradle.util.Matchers
 import org.gradle.util.internal.ToBeImplemented
 import org.junit.Rule
 import spock.lang.Issue
 
+import static org.apache.commons.io.FilenameUtils.separatorsToUnix
```
Comment (big-guy) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:30]: ❌ Our fixture for this is `TextUtil.normaliseFileSeparators`

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy [hunk 7]
```diff
@@ -2239,4 +2242,121 @@ class CopyTaskIntegrationSpec extends AbstractIntegrationSpec {
...
+                into 'after'
+                duplicatesStrategy = DuplicatesStrategy.FAIL
+            }
+        """
+
+        expect: "a failure"
+        fails 'copy'
+
+        and: "with a clear failure message"
+        failure.assertHasCause('Encountered duplicate path "sub/c.txt", extracted from "files.zip", during copy operation configured with DuplicatesStrategy.FAIL')
```
Comment (big-guy) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:2269]: 🤔 Usually we use single quotes to highlight paths/names.  

🤔 Does the path to the zip file need to be a fully qualified path? You could have a zip coming from Gradle user home or another task's build output. This makes it look like it might be in the root.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy [hunk 8]
```diff
@@ -2239,4 +2242,121 @@ class CopyTaskIntegrationSpec extends AbstractIntegrationSpec {
...
+
+        and: "another tar file with the same contents"
+        TestFile tarFile2 = file("before/files2.tar")
+        untarredDir.tarTo(tarFile2)
+
+        and: "a copy task that copies from both tar files, failing on duplicates"
+        buildFile << """
+            task (copy, type: Copy) {
+                from tarTree('${separatorsToUnix(tarFile.path)}')
+                from tarTree('${separatorsToUnix(tarFile2.path)}')
```
Comment (big-guy) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:2348]: 🤔 is there any reason to believe that the combination of two tarTrees could behave differently from a tarTree + directory?  Why not a zipTree + tarTree? I think we might be able to get rid of this test.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java [hunk 9]
```diff
@@ -196,7 +200,7 @@ public DetailsImpl(ReadableResourceInternal resource, File expandedDir, TarArchi
 
         @Override
         public String getDisplayName() {
-            return String.format("tar entry %s!%s", resource.getDisplayName(), entry.getName());
+            return String.format("%s %s!%s", TAR_ENTRY_PREFIX, resource.getDisplayName(), entry.getName());
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java:203]: 💭 what was wrong with what it was doing before?

File: subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFileHelper.groovy (hunk 3 above)
Comment (big-guy) [reply subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFileHelper.groovy:294]: 🎉

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java (hunk 1 above)
Comment (big-guy) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java:35]: 💭 would it make sense to make this implement `Describable` instead?

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java [hunk 10]
```diff
@@ -18,9 +18,28 @@
...
+
+    /**
+     * Checks if this file copy details represents a file copy of an entry in a compressed archive.
+     *
+     * @return {@code true} if this file copy details represents a file copy of an entry in a compressed archive; {@code false} otherwise
+     */
+    default boolean isCompressedArchiveEntry() {
+        return false;
+    }
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java:44]: ❌ I don't think we should be exposing this.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java [hunk 11]
```diff
@@ -66,6 +67,30 @@ public WorkResult execute(final CopyActionProcessingStream stream) {
...
+        }
+
+        String pathBeforeExclamation = displayName.substring(0, exclamationIndex);
+        int lastSlashIndex = pathBeforeExclamation.lastIndexOf("/");
+        if (lastSlashIndex == -1) {
+            throw new IllegalStateException("Expected to find '/' in display name of compressed file entry: " + displayName);
+        }
+
+        return pathBeforeExclamation.substring(lastSlashIndex + 1);
+    }
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java:92]: ❌ This isn't what we should do. 

The wording isn't very good and I think focuses on the wrong things. It looks like it's saying there are duplicates in the archive file.

This is the message we produce with the PR now:
> Encountered duplicate path "sub/c.txt", extracted from "files.zip", during copy operation configured with DuplicatesStrategy.FAIL

I think we want to say something like:
> Cannot copy <zip entry> because it has already been copied from <previous source>

IMO, the detail about duplicates strategy isn't useful but we could add "and the copy is configured to not allow duplicates".

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java [hunk 12]
```diff
@@ -55,9 +56,9 @@ public WorkResult execute(final CopyActionProcessingStream stream) {
                     if (strategy == DuplicatesStrategy.EXCLUDE) {
                         return;
                     } else if (strategy == DuplicatesStrategy.FAIL) {
-                        throw new DuplicateFileCopyingException(String.format("Encountered duplicate path \"%s\" during copy operation configured with DuplicatesStrategy.FAIL", details.getRelativePath()));
+                        throw new DuplicateFileCopyingException(String.format("Encountered duplicate path %s during copy operation configured with DuplicatesStrategy.FAIL", explainDuplicateLocation(details)));
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java:59]: ❌ based on what I said below, what about changing this around:

1. Instead of keeping only the RelativePath of visited files, we also keep their copy details (or display name)
2. When creating the exception, we can do something like:
```
throw new DuplicateFileCopyingException(String.format("Cannot copy %s because it has already been copied from %s", details.getDisplayName(), visitedFiles.get(relativePath).getDisplayName()));
```
This produces a message like:
> Cannot copy zip entry /Users/sterling/gits/gradle/subprojects/core/build/tmp/teŝt files/CopyTaskInt.Spec/t9if0/before/files.zip!sub/c.txt because it has already been copied by file '/Users/sterling/gits/gradle/subprojects/core/build/tmp/teŝt files/CopyTaskInt.Spec/t9if0/before/files/sub/c.txt'

We could change the archive entry's display name if we thought that was too technical.

**Review by big-guy — CHANGES_REQUESTED** [review]

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java (hunk 1 above)
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java:35]: Looks like it would.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy (hunk 6 above)
Comment (tresat) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:30]: Good to know - I looked and somehow didn't find this.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy (hunk 7 above)
Comment (tresat) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:2269]: Rewriting message.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy (hunk 8 above)
Comment (tresat) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:2348]: I wasn't sure if the Copy task would somehow optimize thinking "this is the same source, I can skip warning about this this" OR if it would de-duplicate source paths prior to copying.  I can delete these tests if you'd like.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java (hunk 10 above)
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java:38]: I'm getting rid of this, as there's no need after reworking the message, but would like to hear more - why is it a problem if the copy details internally knows whether it's copying from an archive or not?

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java (hunk 12 above)
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java]: I changed the message to this plus also including the destination directory to the message.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecInternal.java [hunk 13]
```diff
@@ -53,6 +54,9 @@ public interface CopySpecInternal extends SyncSpec {
 
     CopySpecInternal preserve(Action<? super PatternFilterable> action);
 
+    @Nullable
+    File getDestinationDir();
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecInternal.java:58]: Already available as destinationDir or destPath, this makes retrieval of the output path consistent.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopyActionExecuter.java [hunk 14]
```diff
@@ -40,6 +40,7 @@ public CopyActionExecuter(Instantiator instantiator, ObjectFactory objectFactory
     public WorkResult execute(final CopySpecInternal spec, CopyAction action) {
         final CopyAction effectiveVisitor = new DuplicateHandlingCopyActionDecorator(
                 new NormalizingCopyActionDecorator(action, fileSystem),
+                spec,
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopyActionExecuter.java:43]: `DuplicateHandlingCopyActionDecorator` now stores the `CopySpec` to use the destination dir in the failure message upon hitting duplicate files.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java [hunk 15]
```diff
@@ -662,16 +663,17 @@ public RelativePath getDestPath() {
...
 
-            if (path.startsWith("/") || path.startsWith(File.separator)) {
-                return RelativePath.parse(false, path);
+            String pathAsString = path.getPath();
+            if (pathAsString.startsWith("/") || pathAsString.startsWith(File.separator)) {
+                return RelativePath.parse(false, pathAsString);
             }
 
-            return RelativePath.parse(false, parentPath, path);
+            return RelativePath.parse(false, parentPath, pathAsString);
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java:676]: Just adjusting from `String` to `File` results with the new method here.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java [hunk 16]
```diff
@@ -242,9 +242,10 @@ public Set<Object> getSourcePaths() {
         return sourcePaths.getFrom();
     }
 
+    @Override
     @Nullable
-    public String getDestPath() {
-        return destDir == null ? null : PATH_NOTATION_PARSER.parseNotation(destDir);
+    public File getDestinationDir() {
+        return destDir == null ? null : new File(PATH_NOTATION_PARSER.parseNotation(destDir));
```
Comment (octylFractal) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java:248]: 🤔 Perhaps this should use `FileOperations#file` instead, so we (1) keep existing `File` objects the same, instead of converting it to `String` and back, and (2) have similar behavior to other methods that convert to `File`. However, I do note that this would result in potential issues if someone was passing a boolean or integer, as that is accepted by the path notation parser but not `file`. I don't know if that's a concern.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy [hunk 17]
```diff
@@ -2239,4 +2240,187 @@ class CopyTaskIntegrationSpec extends AbstractIntegrationSpec {
...
+        def unzippedDir = file("before/files")
+        def unzippedFile = unzippedDir.file("sub/c.txt").touch()
+
+        and: "another directory with the same file"
+        def unzippedDir2 = file("before2/files")
+        def unzippedFile2 = unzippedDir2.file("sub/c2.txt").touch()
+
+        and: "a copy task that copies from both of these, failing on duplicates"
+        buildFile << """
+            task (copy, type: Copy) {
```
Comment (big-guy) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:2254]: 🤔 why are you using this unusual way of declaring the task? Maybe you meant `task copy(type: Copy)`?

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java [hunk 18]
```diff
@@ -23,49 +23,59 @@
...
         this.documentationRegistry = documentationRegistry;
     }
 
     @Override
     public WorkResult execute(final CopyActionProcessingStream stream) {
-        final Set<RelativePath> visitedFiles = new HashSet<>();
+        final Map<RelativePath, String> visitedFiles = new HashMap<>();
 
-        return delegate.execute(action -> stream.process(details -> {
+        return delegate.execute(action -> stream.process((FileCopyDetailsInternal details) -> {
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java:51]: 🤔 maybe we can just make FileCopyDetails a Describable too?

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java (hunk 15 above)
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java:676]: 🤔 This looks all sorts of weird.

`path.getPath` is not quite the same thing as `getDestPath` was returning before.  We're turning `destPath` into a `File` and then going back to a `String` to manipulate it more.

Can we avoid tracking the destination directory completely for now?

I think saying:
> Cannot copy zip entry '/Users/sterling/gits/gradle/subprojects/core/build/tmp/teŝt files/CopyTaskInt.Spec/8mt32/before/files.zip!sub/c.txt' to 'other/sub/c.txt' because file '/Users/sterling/gits/gradle/subprojects/core/build/tmp/teŝt files/CopyTaskInt.Spec/8mt32/before/files/sub/c.txt' has already been copied there.

is already a big improvement and would make the error consistent across all Copy-like tasks (Copy, Jar, etc)

**Review by big-guy — CHANGES_REQUESTED** [review]

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy (hunk 17 above)
Comment (tresat) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy:2254]: Yep, just a typo.  I'm surprised that worked.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java (hunk 18 above)
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java:51]: We can (and I will) do that, but we still need the internal type here to use `isDefaultDuplicatesStrategy().`

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java (hunk 15 above)
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java]: I reverted all this and restored the original `getDestPath()` method.  I was just trying to consolidate near duplicate methods here - the weirdness exists prior to this change.

I think this can keep the destination dir for the message with this change.  I think it makes a clearer message to provide it if at all possible.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
The test failures here looks like a missing install on CI and I don't think they are relevant here.

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
> WARN: This is a feature pull request but no changes to [release note](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/release/notes.md) found.

@ljacomet - Do you think this merits a release note?  It's just a clearer error message.
