### PR TITLE
Fail on unpack failure

### LINKED ISSUE #9033: Fail build for pack/unpack errors
As discussed in https://github.com/gradle/build-cache/issues/1535#issuecomment-476115501, we are adding a lot of complexity to work around issues that are most probably signs of something going very wrong. Examples include the inability to store things in the local cache, or a broken cache artifact.

If we could be more strict about these we could remove a lot of complexity, and perhaps help users identify serious problems that could go unnoticed otherwise.

Actual steps to take:

- fail the build on unpack error (allows the removal of the whole "clean up after unpack failure" codepath)
- fail the build on pack error

Putting this on 6.0 as it is a breaking change in some sense.

### PR DESCRIPTION
**Pull request by lptr**
Previously we used to try a complicated dance to continue even if unpacking a cached result failed. We did this because wanted to avoid a corrupted cache entry breaking a build. However, with real-world usage it looks like hiding these problems causes more grief, and adds quite some complexity to the process. So we are removing this mitigation now.

Fixes #9033

### CODE REVIEW

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationStep.java [hunk 1]
```diff
@@ -99,20 +99,22 @@ public int stepsCount() {
...
 
         Try<ArtifactTransformDependencies> resolvedDependencies = dependenciesResolver.forTransformer(transformer);
-        return resolvedDependencies.getSuccessfulOrElse(dependencies -> {
-            ImmutableList<File> inputArtifacts = subjectToTransform.getFiles();
-            if (inputArtifacts.isEmpty()) {
-                return CacheableInvocation.cached(Try.successful(subjectToTransform.createSubjectFromResult(ImmutableList.of())));
-            } else if (inputArtifacts.size() > 1) {
-                return CacheableInvocation.nonCached(() ->
+        return resolvedDependencies
+            .tryMap(dependencies -> {
```
Comment (wolfs) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationStep.java]: Why do we want to catch exceptions here? When a failure happens here then it seems to be in the Gradle code, so I think the whole build should fail, not only the transform.

Comment (lptr) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationStep.java]: Ah, I merged too quick.

It's a good point. Here's the resolution: https://github.com/gradle/gradle/pull/10148

**Comment by emartynov** [comment]
Why not just ignore this error? I'm fine to not to have this task output cached.
