### PR TITLE
Handle file watcher events when they come in

### LINKED ISSUE #12226: Handle long running idle daemons for VFS retention
Currently, we store all change events which come in from an event driven file watcher in an error list until the next build starts. If a daemon is idle for a longer period of time, and there are many changes in the workspace it is watching, then it can easily run out of memory.

We should prevent this from happening.

---
cc: @gradle/build-cache

### LINKED ISSUE #12232: Endless creation of crashing daemons after upgrading to 6.0.1 or 6.1.1
On my Ubuntu 18.04 jenkins server, I upgraded a project to use 6.1.1 gradle and whenever I run a task like clean or build etc. it starts endlessly spawning daemons that immediately crash. The only reason I can think of was something about not being found in the registry? Downgrading to 5.6.4 fixes the issue. I'll get more helpful information later, but I just had to get everything back to normal.

### PR DESCRIPTION
**Pull request by wolfs**
The event driven watchers now handle the file changes as they come in instead of storing them in memory.

Fixes #12226

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/internal/vfs/DarwinFileWatcherRegistry.java [hunk 1]
```diff
@@ -37,21 +37,23 @@
...
+        super(
+            Native.get(OsxFileEventFunctions.class).startWatching(
                 watchRoots.stream()
                     .map(Path::toString)
                     .collect(Collectors.toList()),
                 // TODO Figure out a good value for this
                 300, TimeUnit.MICROSECONDS,
-                (type, path) -> events.add(WatcherEvent.createEvent(type, path))
-            ));
+                (type, path) -> WatcherEvent.createEvent(type, path).dispatch(handler)
```
Comment (lptr) [inline subprojects/core/src/main/java/org/gradle/internal/vfs/DarwinFileWatcherRegistry.java]: This could probably be inlined now.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/JdkFileWatcherRegistry.java [hunk 2]
```diff
@@ -93,6 +95,7 @@ public void stopWatching(ChangeHandler handler) throws IOException {
             }
         } finally {
             close();
+            handler.close();
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/JdkFileWatcherRegistry.java]: Why do we need to close this now? And why here? If we get the handler injected in the constructor I'd say whoever created it should dispose of it, too.

File: subprojects/core/src/main/java/org/gradle/internal/vfs/DarwinFileWatcherRegistry.java (hunk 1 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/internal/vfs/DarwinFileWatcherRegistry.java]: I inlined `WatcherEvent`.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/JdkFileWatcherRegistry.java (hunk 2 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/JdkFileWatcherRegistry.java]: I am returning the statistics for logging from stopWatching. Not there is no need to close the handler any more.

File: subprojects/core/src/main/java/org/gradle/internal/vfs/WindowsFileWatcherRegistry.java [hunk 3]
```diff
@@ -37,11 +36,11 @@
 
     public WindowsFileWatcherRegistry(Set<Path> watchRoots, ChangeHandler handler) {
         super(
-            Native.get(WindowsFileEventFunctions.class).startWatching(
+            callback -> Native.get(WindowsFileEventFunctions.class).startWatching(
                 watchRoots.stream()
                     .map(Path::toString)
                     .collect(Collectors.toList()),
-                (type, path) -> WatcherEvent.createEvent(type, path).dispatch(handler)
+                callback
```
Comment (lptr) [inline subprojects/core/src/main/java/org/gradle/internal/vfs/WindowsFileWatcherRegistry.java]: This kind of constructor callback still bothers me, but I have no better idea atm.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/NoopFileWatcherRegistry.java [hunk 4]
```diff
@@ -30,9 +30,11 @@
     private static final Logger LOGGER = LoggerFactory.getLogger(NoopFileWatcherRegistry.class);
 
     private static final FileWatcherRegistry INSTANCE = new NoopFileWatcherRegistry();
+    private static final FileWatchingStatistics NOOP_FILE_WATCHING_STATISTICS = new FileWatchingStatistics(true, 0);
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/NoopFileWatcherRegistry.java]: This will make us log that the VFS was dropped due to an unknown event. I think that's fine for now, but we need something better for when file watching is disabled. Perhaps we should have the `FileWatcherRegistry` issue those logs instead, and just do nothing in this implementation?

Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/NoopFileWatcherRegistry.java]: This is not about file watching being disabled, but about file watching being enabled and not supported on the current OS/Architecture. We should issue a more specific warning in this case when you try to enable it.

Comment (lptr) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/NoopFileWatcherRegistry.java]: That's what I wanted to say, too. :) I think moving the logging to the `FileWatcherRegistry` is going to be necessary to issue a more specific message.
