### PR TITLE
Revised plan for usage checks for verification variants

### LINKED ISSUE #19231: Add usage checks for verification variants - revised plan
This issue replaces 2 previous issues:

- https://github.com/gradle/gradle/issues/19007
- https://github.com/gradle/gradle/issues/19009

with a new direction informed by exploring those.

# New Plan
We are going to add a check during *publication*, where if a component uses the`Category` attribute with the( incubating) value of "verification" then publication will fail with an error.

We will match the attribute key on the string "org.gradle.category".  This check will be hardcoded.

We will add documentation to the code and user guide making it very clear not to use this category if you intent to publish.  We will link to this documentation from the error message.

We will include the work to add a "(i)" indicator to the outgoingVariants report if a configuration contains an attribute in the verification category. 

# Will Not Do
Any sort of feature flag to hide production or consumption of new verification variants.
Any sort of configurable attribute publishing ban flag or list.
Any related validity checks at the time a variant is added to component (we will wait until the component is published to fail).

### PR DESCRIPTION
**Pull request by tresat**
Fixes #19231

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test QF

File: subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java [hunk 1]
```diff
@@ -74,6 +81,21 @@
 
     boolean isPublishBuildId();
 
+    default void checkForUnpublishableAttributes(SoftwareComponentInternal component, DocumentationRegistry documentationRegistry) {
```
Comment (tresat) [inline subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java:84]: I moved this here to avoid duplicating between Ivy and Maven publications, which don't share a common base class.  Perhaps they should, then this could be made non-public?  It's only public on the Internal type though.

Or I could move copies back into `DefaultIvyPublication` and `DefaultMavenPublication`.  Thoughts?

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java [hunk 2]
```diff
@@ -1087,6 +1088,12 @@ public void preventFromFurtherMutation() {
         }
     }
 
+    @Override
+    public boolean isIncubating() {
```
Comment (tresat) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java:1092]: I can't call this from the publishing side, which doesn't deal in `Configuration`s, but `Component`s, which is too bad.  I though consolidating the check here with the check on the publishing side wouldn't be necessary.

I don't think this side needs to check for `String` attributes which use 'org.gradle.category' - they won't show up in `outgoingVariants` as incubating, but that's fine.  it's the publishing check that seemed to need to be more comprehensive.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle clean

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
I added descriptions to the new variants in the last commit for when they show up in `outgoingVariants`.  Let me know if this is okay, otherwise I can revert it.

File: subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java (hunk 1 above)
Comment (ljacomet) [reply subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java:84]: I wonder about that. We know that `Configuration` and its hierarchy is going to be a challenge to evolve.
And I am pretty sure there are users out there of `ConfigurationInternal`.

So I would recommend finding a different location for that method, possible as a static one in some helper type.

**Review by ljacomet — COMMENTED** [review]
Looks good overall! Thanks for doing configuration description!

Added a reply to your question about `ConfigurationInternal`

File: subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java (hunk 1 above)
Comment (big-guy) [reply subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java:84]: I was thinking that we only needed to block someone from inadvertently publishing the new variants that we've added (sources, jacoco execution data and test results) and not prevent any variant with this category from being published. This is a roundabout way of doing sort of the same thing as https://github.com/gradle/gradle/pull/19056 (which tied publishing to a particular attribute).

Could we just check `isIncubating` in `ConfigurationVariantMapping.collectUsageContexts`?  IIUC, someone would need to call `addVariantsFromConfiguration` with one of the new variant configurations to force it to be added to the software component.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java (hunk 2 above)
Comment (big-guy) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java:1092]: Would it make sense to just make this a mutable property of the configuration and in every place we have a new variant that we want to keep unstable, we could set that flag?

File: subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaIntegTest.groovy [hunk 3]
```diff
@@ -140,4 +140,92 @@ class MavenPublishJavaIntegTest extends AbstractMavenPublishJavaIntegTest {
         javaLibrary.assertPublished()
     }
 
+    def "can not publish variant with attribute specifying category = verification"() {
```
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaIntegTest.groovy:143]: I'll add a new test, that's a good idea.

After talking with @ljacomet , we settled on the approach that particular attribute of Category with the value of verification would always be banned from publishing, so it's definitely fair to say this is a different (hopefully better) way of doing the same sort of check as #19056.  I thought that's what we wanted here.

If we change to a mutable property, couldn't a malicious user find and set the flag at runtime via reflection as well, allowing publishing?  Or create a new configuration with all the same attributes and publish THAT instead?

If I move the check to inside `collectUsageContexts()`, then the check lives in the plugins project, is this okay?  Are you saying there are other ways to publish that would bypass the check where it lives now?  

My commit from just now addresses Louis' comment, but I don't think has any bearing on the others.

**Comment by tresat** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge
