### PR TITLE
Copy resolution listeners when a configuration is copied

### LINKED ISSUE #1567: Before resolve actions are not copied when a configuration is copied
### Expected Behavior

When a configuration is copied any before resolve actions registered with the configuration are registered with the copy. This would be consistent with the behaviour for actions registered with the configuration's resolution strategy.

### Current Behavior

Before resolve actions are not copied to the configuration copy.

### Context

This has caused some unexpected behaviour in the interactions between the [Dependency Management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) and the [Versions plugin](https://github.com/ben-manes/gradle-versions-plugin):

- https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/155
- https://github.com/ben-manes/gradle-versions-plugin/issues/123#issuecomment-258680712

### Steps to Reproduce (for bugs)

This script will reproduce the behaviour:

```groovy
apply plugin: 'java'

ext.beforeResolveAction = new BeforeResolveAction()
ext.eachDependencyAction = new EachDependencyAction()

configurations.compile.incoming.beforeResolve(beforeResolveAction)
configurations.compile.resolutionStrategy.eachDependency(eachDependencyAction)

repositories {
    mavenCentral()
}

dependencies {
    compile 'commons-logging:commons-logging:1.2'
}

task(resolveOriginal) {
    doLast {
        configurations.compile.resolve()
        assertActionsCalled()
    }
}

task(resolveCopy) {
    doLast {
        configurations.compile.copy().resolve()
        assertActionsCalled()
    }
}

def assertActionsCalled() {
    if (!eachDependencyAction.called) {
        throw new GradleException('Each dependency action was not called')
    }
    if (!beforeResolveAction.called) {
        throw new GradleException('Before resolve action was not called')
    }
}

class BeforeResolveAction implements Action<ResolvableDependencies> {

    boolean called

    void execute(ResolvableDependencies dependencies) {
        called = true
    }

}

class EachDependencyAction implements Action<DependencyResolveDetails> {

    boolean called

    void execute(DependencyResolveDetails details) {
        called = true
    }

}
```

Building the `resolveOriginal` task will succeed, but building the `resolveCopy` task will fail as the before resolve action hasn't been called.

### Your Environment

I do not believe that this behaviour is environment-specific. The problem exists in Gradle 2.x and 3.x.

### PR DESCRIPTION
**Pull request by wilkinsona**
## Context

This PR fixes #1567

#### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [ ] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

#### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java [hunk 1]
```diff
@@ -119,7 +119,7 @@
     private final CompositeDomainObjectSet<PublishArtifact> inheritedArtifacts;
     private final DefaultPublishArtifactSet allArtifacts;
     private final ConfigurationResolvableDependencies resolvableDependencies = new ConfigurationResolvableDependencies();
-    private final ListenerBroadcast<DependencyResolutionListener> dependencyResolutionListeners;
+    private ListenerBroadcast<DependencyResolutionListener> dependencyResolutionListeners;
```
Comment (bmuschko) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java]: I don't see a reason why the field should not be `final`. Can we change that back?

File: subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy [hunk 2]
```diff
@@ -765,6 +764,35 @@ class DefaultConfigurationSpec extends Specification {
         assert copiedConfiguration.extendsFrom.empty
     }
 
+    def "Calls resolve actions and closures from original configuration when copied configuration is resolved"() {
```
Comment (bmuschko) [inline subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy]: Can you add an `@Issue` annotation to indicate the relevant issue? I would like like this: `@Issue("gradle/gradle#1567")`.

File: subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy [hunk 3]
```diff
@@ -765,6 +764,35 @@ class DefaultConfigurationSpec extends Specification {
...
+        Action<ResolvableDependencies> beforeResolveAction = Mock()
+        Action<ResolvableDependencies> afterResolveAction = Mock()
+        def config = conf("conf")
+        def beforeResolveCalled
+        def afterResolveCalled
+
+        given:
```
Comment (bmuschko) [inline subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy]: Maybe extend the test case to demonstrate that a copy of a configuration with no before and after resolve action also has zero before and after resolve actions.

File: subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy [hunk 4]
```diff
@@ -765,6 +764,35 @@ class DefaultConfigurationSpec extends Specification {
         assert copiedConfiguration.extendsFrom.empty
     }
 
+    def "Calls resolve actions and closures from original configuration when copied configuration is resolved"() {
+        Action<ResolvableDependencies> beforeResolveAction = Mock()
+        Action<ResolvableDependencies> afterResolveAction = Mock()
+        def config = conf("conf")
+        def beforeResolveCalled
```
Comment (bmuschko) [inline subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy]: We should probably initialize both fields with `false` because it's not strongly typed and therefore would have a `null` default value.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java (hunk 1 above)
Comment (wilkinsona) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java]: It needs to be assigned when the copy is being made

**Comment by wilkinsona** [comment]
I've made the requested changes (other than the field being final)

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java (hunk 1 above)
Comment (bmuschko) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java]: I see, thanks for checking.

**Comment by bmuschko** [comment]
Thanks for making the changes. It has been merged.

**Comment by DanielThomas** [comment]
@bmuschko this broke our resolution rules plugin. If the copied `beforeResolve` retains a reference to the original configuration, or `resolutionStrategy`, for instance:

`configurations.all { config ->
  config.incoming.beforeResolve {
        <do something with config>
  }
}`

Then existing code depending on this behavior fails. If this is the plan going forward, then `ResolvableDependencies` would need to expose it's reference to the configuration, and this documented as a breaking change.

**Comment by oehme** [comment]
I don't think `ResolveableDependencies` should expose a `Configuration`. It already exposes a `DependencySet` that you can inspect/mutate. What would be the use case for inspecting the Configuration?

**Comment by DanielThomas** [comment]
The case is in any way mutating the configuration by either adding dependencies, resolution strategies etc. where the calculation of that logic is expensive, and it's desirable to delay until `beforeResolve`.

In this case, we're copying the configuration and applying module alignments using `resolutionStrategy.eachDependency`. We have to do that in `beforeResolve` so we're not doing that expensive calculation except if the configuration is to be resolved, and we can't mutate the `DependencySet` because we need to affect transitive dependencies.

**Comment by DanielThomas** [comment]
In the alignment case, we could catch the recursion differently, but this breaks our dependency lock and recommender plugins too.

**Comment by oehme** [comment]
@DanielThomas could you check the DependencySet for equality with the one of the configuration you originally registered on? In that case we could just document this as a breaking change.

A long term solution proposed by @adammurdoch would be a new dependency resolution hook that allows plugins to influence which version we pick, based on the whole graph (with potential respins). That would also be a huge performance boost, because these plugins could then stop copying configurations and resolving multiple times.

**Comment by DanielThomas** [comment]
@oehme that would allow us to short-circuit the alignment, but this still breaks dependency locks and recommender: they'll affect the original, instead of the copy.

**Comment by oehme** [comment]
> but this still breaks dependency locks and recommender: they'll affect the original, instead of the copy.

I'm afraid I don't understand this yet. Would this not solve the problem?

```
conf.incoming.beforeResolve { incoming ->
  if (incoming == conf.incoming) { //don't let the copy call this again
    maybeApplyLock(conf, extension, overrides, globalLockFilename, lockFilename)
  }
}
```

**Comment by DanielThomas** [comment]
That would solve the issue with alignment, but doesn't allow the other plugins to work with copied configurations. We need the `beforeResolve`s in the other plugins to affect the _copy_, so it can successfully resolve. With this change, when `beforeResolve` is called on the copy, we're holding a reference to the original.

**Comment by oehme** [comment]
Maybe I'm missing something, here's what I understand:

The beforeResolve listeners were not copied before. Now they are. The if-condition I proposed makes sure that the copied listener turns into a noop on the copy. That is semantically equivalent to not copying the listener at all. So whatever worked before should work with that.

**Comment by DanielThomas** [comment]
Let's put the original example aside, as this impacts any use of `beforeResolve` that uses it as a configuration lifecycle hook, rather than as a way of mutating resolvable dependencies. 

The simple pattern being this:

```
configurations.all { conf ->
	conf.incoming.beforeResolve {
		<do anything with 'conf' here>
	}
}

configurations.compile.copy().resolve()
```

Previously, these were not copied, which was fine because you simply add the configuration to the `ConfigurationContainer` to get the add handlers configured correctly. With this change, the `beforeResolve` handler on the copy will refer to the original configuration, instead of the copy.

That's why I suggest that if you want to move forward with copying these, you differentiate between explicitly configured handlers and those contributed by ConfigurationContainer after add handlers, and exclude the latter from the copy, then you can:

- Add the configuration to the ConfigurationContainer to get the handler OR
- Implement support to process add handlers in copy (#1555)

**Comment by DanielThomas** [comment]
@oehme that workaround works a treat! Thanks for the assist.
