### PR TITLE
Propagate ValueSource description for missing values

### LINKED ISSUE #25716: Improve error messaging of built-in providers
### Expected Behavior

An exception message that contains the environment variable name that could not be found rather than "this provider".

Doing a short debug in `AbstractMinimalProvider`, it seems that `cannotQueryValueOf` is totally ready for a nice message via `getDisplayName()`, and even a causal chain.

It seems that adding the following method to `DefaultValueSourceProviderFactory.ValueSourceProvider` would solve this problem:
```java
@Override protected String getDeclaredDisplayName() {
  ValueSource source = value.source();
  return source instanceof Describable ? source.getDisplayName() : super.getDeclaredDisplayName();
}
```
`LazilyObtainedValue` might need some adjustments to cache the `source` along with the value too if it has been obtained.

### Current Behavior (optional)

```gradle
providers.environmentVariable("NON_EXISTENT_ENV_VAR").get()
```

```
org.gradle.api.internal.provider.MissingValueException: Cannot query the value of this provider because it has no value available.
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:75)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:93)
        at Build_gradle....(build.gradle.kts:78)
```

If possible, taking it a step further:
```gradle
providers.environmentVariable("NON_EXISTENT_ENV_VAR").map(::File).get()
```
should still contain the root cause in some form.

### Context

To improve developer experience, and bring down diagnostic time.

### PR DESCRIPTION
**Pull request by urdak**
Check if a ValueSource is Describable and include the DisplayName in the path of the Missing Value.

Part of #25716 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ljacomet** [comment]
Thank you for your contribution!

This PR has a valid DCO and tests. The relevant team for this area will confirm the design of the implementation choices.

***

@gradle/bt-configuration Please confirm that it fixes the referenced issue or is one step towards that

File: platforms/core-configuration/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderIntegrationTest.groovy [hunk 1]
```diff
@@ -274,6 +274,27 @@ class ProviderIntegrationTest extends AbstractIntegrationSpec {
                 - task ':run' property 'p2'""".stripIndent())
     }
 
+    def "reasonable error message if the provider has no value"() {
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderIntegrationTest.groovy:277]: 💭 I'd remove this test since we already have the one in `DefaultValueSourceProviderFactoryTest`. I can do that after the merge

**Review by bamboo — APPROVED** [review]

**Comment by bamboo** [comment]
Thanks, @urdak!

**Comment by urdak** [comment]
Looks like the test I added fails on Windows:
```
 e.message == """Cannot query the value of this provider because it has no value available. The value of this provider is derived from: nullValueSource"""
  | |       |
  | |       false
  | |       1 difference (99% similarity)
  | |       Cannot query the value of this provider because it has no value available.(\r)\nThe value of this provider is derived from: nullValueSource
  | |       Cannot query the value of this provider because it has no value available.(-~)\nThe value of this provider is derived from: nullValueSource
```
Should I resolve this issue myself? I guess just adding `System.lineSeparator()` instead a new line should fix it.

**Comment by bamboo** [comment]
Sorry for the lag, @urdak, I fixed it via `TextUtil.toPlatformLineSeparators`.
