### PR TITLE
Properly expand unique snapshot in file names

### LINKED ISSUE #21111: Adding files to variants created from ComponentMetadataRules does not work when SNAPSHOT versions are used
### Expected Behavior

A ComponentMetadataRule that derives a new variant and adds files to that variant should work with SNAPSHOT dependencies where the file's name actually contains a timestamped version. 

### Current Behavior

It's not possible to add files to a variant using `withFiles { addFile("") }`. Gradle will construct the wrong file name.

### Context

I've a plugin that adds a `ComponentMetadataRule` for downloading POM files that live alongside the other artifacts inside a repository. I need to POM files in order to extract data form the `licenses` element in the POM. My rule does the following:

```kotlin
withFiles {
    removeAllFiles()
    addFile("${context.details.id.name}-${context.details.id.version}.pom")
}
```

However when this rule processes a snapshot version, I'm seeing the following error:

```
Cannot fingerprint input file property 'rootSpec$1': Could not resolve all files for configuration ':poms'.
> Could not resolve all files for configuration ':poms'.
  > Could not find commons-lang3-3.2.2-SNAPSHOT-3.2.2-SNAPSHOT.pom (org.apache.commons:commons-lang3:3.2.2-SNAPSHOT:20140111.132309-5).
    Searched in the following locations:
        https://repository.apache.org/content/repositories/snapshots/org/apache/commons/commons-lang3/3.2.2-SNAPSHOT/commons-lang3-3.2.2-SNAPSHOT.pom
```

### Steps to Reproduce 

1. Clone  https://github.com/britter/gradle-sandbox/
2. `cd component-metadata-rules-SNAPSHOTS/build.gradle.kts`
3. `./gradlew downloadPoms`

### Your Environment

Build scan URL: https://scans.gradle.com/s/hi2dnfy5yvhnk/failure#1

### PR DESCRIPTION
**Pull request by ljacomet**
When using component metadata rules, the underlying artifact reference
did not properly expand a snapshot version to its unique timestamp.

With these changes, this is now happening, and is behaving the same as a
similar reference in the metadata directly.

Fixes #21111

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by jbartok — APPROVED** [review]

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenSnapshotResolveIntegrationTest.groovy [hunk 1]
```diff
@@ -1075,6 +1075,90 @@ class CheckIsChangingRule implements ComponentMetadataRule {
...
+
+    void execute(ComponentMetadataContext context) {
+        context.details.maybeAddVariant("pom", baseVariant) {
+            attributes {
+                attribute(Category.CATEGORY_ATTRIBUTE, getObjects().named(Category, Category.DOCUMENTATION))
+                attribute(DocsType.DOCS_TYPE_ATTRIBUTE, getObjects().named(DocsType, "pom"))
+            }
+            withFiles {
+                removeAllFiles()
+                addFile("\${context.details.id.name}-\${context.details.id.version}.pom")
```
Comment (h0tk3y) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenSnapshotResolveIntegrationTest.groovy:1133]: Minor suggestion, feel free to ignore: if it was a black box to test, it could also be worth it to test how this works for files that Gradle is usually not aware of, unlike a POM which should be definitely there and even already downloaded at this point.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/DefaultExternalResourceArtifactResolver.java [hunk 2]
```diff
@@ -117,6 +117,16 @@ private LocallyAvailableExternalResource downloadByUrl(List<ResourcePattern> pat
         return null;
     }
 
+    private String normalizeRelativeUrl(UrlBackedArtifactMetadata artifact) {
+        ModuleComponentIdentifier componentId = artifact.getComponentId();
+        if (componentId instanceof MavenUniqueSnapshotComponentIdentifier) {
+            // We need to replace the `-SNAPSHOT` in the relative URL but only for the version part
+            MavenUniqueSnapshotComponentIdentifier snapshotComponentId = (MavenUniqueSnapshotComponentIdentifier) componentId;
+            return artifact.getRelativeUrl().replace("-" + snapshotComponentId.getSnapshotVersion(), "-" + snapshotComponentId.getTimestampedVersion());
```
Comment (h0tk3y) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/DefaultExternalResourceArtifactResolver.java:125]: Corner case: can the snapshot version appear anywhere else in the URL where we don't actually need to replace it? Do we want to replace only the specific occurrences? Or is this not a realistic case?

**Review by h0tk3y — APPROVED** [review]

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/DefaultExternalResourceArtifactResolver.java (hunk 2 above)
Comment (ljacomet) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/DefaultExternalResourceArtifactResolver.java:125]: Yes it does, as a `/<version>/` path element, which is why the replacement is done for `-<version>` which appears only in the file name according to Maven repository conventions.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenSnapshotResolveIntegrationTest.groovy (hunk 1 above)
Comment (ljacomet) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenSnapshotResolveIntegrationTest.groovy:1133]: The POM file downloaded that way is handled as an artifact, not as the metadata file. Gradle currently does not optimize this and will download and cache the file in different locations as metadata files are handled specially.

So the test is valid.

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle test and merge
