### PR TITLE
Always configure intermediate parents when a child project is configured

### LINKED ISSUE #14552: Gradle fails with "Could not apply requested plugin" in some scenarios using configuration on demand
I'm seeing a bug where a Gradle plugin defined in an included build applied to multiple project fails in certain scenarios (when certain tasks are requested). 

### Expected Behavior
Given each of the projects independently builds fine, I would expect requesting several of them to build at the same time would also build fine.

### Current Behavior
The build fails with an error like the following:

```
❯ ./gradlew :projects:baz:classes :projects:foo:bar:classes --scan
Configuration on demand is an incubating feature.

> Configure project :projects:foo:bar
Hello, world! Applying to bar

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sean_abraham/projects/personal/gradle-repros/included-build-plugin-application/projects/foo/build.gradle' line: 4

* What went wrong:
Could not apply requested plugin [id: 'com.example.buildplugin'] as it does not provide a plugin with id 'com.example.buildplugin'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'com.example.buildplugin' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

When both `:projects:baz` and `:projects:foo:bar` each build find (as well as `projects:foo:` which `:projects:baz` depends on). Note this both fails using the `plugins { }` block as well as legacy plugin application format (buildscript classpath dependencies + `apply plugin ...`).

See the included repro for further details

### Context
This is blocking my ability to refactor a module into two, both of which need the same build plugin defined (which is defined in an included build).

### Steps to Reproduce 
https://github.com/seanabraham/included-build-plugin-gradle-repro

### Your Environment
Build scan URL: https://scans.gradle.com/s/w4yopkrbla6lg

### PR DESCRIPTION
**Pull request by bigdaz**
When configure-on-demand is enabled, a project is evaluated only when required. In a nested
project structure, this can mean that a child project is configured without it's parent.
However, in a nested project structure, the parent project contributes a classloader that is used
by the child.

These 2 effects combined can result in:
- The parent project scope class loader is defined before the scope is locked.
  This violates the check enabled by `org.gradle.classloaderscope.strict`.
- In a composite build, plugins applied to the parent project may not be visible.

This commit fixes this by ensuring that intermediate parent projects are always configured
before a child project. (The root project is already configured before any children).

Fixes #14552

### CODE REVIEW

**Comment by eskatos** [comment]
Awesome!
This should also fix https://github.com/gradle/gradle/issues/4823

File: subprojects/core/src/main/java/org/gradle/execution/TaskPathProjectEvaluator.java [hunk 1]
```diff
@@ -33,6 +33,11 @@ public void configure(ProjectInternal project) {
         if (cancellationToken.isCancellationRequested()) {
             throw new BuildCancelledException();
         }
+        // Need to configure intermediate parent projects for configure-on-demand
+        ProjectInternal parentProject = project.getParent();
+        if (parentProject != null && parentProject != project.getRootProject()) {
+            configure(project.getParent());
```
Comment (bamboo) [inline subprojects/core/src/main/java/org/gradle/execution/TaskPathProjectEvaluator.java:39]: 💄 should reuse `parentProject` here

Comment (bigdaz) [reply subprojects/core/src/main/java/org/gradle/execution/TaskPathProjectEvaluator.java]: Of course! You can tell it's been a while since I've written code. Fixed.

**Comment by bigdaz** [comment]
@bamboo @big-guy : `parentProject !- project.getRootProject()` is a minor optimization. Should I just leave it out and assume that re-configuring a Project instance is cheap?  It looks like we are already making a this assumption here: https://github.com/gradle/gradle/blob/a138710ab109e271b17ee48dc49b359284cd3f66/subprojects/core/src/main/java/org/gradle/execution/DefaultTasksBuildExecutionAction.java#L54

It looks like any work has a short-circuit in `LifecycleProjectEvaluator`, but not in `ConfigureActionsProjectEvaluator`. As long as we continue to treat `LifecycleProjectEvaluator` as the entry point to all project evaluation, I guess we are safe.

**Comment by bigdaz** [comment]
@bot-gradle test RFM

**Comment by bigdaz** [comment]
@bot-gradle test RFM

**Comment by bigdaz** [comment]
@bot-gradle test RFM
