### PR TITLE
Use groupId:artifactId when converting maven to gradle project

### LINKED ISSUE #3078: gradle init on Maven project results in StackOverflow
### Expected Behavior

`gradle init` invoked on the root project of my Maven multimodule should complete without errors or fail with meaningful output

### Current Behavior

`gradle init` invoked on the root project of my Maven multimodule will fail with a StackOverflow
```
bof@MBLMIXFBO /cygdrive/d/res-apps.trunk.svn/res-apps
$ gradle init --stacktrace
:wrapper UP-TO-DATE
:init
Maven to Gradle conversion is an incubating feature.
:init FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':init'.
> java.lang.StackOverflowError (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':init'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.StackOverflowError
        at org.gradle.buildinit.plugins.internal.maven.Maven2Gradle.generateFqn(Maven2Gradle.groovy:218)
        at org.gradle.buildinit.plugins.internal.maven.Maven2Gradle.generateFqn(Maven2Gradle.groovy:223)
******** MANY MORE TIMES *******************
        at org.gradle.buildinit.plugins.internal.maven.Maven2Gradle.generateFqn(Maven2Gradle.groovy:223)
        at org.gradle.buildinit.plugins.internal.maven.Maven2Gradle.generateFqn(Maven2Gradle.groovy:223)


* Get more help at https://help.gradle.org

BUILD FAILED in 2s
2 actionable tasks: 1 executed, 1 up-to-date
```

### Context

We have a modestly big multimodules Maven - Java/Spring project, with some (10ish) levels of pom projects. Maven builds are slow and this affects our productivity, I wanted to try gradle and I was just starting with `gradle init`.

### Steps to Reproduce (for bugs)

I cannot provide an example because our project is closed-sourced, and I have absolutely no hint about what caused the infinite recursion in those precise lines.
If someone can suggest me about what caused the infinite recursion I will forge a synthetic example.

### Your Environment

This is my environment versions, I'll be glad to provide more info.

```
$ gradle --version

------------------------------------------------------------
Gradle 4.2.1
------------------------------------------------------------

Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_31 (Oracle Corporation 25.31-b07)
OS:           Windows 8.1 6.3 amd64
```

### PR DESCRIPTION
**Pull request by blindpirate**
### Context

This fixes #3078 

Previously, `Maven2Gradle` used `artifactId` as unique identifier when converting a maven project to Gradle project, which is incorrect because it's possible to have same artifact id but different group id in the same project. https://github.com/jschneider/gradle-reproduce-3078 provides a reproduction for this issue.

This PR uses `groupId:artifactId` as the unique identifier to avoid this issue.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bmuschko Would you like to take a look? It's pretty simple.

File: subprojects/build-init/src/main/groovy/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.groovy [hunk 1]
```diff
@@ -215,16 +217,22 @@ ${globalExclusions(this.effectivePom)}
...
-                proj.artifactId.text() == project.parent.artifactId.text()
+                getModuleIdentifier(proj) == getModuleIdentifier(project.parent)
             }
             if (parentInBuild) {
                 generateFqn(parentInBuild, allProjects, buffer)
             }
         }
     }
 
+    private ModuleIdentifier getModuleIdentifier(def project) {
```
Comment (bmuschko) [inline subprojects/build-init/src/main/groovy/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.groovy]: :o: I'd type `project` here for better understanding. In the long run we might want to convert the class into Java.

File: subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/maven/MavenProjectsCreatorSpec.groovy [hunk 2]
```diff
@@ -141,4 +141,60 @@ class MavenProjectsCreatorSpec extends Specification {
         then:
         gradleProject.contains("compileOnly group: 'org.gradle', name: 'build-init', version:'1.0.0'")
     }
+
+    def "creates multi module project with same artifactId"() {
```
Comment (bmuschko) [inline subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/maven/MavenProjectsCreatorSpec.groovy]: :x: We should probably also add a test case that tests where `project.groupId` == null.

File: subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/maven/MavenProjectsCreatorSpec.groovy [hunk 3]
```diff
@@ -141,4 +141,60 @@ class MavenProjectsCreatorSpec extends Specification {
...
+  <parent>
+    <groupId>org.gradle</groupId>
+    <artifactId>test</artifactId>
+    <version>0</version>
+  </parent>
+
+  <modelVersion>4.0.0</modelVersion>
+  <artifactId>commons</artifactId>
+  <packaging>pom</packaging>
+
```
Comment (blindpirate) [inline subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/maven/MavenProjectsCreatorSpec.groovy]: If I understand you correctly, this pom does have `project.groupId==null`

File: subprojects/build-init/src/main/groovy/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.groovy (hunk 1 above)
Comment (blindpirate) [reply subprojects/build-init/src/main/groovy/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.groovy]: Good catch. I felt inconvenient as well when I first saw this code.

File: subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/maven/MavenProjectsCreatorSpec.groovy (hunk 3 above)
Comment (bmuschko) [reply subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/maven/MavenProjectsCreatorSpec.groovy]: Oh, I see. You are right. Preferably I'd love to see two different test cases or a `where` clause instead so that it's easier to see that both cases are covered.
