### PR TITLE
Immediately fail task on CC-induced execution problem

### LINKED ISSUE #32542: CC problems reported at execution time can be hidden by build cache on subsequent runs
For instance, accessing the project instance in the task action results in the build failure on the first run. However, on the second run, the offending task is up-to-date and the build "succeeds".

Here is an integration test draft that shows the current behavior:
```groovy
        String cacheDir = temporaryFolder.file("cache-dir").createDir().absoluteFile.toURI().toString()
        def localBuildCache = new TestBuildCache(new File(new URI(cacheDir).path))

        settingsFile << localBuildCache.localCacheConfiguration()

        javaFile "src/main/java/Main.java", """public class Main {}"""

        buildFile """
            plugins { id("java") }

            version = "foo-version"
            tasks.compileJava { // using a cacheable task
                doLast {
                    println("version:" + project.version.toString())
                }
            }
        """

        when:
        fails "compileJava", "--build-cache", "--configuration-cache"

        then:
        // TODO: it seem wrong to allow execution-time to observe this incorrect value
        outputContains("version:unspecified")

        failureCauseContains("Invocation of 'Task.project' by task ':compileJava' at execution time is unsupported.")

        when:
        run "compileJava", "--build-cache", "--configuration-cache"

        then:
        outputContains("Calculating task graph as no cached configuration is available for tasks: compileJava")

        // TODO: expected:
        // failureCauseContains("Invocation of 'Task.project' by task ':compileJava' at execution time is unsupported.")

        // TODO: actual:
        outputContains("> Task :compileJava UP-TO-DATE")
```

### PR DESCRIPTION
**Pull request by alllex**
Fixes #32542

We now fail tasks immediately when a CC problem is detected at execution time, treating it as an interrupting problem (see #33541). This resolves the original issue by propagating the interrupting failure through the regular execution engine pipeline, marking the offensive task as failed and avoid caching it.

This PR preserves the behavior of CC warning mode: when enabled, it turns normally interrupting execution problems into deferred problems, which in the warning mode are only reported, but don't fail the build.

### CODE REVIEW

**Comment by alllex** [comment]
@bot-gradle test this on linux without pts

**Comment by alllex** [comment]
@bot-gradle test this on linux without pts

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/problems/ConfigurationCacheProblems.kt [hunk 1]
```diff
@@ -165,6 +165,11 @@ class ConfigurationCacheProblems(
         onProblem(problem, ProblemSeverity.Interrupting)
     }
 
+    override fun onExecutionTimeProblem(problem: PropertyProblem) {
+        val severity = if (isWarningMode) ProblemSeverity.Deferred else ProblemSeverity.Interrupting
+        onProblem(problem, severity)
+    }
```
Comment (alllex) [inline platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/problems/ConfigurationCacheProblems.kt:171]: ℹ️  This is the main change for production code. Previously, the execution-time problems were treated as deferred.

File: platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheIncompatibleTasksIntegrationTest.groovy [hunk 2]
```diff
@@ -258,29 +313,6 @@ class ConfigurationCacheIncompatibleTasksIntegrationTest extends AbstractConfigu
         "provider { task.project }.map { it.name }" || _
     }
 
-    def "tasks that access project at execution time emit problems when incompatible task is present"() {
```
Comment (alllex) [inline platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheIncompatibleTasksIntegrationTest.groovy:261]: ℹ️  Replaced by a sibling test `execution-time problems in tasks that are not marked incompatible are treated as interrupting failures when incompatible tasks are also scheduled`

File: platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheProblemReportingIntegrationTest.groovy [hunk 3]
```diff
@@ -521,128 +522,58 @@ class ConfigurationCacheProblemReportingIntegrationTest extends AbstractConfigur
         }
     }
 
-    def "task execution problems are reported and fail the build by default invalidating the cache"() {
```
Comment (alllex) [inline platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheProblemReportingIntegrationTest.groovy:524]: ℹ️  replaced by the new tests in `ConfigurationCacheTaskExecutionIntegrationTest`

File: platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheProblemReportingIntegrationTest.groovy [hunk 4]
```diff
@@ -812,92 +744,13 @@ class ConfigurationCacheProblemReportingIntegrationTest extends AbstractConfigur
...
-            withProblem("Build file 'build.gradle': line 8: invocation of 'Task.project' at execution time is unsupported.")
             withProblem("Task `:moreProblems` of type `BrokenTask`: cannot deserialize object of type 'org.gradle.api.Project' as these are not supported with the configuration cache.")
+            withProblem("Task `:moreProblems` of type `BrokenTask`: cannot deserialize object of type 'org.gradle.api.artifacts.ConfigurationContainer' as these are not supported with the configuration cache.")
             withProblem("Task `:problems` of type `BrokenTask`: cannot deserialize object of type 'org.gradle.api.Project' as these are not supported with the configuration cache.")
-            totalProblemsCount = 4
-            problemsWithStackTraceCount = 2
-        }
-    }
-
-    def "reports #invocation access during execution"() {
```
Comment (alllex) [inline platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheProblemReportingIntegrationTest.groovy:825]: ℹ️ replaced by the new tests in `ConfigurationCacheTaskExecutionIntegrationTest`

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/initialization/ConfigurationCacheProblemsListener.kt [hunk 5]
```diff
@@ -107,25 +107,25 @@ class DefaultConfigurationCacheProblemsListener internal constructor(
...
+                    text(" at execution time is unsupported with the configuration cache.")
                 }
             }
                 .exception(
                     if (isExecutingOtherTask) {
-                        "Execution of $runningTask caused invocation of '$invocationDescription' by $task at execution time which is unsupported."
+                        "Execution of $runningTask caused invocation of '$invocationDescription' by $task at execution time which is unsupported with the configuration cache."
                     } else {
-                        "Invocation of '$invocationDescription' by $task at execution time is unsupported."
+                        "Invocation of '$invocationDescription' by $task at execution time is unsupported with the configuration cache."
```
Comment (alllex) [inline platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/initialization/ConfigurationCacheProblemsListener.kt:128]: ℹ️  We already mention CC in the same manner in all serialization-time problems. Now that the execution-time problems result in independent build failures, it's even more important to indicate that they are caused by CC being enabled.

**Comment by alllex** [comment]
@bot-gradle test this without pts

**Comment by alllex** [comment]
@bot-gradle test this without pts

File: platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheProblemReportingIntegrationTest.groovy [hunk 6]
```diff
@@ -1335,26 +1194,55 @@ class ConfigurationCacheProblemReportingIntegrationTest extends AbstractConfigur
...
-            withProblem("Build file 'build.gradle': line 530: invocation of 'Task.project' at execution time is unsupported.")
-            withProblem("Build file 'build.gradle': line 535: invocation of 'Task.project' at execution time is unsupported.")
-            withProblem("Build file 'build.gradle': line 540: invocation of 'Task.project' at execution time is unsupported.")
-            withProblem("Build file 'build.gradle': line 545: invocation of 'Task.project' at execution time is unsupported.")
-            withProblem("Build file 'build.gradle': line 55: invocation of 'Task.project' at execution time is unsupported.")
-            withProblem("Build file 'build.gradle': line 550: invocation of 'Task.project' at execution time is unsupported.")
-            withProblem("Build file 'build.gradle': line 555: invocation of 'Task.project' at execution time is unsupported.")
+            withProblem("Task `:broken100` of type `org.gradle.api.DefaultTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.")
```
Comment (bamboo) [inline platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheProblemReportingIntegrationTest.groovy]: 💅 Couldn't we make these into a loop now?

Comment (alllex) [reply platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheProblemReportingIntegrationTest.groovy]: Done
