### PR TITLE
Don't cache task with dangling symlinks in outputs

### LINKED ISSUE #9906: Don't cache task with dangling symlinks in outputs
Continuing #9708 for caching

When snapshotting we sometimes fail if we encounter a dangling symlink.
We want to change this, and treat a dangling symlink as if we encountered a missing file.

* [x] Add test to assert that we're disabling the build cache if we have broken symlinks in the output
Note: that we still can't cache output with dangling symlinks. Throwing an exception in this case is sufficient.

### PR DESCRIPTION
**Pull request by paplorinc**
Fixes #9906

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolver.java [hunk 1]
```diff
@@ -64,13 +65,21 @@ public DefaultTaskCacheabilityResolver(RelativeFilePathResolver relativeFilePath
...
             if (!(spec instanceof CacheableOutputFilePropertySpec)) {
-                return Optional.of(new CachingDisabledReason(
-                    CachingDisabledReasonCategory.NON_CACHEABLE_OUTPUT,
+                return Optional.of(new CachingDisabledReason(CachingDisabledReasonCategory.NON_CACHEABLE_OUTPUT,
                     "Output property '" + spec.getPropertyName() + "' contains a file tree"
                 ));
             }
         }
 
+        Optional<File> invalidRootFile = outputFileProperties.stream()
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolver.java]: is it okay to scan all properties?

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolver.java [hunk 2]
```diff
@@ -64,13 +65,21 @@ public DefaultTaskCacheabilityResolver(RelativeFilePathResolver relativeFilePath
...
+            .flatMap(spec -> spec.getPropertyFiles().getFiles().stream())
+            .filter(file -> !file.exists()).findAny();
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolver.java]: should we use something more sophisticated than `.exists`, i.e. resolve it or check if it doesn't exist and is a symlink?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/OutputBrokenSymlinkCacheIntegrationTest.groovy [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+            }
+        """
+        assert !link.exists()
+
+        when:
+        runTask(this)
+        then:
+        executedAndNotSkipped ":${taskName}"
+        outputContains "Caching disabled for task ':${taskName}'"
+        outputContains "Output contains uncacheable file: '${root}'"
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/OutputBrokenSymlinkCacheIntegrationTest.groovy]: is it okay that we're complaining about root here, and not the actual broken link?

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolver.java (hunk 2 above)
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolver.java]: I'm a bit confused about this, since if the task creates the symlink, how could it disable caching before running it, since the output is not yet a broken link.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy [hunk 4]
```diff
@@ -380,6 +381,32 @@ class CacheTaskArchiveErrorIntegrationTest extends AbstractIntegrationSpec {
...
+                outputs.cacheIf { true }
+            }
+        """
+
+        when:
+        executer.withStackTraceChecksDisabled().withBuildCacheEnabled()
+        run "producesLink"
+        then:
+        executedAndNotSkipped ":producesLink"
+        outputContains "Couldn't read file content 'tree-outputDirectory/link'"
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy]: The error message should contain the absolute path of the file we couldn't read and not the relative path it will have in the archive.

Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy]: Done, thanks

**Comment by paplorinc** [comment]
Merged, thanks for the reviews.
