### PR TITLE
Shrink incremental compilation state files

### LINKED ISSUE #14669: Duplicate key com/.../.../.../DisplayBoxesActivity.java
### Expected Behavior
The project should successfully compile.

### Current Behavior
Every time I try to compile I get:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Duplicate key com/.../.../.../DisplayBoxesActivity.java
``` 

### Context
I'm just attempting to run my project and I'm unsure why this does not compile. I have even tried reverting my project to stages where it did compile and I still cant get anything to work. 

### Your Environment
Build scan URL:
**The build scan was not published due to a configuration problem.**

### LINKED ISSUE #16806: Performance regression after incremental compiler change
### Context

https://github.com/gradle/gradle/pull/16536 seems to introduce some performance regression, which can be ~6% in some scenario:

https://builds.gradle.org/repository/download/Gradle_Master_Check_PerformanceTestSlowLinuxbucket11/42534158:id/results/performance/build/test-results-largeMonolithicJavaProjectPerformanceTest.zip!/performance-tests/report/tests/clean-assemble-with-empty-local-cache---largeMonolithicJavaProject---TaskOutputCachingJavaPerformanceTest.html#result1990747628

Bisect to https://github.com/gradle/gradle/commit/a59133ca10bd660cf47802adc634b05b344d6419

Or 1%~2% in other scenarios:

https://builds.gradle.org/repository/download/Gradle_Master_Check_PerformanceTestTestLinuxbucket33/42539557:id/results/performance/build/test-results-largeMonolithicGroovyProjectPerformanceTest.zip!/performance-tests/report/tests/assemble-for-non-abi-change---largeMonolithicGroovyProject---JavaIncrementalExecutionPerformanceTest.html#result1990747628

https://builds.gradle.org/repository/download/Gradle_Master_Check_PerformanceTestSlowLinuxbucket5/42534152:id/results/performance/build/test-results-largeJavaMultiProjectPerformanceTest.zip!/performance-tests/report/tests/clean-checkout---largeJavaMultiProject---JavaFirstUsePerformanceTest.html

I'll have to rebaseline all to unblock `master`.

### PR DESCRIPTION
**Pull request by oehme**
Deduplicate class and resource names across whole PreviousCompilationData
-------------------------------------------------------------------------

Before this change, we had duplicate class names in the classpath snapshot,
output snapshot, annotation processing data and constants mapping. This was
bloating the previous compilation data file significantly.

With this change, each name is only written once and reused across all
these data structures.

Merge sourceClassesMapping into previousCompilationData
-------------------------------------------------------

This removes an inefficient plain text file and replaces it with
an efficient binary representation. It also avoids duplicate storage
since the class names are already contained in the previous compilation
data, so the only thing we're newly adding are the relative source paths.
These are now optimized with our hierarchical name serializer.

As part of this change, the Groovy and Java compiler have been aligned to
both use the ApiCompilerResult, which opens up the path for incremental
annotation processing and constant tracking in Groovy.

There is an inconsistency in how the two languages handle class files
for which the source could not be determined. Groovy does a full recompile,
Java just ignores it. It turns out that the Java case is because we don't
determine the relative path for files generated by annotation processors.
I've fixed half of the issue by adding the generated sources dir to the
CompilationSourceDirs. However, there is also the possibility to generate
class files directly from an annotation processor and in that case our class
name collector will not see that class. In order to keep this scenario incremental,
I've accepted the inconsistent behavior for now. This should be fixed in a later
change, so that annotation processing correctly tracks generated class files
and both Java and Groovy do a full recompile for any files that are untracked.

The CompilerApiData now distinguishes between whether it supports only source to
class mapping or whether it also supports constant mapping. This is required to
make Groovy work correctly, as Groovy does not yet collect constant data, but does
collect source to class data.

Simplify ConstantDependentsMapping
----------------------------------

Tracking the visited classes is unnecessary. It was previously used in the
merging code, but this code really only needed the set of changed classes,
which was already given by the RecompilationSpec

Replace IntSet with DependentSet, as we already have efficient serialization
for those and the Strings on the compiler API side are deduplicated already.

Make hierarchical name serialization denser
-------------------------------------------

Split names along package separators, nested class separators, file separators
and camel case borders. Give each prefix/suffix an integer ID and write that ID
whenever the same prefix/suffix is encountered in a name.

Use constants analysis when minifying classpath snapshots
---------------------------------------------------------

Now that we have proper constant tracking, we no longer need to keep all classes
on the classpath which have constants, but only those that were actually used.

Correct handling of array types in ClassDependenciesVisitor
-----------------------------------------------------------

I noticed during profiling that we were sometimes referencing array types in our
class analyis, which we should never do. I traced this back to the inconsistent
handling in the ClassDependenciesVisitor. I've simplified this so that handling
of array and primitive types is now centralized, so that they are always unwrapped
or ignored correctly.

Results
========

- gradle/gradle now uses 20MB, down from 49.1 MB. Could be even less if we implemented
constant tracking for Groovy, as that would allow us to discard all unused constant
holders form the analysis file.
- largeMonolithicJavaProject now uses 10.6 MB, down from 23 MB

Fixes #16806
Fixes #14669

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by oehme** [comment]
@melix FYI

File: subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java [hunk 1]
```diff
@@ -129,6 +134,10 @@ protected DaemonForkOptions toDaemonForkOptions(GroovyJavaJointCompileSpec spec)
         // This should come from the compiler classpath only
         gradleFilterSpec.disallowPackage("org.gradle.api.internal.tasks.compile");
 
+        gradleFilterSpec.allowClass(ApiCompilerResult.class);
```
Comment (oehme) [inline subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java:137]: This shouldn't be necessary, but currently is because the worker API handles return types differently depending on whether you use process isolation or classpath isolation. In the former case, the return value is serialized and deserialized, so the correct class is returned. In the latter case, the result is returned directly, which means it is not an instance of the expected class unless we allow that class to leak through here. Should probably be fixed in the worker API, so that it always serializes/deserializes results, but that seemed out of scope for this change.

File: subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/GroovyJavaJointIncrementalCompilationIntegrationTest.groovy [hunk 2]
```diff
@@ -63,11 +63,11 @@ class GroovyJavaJointIncrementalCompilationIntegrationTest extends AbstractJavaG
         where:
         scenario                                    | initialSet            | firstChange                   | firstBuildMessage                                        | secondChange                  | secondBuildMessage
         'Add Java files to Groovy file set'         | ['G']                 | ['G', 'J']                    | 'non-Groovy file'                                        | ['G', 'J']                    | 'UP-TO-DATE'
-        'Add Groovy files to Java file set'         | ['J']                 | ['G', 'J']                    | 'unable to get source-classes mapping'                   | ['G', 'J.changed']            | 'non-Groovy file'
+        'Add Groovy files to Java file set'         | ['J']                 | ['G', 'J']                    | 'G.groovy has been added'                                | ['G', 'J.changed']            | 'non-Groovy file'
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/GroovyJavaJointIncrementalCompilationIntegrationTest.groovy:66]: This is now fixed because previously we had no distinction between "no mapping" and "empty mapping". Now we do with the `CompilerApiData.isAvailable`

File: subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/GroovySourceIncrementalCompilationIntegrationTest.groovy [hunk 3]
```diff
@@ -156,17 +156,24 @@ class A2{}
     def 'merge old class source mappings if no recompilation required'() {
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/GroovySourceIncrementalCompilationIntegrationTest.groovy:156]: This was testing an implementation detail. I've fixed it to test the resulting behavior instead.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java [hunk 4]
```diff
@@ -131,7 +133,6 @@ public ClassSetAnalysisData reduceToTypesAffecting(ClassSetAnalysisData other) {
                 usedClasses.add(cls);
             }
         }
-        usedClasses.addAll(classesToConstants.keySet());
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java:134]: This was unnecessarily inefficient - We were adding the constants before the transitive hull operation. But constants are constant and can't be affected by others, so we didn't need all their upstream dependencies. This is now fixed, along with using less constant holders when possible. This had by far the biggest impact on the analysis file.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java [hunk 5]
```diff
@@ -146,27 +147,35 @@ public ClassSetAnalysisData reduceToTypesAffecting(ClassSetAnalysisData other) {
...
-            }
-            DependentsSet dependentsSet = this.dependents.get(usedClass);
-            if (dependentsSet != null) {
-                if (dependentsSet.isDependencyToAll()) {
-                    dependents.put(usedClass, dependentsSet);
-                } else {
-                    Set<String> usedAccessibleClasses = new HashSet<>(dependentsSet.getAccessibleDependentClasses());
-                    usedAccessibleClasses.retainAll(usedClasses);
-                    dependents.put(usedClass, DependentsSet.dependentClasses(Collections.emptySet(), usedAccessibleClasses));
+                DependentsSet dependentsSet = this.dependents.get(usedClass);
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java:163]: Moved this up into the if-statement, so we only keep classes that are actually on the classpath. This exludes classes that are referenced, but not on the classpath. This happens e.g. with the `gradleApi` JAR, which has references to types that it doesn't include.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java [hunk 6]
```diff
@@ -17,27 +17,25 @@
...
-import java.util.Optional;
 
 /**
  * A converter which infers the class names from the file name.
  */
 public class FileNameDerivingClassNameConverter implements SourceFileClassNameConverter {
     @Override
     public Collection<String> getClassNames(String sourceFileRelativePath) {
-        return Collections.singleton(findClassNameForRelativePath(sourceFileRelativePath));
+        if (sourceFileRelativePath.endsWith(".java")) {
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java:27]: Just making it clear here that this class should never be used by the Groovy compiler - If it is accidentally used, the Groovy compiler will silently ignore all changes, because it will return the file name as the class name. This cost me quite a bit of time to track down, so I decided to leave this in even though it is now (correctly) never used by the Groovy compiler.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/serialization/HierarchicalNameSerializer.java [hunk 7]
```diff
@@ -0,0 +1,104 @@
...
+ */
+public class HierarchicalNameSerializer extends AbstractSerializer<String> {
+
+    private final Interner<String> interner;
+    private final BiMap<Integer, String> namesById = HashBiMap.create();
+    private final CharMatcher separatorMatcher;
+
+    public HierarchicalNameSerializer(Interner<String> interner) {
+        this.interner = interner;
+        this.separatorMatcher = CharMatcher.anyOf(".$/").or(CharMatcher.inRange('A', 'Z'));
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/serialization/HierarchicalNameSerializer.java:44]: This is pretty much the only new thing here - Splitting on camel case and slash in addition to dot and dollar. Saves quite a bit of space for repetitive names like `xxxIntegrationTest`.

File: subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java (hunk 1 above)
Comment (lptr) [reply subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java:135]: I think these comments would be good to have in code, too.

Comment (oehme) [reply subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java:135]: Done

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/compilerapi/constants/ConstantsAnalysisResult.java [hunk 8]
```diff
@@ -16,15 +16,31 @@
 
 package org.gradle.api.internal.tasks.compile.incremental.compilerapi.constants;
 
-
+import java.io.Serializable;
 import java.util.Optional;
 
-public interface ConstantsAnalysisResult {
+public class ConstantsAnalysisResult implements Serializable {
```
Comment (melix) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/compilerapi/constants/ConstantsAnalysisResult.java:22]: We should think about changing how this works. It's a bit weird to serialize the builder and pass it from the compiler daemon to the daemon. Instead I think we should eventually (not in this PR) change this so that the mapping is built locally _then_ passed to the daemon. This can be done by implementing our custom `writeObject` which would trigger finalization of the builder. Currently not easily doable because the datastructure that we use _out_ of the builder, the mapping itself, includes classes which are not serializable or not efficiently serialized. This means we should think about a more efficient communication protocol between the compiler daemon and the client.

The advantage is that we would perform the analysis and the mapping building in the compiler daemon itself, which is done (usually) out of process so this leaves the daemon free to do other things in between.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java [hunk 9]
```diff
@@ -146,27 +147,35 @@ public ClassSetAnalysisData reduceToTypesAffecting(ClassSetAnalysisData other) {
             }
         }
 
+        Set<String> usedConstantSources = compilerApiData.isSupportsConstantsMapping()
+            ? compilerApiData.getConstantToClassMapping().getConstantDependents().keySet()
+            : classesToConstants.keySet();
+
+        usedClasses.addAll(usedConstantSources);
+
         Map<String, HashCode> classHashes = new HashMap<>(usedClasses.size());
```
Comment (melix) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java:156]: This datastructure looks a bit inefficient. We create 3 hashmaps from class to whatever. There's confusing redundancy with `ClassAnalysis` actually. We should think about merging those.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java (hunk 5 above)
Comment (melix) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java:163]: do we have a test case covering this change?

**Review by melix — APPROVED** [review]
That's nice improvements! I left a number of comments and fixed some myself but this shouldn't block merging.

**Comment by melix** [comment]
@bot-gradle test this

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java (hunk 9 above)
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java:156]: ClassAnalysis tracks forward dependencies, this here tracks reverse dependencies. Also, in general the keys of these maps can be different. i.e. `dependents` can have more keys than `classHashes` because dependents can contain information about classes outside a JAR that this JAR uses.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/compilerapi/constants/ConstantsAnalysisResult.java (hunk 8 above)
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/compilerapi/constants/ConstantsAnalysisResult.java:22]: I'm not sure what problem that would solve. Have we identified a performance problem here?

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java (hunk 5 above)
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java:163]: It's a performance optimization, so the perf tests should handle regressions here.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java (hunk 9 above)
Comment (melix) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java:156]: Yes but hash maps are quite memory intensive and having a domain object which stores the `HashCode` + dependents + constants, even if some of them are empty, is probably more efficient.

Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java:156]: You would still be left with two maps in that case, because as mentioned above, `dependents.keySet` is a superset of `classHashes.keySet`. So you'd still need to track the dependents of those external classes. The code you see here is a special case where we drop all external classes, because we know it is safe (we're looking at the whole classpath). But that's not how ClassSetAnalysisData generally works.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/compilerapi/constants/ConstantsAnalysisResult.java (hunk 8 above)
Comment (melix) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/compilerapi/constants/ConstantsAnalysisResult.java:22]: It's more a logical problem than an performance one. The "builder" should actually live on the compiler worker. There's no need for the builder on the consumer (daemon) side. We do this by convenience only. IF, we want to fix this, it could have the nice side effect of improving performance by delegating the work of building the actual final structure to the compiler worker instead of the daemon, which is free to do other tasks in parallel.

**Comment by melix** [comment]
@bot-gradle test and merge

**Comment by melix** [comment]
@bot-gradle test and merge
