### PR TITLE
Make `addJvmArguments` TAPI method append the arguments instead of setting it

### LINKED ISSUE #31462: The Gradle Tooling API resets Daemon JVM arguments that are defined in gradle.properties
### Current Behavior

The `org.gradle.tooling.ConfigurableLauncher#addJvmArguments(java.lang.String...)` function resets the JVM arguments from other sources.
For example, it resets JVM arguments that are defined in the `gradle.properties` file.

### Expected Behavior

The `org.gradle.tooling.ConfigurableLauncher#addJvmArguments(java.lang.String...)` function should add the JVM arguments to the arguments from other sources.
For example, it should merge JVM arguments that are defined in the `gradle.properties` file and arguments that are defined by tooling API.

### Context (optional)

In IntelliJ IDEA, we use Gradle tooling API to run sync and tasks in Gradle projects. In particular, we defined custom JVM arguments for the debugger agent, telemetry agent, profiler agent, http[s] proxy settings, Android SDK setup, etc. Also, we want to keep all user-defined properties in their project. We use org.gradle.tooling.ConfigurableLauncher#addJvmArguments(java.lang.String...) for preparing JVM arguments. However,  this function resets all user-defined properties. Therefore, to achieve this result, we need to reimplement the logic of Gradle JVM arguments resolution that fails from time to time.

We would greatly appreciate it if this JVM arguments merging process would be implemented on the Gradle tooling API. This will help us get rid of the problem of Gradle reverse engineering. 

### Self-contained Reproducer Project

1. Download attached project [gradle-tooling-api.zip](https://github.com/user-attachments/files/17962363/gradle-tooling-api.zip).
2. Run the `./gradlew run` command.
     * It will show output from the nested process that was run by Gradle tooling API. Here, we can see that `my-argument` is defined, but no `gradle-argument` and no `-Xmx2g`. These arguments are defined in the gradle.properties files in the test project but were reset by the tooling TAPI. (It is a bug).
```
INIT_SCRIPT.my-argument = 'Defined by ToolingApiMain'
INIT_SCRIPT.gradle-argument = null
INIT_SCRIPT.jvmArgs = [
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED
--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
--add-opens=java.base/java.nio.charset=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
-Dfile.encoding=UTF-8
-Duser.country=DE
-Duser.language=en
-Duser.variant
-javaagent:/Users/Sergey.Vorobyov/.gradle/wrapper/dists/gradle-8.10-bin/deqhafrv1ntovfmgh0nh3npr9/gradle-8.10/lib/agents/gradle-instrumentation-agent-8.10.jar
]
```
3. Comment line 35 in the src/main/java/org/example/ToolingApiMain.java file.
    * It defines the `my-argument` JVM argument for the nested Gradle process.
4. Run the `./gradlew run` command, again.
    * Here, we can see that `my-argument` isn't defined, but `gradle-argument` and no `-Xmx2g` arguments are defined.
```
INIT_SCRIPT.my-argument = null
INIT_SCRIPT.gradle-argument = Defined by gradle.properties
INIT_SCRIPT.jvmArgs = [
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED
--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
--add-opens=java.base/java.nio.charset=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
-Xmx2g
-Dfile.encoding=UTF-8
-Duser.country=DE
-Duser.language=en
-Duser.variant
-javaagent:/Users/Sergey.Vorobyov/.gradle/wrapper/dists/gradle-8.10-bin/deqhafrv1ntovfmgh0nh3npr9/gradle-8.10/lib/agents/gradle-instrumentation-agent-8.10.jar
]
```

### Gradle version

8.10

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by hegyibalint**
Fixes #31462

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by hegyibalint** [comment]
@bot-gradle test this

**Comment by hegyibalint** [comment]
Survived an ACTR

File: platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/parameters/ConsumerOperationParameters.java [hunk 1]
```diff
@@ -403,8 +444,25 @@ public File getJavaHome() {
...
+            return null;
+        } else {
+            // ...otherwise, return the combined list of JVM arguments
+            List<String> arguments = new ArrayList<>(baseJvmArguments);
+            arguments.addAll(additionalJvmArguments);
+            return arguments;
+        }
+    }
+
+    public List<String> getBaseJvmArguments() {
```
Comment (donat) [inline platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/parameters/ConsumerOperationParameters.java:460]: ❌ There's a missing usecase that we should consider supporting. What if the client want to actively delete the jvmArgs. I think the desired spec for base jvmargs should be as follows:
- 1. client does not call setJvmArgs() - daemon-calculated jvm args should be used
- 2. client calls setJvmArgs(emptyList()) - daemon-calculated jvm args should be ignored
- 3. client calls setJvmArgs(listOf(myarg)) - daemon-calculated jvm args should be overwritten with the client-supplied args

**Review by donat — CHANGES_REQUESTED** [review]
Looks good. I have a couple of minor suggestion and there's a usecase that we did not discuss.

File: platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java [hunk 2]
```diff
@@ -346,10 +346,23 @@ private Parameters initParams(ProviderOperationParameters operationParameters) {
...
 
-        //override the params with the explicit settings provided by the tooling api
-        List<String> jvmArguments = operationParameters.getJvmArguments();
-        if (jvmArguments != null) {
-            daemonParams.setJvmArgs(jvmArguments);
+        // Since 8.13, we split the daemon JVM args into base and additional JVM args (#31462)
+        // When calling the following new methods, the following can happen:
+        // - < 8.13: the new split will return a null
+        // - >=8.13: the new split will return a non-null value, clearly signifying that the method is supported.
+        List<String> baseJvmArguments = operationParameters.getBaseJvmArguments(null);
```
Comment (donat) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java:353]: Idea: You can create a local (empty) list, pass it as arguments and check for reference equality to see if `getBaseJvmArguments` was available on the `operationParameters` proxy.

File: platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/parameters/ConsumerOperationParameters.java (hunk 1 above)
Comment (hegyibalint) [reply platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/parameters/ConsumerOperationParameters.java:460]: This poses a problem, as we used the tri-state logic (null, empty, something) with the following semantics:
 - null meant that the method didn't exist, and we act accordingly
 - empty list means that the method exists, but the user didn't set anything
 - non-empty list means that the user set something, and we should override

Based on your comment, we should have four states:
 - incompatible: before 8.13, using the old behavior
 - default: daemon-calculated jvm args should be used
 - ignore: daemon-calculated jvm args should be ignored
 - override: daemon-calculated jvm args should be overwritten with the client-supplied args

As with a tri-state value, we cannot do four things. this needs another solution.

File: platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/parameters/ConsumerOperationParameters.java [hunk 3]
```diff
@@ -403,8 +444,25 @@ public File getJavaHome() {
         return javaHome;
     }
 
+    @Nullable
     public List<String> getJvmArguments() {
-        return jvmArguments;
+        if (baseJvmArguments.isEmpty() && additionalJvmArguments.isEmpty()) {
+            // To keep the old behavior, when no JVM arguments are set, return null...
+            return null;
```
[the remark this answers is not in the document]
Comment (hegyibalint) [reply platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/parameters/ConsumerOperationParameters.java:451]: Correct

**Review by ljacomet — COMMENTED** [review]
From discussions today, this feels related to the following issue:
* #31484 

Is the fix proposed here taking care of that other issue?
Does the issue add information that could make us consider an alternative fix?

File: platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java [hunk 4]
```diff
@@ -346,10 +347,28 @@ private Parameters initParams(ProviderOperationParameters operationParameters) {
...
+        // Since 8.13, we split the daemon JVM args into base and additional JVM args (#31462)
+        // When calling the following new methods, the following states can happen:
+        // - incompatible (before 8.13 provider): falling back to old behavior,
+        // - not used: no methods should be called, default daemon JVM arguments are applied
+        // - used:
+        //   - base JVM arguments (if supplied) override the default daemon JVM arguments
+        //   - additional JVM (if supplied) applied on top of the set JVM arguments
+        try {
+            List<String> baseJvmArguments = operationParameters.getBaseJvmArguments();
+            if (baseJvmArguments != null && !baseJvmArguments.isEmpty()) {
```
Comment (donat) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java:359]: ❌ Null should mean that we don't call `setJvmArgs()`.

File: platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java [hunk 5]
```diff
@@ -346,10 +347,28 @@ private Parameters initParams(ProviderOperationParameters operationParameters) {
...
-        List<String> jvmArguments = operationParameters.getJvmArguments();
-        if (jvmArguments != null) {
-            daemonParams.setJvmArgs(jvmArguments);
+        // Since 8.13, we split the daemon JVM args into base and additional JVM args (#31462)
+        // When calling the following new methods, the following states can happen:
+        // - incompatible (before 8.13 provider): falling back to old behavior,
+        // - not used: no methods should be called, default daemon JVM arguments are applied
+        // - used:
+        //   - base JVM arguments (if supplied) override the default daemon JVM arguments
+        //   - additional JVM (if supplied) applied on top of the set JVM arguments
```
Comment (donat) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java:356]: Thanks for making it clear and traceable why the change hapened 🎉

File: platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java (hunk 4 above)
Comment (donat) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java:359]: ❌ 
- Null should mean that we don't call setJvmArgs().
- empty and non-empty list means the same: setJvmArgs()  should be called.

File: platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java [hunk 6]
```diff
@@ -346,10 +347,28 @@ private Parameters initParams(ProviderOperationParameters operationParameters) {
...
+        try {
+            List<String> baseJvmArguments = operationParameters.getBaseJvmArguments();
+            if (baseJvmArguments != null && !baseJvmArguments.isEmpty()) {
+                daemonParams.setJvmArgs(baseJvmArguments);
+            }
+            List<String> additionalJvmArguments = operationParameters.getAdditionalJvmArguments();
+            if (additionalJvmArguments != null && !additionalJvmArguments.isEmpty()) {
+                daemonParams.addJvmArgs(additionalJvmArguments);
+            }
```
Comment (donat) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java:365]: This is correct, but the `isEmpty()` check is probably redundant as `addJvmArgs(emptyList())` is, iiuc, a no-op.

File: platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/connection/ProviderOperationParameters.java [hunk 7]
```diff
@@ -51,11 +51,30 @@ public interface ProviderOperationParameters {
     File getJavaHome();
 
     /**
-     * @return When null, use the provider's default JVM arguments. When empty, use no JVM arguments.
+     * Returns a backward-compatible concatenated list of {@link #getBaseJvmArguments()} and {@link #getAdditionalJvmArguments()}.
+     * Deduplication is the responsibility of the caller.
```
Comment (donat) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/connection/ProviderOperationParameters.java:55]:
```suggestion
     * Returns the concatenated list of {@link #getBaseJvmArguments()} and {@link #getAdditionalJvmArguments()}. The method is only kept for backwards compatibility (see #31462) to support Gradle versions where {@link #getBaseJvmArguments()} and  {@link #getAdditionalJvmArguments()} is not yet available.
```

File: platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r813/ProblemProgressEventCrossVersionTest.groovy [hunk 8]
```diff
@@ -256,6 +260,7 @@ class ProblemProgressEventCrossVersionTest extends ToolingApiSpecification {
     }
 
     @TargetGradleVersion("=8.5")
+    @Requires(IntegTestPreconditions.JavaHomeWithDifferentVersionAvailable)
```
Comment (donat) [inline platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r813/ProblemProgressEventCrossVersionTest.groovy:263]: 🎉 Thanks for fixing the test!

File: platforms/ide/tooling-api/src/test/groovy/org/gradle/tooling/internal/consumer/parameters/ConsumerOperationParametersTest.groovy
Comment (donat) [inline platforms/ide/tooling-api/src/test/groovy/org/gradle/tooling/internal/consumer/parameters/ConsumerOperationParametersTest.groovy:1]: ❌ Do we have a cross-version test coverage that we test the new behaviour?

**Review by donat — CHANGES_REQUESTED** [review]

File: platforms/core-runtime/client-services/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java
Comment (donat) [inline platforms/core-runtime/client-services/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java:1]: ❌ Please mention this behavioural change as a potential breaking change in the release notes.

Comment (hegyibalint) [reply platforms/core-runtime/client-services/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java:1]: Do you still think there is anything worth mentioning? This was a bug (which luckily didn't become a feature).

File: platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java [hunk 9]
```diff
@@ -346,10 +347,25 @@ private Parameters initParams(ProviderOperationParameters operationParameters) {
...
+            // See LongRunningOperation.setJvmArguments(java.lang.String...)
+            if (baseJvmArguments != null && !baseJvmArguments.isEmpty()) {
+                daemonParams.setJvmArgs(baseJvmArguments);
+            }
+            List<String> additionalJvmArguments = operationParameters.getAdditionalJvmArguments();
+            if (additionalJvmArguments != null) {
+                daemonParams.addJvmArgs(additionalJvmArguments);
+            }
+        } catch (UnsupportedMethodException ex) {
+            // See
```
Comment (donat) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java:364]: 💄 Reference missing

File: platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/AbstractLongRunningOperation.java [hunk 10]
```diff
@@ -120,7 +120,7 @@ public T setJavaHome(File javaHome) {
 
     @Override
     public T setJvmArguments(String... jvmArguments) {
-        operationParamsBuilder.setJvmArguments(rationalizeInput(jvmArguments));
+        operationParamsBuilder.setBaseJvmArguments(CollectionUtils.toList(jvmArguments));
```
Comment (donat) [inline platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/AbstractLongRunningOperation.java:123]: ❓ Shouldn't we keep `rationalizeInput` here?
```suggestion
        operationParamsBuilder.setBaseJvmArguments(rationalizeInput(CollectionUtils.toList(jvmArguments)));
```

**Review by donat — APPROVED** [review]

File: platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/AbstractLongRunningOperation.java (hunk 10 above)
Comment (hegyibalint) [reply platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/AbstractLongRunningOperation.java:123]: You are right about this; this can use `rationalizeInput` now.

File: platforms/core-runtime/client-services/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java
Comment (donat) [reply platforms/core-runtime/client-services/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java:1]: Yes, it worths mentioning. Even if it's a fix, it's also a change in behaviour. There might be users out there who depend on the wrong behaviour and will be surprised when their perceived "good" state breaks. In that case we should be able to point at the "potential breaking changes" section in our documentation saying that the change is expected.

**Review by donat — CHANGES_REQUESTED** [review]
Documentation and we are good to go.

**Comment by hegyibalint** [comment]
> Documentation and we are good to go.

Please check the upgrade guide `adoc`. I've attempted to make a concise summary detailing what did we change.

File: platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc [hunk 11]
```diff
@@ -52,6 +52,12 @@ The `testType` property on link:{javadocPath}/org/gradle/testing/jacoco/plugins/
 Similarly, the `testType` property was removed from link:{javadocPath}/org/gradle/api/plugins/jvm/JvmTestSuite.html[JvmTestSuite] and both the `TestSuiteTargetName` and `TestSuiteType` attributes have been removed.
 Test reports and Jacoco reports can now be aggregated between projects by specifying the name of the test suite in the target project to aggregate.
 
+==== Changed behavior when calling `BuildLauncher#addJvmArguments`
+
+An issue was found and fixed in `BuildLauncher#addJvmArguments` that caused it to override flags coming from the `org.gradle.jvmargs` system property.
```
Comment (donat) [inline platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc:57]: 💄 I'd link the original issue here.

**Review by donat — APPROVED** [review]
