### PR TITLE
Watch watchable hierarchies on Linux

### LINKED ISSUE #19250: Disk files cleanup on Teamcity causes problems with file system watching on Linux
After re-enabling Swabra on CI, there were a lot of file not found exceptions when running ktlint on the build logic sources:
```
A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
> /mnt/tcagent1/work/checkout-dir/buildSrc/src/main/kotlin/com/gradle/some/name/MyClass.kt (No such file or directory)
```

It seems like there are also problems on Linux with the way disk files cleanup (Swabra) is handled on Teamcity. See #17865 for a problem we already fixed on Windows.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by wolfs**
if they contain something worth watching. This allows us to capture events when the project root directory is moved to a different location.

Fixes #19250

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test this

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java [hunk 1]
```diff
@@ -139,7 +142,7 @@ private void update(SnapshotHierarchy root) {
             });
     }
 
-    protected abstract void updateWatchesOnChangedWatchedFiles(FileHierarchySet watchedFiles);
+    protected abstract void updateWatchesOnChangedWatchedFiles(FileHierarchySet newWatchedFiles);
```
Comment (lptr) [inline subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java:145]: Nit: revert rename?

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java [hunk 2]
```diff
@@ -158,11 +171,16 @@ private void updateWatchedDirectories(Map<String, Integer> changedWatchDirectori
...
     }
 
     private static void increment(String path, Map<String, Integer> changedWatchedDirectories) {
-        changedWatchedDirectories.compute(path, (key, value) -> value == null ? 1 : value + 1);
+        changedWatchedDirectories.compute(path, (key, value) -> zeroToNull(value == null ? 1 : value + 1));
+    }
+
+    @Nullable
+    private static Integer zeroToNull(int value) {
+        return value == 0 ? null : value;
```
Comment (lptr) [inline subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java:183]: Why not add a `nullToZero()` method as well? That'd make the code more readable I think.

**Review by lptr — APPROVED** [review]
Left two small comments, but LGTM overall.

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java (hunk 1 above)
Comment (wolfs) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java:145]: I prefer the new parameter name, given that it clarifies which watched files you receive and that HierarchicalFileWatcherUpdater already used `newWatchedFiles` as parameter name before this change.

Comment (lptr) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java:145]: Good point.

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by wolfs** [comment]
@bot-gradle test and merge
