### PR TITLE
Work around ConcurrentModificationException in Groovy 4 MetaClassImpl

### LINKED ISSUE #33539: ConcurrentModificationException in Groovy 4 MetaClassImpl
We're observing CME in tests:
https://ge.gradle.org/scans/tests?search.timeZoneId=Europe%2FBerlin&tests.container=org.gradle.internal.cc.impl.ConfigurationCacheDependencyResolutionIntegrationTest&tests.test=many%20tasks%20in%20the%20same%20project%20can%20consume%20the%20output%20of%20transform%20of%20external%20dependencies

Non-sanitized stack trace looks like:
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at groovy.lang.MetaClassImpl.getMetaProperty(MetaClassImpl.java:308)
	at groovy.lang.MetaClassImpl.hasProperty(MetaClassImpl.java:293)
	at org.gradle.internal.serialize.codecs.core.ClosureCodec$BrokenScript.getProperty(GroovyCodecs.kt:123)
	at groovy.lang.Script.println(Script.java:175)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1333)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1088)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:645)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.println(DefaultGroovyMethods.java:878)
	at org.codehaus.groovy.runtime.dgm$630.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:280)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at build_63eo36e7ohuqkubbko01al1jo$_run_closure6$_closure23.doCall$original(/Users/mlopatkin/Projects/gradle/worktrees/gradle/platforms/core-configuration/configuration-cache/build/tmp/teŝt files/Configurati.Test/eath4/build.gradle:218)
	at build_63eo36e7ohuqkubbko01al1jo$_run_closure6$_closure23.doCall(/Users/mlopatkin/Projects/gradle/worktrees/gradle/platforms/core-configuration/configuration-cache/build/tmp/teŝt files/Configurati.Test/eath4/build.gradle)
```

It looks like Groovy 3 also used thread-unsafe collection implementations, but there was no checks to trigger CME. They switched to JDK collections in https://github.com/apache/groovy/pull/1306.

It isn't clear if this affects other places aside from CC's script object replacements, but the `MetaClassImpl` implementation doesn't look particularly thread-safe.

### PR DESCRIPTION
**Pull request by mlopatkin**
Doing property lookups may modify internal structures of MetaClassImpl, namely `classPropertyIndexForSuper` map, in a thread-unsafe way. With Groovy 3 this was likely a silent data corruption, but in Groovy 4 it becomes an exception.

As a workaround, we've added extra layer of synchronization around property lookups for the code that we know was broken. There may be other instances in the Groovy runtime itself, or the internal Groovy property lookup may be different enough to avoid hitting the affected code paths.

Fixes #33539.

### CODE REVIEW

**Comment by bamboo** [comment]
Could the same problem manifest itself when using different instances of the same Groovy (meta)class in different threads (e.g. for Gradle model objects or user defined Groovy types)?

**Comment by mlopatkin** [comment]
> Could the same problem manifest itself when using different instances of the same Groovy (meta)class in different threads (e.g. for Gradle model objects or user defined Groovy types)?

I'm not sure if I properly follow what you call "instances". Are you talking about instances of the same class sharing the same MetaClass instance? These may be affected. I'm also surprised we don't see these issues widespread.

However, after looking deeper into the initialization code, I suspect that the issue only affects metaclasses of interfaces. Metaclasses of concrete classes seem to be properly initialized with locks held. It may be that normally only these metaclasses participate in property lookups, thus masking the issue. The codec looks up the metaclass by the interface (`Project`, `Gradle`, `Settings`), thus it may expose behavior uncommon to usual Groovy operation.

File: platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/GroovyCodecs.kt [hunk 1]
```diff
@@ -162,3 +162,21 @@ object GroovyMetaClassCodec : Codec<MetaClass> {
...
 }
+
+
+/**
+ * MetaClass implementations in Groovy (at least, in Groovy 4) are not fully thread-safe.
+ * This wrapper adds the necessary level of thread-safety for concurrent property lookups.
+ *
+ * This can be removed after updating to a thread-safe version of Groovy runtime.
+ */
+@JvmInline
```
Comment (bamboo) [inline platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/GroovyCodecs.kt:173]: 👍

**Comment by bamboo** [comment]
> Are you talking about instances of the same class sharing the same MetaClass instance? These may be affected. I'm also surprised we don't see these issues widespread.

Yes.

> The codec looks up the metaclass by the interface (Project, Gradle, Settings), thus it may expose behavior uncommon to usual Groovy operation.

I see.

**Review by bamboo — APPROVED** [review]

**Comment by mlopatkin** [comment]
@bot-gradle test APT
