### PR TITLE
Don't use `withVariantReselection` for Jacoco report aggregation with only the `classes` attribute present

### LINKED ISSUE #25618: Micronaut JacocoReportAggregationPlugin broken in Gradle 8.2
### Expected Behavior

Success with Gradle 8.1.1: https://ge.micronaut.io/s/z4db5b7satq26/dependencies?focusedDependency=WzAsMCwxMjM0LFswLDAsWzEyMzRdXV0&toggled=W1swXSxbMCwwXV0

### Current Behavior

Failure with Gradle 8.2: https://ge.micronaut.io/s/kruw4j3titqcs/failure

### Context (optional)

Selection of `classDirectories` in the `JacocoReport` task is failing due to too many matching variants when a project applies the `jacoco-report-aggregation` plugin and its project dependency applies the `java-test-fixtures` plugin and contains test fixtures, which also make a `classes` variant such as:

```
- Configuration ':micronaut-openapi-generator:testFixturesRuntimeElements' variant classes declares a component, preferably in the form of class files:
```

available.  The failure is due to an `ArtifactView` that uses `withVariantReselection()`, the originating `Configuration` reported in the error message is not problematic.  Reselection should **not** be used to select class directories here.

### Steps to Reproduce

See new integration test in `JacocoAggregationIntegrationTest` or rerun the Micronaut build at [this commit](https://github.com/micronaut-projects/micronaut-openapi/commit/7ad6aa1a49a8e90a05b524ff16d54173ba078f12) using Gradle 8.2.

### Gradle version

8.2

### Gradle version that used to work

8.1.1

### PR DESCRIPTION
**Pull request by tresat**
Fixes #25618

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java [hunk 1]
```diff
@@ -91,7 +91,6 @@ public void apply(Project project) {
         });
 
         ArtifactView classDirectories = codeCoverageResultsConf.getIncoming().artifactView(view -> {
-            view.withVariantReselection();
```
Comment (ljacomet) [inline subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java:94]: Is this an indication that we have an issue with variant re-selection and capabilities?

Comment (jvandort) [reply subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java:94]: There is an issue here. Reselection will reselect "out of" your capability. Reselection should be restricted to only variants with the same capabilities as the original.

Comment (tresat) [reply subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java:94]: Reselection ignores the attributes set on the `Configuration` that created the `ArtifactView`.  We need to maintain those attributes here to narrow selection to the single proper variant, otherwise there are multiple potential matches with `classes` or compatible with `classes` and selection fails.

Comment (jvandort) [reply subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java:94]: The capabilites issue exists. But it may not be related to this issue

Comment (jvandort) [reply subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java:94]: The multiple potential matches being from the production compiled code and the test fixtures code? I think capabilities may be related since both variants should have identical attributes but just different capabilities

Comment (big-guy) [reply subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java:94]: Yeah, that's what I think is going on too.  We're re-selecting from the full set of variants instead of the ones for the requested capability. 

This is good enough for 8.2.1, but there's something deeper here that's missing.

**Comment by tresat** [comment]
@bot-gradle test and merge
