### PR TITLE
Use UTF-8 when extracting build cache artifacts

### LINKED ISSUE #9877: Extracting cache entry fails on non-UTF-8 system locale
When unpacking a cached result on a system with a non-UTF-8 encoding this can happen:

```text
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
        at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:816)
        at org.apache.commons.compress.archivers.zip.NioZipEncoding.decode(NioZipEncoding.java:133)
        at org.apache.commons.compress.archivers.tar.TarUtils.parseName(TarUtils.java:299)
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1275)
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1266)
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(TarArchiveEntry.java:404)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:283)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:552)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.paxHeaders(TarArchiveInputStream.java:444)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:318)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpackDirectoryTree(TarBuildCacheEntryPacker.java:292)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpackTree(TarBuildCacheEntryPacker.java:254)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpack(TarBuildCacheEntryPacker.java:198)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpack(TarBuildCacheEntryPacker.java:158)
        at org.gradle.caching.internal.packaging.impl.GZipBuildCacheEntryPacker.unpack(GZipBuildCacheEntryPacker.java:49)
        at org.gradle.caching.internal.command.BuildCacheCommandFactory$LoadCommand.load(BuildCacheCommandFactory.java:94)
        at org.gradle.caching.internal.controller.DefaultBuildCacheController$Unpack$1.run(DefaultBuildCacheController.java:178)
        at
```

### PR DESCRIPTION
**Pull request by lptr**
Fixes #9877

We have been using `UTF-8` as the encoding when creating TAR files to store cached output. However, we haven't been using the same encoding when unpacking. Instead, we were using the system default (which is `UTF-8` in most cases, but not always). This causes no issues as long as the file names stored in the TAR file are ASCII-only. And the TAR implementation in `commons-compress` that we use does some tricks to support non-ASCII characters even when a non-UTF-8 character set is chosen for unpacking. However, in some cases there is a failure due to this confusion of encodings.

### CODE REVIEW

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+
+        when:
+        withBuildCache().run"createFile", "-Dfile.encoding=$fileEncoding", "--info"
+        then:
+        output.contains("> Default charset: $fileEncoding")
+        executedAndNotSkipped(":createFile")
+
+        when:
+        assert outputFile.delete()
+        withBuildCache().run"createFile", "-Dfile.encoding=$fileEncoding", "--info"
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: minor: formatting

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+                    file("$fileName").text = "output"
+                }
+            }
+        """
+
+        when:
+        withBuildCache().run"createFile", "-Dfile.encoding=$fileEncoding", "--info"
+        then:
+        output.contains("> Default charset: $fileEncoding")
+        executedAndNotSkipped(":createFile")
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: minor: if you think it makes sense please consider unifying the method parentheses usages

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+
+import org.gradle.integtests.fixtures.DirectoryBuildCacheFixture
+import org.gradle.integtests.fixtures.daemon.DaemonIntegrationSpec
+import spock.lang.Issue
+import spock.lang.Unroll
+
+class BuildCacheEntryPackingIntegrationTest extends DaemonIntegrationSpec implements DirectoryBuildCacheFixture {
+    @Issue("https://github.com/gradle/gradle/issues/9877")
+    @Unroll
+    def "can store and load files having #type characters in name (default file encoding #fileEncoding)"() {
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: what's the failure reason before the fix?

Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: I'm not sure I fully understand your question. The failure that triggered the addition of this test is detailed in the linked issue. There is no fix yet, as I first would like to reproduce the problem. Unfortunately, I couldn't do that yet. That's why the PR is in draft, and in progress.

Does this answer your question? Are you expecting some change in the code?

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 2 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Will do, thanks.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 1 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: 👍

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 3 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: It wasn't clear to me that the problem wasn't reproduced yet, I assumed the detailed PR with the tests meant that at least some of them were failing, otherwise I didn't see what the point of a PR was.
Screen Shot 2019-07-05 at 9 03 49

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+        withBuildCache().run"createFile", "-Dfile.encoding=$fileEncoding", "--info"
+        skipped(":createFile")
+
+        then:
+        output.contains("> Default charset: $fileEncoding")
+        outputFile.text == "output"
+
+        where:
+        [type, fileName, fileEncoding] << [
+            [
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: please run the first part in the same suite, otherwise these take too long (2.5 minutes locally)

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 3 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: What is the purpose of your comments here? As I said above, this is a draft of a PR, it's not intended to be reviewed yet. I'm just trying to reproduce the problem a user reported, and failing. Nothing to see here yet. :)

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 4 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Again, this is a draft PR I currently use to reproduce the problem. That's why there are so many tests currently. Please hold off the review until the PR is ready.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 3 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Ok :)

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+                "ascii-only": "input-file.txt",
+                "chinese-simplified": "敏捷的棕色狐狸跳过了懒狗.txt",
+                "chinese-traditional": "敏捷的棕色狐狸跳過了懶狗.txt",
+                "cyrillic": "АдрМНИн.txt",
+                "hungarian": "Dezső.txt",
+                "space": "input file.txt",
+                "zwnj": "input\u200cfile.txt",
+                "url-quoted": "input%<file>#2.txt",
```
Comment (andrey-fomin) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: It's impossible to create file with `<` or `>` in Windows.
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: :+1:

**Comment by lptr** [comment]
I haven't been able to reproduce the problem reported by @andrey-fomin even with the provided reproducer (see [attachment](https://github.com/gradle/gradle/files/3376480/test.zip)), as it did not manage to decompress:

```console
$ unzip test.zip
Archive:  test.zip
  inflating: test/build.gradle.kts
   creating: test/gradle/
   creating: test/gradle/wrapper/
  inflating: test/gradle/wrapper/gradle-wrapper.jar
  inflating: test/gradle/wrapper/gradle-wrapper.properties
  inflating: test/gradlew
  inflating: test/gradlew.bat
  inflating: test/out.log
   creating: test/src/
   creating: test/src/main/
   creating: test/src/main/java/
error:  cannot create test/src/main/java/������.java
        Illegal byte sequence
```

It seems that the TAR implementation we are using from `commons-compress` already corrects for a non-UTF-8 default charset (see [source code](https://github.com/apache/commons-compress/blob/rel/1.18/src/main/java/org/apache/commons/compress/archivers/zip/NioZipEncoding.java#L174-L185)). This explains why nobody has reported problems with unpacking non-UTF-8 file names when loading from cache. What it doesn't is how @andrey-fomin could have encountered the exception in the first place.

Nevertheless, I added some more thorough integration tests around packaging, and set the encoding for the unpacking to UTF-8 as it should have been all along.

**Comment by wolfs** [comment]
@lptr I manged to reproduce the error on my machine. The changes were to use an output directory with the file with the bad name in it and the `windows-1250` charset. See my last two commits here: https://github.com/gradle/gradle/compare/wolfs/build-cache/issue-9877

Let's see if the test also breaks on CI: https://builds.gradle.org/viewLog.html?buildId=24765494&buildTypeId=Gradle_Check_Quick_1_buildCachePackaging&tab=buildResultsDiv&branch_Gradle_Check_Quick_1=wolfs%2Fbuild-cache%2Fissue-9877

**Comment by paplorinc** [comment]
Retriggered the build caused, failed with `stderr: fatal: Could not write new index file.`

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+        output.contains("> Default charset: $fileEncoding")
+        outputFile.text == "output"
+
+        where:
+        fileEncoding << DEFAULT_ENCODINGS
+    }
+
+    @Issue("https://github.com/gradle/gradle/issues/9877")
+    @Unroll
+    def "can store and load files having non-ascii characters in property name using default file encoding #fileEncoding"() {
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: ❓ are we actually using the default encoding or rather ignoring it?

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+        executedAndNotSkipped(":createFile")
+
+        when:
+        assert outputFile.delete()
+        withBuildCache().run("createFile", "-Dfile.encoding=$fileEncoding")
+        skipped(":createFile")
+
+        then:
+        output.contains("> Default charset: $fileEncoding")
+        outputFile.text == "output"
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: ❓ what's the purpose of checking output when the task was skipped?

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 8]
```diff
@@ -0,0 +1,115 @@
...
+        output.contains("> Default charset: $fileEncoding")
+        executedAndNotSkipped(":createFile")
+
+        when:
+        assert outputFile.delete()
+        withBuildCache().run("createFile", "-Dfile.encoding=$fileEncoding")
+        skipped(":createFile")
+
+        then:
+        output.contains("> Default charset: $fileEncoding")
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Consider using `outputContains` instead to have a more compact error in case of failure, since having `output` here will list the content of the file on failure (which is already listed anyway)

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 9]
```diff
@@ -0,0 +1,115 @@
...
+package org.gradle.caching.internal.packaging
+
+import org.gradle.integtests.fixtures.DirectoryBuildCacheFixture
+import org.gradle.integtests.fixtures.daemon.DaemonIntegrationSpec
+import spock.lang.Issue
+import spock.lang.Unroll
+
+class BuildCacheEntryPackingIntegrationTest extends DaemonIntegrationSpec implements DirectoryBuildCacheFixture {
+
+    private static final NON_ASCII_NAME = [
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: ❓ is there any advantage in having privates in test files?

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 10]
```diff
@@ -0,0 +1,115 @@
...
+    ]
+
+    @Unroll
+    def "can store and load files having non-ascii characters in file name using default file encoding #fileEncoding"() {
+        def fileName = NON_ASCII_NAME + ".txt"
+        def outputFile = file("dir", fileName)
+
+        buildFile << """
+            println "> Default charset: \${java.nio.charset.Charset.defaultCharset()}"
+            println "> Storing file in cache: $fileName"
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: ❓ does this still make sense or was it added for debugging purposes?

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 11]
```diff
@@ -0,0 +1,115 @@
...
+        then:
+        output.contains("> Default charset: $fileEncoding")
+        outputFile.text == "output"
+
+        where:
+        fileEncoding << DEFAULT_ENCODINGS
+    }
+
+    @Issue("https://github.com/gradle/gradle/issues/9877")
+    @Unroll
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: ❓ Would it make sense to add the `@Unroll` to the class instead?
❓ Should we add the `Issue` annotation to the rest of the related tests?

File: subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker.java [hunk 12]
```diff
@@ -73,6 +74,9 @@
  * Packages build cache entries to a POSIX TAR file.
  */
 public class TarBuildCacheEntryPacker implements BuildCacheEntryPacker {
+
+    private static final String UTF_8 = StandardCharsets.UTF_8.name();
```
Comment (paplorinc) [inline subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker.java]: Naming the field by its value doesn't reflect its intent. What should happen when we decide to use UTF-16? Should we rename the symbol as well, even though the intent is the same?
If you think it makes sense, please consider renaming it.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy [hunk 13]
```diff
@@ -0,0 +1,115 @@
...
+
+        then:
+        output.contains("> Default charset: $fileEncoding")
+        outputFile.text == "output"
+
+        where:
+        fileEncoding << DEFAULT_ENCODINGS
+    }
+
+    @Issue("https://github.com/gradle/gradle/issues/9877")
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: I think the `@Issue` belongs to the other test (or to both). The reported problem was about file names and not property names.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 6 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: We are using a default encoding to run the build.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 7 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: That's the whole point here. The task is skipped because it's loaded from cache. We need to check if the output is created as expected.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 8 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Hm, I never noticed that method provides better output. I’ll check it out, thanks!

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 6 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Didn't we specify UTF-8 explicitly to pack/unpack - or is that not what the title refers to?

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 7 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: wasn't yet aware that skipped meant it could be restored from cache. Thanks for clarifying.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 6 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Yes, that is how we deal with the default encoding (in the OS) being set to different values.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 9 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: I don't think there's anything specific to tests here. This is a value that only should be used in this class, so it should be `private`.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 13 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Good point, fixed.

File: subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker.java (hunk 12 above)
Comment (lptr) [reply subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker.java]: Good point, I changed it.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 11 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: I moved the `@Issue` annotation to where it belongs. I think `@Unroll` on the class means something a bit different, so I don't want to move it there. We might add more tests here that don't need to be unrolled.

Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Do I understand it correctly that we have tests with `where` clauses that we don't want to unroll?

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 10 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: If you don't feel strongly about removing this I'd leave this in. It's nice as a human to see this in the output.

Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: 👍

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 6 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: I understood the encoding is ignored in favor of the encoding we're explicitly setting (utf8). Do I misunderstand the title or the fix?

Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: I'm not sure what you are asking. Do you have a suggestion for a change maybe?

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 9 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Minor: Are there cases when we're referencing fields from other tests? Don't we always treat test fields as implicitly private?

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 6 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Before setting the encoding explicitly, the default encoding was used, right?
So the test name does reflect the previous state, but now we're explicitly setting the encoding that should be used, so it seems to me that the default file encoding (still present in the test name) doesn't play any role anymore.
I'm okay with you ignoring this nit, I may have misunderstood it.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 11 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: No, there are multiple reasons why I don't usually put `@Unroll` on a class.

IntelliJ has a problem navigating to unrolled tests. Adding `@Unroll` to the test class used to mean that navigation to non-parametrized tests was broken, too. This latter problem seems to have been fixed lately, so we _could_ add `@Unroll` to this class as you suggest.

But then again, why add it to the test class? If I move all parametrized tests to a different class, should I then remove `@Unroll` from the class itself? It's not the right abstraction level to annotate. What we need instead is global-unroll that enables unrolling automatically for every test. There seems to be a Spock extension to do just that: https://github.com/szpak/spock-global-unroll, let's investigate that outside of this PR.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 6 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: We don't set the default encoding/charset set for the JVM. What we do in production code (and was not doing well before the fix) is that we keep our business independent of the default encoding. This is what the test title says: (even) when default encoding is set to something unusual we succeed in conducting our work. Let me know if you have an idea how to clarify this further if needed.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 8 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: I tested it, and `output.contains()` prints a lot less noise than `outputContains()` (47 vs 150 lines). :o

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 6 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Yes, that's why maybe instead we could:
> can store and load files [...] ~using~ ignoring the default file encoding

If you don't think that helps, please feel free to resolve this conversation.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 9 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: I'm not sure what "implicitly private" means. What is the benefit of not declaring this as `private`? Why wouldn't we want to be explicit when something is shared between tests?

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 11 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Ah, that's brilliant, lemme' see how complicated that would be

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 6 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: OK, I pushed a change, please check.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 8 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Both seem very verbose to me, just wanted to point out that there's a difference.
Both will print the output several times, the difference is in the error message:

Screen Shot 2019-07-16 at 11 47 12

vs

Screen Shot 2019-07-16 at 11 44 31

---

On an unrelated topic, maybe we could compact the output of `output.contains` to make it less noisy.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 9 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: If we are practicing that, I.e. define a constant in one test and use it in the other, it may make sense to signal that this constant is not one of those.
Since I assume we're not advocating that, we can already assume that everything is private, so explicitly declaring it has little advantage.
I don't mind, just want to clarify.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 11 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Not worth time in it since: https://github.com/spockframework/spock/issues/967#issuecomment-497016452

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 9 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: OK, I think I understand your argument now. You are saying that `private` adds only noise here, as we'd never actually reference this field from another test. Do I get that correctly? We do use this inconsistently, and I think it's fine either way.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 8 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: We could. Please open a separate issue if you think we should.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 9 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Thanks for taking the time.

File: subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy (hunk 8 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy]: Opened https://github.com/gradle/gradle/issues/9966#issue-468564257
