### PR TITLE
Return correct relative path when snapshotting

### LINKED ISSUE #6656: FileTreeElement.getPath() returns absolute system dependent filepath
With Gradle 4.10 the result of `FileTreeElement.getPath()` changed in a breaking way.

### Expected Behavior
From the method documentation:

> Returns the path of this file, relative to the root of the containing file tree. Always uses '/' as the hierarchy separator, regardless of platform file separator. Same as calling <code>getRelativePath().getPathString()</code>.

The expected String path should be relative to the `FileTree` and use `/` as file seperators even on windows environments.

### Current Behavior

With Gradle `4.10` this changed. The resulting String is an absolute system dependent path.

### Context

In my plugin I provide a default `FileCollection` which is constructed with the help of `PatternFilterable include(Spec<FileTreeElement> includeSpec);` API.
In my `Spec<FileTreeElement>` implementation I retrieve the file path with `element.getPath() and do some checks based on the asumption that it is relative and normalized.

In gradle `<= 4.9` the `FileTreeElement` was implemented as a `DefaultFileVisitDetails` which calls `getRelativePath().getPathString();` as advertised in the docs.
As of gradle `4.10` some elements are implemented as `PathBackedFileTreeElement` which implements `getPath()` as follows:

https://github.com/gradle/gradle/blob/f3079d75d8377c73b996aa19caf898ead63c21ca/subprojects/core/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java#L304-L307

### Steps to Reproduce (for bugs)

https://github.com/wooga/atlas-build-unity in branch `gradle/issue_6656`

running the test specs from `UnityBuildPlayerTaskIntegrationSpec` will work from gradle version `3.5` - `4.9` and start to fail on `4.10`.

### Your Environment

I can verify this issue both on macOS and windows systems.

### PR DESCRIPTION
**Pull request by wolfs**
Fixes #6656

### CODE REVIEW

File: subprojects/core/src/test/groovy/org/gradle/api/internal/file/collections/jdk7/Jdk7DirectoryWalkerTest.groovy [hunk 1]
```diff
@@ -319,4 +324,36 @@ class Jdk7DirectoryWalkerTest extends Specification {
         }
     }
 
+    def "directory snapshotter returns the same details as directory walker"() {
+        given:
+        def rootDir = tmpDir.createDir("root")
+        generateFilesAndSubDirectories(rootDir, 10, 5, 3, 1, new AtomicInteger(0))
+        MirrorUpdatingDirectoryWalker directorySnapshotter = new MirrorUpdatingDirectoryWalker(TestFiles.fileHasher(), TestFiles.fileSystem(), new StringInterner())
+        def patternSet = Mock(PatternSet)
+        List<FileVisitDetails> visitedWithJdk7Walker = null
```
Comment (lptr) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/file/collections/jdk7/Jdk7DirectoryWalkerTest.groovy]: No need to set this to `null`. You could actually do the walking here, as it is a prerequisite to the `when:` part, not part of it.

**Comment by wolfs** [comment]
@lptr I added some more test coverage for the `DirectorySnapshotter`. Could you have another look?
