### PR TITLE
Fix Antlr task dependency wiring and add packageName property

### LINKED ISSUE #19555: ANTLR plugin's generated source dir creates implicit task dependencies
When the built-in `antlr` plugin generated source dir is added, a proper dependency relationship isn't maintained, so consumers of the souce set's SourceDirectory set do not depend on the grammar generation task.

### Expected Behavior
Tasks declaring a source set's java sources as an input should automatically gain a depenency on the `generateGrammarSource` task

### Current Behavior
Depenencies have to be added manually, and the `sourcesJar` task will generate a warning upon execution:

```
 Execution optimizations have been disabled for task ':sourcesJar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/runner/work/gradle-issue-reproducer/gradle-issue-reproducer/build/generated-src/antlr/main'. Reason: Task ':sourcesJar' uses this output of task ':generateGrammarSource' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Gradle detected a problem with the following location: '/home/runner/work/gradle-issue-reproducer/gradle-issue-reproducer/build/generated-src/antlr/main'. Reason: Task ':sourcesJar' uses this output of task ':generateGrammarSource' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See docs.gradle.org/7.3.3/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
```

Some other tasks that use the java sources of a SourceSet will instead silently fail to include the generated sources -- see the reproducer for an example of this case

### Context

This issue can be worked around with manual configuration of `dependsOn` for the relevant tasks, but that extra step should not be necessary. Cases where no warning is displayed could lead to unstable results in builds.

### Steps to Reproduce 
See https://github.com/zml2008/gradle-issue-reproducer/blob/antlr-dependency-warnings/build.gradle.

- `./gradlew assemble --warning-mode=fail` triggers a build failure
- `./gradlew clean printJavaSources` silently produces incorrect results

both are executed within the GitHub Actions workflow in the repository.

### LINKED ISSUE #25885: antlr plugin's generated source files are not properly tracked for task wiring purposes
### Expected Behavior

Given a build script like below, running a task that consumes generated source files from antlr should not trigger any build failures due to failing to declare explicit task dependencies. Gradle's `SourceSets` concept should handle this transparently.

### Current Behavior

Running `./gradlew lib:generateGrammarSource lib:printFiles --console=verbose` will result in a build failure due to failure to declare explicit task dependencies (which should not be required).

```
./gradlew lib:generateGrammarSource lib:printFiles --console=verbose
> Task :lib:generateGrammarSource NO-SOURCE
> Task :lib:printFiles FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':lib:printFiles' (type 'MyTask').
  - Gradle detected a problem with the following location: '/Users/trobalik/Development/temp/antlr/lib/build/generated-src/antlr/main'.
    
    Reason: Task ':lib:printFiles' uses this output of task ':lib:generateGrammarSource' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':lib:generateGrammarSource' as an input of ':lib:printFiles'.
      2. Declare an explicit dependency on ':lib:generateGrammarSource' from ':lib:printFiles' using Task#dependsOn.
      3. Declare an explicit dependency on ':lib:generateGrammarSource' from ':lib:printFiles' using Task#mustRunAfter.

...
```

### Context (optional)

I ran into this while upgrading [my plugin](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/tree/main) to Gradle 8.2.1 (from 7.5). I ended up [disabling one of my tests](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/functionalTest/groovy/com/autonomousapps/jvm/AntlrSpec.groovy#L12) so that I wouldn't be blocked. There is also an [open issue](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/685) on my plugin for [this deprecation warning](https://github.com/gradle/gradle/issues/18563) in Gradle 7.x.

### Steps to Reproduce

Take the following build script. Use Gradle 8.2.1.
```groovy
// lib/build.gradle (from `gradle init`)
plugins {
  id 'java-library'
  id 'antlr'
}

repositories {
  mavenCentral()
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(11)
  }
}

tasks.register('printFiles', MyTask) {
  sourceFiles.setFrom(sourceSets.main.allJava.sourceDirectories.asFileTree)
  output.set(layout.buildDirectory.file("output.txt"))
}

@CacheableTask
abstract class MyTask extends DefaultTask {

  @PathSensitive(PathSensitivity.RELATIVE)
  @InputFiles
  abstract ConfigurableFileCollection getSourceFiles()

  @OutputFile
  abstract RegularFileProperty getOutput()

  @TaskAction void action() {
    def output = output.get().asFile
    output.delete()

    def names = sourceFiles.collect {
      it.name
    }

    logger.quiet("Files: $names")

    output.write(names.toString())
  }
}
```
Now run
```
./gradlew lib:generateGrammarSource lib:printFiles
```

### Gradle version

8.2.1

### Build scan URL (optional)

https://scans.gradle.com/s/yqb63g6g5qal4/tests/task/:functionalTest/details/com.autonomousapps.jvm.AntlrSpec/antlr%20dep%20on%20antlr%20conf%20is%20not%20declared%20unused%20(Gradle%208.2.1)?top-execution=1

### Your Environment (optional)

_No response_

### LINKED ISSUE #33180: ANT-style exclusions stopped working for Checkstyle and PMD tasks
### Current Behavior

```gradle
tasks.withType(Checkstyle).configureEach {
	exclude(['**/com/company/SomeClass*'])
}
```

Used to work in Gradle 8.13. It stopped working in Gradle 8.14-rc-2. That is, this file is checked by Checkstyle. Same for PMD.

### Expected Behavior

Old behavior as in Gradle 8.13.

### Context (optional)

_No response_

### Self-contained Reproducer Project

[Repo](https://github.com/boris-petrov/gradle-ant-exclusion-bug).

Run `./gradlew checkstyleMain` on this. It will give some Checkstyle errors in `build/generated-src/antlr/main/com/company/Hello*` which are actually ignored with `exclude(['**/com/company/Hello*'])`.

### Gradle version

8.14-rc-2

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by ghale**
This PR does a few things:

1) It creates a task dependency between the generated source set and the Antlr source generation task.  So any task that uses the generated source set as an input will automatically get an implicit task dependency on the source generation task.
2) The source set automatically follows the output of the source generation task.  Previously, any time the output directory of the task changed, the source set needed to also be updated.
3) It adds a new `Antlr.packageName` property to model the package as a first class thing for Antlr 4.  This allows Gradle to understand when the `-package` argument is in use and adjust the configuration of the underlying Antlr tool accordingly.  Previously, both the output directory and arguments had to be set in a coordinated matter to configure it properly.

See [this comment](https://github.com/gradle/gradle/issues/33180#issuecomment-2985296956) for more detail on the problems these changes solve.

Fixes #19555 
Fixes #25885 
Fixes #33180

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

File: platforms/software/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrTask.java [hunk 1]
```diff
@@ -349,4 +351,18 @@ protected FileCollection getStableSources() {
 
     @Inject
     protected abstract Deleter getDeleter();
+
+    /**
+     * Sets the package to be used when generating the parser source files.  Antlr 4 only.
```
Comment (jvandort) [inline platforms/software/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrTask.java]:
```suggestion
     * Sets the package to be used when generating the parser source files.  Supported only when using Antlr 4.
```

File: platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/AntlrPluginIntegrationTest.groovy [hunk 2]
```diff
@@ -103,4 +91,45 @@ class AntlrPluginIntegrationTest extends WellBehavedPluginTest {
...
+        """
+
+        and:
+        file("src/main/antlr/TestGrammar.g") << testGrammarSource
+
+        when:
+        succeeds('sourcesJar')
+
+        then:
+        executed(':generateGrammarSource')
```
Comment (jvandort) [inline platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/AntlrPluginIntegrationTest.groovy:120]: 🤔 Should we also check that the resulting sources jar has the generated sources?

File: platforms/documentation/docs/src/docs/release/notes.md [hunk 3]
```diff
@@ -107,6 +107,32 @@ assert(bar.getAttribute(color) == "orange") // `color` gets overwritten again
 assert(bar.getAttribute(shape) == "square") // `shape` remains the same
 ```
 
+### Configuration Improvements
+
+#### Simpler target package configuration for Antlr 4
+The AntlrTask class now supports setting the target package for generated code explicitly for Antlr 4.
```
Comment (jvandort) [inline platforms/documentation/docs/src/docs/release/notes.md]:
```suggestion
The AntlrTask class now supports explicitly setting the target package for generated code when using Antlr 4.  
```

File: platforms/documentation/docs/src/docs/release/notes.md [hunk 4]
```diff
@@ -107,6 +107,32 @@ assert(bar.getAttribute(color) == "orange") // `color` gets overwritten again
...
+
+```kotlin
+tasks.named("generateGrammarSource").configure {
+    // Set the target package for generated code
+    packageName = "com.example.generated"
+}
+```
+
+#### Antlr generated sources are automatically tracked
+In previous versions of Gradle, the Antlr generated sources were added to a java source set for compilation, but if the generated sources directory was changed, this change was not reflected in the source set.
```
Comment (jvandort) [inline platforms/documentation/docs/src/docs/release/notes.md]:
```suggestion
In previous versions of Gradle, the Antlr-generated sources were added to a java source set for compilation, but if the generated sources directory was changed, this change was not reflected in the source set.  
```

File: platforms/software/antlr/src/test/groovy/org/gradle/api/plugins/antlr/AntlrPluginTest.groovy [hunk 5]
```diff
@@ -93,4 +94,41 @@ class AntlrPluginTest extends AbstractProjectBuilderSpec {
...
+
+        then:
+        def generateGrammarSource = project.tasks.generateGrammarSource
+        def sourcesJar = project.tasks.sourcesJar
+        sourcesJar.taskDependencies.getDependencies(null).contains(generateGrammarSource)
+    }
+
+    def 'can derive source root directory from task configuration'() {
+        expect:
+        AntlrPlugin.deriveGeneratedSourceRootDirectory(outputDirectory, arguments) == expectedDirectory
```
Comment (jvandort) [inline platforms/software/antlr/src/test/groovy/org/gradle/api/plugins/antlr/AntlrPluginTest.groovy]: 💭 I'm not sure I love the idea of exposing this method as `@VisibleForTesting` just so we can call it here. I generally favor unit testing something through its "public interface". 

Is there a way we can refactor this test to allow us to test it through its "public interface"? (i.e. applying the plugin, setting a packageName on the task, verifying the target output dir is in the java source set)

File: platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/AntlrFilteringIntegrationTest.groovy [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+                    println("Filtered task executed with sources:")
+                    source.files.each { file ->
+                        println(" - " + relativePath(file))
+                    }
+                }
+            }
+        """
+
+        when:
+        executerConfig.call(executer)
```
Comment (jvandort) [inline platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/AntlrFilteringIntegrationTest.groovy]: 💭 WDYT about taking a `expectDeprecation` boolean instead of a generic `executerConfig`? Seems a bit more direct way of doing this if different executions don't need to inject wildly different behavior per run

EDIT: Same goes for some of these other tests which are doing something similar

File: platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/Antlr3PluginIntegrationTest.groovy [hunk 7]
```diff
@@ -73,6 +79,46 @@ class Antlr3PluginIntegrationTest extends AbstractAntlrIntegrationTest {
         assertAntlrVersion(3)
     }
 
+    def "exception when package is set using #description"() {
+        goodGrammar()
+
+        buildFile "grammar-builder/build.gradle","""
```
Comment (jvandort) [inline platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/Antlr3PluginIntegrationTest.groovy]:
```suggestion
        buildFile "grammar-builder/build.gradle", """
```

File: platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/Antlr2PluginIntegrationTest.groovy [hunk 8]
```diff
@@ -62,6 +64,44 @@ class Antlr2PluginIntegrationTest extends AbstractAntlrIntegrationTest {
         assertGrammarSourceGenerated("UnpackagedGrammar")
     }
 
+    def "exception when package is set using #description"() {
+        goodGrammar()
+
+        buildFile "grammar-builder/build.gradle","""
```
Comment (jvandort) [inline platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/Antlr2PluginIntegrationTest.groovy]:
```suggestion
        buildFile "grammar-builder/build.gradle", """
```

**Review by lkasso — COMMENTED** [review]
Release notes look great!

File: platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/AntlrPluginIntegrationTest.groovy (hunk 2 above)
Comment (ghale) [reply platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/AntlrPluginIntegrationTest.groovy:120]: I think it's relevant.  Done.

File: platforms/software/antlr/src/test/groovy/org/gradle/api/plugins/antlr/AntlrPluginTest.groovy (hunk 5 above)
Comment (ghale) [reply platforms/software/antlr/src/test/groovy/org/gradle/api/plugins/antlr/AntlrPluginTest.groovy]: Yeah, it really doesn't need to be in this class since it's a static String manipulation method, it just evolved this way.  I've moved the meat of this out to a utility class (`FilePathUtil`) as a public member and do the testing there instead.

File: platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/AntlrFilteringIntegrationTest.groovy (hunk 6 above)
Comment (ghale) [reply platforms/software/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/AntlrFilteringIntegrationTest.groovy]: Good point.  Not sure why I didn't do that in the first place - using a boolean here is definitely more direct and comprehensible.  Done.

**Comment by ghale** [comment]
@bot-gradle test this

**Comment by benjamin-bader** [comment]
@ghale thanks for taking this over the line!  really appreciate your work on this, and I'm looking forward to 9.1.0.
