### PR TITLE
Fix configuration cache incompatibility in Java Gradle Plugin Plugin

### LINKED ISSUE #22545: Misleading "No valid plugin descriptors" is shown when running from the configuration cache
### Expected Behavior
No false positive warning about "No valid plugin descriptors were found" should be shown when building a plugin jar with the configuration cache.

### Current Behavior
False positive warning is shown.

### Steps to Reproduce 
With the [reproducer project](https://github.com/mlopatkin/gradle-issue-reproducers/tree/false-positive-no-valid-plugin-descriptors):
1. Run `./gradlew jar`
2. Run `./gradlew jar` one more time, reusing the configuration cache

### Your Environment
Gradle 7.5.1

### PR DESCRIPTION
**Pull request by mlopatkin**
Plugin validation action relied on sharing List and Set between the validating action and file handlers. This doesn't work well with the configuration cache serialization, as it treats collections as values without identity. As a result of deserialization, each Action got a different copy of the collection, so the mutations weren't visible to the validation action.

The fix wraps the collections into a class. The class identity is preserved when deserializing, so all Actions share the same instance of the state class.

Fixes #22545

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java [hunk 1]
```diff
@@ -282,23 +280,62 @@ private Provider<JavaLauncher> toolchainLauncher(Project project) {
         return service.launcherFor(extension.getToolchain());
     }
 
+    /**
+     * A state shared by the validation process.
+     * The state is first collected by the {@link Jar#filesMatching(String, Action)} during the bundling.
+     * Then {@link PluginValidationAction} (added to the Jar as doLast) processes the collected information to emit warnings if necessary.
+     * <p>
+     * List and Set cannot be shared without this wrapper class as their identity isn't preserved by the configuration cache.
```
Comment (abstratt) [inline subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java:288]: This makes sense as a description of your design for this change, but not as much as explaining the resulting code.

Instead, I would say use more general terms like wrapping the state into this class is required so it remains a shared object when storing it into/loading it from the configuration cache (collections in are duplicated when serialized).

**Review by abstratt — APPROVED** [review]
This kind of gotcha should be documented somewhere in the configuration cache documentation (so people don't make the same "mistake" in their own plugins). 

Otherwise, just a suggestion for changing a comment to be less about this change/bug and more about the design rationale per se.

**Comment by abstratt** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, BD

**Comment by mlopatkin** [comment]
> This kind of gotcha should be documented somewhere in the configuration cache documentation (so people don't make the same "mistake" in their own plugins).

Good idea, I've added documentation.

> Otherwise, just a suggestion for changing a comment to be less about this change/bug and more about the design rationale per se.

Cleaned up the Javadoc, so it shouldn't be too elaborate now.

**Comment by mlopatkin** [comment]
[Link to the changed docs](https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/67767097:id/distributions/gradle-8.3-docs.zip!/gradle-8.3-20230628110610%2B0000/docs/userguide/configuration_cache.html#config_cache:requirements:shared_objects)

File: subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc [hunk 2]
```diff
@@ -837,6 +837,43 @@ Instead, tasks should be connected using <<lazy_configuration#working_with_task_
 
 Note that this requirement makes it unsupported to write tasks that configure other tasks at execution time.
 
+[[config_cache:requirements:shared_objects]]
+=== Sharing mutable objects
+When storing a task to the configuration cache, all objects directly or indirectly referenced through the task's fields are serialized.
+In most cases, deserialization preserves reference equality: if two fields `a` and `b` referenced the same instance at configuration time, then upon deserialization they will reference the same instance again, so `a == b` (or `a === b` in Groovy and Kotlin syntax) still holds.
```
Comment (lkasso) [inline subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc:843]:
```suggestion
In most cases, deserialization preserves reference equality: if two fields `a` and `b` reference the same instance at configuration time, then upon deserialization they will reference the same instance again, so `a == b` (or `a === b` in Groovy and Kotlin syntax) still holds.
```

File: subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc [hunk 3]
```diff
@@ -837,6 +837,43 @@ Instead, tasks should be connected using <<lazy_configuration#working_with_task_
...
+====
+include::sample[dir="snippets/configurationCache/sharedObjects/kotlin",files="build.gradle.kts[]"]
+include::sample[dir="snippets/configurationCache/sharedObjects/groovy",files="build.gradle[]"]
+====
+<1> `doLast` action captures the references from the enclosing scope. These captured references are also serialized to the configuration cache.
+<2> Compare the reference to an object of user-defined class stored in the task field and the reference captured in the `doLast` action.
+<3> Compare the reference to `ArrayList` instance stored in the task field and the reference captured in the `doLast` action.
+<4> Check the equality of stored and captured lists.
+
+Running the build without configuration cache shows that reference equality is preserved in both cases.
```
Comment (lkasso) [inline subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc:857]:
```suggestion
Running the build without the configuration cache shows that reference equality is preserved in both cases.
```

File: subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc [hunk 4]
```diff
@@ -837,6 +837,43 @@ Instead, tasks should be connected using <<lazy_configuration#working_with_task_
...
+However, with the configuration cache enabled, only the user-defined object references are the same.
+List references are different, though the referenced lists are equal.
+----
+❯ gradle --configuration-cache checkEquality
+include::{snippetsPath}/configurationCache/sharedObjects/tests/sharingObjectsWithConfigurationCache.out[]
+----
+
+In general, it isn't recommended to share mutable objects between configuration and execution phases.
+If you need to do this, you should always wrap the state in a class you define.
+There's no guarantee that the reference equality is preserved for standard Java, Groovy, and Kotlin types, or for Gradle-defined types.
```
Comment (lkasso) [inline subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc:872]:
```suggestion
There is no guarantee that the reference equality is preserved for standard Java, Groovy, and Kotlin types, or for Gradle-defined types.
```

**Review by lkasso — APPROVED** [review]
Very minor changes in docs.

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Comment by TWiStErRob** [comment]
Really nice docs! Thanks for recording the gotcha!
