### PR TITLE
Fix Invalid cookie header messages

### LINKED ISSUE #1596: Invalid cookie header: Invalid 'expires' attribute messages flood the build output
When downloading jars from custom repository running on AWS, the following messages are displayed:

Invalid cookie header: "Set-Cookie: AWSALB=gQoLH+yfJ5Q1FtG42X6LxcXpElV3tGjbRRtKVkdgpzbUi6VvvAUUTFxZddt28f7EIwwNEv0SJRl+itg6OKSQcRnc9tOc2TWlrye/cxrXoci0veb/c3J+RIYZEGyQ; Expires=Thu, 23 Mar 2017 15:03:12 GMT; Path=/". Invalid 'expires' attribute: Thu, 23 Mar 2017 15:03:12 GMT

One message per jar appears in the output, so basically the screen is flooded with them

### Expected Behavior
Such messages should not be visible in the output

### Current Behavior
A multitude of:
Invalid cookie header: "Set-Cookie: AWSALB=[COOKIE GOES HERE]; Expires=Thu, 23 Mar 2017 15:03:12 GMT; Path=/". Invalid 'expires' attribute: Thu, 23 Mar 2017 15:03:12 GMT

### Context
We have a custom maven repository running on AWS with all packages downloaded from there.

This may be related: https://issues.apache.org/jira/browse/HTTPCLIENT-1077
Especially if gradle uses apache HttpClient

### PR DESCRIPTION
**Pull request by wolfs**
When downloading from some repositories like the oracle maven repository
httpclient is not able to parse the expires attribute in the set cookie
header.
This looks like using the `standard` cookie spec instead of the default
one fixes the problem. It is also necessary to upgrade httpclient to
the latest version to make this work for
https://issues.apache.org/jira/browse/HTTPCLIENT-1077.

This would fix #1596.

### CODE REVIEW

**Comment by big-guy** [comment]
@mark-vieira did the last HTTPClient upgrade.  I don't know if there's anything special we need to check to make sure this works (I think our NTLM/Kerberos coverage is non-existent).

**Comment by mark-vieira** [comment]
We have _some_ NTLM support but it only the username/password scenario and pretty limited. We have no Kerberos coverage that I'm aware of.

FYI, I'd be a little tentative to change cookie policies when it's not super clear what all this means. Are there now _other_ scenarios that used to work that won't anymore?

**Comment by alkemist** [comment]
The `Expires` attribute of `Set-Cookie` header that GE apps will send is definitely valid, so the fix has to be on the Gradle side. 

However, I can't fathom what Apache HTTP client is doing here. Based on the last comment on ttps://issues.apache.org/jira/browse/HTTPCLIENT-1077, this should work out of the box with the default cookie parsing policy. 

Regardless, we should end up with some _functional_ tests out of this where we launch HTTP requests at server we control that can send back different kinds of cookies that we will encompass in the wild and assert that we don't see errors.

**Comment by alkemist** [comment]
Also, fwiw, our build cache implementation does not set any cookies. So, they are either pointing at something else or they have something custom in front that is adding cookies. My guess is that they have misconfigured and are pointing at the scans app, which does set cookies.

**Comment by wolfs** [comment]
@alkemist Yes, they have been pointing the URL to the wrong place - `/build-cache/` instead of `/cache/`. So these warnings will not show up for the build cache - which is good.
I digged a little bit deeper into the httpclient code. It seems like the `default` cookie header parser of httpclient checks if there is an expires header in the cookie and no version - if this is the case it uses a Netscape spec parser. This parser currently only supports dates of the form `EEE, dd-MMM-yy HH:mm:ss z`. The cookie under question sends a date of the form `EEE, dd MMM yyyy HH:mm:ss zzz`.
The `standard` cookie header parser would allow three other date formats: 
 - `EEE, dd MMM yyyy HH:mm:ss zzz`
 - `EEE, dd-MMM-yy HH:mm:ss zzz`
 - `EEE MMM d HH:mm:ss yyyy`
but not the netscape one.
We could use the `default` cookie spec and allow more date patterns. WDYT?

**Comment by mark-vieira** [comment]
> We could use the default cookie spec and allow more date patterns. WDYT?

This would be my preference as there are likely _other_ differences with switching to the "standard" spec.

**Comment by wolfs** [comment]
@mark-vieira @alkemist Here is a fix for the problem by accepting more date patterns for the `expires` header. WDYT?
Any good ideas where I could add tests for the new behavior?

**Comment by mark-vieira** [comment]
My gut is we should have integration tests in the `resourcesHttp` project for this kind of stuff. Currently all integration testing revolves around some _use_ of this core library (i.e. dependency resolution) but I'm not sure that's the best place to put it since now things like the build cache client share this logic. 

This would also be a good place to put generic HTTP integration tests like SNI handling, etc.

@alkemist thoughts?

**Comment by wolfs** [comment]
@alkemist @mark-vieira I added some integration tests. Could you provide some more data for the use-cases (cookie headers) I should still test?

File: subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientConfigurer.java [hunk 1]
```diff
@@ -159,6 +169,32 @@ public void configureUserAgent(HttpClientBuilder builder) {
         builder.setUserAgent(UriTextResource.getUserAgentString());
     }
 
+    private void configureCookieSpecRegistry(HttpClientBuilder builder) {
+        PublicSuffixMatcher publicSuffixMatcher = PublicSuffixMatcherLoader.getDefault();
```
Comment (mark-vieira) [inline subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientConfigurer.java]: I don't see the need for doing this. `HttpClientBuilder` already initializes this with this value when unspecified.

Comment (mark-vieira) [inline subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientConfigurer.java]: I think we could avoid a lot of this reimplementation of HttpClient code by just calling `CookieSpecRegistries.createDefault` and then using `register()` to replace the ones we need to.

Comment (wolfs) [inline subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientConfigurer.java]: We can't use `CookieSpecRegistries` since this has been introduced in http client `4.5` and we are using `4.4.1` :(

Comment (wolfs) [inline subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientConfigurer.java]: We can't use CookieSpecRegistries since this has been introduced in http client 4.5 and we are using 4.4.1 :(

**Comment by wolfs** [comment]
@mark-vieira I replied to your comment. Anything else?
