### PR TITLE
Filter out JREs when looking for compiler/javadoc in toolchains

### LINKED ISSUE #22831: JavaToolchainService.compilerFor will provide a JRE in case that is the only toolchain available
Currently, `JavaToolchainService.compilerFor` will return a JRE in case no JDK is available, and only a JRE is detected. 

### Expected Behavior
`JavaToolchainService.compilerFor` should never return something backed by a JRE.

### Current Behavior
Currently, it will take [JDK over JRE](https://github.com/gradle/gradle/blob/419f98937994b291ad48ba3cdf04d94d42009bf3/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainComparator.java#L30) however, there is no check in case only a JRE is available.

### Steps to Reproduce 
Run it on a machine where only a JRE is detected.

### Proposal
I propose to enhance `JavaToolchainSpec` also to be able to request specific capabilities and request a `JAVA_COMPILER` capability when calling `JavaToolchainService.compilerFor`

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #22831 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Review by tresat — CHANGES_REQUESTED** [review]
I'm worried about the definition of a JDK/JRE used here not being precise enough causing issues at some point.

File: testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AvailableJavaHomes.java [hunk 1]
```diff
@@ -148,13 +148,20 @@ public static List<Jvm> getAvailableJdks(final JavaVersion version) {
         return getAvailableJdks(element -> version.equals(element.getLanguageVersion()));
     }
 
+    public static List<Jvm> getAvailableJdks(final Spec<? super JvmInstallationMetadata> filter) {
+        return getAvailableJvmMetadatas().stream()
+            .filter(input -> input.hasCapability(JAVA_COMPILER))
```
[the remark this answers is not in the document]
Comment (octylFractal) [reply testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AvailableJavaHomes.java:153]: I suppose, I will also check for `javadoc`. If we need anything more specific we can add it when needed, this is only for internal testing anyways.

File: platforms/jvm/toolchains-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java [hunk 2]
```diff
@@ -134,24 +179,25 @@ private JavaToolchain resolveToolchain(JavaToolchainSpecInternal requestedSpec)
...
+    private JavaToolchain query(JavaToolchainSpec spec, Set<JavaInstallationCapability> requiredCapabilities, boolean isFallback) {
         if (spec instanceof CurrentJvmToolchainSpec) {
-            return asToolchainOrThrow(InstallationLocation.autoDetected(currentJavaHome, "current JVM"), spec, isFallback);
+            return asToolchainOrThrow(InstallationLocation.autoDetected(currentJavaHome, "current JVM"), spec, requiredCapabilities, isFallback);
         }
 
         if (spec instanceof SpecificInstallationToolchainSpec) {
-            return asToolchainOrThrow(InstallationLocation.userDefined(((SpecificInstallationToolchainSpec) spec).getJavaHome(), "specific installation"), spec, false);
+            return asToolchainOrThrow(InstallationLocation.userDefined(((SpecificInstallationToolchainSpec) spec).getJavaHome(), "specific installation"), spec, requiredCapabilities, false);
         }
```
[the remark this answers is not in the document]
Comment (octylFractal) [reply platforms/jvm/toolchains-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java:189]: I'm not sure we have any code that asks the _spec(ification)_ for the end result of the query? This seems normal to me.

File: platforms/jvm/toolchains-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java [hunk 3]
```diff
@@ -172,27 +218,30 @@ private void warnIfAutoProvisionedToolchainUsedWithoutRepositoryDefinitions(Inst
...
     }
 
-    private JavaToolchain downloadToolchain(JavaToolchainSpec spec) {
+    private JavaToolchain downloadToolchain(JavaToolchainSpec spec, Set<JavaInstallationCapability> requiredCapabilities) {
```
[the remark this answers is not in the document]
Comment (octylFractal) [reply platforms/jvm/toolchains-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java:221]: No, the `spec` is end-user configuration, whereas these capabilities are only used internally. It would be interesting to consider exposing them as public API in the future (#29278 related).

File: platforms/jvm/toolchains-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JvmMetadataWithAddedCapabilities.groovy [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.gradle.jvm.toolchain.internal
+
+import org.gradle.internal.jvm.inspection.JavaInstallationCapability
+import org.gradle.internal.jvm.inspection.JvmInstallationMetadata
+
+class JvmMetadataWithAddedCapabilities implements JvmInstallationMetadata {
```
Comment (tresat) [inline platforms/jvm/toolchains-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JvmMetadataWithAddedCapabilities.groovy:22]: 💅 Missing javadoc on new top-level type.

File: platforms/jvm/toolchains-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JvmMetadataWithAddedCapabilities.groovy [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+    @Delegate
+    private final JvmInstallationMetadata metadata
+    private final Set<JavaInstallationCapability> additionalCapabilities
+
+    JvmMetadataWithAddedCapabilities(JvmInstallationMetadata metadata, Set<JavaInstallationCapability> additionalCapabilities) {
+        this.metadata = metadata
+        this.additionalCapabilities = additionalCapabilities
```
Comment (tresat) [inline platforms/jvm/toolchains-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JvmMetadataWithAddedCapabilities.groovy:29]: 💭 Should this create a defensive copy of this collection?

File: platforms/jvm/toolchains-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java [hunk 6]
```diff
@@ -38,16 +39,53 @@
...
 @ServiceScope(Scope.Project.class) //TODO #24353: should be much higher scoped, as many other toolchain related services, but is bogged down by the scope of services it depends on
 public class JavaToolchainQueryService {
 
+    private static final class ToolchainLookupKey {
+        private final JavaToolchainSpecInternal.Key specKey;
+        private final Set<JavaInstallationCapability> requiredCapabilities;
+
+        private ToolchainLookupKey(JavaToolchainSpecInternal.Key specKey, Set<JavaInstallationCapability> requiredCapabilities) {
+            this.specKey = specKey;
+            this.requiredCapabilities = requiredCapabilities;
```
Comment (tresat) [inline platforms/jvm/toolchains-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java:60]: 💭 Defensive copies needed?  At least of the collection.

**Review by tresat — APPROVED** [review]
Looks good, I only left a few nitpicks. 

After seeing these changes, I'm even more strongly in favor of including capabilities in the `spec` via something like https://github.com/gradle/gradle/issues/29278 in the future, as they appear to be "arguments that travel together" and should be consolidated into a single type.

File: platforms/jvm/toolchains-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JvmMetadataWithAddedCapabilities.groovy (hunk 4 above)
Comment (octylFractal) [reply platforms/jvm/toolchains-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JvmMetadataWithAddedCapabilities.groovy:22]: Perhaps we should have an archunit or checkstyle rule for this.

Comment (tresat) [reply platforms/jvm/toolchains-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JvmMetadataWithAddedCapabilities.groovy:31]: Absolutely.
