### PR TITLE
Fix CC compatibility of Resource compilation on Windows

### LINKED ISSUE #30717: Linking resources on Windows does not work with CC
See [this failure](https://ge.gradle.org/s/c5gwmvnduirpw/tests/task/:language-native:configCacheIntegTest/details/org.gradle.language.rc.WindowsResourcesIntegrationTest/build%20static%20library%20and%20link%20into%20executable%20visual%20c%2B%2B%202019%20(16.0.0)?top-execution=1)

There is an input file collection of stuff to link, that should include an RC file that is provided by the resource compiler task. It works without CC, but with CC it fails: it evaluates the file collection down to files when storing CC and skips the RC file because it isn't there yet.

### PR DESCRIPTION
**Pull request by mlopatkin**
By preserving file collection structure for link files

The resource compiler adds a complex output file collection as an extra link files source, that can only be evaluated once the resources have been built. Stuffing everything into StaticLibraryLinkOutputs hides this complexity inside an opaque FileCollection. The configuration cache cannot rediscover the structure and ends up resolving the collection at store time, effectively ignoring the extra files.

This commit changes the file collection implementation so CC can store the resource compilations output structure properly, in a lazy manner.

Fixes #30717

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, ACC

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, ACC without PTS

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, ACC without PTS

**Review by adammurdoch — APPROVED** [review]

File: platforms/native/platform-native/src/main/java/org/gradle/nativeplatform/internal/DefaultStaticLibraryBinarySpec.java [hunk 1]
```diff
@@ -58,7 +59,10 @@ public void additionalLinkFiles(FileCollection files) {
 
     @Override
     public FileCollection getLinkFiles() {
-        return getFileCollectionFactory().create(new StaticLibraryLinkOutputs());
+        ConfigurableFileCollection result = getFileCollectionFactory().configurableFiles("Link files for " + getDisplayName());
+        result.from(getFileCollectionFactory().create(new StaticLibraryLinkOutputs()));
+        additionalLinkFiles.forEach(result::from);
```
Comment (big-guy) [inline platforms/native/platform-native/src/main/java/org/gradle/nativeplatform/internal/DefaultStaticLibraryBinarySpec.java:64]: I think this might have a slightly different meaning now--`getLinkFiles()` will only contain the elements of `additionalLinkFiles` that were added before `getLinkFiles` is called. 

It's hard to tell if this actually makes a difference because there are so many places we call `getLinkFiles` in a deferred way. 

Would something like this also work for CC?
```
result.from(additionalLinkFiles)
```
