### PR TITLE
Fix issue with test exception that cannot be deserialized

### LINKED ISSUE #23602: Since Gradle 7.6 my integration tests fail - but report "BUILD SUCCESSFUL"
I upgraded to Gradle 7.6 and at first everything seemed to be fine. Then I noticed a *decrease* in unit tests according to test reports in my Jenkins pipeline.
But I did not delete any tests.
Turns out: my integration tests fail with weird exceptions - but Gradle still reports "BUILD SUCCESSFULL" even though on the console you can see Exceptions and breaking tests.

The log reads like this:
```
+ ./gradlew :integrationTest
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :processIntegrationTestResources
> Task :compileIntegrationTestKotlin
> Task :compileIntegrationTestJava NO-SOURCE
> Task :integrationTestClasses
> Task :integrationTest

Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:60814'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:72)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	... 6 more

BUILD SUCCESSFUL in 2m 2s
7 actionable tasks: 3 executed, 4 up-to-date

It was by pure luck I saw these exceptions only because the number tests seemingly decreased...

```
### Expected Behavior
First: my tests should run just like they did with Gradle 7.5.1 before.
Second: I would love some explanation on that issue...
Thirdly: IF a build produces exceptions and skipped / omitted tests, it should not SUCCEED. It should fail.

### Current Behavior
My build succeeds even though the build is not properly done. Tests are missing without any notice which basically is the worst case scenario. Tests should never disappear unnoticed.

### Context
Happens locally on a MacBook as well as on a Jenkins server (Windows)

### Steps to Reproduce 
I have no idea on how to do this... :-(

### Your Environment

Build scan URL:
https://gradle.com/s/v77ms75oxijm6

### PR DESCRIPTION
**Pull request by ghale**
Previously, a failure while deserializing an exception thrown by a test would cause the result processor proxy to blow up and fail and the test would be in an unknown state.  This changes it so that we capture failures that occur during deserialization of the exception and we replace the test exception with an exception that notifies the user that there was an exception with a given type, but we are unable to provide the full exception because it failed to deserialize when transmitting back to the build process.  In specific cases, we might be able to do something about the issue with deserialization, but in the general case, I think this is the best we can do.  We'll now at least report the test as failed and provide some minimal information to the user so that they know what exception was thrown and why we couldn't provide more.

Fixes #23602

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java [hunk 1]
```diff
@@ -183,12 +182,19 @@ public DefaultTestFailure read(Decoder decoder) throws Exception {
             for (int i = 0; i < numOfCauses; i++) {
                 causes.add(read(decoder));
             }
+
+            String rawFailureName = decoder.readString();
```
Comment (tresat) [inline subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:186]: 🧐 Perhaps worth extracting a `readFailure()` method here?

Would also allow a good place to document the purpose of this check, which might seem to be just wrapping an exception for no good reason.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java [hunk 2]
```diff
@@ -199,6 +205,9 @@ public void write(Encoder encoder, DefaultTestFailure value) throws Exception {
             for (TestFailure cause : value.getCauses()) {
                 write(encoder, (DefaultTestFailure) cause);
             }
+            Throwable rawFailure = value.getRawFailure();
```
Comment (tresat) [inline subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:208]: 🧐 If adding a `readFailure()` method (here or elsewhere), it would be good to add a `writeFailure()` method too, so that it is obvious these 2 sections of code must remain in sync.  This could be noted in the docstrings.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java [hunk 3]
```diff
@@ -183,12 +182,19 @@ public DefaultTestFailure read(Decoder decoder) throws Exception {
             for (int i = 0; i < numOfCauses; i++) {
                 causes.add(read(decoder));
             }
+
+            String rawFailureName = decoder.readString();
+            Throwable rawFailure;
+            try {
+               rawFailure = throwableSerializer.read(decoder);
+            } catch(Exception e) {
+                rawFailure = new IllegalStateException("An exception of type " + rawFailureName + " was thrown by the test, but there was a failure while transmitting the exception back to the build process", e);
```
Comment (tresat) [inline subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:191]: ❕ I (weakly) don't think this is an appropriate place for an `ISE` - exactly what _state_ is illegal here/or what method has been invoked at the wrong time?  

I think a custom exception class would make it clear this problem has been anticipated by Gradle.  Or, alternately, if you think that is too heavyweight, maybe use `NotSerializableException` (also not quite a perfect fit, but perhaps closer than `ISE`)?

Comment (tresat) [inline subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:191]: ❔ Is "while transmitting" a proper description?  This makes me think of a communication/networking issue, not a serialization issue.  Also "there was a failure" should probably be rewritten to use active voice.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java [hunk 4]
```diff
@@ -183,12 +182,19 @@ public DefaultTestFailure read(Decoder decoder) throws Exception {
             for (int i = 0; i < numOfCauses; i++) {
                 causes.add(read(decoder));
             }
+
+            String rawFailureName = decoder.readString();
+            Throwable rawFailure;
+            try {
+               rawFailure = throwableSerializer.read(decoder);
+            } catch(Exception e) {
```
Comment (tresat) [inline subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:190]: 💭 Should this perhaps catch any `Throwable`?  IDK what other type of serialization failures we might encounter here.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java (hunk 1 above)
Comment (tresat) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:186]: 💭 Alternately, might this new method be moved to the `Serializer` interface itself as a `default readCatching()` method?  It seems like we might run into this problem elsewhere.

**Review by tresat — CHANGES_REQUESTED** [review]

**Review by jvandort — APPROVED** [review]
This looks good, though I think we're missing some extra handling for the "Unexpected exception thrown." message which is thrown in the original reproducer. I think if we encounter an unrecoverable error we should make sure to fail the test -- in order to protect from errors like this one again in the future.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java (hunk 4 above)
Comment (jvandort) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:190]: I think in general you should avoid catching `Throwable`s, since they include `Error`s like OOMs

File: subprojects/testing-jvm/src/testFixtures/groovy/org/gradle/testing/fixture/JUnitPlatformTestFixture.groovy [hunk 5]
```diff
@@ -108,6 +109,11 @@ trait JUnitPlatformTestFixture {
             return this
         }
 
+        TestClass withAdditionalContent(String content) {
```
[the remark this answers is not in the document]
Comment (jvandort) [reply subprojects/testing-jvm/src/testFixtures/groovy/org/gradle/testing/fixture/JUnitPlatformTestFixture.groovy:112]: TBH I'm not sure I'm in love with the whole `testClass` and `testMethod` structure in this test, since in order to understand the structure of the test classes you need to learn a new niche DSL. Obviously not something to fix in here, but I was able to understand the tests added in the other classes more easily than the ones for junit platform.

[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/testing-jvm/src/testFixtures/groovy/org/gradle/testing/fixture/JUnitPlatformTestFixture.groovy:112]: > but I was able to understand the tests added in the other classes more easily than the ones for junit platform.

👍

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java (hunk 4 above)
Comment (tresat) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:190]: Yeah, that's definitely the downside.  But OTOH, an `OOM` _during de-serialization_ might be a result of some wacky custom de-serialization logic bug.

Comment (jvandort) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:190]: Yes, potentially, but we would want that OOM to bubble up and fail the build. If we caught it here, we would be saving it off as a reference and letting execution continue, which is not what we want to do with an OOM.

Comment (tresat) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:190]: I think that's maybe debatable.  A memory issue caused by a bad de-serialization of a custom exception type might be fully recoverable rather than fatal.  But I don't feel too strongly about this, I just just noting it something to consider.

Comment (jvandort) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:190]: How could we feasibly recover from this? Recovering from OOMs is not something I really have experience with, so I'm not sure what we'd do here in this case

Comment (tresat) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:190]: If the failure is caused during attempted allocation of a gigantic array during instantiation, for instance, the JVM is fine afterwards - you just don't have an instance (or a gigantic array).

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java [hunk 6]
```diff
@@ -171,7 +171,6 @@ public DefaultTestFailureSerializer(Serializer<Throwable> throwableSerializer) {
 
         @Override
         public DefaultTestFailure read(Decoder decoder) throws Exception {
-            Throwable rawFailure = throwableSerializer.read(decoder);
```
[the remark this answers is not in the document]
Comment (ghale) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:174]: What it handles cleanly is a failure to rehydrate a valid object that is properly transmitted (i.e. we get a ClassNotFound or something similar).  My understanding is that it is still potentially possible to have some sort of weird error where the object isn't valid or the stream is corrupt and this could blow up the stream before it finished fully reading the object.

Those are not things that should happen normally, but my thinking here was that if that _did_ happened, by moving this to the end of the stream, you would still at least get a test failure for _this_ test and the captured failure would be a clue as to what was happening.  It would be nice to have a test for that case, too, but that would be such a low level failure (i.e. creating/serializing invalid objects or corrupting the byte stream) it seemed like overkill.

I don't _think_ reordering the data in the test event protocol would affect anything.

File: subprojects/testing-jvm/src/testFixtures/groovy/org/gradle/testing/fixture/JUnitPlatformTestFixture.groovy (hunk 5 above)
[the remark this answers is not in the document]
Comment (ghale) [reply subprojects/testing-jvm/src/testFixtures/groovy/org/gradle/testing/fixture/JUnitPlatformTestFixture.groovy]: I think you're right.  I almost yanked it out before I cut the PR, but then for some reason I didn't.  It can be expressive when you've got a bunch of simple tests that pass/fail/skip without a bunch of boilerplate, but here it doesn't seem to simplify anything.  

I've changed it to just a raw test class.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java (hunk 1 above)
Comment (ghale) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:197]: I've pulled it out into a method with some docs on why we do what we do.  

I'm not sure about pulling it up into `Serializer` because I couldn't think of a case where we would want to do something similar (i.e. catch the exception and wrap it rather than just throwing it up the chain).  Doesn't mean a case doesn't exist, I just couldn't think of one.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java (hunk 4 above)
Comment (ghale) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java:201]: I agree with @jvandort.  I'd prefer to just catch `Exception` here for now.  We can always make this less specific if we find a case where we get a `Throwable` instead.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java (hunk 3 above)
Comment (ghale) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java]: Well the "illegal state" is that we don't have the exception that we want to put in the test failure.  It's admittedly a weak association.  I changed it to a custom exception class.

Comment (ghale) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java]: I changed this to "but Gradle was unable to recreate the exception in the build process".  I'm struggling to describe this in a way that is sensible to the user without being too abstract (i.e. I don't think the user knows or cares if the exception is being serialized/deserialized so I wanted to avoid being that technical).  I don't feel like the current message is great, either, but I couldn't think of anything better.  I'm open to suggestions. if you have better ideas.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java (hunk 2 above)
Comment (ghale) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java]: Good point.  Done.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java (hunk 3 above)
Comment (tresat) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java]: I think that's already a big improvement.  Should be enough of a breadcrumb, and I don't have anything better.

**Review by tresat — APPROVED** [review]

**Comment by ghale** [comment]
@bot-gradle test and merge

**Comment by Zordid** [comment]
Will your fix be backported to Gradle 7 as well?

**Comment by ghale** [comment]
@Zordid Sorry for the late reply, for some reason I never saw your question.  We haven't done any 7.x patches since this fix was implemented, but I created [a new issue](https://github.com/gradle/gradle/issues/24901) to backport this to 7.x.  Assuming we do another 7.x release, we'll try to get this included.
