### PR TITLE
JVM running Gradle should be preferred if it matches Toolchain spec

### LINKED ISSUE #18290: Unexpected behavior of Java toolchains
This is following a conversation with @ilopmar who was puzzled by this behavior and @ljacomet who suggested to raise an issue for discussion.

### Expected Behavior

If the Java version which Gradle runs on is compatible with the requested toolchain, then this version should be preferred over other detected toolchains.

### Current Behavior

Currently, even if the current Java version is compatible with the toolchain requirements, a different _compatible_ toolchain can be selected by Gradle.

### Context

The [native image plugin](https://github.com/graalvm/native-build-tools/) makes use of the toolchain mechanism to select the right version of `native-image` to call. This is configured this way:

```java
        getJavaLauncher().convention(
                toolchains.launcherFor(spec -> {
                    spec.getLanguageVersion().set(JavaLanguageVersion.of(JavaVersion.current().getMajorVersion()));
                    if (GradleUtils.isAtLeastGradle7()) {
                        spec.getVendor().set(JvmVendorSpec.matching("GraalVM"));
                    }
                })
        );
```

which, basically, means that we set the language version to the current Java version (that Gradle uses). We have to do this because there's no public API allowing to tell what version to use from either the `java { toolchain { ... } }` spec, nor the old `targetCompatibility`. However, you'll notice that it simply makes sure that if you run on Gradle with say, Java 8, then it's going to use a GraalVM JDK 8 release. The user can override this default using our DSL:

```gradle
graalvmNative {
    images {
        main {
            javaLauncher = javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(11)
                vendor = JvmVendorSpec.matching("GraalVM")
            }
        }
    }
}
```

Now, imagine that you have multiple GraalVM installations that Gradle is capable of detecting. Typically, here, multiple versions installed via SDKMAN! There might be different folders containing different releases of GraalVM, and in particular more than one version compatible with Java 11: 21.1.0, 21.2.0, ...

If the requirement is set to `JavaLanguageVersion.of(11)` and that you start a build with AdoptOpenJDK 8, then Gradle will determine that it's not compatible, but it will find an appropriate JDK via auto-detection and SDKMAN!. You won't be able to tell which one you prefer, but that's probably fine (this should ideally be modeled as another property of the spec).

Now, imagine that instead, you start the build with GraalVM 21.2.0 for Java 11. This toolchain _is_ compatible with the requirement. However, when started, we can see that the version of GraalVM which is used to start `native-image` is a _different one_:

```
> Task :nativeCompile
Executing [
/home/ivan/.sdkman/candidates/java/graal-jdk11-master-patch-resources/bin/java \ <----
```

So despite the fact that the _current version_ is compatible, Gradle prefers to use a different one, which is also technically speaking compatible, but unexpected.

The consequence is that for users who are used to the "old way" of switching JDKs from command-line to build with a different JDK get confused by the selection. The only workaround is to disable detection (`-Porg.gradle.java.installations.auto-detect=false` **and** to set the toolchains locations explicitly, e.g `org.gradle.java.installations.fromEnv=JAVA_HOME`.

IMO, if the current Java version is compatible, it should be preferred over other detected installations.

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #18290

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test RFM

File: subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java [hunk 1]
```diff
@@ -73,15 +80,23 @@ private JavaToolchain query(JavaToolchainSpec filter) {
         if (filter instanceof SpecificInstallationToolchainSpec) {
             return asToolchain(((SpecificInstallationToolchainSpec) filter).getJavaHome(), filter).get();
         }
-        return registry.listInstallations().stream()
+
+        Optional<JavaToolchain> currentJvmAsMatchingToolchain = Stream.of(asToolchain(currentJvmHome, filter))
```
Comment (ljacomet) [inline subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java:84]: I am afraid this is too simplistic. The current JVM should only be considered if auto-detection is enabled. If it is not, then it should not be selected and only specific configured toolchain should be selected.

**Review by ljacomet — CHANGES_REQUESTED** [review]

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaExecToolchainIntegrationTest.groovy [hunk 2]
```diff
@@ -14,17 +14,17 @@
...
-import org.gradle.api.JavaVersion
 import org.gradle.integtests.fixtures.AbstractPluginIntegrationTest
 import org.gradle.integtests.fixtures.AvailableJavaHomes
 import org.gradle.internal.jvm.Jvm
 import spock.lang.IgnoreIf
 
 class JavaExecToolchainIntegrationTest extends AbstractPluginIntegrationTest {
 
-    @IgnoreIf({ AvailableJavaHomes.differentJdk == null })
+    @IgnoreIf({ AvailableJavaHomes.differentVersion == null })
```
[the remark this answers is not in the document]
Comment (jbartok) [reply subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaExecToolchainIntegrationTest.groovy:27]: These tests have turned nondeterministic precisely because of what you are saying in your other comment, ie. because I made it pick the current JVM even when auto-detection wasn't enabled. Will revert.

File: subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainQueryServiceTest.groovy [hunk 3]
```diff
@@ -282,6 +283,24 @@ class JavaToolchainQueryServiceTest extends Specification {
         installed == 1
     }
 
+    @Ignore //todo: need to make it work somehow
```
Comment (jbartok) [inline subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainQueryServiceTest.groovy:286]: Need to make this actually work somehow.

File: subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainComparator.java [hunk 4]
```diff
@@ -23,10 +23,17 @@
 
 public class JavaToolchainComparator implements Comparator<JavaToolchain> {
 
+    private final boolean currentJvmMatters;
+
+    public JavaToolchainComparator(boolean currentJvmMatters) {
+        this.currentJvmMatters = currentJvmMatters;
```
Comment (ljacomet) [inline subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainComparator.java:29]: This is not needed. The current vm detector is disabled if auto-detection is disabled.

**Review by ljacomet — CHANGES_REQUESTED** [review]
Overall logic looks better

See below for further simplification

File: subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainComparator.java (hunk 4 above)
Comment (jbartok) [reply subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainComparator.java:29]: I don't think this is true. The `JavaToolchainQueryService` will sort the installations via the `JavaToolchainComparator` even when auto-detection is off. Let's say on a CI server where the installations have been specified via `org.gradle.java.installations.paths`. If I understand correctly, in such a situation we don't want the current JVM to end up first/be picked, but if I remove that boolean flag, it will be. 

As proof: `JavaToolchainQueryServiceTest.refer version Gradle is running on as long as it is a match` passes even if you set `auto-detection` to `false` on line 393. (Talking about the code as is now in this PR).

**Comment by jbartok** [comment]
@bot-gradle test QFL

File: subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainComparator.java (hunk 4 above)
Comment (ljacomet) [reply subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainComparator.java:29]: You are right! I missed that corner case. This should be clearly documented though. I will add a note to the issue about this.

File: subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainComparator.java [hunk 5]
```diff
@@ -23,10 +23,17 @@
 
 public class JavaToolchainComparator implements Comparator<JavaToolchain> {
 
+    private final boolean currentJvmMatters;
```
Comment (ljacomet) [inline subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainComparator.java:26]: I would rename this to `prioritizeCurrentJvm` to make the intent clearer

**Review by ljacomet — APPROVED** [review]
Minor rename suggestion, otherwise LGTM once tests pass 😉

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Review by ljacomet — APPROVED** [review]
