### PR TITLE
Revert exposing internal APIs

### LINKED ISSUE #23440: Gradle 8 compiled plugins are not usable with Gradle <7
### Expected Behavior
When I compile a plugin with the latest Gradle version, I expect it to work with older versions, otherwise it's not possible to support a range of Gradle versions. See e.g. Kotlin or Gradle Enterprise plugins which do this extensively.

### Current Behavior
```kotlin
abstract class SomeTask: DefaultTask() // not necessary to be defined here, just to show the inheritance tree

fun something(some: SomeTask) {
   some.inputs.files(...)
}
```
compiling the above against `implementation(gradleApi())` in Gradle 8 RC1, it binds (at compile time) to

https://github.com/gradle/gradle/blob/287aac28bc8f1de1b1b74852da8b254cc376bbfb/subprojects/core/src/main/java/org/gradle/api/internal/TaskInputsInternal.java#L31-L32

### Steps to Reproduce 
1. Compile a plugin with Gradle 8 which calls `task.inputs.files(...)`
2. Use this plugin in Gradle 7.x
3. Stand in awe of this beauty:
```
Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.internal.tasks.TaskInputFilePropertyBuilderInternal org.gradle.api.internal.TaskInputsInternal.files(java.lang.Object[])'
	at com.example.SomethingKt.something(something.kt:4)
```

### Context
@lptr added these methods recently: https://github.com/gradle/gradle/pull/22739
It looks like we've been here before as @big-guy explains with Gradle 3.2 breaking compatibility: https://github.com/gradle/gradle/issues/1030
https://github.com/gradle/gradle/issues/1004 is the issue that's being regressed I guess.
Related, or potentially "caused by": https://github.com/gradle/gradle/issues/23431

### Workaround
`(some as Task).inputs` will force the compile-time binding to resolve `Task.getInputs(): TaskInputs` which doesn't have the `files()` overload and therefore compatible with all Gradle versions.

"Gradle Plugin author DX" will be disrupted if this stays like this.

### Your Environment

Build scan URL: it's simple to see the problem statically, but if really necessary I can set up a running example.
For real examples: [see this build's test report artifacts](https://github.com/TWiStErRob/net.twisterrob.gradle/actions/runs/3866626055) (tests in this project runs many Gradle builds for compatibility testing).

### PR DESCRIPTION
**Pull request by lptr**
Because DefaultTask.getInputs() exposes internal APIs (see , we ended up accidentally exposing more internal APIs that caused plugins compiled against Gradle 8.0 to fail to load with earlier versions. This reverts the change to fix the immediate issue.

Fixes #23440

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test this please.

File: subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/AbstractTaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy [hunk 1]
```diff
@@ -224,9 +217,13 @@ apply plugin: SomePlugin
 
             task t(type: SubclassTask)
         """
+    }
 
-        then:
-        version previous withTasks 'assemble' inDirectory(file("producer")) run()
-        version current requireDaemon() requireIsolatedDaemons() withTasks 't' run()
+    protected static String declareTaskClass(GradleVersion targetVersion) {
+        if (targetVersion >= GradleVersion.version("7.0")) {
```
Comment (lptr) [inline subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/AbstractTaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy:223]: 💬 Version 7.0 is not the version where we introduced abstract task support, but we only actually need to declare these tasks as `abstract` from Gradle 8.0 so this is sufficient, at least for this quick-fix PR. We can fine-tune this more in a later PR.

**Review by ljacomet — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test and merge
