### PR TITLE
Make progress bar robust against excessive progress reports (#24576)

### LINKED ISSUE #24576: `NegativeArraySizeException` during progress rendering
Due to issues like #24370, it can happen that the done work is more than the total work.
If this is "over-enough", the calculation of the progress bar visualization causes a `NegativeArraySizeException`.
And this then causes the console output to hang completely with 8.0.2 as reported in #24575.

So as formula, currently as soon as `ceil((14 / 13 * totalWork) - totalWork)` work items too many are reported, the calculation will cause the `NegativeArraySizeException`. With total work of 1225 as in #24370 this makes for a buffer of 94 additional work items or 107.7 %. While investigating and reproducing the total work was reduced to 1, which then has a puffer of 0 and stalls the output as soon as one work item is repoted too much. And for a buffer of 1 additional work item without exception you need a total work amount of 14.

```plain
java.lang.NegativeArraySizeException: -52
	at org.gradle.internal.logging.console.ProgressBar.fill(ProgressBar.java:90)
	at org.gradle.internal.logging.console.ProgressBar.formatProgress(ProgressBar.java:76)
	at org.gradle.internal.logging.console.BuildStatusRenderer.renderNow(BuildStatusRenderer.java:122)
	at org.gradle.internal.logging.console.BuildStatusRenderer.onOutput(BuildStatusRenderer.java:114)
	at org.gradle.internal.logging.console.AbstractUserInputRenderer.onOutput(AbstractUserInputRenderer.java:56)
	at org.gradle.internal.logging.console.ThrottlingOutputEventListener.renderNow(ThrottlingOutputEventListener.java:95)
	at org.gradle.internal.logging.console.ThrottlingOutputEventListener.onOutput(ThrottlingOutputEventListener.java:72)
	at org.gradle.internal.logging.console.ThrottlingOutputEventListener$1.run(ThrottlingOutputEventListener.java:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #24576

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- n/a Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- n/a Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

File: subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java [hunk 1]
```diff
@@ -60,6 +64,16 @@ public void moreProgress(int totalProgress) {
 
     public void update(boolean failing) {
         this.current++;
+        if (current > total) {
```
Comment (hegyibalint) [inline subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java:67]: 🤔 I'm not convinced of this solution. It seems excessive that we start a thread for this. 

If we hit the condition `current > total`, we are going to start a thread for _each_ invocation of `update`.
This method will be called from `BuildStatusRendeded.onOutput`

https://github.com/gradle/gradle/blob/eb27e930e9120bff77261c49818111fcfda2bcdc/subprojects/logging/src/main/java/org/gradle/internal/logging/console/BuildStatusRenderer.java#L101-L108

I don't have an exact place where the events are created, but I'm afraid that we get an event for every build operation, and that would mean a _lot_ of threads created.

Depending on these factors, it might be better not to log anything. Looking at [`OutputEventListenerBackedLoggerContext`](https://github.com/gradle/gradle/blob/eb27e930e9120bff77261c49818111fcfda2bcdc/subprojects/logging/src/main/java/org/gradle/internal/logging/slf4j/OutputEventListenerBackedLoggerContext.java), there would be ways to extend the class a bit not to emit events when logging.

WDYT?

Comment (Vampire) [reply subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java:67]: I considered not logging it, but the problem with not logging anything is, that you then will not get reports about such incidents.
My intention was, that there are warning printed to increase the probability that users actually report such cases, that should always be bugs of either `total` not being set correctly, or `update` being called wrongly.

And usually, the case should not happen, as it is a bug if it happens.
So I thought if it actually happens, it would be ok to start threads there.

Also, I don't think it would be lots of threads, unless there is much discrepancy between the `current` and `total`.
`total` is the amount of actions in the build, so mainly the amount of tasks that are being executed. Some other things too, like artifact transformations done.
For example in #24370 which was the trigger for this fix, `total` was 1225 and there were 54 additional `update` calls. So yes, in this quite big build, there would have been 54 Threads to log this warning if that is what you call "lot". It of course is "a lot", but caused by a bug and if no bug is there, no threads will be created. :-)

If you are concerned about the amount of threads, how about a single-thread-executor that gets lazily initialized on first exccessive "update" call and then is reused? This way it would only be one additional thread.

Comment (hegyibalint) [reply subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java:67]: > I considered not logging it, but the problem with not logging anything is, that you then will not get reports about such incidents.

I agree with this, I also think not logging should be a last resort to fix this.

> like artifact transformations done.

This is as example I'm afraid of, as AGP for example relies on transformations heavily. If we have any oops there, we might create ridiculous amount of threads.

> If you are concerned about the amount of threads, how about a single-thread-executor that gets lazily initialized on first exccessive "update" call and then is reused? This way it would only be one additional thread.

That sounds much better! Can I ask you to implement it?

File: subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java [hunk 2]
```diff
@@ -60,6 +64,16 @@ public void moreProgress(int totalProgress) {
...
+            new Thread(new Runnable() {
+                @Override
+                public void run() {
+                    // do not do this directly or a deadlock happens
+                    // to prevent that deadlock, execute it separately in a new thread
+                    LOGGER.warn("More progress was logged than there should be ({} > {})", current, total);
```
Comment (hegyibalint) [inline subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java:73]: I'm trying to wrap my head around how deferring stops us having a livelock here.
IIUC `LOGGER` will still report the event, and it should make a loop.

Comment (Vampire) [reply subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java:79]: If you merge this PR with #24592, comment out the deadlock prevention code, and use my reproducer from #24370, you can easily reproduce the deadlock.
Here the thread dump of the two relevant threads that block each other, I just reproduced it:
```threaddump
"main@1" prio=5 tid=0x1 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks pool-1-thread-1@1771
	 waiting for pool-1-thread-1@1771 to release lock on <0xa8c> (a java.lang.Object)
	  at org.gradle.internal.logging.console.ThrottlingOutputEventListener.onOutput(ThrottlingOutputEventListener.java:79)
	  at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source:-1)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	  at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
	  at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:257)
	  at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:164)
	  at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:148)
	  at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	  at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	  at com.sun.proxy.$Proxy0.onOutput(Unknown Source:-1)
	  at org.gradle.internal.logging.sink.OutputEventTransformer.invokeListener(OutputEventTransformer.java:113)
	  - locked <0xa80> (a java.lang.Object)
	  at org.gradle.internal.logging.sink.OutputEventTransformer.onOutput(OutputEventTransformer.java:90)
	  at org.gradle.internal.logging.sink.OutputEventRenderer.onOutput(OutputEventRenderer.java:430)
	  at org.gradle.internal.logging.sink.OutputEventListenerManager$1.onOutput(OutputEventListenerManager.java:36)
	  at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:242)
	  at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:202)
	  at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:152)
	  at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:98)
	  at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
	  at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:167)
	  at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:259)
	  at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:230)
	  at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:74)
	  at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
	  at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:96)
	  at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:40)
	  at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
	  at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	  at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:361)
	  at org.gradle.launcher.Main.doAction(Main.java:35)
	  at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	  at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.gradle.launcher.GradleMain.main(GradleMain.java:34)

"pool-1-thread-1@1771" prio=5 tid=0x12 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks main@1
	 waiting for main@1 to release lock on <0xa80> (a java.lang.Object)
	  at org.gradle.internal.logging.sink.OutputEventTransformer.invokeListener(OutputEventTransformer.java:113)
	  at org.gradle.internal.logging.sink.OutputEventTransformer.onOutput(OutputEventTransformer.java:106)
	  at org.gradle.internal.logging.sink.OutputEventRenderer.onOutput(OutputEventRenderer.java:430)
	  at org.gradle.internal.logging.sink.OutputEventListenerManager$1.onOutput(OutputEventListenerManager.java:36)
	  at org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger.log(OutputEventListenerBackedLogger.java:52)
	  at org.gradle.internal.logging.slf4j.BuildOperationAwareLogger.log(BuildOperationAwareLogger.java:140)
	  at org.gradle.internal.logging.slf4j.BuildOperationAwareLogger.log(BuildOperationAwareLogger.java:154)
	  at org.gradle.internal.logging.slf4j.BuildOperationAwareLogger.log(BuildOperationAwareLogger.java:148)
	  at org.gradle.internal.logging.slf4j.BuildOperationAwareLogger.warn(BuildOperationAwareLogger.java:382)
	  at org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger.warn(OutputEventListenerBackedLogger.java:25)
	  at org.gradle.internal.logging.console.ProgressBar.update(ProgressBar.java:79)
	  at org.gradle.internal.logging.console.BuildStatusRenderer.phaseProgressed(BuildStatusRenderer.java:140)
	  at org.gradle.internal.logging.console.BuildStatusRenderer.onOutput(BuildStatusRenderer.java:106)
	  at org.gradle.internal.logging.console.AbstractUserInputRenderer.onOutput(AbstractUserInputRenderer.java:56)
	  at org.gradle.internal.logging.console.ThrottlingOutputEventListener.renderNow(ThrottlingOutputEventListener.java:105)
	  at org.gradle.internal.logging.console.ThrottlingOutputEventListener.onOutput(ThrottlingOutputEventListener.java:82)
	  - locked <0xa8c> (a java.lang.Object)
	  at org.gradle.internal.logging.console.ThrottlingOutputEventListener$1.run(ThrottlingOutputEventListener.java:66)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at java.lang.Thread.run(Thread.java:829)
```
By not logging directly from the progress bar, but doing it from a different thread, this mutual deadlock is broken.

Comment (Vampire) [reply subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java:79]: Of course this deadlock could also be another bug that should instead be fixed properly so that it cannot happen, but I didn't investigate in that direction. :-)

File: subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java (hunk 1 above)
Comment (Vampire) [reply subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java:70]: Sure, no problem at all. Update pushed.

**Comment by hegyibalint** [comment]
@bot-gradle test this

**Comment by Vampire** [comment]
Is the compilation error at https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_CompileAllBuild_BuildCacheNG/68179315?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildChangesSection=true something I should worry about?

**Comment by hegyibalint** [comment]
> Is the compilation error at https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_CompileAllBuild_BuildCacheNG/68179315?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildChangesSection=true something I should worry about?

No, this is only to dogfood the new cache solution we are working on.

**Review by hegyibalint — APPROVED** [review]

**Comment by hegyibalint** [comment]
@bot-gradle test and merge please

**Comment by eskatos** [comment]
@bot-gradle test and merge
