### PR TITLE
Disable configuration cache on TAPI model building

### LINKED ISSUE #15044: Configuration cache - Intellij synchronization crashes
When using configuration cache with a kotlin based gradle project in Intellij, the first synchronization works but the second (consuming the gradle cache) fails with the error:
```
No model of type 'DummyModel' is available in this build.
> No builders are available to build a model of type 'org.jetbrains.plugins.gradle.model.internal.DummyModel'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

This can be reproduced by creating a new project with `gradle init` (gradle 6.7):
```
√ ps/gradle-xxx % gradle init
Starting a Gradle Daemon (subsequent builds will be faster)

Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 2

Select implementation language:
  1: C++
  2: Groovy
  3: Java
  4: Kotlin
  5: Scala
  6: Swift
Enter selection (default: Java) [1..6] 3

Split functionality across multiple subprojects?:
  1: no - only one application project
  2: yes - application and library projects
Enter selection (default: no - only one application project) [1..2] 1

Select build script DSL:
  1: Groovy
  2: Kotlin
Enter selection (default: Groovy) [1..2] 2

Select test framework:
  1: JUnit 4
  2: TestNG
  3: Spock
  4: JUnit Jupiter
Enter selection (default: JUnit 4) [1..4] 1

Project name (default: gradle-xxx): 
Source package (default: gradle.xxx): 

> Task :init
Get more help with your project: https://docs.gradle.org/6.7/samples/sample_building_java_applications.html

BUILD SUCCESSFUL in 33s
2 actionable tasks: 2 executed

```

And just adding a `gradle.properties` file with the content:
```
org.gradle.unsafe.configuration-cache=true
org.gradle.unsafe.configuration-cache-problems=warn
org.gradle.unsafe.configuration-cache.max-problems=5000
```

Opening and resyncing the project using Intellij `2020.2.3` and kotlin plugin `1.4.10-release-IJ2020.2-1` reproduces the issue.

reproducer: [gradle-15044.zip](https://github.com/gradle/gradle/files/5465759/gradle-15044.zip)

Error in Intellij:
Screen Shot 2020-10-30 at 10 40 59

### PR DESCRIPTION
**Pull request by eskatos**
Fixes #15044

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

File: subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java [hunk 1]
```diff
@@ -153,15 +154,22 @@ BuildTreeBuildActionExecutor createActionExecuter(List<BuildActionRunner> buildA
...
+                buildOperationNotificationValve,
+                buildCancellationToken,
                 new RunAsBuildOperationBuildActionRunner(
                     new BuildCompletionNotifyingBuildActionRunner(
                         new FileSystemWatchingBuildActionRunner(
                             new ValidatingBuildActionRunner(
                                 new BuildOutcomeReportingBuildActionRunner(styledTextOutputFactory,
-                                    new ChainingBuildActionRunner(buildActionRunners)))))));
+                                    new ChainingBuildActionRunner(buildActionRunners)))))),
+                configurationCacheSupport
```
Comment (bamboo) [inline subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java:171]: 💄 I'd move the `configurationCacheSupport` parameter to be after `buildCancellationToken`  for symmetry.

**Review by bamboo — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test this

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheToolingApiInvocationIntegrationTest.groovy [hunk 2]
```diff
@@ -99,6 +102,74 @@ class ConfigurationCacheToolingApiInvocationIntegrationTest extends AbstractConf
...
+            2.times {
+                def output = new ByteArrayOutputStream()
+                def model = connection.action(new SomeToolingBuildAction())
+                    .addJvmArguments(executer.jvmArgs)
+                    .forTasks("assemble")
+                    .setStandardOutput(output)
+                    .setStandardError(System.err)
+                    .run()
+                assert model == "It works!"
+                assert !output.toString().contains("Configuration cache is an incubating feature.")
```
Comment (adammurdoch) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheToolingApiInvocationIntegrationTest.groovy:145]: If we ever change this string, this test may silently stop checking anything. It might be better to, for example, add some logging to the build script and assert that this logging is present in both executions (that is, the build script is run in both cases).

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheToolingApiInvocationIntegrationTest.groovy [hunk 3]
```diff
@@ -99,6 +102,74 @@ class ConfigurationCacheToolingApiInvocationIntegrationTest extends AbstractConf
         outputContains("Reusing configuration cache.")
     }
 
+    def "configuration cache is disabled for model building actions"() {
```
Comment (adammurdoch) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheToolingApiInvocationIntegrationTest.groovy:105]: We should probably test each of the cases where the cache should be disabled: requesting a model from the client, running a build action, and running a phased build action.

**Comment by eskatos** [comment]
Thanks for the review @adammurdoch, follow ups in https://github.com/gradle/gradle/pull/15446
