### PR TITLE
Use distict artifact set identifier for composite builds

### LINKED ISSUE #32045: 8.12: Included build not found in build
### Current Behavior

My current build fails with:

```
Could not determine the dependencies of task ':apollo-kotlin:rootPackageJson'.
> Included build 'apollo-kotlin' not found in build 'apollo-kotlin'. 
```

### Expected Behavior

I expect it to work as in 8.11. Or find a better solution if something changed in 8.12

### Context (optional)

Apologies I haven't found a more minimal reproducer. 

See https://github.com/apollographql/apollo-kotlin/pull/6354 for how I ended up making it work.

### Self-contained Reproducer Project

To reproduce:

```
git clone https://github.com/apollographql/apollo-kotlin
cd apollo-kotlin
git checkout c256f76d0e21db11c5af1baf8a5564d7249697b3
sed -i old 's/11/12/g' gradle/wrapper/gradle-wrapper.properties
./gradlew -p tests build
```

Output:

```
> Configure project :apollo-kotlin:apollo-gradle-plugin
Signing plugin detected. Will automatically sign the published artifacts.

[Incubating] Problems report is available at: file:///Users/martinbonnin/git/apollo-kotlin/tests/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':apollo-kotlin:rootPackageJson'.
> Included build 'apollo-kotlin' not found in build 'apollo-kotlin'. 
```

### Gradle version

8.12

### Gradle version that used to work

8.11.1

### PR DESCRIPTION
**Pull request by jvandort**
In a prior PR, #31260, we modified the caching of variant artifact sets to cache in more scenarios. This improved caching exposed a bug elsewhere that caused artifacts from an included build to be reported as coming from the current build, or sometimes the reverse where an artifact from the current build was reported as coming from an included build.

The root problem is that we continued to use the same artifact set identifier, which is used as a cache key, when the artifacts of that artifact set were different. This caused us to use cache values that did not correspond to what we were actually caching. In effect, one key (identifier) mapped to multiple values. This commit ensures the key properly describes the artifacts it identifies.

Fixes #32045 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java [hunk 1]
```diff
@@ -74,22 +75,21 @@ public DefaultLocalVariantGraphResolveState(
...
                     oldArtifactSet.getArtifacts().stream()
-                        .map(artifactTransformer::transform)
+                        .map(originalArtifact -> new CompositeProjectComponentArtifactMetadata(overrideComponentId, originalArtifact))
                         .collect(ImmutableList.toImmutableList())
                 );
 
             copiedArtifactSets.add(new LocalVariantMetadata(
                 oldArtifactSet.getName(),
-                oldArtifactSet.getIdentifier(),
+                OverrideComponentIdArtifactSetIdentifier.of(overrideComponentId, oldArtifactSet.getIdentifier()),
```
Comment (jvandort) [inline platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java:92]: This was the actual bug this PR solves. 
Previously, we use the same identifier for the artifact set, when in reality the artifacts that identifier identified have changed. We need to use a different artifact identifier for this new set.

Comment (jvandort) [reply platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java:92]: This identifier is used as a key to a cache here https://github.com/gradle/gradle/blob/b6e0160a79046236466eb4c8f3f5ae836d3902a8/platforms/software/dependency-management/src/main/java/org/gradle/internal/resolve/resolver/DefaultVariantArtifactResolver.java#L82

**Comment by jvandort** [comment]
@bot-gradle test RFR

**Comment by jvandort** [comment]
@bot-gradle test this

File: platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java [hunk 2]
```diff
@@ -219,4 +219,61 @@ public Set<LocalVariantMetadata> getArtifactVariants() {
...
+        }
+
+        @Nullable
+        public static OverrideComponentIdArtifactSetIdentifier of(
+            ComponentIdentifier overrideComponentId,
+            @Nullable VariantResolveMetadata.Identifier delegate
+        ) {
+            if (delegate == null) {
+                return null;
+            }
```
Comment (tresat) [inline platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java:253]: 🤔 Instead of having null input return null results here, it might be better to just null check prior to calling `of`.

File: platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/LocalVariantMetadata.java [hunk 3]
```diff
@@ -24,14 +24,16 @@
...
+
 /**
  * Implementation of {@link VariantResolveMetadata} which allows variant artifacts to be calculated lazily
  * while holding a project lock.
  */
 public final class LocalVariantMetadata extends DefaultVariantMetadata {
     private final CalculatedValue<ImmutableList<LocalComponentArtifactMetadata>> artifacts;
 
-    public LocalVariantMetadata(String name, Identifier identifier, DisplayName displayName, ImmutableAttributes attributes, ImmutableCapabilities capabilities, CalculatedValue<ImmutableList<LocalComponentArtifactMetadata>> artifacts) {
+    public LocalVariantMetadata(String name, @Nullable Identifier identifier, DisplayName displayName, ImmutableAttributes attributes, ImmutableCapabilities capabilities, CalculatedValue<ImmutableList<LocalComponentArtifactMetadata>> artifacts) {
```
Comment (tresat) [inline platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/LocalVariantMetadata.java:36]: ❗ Since the nullable ID is passed to the superclass, that should be updated for nullability, too.  That field is exposed on a getter, so there might be further consequences of this change.

File: platforms/software/dependency-management/src/main/java/org/gradle/composite/internal/CompositeProjectComponentArtifactMetadata.java [hunk 4]
```diff
@@ -17,22 +17,34 @@
...
 import org.gradle.internal.component.local.model.LocalComponentArtifactMetadata;
 import org.gradle.internal.component.model.IvyArtifactName;
 
 import java.io.File;
 
+/**
+ * Represents an artifact that has its owning component ID overridden.
+ * <p>
+ * This is used when an artifact is referenced from another build, and its owning component id is overridden to its foreign counterpart.
+ * This will go away in Gradle 9.0, when we no longer need to override the owning component id with a foreign identifier.
```
Comment (tresat) [inline platforms/software/dependency-management/src/main/java/org/gradle/composite/internal/CompositeProjectComponentArtifactMetadata.java:31]: 🤔 Even though it's internal API, if it is currently used by Kotlin, and will be going away, would it make sense to mark this as `@Deprecated`?

**Review by tresat — CHANGES_REQUESTED** [review]

File: platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java (hunk 2 above)
Comment (jvandort) [reply platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java:253]: The whole point of `of` is to deal with the nullable ID

File: platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/LocalVariantMetadata.java (hunk 3 above)
Comment (jvandort) [reply platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/LocalVariantMetadata.java:36]: `DefaultVariantMetadata`, the superclass, already has a `@Nullable` annotation on this constructor parameter and the interface already has a `@Nullable` annotation on the getter.

File: platforms/software/dependency-management/src/main/java/org/gradle/composite/internal/CompositeProjectComponentArtifactMetadata.java (hunk 4 above)
Comment (jvandort) [reply platforms/software/dependency-management/src/main/java/org/gradle/composite/internal/CompositeProjectComponentArtifactMetadata.java:31]: Good idea, added a deprecated annotation

**Comment by jvandort** [comment]
@bot-gradle test this

File: platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java (hunk 2 above)
Comment (tresat) [reply platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java:253]: I agree, but see that as a good thing?

File: platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/LocalVariantMetadata.java (hunk 3 above)
Comment (tresat) [reply platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/LocalVariantMetadata.java:36]: My mistake here, I must have opened the wrong class when I looked for this.

**Review by tresat — APPROVED** [review]

File: platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java (hunk 2 above)
Comment (jvandort) [reply platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java:253]: Why have a method that just calls new and passes its two parameters verbatim to a constructor? Seems a bit worthless to me

Comment (jvandort) [reply platforms/software/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalVariantGraphResolveState.java:253]: Yeah this could probably use a better name.

It's just more concise in the calling method where you either need a ternary, which I didn't like initially, or a to assign the new id to a variable in an if, which was more wordy than I wanted

In any case this is just a style thing and is fine the way it is imo
