### PR TITLE
Store transform outputs in a version-bound directory

### LINKED ISSUE #28178: Unused `caches/transforms-3` directory is not removed by Gradle User Home cache cleanup
### Current Behavior

When a user upgrades their build to run with Gradle 8.6, the `~/.gradle/caches/transforms-4` directory is used, and the old `transforms-3` directory is not.
When cleanup runs, old unused versions of Gradle are removed from GUH, including the `caches/<gradle-version>` directory together with other directories that are no longer required (like old `caches/jars-x` and `caches/modules-2/metadata-x` directories.

However, the `transforms-*` directories are not cleaned in this way, and older versions will never be removed by cache cleanup.

### Expected Behavior

When a user runs only with Gradle 8.6, the Gradle User Home cleanup should remove the no-longer-used `caches/transforms-3` directory.

### Context (optional)

_No response_

### Steps to Reproduce

- Run a build with Gradle 8.5. Note that Gradle User Home has a `caches/transforms-3` directory.
- Run the same build with Gradle 8.6. Now there is a `caches/transforms-4` directory as well.
- Wait 7 days, or artificially age the files in Gradle User Home.
- Run the same build with Gradle 8.6. Stop the daemon so that Gradle User Home cleanup runs.
- Note that the `caches/8.5` directory has been removed, but not the `caches/transforms-3` directory.

### Gradle version

8.6

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by bigdaz**
Fixes #28178 

### Context

Each transform output is implicitly tied to the Gradle version used to generate it. As such, it makes no sense to store these entries in a cross-version cache (like `caches/transforms-4`). Instead, these transform outputs are now stored in a version-bound cache directory: `caches/<gradle-version>/transforms`.

This change makes the transform cache directory easier to manage:
- It will only contain entries that are relevant to the Gradle version being used
- It will automatically be purged when the bound Gradle version is no longer used

As well as moving the transform outputs into a version-bound directory, this PR also ensures that old `caches/transforms-X` directories will be purged when they are no longer used by an active Gradle version.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this APT

File: platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/ArtifactCacheUnusedEntryCleanupIntegrationTest.groovy [hunk 1]
```diff
@@ -33,13 +33,13 @@ import static java.util.concurrent.TimeUnit.DAYS
...
 
-class DefaultArtifactCacheLockingAccessCoordinatorIntegrationTest extends AbstractHttpDependencyResolutionTest implements FileAccessTimeJournalFixture, GradleUserHomeCleanupFixture {
+class ArtifactCacheUnusedEntryCleanupIntegrationTest extends AbstractHttpDependencyResolutionTest implements FileAccessTimeJournalFixture, GradleUserHomeCleanupFixture {
     public static final int HALF_DEFAULT_MAX_AGE_IN_DAYS = Math.max(1, DEFAULT_MAX_AGE_IN_DAYS_FOR_DOWNLOADED_CACHE_ENTRIES / 2 as int)
 
     def snapshotModule = mavenHttpRepo.module('org.example', 'example', '1.0-SNAPSHOT').publish().allowAll()
 
     def setup() {
-        requireOwnGradleUserHomeDir()
+        requireOwnGradleUserHomeDir("test requires its own journal")
```
Comment (asodja) [inline platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/ArtifactCacheUnusedEntryCleanupIntegrationTest.groovy:42]: 🎉 Thanks for adding a reason!

File: platforms/core-execution/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersionMapping.java [hunk 2]
```diff
@@ -65,6 +65,10 @@ public Builder incrementedIn(String minGradleVersion) {
             return changedTo(versions.get(versions.lastKey()) + 1, minGradleVersion);
         }
 
+        public Builder retiredIn(String gradleVersion) {
+            return changedTo(Integer.MAX_VALUE, gradleVersion);
```
Comment (asodja) [inline platforms/core-execution/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersionMapping.java:69]: ❓ Is this retiredIn required?

Asking this since then this `Integer.MAX_VALUE` is added to versionMapping and I am not sure what are consequences of that. So I wonder if it's better to not add this version there.

**Review by asodja — CHANGES_REQUESTED** [review]
Overall looks good, just added small comments.

And as mentioned on the Slack we should also fix clean artifact transfom tests, (e.g. [RealLifeAndroidBuildPerformanceTest.groovy#L91](https://github.com/gradle/gradle/blob/1b737ada66ba7f9c2846a1118650a82123e334b0/subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy#L91)), since transforms cache folder is not cleaned after these changes.
We can just implement a custom mutator for now in the gradle/gradle and later fix it also in the gradle-profiler.

File: platforms/core-execution/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersionMapping.java (hunk 2 above)
Comment (bigdaz) [reply platforms/core-execution/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersionMapping.java:69]: The `CacheVersionMapping` is used to determine if a particular cache directory is used by a version of Gradle. The `UnusedVersionsCacheCleanup` looks at the currently used Gradle versions and removes any cache directories that are not used by any of them.

I added the `retiredIn` method to make it clear that there is no valid `transforms-X` directory for that gradle version (and newer). Setting the version to `Integer.MAX_VALUE` was a simple implementation.
I guess it would be better to implement `retiredIn` such that [these methods](https://github.com/gradle/gradle/blob/497dffa06e9a0769c5e0e2ba866d0fbd88f7a1d5/platforms/core-execution/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersionMapping.java#L44-L51) return `null` instead of `Integer.MAX_VALUE`. But the overall impact will be the same.

Comment (bigdaz) [reply platforms/core-execution/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersionMapping.java:74]: I tried a few other implementations, but they all added complexity without really adding any value. If `CacheVersionMapping` returns `null` for a "retired" cache layout, then all of the calling code needs to deal with null.
I've left this as-is: eventually we may be able to remove the `TRANSFORMS` mapping altogether. But for now it is required so that new Gradle versions are able to clean up the `transforms-X` directories left behind by older versions.

**Comment by bigdaz** [comment]
@asodja This is ready for another review:
- `RealLifeAndroidBuildPerformanceTest` now uses a composite mutator that will clear relevant entries in `caches/transforms-X` as well as `caches/<version>/transforms`.
- I ended up not changing the implementation of `CacheVersionMapping.Builder.retiredIn`: the code works fine, but instead of returning `null` for `CacheVersionMapping.getLatestVersion()` and `CacheVersionMapping.getVersionUsedBy()`, we return `MAX_VALUE`. The benefit to this is that all existing logic dealing with these versions continues to work, and doesn't need to check for null values.

PTAL

File: subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/mutator/ClearArtifactTransformCacheWithoutInstrumentedJarsMutator.groovy [hunk 3]
```diff
@@ -82,4 +109,20 @@ class ClearArtifactTransformCacheWithoutInstrumentedJarsMutator extends ClearArt
...
     }
+
+    static BuildMutator create(File gradleUserHome, CleanupSchedule schedule) {
+        def clearOldTransformsDir = new ClearArtifactTransformCacheWithoutInstrumentedJarsMutator(
+            new File(gradleUserHome, "caches"),
+            schedule,
+            "transforms-")
+
+        def clearNewTransformsDir = new ClearArtifactTransformCacheWithoutInstrumentedJarsMutator(
+            new File(gradleUserHome, "caches/" + GradleVersion.current().version),
```
Comment (asodja) [inline subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/mutator/ClearArtifactTransformCacheWithoutInstrumentedJarsMutator.groovy:120]: 🤔 Oh I see this is more complicate now. Sorry for troubles with that.
I think if we do `GradleVersion.current().version` we will get a version from Gradle that invokes the test. So I think we will need to get versions from  `invocationSettings.getVersions()`

File: platforms/core-execution/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersionMapping.java (hunk 2 above)
Comment (asodja) [reply platforms/core-execution/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersionMapping.java:74]: Ok, sounds good to me, thanks for checking other options

**Review by asodja — COMMENTED** [review]
LGTM, I just have a concern about that cache cleanup. I think it won't work correctly, see my comment:
https://github.com/gradle/gradle/pull/28535/files#r1540161987

If you won't be able to verify that today I can also do it during a week and make sure we merge that before branching.

File: subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/mutator/ClearArtifactTransformCacheWithoutInstrumentedJarsMutator.groovy (hunk 3 above)
Comment (asodja) [reply subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/mutator/ClearArtifactTransformCacheWithoutInstrumentedJarsMutator.groovy:120]: If you won't be able to verify that today I can also do it during a week and make sure we merge that before branching.

Comment (bigdaz) [reply subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/mutator/ClearArtifactTransformCacheWithoutInstrumentedJarsMutator.groovy]: I pushed 4f1daf710733b3f099b8fea74899b0723669b7c2 which should do the trick.

**Comment by asodja** [comment]
@bot-gradle test this APT

**Comment by bigdaz** [comment]
@bot-gradle test this APT

**Review by asodja — APPROVED** [review]
LGTM
