### PR TITLE
Fail on duplicates when creating archives by default

### LINKED ISSUE #10039: Fail on duplicates when creating archives by default
In order to avoid JARs and TARs being flagged as "grossly invalid archives" (#9990), the default duplicate strategy should be fail.

De-incubate API:

- [x] `DuplicatesStrategy.INHERIT`

---
cc: @gradle/build-cache

### PR DESCRIPTION
**Pull request by paplorinc**
Fixes #10039

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java [hunk 1]
```diff
@@ -71,7 +71,7 @@
     private Integer fileMode;
     private Boolean caseSensitive;
     private Boolean includeEmptyDirs;
-    private DuplicatesStrategy duplicatesStrategy = DuplicatesStrategy.INHERIT;
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java]: This needs to stay inherit.

File: subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java [hunk 2]
```diff
@@ -40,23 +40,23 @@
...
     WARN,
 
     /**
+     * The default strategy since 6.0
      * Throw a {@link DuplicateFileCopyingException} when subsequent items are to be created at the same path.
-     * <p> 
+     * <p>
      * Use this strategy when duplicates are an error condition that should cause the build to fail.
      */
     FAIL,
```
Comment (wolfs) [inline subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java]: Maybe this should only be the default strategy for archives. I don't see why the duplicate strategy would be a problem for copying/synching.

Comment (paplorinc) [reply subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java]: Is it even possible to have duplicates for non-archives?

Comment (wolfs) [reply subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java]: Not on the disc, though we detect the duplicates nontheless. This is why the sync action fails in the native test: https://github.com/gradle/gradle/blob/1883a66c73d52315e3eb10f54a0451ebe3c92e17/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/tasks/InstallExecutable.java#L263-L267

Comment (wolfs) [reply subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java]: How about we change the default only on `AbstractArchiveTask`?

**Comment by paplorinc** [comment]
Rebased, since the underlying fix has changes (i.e. need a full review)

File: subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java (hunk 2 above)
Comment (paplorinc) [reply subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java]: Yeah, that's what I attempted based on your comment that the default for copy shouldn't change.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java (hunk 1 above)
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java]: Done

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java [hunk 3]
```diff
@@ -71,7 +71,14 @@
...
+
+    private static final DuplicatesStrategy DUPLICATION_STRATEGY_DEFAULT = DuplicatesStrategy.INHERIT;
+    private DuplicatesStrategy duplicatesStrategy = getDefaultDuplicatesStrategy();
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java]: Can't we say in the constructor of `AbstractArchiveTask`:
```
getRootSpec().setDuplicatesStrategy(DuplicatesStrategy.FAIL);
```

And that would be everything?

File: subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ArchivesContinuousIntegrationTest.groovy [hunk 4]
```diff
@@ -77,6 +77,7 @@ class ArchivesContinuousIntegrationTest extends Java7RequiringContinuousIntegrat
 
         buildFile << """
             task unpack(type: Sync) {
+                duplicatesStrategy = DuplicatesStrategy.INCLUDE
```
Comment (wolfs) [inline subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ArchivesContinuousIntegrationTest.groovy]: The `Sync` task shouldn't need any different duplicate strategy, right?

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy [hunk 5]
```diff
@@ -2324,6 +2324,8 @@ Found the following transforms:
             ${declareTransform(transformImplementation)}
 
             task resolve(type: Copy) {
+                duplicatesStrategy = DuplicatesStrategy.EXCLUDE
```
Comment (wolfs) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy]: The `Copy` task should not be affected by the change.

File: subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java [hunk 6]
```diff
@@ -40,22 +40,23 @@
...
 
     /**
-     * The default strategy, which is to inherit the strategy from the parent copy spec, if any,
+     * The default strategy for Copy/Sync, which is to inherit the strategy from the parent copy spec, if any,
```
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java]:
```suggestion
     * The default strategy, which is to inherit the strategy from the parent copy spec, if any,
```

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java (hunk 3 above)
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java]: I can but this will create one strategy originally (inherit) and later override it (fail) - i.e. the intermediary state will be invalid.
Is that okay?

File: subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ArchivesContinuousIntegrationTest.groovy (hunk 4 above)
Comment (paplorinc) [reply subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ArchivesContinuousIntegrationTest.groovy]: It's implicit again, yes.
Reverted.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy (hunk 5 above)
Comment (paplorinc) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy]: Done

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java (hunk 3 above)
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java]: Done

File: subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ArchivesContinuousIntegrationTest.groovy [hunk 7]
```diff
@@ -75,18 +75,18 @@ class ArchivesContinuousIntegrationTest extends Java7RequiringContinuousIntegrat
...
                 from($type("${sourceFile.toURI()}"))
                 into("unpack")
-"""
-        if (readonly) {
-            buildFile << """
-                fileMode 0644
-                dirMode 0755
-            """
-        }
-        buildFile << """
```
Comment (paplorinc) [inline subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ArchivesContinuousIntegrationTest.groovy]: this looked ugly, extracted it to a variable

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java [hunk 8]
```diff
@@ -585,7 +588,7 @@ public FileTree getAllSource() {
 
         @Override
         public DuplicatesStrategy getDuplicatesStrategy() {
-            if (duplicatesStrategy != DuplicatesStrategy.INHERIT) {
+            if (duplicatesStrategy != DEFAULT_DUPLICATION_STRATEGY) {
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java]: extracted to reflect the intent: if it's the default, we should ignore it here (might as well be `null` instead, but didn't want to change it, don't know about the implications)

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy [hunk 9]
```diff
@@ -688,8 +687,7 @@ class ArchiveIntegrationTest extends AbstractIntegrationSpec {
         "test.tar"  | "tarTree" | "createTar"
     }
 
-
-    def ensureDuplicatesIncludedInTarByDefault() {
+    def ensureDuplicatesNotIncludedInTarByDefault() {
```
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy]: By default? You mean if we set it explicitly to `INCLUDE`, right?
I didn't look at complete coverage, but you're right, we should have that as well.
Done

File: subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java]: Done

**Comment by paplorinc** [comment]
Added it to the upgrade notes and working_with_files#Creating archives.

File: subprojects/docs/src/docs/userguide/upgrading_version_5.adoc [hunk 10]
```diff
@@ -40,7 +40,7 @@ Some plugins will break with this new version of Gradle, for example because the
 
 ==== Local build cache type shouldn't be specified
 
-When configuring the local build cache the use of `BuildCacheConfiguration.local(Class)` and `local(Class, Action)` has now been deprecated; use `getLocal()` or `local(Action)` instead.
+When configuring the local build cache the use of `BuildCacheConfiguration.local(Class)` and `local(Class, Action)` have now been deprecated; use `getLocal()` or `local(Action)` instead.
```
Comment (paplorinc) [inline subprojects/docs/src/docs/userguide/upgrading_version_5.adoc]: @lptr, is this correct?

File: subprojects/docs/src/docs/userguide/upgrading_version_5.adoc [hunk 11]
```diff
@@ -1,4 +1,4 @@
-// Copyright 2018 the original author or authors.
+// Copyright 2019 the original author or authors.
```
Comment (paplorinc) [inline subprojects/docs/src/docs/userguide/upgrading_version_5.adoc]: I think this should be 2019

File: subprojects/docs/src/docs/userguide/working_with_files.adoc [hunk 12]
```diff
@@ -150,6 +150,8 @@ Notice how we specify the destination and name of the archive instead of an `int
 
 Each type of archive has its own task type, the most common ones being link:{groovyDslPath}/org.gradle.api.tasks.bundling.Zip.html[Zip], link:{groovyDslPath}/org.gradle.api.tasks.bundling.Tar.html[Tar] and link:{groovyDslPath}/org.gradle.api.tasks.bundling.Jar.html[Jar]. They all share most of the configuration options of `Copy`, including filtering and renaming.
 
+One notable difference between the `Copy` and `Sync` tasks and the archives is that starting with Gradle 6.0 duplicate files will not be allowed in archives anymore.
```
Comment (paplorinc) [inline subprojects/docs/src/docs/userguide/working_with_files.adoc]: added it here since we're talking about similarities with Copy before

File: subprojects/docs/src/docs/userguide/upgrading_version_5.adoc [hunk 13]
```diff
@@ -380,6 +380,24 @@ Internally, `AbstractArchiveTask` prefers the new properties and methods like `g
 
 If your plugin/build only uses these types (and does not extend them), nothing has changed.
 
+==== Archives fail on duplicates
+
+Until now archives defaulted to the `INHERIT` duplicates strategy, allowing the same path to exist multiple times in an archive.
```
Comment (wolfs) [inline subprojects/docs/src/docs/userguide/upgrading_version_5.adoc]: I think we need to be more specific what `archives` means here. I think we should reference `archive tasks`, and maybe point to `Zip` and `Tar` specifically.

File: subprojects/docs/src/docs/userguide/working_with_files.adoc (hunk 12 above)
Comment (wolfs) [inline subprojects/docs/src/docs/userguide/working_with_files.adoc]: We don't need to say `Gradle 6.0` here. Just state the difference, the docs are published for a version.

File: subprojects/docs/src/docs/userguide/upgrading_version_5.adoc (hunk 13 above)
Comment (paplorinc) [reply subprojects/docs/src/docs/userguide/upgrading_version_5.adoc]: The previous header already defines it:
> ==== Change in behavior for tasks extending `AbstractArchiveTask` or subtypes (`Zip`, `Jar`, `War`, `Ear`, `Tar`)

File: subprojects/docs/src/docs/userguide/working_with_files.adoc (hunk 12 above)
Comment (paplorinc) [reply subprojects/docs/src/docs/userguide/working_with_files.adoc]: It was like that in other sections, should I delete it from there as well?

File: subprojects/docs/src/docs/userguide/working_with_files.adoc [hunk 14]
```diff
@@ -150,6 +150,8 @@ Notice how we specify the destination and name of the archive instead of an `int
 
 Each type of archive has its own task type, the most common ones being link:{groovyDslPath}/org.gradle.api.tasks.bundling.Zip.html[Zip], link:{groovyDslPath}/org.gradle.api.tasks.bundling.Tar.html[Tar] and link:{groovyDslPath}/org.gradle.api.tasks.bundling.Jar.html[Jar]. They all share most of the configuration options of `Copy`, including filtering and renaming.
 
+One notable difference between the `Copy` and `Sync` tasks and the archives is that duplicate files will not be allowed in archives anymore.
```
Comment (wolfs) [inline subprojects/docs/src/docs/userguide/working_with_files.adoc]:
```suggestion
One notable difference between the `Copy` and `Sync` tasks and the archive tasks is that duplicate files are not allowed in the latter by default.
```

I wonder if we should add a link to the DSL doc how the duplicate handling can be changed.

File: subprojects/docs/src/docs/userguide/upgrading_version_5.adoc [hunk 15]
```diff
@@ -380,6 +380,24 @@ Internally, `AbstractArchiveTask` prefers the new properties and methods like `g
...
+
+```
+task archive(type: Zip) {
+    duplicatesStrategy = DuplicatesStrategy.INCLUDE // allow duplicates
+    archiveName = 'archive.zip'
+    from 'src'
+}
+```
+
+*Note* that `Copy` and `Sync` tasks are unaffected: they still use the `INHERIT` duplicates strategy as default.
```
Comment (wolfs) [inline subprojects/docs/src/docs/userguide/upgrading_version_5.adoc]:
```suggestion
*Note* that `Copy` and `Sync` tasks are unaffected: they still use the `INCLUDE` duplicates strategy as default.
```

File: subprojects/docs/src/docs/userguide/upgrading_version_5.adoc (hunk 13 above)
Comment (wolfs) [reply subprojects/docs/src/docs/userguide/upgrading_version_5.adoc]:
```suggestion
Until now archive tasks defaulted to the `INCLUDE` duplicates strategy, allowing the same path to exist multiple times in an archive.
```

I don't think people read the previous header. Let's repeat the affected tasks again here. Or have one section (changes for archive tasks) with two sub-sections.

File: subprojects/docs/src/docs/userguide/upgrading_version_5.adoc [hunk 16]
```diff
@@ -380,6 +380,24 @@ Internally, `AbstractArchiveTask` prefers the new properties and methods like `g
 
 If your plugin/build only uses these types (and does not extend them), nothing has changed.
 
+==== Archives fail on duplicates
```
Comment (wolfs) [inline subprojects/docs/src/docs/userguide/upgrading_version_5.adoc]:
```suggestion
==== Archive tasks fail on duplicate files
```

File: subprojects/docs/src/docs/userguide/upgrading_version_5.adoc (hunk 15 above)
Comment (paplorinc) [reply subprojects/docs/src/docs/userguide/upgrading_version_5.adoc]: Meaning that inherit will delegate to include?
I.e. https://github.com/gradle/gradle/blob/623062702ba0bd809a0393cd53bed37f3ff9e58e/subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java#L75

File: subprojects/docs/src/docs/userguide/upgrading_version_5.adoc (hunk 10 above)
Comment (paplorinc) [reply subprojects/docs/src/docs/userguide/upgrading_version_5.adoc]: Reverted for now

File: subprojects/docs/src/docs/userguide/upgrading_version_5.adoc (hunk 13 above)
Comment (paplorinc) [reply subprojects/docs/src/docs/userguide/upgrading_version_5.adoc]: Done

File: subprojects/docs/src/docs/userguide/working_with_files.adoc (hunk 14 above)
Comment (paplorinc) [reply subprojects/docs/src/docs/userguide/working_with_files.adoc]: That's already available in the upgrade notes, that should suffice for now, I think.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java [hunk 17]
```diff
@@ -71,7 +71,10 @@
     private Integer fileMode;
     private Boolean caseSensitive;
     private Boolean includeEmptyDirs;
-    private DuplicatesStrategy duplicatesStrategy = DuplicatesStrategy.INHERIT;
+
+    private static final DuplicatesStrategy DEFAULT_DUPLICATION_STRATEGY = DuplicatesStrategy.INHERIT;
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java]: `INHERIT` will delegate to the parent spec. If there is no parent spec, or the parent spec did not set something explicitly, then the default is returned - `INCUDE`. So the variable name is actually misleading: The default duplicate strategy is `INCLUDE`, not `INHERIT`. `INHERIT` serves as a null-object to make it easier to use the DSL from Kotlin.

So I would suggest you inline the constant or use something like this:
```
private static final DuplicatesStrategy DEFAULT_DUPLICATES_STRATEGY = DuplicatesStrategy.INCLUDE;

...

        public DuplicatesStrategy getDuplicatesStrategy() {
            if (duplicatesStrategy != DuplicatesStrategy.INHERIT) {
                return duplicatesStrategy;
            }
            if (parentResolver != null) {
                return parentResolver.getDuplicatesStrategy();
            }
            return DEFAULT_DUPLICATES_STRATEGY;
        }
```

File: subprojects/docs/src/docs/userguide/working_with_files.adoc (hunk 14 above)
Comment (wolfs) [reply subprojects/docs/src/docs/userguide/working_with_files.adoc]: The upgrade notes (as the release notes) are not something persistent. The user manual is. So if I am using Gradle 15.5, and I want to know how to include duplicate files in my JAR, where should I look? Linking to the DSL doc for `AbstractArchiveTask.duplicatesStrategy` should be enough.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java (hunk 17 above)
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java]: Inlined, thanks for explaining (it's why I wanted to use `null` previously as a default, to signal that it wasn't set yet)

File: subprojects/docs/src/docs/userguide/working_with_files.adoc [hunk 18]
```diff
@@ -150,6 +150,8 @@ Notice how we specify the destination and name of the archive instead of an `int
 
 Each type of archive has its own task type, the most common ones being link:{groovyDslPath}/org.gradle.api.tasks.bundling.Zip.html[Zip], link:{groovyDslPath}/org.gradle.api.tasks.bundling.Tar.html[Tar] and link:{groovyDslPath}/org.gradle.api.tasks.bundling.Jar.html[Jar]. They all share most of the configuration options of `Copy`, including filtering and renaming.
 
+One notable difference between the `Copy` and `Sync` tasks and the archive tasks is that duplicate files are not allowed in the latter by default.
```
Comment (wolfs) [inline subprojects/docs/src/docs/userguide/working_with_files.adoc]: This comment is still unresolved: https://github.com/gradle/gradle/pull/10143#discussion_r310093542

File: subprojects/docs/src/docs/userguide/working_with_files.adoc (hunk 14 above)
Comment (paplorinc) [reply subprojects/docs/src/docs/userguide/working_with_files.adoc]: Done, please review and recommend alternative, if you feel it's needed.
Also https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:duplicatesStrategy

claims
> Default with java plugin:
> null

but upgrading_version_4 claims:
* For better compatibility with the Kotlin DSL, link:{javadocPath}/org/gradle/api/file/DuplicatesStrategy.html[CopySpec.duplicatesStrategy] is no longer nullable. The property setter no longer accepts null as a way
to reset the property back to its default value. Use DuplicatesStrategy.INHERIT instead.

If you think it's wrong, can you either push a fix or point me to the right place to fix it?

Comment (wolfs) [reply subprojects/docs/src/docs/userguide/working_with_files.adoc]: I pushed a fix.
