### PR TITLE
Fix OSC 9;4 progress bar not cleared on SIGINT

### LINKED ISSUE #37022: OSC 9;4 progress bar not cleared on SIGINT
### Current Behavior

Using Gradle 9.4 with Ghostty 1.3, when a long-running operation is interrupted with SIGINT (via ctrl+C) the OSC 9;4 progress reporting to the terminal is not reset to 0 state (hidden). Ghostty will (thankfully) eventually hide the progress after a timeout, but I'm not sure that UX nicety will be present in every terminal emulator.
 
Image

### Expected Behavior

OSC 9;4;0 is sent to hide the progress

### Context (optional)

_No response_

### Self-contained Reproducer Project

Any project, run any task, and ctrl+c while the progress bar is being displayed.

Here's an Asciinema recording of an example:
```
{"version":3,"term":{"cols":90,"rows":28,"type":"xterm-ghostty","version":"ghostty 1.3.0-main+619e33a4f","theme":{"fg":"#ffffff","bg":"#282c34","palette":"#1d1f21:#cc6666:#b5bd68:#f0c674:#81a2be:#b294bb:#8abeb7:#c5c8c6:#666666:#d54e53:#b9ca4a:#e7c547:#7aa6da:#c397d8:#70c0b1:#eaeaea"}},"timestamp":1773152668,"env":{"SHELL":"/opt/homebrew/bin/fish"}}
[0.065, "o", "\u001b[?u\u001b[>0q\u001b]11;?\u001b\\\u001b[?1049h\u001bP+q696e646e\u001b\\\u001bP+q71756572792d6f732d6e616d65\u001b\\\u001b[?1049l\u001b[0c"]
[0.000, "o", "\r"]
[0.003, "o", "\u001b]7;file://JakesSklightMBP.localdomain/Users/jw/dev/sqldelight/sqldelight\u0007"]
[0.014, "o", "\u001b]0;~/d/s/sqldelight\u0007\u001b[m\u001b]11;?\u001b\\\u001b[6n\u001b[0c\u001b[?2004h\u001b[?2031h\u001b[=5u"]
[0.000, "o", "\u001b[K\u001b]133;A;click_events=1\u001b\\\u001b[J\r\n\u001b[K\u001b[1;36m~/d/s/sqldelight\u001b[0m on \u001b[1;35m renovate/kotlin-monorepo\u001b[0m \u001b[1;32m(3f53c2d)\u001b[0m \u001b[37m─────────\u001b[0m took \u001b[1;33m0ms\u001b[0m at \u001b[1;33m10:24:28 AM\u001b[0m\r\n\u001b[1;32m❯\u001b[0m \u001b]133;B\u0007\u001b[K\r\u001b[2C"]
[0.454, "o", "g\r\u001b[3C"]
[0.002, "o", "\u001b[90ma\u001b[m\r\u001b[3C\b\u001b[91mg\u001b[90ma\u001b[m\r\u001b[3C"]
[0.036, "o", "\u001b[91ma\u001b[m\r\u001b[4C\r\u001b[4C\u001b[2Dga\r\u001b[4C"]
[0.098, "o", "\u001b[?2004l\u001b[?2031l\u001b[=0u"]
[0.000, "o", "\r\u001b[4C\r\n\u001b[m\u001b]133;C;cmdline_url=ga\u0007"]
[0.002, "o", "\u001b]0;ga ~/d/s/sqldelight\u0007\u001b[m\r"]
[0.306, "o", "\r\n\r\n\u001b[2A\u001b[1m\u001b]9;4;1;0\u0007│\u001b[0;32;1m···············\u001b[0;39;1m│ 0% INITIALIZING [30ms]\u001b[m\u001b[50D\u001b[1B\u001b[1m> Evaluating settings > :buildLogic > Resolve dependencies of classpath\u001b[m\u001b[71D\u001b[1B"]
[0.093, "o", "\u001b[2AType-safe project accessors is an incubating feature.\r\n\u001b[1B\u001b[0K\r\n\u001b[2A\u001b[1m\u001b]9;4;1;0\u0007│\u001b[0;32;1m···············\u001b[0;39;1m│ 0% CONFIGURING [127ms]\u001b[m\u001b[0K\u001b[50D\u001b[1B\u001b[1m> root project\u001b[m\u001b[14D\u001b[1B"]
[0.102, "o", "\u001b[2A\u001b[1m\u001b]9;4;1;12\u0007│\u001b[0;32;1m█▊·············\u001b[0;39;1m│ 12% CONFIGURING [230ms]\u001b[m\u001b[52D\u001b[1B\u001b[1m> :runtime\u001b[m\u001b[0K\u001b[10D\u001b[1B"]
[0.099, "o", "\u001b[2A\u001b[1m\u001b]9;4;1;14\u0007│\u001b[0;32;1m██▏············\u001b[0;39;1m│ 14% CONFIGURING [329ms]\u001b[m\u001b[52D\u001b[1B\u001b[1m> :sqldelight-compiler\u001b[m\u001b[22D\u001b[1B"]
[0.101, "o", "\u001b[2A\u001b[1m\u001b]9;4;1;26\u0007│\u001b[0;32;1m████···········\u001b[0;39;1m│ 26% CONFIGURING [430ms]\u001b[m\u001b[52D\u001b[1B\u001b[1m> :adapters:primitive-adapters\u001b[m\u001b[30D\u001b[1B"]
[0.095, "o", "\u001b[2A\u001b[1m\u001b]9;4;1;26\u0007│\u001b[0;32;1m████···········\u001b[0;39;1m│ 26% CONFIGURING [526ms]\u001b[m\u001b[52D\u001b[2B"]
[0.104, "o", "\u001b[2A\u001b[1m\u001b]9;4;1;46\u0007│\u001b[0;32;1m██████▉········\u001b[0;39;1m│ 46% CONFIGURING [630ms]\u001b[m\u001b[52D\u001b[1B\u001b[1m> :dialects:sqlite-3-30\u001b[m\u001b[0K\u001b[23D\u001b[1B"]
[0.101, "o", "\u001b[2A\u001b[0K\r\n\u001b[1m> Configure project :drivers:android-driver\u001b[m\r\nclass org.jetbrains.dokka.gradle.adapters.AndroidExtensionWrapper could not get Android Extension for project :drivers:android-driver\r\nclass org.jetbrains.dokka.gradle.adapters.AndroidExtensionWrapper could not get Android Extension for project :drivers:android-driver\r\n\u001b[0K\r\n\u001b[0K\r\n\u001b[2A\u001b[1m\u001b]9;4;1;58\u0007│\u001b[0;32;1m████████▊······\u001b[0;39;1m│ 58% CONFIGURING [730ms]\u001b[m\u001b[52D\u001b[1B\u001b[1m> :drivers:driver-test\u001b[m\u001b[22D\u001b[1B"]
[0.095, "o", "\u001b[2A\u001b[1m\u001b]9;4;1;63\u0007│\u001b[0;32;1m█████████▌·····\u001b[0;39;1m│ 63% CONFIGURING [825ms]\u001b[m\u001b[52D\u001b[1B\u001b[1m> :drivers:native-driver\u001b[m\u001b[24D\u001b[1B"]
[0.102, "o", "\u001b[2A\u001b[1m\u001b]9;4;1;68\u0007│\u001b[0;32;1m██████████▏····\u001b[0;39;1m│ 68% CONFIGURING [927ms]\u001b[m\u001b[52D\u001b[1B\u001b[1m> :drivers:sqlite-driver\u001b[m\u001b[24D\u001b[1B"]
[0.102, "o", "\u001b[2A\u001b[1m\u001b]9;4;1;73\u0007│\u001b[0;32;1m██████████▉····\u001b[0;39;1m│ 73% CONFIGURING [1s]\u001b[m\u001b[0K\u001b[49D\u001b[1B\u001b[1m> :extensions:androidx-paging3\u001b[m\u001b[30D\u001b[1B"]
[0.079, "o", "^C"]
[0.000, "o", "\u001b[0m\u001b[?12l\u001b[?25h"]
[0.066, "o", "\u001b]133;D;130\u0007"]
[0.000, "o", "\u001b[?25h"]
[0.000, "o", "\u001b[2m⏎\u001b[m                                                                                         \r⏎ \r"]
[0.000, "o", "\u001b]7;file://JakesSklightMBP.localdomain/Users/jw/dev/sqldelight/sqldelight\u0007"]
[0.014, "o", "\u001b]0;~/d/s/sqldelight\u0007\u001b[m\u001b]11;?\u001b\\\u001b[6n\u001b[0c\u001b[?2004h\u001b[?2031h\u001b[=5u"]
[0.000, "o", "\u001b[K\u001b]133;A;click_events=1\u0007\u001b[J\r\n\u001b[K\u001b[1;36m~/d/s/sqldelight\u001b[0m on \u001b[1;35m renovate/kotlin-monorepo\u001b[0m \u001b[1;32m(3f53c2d)\u001b[0m \u001b[37m─────\u001b[0m took \u001b[1;33m1s445ms\u001b[0m at \u001b[1;33m10:24:30 AM\u001b[0m\r\n\u001b[1;31m❌130\u001b[0m \u001b[1;31m❯\u001b[0m \u001b]133;B\u0007\u001b[K\r\u001b[8C"]
[2.531, "o", "\u001b[?2004l\u001b[?2031l\u001b[=0u\r\n\u001b[m\u001b[m"]
[0.002, "x", "0"]
```
You can see the OSC 9;4;1 updates to the value, but no OSC 9;4;0 once Gradle observes the SIGINT and begins resetting the terminal state.

### Gradle version

9.4

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by reinsch82**
## Summary

Fixes #37022 — the OSC 9;4 taskbar progress indicator (ConEmu, Ghostty, iTerm2, kitty) was not being cleared when a build was interrupted with Ctrl+C.

- Register a JVM shutdown hook in `ConsoleConfigureAction` that writes `ESC]9;4;0` (remove taskbar progress) directly to `stdout` when the terminal supports OSC 9;4. This fires reliably on SIGINT and any other abrupt JVM exit.
- Add `ProgressBar.buildTaskbarProgressResetSequence(ConsoleMetaData)` — a public static method returning the reset sequence, or empty string if unsupported.
- Refactor the existing `buildTaskbarProgressSequence` to use a shared private `buildOsc94Sequence(String)` helper, eliminating duplication of the `ESC]9;4;` format string.

**Why a shutdown hook instead of `EndOutputEvent`:**
`EndOutputEvent` is only fired from `OutputEventRenderer.removeChain()`, which is called from `restore()` — this path is not taken when the client JVM exits via SIGINT. The JVM shutdown hook fires unconditionally on exit regardless of how the JVM is terminated.

## Test plan

- [ ] Run any Gradle build in a supported terminal (Ghostty, iTerm2 ≥ 3.6.6, kitty, ConEmu) and press Ctrl+C while the OSC 9;4 progress bar is visible — progress indicator should be cleared immediately
- [ ] Verify a normal build completion also clears the progress indicator (shutdown hook fires on normal exit too)

### CODE REVIEW

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java [hunk 1]
```diff
@@ -278,10 +278,26 @@ private String buildTaskbarProgressSequence(int progressPercent, boolean isError
...
+            return "";
+        }
+        // State 0 = remove; progress field is omitted as it is not applicable
+        return buildOsc94Sequence("0");
+    }
+
+    // ESC ] 9 ; 4 ; state ; progress BEL
+    // Using BEL (0x07) instead of ST (ESC \) for broader compatibility
+    private static String buildOsc94Sequence(String command) {
+        return "\u001B]9;4;" + command + "\u0007";
```
[the remark this answers is not in the document]
Comment (reinsch82) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java]: @copilot open a new pull request to apply changes based on [this feedback](https://github.com/gradle/gradle/pull/37038#discussion_r2919332841)

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java [hunk 2]
```diff
@@ -278,10 +278,26 @@ private String buildTaskbarProgressSequence(int progressPercent, boolean isError
...
+     * or an empty string if the terminal does not support taskbar progress.
+     * Should be sent when the build ends or is interrupted (e.g. SIGINT).
+     */
+    public static String buildTaskbarProgressResetSequence(ConsoleMetaData consoleMetaData) {
+        if (!consoleMetaData.supportsTaskbarProgress()) {
+            return "";
+        }
+        // State 0 = remove; progress field is omitted as it is not applicable
+        return buildOsc94Sequence("0");
+    }
```
[the remark this answers is not in the document]
Comment (reinsch82) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java:296]: @copilot open a new pull request to apply changes based on [this feedback](https://github.com/gradle/gradle/pull/37038#discussion_r2919332886)

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java [hunk 3]
```diff
@@ -57,6 +58,39 @@ public static void execute(OutputEventRenderer renderer, ConsoleOutput consoleOu
...
+                        }
+                    }, "taskbar-progress-reset"));
+                } catch (SecurityException | IllegalStateException ignored) {
+                    // Unable to register shutdown hook; proceed without it
+                }
+            }
+        }
+    }
+
+    private static boolean shouldRegisterTaskbarReset(ConsoleOutput consoleOutput, ConsoleMetaData consoleMetadata) {
```
Comment (jbartok) [inline platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: This feels like duplication of logic, for example of things like: `consoleMetaData.supportsTaskbarProgress()`. There should be a single place for such logic.

File: platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/ProgressBarTest.groovy [hunk 4]
```diff
@@ -230,6 +230,33 @@ class ProgressBarTest extends Specification {
         id = unicode ? "unicode" : "ascii"
     }
 
+    def "builds taskbar progress reset sequence when supported (#id)"() {
```
Comment (jbartok) [inline platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/ProgressBarTest.groovy:233]: Would be good to have a test actually testing what we are implementing, which is what happens to the console on an actual Ctrl+C press. More like an integration test, assuming it's possible to write one.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java (hunk 3 above)
Comment (reinsch82) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: It's different though. they are checking for different things.
This checks for user choices, the other for technical availability, both have to be true that this makes sense.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java [hunk 5]
```diff
@@ -278,10 +279,27 @@ private String buildTaskbarProgressSequence(int progressPercent, boolean isError
...
+
+    // ESC ] 9 ; 4 ; state [; progress] BEL
+    // Using BEL (0x07) instead of ST (ESC \) for broader compatibility
+    @VisibleForTesting
```
Comment (eskatos) [inline platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java]: ❌ Method is both `private` and annotated with `@VisibleForTesting`. This is contradictory

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java [hunk 6]
```diff
@@ -98,6 +132,10 @@ private static void configureAutoConsole(OutputEventRenderer renderer, ConsoleMe
         }
     }
 
+    private static boolean shouldWriteRichContent(ConsoleMetaData consoleMetaData) {
```
Comment (eskatos) [inline platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: ❌ I think this name is confusing. The test is about stdout being an interactive terminal, not if some rich content should be written. I'd remove this method and inline the check for better readability.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java (hunk 3 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: ❌ Tangling this with the user choice will make this code harder to change in the future. I think it would be better to check for capabilities here, the same as what make the code decide if there is a task bar.

File: testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ForkingGradleHandle.java [hunk 7]
```diff
@@ -172,6 +173,40 @@ public GradleHandle abort() {
         return this;
     }
 
+    @Override
+    public GradleHandle sendSigInt() {
```
Comment (eskatos) [inline testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ForkingGradleHandle.java]: ❌ This implementation with reflection looks like something we don't want to maintain. Isn't there a better way?

**Review by eskatos — CHANGES_REQUESTED** [review]

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java (hunk 5 above)
Comment (reinsch82) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java]: misunderstanding on my end what the annotation means.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java (hunk 6 above)
Comment (reinsch82) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: I understand the sentiment. I went with this, because it links the 2 usages of it.

`isStdOutTerminal` is used to determine whether rich terminal should be used in the `Auto` mode. By using this method it is more visible that the initialization of the rich console and the determination in `Auto` mode are related and need to be changed together.

FTR I inlined one usage, since it doesn't serve the above mention purpose.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java (hunk 3 above)
Comment (reinsch82) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: I think we shouldn’t send the clean up code if no 9;4 commands have been used.
Or do you think this doesn’t matter since it’s a NOP anyway?

**Comment by reinsch82** [comment]
@bot-gradle test this

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java (hunk 3 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: I agree we should not send the reset sequence if no 9;4 commands have been used. But I would detangle that from the high level user choices.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java (hunk 6 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: I still think it is confusing, for the same reasons.
And now that there are only two usages in a single method I see even less use for this method.

File: testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ForkingGradleHandle.java [hunk 8]
```diff
@@ -172,6 +173,35 @@ public GradleHandle abort() {
...
+        try {
+            Process process = getExecHandle().getProcess();
```
Comment (eskatos) [inline testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ForkingGradleHandle.java]: ❌ This is much better. But I'm not sure we want to expose the `Process` object on `ExecHandle`. It is a central piece of a lot of process management infrastructure across the codebase and adding this allows a lot of footguns. Wasn't `ExecHandle.abort()` enough? If not, I'd rather we have support for sending signals on `ExecHandle` instead.

Comment (reinsch82) [reply testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ForkingGradleHandle.java]: `abort` seems too forceful. it doesn't run the shutdown hook

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java (hunk 3 above)
Comment (reinsch82) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: I let myself to be mislead :(.

We only decide this on capability, it is independent of user choice.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java [hunk 9]
```diff
@@ -57,6 +58,27 @@ public static void execute(OutputEventRenderer renderer, ConsoleOutput consoleOu
         } else if (consoleOutput == ConsoleOutput.Colored) {
             configureColoredConsole(renderer, consoleMetadata, stdout, stderr);
         }
+
+            registerTaskbarReset(consoleMetadata, stdout);
```
Comment (eskatos) [inline platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: 💅 Wrong indentation

File: platforms/core-runtime/process-services/src/main/java/org/gradle/process/internal/ExecHandle.java [hunk 10]
```diff
@@ -45,6 +45,13 @@ public interface ExecHandle extends Describable {
 
     ExecHandleState getState();
 
+    /**
+     * Sends the given signal to the process. Unix/macOS only.
```
Comment (eskatos) [inline platforms/core-runtime/process-services/src/main/java/org/gradle/process/internal/ExecHandle.java]: 🎨  It would be good to not let Windows behaviour undefined. It might be enough to simply throw an explaining exception early. Future us writing code using that capability will be thankful.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java (hunk 3 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: 👍

File: testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ForkingGradleHandle.java (hunk 8 above)
Comment (eskatos) [reply testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ForkingGradleHandle.java]: 👍 for adding support to send signals to `ExecHandle`

**Review by eskatos — APPROVED** [review]
This is much better.
Approved with two minor comments.

File: subprojects/core/src/main/java/org/gradle/process/internal/ExecHandleRunner.java [hunk 11]
```diff
@@ -60,6 +60,37 @@ public ExecHandleRunner(
...
+        lock.lock();
+        try {
+            if (process == null) {
+                throw new IllegalStateException("Cannot send signal " + signal + ": the process has not started yet");
+            }
+            try {
+                long pid = getProcessId(process);
+                new ProcessBuilder("kill", "-" + signal, String.valueOf(pid))
+                    .start()
+                    .waitFor();
```
Comment (eskatos) [inline subprojects/core/src/main/java/org/gradle/process/internal/ExecHandleRunner.java]: ❌ Actually, this is not solid. The case of failing `kill` command is not handled, exit code not checked, no information brought up when it happens. I think this should be fixed before merging.

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test RFN
