### PR TITLE
CC store inlcuded build projects used for transform

### LINKED ISSUE #36177: Configuration Cache fails to restore project from included build if it is included on buildscript classpath
### Current Behavior

A configuration in one project depends on a single project from an included build. An artifact transform is applied to the configuration and used as a task input. The project from the included build is _also_ included on the root project's buildscript classpath.

With CC disabled, the transform is successfully executed. With CC enabled, the following failure is thrown:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':toolingApiShadedJar'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Failed to transform kotlin-dsl-shared-runtime.jar (project :kotlin-dsl-shared-runtime) to match attributes {artifactType=foo, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=17, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > project :kotlin-dsl-shared-runtime not found.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights from a Build Scan (powered by Develocity).
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':toolingApiShadedJar'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:210)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:205)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:54)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.DefaultNodeExecutor.executeLocalTaskNode(DefaultNodeExecutor.java:55)
	at org.gradle.execution.plan.DefaultNodeExecutor.execute(DefaultNodeExecutor.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:339)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:84)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:339)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:328)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.api.internal.artifacts.ivyservice.TypedResolveException: Could not resolve all files for configuration ':runtimeClasspath'.
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ArtifactSetToFileCollectionFactory$NameBackedResolutionHost.consolidateFailures(ArtifactSetToFileCollectionFactory.java:194)
	at org.gradle.api.internal.artifacts.configurations.ResolutionHost.rethrowFailuresAndReportProblems(ResolutionHost.java:75)
	at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.maybeThrowResolutionFailures(ResolutionBackedFileCollection.java:86)
	at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.visitContents(ResolutionBackedFileCollection.java:76)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:361)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:112)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:66)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:99)
	at org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection.visitChildren(DefaultFileCollectionFactory.java:311)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:112)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:361)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:112)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:66)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.visitContents(DefaultConfigurableFileCollection.java:635)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitChildren(DefaultConfigurableFileCollection.java:448)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:112)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:361)
	at org.gradle.api.internal.file.FileCollectionBackedFileTree.visitContents(FileCollectionBackedFileTree.java:94)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:361)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:112)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:66)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:91)
	at org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection.visitChildren(DefaultFileCollectionFactory.java:311)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:112)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:361)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:112)
	at org.gradle.api.internal.tasks.PropertyFileCollection.visitChildren(PropertyFileCollection.java:48)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:112)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:361)
	at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:48)
	at org.gradle.internal.execution.impl.DefaultInputFingerprinter$InputCollectingVisitor.visitInputFileProperty(DefaultInputFingerprinter.java:151)
	at org.gradle.internal.execution.steps.SkipEmptyMutableWorkStep$2.visitInputFileProperty(SkipEmptyMutableWorkStep.java:190)
	at org.gradle.api.internal.tasks.execution.TaskExecution.visitMutableInputs(TaskExecution.java:345)
	at org.gradle.internal.execution.steps.SkipEmptyMutableWorkStep.lambda$fingerprintPrimaryInputs$2(SkipEmptyMutableWorkStep.java:186)
	at org.gradle.internal.execution.impl.DefaultInputFingerprinter.fingerprintInputProperties(DefaultInputFingerprinter.java:77)
	at org.gradle.internal.execution.steps.SkipEmptyMutableWorkStep.fingerprintPrimaryInputs(SkipEmptyMutableWorkStep.java:181)
	at org.gradle.internal.execution.steps.SkipEmptyMutableWorkStep.executeMutable(SkipEmptyMutableWorkStep.java:81)
	at org.gradle.internal.execution.steps.SkipEmptyMutableWorkStep.executeMutable(SkipEmptyMutableWorkStep.java:53)
	at org.gradle.internal.execution.steps.MutableStep.execute(MutableStep.java:26)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.executeMutable(LoadPreviousExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.executeMutable(LoadPreviousExecutionStateStep.java:23)
	at org.gradle.internal.execution.steps.MutableStep.execute(MutableStep.java:26)
	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.executeMutable(HandleStaleOutputsStep.java:77)
	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.executeMutable(HandleStaleOutputsStep.java:43)
	at org.gradle.internal.execution.steps.MutableStep.execute(MutableStep.java:26)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$executeMutable$0(AssignMutableWorkspaceStep.java:34)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:305)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.executeMutable(AssignMutableWorkspaceStep.java:30)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.executeMutable(AssignMutableWorkspaceStep.java:21)
	at org.gradle.internal.execution.steps.MutableStep.execute(MutableStep.java:26)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:56)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:38)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:68)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:132)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.api.internal.tasks.execution.ProblemsTaskPathTrackingTaskExecuter.execute(ProblemsTaskPathTrackingTaskExecuter.java:41)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	... 23 more
Caused by: org.gradle.api.internal.artifacts.transform.TransformException: Failed to transform kotlin-dsl-shared-runtime.jar (project :kotlin-dsl-shared-runtime) to match attributes {artifactType=foo, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=17, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
	at org.gradle.api.internal.artifacts.transform.TransformedProjectArtifactSet.visit(TransformedProjectArtifactSet.java:95)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ParallelResolveArtifactSet$VisitingSet$StartVisitAction.visitResults(ParallelResolveArtifactSet.java:100)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ParallelResolveArtifactSet$VisitingSet.visit(ParallelResolveArtifactSet.java:69)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ArtifactSetToFileCollectionFactory$PartialSelectedArtifactSet.visitFiles(ArtifactSetToFileCollectionFactory.java:275)
	at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.visitContents(ResolutionBackedFileCollection.java:75)
	... 88 more
Caused by: java.lang.IllegalArgumentException: project :kotlin-dsl-shared-runtime not found.
	at org.gradle.api.internal.project.DefaultProjectStateRegistry.stateFor(DefaultProjectStateRegistry.java:151)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformInvocationFactory.determineProducerProject(DefaultTransformInvocationFactory.java:143)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformInvocationFactory.createInvocation(DefaultTransformInvocationFactory.java:85)
	at org.gradle.api.internal.artifacts.transform.TransformStep.lambda$createInvocation$2(TransformStep.java:79)
	at org.gradle.internal.Try$Success.map(Try.java:170)
	at org.gradle.api.internal.artifacts.transform.TransformStep.createInvocation(TransformStep.java:69)
	at org.gradle.api.internal.artifacts.transform.TransformStepNode$InitialTransformStepNode$TransformInitialArtifact$1.transform(TransformStepNode.java:250)
	at org.gradle.api.internal.artifacts.transform.TransformStepNode$TransformStepBuildOperation.call(TransformStepNode.java:381)
	at org.gradle.api.internal.artifacts.transform.TransformStepNode$TransformStepBuildOperation.call(TransformStepNode.java:360)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:210)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:205)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:54)
	at org.gradle.api.internal.artifacts.transform.TransformStepNode$AbstractTransformArtifacts.calculateValue(TransformStepNode.java:354)
	at org.gradle.api.internal.artifacts.transform.TransformStepNode$AbstractTransformArtifacts.calculateValue(TransformStepNode.java:334)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:227)
	at org.gradle.internal.Try.ofFailable(Try.java:46)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.attachValue(CalculatedValueContainer.java:222)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:195)
	at org.gradle.internal.model.CalculatedValueContainer.run(CalculatedValueContainer.java:181)
	at org.gradle.api.internal.artifacts.transform.TransformStepNode.execute(TransformStepNode.java:183)
	at org.gradle.execution.plan.DefaultNodeExecutor.execute(DefaultNodeExecutor.java:31)
	... 10 more
```

This error does not occur if the buildscript does not depend on the included build project.

### Expected Behavior

No failure is thrown during CC

### Context (optional)

This is a minimized version of a reproducer from the `gradle/gradle` build, where the  `toolingApiShadedJar` in the `tooling-api` project will fail if the tooling-api transitively depends on the `org.gradle:kotlin-dsl-shared-runtime` project.

### Self-contained Reproducer Project

```

    def reproducer() {
        kotlinFile("kotlin-dsl-shared-runtime/build.gradle", """
            plugins {
                id("java-library")
            }
            group = "org.gradle"
        """)

        settingsFile << """
            includeBuild("kotlin-dsl-shared-runtime")
        """

        buildFile("""
            // If this buildscript block is removed, the CC execution succeeds
            buildscript {
                dependencies {
                    classpath("org.gradle:kotlin-dsl-shared-runtime")
                }
            }

            plugins {
                id("java-library")
            }

            abstract class FooTransform implements TransformAction<org.gradle.api.artifacts.transform.TransformParameters.None> {
                @InputArtifact
                abstract Provider<FileSystemLocation> getInput()
                void transform(TransformOutputs outputs) {
                    outputs.file(input.get().asFile.name + ".transformed").createNewFile()
                }
            }

            dependencies {
                registerTransform(FooTransform) {
                    from.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, "jar")
                    to.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, "foo")
                }

                implementation("org.gradle:kotlin-dsl-shared-runtime")
            }

            tasks.register("toolingApiShadedJar", Sync) {
                from(configurations.runtimeClasspath.incoming.artifactView {
                    attributes.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, "foo")
                }.files)
                into(layout.buildDirectory)
            }
        """)

        when:
        succeeds("toolingApiShadedJar")

        then:
        file("build/kotlin-dsl-shared-runtime.jar.transformed").exists()

        when:
        fails("toolingApiShadedJar", "--configuration-cache")

        then:
        failure.assertHasCause("project :kotlin-dsl-shared-runtime not found.")
    }

```

### Gradle version

9.4.0

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by 6hundreds**
Fixes #36177 

## Current design overview
In case of included builds, we decide how to store it in CC by checking [does it have a work ](https://github.com/gradle/gradle/blob/master/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt#L304), what is checking the contents of the build's execution plan.

### When there is a work:
- we store the build as `IncludedBuild` meaning storing its projects as `ProjectWithWork`:
https://github.com/gradle/gradle/blob/5a2aa0e4ba5a5bd64c77bf997e8d9cfb9afa3608/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt#L467-L468 
- when we load, we register and create `projects with work` of the build:
https://github.com/gradle/gradle/blob/5a2aa0e4ba5a5bd64c77bf997e8d9cfb9afa3608/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt#L490-L492

### When there is no work:
- we store the build as `BuildWithNoWork` meaning storing its projects as `ProjectWithNoWork`:
https://github.com/gradle/gradle/blob/5a2aa0e4ba5a5bd64c77bf997e8d9cfb9afa3608/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt#L437 
- when we load, we just load `BuildWithNoWork` without actual project registration in ProjectRegistry:
https://github.com/gradle/gradle/blob/5a2aa0e4ba5a5bd64c77bf997e8d9cfb9afa3608/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt#L447-L456

Absence of restored project registration in ProjectRegistry is an important aspect, since if we want to have a Project as an input for the work, we have to have it restored properly after CC.

### Included plugin builds
In order to provide precompiled plugins to the root build, the task graph of these builds executed early as a part of build logic building process, triggered here:
https://github.com/gradle/gradle/blob/5a2aa0e4ba5a5bd64c77bf997e8d9cfb9afa3608/subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultBuildLogicBuilder.java#L66-L76
resulting setting `EMPTY` execution plan for the included build BEFORE CC checks the work presence:
https://github.com/gradle/gradle/blob/0a66e25c91ae23e67707df1ed549376b254d1d8b/subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java#L130-L135 

Having said that, included plugin builds always have no work at the CC store moment and being stored as `BuildWithNoWork`

### Included library(non-plugin) builds
The goal of these type of builds is to provide dependency substitutions for the root builds, so the execution of the task graph is postponed(since it doesn't go through build logic building process). In other words, these builds always have some work at the CC store moment and being stored as `IncludedBuild`, meaning store/reload all its projects.

However, when a project of such a build is being used as a part of buildscript classpath(apply plugins is somewhat similar to this, as it also alters buildscript classpath), we have to go through build logic building process, where we execute task graph early, forcing build to be stored as `BuildWithNoWork`.

## This PR
This PR adds an analysis of the root build work graph by looking for transform nodes, and store included build projects used as input artifacts for those transforms

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by 6hundreds** [comment]
@bot-gradle test acc

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt [hunk 1]
```diff
@@ -457,19 +485,28 @@ class ConfigurationCacheState(
...
             withDebugFrame({ "Gradle" }) {
                 writeGradleState(gradle)
-                val projects = collectProjects(buildState.projects, scheduledWork.scheduledNodes, gradle.serviceOf())
+                val projects = collectProjects(buildState.projects, scheduledWork.scheduledNodes, gradle.serviceOf(), shouldStoreProject)
                 writeProjects(gradle, projects)
                 writeRequiredBuildServicesOf(buildState, buildTreeState)
             }
-            withDebugFrame({ "Work Graph" }) {
-                writeWorkGraphOf(gradle, scheduledWork)
+            if (scheduledWork.scheduledNodes.isNotEmpty()) {
```
Comment (6hundreds) [inline platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt:517]: Before this PR, included builds with no work(say, build logic builds) were stored as `BuildWithNoWork`. Now we can store such builds (we're interested in storing projects mostly) if their projects used as inputs for transform in the root build

File: subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java [hunk 2]
```diff
@@ -79,6 +79,9 @@ public class DefaultTaskExecutionGraph implements TaskExecutionGraphInternal {
     private List<Task> allTasks = Collections.emptyList();
     private boolean hasFiredWhenReady;
 
+    @Nullable
+    private ScheduledWork collectedScheduledWork = null;
```
Comment (6hundreds) [inline subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java]: Stored for avoiding compute it twice, since it can be very expensive to traverse over root build task graph

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt [hunk 3]
```diff
@@ -326,20 +346,23 @@ class ConfigurationCacheState(
     private
     suspend fun WriteContext.writeBuildState(build: BuildToStore, buildTreeState: StoredBuildTreeState) {
         val state = build.build
+        val includedBuildProjectsToTransformInRootBuild = includedBuildProjectsToTransformInRootBuild(state)
```
Comment (mlopatkin) [inline platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt]: :question: Can we lift it into buildTreeState? I suspect just walking the nodes for every build is going to be expensive. We can compute `build -> transformed project` multimap and reuse it instead.

With that optimization we may not need the cache in `collectScheduledWork()` even.

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt [hunk 4]
```diff
@@ -316,6 +319,23 @@ class ConfigurationCacheState(
...
+            .filterIsInstance<TransformStepNode>()
+            .mapNotNull { node ->
+                val id = node.inputArtifact.id.componentIdentifier
+                (id as? ProjectComponentIdentifier)?.let {
+                    if (it.build.buildPath == build.identityPath.asString()) {
+                        Path.path(it.projectPath)
+                    } else {
+                        null
+                    }
+                }
```
Comment (mlopatkin) [inline platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt]: 💅 I find the following a bit easier to read:
```suggestion
                if (id is ProjectComponentIdentifier && id.build.buildPath == build.identityPath.asString()) {
                    Path.path(id.projectPath)
                } else {
                    null
                }
```

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt (hunk 3 above)
Comment (6hundreds) [reply platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt]: @mlopatkin PTAL at the last changes, I feel like I've a bit overengineered in the response to your comment.

**Comment by 6hundreds** [comment]
@mlopatkin Thanks for the review! PTAL again

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt (hunk 3 above)
Comment (mlopatkin) [reply platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt]: > PTAL at the last changes, I feel like I've a bit overengineered in the response to your comment.

Yep, I had a bit simpler implementation in mind. Let me draft it on top of your changes...

**Comment by mlopatkin** [comment]
❓ One thing that I missed during the first round - what if the transform isn't part of the root build, but is in another included build itself?

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt (hunk 3 above)
Comment (mlopatkin) [reply platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt]: > > PTAL at the last changes, I feel like I've a bit overengineered in the response to your comment.
> 
> Yep, I had a bit simpler implementation in mind. Let me draft it on top of your changes...

Something akin to 1bcb4d3a5643e0904f64c4c51f52e9e989db6c11

**Comment by 6hundreds** [comment]
@bot-gradle test this

File: platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheIncludedBuildTransformIntegrationTest.groovy [hunk 5]
```diff
@@ -0,0 +1,234 @@
...
+        settingsFile """
+            includeBuild("consumer")
+            includeBuild("build-logic")
+        """
+
+        buildFile """
+            tasks.register("run") {
+                dependsOn(gradle.includedBuild("consumer").task(":syncFoo"))
+            }
+        """
```
Comment (mlopatkin) [inline platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheIncludedBuildTransformIntegrationTest.groovy:226]: :x: this test still fails if we add a build logic dependency on the `"org.test:lib:1.0"` and run `:run` twice:

```diff
diff --git a/platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheIncludedBuildTransformIntegrationTest.groovy b/platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheIncludedBuildTransformIntegrationTest.groovy
index 9b93c422113..2ec5fd2e278 100644
--- a/platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheIncludedBuildTransformIntegrationTest.groovy
+++ b/platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheIncludedBuildTransformIntegrationTest.groovy
@@ -191,6 +191,12 @@ class ConfigurationCacheIncludedBuildTransformIntegrationTest extends AbstractCo
         """
 
         buildFile """
+            buildscript {
+                dependencies {
+                    classpath("org.test:lib:1.0")
+                }
+            }
+
             tasks.register("run") {
                 dependsOn(gradle.includedBuild("consumer").task(":syncFoo"))
             }
@@ -198,11 +204,83 @@ class ConfigurationCacheIncludedBuildTransformIntegrationTest extends AbstractCo
 
         when:
         configurationCacheRun "run"
+        configurationCacheRun "run"
 
         then:
         file("consumer/build/lib-1.0.jar.foo").exists()
     }
```

Second invocation is crucial because we skip a fair share of restoring the builds when `load-after-store` is in play, see 
* https://github.com/gradle/gradle/blob/83a4d9f0cb9d64108a47c4a390f2b30b86563dfc/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt#L203-L207
It then fails with:
```
Caused by: java.util.NoSuchElementException: Key : is missing in the map.
	at app//kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at app//kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:371)
	at app//org.gradle.internal.cc.impl.ConfigurationCacheState.convertProjects(ConfigurationCacheState.kt:242)
	at app//org.gradle.internal.cc.impl.ConfigurationCacheState.identifyBuild(ConfigurationCacheState.kt:227)
	at app//org.gradle.internal.cc.impl.ConfigurationCacheState.readRootBuildState(ConfigurationCacheState.kt:205)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$readRootBuildStateFrom$1.invokeSuspend(DefaultConfigurationCacheIO.kt:229)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$readConfigurationCacheStateWithSpecialDecoders$1.invokeSuspend(DefaultConfigurationCacheIO.kt:352)
	at app//org.gradle.internal.serialize.graph.CodecKt$readWith$1$1.invokeSuspend(Codec.kt:148)
	at app//org.gradle.internal.serialize.graph.RunningKt$runReadOperation$1.invokeSuspend(Running.kt:33)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at app//kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at app//org.gradle.internal.serialize.graph.RunningKt.runToCompletion(Running.kt:58)
	at app//org.gradle.internal.serialize.graph.RunningKt.runReadOperation(Running.kt:32)
	at app//org.gradle.internal.serialize.graph.CodecKt.readWith(Codec.kt:147)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.withReadContextFor(DefaultConfigurationCacheIO.kt:505)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.withReadContextFor(DefaultConfigurationCacheIO.kt:497)
	at app//org.gradle.internal.cc.impl.ConfigurationCacheBuildTreeIO.withReadContextFor(ConfigurationCacheBuildTreeIO.kt:100)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.withReadContextFor(DefaultConfigurationCacheIO.kt:100)
	at app//org.gradle.internal.cc.impl.ConfigurationCacheBuildTreeIO.withReadContextFor$default(ConfigurationCacheBuildTreeIO.kt:94)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.readConfigurationCacheStateWithSpecialDecoders(DefaultConfigurationCacheIO.kt:350)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.readConfigurationCacheState$lambda$0$0(DefaultConfigurationCacheIO.kt:258)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.withSharedObjectDecoderFor(DefaultConfigurationCacheIO.kt:334)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.readConfigurationCacheState$lambda$0(DefaultConfigurationCacheIO.kt:257)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.withStringDecoderFor(DefaultConfigurationCacheIO.kt:322)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.readConfigurationCacheState(DefaultConfigurationCacheIO.kt:256)
	at app//org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.readRootBuildStateFrom(DefaultConfigurationCacheIO.kt:227)
```

It looks like we need to serialize all project hierarchy or at least the root project of the build to be able to restore everything properly.

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt [hunk 6]
```diff
@@ -837,17 +883,31 @@ class ConfigurationCacheState(
...
-            if (relevantProjects.contains(project)) {
-                mutableModel.layout.buildDirectory.finalizeValue()
-                ProjectWithWork(project.projectPath, mutableModel.projectDir, mutableModel.buildFile, mutableModel.layout.buildDirectory.asFile.get(), mutableModel.normalization.computeCachedState())
-            } else {
-                ProjectWithNoWork(project.projectPath, mutableModel.projectDir, mutableModel.buildFile)
+        return projects.allProjects
+            .filter(shouldStoreProject)
+            .map { project ->
+                val mutableModel = project.mutableModel
+                if (relevantProjects.contains(project) || project.projectPath in transformInputProjects) {
```
Comment (mlopatkin) [inline platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt:914]: ❓ Why do we need to check belonging twice? To get the project restored as ProjectWithWork (i.e. registered in the projects list) even if it isn't relevant?

I don't particularly like the duplication between this and `shoudStoreProject` predicate. It took me a while to understand all the different cases :(

**Comment by 6hundreds** [comment]
@bot-gradle test this

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt (hunk 6 above)
Comment (6hundreds) [reply platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/internal/cc/impl/ConfigurationCacheState.kt:914]: Please see the comment here 
https://github.com/gradle/gradle/pull/36872/changes#diff-7b2afca823651574f7f4e9b9851994ebc98993b2231fc92f8d6ddf4020bcdc83R908-R913
