### PR TITLE
Workaround for Groovy compiler bug

### LINKED ISSUE #6027: Plugin compiled with Groovy's @CompileStatic breaks with Gradle 4.9
A bug in the Groovy compiler 2.4.10 and before ((GROOVY-8142)[https://issues.apache.org/jira/browse/GROOVY-8142]) can cause a plugin to refer to Gradle internal APIs even though its source only refers to public ones. Once Gradle changes or removes the unintentionally referred-to internal APIs, the published plugin stops working.

This is what happened at least in one case with the [Gradle Packer plugin](https://gitlab.com/ysb33rOrg/packer-gradle-plugin/blob/RELEASE_0_1_3/src/main/groovy/org/ysb33r/gradle/packer/tasks/PackerBuilder.groovy#L193): it refers to the public `Project.file()` API, but ended up with the bytecode referring to the internal `FileOperations.file()` API. In Gradle 4.9 `DefaultProject` stopped implementing `FileOperations`, which was a change to only internal APIs, yet it caused the Packer plugin to break with the following error:

```text
java.lang.IncompatibleClassChangeError: Class org.gradle.api.internal.project.DefaultProject_Decorated does not implement the requested interface org.gradle.api.internal.file.FileOperations
```

The problem to occur requires the following conditions to all be present:

- the plugin must be compiled with Gradle 3.5 or earlier (Gradle 4.0 shipped a year ago with Groovy 2.4.11 that has the compiler bug fixed)
- the plugin must be calling `Project.file()`, `Project.files()` etc. _from inside a type that extends `DefaultTask`_ (there might be other cases, but the methods on `FileOperations` are the ones that we know about)
- the task in question must be written in Groovy, and must be using `@CompileStatic`
- GROOVY-8142 must trigger while building the plugin – this doesn't happen every time, so even if all the above conditions are present, you might still end up with the correct bytecode

### PR DESCRIPTION
**Pull request by lptr**
See https://issues.apache.org/jira/browse/GROOVY-8732

Fixes #6027.

### CODE REVIEW

**Comment by lptr** [comment]
Quick feedback build: https://builds.gradle.org/viewQueued.html?itemId=14808985

**Comment by lptr** [comment]
Cross-version tests: https://builds.gradle.org/viewLog.html?buildId=14810553

**Comment by lptr** [comment]
All-cross-version tests for `integTest`: https://builds.gradle.org/viewQueued.html?itemId=14810696

**Comment by lptr** [comment]
Check if test fails as expected: https://builds.gradle.org/viewQueued.html?itemId=14811351

**Comment by lptr** [comment]
Branch build: https://builds.gradle.org/viewQueued.html?itemId=14812532

**Comment by lptr** [comment]
Branch build: https://builds.gradle.org/viewQueued.html?itemId=14812942

File: subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy [hunk 1]
```diff
@@ -213,4 +215,45 @@ apply plugin: SomePlugin
         version previous requireGradleDistribution() withTasks 'assemble' inDirectory(file("producer")) run()
         version current requireGradleDistribution() withTasks 't' run()
     }
+
+    @Issue("https://github.com/gradle/gradle/issues/6027")
+    def "task can use project.file() from statically typed Groovy"() {
+        // Don't run these for RC 3, as stuff did change during the RCs
+        Assume.assumeFalse(previous.version == GradleVersion.version("2.14-rc-3"))
```
Comment (wolfs) [inline subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy]: I am pretty sure we are not running tests against `2.14` RCs, now that `2.14` is out.

File: subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy [hunk 2]
```diff
@@ -213,4 +215,45 @@ apply plugin: SomePlugin
...
+
+        when:
+        file("producer/build.gradle") << """
+            apply plugin: 'groovy'
+            dependencies {
+                ${previous.version < GradleVersion.version("1.4-rc-1") ? "groovy" : "compile"} localGroovy()
```
Comment (wolfs) [inline subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy]: Do we really want to test versions this old? Shouldn't we annotate this class with something like `@TargetVersions(["3.0+"])`?

File: subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java [hunk 3]
```diff
@@ -137,7 +138,10 @@
 import static org.gradle.util.GUtil.addMaps;
 
 @NoConventionMapping
-public class DefaultProject extends AbstractPluginAware implements ProjectInternal, DynamicObjectAware {
+public class DefaultProject extends AbstractPluginAware implements ProjectInternal, DynamicObjectAware,
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java]: Do we still want to rename fields on Project, too?

File: subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java [hunk 4]
```diff
@@ -94,19 +94,24 @@
 
     private final TaskIdentity<?> identity;
 
-    private final ProjectInternal project;
+    // Weird name to work around https://issues.apache.org/jira/browse/GROOVY-8732
+    private final ProjectInternal _project;
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java]: We can reap the benefits of these renames when everyone uses at least Gradle 4.10 to compile, right? So we could remove `FileOperations` from `ProjectInternal` in Gradle 6.0?

Comment (lptr) [reply subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java]: `ProjectInternal` does not implement `FileOperations`, only `DefaultProject` does. It would need to remain so as long as we want to support plugins compiled against Gradle 4.9 or earlier.

File: subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java (hunk 3 above)
Comment (lptr) [reply subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java]: No, because users don't extend `DefaultProject`, and the Groovy bug only affects subclassing.

File: subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy (hunk 2 above)
Comment (lptr) [reply subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy]: There is no such thing as `@TargetVersions("3.0+")` unfortunately. And the tests run just fine on 1.0, so why not keep them? In any case, if we want to cull the number of cross-version tests we run, that should happen on a general basis, not on a single test.

Comment (wolfs) [reply subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy]: I thought there was: https://github.com/gradle/gradle/blob/6bd97fbe62de4180a8ad946f9d61edaac9eb09d7/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/CrossVersionTestRunner.groovy#L70-L73

I'm fine with running this test for every version.

Comment (lptr) [reply subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy]: Hm. When I added that annotation it just failed with some exception. In any case, I still think we should not reduce the range of tested versions for some tests but not others.

**Comment by lptr** [comment]
I think this is good to merge, the only failure was an unrelated test due to unable to delete file error.
