### PR TITLE
Use default name for root project

### LINKED ISSUE #15655: Builds fail if root project is in root of mount point, with further implications
Building any project in a root mount point (e.g. `C:/` for Windows or `/` for *nix) fails unless `settings.gradle` has a `rootProject.name=` value specified.

### Expected Behavior

Gradle should not be smart about the project name, by deducing it from the directory name, but it should be specified explicitly. Especially, this is problematic in a multi-developer environment where the project name can vary greatly depending on what developers are naming their clone directories, and it will affect what's getting reported to Gradle Enterprise, thereby polluting data.

I suppose it could be discouraged as a deprecation, then to be disallowed in a future major release.

### Current Behavior

```
A problem occurred configuring root project ''.
> The project name must not be empty. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/6.7.1/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
```

### Context

This was causing issues when I mounted a shared folder in a Windows VirtualBox environment.

### Steps to Reproduce 

```shell
$ gradle -p / --project-cache-dir=$HOME
```

## Your Environment
OS: Windows/macOS
Gradle: 6.8-rc-4

### PR DESCRIPTION
**Pull request by reinsch82**
- fixes #15655

### CODE REVIEW

**Comment by reinsch82** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java [hunk 1]
```diff
@@ -101,11 +105,20 @@ public DefaultSettings(
...
-        this.rootProjectDescriptor = createProjectDescriptor(null, settingsDir.getName(), settingsDir);
+        this.rootProjectDescriptor = createProjectDescriptor(null, getProjectName(settingsDir), settingsDir);
         this.dependencyResolutionManagement = services.get(DependencyResolutionManagementInternal.class);
         this.toolchainManagement = services.get(ToolchainManagementInternal.class);
     }
 
+    private static String getProjectName(File settingsDir) {
+        if(contains(File.listRoots(), settingsDir)) {
+            String rootIndicator = settingsDir.toPath().getRoot().toString().replaceAll("[\\\\:\\/]*", "");
+            return "generated " + rootIndicator  + (rootIndicator.isEmpty() ? "" : " ") +
```
Comment (ljacomet) [inline subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java:116]: I would use `-` instead of spaces as the later is going to make it harder to use the name on the CLI. Not that it should happen often.

**Review by ljacomet — CHANGES_REQUESTED** [review]
Thanks for looking into that and I believe this solution makes sense.

We should add documentation for this though and I have a comment on the choice of the separator character.

**Review by hythloda — APPROVED** [review]

**Comment by reinsch82** [comment]
@bot-gradle test this

File: subprojects/core-api/src/main/java/org/gradle/api/Project.java [hunk 2]
```diff
@@ -304,7 +304,9 @@ public interface Project extends Comparable<Project>, ExtensionAware, PluginAwar
 
     /**
      * <p>Returns the name of this project. The project's name is not necessarily unique within a project hierarchy. You
-     * should use the {@link #getPath()} method for a unique identifier for the project.</p>
+     * should use the {@link #getPath()} method for a unique identifier for the project.
+     * If the root project is unnamed and is located on a file system root it will have a generated random name
```
Comment (octylFractal) [inline subprojects/core-api/src/main/java/org/gradle/api/Project.java:308]: nitpick: word order
```suggestion
     * If the root project is unnamed and is located on a file system root it will have a randomly-generated name
```

**Comment by reinsch82** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java [hunk 3]
```diff
@@ -101,11 +105,21 @@ public DefaultSettings(
...
         this.startParameter = startParameter;
         this.services = serviceRegistryFactory.createFor(this);
-        this.rootProjectDescriptor = createProjectDescriptor(null, settingsDir.getName(), settingsDir);
+        this.rootProjectDescriptor = createProjectDescriptor(null, getProjectName(settingsDir), settingsDir);
         this.dependencyResolutionManagement = services.get(DependencyResolutionManagementInternal.class);
         this.toolchainManagement = services.get(ToolchainManagementInternal.class);
     }
 
+    private static String getProjectName(File settingsDir) {
+        if(contains(File.listRoots(), settingsDir)) {
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java:114]:
```suggestion
        if (contains(File.listRoots(), settingsDir)) {
```

💄  In general, I think we use a space in front of the `(` after an `if`.

File: subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java [hunk 4]
```diff
@@ -101,11 +105,21 @@ public DefaultSettings(
...
+            String rootIndicator = settingsDir.toPath().getRoot().toString().replaceAll("[\\\\:\\/]*", "");
+            // using "-" to separate the parts of the root project name to allow easier usage in the CLI, just in case.
+            return "generated-" + rootIndicator  + (rootIndicator.isEmpty() ? "" : "-") +
+                sha512().hashString(now().toString()).toString().substring(0, 6);
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java:118]: The disadvantage here is that this name is unstable and will vary between builds. Did you think of a way to make it stable?

**Review by wolfs — APPROVED** [review]

File: subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java (hunk 3 above)
Comment (reinsch82) [reply subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java:114]: That happens because I'm currently a bit afraid of using the auto formatter ;)

File: subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java (hunk 4 above)
Comment (reinsch82) [reply subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java:118]: not too much.
@ljacomet even suggested feeling some pain if you not follow the guidelines helps ;)
and the guideline is: name your root project.
also it is a rare corner case to my understanding. It will only be used in situations where the project is actually checked out on `root/c:\/d:\/...`

**Review by ljacomet — APPROVED** [review]

**Comment by reinsch82** [comment]
@bot-gradle test and merge

**Comment by reinsch82** [comment]
@bot-gradle test and merge

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by reinsch82** [comment]
@bot-gradle test and merge
