### PR TITLE
Check if multi-release JARs are properly instrumented when loading classes

### LINKED ISSUE #25434: Instrumentation of multi-release JARs should not fail on newer versions
### Expected Behavior

When the multi-release JAR of the buildscript classpath contains a versioned directory for Java version that the current Gradle doesn't support, Gradle should be able to instrument the root directory and supported versioned directories without failures.

### Current Behavior (optional)

The instrumentation fails when it tries to instrument the classes in the unsupported versioned directory.

### Context

This issue makes it impossible to use newer libraries as part of the buildscript classpath, even if the library itself is backwards-compatible. It defeats the purpose of the MR-JAR.

See also #24390 and #24430.

### PR DESCRIPTION
**Pull request by mlopatkin**
Gradle can only instrument bytecode up to the version ASM understands.
For multi-release JARs this means that versioned directories for the
unsupported JVM versions are not processed and instrumented JARs contain
no classes for these versions. However, due to the way agent-based
instrumentation works, classes are loaded first from the original JAR
and only then the agent replaces the bytecode with the instrumented
copy. Prior to this commit, it was possible that the non-instrumented
original class could be loaded when Gradle would run on the unsupported
JVM.

Now instrumentation puts a marker resource into processed multi-release
JARs which contains instrumentation status. Root directory always has
"instrumented" status. If there is an unsupported versioned directory
with class files, it gets a versioned resource with "not instrumented"
status.

The replacing class loader loads the resource and checks the status when
transformed classes are looked up in the JAR for the first time. If the
JVM is unsupported and there are versioned class for this JVM, the class
loader loads the "not instrumented" version of the resource and aborts
loading the class.

Fixes #25434

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test APT

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle test this

File: subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java [hunk 1]
```diff
@@ -185,26 +191,39 @@ public synchronized byte[] loadTransformedClass(String className) throws IOExcep
...
-                try {
-                    // Set up the MR-JAR properly when running on Java 9+.
-                    jarFile = new JarFile(jarFilePath, true, JarFile.OPEN_READ, JarFile.runtimeVersion());
-                } catch (NoSuchMethodError e) {
-                    // Running on Java 8, fall back to the old ways.
-                    jarFile = new JarFile(jarFilePath);
+                jarFile = JarCompat.open(jarFilePath);
+                if (jarFile.isMultiRelease() && !isTransformed(jarFile.getJarFile())) {
+                    throw new GradleException(
+                        "Cannot load multi-release JAR '"
```
Comment (bamboo) [inline subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java:204]: 🤔 Can we also include something about the running JVM version here? Perhaps something like "... because it cannot be fully instrumented for Java 22 by this version of Gradle. Please use a supported Java version (<= 21)."

File: subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java [hunk 2]
```diff
@@ -290,12 +283,14 @@ protected void processResource(ClasspathBuilder.EntryBuilder builder, ClasspathE
...
 
+        protected void finishProcessing(ClasspathBuilder.EntryBuilder builder) throws IOException {}
+
         private boolean isClassFile(ClasspathEntryVisitor.Entry entry) {
             return entry.getName().endsWith(".class");
         }
 
         private boolean isManifest(ClasspathEntryVisitor.Entry entry) {
-            return isManifestName(entry.getName());
+            return JarUtil.isManifestName(entry.getName());
```
[the remark this answers is not in the document]
Comment (bamboo) [reply subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java:293]: Ok. I agree that, in certain situations, when the context is not clear or there's ambiguity, qualified names can help better understand the meaning behind a symbol. Often though, they add noise, make lines longer (which can actually make it more painful to read code in the web by requiring horizontal scrolling) and the reading less fluent.

We should come up with guidelines around this otherwise I predict a strong chance of these code changes flip flopping between `Replace static import with qualified access` and `Add static import`.

File: subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java [hunk 3]
```diff
@@ -185,26 +192,40 @@ public synchronized byte[] loadTransformedClass(String className) throws IOExcep
...
-                try {
-                    // Set up the MR-JAR properly when running on Java 9+.
-                    jarFile = new JarFile(jarFilePath, true, JarFile.OPEN_READ, JarFile.runtimeVersion());
-                } catch (NoSuchMethodError e) {
-                    // Running on Java 8, fall back to the old ways.
-                    jarFile = new JarFile(jarFilePath);
+                jarFile = JarCompat.open(jarFilePath);
+                if (jarFile.isMultiRelease() && !isTransformed(jarFile.getJarFile())) {
+                    throw new GradleException(String.format(
+                        "Cannot load multi-release JAR '%s' because it cannot be fully instrumented for Java %d by this version of Gradle. Please use supported Java version (<=%d).",
```
Comment (bamboo) [inline subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java:205]:
```suggestion
                        "Cannot load multi-release JAR '%s' because it cannot be fully instrumented for Java %d by this version of Gradle. Please use a supported Java version (<=%d).",
```

File: subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java [hunk 4]
```diff
@@ -185,26 +192,40 @@ public synchronized byte[] loadTransformedClass(String className) throws IOExcep
...
             return className + ".class";
         }
     }
+
+    private static boolean isTransformed(JarFile jarFile) throws IOException {
+        JarEntry entry = jarFile.getJarEntry(MARKER_RESOURCE_NAME);
+        if (entry != null) {
+            InputStream in = jarFile.getInputStream(entry);
+            try {
+                return "true".equals(StreamByteBuffer.of(in).readAsString("UTF-8"));
```
Comment (bamboo) [inline subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java:224]: 💡 Since this marker is only ever read by Gradle, why not make it a single byte?

File: subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/archive/JarTestFixture.groovy [hunk 5]
```diff
@@ -101,7 +101,7 @@ class JarTestFixture extends ZipTestFixture {
     }
 
     def assertIsMultiRelease() {
-        "true" == manifest.mainAttributes.getValue("Multi-Release")
+        assert "true" == manifest.mainAttributes.getValue("Multi-Release")
```
Comment (bamboo) [inline subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/archive/JarTestFixture.groovy:104]: 👍

**Review by bamboo — CHANGES_REQUESTED** [review]

File: subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java (hunk 4 above)
Comment (mlopatkin) [reply subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java]: Thanks! In fact, we can go deeper and make it 0 bytes for the common case, and only use a non-empty file for the unsupported versions.

Comment (bamboo) [reply subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java]: Even better! 😃

**Review by bamboo — APPROVED** [review]
Good stuff 👍

**Comment by mlopatkin** [comment]
@bot-gradle test and merge
