### PR TITLE
Intercept `Path.readText()` calls for CC inputs

### LINKED ISSUE #33704: Calls to kotlin extension `Path.readText()` not captured in configuration cache
### Current Behavior

When I call `Path.readText()` in a plugin, that input is not captured in configuration cache. If I instead call `Path.readLines()` the input is captured.

This is really strange since `Path.readText()` eventually calls `Files.newInputStream`, which is instrumented by `NioFileInterceptors`.

### Expected Behavior

Calling `Path.readText()` should result in capturing that file access as a configuration cache input

### Context (optional)

_No response_

### Self-contained Reproducer Project

Clone this branch of my Spotlight project: https://github.com/joshfriend/spotlight/compare/broken-cc-tracking and check out commit https://github.com/joshfriend/spotlight/commit/e700d422bd895fae8cdafaa2f2e8f8c3bac0bc88

Run `./gradlew :spotlight-gradle-plugin:functionalTest` to see test failures caused by the configuration cache report containing unexpected inputs.

Then, in [this section](https://github.com/joshfriend/spotlight/blob/e700d422bd895fae8cdafaa2f2e8f8c3bac0bc88/buildscript-utils/src/main/kotlin/com/fueledbycaffeine/spotlight/buildscript/BuildFile.kt#L30-L35), swap the commented out section back in and rerun the tests. They should pass because Gradle is not properly tracking the CC inputs.

### Gradle version

8.14.1, 9.0.0-milestone-9

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by jbartok**
Fixes:
* https://github.com/gradle/gradle/issues/33704

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/inputs/undeclared/UndeclaredFileAccess.groovy [hunk 1]
```diff
@@ -301,4 +304,80 @@ abstract class UndeclaredFileAccess extends BuildInputRead {
             }
         }
     }
+
+    static UndeclaredFileAccess pathText(String filePath) {
+        kotlinOnlyPathAccess(filePath, "Paths.get(\"$filePath\").readText()")
+        // makes no sense to test the Java & Groovy versions, because there the Charset parameter needs to be provided
```
Comment (ov7a) [inline platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/inputs/undeclared/UndeclaredFileAccess.groovy:310]: 💭 I'm not sure I get this comment 100%. Should it be on `kotlinOnlyPathAccess` helper?

**Review by ov7a — APPROVED** [review]

File: platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/inputs/undeclared/UndeclaredFileAccess.groovy (hunk 1 above)
Comment (jbartok) [reply platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/inputs/undeclared/UndeclaredFileAccess.groovy]: The comment tries to explain that we are not testing the `pathText` method and Java and Groovy, because it doesn't have an equivalent there (the equivalent needs an explicit encoding param, but that case is tested separately anyways). I'll try to rephrase.
