### PR TITLE
Wrapper HTTPS proxy authentication

### LINKED ISSUE #5052: Gradle wrapper does not respect proxy user and pass for distribution downloading
### Expected Behavior
When http.proxyHost, http.proxyPort, http.proxyUser and http.proxyPassword are specified in GRADLE_OPTS environment variable they should be respected during distribution downloading.

### Current Behavior
Seems like only http.proxyHost and http.proxyPort are taken into account.
While invoking "gradlew installDist" this exception is thrown:
Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"

### Context
Build container is behind web proxy and all gradle operations (distribution downloading and build dependency downloading) should respect all web proxy properties (http.proxyHost, http.proxyPort, http.proxyUser and http.proxyPassword + https.proxyHost, https.proxyPort, https.proxyUser and https.proxyPassword). 

### Steps to Reproduce (for bugs)
Gradle 4.4 is used and gradle-wrapper.properties look like this:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-bin.zip
```

Steps:
```
bash-4.2$ echo "env GRADLE_OPTS: ${GRADLE_OPTS}"
env GRADLE_OPTS: -Dhttp.proxyHost=proxy.host -Dhttp.proxyPort=8080 -Dhttp.proxyUser=proxy-user -Dhttp.proxyPassword=proxy-pass -Dhttps.proxyHost=proxy.host -Dhttps.proxyPort=8080 -Dhttps.proxyUser=proxy-user -Dhttps.proxyPassword=proxy-pass

bash-4.2$ echo "env JAVA_OPTS: ${JAVA_OPTS}"
env JAVA_OPTS: -XshowSettings:properties -Djava.util.logging.config.file=/tmp/logging.properties

bash-4.2$ ./gradlew installDist
Property settings:
    awt.toolkit = sun.awt.X11.XToolkit
    file.encoding = ANSI_X3.4-1968
    file.encoding.pkg = sun.io
    file.separator = /
    http.proxyHost = proxy.host
    http.proxyPassword = proxy-pass
    http.proxyPort = 8080
    http.proxyUser = proxy-user
    https.proxyHost = proxy.host
    https.proxyPassword = proxy-pass
    https.proxyPort = 8080
    https.proxyUser = proxy-user
    java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
    java.awt.printerjob = sun.print.PSPrinterJob
    java.class.path = /tmp/src/gradle/wrapper/gradle-wrapper.jar
    java.class.version = 52.0
    java.endorsed.dirs = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/endorsed
    java.ext.dirs = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/ext
        /usr/java/packages/lib/ext
    java.home = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre
    java.io.tmpdir = /tmp
    java.library.path = /usr/java/packages/lib/amd64
        /usr/lib64
        /lib64
        /lib
        /usr/lib
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 1.8.0_161-b14
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.util.logging.config.file = /tmp/logging.properties
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_161
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Oracle Corporation
    java.vm.version = 25.161-b14
    line.separator = \n
    org.gradle.appname = gradlew
    os.arch = amd64
    os.name = Linux
    os.version = 3.10.0-693.17.1.el7.x86_64
    path.separator = :
    sun.arch.data.model = 64
    sun.boot.class.path = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/resources.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/rt.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/sunrsasign.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/jsse.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/jce.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/charsets.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/jfr.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/classes
    sun.boot.library.path = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/amd64
    sun.cpu.endian = little
    sun.cpu.isalist =
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.command = org.gradle.wrapper.GradleWrapperMain installDist
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = ANSI_X3.4-1968
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level = unknown
    user.country = US
    user.dir = /tmp/src
    user.home = /opt/app-root/src
    user.language = en
    user.name = default
    user.timezone =

Downloading https://services.gradle.org/distributions/gradle-4.4-bin.zip
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.http.HttpURLConnection plainConnect0
FINEST: ProxySelector Request for https://services.gradle.org/distributions/gradle-4.4-bin.zip
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.https.HttpsClient New
FINEST: Looking for HttpClient for URL https://services.gradle.org/distributions/gradle-4.4-bin.zip and proxy value of HTTP @ proxy.host:8080
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.https.HttpsClient <init>
FINEST: Creating new HttpsClient with url:https://services.gradle.org/distributions/gradle-4.4-bin.zip and proxy:HTTP @ proxy.host:8080 with connect timeout:-1
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.http.HttpURLConnection plainConnect0
FINEST: Proxy used: HTTP @ proxy.host:8080
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.http.HttpURLConnection sendCONNECTRequest
FINE: sun.net.www.MessageHeader@108c4c355 pairs: {CONNECT services.gradle.org:443 HTTP/1.1: null}{User-Agent: Java/1.8.0_161}{Host: services.gradle.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Proxy-Connection: keep-alive}
Apr 14, 2018 10:25:19 PM sun.net.www.http.HttpClient logFinest
FINEST: KeepAlive stream used: https://services.gradle.org/distributions/gradle-4.4-bin.zip
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.http.HttpURLConnection doTunneling
FINE: sun.net.www.MessageHeader@4ccabbaa14 pairs: {null: HTTP/1.1 407 Proxy Authentication Required}{Server: squid/3.5.20}{Mime-Version: 1.0}{Date: Sat, 14 Apr 2018 22:25:19 GMT}{Content-Type: text/html;charset=utf-8}{Content-Length: 3744}{X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0}{Vary: Accept-Language}{Content-Language: en}{Proxy-Authenticate: Basic realm="proxy"}{X-Cache: MISS from node187}{X-Cache-Lookup: NONE from node187:8080}{Via: 1.1 node187 (squid/3.5.20)}{Connection: keep-alive}
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.http.HttpURLConnection getHttpProxyAuthentication
FINER: Proxy Authentication for AuthenticationHeader: prefer null returned null

Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2142)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

bash-4.2$
```

Regards,
N.

### PR DESCRIPTION
**Pull request by sschuberth**
Fixes #5052 and #11065.

### Context
I'm myself affect from the proxy issue with the wrapper, as well as several people who upvoted the issue report / participated in the discussion.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by sschuberth** [comment]
Unfortunately, running my newly added intgration tests for https proxy support via

    ./gradlew --no-daemon :wrapper:integTest --tests org.gradle.integtests.WrapperHttpIntegrationTest

fails with

```
org.gradle.integtests.WrapperHttpIntegrationTest > downloads wrapper via https proxy FAILED
    org.gradle.integtests.fixtures.executer.UnexpectedBuildFailure at WrapperHttpIntegrationTest.groovy:133
    org.gradle.internal.exceptions.DefaultMultiCauseException at ChainingHttpHandler.java:90
        Caused by: java.lang.AssertionError at CyclicBarrierRequestHandler.java:210

org.gradle.integtests.WrapperHttpIntegrationTest > downloads wrapper via authenticated https proxy FAILED
    org.gradle.integtests.fixtures.executer.UnexpectedBuildFailure at WrapperHttpIntegrationTest.groovy:184
    org.gradle.internal.exceptions.DefaultMultiCauseException at ChainingHttpHandler.java:90
        Caused by: java.lang.AssertionError at CyclicBarrierRequestHandler.java:210
```

I'm appreciate any help to make them pass.

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy [hunk 1]
```diff
@@ -71,4 +75,51 @@ class WrapperHttpsIntegrationTest extends AbstractWrapperIntegrationSpec {
         then:
         outputDoesNotContain('WARNING Using HTTP Basic Authentication over an insecure connection to download the Gradle distribution. Please consider using HTTPS.')
     }
+
+    def "downloads wrapper via https proxy"() {
```
Comment (donat) [inline subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy:79]: ❌ Missing test coverage: 
- "downloads wrapper via http proxy" (not https)
- proxy settings defined in an environmental variable
- proxy settings defined in an environmental variable and overridden by system properties

File: subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java [hunk 2]
```diff
@@ -55,12 +56,84 @@ public Download(Logger logger, DownloadProgressListener progressListener, String
...
+        // Do not fallback to environment variables if a proxy has been set via properties.
+        if (System.getProperty(protocol + ".proxyHost") != null) {
+            return;
+        }
+
+        String variableName = protocol + "_proxy";
+        String proxyString = System.getenv(variableName);
+        if (proxyString == null) {
+            proxyString = System.getenv(variableName.toUpperCase());
+        }
```
Comment (donat) [inline subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java:69]: ❌ So the environmental variables we read here are `HTTP_PROXY` and `HTTPS_PROXY`. I think we should not calculate the key, but explicitly define them as a static final variable.

Also, do we actually need this? It seems like that reading the system properties is enough, or do I miss a use-case?

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy [hunk 3]
```diff
@@ -16,17 +16,21 @@
...
 import org.gradle.test.fixtures.keystore.TestKeyStore
 import org.gradle.test.fixtures.server.http.BlockingHttpsServer
+import org.gradle.test.fixtures.server.http.TestProxyServer
 import org.gradle.wrapper.Download
 import org.junit.Rule
+import spock.lang.Issue
 
 import static org.gradle.test.matchers.UserAgentMatcher.matchesNameAndVersion
 
 class WrapperHttpsIntegrationTest extends AbstractWrapperIntegrationSpec {
```
Comment (donat) [inline subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy:30]: ❌ I've run your pr through our CI pipeline and got some test failures on Linux. Can you please check those out: https://builds.gradle.org/viewLog.html?buildId=34250652&tab=buildResultsDiv&buildTypeId=Gradle_Check_Quick_1_bucket50 (you should be able to log in as guest).

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy [hunk 4]
```diff
@@ -71,4 +75,51 @@ class WrapperHttpsIntegrationTest extends AbstractWrapperIntegrationSpec {
...
+        given:
+        proxyServer.start('my_user', 'my_password')
+
+        and:
+        prepareWrapper(server.uri.toString())
+        server.expect(server.get("/gradlew/dist").sendFile(distribution.binDistribution))
+        file("gradle.properties") << """
+    systemProp.https.proxyHost=localhost
+    systemProp.https.proxyPort=${proxyServer.port}
+    systemProp.https.nonProxyHosts=${JavaVersion.current() >= JavaVersion.VERSION_1_7 ? '' : '~localhost'}
```
Comment (donat) [inline subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy:111]: ❌ The Gradle tests are expected to run on Java 1.8 and above. You can remove the branch here.

File: subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java [hunk 5]
```diff
@@ -55,12 +56,84 @@ public Download(Logger logger, DownloadProgressListener progressListener, String
...
+                    }
+                }
+
+                if ("https".equals(protocol)) {
+                    String proxyUser = System.getProperty("https.proxyUser");
+                    if (proxyUser != null) {
+                        String proxyPassword = System.getProperty("https.proxyPassword", "");
+                        return new PasswordAuthentication(proxyUser, proxyPassword.toCharArray());
+                    }
+                }
```
Comment (donat) [inline subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java:130]: Can we refactor the duplicated code to a separate method?

File: subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java (hunk 2 above)
Comment (sschuberth) [reply subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java:69]: The use-case is if people behind a proxy start to use Gradle. Such users usually already have the `http_proxy` / `https_proxy` environment variables defined for other programs, like cURL, to work. Consequently, these users often expected (with reason) that Gradle should also work, but it doesn't without this change.

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy (hunk 4 above)
Comment (sschuberth) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy:111]: I copied this from the existing `WrapperHttpIntegrationTest`. Should I remove this check also from there?

File: subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java (hunk 5 above)
Comment (sschuberth) [reply subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java:130]: I've generalized the code to avoid the code duplication.

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy (hunk 4 above)
Comment (sschuberth) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy:111]: I just did that.

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy (hunk 1 above)
Comment (sschuberth) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy:79]: >     * "downloads wrapper via http proxy" (not https)

That's covered by the existing `WrapperHttpIntegrationTest`.

>     * proxy settings defined in an environmental variable

I'm planning to add any missing tests as soon as I see the existing tests pass. Do you have any idea about the test failure I've [mentioned above](https://github.com/gradle/gradle/pull/12598#issuecomment-602071079)?

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy (hunk 4 above)
Comment (big-guy) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy]: I think this was actually doing something important.  By default, Java won't use a proxy for localhost (`nonProxyHosts` contains localhost by default).  This test was clearing `nonProxyHosts` so that the proxy will be used.  We still need to do that

Comment (sschuberth) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy]: Ah, so the condition does not intend to treat Java >= 1.7 specially, but Java < 1.7 specially. I'll drop the commit and adjust my changes again.

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy (hunk 1 above)
Comment (donat) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy]: _running build locally_

File: subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java (hunk 2 above)
Comment (donat) [reply subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java:69]: It makes sense. It seems to me though, that we should add documentation explaining the expected behavior.

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy (hunk 3 above)
Comment (donat) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy:29]: New build containing the latest changes from master: https://builds.gradle.org/viewQueued.html?itemId=35015922

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy (hunk 1 above)
Comment (donat) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy]: It fails consistently on Linux and on MacOS as well. It seems to be a problem with the test itself (the proxy simply doesn't work). Running from the cmd line I get the same short error output, but the stack trace is available if I run the test from IDEA:
```
Using 8 worker leases.
Starting Build
Settings evaluated using settings file '/opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/settings.gradle'.
Projects loaded. Root project using build file '/opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/build.gradle'.
Included projects: [root project 'fai4n']

> Configure project :
Evaluating root project 'fai4n' using build file '/opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/build.gradle'.
All projects evaluated.
Selected primary task 'wrapper' from project :
Tasks to be executed: [task ':wrapper']
Tasks that were excluded: []
:wrapper (Thread[Execution worker for ':',5,main]) started.

> Task :wrapper
Caching disabled for task ':wrapper' because:
  Build cache is disabled
Task ':wrapper' is not up-to-date because:
  No history is available.
:wrapper (Thread[Execution worker for ':',5,main]) completed. Took 0.052 secs.

BUILD SUCCESSFUL in 87ms
1 actionable task: 1 executed
Starting build with: /opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/gradlew --no-daemon --stacktrace --gradle-user-home /opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/user-home --warning-mode=all -Dmaven.repo.local=/opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/m2-home-should-not-be-filled -Dorg.gradle.internal.repository.max.tentatives=1 hello
Working directory: /opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n
Environment vars:
    JAVA_HOME: /Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home
    GRADLE_HOME: 
    GRADLE_USER_HOME: null
    JAVA_OPTS: 
    GRADLE_OPTS: -Dorg.gradle.daemon.idletimeout=120000 "-Dorg.gradle.daemon.registry.base=/opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/daemon" -Dorg.gradle.native.dir=/opt/Development/git/gradle/gradle/intTestHomeDir/worker-1/native -Dorg.gradle.deprecation.trace=true -Dorg.gradle.internal.reuse.user.home.services=false -Djava.io.tmpdir=/opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp -Dfile.encoding=UTF-8 -Dorg.gradle.classloaderscope.strict=true -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false -ea -ea -Xms256m -Xmx512m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/Development/git/gradle/gradle/intTestHomeDir/worker-1
    GRADLE_RO_DEP_CACHE: 
Downloading http://127.0.0.1:53561/gradlew/dist

Exception in thread "main" java.io.IOException: Server returned HTTP response code: 407 for URL: http://127.0.0.1:53561/gradlew/dist
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:149)
	at org.gradle.wrapper.Download.download(Download.java:128)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

Gradle execution failed in /opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n with: /opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/gradlew [--no-daemon, --stacktrace, --gradle-user-home, /opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/user-home, --warning-mode=all, -Dmaven.repo.local=/opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/m2-home-should-not-be-filled, -Dorg.gradle.internal.repository.max.tentatives=1, hello]
Process ExecResult:
{exitValue=1, failure=null}
-----
Output:
Downloading http://127.0.0.1:53561/gradlew/dist


-----
Error:
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 407 for URL: http://127.0.0.1:53561/gradlew/dist
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:149)
	at org.gradle.wrapper.Download.download(Download.java:128)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

-----

org.gradle.integtests.fixtures.executer.UnexpectedBuildFailure: Gradle execution failed in /opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n with: /opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/gradlew [--no-daemon, --stacktrace, --gradle-user-home, /opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/user-home, --warning-mode=all, -Dmaven.repo.local=/opt/Development/git/gradle/gradle/subprojects/wrapper/build/tmp/test files/WrapperHttpIntegrationTest/downloads_wrapper_v...ted_proxy/fai4n/m2-home-should-not-be-filled, -Dorg.gradle.internal.repository.max.tentatives=1, hello]
Process ExecResult:
{exitValue=1, failure=null}
-----
Output:
Downloading http://127.0.0.1:53561/gradlew/dist


-----
Error:
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 407 for URL: http://127.0.0.1:53561/gradlew/dist
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:149)
	at org.gradle.wrapper.Download.download(Download.java:128)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

-----

	at org.gradle.integtests.fixtures.executer.ForkingGradleHandle.unexpectedBuildStatus(ForkingGradleHandle.java:240)
	at org.gradle.integtests.fixtures.executer.ForkingGradleHandle.waitForStop(ForkingGradleHandle.java:222)
	at org.gradle.integtests.fixtures.executer.ForkingGradleHandle.waitForFinish(ForkingGradleHandle.java:190)
	at org.gradle.integtests.fixtures.executer.NoDaemonGradleExecuter.doRun(NoDaemonGradleExecuter.java:201)
	at org.gradle.integtests.fixtures.executer.AbstractGradleExecuter.run(AbstractGradleExecuter.java:1074)
	at org.gradle.integtests.fixtures.executer.AbstractDelegatingGradleExecuter.doRun(AbstractDelegatingGradleExecuter.java:29)
	at org.gradle.integtests.fixtures.executer.AbstractGradleExecuter.run(AbstractGradleExecuter.java:1074)
	at org.gradle.integtests.WrapperHttpIntegrationTest.downloads wrapper via authenticated proxy(WrapperHttpIntegrationTest.groovy:166)


```

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy (hunk 3 above)
Comment (donat) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy:29]: I think if the test coverage is fixed then we can proceed with the merge.

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy (hunk 1 above)
Comment (sschuberth) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy]: > It seems to be a problem with the test itself (the proxy simply doesn't work).

But aren't the existing proxy-related tests in `master` supposed to pass?

Comment (donat) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy]: What I meant is that your changes probably broke the tests. They work properly on master.

Comment (donat) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy]: They do pass. We'll need to investigate why your tests fail.

Comment (donat) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy]: They do work. I'm not sure why it fails for your case, it needs to be investigated.

File: subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java [hunk 6]
```diff
@@ -55,12 +56,73 @@ public Download(Logger logger, DownloadProgressListener progressListener, String
...
+    private Authenticator getProxyPasswordAuthenticator() {
+        return new Authenticator() {
+            @Override
+            protected PasswordAuthentication getPasswordAuthentication() {
+                // While Java itself only defines the use of the "http(s).proxyHost" and "http(s).proxyPort" properties, see [1] for Java 8, the Apache HttpClient established the use of the
+                // "http(s).proxyUser" and "http(s).proxyPassword" properties, see [2], so support them here.
+                // [1] https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html#Proxies
+                // [2] https://hc.apache.org/httpcomponents-client-5.0.x/httpclient5/xref/org/apache/hc/client5/http/impl/auth/SystemDefaultCredentialsProvider.html#L117
+
+                String protocol = getRequestingScheme();
```
Comment (donat) [inline subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java:114]: ❌ `getRequestingScheme()` returns the authentication type (e.g. `basic`) instead of the protocol. Should be: 

```suggestion
                String protocol = getRequestingProtocol();
```

Comment (sschuberth) [reply subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java:114]: Thanks for catching this, fixed.

File: subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java [hunk 7]
```diff
@@ -55,12 +56,73 @@ public Download(Logger logger, DownloadProgressListener progressListener, String
...
+                System.setProperty(protocol + ".proxyUser", userAndPassword[0]);
+                if (userAndPassword.length > 1) {
+                    System.setProperty(protocol + ".proxyPassword", userAndPassword[1]);
+                }
+            }
+        } catch (MalformedURLException e) {
+            // Simply ignore a malformed proxy URL.
+            if (proxyString != null) {
+                logger.log("Unable to parse value '" + proxyString + "' of environment variable '" + variableName + "' as a URL.");
+                if (!proxyString.startsWith("http")) {
```
[the remark this answers is not in the document]
Comment (sschuberth) [reply subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java:92]: Actually, this should stay "http", as the *proxy's* protocol *for* HTTPS still is HTTP, also see https://stackoverflow.com/a/10442767/1127485.

File: subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java [hunk 8]
```diff
@@ -55,12 +56,73 @@ public Download(Logger logger, DownloadProgressListener progressListener, String
...
+        }
+
+        String variableName = protocol + "_proxy";
+        String proxyString = System.getenv(variableName);
+        if (proxyString == null) {
+            proxyString = System.getenv(variableName.toUpperCase());
+        }
+
+        try {
+            URL proxyUrl = new URL(proxyString);
```
[the remark this answers is not in the document]
Comment (sschuberth) [reply subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java:72]: I'll fix this later as I decided to drop that commit from this PR for simplicity. Because I would need to add support for `http(s)_proxy` environment variables also to the main Gradle, not just the wrapper.

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy (hunk 1 above)
Comment (sschuberth) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpsIntegrationTest.groovy]: My guess is that `WrapperHttpsIntegrationTest` fails because the used [LittleProxy](https://github.com/adamfisk/LittleProxy) library does not support a HTTPS proxy.

**Comment by sschuberth** [comment]
@donat @big-guy I've reworked the PR from the ground up to address your comment, fix failing tests, and keep changes to a minimum. Thanks for your input. Please have a new look now.

File: subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_repositories.adoc [hunk 9]
```diff
@@ -661,7 +661,7 @@ A proxy for S3 can be configured using the following system properties:
 * `https.proxyPort`
 * `https.proxyUser`
 * `https.proxyPassword`
-* `https.nonProxyHosts`
+* `http.nonProxyHosts`
```
Comment (donat) [inline subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_repositories.adoc:664]: ⭕ This might be an accidental change?

File: subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc [hunk 10]
```diff
@@ -259,7 +259,7 @@ systemProp.https.proxyHost=www.somehost.org
 systemProp.https.proxyPort=8080
 systemProp.https.proxyUser=userid
 systemProp.https.proxyPassword=password
-systemProp.https.nonProxyHosts=*.nonproxyrepos.com|localhost
+systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhost
```
Comment (donat) [inline subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc:262]: ⭕ Accidental change?

File: subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java [hunk 11]
```diff
@@ -52,13 +52,9 @@ public Download(Logger logger, DownloadProgressListener progressListener, String
...
         this.progressListener = new DefaultDownloadProgressListener(logger, progressListener);
-        configureProxyAuthentication();
-    }
 
-    private void configureProxyAuthentication() {
-        if (System.getProperty("http.proxyUser") != null) {
-            Authenticator.setDefault(new ProxyAuthenticator());
-        }
+        // Only an authenticator for proxies needs to be set. Basic authentication is supported by directly setting the request header field.
+        Authenticator.setDefault(new ProxyAuthenticator());
```
Comment (donat) [inline subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java:57]: Just to be on the safe side, I'd set the global authenticator if necessary.
```suggestion
       if (System.getProperty("http.proxyUser") != null || System.getProperty("https.proxyUser") != null) {
            Authenticator.setDefault(new ProxyAuthenticator());
        }```

**Comment by donat** [comment]
CI build scheduled: https://builds.gradle.org/viewQueued.html?itemId=35266195

**Comment by sschuberth** [comment]
> I only have one minor suggestion.

Thanks for adding the `if`-statement yourself. But doesn't the SHA256 of the wrapper need to be updated afterwards again (i.e. the order of your commits be swapped)?

**Comment by sschuberth** [comment]
> > I only have one minor suggestion.
> 
> Thanks for adding the `if`-statement yourself. But doesn't the SHA256 of the wrapper need to be updated afterwards again (i.e. the order of your commits be swapped)?

I've fixed up my PR in that regard once more.

**Comment by donat** [comment]
@sschuberth Thank you for your contribution!

**Comment by sschuberth** [comment]
Thanks for your patience with the review iterations :smile:
