### PR TITLE
Fix some corner cases in input tracking

### LINKED ISSUE #22305: Custom ValueSource erroneously tracks files etc used in obtain() when ValueSource parameters are passed in
When creating a custom ValueSource with parameters, and using other ValueSource instances for those parameters, the inputs are erroneously tracked.

### Expected Behavior
As documented, ValueSource implementations should not track files, environment variables, etc.

### Current Behavior
Gradle erroneously tracks ValueSource inputs, resulting in unexpectedly dirty configuration caches.

### Context
This causes the configuration cache to miss 100% of the time.

  This is due to a collision of events:
     - Gradle fingerprints the input parameters to the ValueSource;
     - this results in beforeValueObtained() event being fired, which DISABLES input tracking
     - ...and then afterValueObtained() is fired, which ENABLES input tracking, just in time to drop into the obtain()
       method of our custom ValueSource

### Steps to Reproduce 
Reproduced [here](https://github.com/cloudshiftinc/repro-gradle-configuration-cache-value-source).  Consistently reproducible in configurations where a ValueSource is used as a parameter to a ValueSource

### Your Environment
MacOS, Gradle 7.5.1, Java 17

### PR DESCRIPTION
**Pull request by mlopatkin**
This PR addresses some discrepancies in how the configuration cache input tracking works inside the ValueSource and `buildscan.background` callback. Prior:
1. `ValueSource.obtain` was complaining about the use of the standard Java process API
2. `buildscan.background` was complaining about the use of `ExecOperations`.

The discrepancy was coming from the fact that there were two ways of disabling input tracking - removing the instrumentation "interceptor" temporarily (used by `background`), and ignoring the calls in the input listener in the `ConfigurationCacheFingerprintWriter` (used by ValueSource). This PR removes the first way, extracts the state of the input tracking into a separate `InputTrackingState` class, and switches `background` to use this new class. Additionally, as the external process warning is closely tied to the input tracking, the `ConfigurationCacheProblemsListener` also takes input tracking state into account when deciding whether to emit a problem if an external process is started.

The remaining corner cases are related to ValueSources evaluated at the configuration time. Evaluating a value source inside the `background` block may still make this source a configuration input. The workaround is to use Java APIs directly to obtain the value instead.

Fixes #22305

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle cancel

**Comment by mlopatkin** [comment]
@bot-gradle test RfR

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt [hunk 1]
```diff
@@ -258,18 +262,19 @@ class ConfigurationCacheFingerprintWriter(
...
 
     override fun beforeValueObtained() {
-        inputTrackingDisabledForThread = true
+        // Do not track additional inputs while computing a value of the value source.
+        inputTrackingState.disableForCurrentThread()
     }
 
     override fun afterValueObtained() {
-        inputTrackingDisabledForThread = false
+        inputTrackingState.enableForCurrentThread()
```
Comment (bamboo) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt:277]: ❓ Won't this cause input tracking to be re-enabled unconditionally after a value is obtained even when input tracking was already disabled before the value was obtained? I wonder if such scenario even exists 🤔

Comment (mlopatkin) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt]: It exists: #22305. I was pushing this to the overall fix of obtaining a value source inside the untracked block, but this can be solved separately. I filed #22494 to track the rest. It seems to be too involved for 7.6 line, as it includes serialization changes we discussed last week.

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle test RfR

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheValueSourceIntegrationTest.groovy [hunk 2]
```diff
@@ -292,4 +295,76 @@ class ConfigurationCacheValueSourceIntegrationTest extends AbstractConfiguration
...
+        """
+
+        when:
+        configurationCacheRun("-Dsome.property=1", "-Dmy.property=value")
+
+        then:
+        configurationCache.assertStateStored()
+        outputContains("result = value1")
+        problems.assertResultHasProblems(result) {
+            withInput("Build file 'build.gradle': system property 'some.property'")
```
Comment (bamboo) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheValueSourceIntegrationTest.groovy:333]: ❓ I assume this will no longer be the case (`some.property` being an input) once https://github.com/gradle/gradle/issues/22305 is fixed?

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InputTrackingState.kt [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+     */
+    fun restoreForCurrentThread() {
+        Preconditions.checkState(inputTrackingDisabledCounterForThread > 0, "Restore input tracking state without prior disable is detected")
+        --inputTrackingDisabledCounterForThread
+    }
+}
+
+
+private
+operator fun <T> ThreadLocal<T>.getValue(thisRef: Any?, property: KProperty<*>) = get()
```
Comment (bamboo) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InputTrackingState.kt:64]: 🎨 Consider moving extensions to `org/gradle/configurationcache/extensions/ThreadLocalExtensions.kt` for easy discovery.

File: subprojects/core/src/testFixtures/groovy/org/gradle/process/ShellScript.groovy [hunk 4]
```diff
@@ -178,7 +178,7 @@ abstract class ShellScript {
 
         @Override
         Builder printText(String text) {
-            return addLine("echo \"$text\"")
+            return addLine("echo $text")
```
Comment (bamboo) [inline subprojects/core/src/testFixtures/groovy/org/gradle/process/ShellScript.groovy:181]: ❓ AFAICT the behavior will be different when `text` includes newlines. Is this as intended?

Comment (mlopatkin) [reply subprojects/core/src/testFixtures/groovy/org/gradle/process/ShellScript.groovy:181]: It wouldn't work with newlines either way. On Windows, the previous line was just printing out quotes. Looks like I never had a test to verify if the output is unquoted before.

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheValueSourceIntegrationTest.groovy (hunk 2 above)
Comment (mlopatkin) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheValueSourceIntegrationTest.groovy:333]: No, we'll need #22494 for that. This PR fixes #22305 which is essentially "all inputs are now tracked in my `ValueSource.obtain()` implementation after I called `parameters.myParam.get()`".  Without the fix, we'd also have `system property my.property` as an input.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InputTrackingState.kt (hunk 3 above)
Comment (mlopatkin) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InputTrackingState.kt:64]: Will do, thanks

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheValueSourceIntegrationTest.groovy (hunk 2 above)
Comment (bamboo) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheValueSourceIntegrationTest.groovy:333]: Got it, thanks.

**Comment by mlopatkin** [comment]
@bot-gradle test and merge
