### PR TITLE
Ignore artifact transforms when resolving Task.getTaskDependencies()

### LINKED ISSUE #6156: Cannot resolve task dependencies when task has transformed artifacts as inputs
In Gradle 4.8 and earlier, it was possible to query a task's dependencies with `task.getTaskDependencies().getDependencies(task)`. In Gradle 4.9, it produces this error: `Cannot resolve object of unknown type ArtifactTransformDependency to a Task` when the task has transformed artifacts as inputs.

### PR DESCRIPTION
**Pull request by lptr**
The TaskDependency API will be deprecated, because it has numerous shortcomings, including the inability to express dependencies that are not tasks. Until then we need a way to handle artifact transform dependencies. This commit introduces a change that allows ignoring these dependencies when resolving via TaskDependency.

Fixes #6156.

### CODE REVIEW

**Comment by lptr** [comment]
Branch build: https://builds.gradle.org/viewQueued.html?itemId=14634254

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/AbstractTaskDependency.java [hunk 1]
```diff
@@ -16,18 +16,29 @@
...
+import org.gradle.api.internal.artifacts.transform.ArtifactTransformDependency;
 
 import javax.annotation.Nullable;
-import java.util.Collections;
+import java.util.Arrays;
 import java.util.Set;
 
 @NonNullApi
 public abstract class AbstractTaskDependency implements TaskDependencyInternal {
+    private static WorkDependencyResolver<Task> ARTIFACT_TRANSFORM_RESOLVER = new WorkDependencyResolver<Task>() {
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/AbstractTaskDependency.java]: How about we call this `IGNORE_ARTIFACT_TRANSFORM_RESOLVER`?

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy [hunk 2]
```diff
@@ -1717,6 +1718,51 @@ Found the following transforms:
...
+                }
+            }
+        """
+
+        when:
+        run "dependent"
+
+        then:
+        output.count("> Dependency:") == 1
+        output.contains("> Dependency: task ':app:resolve'")
```
Comment (wolfs) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy]: Can we check that `resolve` and the artifact transform actually executed?

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy [hunk 3]
```diff
@@ -1717,6 +1718,51 @@ Found the following transforms:
...
+                ${configurationAndTransform()}
+
+                task dependent {
+                    dependsOn resolve
+                }
+            }
+
+            gradle.taskGraph.whenReady { taskGraph ->
+                taskGraph.allTasks.each { task ->
+                    task.taskDependencies.getDependencies(task).each { dependency ->
```
Comment (wolfs) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy]: Would it be interesting to print out `task`, too? So we would know that `dependent` depends on `resolve`?

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/AbstractTaskDependency.java (hunk 1 above)
Comment (lptr) [reply subprojects/core/src/main/java/org/gradle/api/internal/tasks/AbstractTaskDependency.java]: Good point.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy (hunk 2 above)
Comment (lptr) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy]: Why is that important for this test? We have plenty of other tests to check this behavior.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy (hunk 3 above)
Comment (lptr) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy]: Let's do that...

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy (hunk 2 above)
Comment (wolfs) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy]: It is important that the artifact transform and `resolve` are part of the task graph. If they aren't, then the test would not check what we expect it to check.
