### PR TITLE
Changes in case for input files causes Sync tasks to fail

### LINKED ISSUE #9586: Changes in case for input files causes Sync tasks to fail
On case-insensitive filesystems (Windows, macOS-sometimes), a change in the case of an input file is seen as a change, but causes `Sync` tasks to fail to populate the destination directory properly.

### Expected Behavior
Gradle syncs all input files.

### Current Behavior
Gradle does not sync the proper files.

### Steps to Reproduce 
```
task writeFile {
    def outputFile = new File(buildDir, project.hasProperty("capitalize") ? "OUTPUT" : "output")
    outputs.file outputFile
    doLast {
        outputFile.text = "hello"
    }
}
task sync(type: Sync) {
    from writeFile
    into new File(buildDir, "sync")
}
```

The first build works (`gradle sync`).
The second build with changed case (`gradle sync -Pcapitalize`) fails with an empty `build/sync` directory.

### Your Environment
Occurs on macOS (with case-insensitive filesystems) and Windows.

### PR DESCRIPTION
**Pull request by paplorinc**
Fixes #9586

This is the follow-up of https://github.com/gradle/gradle/pull/9625, based on the file permission related concerns expressed by @lptr in https://github.com/gradle/gradle/pull/9625#issuecomment-500203675

Unlike the original PR, we're not deleting everything and copying after, rather if we detect case change, we rename the file/folder explicitly, since the copy is done via streams, not OS specific copy.

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyAction.java [hunk 1]
```diff
@@ -47,7 +48,7 @@ public File processFile(FileCopyDetailsInternal details) {
             if (copied) {
                 didWork = true;
             }
-            return null;
+            return FileUtils.canonicalize(target);
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyAction.java]: target's case is the new case, but the copy doesn't actually change it on disk.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/SyncCopyActionDecorator.java [hunk 2]
```diff
@@ -53,16 +52,16 @@ public SyncCopyActionDecorator(File baseDestDir, CopyAction delegate, PatternFil
...
-        final Set<RelativePath> visited = new HashSet<RelativePath>();
+        final Set<File> visited = new HashSet<>();
 
         WorkResult didWork = delegate.execute(new CopyActionProcessingStream() {
             @Override
             public void process(final CopyActionProcessingStreamAction action) {
                 stream.process(new CopyActionProcessingStreamAction() {
                     @Override
                     public File processFile(FileCopyDetailsInternal details) {
-                        visited.add(details.getRelativePath());
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/SyncCopyActionDecorator.java]: tracks relative path

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/SyncCopyActionDecorator.java [hunk 3]
```diff
@@ -53,16 +52,16 @@ public SyncCopyActionDecorator(File baseDestDir, CopyAction delegate, PatternFil
...
-                        action.processFile(details);
+                        File copy = action.processFile(details);
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/SyncCopyActionDecorator.java]: tracks copied over file, with canonicalized name

File: subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy [hunk 4]
```diff
@@ -394,36 +393,71 @@ class SyncTaskIntegrationTest extends AbstractIntegrationSpec {
...
+        succeeds('syncIt', '-PcapitalizeFile')
+        def uppercaseOutputFile = file('build/FILE.TXT')
         then:
-        file("build/output").assertExists()
-        file("build/sync/output").assertExists()
+        executedAndNotSkipped ':syncIt'
+        uppercaseOutputFile.parentFile.listFiles() != [].toArray()
+        uppercaseOutputFile.assertExists()
+        uppercaseOutputFile.text == 'FILE'
+        // TODO uppercaseOutputFile.canonicalFile.name == 'FILE.TXT'
```
Comment (paplorinc) [inline subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: @lptr, should we add some custom logic that if the filename differs, do an actual delete and recreate?

File: subprojects/core/src/main/java/org/gradle/api/internal/file/CopyActionProcessingStreamAction.java [hunk 5]
```diff
@@ -18,8 +18,10 @@
 
 import org.gradle.api.internal.file.copy.FileCopyDetailsInternal;
 
+import java.io.File;
+
 public interface CopyActionProcessingStreamAction {
 
-    void processFile(FileCopyDetailsInternal details);
+    File processFile(FileCopyDetailsInternal details);
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/CopyActionProcessingStreamAction.java]: this change seems to be causing plugin failure, e.g. https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy#L86

Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/CopyActionProcessingStreamAction.java]: Fixed

File: subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy (hunk 4 above)
Comment (paplorinc) [reply subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: Done

File: subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy [hunk 6]
```diff
@@ -394,36 +393,71 @@ class SyncTaskIntegrationTest extends AbstractIntegrationSpec {
...
+            file('file4.txt') << 'file4'
+        }
+        and:
+        succeeds('sync', '-PcapitalizeDir')
         then:
-        file("build/OUTPUT").assertExists()
-        // TODO: This should exist
-        file("build/sync/OUTPUT").assertDoesNotExist()
+        executedAndNotSkipped ':syncIt'
+        file('build/file4.txt').canonicalFile.name == 'file4.txt'
```
Comment (wolfs) [inline subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: There is some test coverage missing when the case of a directory changes. For that you would need to create a sub-directory in `DIR` and then change its case. I guess the task will fail if the directory contains some files.

What should we do in this case?

Comment (paplorinc) [reply subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: I am changing the case of `dir` to `DIR` (couldn't use rename, had to delete and recreate to make sure the case is changed correctly) in https://github.com/gradle/gradle/pull/9663/files/3bba35426f9a9faec675b3b00e22883d531030fb#diff-98f85d28fc88be35783c5f9ab2192e19R453

Comment (wolfs) [reply subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: Yes, you are changing the case of `dir` to `DIR`, though you don't sync the directory, you only sync files in the directory. That means that no dir with a case change is in the output directory.

Comment (paplorinc) [reply subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: Understood, added a case to handle it.
Also changed fs delete to fs rename, seems less invasive.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyAction.java [hunk 7]
```diff
@@ -43,10 +45,20 @@ public WorkResult execute(CopyActionProcessingStream stream) {
...
+            renameIfCaseChanged(target);
             boolean copied = details.copyTo(target);
             if (copied) {
                 didWork = true;
             }
         }
+
+        private void renameIfCaseChanged(File target) {
+            if (target.exists()) {
+                File canonicalizedTarget = FileUtils.canonicalize(target);
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyAction.java]: should I attempt a rename instantly, if it exists, or only if the nanonical is different?

File: subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy [hunk 8]
```diff
@@ -394,36 +393,85 @@ class SyncTaskIntegrationTest extends AbstractIntegrationSpec {
...
+        file('build/NESTEDDIR/NESTEDDIRFILE.TXT').with {
+            assert it.exists(): it.parentFile.list()
+            assert it.canonicalFile.name == 'NESTEDDIRFILE.TXT'
+            assert it.text == 'NESTEDDIRFILE'
```
Comment (wolfs) [inline subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: I think we also need to check that `build/NESTEDDIR` has the correct case.

Does this work now since you changed from delete to rename? When using delete, I would expect the method to fail since the directory is not empty. Actually, it would return `false`, right?

File: subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy (hunk 6 above)
Comment (paplorinc) [reply subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: Validated on Mac, Windows and Linux

File: subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy (hunk 8 above)
Comment (paplorinc) [reply subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: Done.

Yes, I would need either `FileUtils.forceDelete` or `renameTo`.

**Comment by paplorinc** [comment]
Merged, thanks! :)

File: subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy [hunk 9]
```diff
@@ -394,36 +393,86 @@ class SyncTaskIntegrationTest extends AbstractIntegrationSpec {
         ins.close()
     }
 
-    @ToBeImplemented
     @Issue("https://github.com/gradle/gradle/issues/9586")
-    @Requires(TestPrecondition.CASE_INSENSITIVE_FS)
-    def "change in case of input file still syncs properly"() {
+    def "change in case of input files and folders will still syncs properly"() {
```
Comment (paplorinc) [inline subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: * change file case only without content
* break it up into smaller once (single file / directory rename)

File: subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy [hunk 10]
```diff
@@ -394,36 +393,86 @@ class SyncTaskIntegrationTest extends AbstractIntegrationSpec {
...
+            assert it.assertExists()
+            assert it.text == 'FILE'
+            assert it.canonicalFile.name == 'FILE.TXT'
+        }
+        and:
+        file('build/file2.txt').assertExists()
+        file('build/file3.txt').assertDoesNotExist()
+        file('build/File4.txt').with {
+            it.assertExists()
+            it.canonicalFile.name == 'File4.txt'
```
Comment (paplorinc) [inline subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: oups...

Comment (paplorinc) [reply subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: Fixed

File: subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy (hunk 9 above)
Comment (paplorinc) [reply subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy]: Fixed
