### PR TITLE
Fix empty directory normalization with artifact transforms and configuration cache

### LINKED ISSUE #15426: Empty directory normalization for artifact transforms doesn't work with configuration cache
Empty directory normalization on the input artifact of an artifact transform is currently ignored when the configuration cache is enabled.  This is because the directory sensitivity parameters are transposed on one of the constructors of `DefaultTransform`.

Ironically, this was masked by a separate issue in the integration test that should have caught this.

### PR DESCRIPTION
**Pull request by ghale**
Fixes #15426 

Also cleans up a few cosmetic details from the initial implementation.

### CODE REVIEW

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDirectorySensitivityIntegrationSpec.groovy [hunk 1]
```diff
@@ -483,7 +479,7 @@ abstract class AbstractDirectorySensitivityIntegrationSpec extends AbstractInteg
                 @Override
                 void transform(TransformOutputs outputs) {
                     File zippedFile = getZippedFile().get().getAsFile()
-                    File unzipDir = outputs.dir(zippedFile.getName())
+                    File unzipDir = outputs.dir(zippedFile.getName() + "/unzipped")
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDirectorySensitivityIntegrationSpec.groovy:482]: Why is this now in the `/unzipped` subdirectory? Is this important for the test?

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDirectorySensitivityIntegrationSpec.groovy [hunk 2]
```diff
@@ -390,13 +386,13 @@ abstract class AbstractDirectorySensitivityIntegrationSpec extends AbstractInteg
 
                     System.out.println "Augmenting..."
                     fileSystemOperations.copy {
-                        from input
-                        into augmentedDir
+                        it.from input
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDirectorySensitivityIntegrationSpec.groovy:389]: This seems to be a bug with configuration caching. I'll raise it with the team.

**Review by wolfs — APPROVED** [review]
LGTM!

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDirectorySensitivityIntegrationSpec.groovy (hunk 2 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDirectorySensitivityIntegrationSpec.groovy:389]: I opened https://github.com/gradle/gradle/issues/15429.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDirectorySensitivityIntegrationSpec.groovy (hunk 1 above)
Comment (ghale) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDirectorySensitivityIntegrationSpec.groovy:482]: It's not important, it just makes it easier to identify when debugging/troubleshooting since it's more clear that this is the unzipped output directory.  That's all.

Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDirectorySensitivityIntegrationSpec.groovy:482]: 👍
