### PR TITLE
Treat non-existing files as regular files when detecting missing task dependencies

### LINKED ISSUE #16980: False positive for implicit dependency deprecation warning
### Expected Behavior
The following project should build without warnings.

### Current Behavior
The following is printed:
```
Execution optimizations have been disabled for task ':someSourceProcessor' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/octy/Documents/gradle-not-really-a-dependency/build/myGeneratedOutput'. Reason: Task ':someSourceProcessor' uses this output of task ':someCodeGenerator' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

### Context
This occurs normally when I add some generated output from e.g. [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin) to the `main` source set. Then I exclude the generated output from my licenser plugin, but Gradle still reports the above warning.

I think this is incorrect behavior because now that I have excluded the elements, the `someSourceProcessor` task does not depend on the `someCodeGenerator` task to work properly.

### Steps to Reproduce 
The following Gist is sufficient to reproduce the problem. Running the `build` task will do it.
https://gist.github.com/octylFractal/a5f0fa0db12324d8b28bf3896ac8e3c9

### Your Environment
Build scan URL: https://scans.gradle.com/s/zqlcff2qryk3i

### LINKED ISSUE #17561: Gradle erroneously detects missing task dependency between missing output file and input filter containing **
Copied from #16980 and originally reported by @m-koops:

And here I have another small sample demonstrating the false positive.  It turns out the warning is triggered as soon as both tasks foo and bar get a filetree as input, although each task has a different filetree. Without the inputs, no warning.

```
val foo by tasks.registering() {
    description = "Foo"

    inputs.files(fileTree(projectDir) {
        include("**/*.foo")
    })
    val reportPath = "${buildDir}/foo.txt"
    outputs.file(reportPath)

    doLast {
        println("foo")
        file(reportPath).writeText("foo")
    }
}

val bar by tasks.registering() {
    description = "Bar"

    inputs.files(fileTree(projectDir) {
        include("**/*.bar")
    })
    val reportPath = "${buildDir}/bar.txt"
    outputs.file(reportPath)

    doLast {
        println("bar")
        file(reportPath).writeText("bar")
    }
}

val fooBar by tasks.registering {
    dependsOn(foo, bar)
}
```

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by wolfs**
This allows excluding/including non-existing files via `**/...` patterns.

Fixes #17561

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test this

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy [hunk 1]
```diff
@@ -407,6 +407,43 @@ class MissingTaskDependenciesIntegrationTest extends AbstractIntegrationSpec imp
         executedAndNotSkipped(":produceInBuild", ":showSources")
     }
 
+    @Issue("https://github.com/gradle/gradle/issues/16980")
+    def "missing dependency detection takes ** excludes for non-existing files into account"() {
+        file("src/main/java/my/JavaClass.java").text = """
+            package my;
+
+            public class JavaClass {}
+        """
```
Comment (lptr) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy:416]: Why is this source file needed?

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy [hunk 2]
```diff
@@ -407,6 +407,43 @@ class MissingTaskDependenciesIntegrationTest extends AbstractIntegrationSpec imp
...
+                outputs.file(reportPath)
+                doLast {
+                    reportPath.text = "bar"
+                }
+            }
+
+            task allReports {
+                dependsOn(fooReport, barReport)
+            }
+        """
```
Comment (lptr) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy:439]: To me this example is less understandable than what the user uploaded. After some investigation now I understand how these inputs produce a similar situation, but I think we can do something where the problem is more obvious to the reader.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy [hunk 3]
```diff
@@ -407,6 +407,43 @@ class MissingTaskDependenciesIntegrationTest extends AbstractIntegrationSpec imp
         executedAndNotSkipped(":produceInBuild", ":showSources")
     }
 
+    @Issue("https://github.com/gradle/gradle/issues/16980")
+    def "missing dependency detection takes ** excludes for non-existing files into account"() {
```
Comment (lptr) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy:411]: I'm having trouble understanding the problem from this title. How about:

```suggestion
    def "missing task dependency detection does not trigger for excluded non-existing files"() {
```

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy (hunk 1 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy]: It isn't, good catch.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy (hunk 2 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy:432]: This PR is actually fixing the problem from the second comment on the issue. I extracted the comment to its own issue: #17561

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy (hunk 3 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy:411]: I think the original name is better.

**Comment by wolfs** [comment]
@lptr PTAL!

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by wolfs** [comment]
@bot-gradle test and merge
