### PR TITLE
Fix renaming project directory causing lost file system notifications on Windows

### LINKED ISSUE #17865: Renaming and recreating the project directory causes Gradle to lose track of changes on Windows
In one build we've seen Gradle fail to compile a subproject (`:build-agent-maven-test-distribution:compileJava`) because it ended up compiling against an outdated version of classes for one of the dependency subprojects (`:test-distribution-client`).

This is a serious issue as it affects build reliability. Here's the result of a very long investigation about how that happened:

* We ended up with the wrong classes because we loaded the results for `:test-distribution-client:compileJava` with the wrong cache key (`3be04def081300037cfdc35044441cae`) – ([scan link](https://e.grdev.net/s/z6q3tbdyamipo/timeline?details=rgqtrv2jfgkg2&expanded=WyIxMyJd&task-path=test-distribution-client)).
* The cache key matched the cache key (correctly) calculated by a previous build on the same daemon that was actually compiling against the earlier version of the source code.
* In the failing build we used the same (but now incorrect) cache key because Gradle believed that the sources were unchanged compared to the previous build, but they were actually different.
* This happened because we did not get notifications when the new version of the source code was checked out by Git.

So how did we miss these notifications?

It turns out that we've been using a TeamCity pluing called [Build Files Cleaner (Swabra)](https://www.jetbrains.com/help/teamcity/build-files-cleaner-swabra.html) in that specific build. The purpose of this plugin seems to be to restore build checkout directories to their original state before a new build is started. Swabra does two strange things.

First, on Windows, Swabra uses `cmd.exe /c rd /s /q <directory>` to delete some stuff. Doing so actually results in changes being reported via their short paths (stuff like `build\classes\java\main\com\gradle\ENTERP~1\app\rpc\client\HTTPRP~1.CLA`). This was a feature introduced in Windows 95 to support long file names on FAT, but apparently even files on NTFS have short names, and that's what is used to report changes to them if you use `rd`. (We might need to follow up on this, but it ended up being a red herring wrt this issue; see https://github.com/gradle/native-platform/pull/289.)

Secondly, and this will be important, the previous build of the same project on the same machine failed to check out from Git. Most probably because there was a forced push to the PR or something. The assumption is that this circumstance resulted in Swabra losing track of things, and deleting the checkout directory:

```text
17:29:20 Swabra
17:29:20   Checkout directory state is unknown. Need a clean checkout directory snapshot - forcing clean checkout
17:29:20 Clearing temporary directory: C:\tcagent1\temp\buildTmp
17:29:20 Failed to delete file: C:\tcagent1\temp\buildTmp\hsperfdata_tcagent1\10968
17:29:20 Failed to delete file: C:\tcagent1\temp\buildTmp\hsperfdata_tcagent1\15552
17:29:20 Failed to delete file: C:\tcagent1\temp\buildTmp\hsperfdata_tcagent1\4332
17:29:20 Unable to cleanup build temporary directory: C:\tcagent1\temp\buildTmp
```

https://builds.gradle.org/buildConfiguration/Enterprise_Master_Component_MavenTestDistributionExtension_CrossVersion_GroupRecentWindows/45017572?buildTab=log&focusLine=42&linesState=38.42

What happened here was that Swabra deleted the whole checkout directory (`C:\tcagent1\work\8d3306ac5f39e07b`), which is also the project root, and thus the directory Gradle was watching. Doing so should have been reported to Gradle, which should have invalidate the relevant parts of the VFS, but that clearly didn't happen. Why?

The first impression was that this might be related to the short paths being reported when deleting directories via `cmd.exe /c rd ...`, but it turns out that the root of the deletion is still reported via its long path, so that's not it. It turns out that Swabra uses a different way to delete the whole checkout directory in this case...

https://github.com/JetBrains/teamcity-swabra/blob/a6f46f3050c8fb7e71c5d40a871af19eb8152d45/agent/src/jetbrains/buildServer/swabra/Swabra.java#L453-L462

Long story short, **Swabra ends up first renaming the checkout directory, and then deleting it**.

Now, Windows curiously does not send any notification about the watched directory being renamed, even though it _would_ send a notification if it was deleted. So Gradle stays ignorant of the fact that the project root was moved. Even more curiously, that's still not the cause of our issue, as when the directory is deleted, even in its new location, `native-platform` still reports the events using the original location. So we end up with Gradle learning about the original location being deleted. So _then_ what?

Close inspection of the logs above shows that in the build in question, Swabra _failed_ to delete some content in the renamed directory, and hence it did not end up deleting the relocated project directory. In turn, Gradle did not get the notification about the watched directory being deleted (correctly, as it hasn't been), and we kept watching it in its new location (`C:\tcagent1\temp\buildTmp`). However, Gradle keeps thinking that it is watching the project in the old location (`C:\tcagent1\work\8d3306ac5f39e07b`).

And then TeamCity re-creates the checkout directory (`C:\tcagent1\work\8d3306ac5f39e07b`) and populates it by checking out the code afresh. And while Gradle _thinks_ it watches that location, there are no notifications being sent.

Later, when Gradle is invoked to build `C:\tcagent1\work\8d3306ac5f39e07b` again in the same daemon, it thinks whatever is remaining in its VFS is still valid, and does not detect that the source code for `:test-distribution-client` has been changed.

There.

---
cc: @gradle/execution, @paplorinc

### PR DESCRIPTION
**Pull request by lptr**
Fixes #17865

Bumps `native-platform` to include:
- https://github.com/gradle/native-platform/pull/290
- https://github.com/gradle/native-platform/pull/292
- https://github.com/gradle/native-platform/pull/293

To be backported to Gradle 6.9.1.

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test RFM please.

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java [hunk 1]
```diff
@@ -31,23 +31,23 @@
 import java.util.concurrent.TimeUnit;
 import java.util.function.Predicate;
 
-public class DarwinFileWatcherRegistryFactory extends AbstractFileWatcherRegistryFactory<OsxFileEventFunctions> {
+public class DarwinFileWatcherRegistryFactory extends AbstractFileWatcherRegistryFactory<OsxFileEventFunctions, OsxFileWatcher> {
```
Comment (wolfs) [inline subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java:34]:
```suggestion
public class OsxFileWatcherRegistryFactory extends AbstractFileWatcherRegistryFactory<OsxFileEventFunctions, OsxFileWatcher> {
```

Should we rename this, so the names for macOS align better?

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java [hunk 2]
```diff
@@ -39,14 +45,22 @@ public WindowsFileWatcherRegistryFactory(WatchableFileSystemDetector watchableFi
...
-    protected FileWatcherUpdater createFileWatcherUpdater(FileWatcher watcher, WatchableHierarchies watchableHierarchies) {
-        return new HierarchicalFileWatcherUpdater(watcher, NO_VALIDATION, watchableHierarchies);
+    protected FileWatcherUpdater createFileWatcherUpdater(WindowsFileWatcher watcher, WatchableHierarchies watchableHierarchies) {
+        return new HierarchicalFileWatcherUpdater(watcher, NO_VALIDATION, watchableHierarchies, root -> invalidateMovedPaths(watcher, root));
+    }
+
+    private static SnapshotHierarchy invalidateMovedPaths(WindowsFileWatcher watcher, SnapshotHierarchy root) {
+        for (File movedPath : watcher.stopWatchingMovedPaths()) {
+            LOGGER.info("Dropping VFS state for moved path {}", movedPath.getAbsolutePath());
+            root = root.invalidate(movedPath.getAbsolutePath(), SnapshotHierarchy.NodeDiffListener.NOOP);
```
Comment (wolfs) [inline subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java:62]: Don't we need to update the watchers after invalidating parts of the VFS? I'd at least expect that we tell the watcher updater that we are not watching the moved path any more.

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java [hunk 3]
```diff
@@ -92,6 +94,11 @@ public void registerWatchableHierarchy(File watchableHierarchy, SnapshotHierarch
         updateWatchedHierarchies(root);
     }
 
+    @Override
+    public SnapshotHierarchy buildStarted(SnapshotHierarchy root) {
+        return movedHierarchyHandler.handleMovedHierarchies(root);
```
Comment (wolfs) [inline subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java:99]: Don't we need to update the watchers after invalidating parts of the VFS? I'd at least expect that we tell the watcher updater that we are not watching the moved path any more.

I think a good way would be to call `updateWatchedHierarchies` if the new root is different.

File: subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy [hunk 4]
```diff
@@ -169,4 +171,72 @@ class ChangesBetweenBuildsFileSystemWatchingIntegrationTest extends AbstractFile
...
+    @Issue("https://github.com/gradle/gradle/issues/17865")
+    def "project directory moved is handled properly"() {
+        def buildCache = new TestBuildCache(temporaryFolder.file("cache-dir").deleteDir().createDir())
+        def buildFileContents = """
+            apply plugin: "base"
+
+            @CacheableTask
+            abstract class CustomTask extends DefaultTask {
+                @InputFile
+                @PathSensitive(PathSensitivity.RELATIVE)
```
[the remark this answers is not in the document]
Comment (lptr) [reply subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy:184]: OK, though it doesn't really matter for this test.

File: subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy [hunk 5]
```diff
@@ -169,4 +171,72 @@ class ChangesBetweenBuildsFileSystemWatchingIntegrationTest extends AbstractFile
...
+                abstract RegularFileProperty getSource()
+
+                @OutputFile
+                abstract RegularFileProperty getTarget()
+
+                @TaskAction
+                def execute() {
+                    def content = source.get().asFile.text
+                    println content
```
[the remark this answers is not in the document]
Comment (lptr) [reply subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy:193]: OK.

File: subprojects/distributions-dependencies/build.gradle.kts [hunk 6]
```diff
@@ -21,7 +21,7 @@ val jacksonVersion = "2.12.1"
 val jaxbVersion = "3.0.0"
 val jettyVersion = "9.4.36.v20210114"
 val mavenVersion = "3.6.3"
-val nativePlatformVersion = "0.22-milestone-18"
+val nativePlatformVersion = "0.22-snapshot-20210802202501+0000"
```
[the remark this answers is not in the document]
Comment (lptr) [reply subprojects/distributions-dependencies/build.gradle.kts:24]: Yes, it's being published right now.

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java [hunk 7]
```diff
@@ -61,12 +61,14 @@
 
     private final FileSystemLocationToWatchValidator locationToWatchValidator;
     private final WatchableHierarchies watchableHierarchies;
+    private final MovedHierarchyHandler movedHierarchyHandler;
     private final WatchedHierarchies watchedHierarchies = new WatchedHierarchies();
 
-    public HierarchicalFileWatcherUpdater(FileWatcher fileWatcher, FileSystemLocationToWatchValidator locationToWatchValidator, WatchableHierarchies watchableHierarchies) {
+    public HierarchicalFileWatcherUpdater(FileWatcher fileWatcher, FileSystemLocationToWatchValidator locationToWatchValidator, WatchableHierarchies watchableHierarchies, MovedHierarchyHandler movedHierarchyHandler) {
```
[the remark this answers is not in the document]
Comment (lptr) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java:67]: Good idea, done.

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java (hunk 1 above)
Comment (lptr) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java:34]: I'm trying to keep this change to the minimum, as we need to merge it back to 6.9.1. Let's do this rename separately.

Comment (wolfs) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java:34]: 👍

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java (hunk 2 above)
Comment (wolfs) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java:62]: I wanted to delete this comment in favor of this one on `HierarchicalFileWatcherUpdater`: https://github.com/gradle/gradle/pull/17922#discussion_r681741115

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java (hunk 3 above)
Comment (lptr) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java:99]: Yes, good point.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@bot-gradle test and merge

File: subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy [hunk 8]
```diff
@@ -169,4 +171,70 @@ class ChangesBetweenBuildsFileSystemWatchingIntegrationTest extends AbstractFile
...
+        run "run"
+        then:
+        targetFile.text == "Hello Old World!"
+        executedAndNotSkipped ":run"
+
+        expect:
+        succeeds "clean"
+
+        when:
+        originalDir.renameTo(renamedDir)
```
Comment (paplorinc) [inline subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy:230]: Does this mean that the issue isn't actually Windows related?

Comment (paplorinc) [reply subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy:230]: what if we do a case-only rename in Windows?

Comment (lptr) [reply subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy:230]: The issue is Windows-related, but there is no point in keeping the test coverage Windows-only.

We will handle a case-rename the same way as any other rename, and report it as moved. This is because `GetFinalPathNameByHandleW()` will return a different path after the rename.
