### PR TITLE
Fix up-to-date check for output files of Sign task

### LINKED ISSUE #4980: The Sign task should have the signature files as output
### Expected Behavior
Task of type `Sign` is not up-to-date when its output file is manipulated or deleted

### Current Behavior
Task of type `Sign` is up-to-date when its output file is manipulated or deleted

### Steps to Reproduce (for bugs)
- run a task of type `Sign`
- modify or delete the generated signature
- rerun the task of type `Sign`

### Your Environment
Gradle 4.6

### PR DESCRIPTION
**Pull request by marcphilipp**
Fixes #4980.

### CODE REVIEW

File: subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java [hunk 1]
```diff
@@ -116,7 +116,7 @@ public Object call() throws Exception {
                 name = "_" + name.substring(1);
             }
 
-            filesWithPotentialNameCollisions.put(name, signature.getToSign());
+            filesWithPotentialNameCollisions.put(name, signature.getSignatureType().fileFor(signature.getToSign()));
```
Comment (wolfs) [inline subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java]: :x: Isn't `signature.getFile()` correct? `signatureType.fileFor(toSign)` seems to be only the default: https://github.com/gradle/gradle/blob/8a7b8ea7bfd2c38689c8fa339c66485f610c10a9/subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java#L316-L334

Comment (marcphilipp) [reply subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java]: Interestingly enough, `getFile()` is not used when generating the signature file:

https://github.com/gradle/gradle/blob/3d3584f20d835168a787bab9e6cd66e5c6956889/subprojects/signing/src/main/java/org/gradle/plugins/signing/type/AbstractSignatureType.java#L38-L45

While I could not find any references to `setFile()`, it looks like `Signature` should pass its `file` to `SignatureType.sign()` instead of ignoring its return value.

Comment (wolfs) [reply subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java]: Interesting, so this never seemed to work as the Javadoc suggests. Instead of deprecating `sign(Signature, File)`, how about we deprecate `setFile`? It has no effect anyway, so we can directly make it a noop, no?
WDYT?

Comment (marcphilipp) [reply subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java]: Well, since `getFile()` is used for uploading, I think `Signature` should pass its `file` to `SignatureType.sign()` in any case. Thus, we might as well leave `setFile()` in place since it's a public API. Are you okay with that?

**Comment by marcphilipp** [comment]
> An other way how to fix this would be to annotate `Signature` with the right input and output annotations and then add this as a `@Nested` input. I don't understand enough to know if this is the right modelling or not. This would also get rid of `getInputFiles`.

That's a really good idea! However, I want to keep changes to these classes to a minimum in this PR since I'm working on them on a feature branch (to add support for publications) as well. I propose to revisit the idea after that work is done if that's okay with you.

> Moreover, we now allow arbitrary names for input/output properties, so the whole name replacing part is not necessary anymore.

Ditto.

File: subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java (hunk 1 above)
Comment (wolfs) [reply subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java]: I think we agree that `getFile` needs to return the signed file, no matter how `Signature` is configured. Like you said, this is used for uploading.

Currently, `setFile` would change the value of `getFile`, but `getFile` would not point anymore to the file generated by `SignatureType.sign`. That is a problem.

So either
1) we extend our public API and add a method to `SignatureType` to fix the behavior when mutating `Signature` or
2) we remove a method (i.e. deprecate for now) from our public API so the destination file of `Signature` cannot be changed any more.

Since no one could have changed the destination of the `Signature` via `setFile` anyway (since it had no effect), I would opt for 2). If the feature to change the destination file for the signature is required at some point, we could re-add it.

WDYT?

**Comment by marcphilipp** [comment]
I've deprecated `setFile()` in db9546d03b54250951d7013f0b36b1731a9a6eee.

@wolfs Please take another look.

File: subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java [hunk 2]
```diff
@@ -309,8 +302,15 @@ private Date defaultDate() {
...
-        this.file = file;
+    /**
+     * Set the file for the generated signature.
+     *
+     * @param file ignored
+     * @deprecated changing the output file is not supported.
+     */
+    @Deprecated
+    public void setFile(@SuppressWarnings("unused") File file) {
+        // do nothing
```
Comment (wolfs) [inline subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java]: ❌ We should print a deprecation warning when this method is used. Did you check how the `file` property shows up in the DSL docs? It should show up as not deprecated.

File: subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java [hunk 3]
```diff
@@ -321,11 +321,6 @@ public void setFile(File file) {
      * @return The signature file. May be {@code null} if unknown at this time.
      */
     public File getFile() {
```
Comment (wolfs) [inline subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java]: I think we need to adjust the Javadoc for `getFile`, since it doesn't default anymore but is the default.

File: subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java (hunk 2 above)
Comment (wolfs) [reply subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java]: ❌ We also need to add a section to the release notes about possibly breaking changes.

Comment (marcphilipp) [reply subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java]: > We should print a deprecation warning when this method is used.

Done in 62d13aecca547272b44f5797e6b5df49c53231b2.

> Did you check how the `file` property shows up in the DSL docs?

The `Signature` class is not part of the DSL docs.

> We also need to add a section to the release notes about possibly breaking changes.

Done in 62d13aecca547272b44f5797e6b5df49c53231b2.

File: subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java (hunk 3 above)
Comment (marcphilipp) [reply subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java]: Done in 62d13aecca547272b44f5797e6b5df49c53231b2.

**Comment by marcphilipp** [comment]
I added an integration test for the deprecation message.

@wolfs Please take another look.

File: subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningTasksIntegrationSpec.groovy [hunk 4]
```diff
@@ -143,4 +143,22 @@ class SigningTasksIntegrationSpec extends SigningIntegrationSpec {
         and:
         file("build", "libs", "sign-1.0.jar.asc").text
     }
+
+    @IgnoreIf({GradleContextualExecuter.parallel})
```
Comment (wolfs) [inline subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningTasksIntegrationSpec.groovy]: Why the `IgnoreIf`?

File: subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningTasksIntegrationSpec.groovy [hunk 5]
```diff
@@ -143,4 +143,22 @@ class SigningTasksIntegrationSpec extends SigningIntegrationSpec {
...
+            }
+            signJar.singleSignature.file = file('custom-signature.txt')
+        """
+
+        when:
+        executer.expectDeprecationWarning()
+        run()
+
+        then:
+        output.contains('Using Signature.setFile() has been deprecated')
```
Comment (wolfs) [inline subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningTasksIntegrationSpec.groovy]: I think we wanted to stop using `output.contains` and start using `outputContains`. This is more robust.

**Comment by marcphilipp** [comment]
Both fixed in 55bebb88d9327e06cf8b26bba38e2b40b63ef911.

@wolfs Please take one more look.
