### PR TITLE
Re-enable AGP lint task smoke test

### LINKED ISSUE #15489: Fix Lint task with evaluation of input properties
The lint task currently doesn't work, since https://github.com/gradle/gradle/pull/15432 introduced evaluation of all input properties. This will be fixed on the AGP side in 4.2.0-beta03.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by wolfs**
The problem has been fixed in AGP 4.2 beta03.

Fixes #15489

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test this

File: subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy [hunk 1]
```diff
@@ -106,9 +105,7 @@ class AndroidSantaTrackerSmokeTest extends AbstractAndroidSantaTrackerSmokeTest
     }
 
     @Unroll
-    @UnsupportedWithConfigurationCache(iterationMatchers = [AGP_3_ITERATION_MATCHER, AGP_4_0_ITERATION_MATCHER, AGP_4_1_ITERATION_MATCHER, AGP_4_2_ITERATION_MATCHER])
```
Comment (eskatos) [inline subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy:109]: :question: I would keep that annotation. Lint isn't supported with the configuration cache and should get fixed in AGP 7.

**Comment by wolfs** [comment]
@bot-gradle test this

File: subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy (hunk 1 above)
Comment (wolfs) [reply subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy:109]: I re-added the annotation. I removed it since I thought the lint task doesn't work with all the older AGP versions at all, though it actually should work with AGP 4.2, so the `UnsupportedWithConfigurationCache` still makes sense.

**Comment by wolfs** [comment]
@bot-gradle test this

File: subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy (hunk 1 above)
Comment (eskatos) [reply subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy:109]: If this test only runs on >=4.2 then the list of `iterationMatchers` here could be reduced

Comment (wolfs) [reply subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy:109]: I removed the unused iteration matchers.

**Review by eskatos — APPROVED** [review]
