### PR TITLE
Fix disabling of performance monitoring via system property

### LINKED ISSUE #24283: org.gradle.daemon.performance.enable-monitoring=false does not disable performance monitoring
According to the [documentation](https://docs.gradle.org/current/userguide/gradle_daemon.html#performance_monitoring),  `org.gradle.daemon.performance.enable-monitoring` system property can be used to disable performance monitoring.

### Current Behavior
```shell
./gradlew <task> -Dorg.gradle.daemon.performance.enable-monitoring=false
```
Does not disable monitoring.

`org.gradle.daemon.performance.enable-monitoring=false` in `gradle.properties`

Also has no effect.

The only way I found to disable monitoring is this:
```shell
JDK_JAVA_OPTIONS="-Dorg.gradle.daemon.performance.enable-monitoring=false" ./gradlew <task>
```

### Expected Behavior
Documented options should work, or documentation should be updated with working methods.

### Your Environment
```
Gradle 8.0.2

JVM: OpenJDK 64-Bit Server VM (19.0.2+9, mixed mode, sharing)
Java: version 19.0.2 2023-01-17, vendor BellSoft
Java Home: /usr/lib/jvm/bellsoft-java19-amd64

Linux Ubuntu 22.04.2 LTS
Linux alexey-PC 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by jvandort**
The HealthExpirationStrategy is constructed before the system properties from the launcher are set in the daemon We handle this by checking if the property is set later, in 'checkExpiration'

Fixes #24283

### CODE REVIEW

File: subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/HealthExpirationStrategy.java [hunk 1]
```diff
@@ -85,12 +84,11 @@ public HealthExpirationStrategy(DaemonHealthStats stats, GarbageCollectorMonitor
         this.stats = stats;
         this.strategy = strategy;
         this.logger = logger;
-        this.enabled = Boolean.parseBoolean(System.getProperty(ENABLE_PERFORMANCE_MONITORING, "true"));
     }
 
     @Override
     public DaemonExpirationResult checkExpiration() {
-        if (!enabled) {
+        if (!Boolean.parseBoolean(System.getProperty(ENABLE_PERFORMANCE_MONITORING, "true"))) {
```
Comment (tresat) [inline subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/HealthExpirationStrategy.java:91]: 💭 You should also add the note from the PR on why this can't be done during class initialization to this method, or the class javadoc or something.  

It would be really easy for someone working on this class later to think "Why do this work each time the method is called, I'll make a quick optimization to store the value in the constructor."  The test would fail, but they'd still lose any time trying to understand why.

**Review by tresat — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge
