### PR TITLE
Incremental Compilation - prefer project compiled sources (#21255)

### LINKED ISSUE #21255: Incremental Java compiler fails with compile errors due to incorrect classpath, while full compilation works
If a Java class with the same fully-qualified name exists in a compile dependency of a module and also in the module itself, the incremental Java compiler picks the definition provided by the dependency. Only if the sources of the class in the module did 
change, the incremental compiler will resolve to the local one.

### Expected Behavior
Incremental compile should always succeed if a full compilation succeeds and vice versa. It should also consistently select the same definition of a class in case of conflicting definitions.

### Current Behavior
If a class that depends on a class with conflicting definitions is changed, the incremental compilation may fail if the two conflicting definitions are not compatible. If the conflicting class in the local module did also change, the incremental compiler passes it as a changed source file to the compiler. Then the compiler resolves any references for this class to the local definition. If the conflicting class did not change, the class files from the previous compilation of the module are appended to the **end** of the classpath. This gives them the lowest priority during resolution. As a result, references will be resolved to the definition exposed by the external dependency. 

A full rebuild after the failed build succeeds.

### Context
We have multiple occurrences of such conflicting classes in a large code base. The developers often have to trigger a gradle build multiple times until it succeeds (especially after changing Git branches).

#### Module base

BaseClass.java:
```java
package org.example;

public class BaseClass {

}
```

#### Module impl

This module depends on the base module.

BaseClass.java
```java
package org.example;

public class BaseClass {

    public void method() {}

}
```

Impl.java
```java
package org.example;

public class Impl extends BaseClass {

    public void repro(Impl i) {
        i.method();
    }
}
```
Archive containing example:
[duplicateclasses.zip](https://github.com/gradle/gradle/files/9111874/duplicateclasses.zip)

Steps to reproduce:
- Do a full build of the project
- Change Impl.java, but not BaseClass.java
- Trigger another build (now using the incremental compiler)
- Build fails with:

```
  duplicateclasses\impl\src\main\java\org\example\Impl.java:6: error: cannot find symbol
        i.method();
         ^
  symbol:   method method()
  location: variable i of type Impl
```

### Your Environment
Gradle 7.5-RC2 (but also observed on older versions)
Java 11

### PR DESCRIPTION
**Pull request by GingerGeek**
This stops a situation where if versions of the same class are in both your sources and your dependencies, the version in your dependencies would be used over the one in your sources. This would lead to compile errors in incremental builds in instances where a consumer class in your sources depends on the specifics of your sources' version that differs from the version in the dependencies.

Fixes #21255 

### Context
Although generally discouraged, projects may contain class files that conflict with their dependencies.
During a full build the compiler will deal with this and prefer resolution to classes being compiled however in incremental building mode we need to consider the order of the classpath to indicate preference of where to source classes from.

This has been seen in the wild in issues such as PaperMC/paperweight#199

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [N/A] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [X] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by GingerGeek** [comment]
I have verified this change locally using the archive from #21255 

I'm not sure if this warrants an integration test? and if so I'm not sure where would be best to add it - within the `language-java` model?

**Review by Floppy012 — APPROVED** [review]
Can confirm, that this PR fixes the issue described in https://github.com/PaperMC/paperweight/issues/199

**Comment by GingerGeek** [comment]
I will try and create an integration test for this case as well, I think i found where it needs to go

**Comment by ov7a** [comment]
Thank you for your contribution!

Please add tests to cover your changes.  

***

Yes, you can add a test case similar to what was described in the original issue. 
Please note that your change may lead to test failures, see the GH workflows for them.

**Comment by ov7a** [comment]
@bot-gradle test this please.

**Comment by GingerGeek** [comment]
I have added an integration test and tested that it fails without the fix.

File: platforms/jvm/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java [hunk 1]
```diff
@@ -119,7 +119,7 @@ private void processSourceChanges(CurrentCompilation current, SourceFileChangePr
         }
     }
 
-    private String rebuildClauseForChangedNonSourceFile(FileChange fileChange) {
+    private static String rebuildClauseForChangedNonSourceFile(FileChange fileChange) {
```
Comment (AustinLMayes) [inline platforms/jvm/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java:122]: What's the reason behind this change?

Comment (GingerGeek) [reply platforms/jvm/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java:122]: This is a utility method so is a fine candidate to be made static. This is in line with other similar methods within this class

**Comment by ov7a** [comment]
Thank you!

This PR is complete and simple enough, it will be merged immediately.

**Comment by ov7a** [comment]
@bot-gradle merge

**Comment by GingerGeek** [comment]
Thank you very much for prompt review and merge 😊
