### PR TITLE
Fix a few ignored test assertions

### LINKED ISSUE #27004: Missing assertions in `IdeaModel` tooling tests
I stumbled across a couple of places where method-level if-statements do not use assertions, and don't actually test the conditions. A quick test showed that at least one of these tests fails when `assert` is added, though I don't have a good idea how to fix the test properly at the moment.

Place one (this one seems to be failing when assertions are added)
https://github.com/gradle/gradle/blob/866060514f01806785b1aef1c029dc402175f41a/platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/m5/ToolingApiIdeaModelCrossVersionSpec.groovy#L293-L301

Place two
https://github.com/gradle/gradle/blob/866060514f01806785b1aef1c029dc402175f41a/platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r31/ToolingApiIdeaModelCrossVersionSpec.groovy#L112-L117

Maybe there are more

### PR DESCRIPTION
**Pull request by donat**
Fixes #27004

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this

File: platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/m5/ToolingApiIdeaModelCrossVersionSpec.groovy [hunk 1]
```diff
@@ -290,13 +290,9 @@ project(':impl') {
 
         then:
         def libs = impl.dependencies
-        if (targetVersion >= GradleVersion.version("3.4")) {
-            libs.size() == 3
-        } else {
-            libs.size() == 1
-        }
+        libs.size() == 1
```
Comment (reinsch82) [inline platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/m5/ToolingApiIdeaModelCrossVersionSpec.groovy:293]: 🎉

**Review by reinsch82 — APPROVED** [review]
