### PR TITLE
Make sure constraint attributes are merged with edge attributes

### LINKED ISSUE #8306: 5.2 regression: cannot resolve configuration with platform dependency
The following build script successfully resolves with Gradle 5.1, but fails with the 5.2 candidate built from the `release` branch:
```
repositories {
    maven { url 'https://dl.bintray.com/palantir/releases' }
    mavenCentral()
}

apply plugin: 'maven-publish'
apply plugin: 'java-library'

dependencies {
  compile platform("org.apache.spark:spark-dist_2.11-hadoop-palantir-bom")
  constraints {
    compile "org.apache.spark:spark-dist_2.11-hadoop-palantir-bom:2.5.0-palantir.7"
  }
}

task foo {
  doLast {
    configurations.compile.resolve()
  }
}
```

Scan for failure: https://scans.gradle.com/s/seqsrqwpijy2u/console-log

Originally reported by @dansanduleac

### PR DESCRIPTION
**Pull request by melix**
### Context

This commit fixes #8306 by making sure that if we resolve a constraint
edge and need to select a configuration based on attributes, we
consider the attributes of at least one real edge on it before resolving.

This allows the engine to consider attributes on constraints as requirements,
but also not to forget about edge constraints if they were any.

### CODE REVIEW

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy [hunk 1]
```diff
@@ -263,6 +263,49 @@ class JavaPlatformResolveIntegrationTest extends AbstractHttpDependencyResolutio
...
+                .hasType("pom")
+                .allowAll()
+                .publish()
+
+        when:
+        buildFile << """
+            dependencies {
+                api platform("org:platform") // no version, will select the "platform" component
+                constraints {
+                   api platform("org:platform:1.0")
```
Comment (ljacomet) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy]: ❌ This version of the test will pass with or without your changes.
There needs to be a version that tries with `api "org:platform:1.0"` as the constraint.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java [hunk 2]
```diff
@@ -65,6 +65,13 @@
     private final PendingDependencies pendingDependencies;
     private ComponentState selected;
     private ImmutableAttributes mergedConstraintAttributes = ImmutableAttributes.EMPTY;
+
+    // This field caches an arbitrary edge attributes, used when computing the attributes
+    // of selection of a constraint, in order to make sure we choose a "variant of the constraint"
+    // which is compatible with edges. In theory we shouldn't select a variant for contraints, but
```
Comment (ljacomet) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java]: Missing "s" in "contraints"

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java [hunk 3]
```diff
@@ -302,13 +310,25 @@ ImmutableAttributes mergedConstraintsAttributes(AttributeContainer append) {
         return attributesFactory.concat(mergedConstraintAttributes, attributes);
     }
 
+    ImmutableAttributes mergeConstraintAttributesWithHardDependencyAttributes(ImmutableAttributes constraintAttributes) {
+        if (nonConstraintAttributes!=null) {
```
Comment (ljacomet) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java]: Code style: spaces around `!=`

Comment (melix) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java]: fixed
