### PR TITLE
Adapt input artifact path for filtering transforms

### LINKED ISSUE #16962: Artifact view contains wrong file dependency in Android project
### Expected Behavior
File dependencies should only be part of the artifact view they contain

### Current Behavior
File dependencies are part of artifact views they don't contain

### Context
This affects Android projects with multiple variants (aka debug, release) which use different file dependencies for the different variants. Depending on the order of which e.g. `compile{Release,Debug}Kotlin` or `merge{Release,Debug}NativeLibs` is being executed, the classpath of those tasks wrongly contains the debug or release file dependency.

This works for me in Gradle 6.8 but breaks in Gradle 7.0.

### Steps to Reproduce 
`settings.gradle`:
```gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "reproduces-file-deps"
```

`build.gradle`:
```gradle
plugins {
    id 'com.android.library' version '4.2.0-beta06'
    id 'org.jetbrains.kotlin.android' version '1.4.32'
}


TaskProvider<Jar> jarRelease = tasks.register("myJarRelease", Jar) {
    destinationDirectory = file("build/release/jar_output")
    archiveFileName = "another_one1.jar"
    archiveVersion = ""
}

dependencies {
    releaseImplementation files(jarRelease.flatMap { it.archiveFile })
}

TaskProvider<Jar> jarDebug = tasks.register("myJarDebug", Jar) {
    destinationDirectory = file("build/debug/jar_output")
    archiveFileName = "another_one2.jar"
    archiveVersion = ""
}

dependencies {
    debugImplementation files(jarDebug.flatMap { it.archiveFile })
}

android {
    compileSdk 30

    defaultConfig {
        minSdk 21
        targetSdk 30
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

Attribute<String> ARTIFACT_TYPE = Attribute.of("artifactType", String.class)
["debug", "release"].each { variant ->
    tasks.register("${variant}Consume") {
        def view = configurations."${variant}RuntimeClasspath".incoming
            .artifactView { config->
                config.attributes {
                    it.attribute(ARTIFACT_TYPE, "android-java-res")
                }
            }.artifacts.artifactFiles
        it.inputs.files(view)
        doLast {
            println "${variant}ArtifactView contains build/debug/jar_output/*: ${view.files.any { it.absolutePath.contains('build/debug/jar_output')}}"
            println "${variant}ArtifactView contains build/release/jar_output/*: ${view.files.any { it.absolutePath.contains('build/release/jar_output')}}"
            println "variant consume"
        }
    }
}
```

When running
```
gradle clean debugConsume releaseConsume
```
Then you have this output:
```
:clean
:myJarDebug
:debugConsume
debugArtifactView contains build/debug/jar_output/*: true
debugArtifactView contains build/release/jar_output/*: false
variant consume
:myJarRelease
:releaseConsume
releaseArtifactView contains build/debug/jar_output/*: true
releaseArtifactView contains build/release/jar_output/*: false
variant consume
```

So you see that both artifact views contain the debug jar and none contains the release jar. There is also a deprecations warning about a missing task dependency, see the build scan for more details.

### Your Environment
Build scan URL: https://ge.gradle.org/s/4ubrszv3nveuy/console-log#L11

### PR DESCRIPTION
**Pull request by wolfs**
so even if the result comes from the in-memory cache,
we use a path relative to the input artifact.

Fixes #16962

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test this

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy [hunk 1]
```diff
@@ -949,6 +949,77 @@ class ArtifactTransformIntegrationTest extends AbstractHttpDependencyResolutionT
         output.contains("files: [lib.jar]")
     }
 
+    def "transforms registering the input as an output can use normalization"() {
```
Comment (lptr) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy:952]: I guess this should link to the issue?

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy [hunk 2]
```diff
@@ -949,6 +949,77 @@ class ArtifactTransformIntegrationTest extends AbstractHttpDependencyResolutionT
...
+        file("input1.jar").text = "jar"
+        file("input2.jar").text = "jar"
+        buildFile("""
+            import org.gradle.api.artifacts.transform.TransformParameters
```
Comment (lptr) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy:956]: Why is this single import required?

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy (hunk 1 above)
Comment (lptr) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy:952]: Should the test name imply that this is about file dependencies specifically?

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy [hunk 3]
```diff
@@ -949,6 +949,77 @@ class ArtifactTransformIntegrationTest extends AbstractHttpDependencyResolutionT
...
+                    from artifacts.artifactFiles
+                    into "\${buildDir}/libs1"
+                    doLast {
+                        println "files: " + artifacts.collect { it.file.name }
+                        println "ids: " + artifacts.collect { it.id }
+                        println "components: " + artifacts.collect { it.id.componentIdentifier }
+                        println "variants: " + artifacts.collect { it.variant.attributes }
+                    }
+                }
+            }
```
Comment (lptr) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy:1007]: I think we should invest some time into decreasing redundancy in this now-2703-line test class. There is just so much noise around the setup that it's really hard to see what exactly the test is trying to prove.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java [hunk 4]
```diff
@@ -0,0 +1,164 @@
...
+ * The result of running a transformation.
+ */
+public interface TransformationResult {
+    /**
+     * The result of the artifact transform, using relative paths into the provided input artifact.
+     */
+    ImmutableList<File> resultRelativeTo(File inputArtifact);
+
+    /**
+     * The result of the artifact transform in the transform workspace.
```
Comment (lptr) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java:34]:
```suggestion
     * The part of the result of the artifact transform that was produced in the transform workspace.
     Does not include results selected from the inputs.
```

Also, I think the term "result" is a bit confusing here, and using "outputs" would be better.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java [hunk 5]
```diff
@@ -0,0 +1,164 @@
...
+     *
+     * May be empty, when the transform only selects elements of the input artifact.
+     */
+    ImmutableList<File> getResultsInWorkspace();
```
Comment (lptr) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java:38]: There is a confusion between singular and plural use of "result" vs "results": in the Javadoc you always say "result", and `resultRelativeTo()` is also singular, but this method uses plural.

Again, the definition of "result" is unclear to me, and I think "outputs" is a much better defined term that we should use here.

Note that the interface itself is called `TransformationResult`, which adds to the confusion. I think the right way to think about it is that this interface represents a _result_ of a transformation, and the methods return the _outputs_ in different forms.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy (hunk 1 above)
Comment (wolfs) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy:952]: This is not about file dependencies. It doesn't matter if the input is a file dependency or something else - this is about the input artifacts having the same normalized form.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy (hunk 2 above)
Comment (wolfs) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy]: I removed it, since the import is added in the test setup to the build script already. We need it, since our default imports don't work for inner classes, and we use `TransformationParameters.None` here.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy (hunk 1 above)
Comment (wolfs) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy:953]: I added a link to the issue.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java (hunk 4 above)
Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java]: I changed the names in the class like we said. PTAL.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy (hunk 3 above)
Comment (wolfs) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy:1006]: I added a project builder test to only test the execution of the artifact tranforms. Please tell me what you think.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java [hunk 6]
```diff
@@ -0,0 +1,144 @@
...
+                return new File(inputArtifact, relativePath);
+            }
+        }
+
+        private static class InputArtifact implements TransformationOutput {
+            @Override
+            public File resolveForInputArtifact(File inputArtifact) {
+                return inputArtifact;
+            }
+        }
```
Comment (lptr) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java:125]: I think something like `EntireInputArtifact` and `PartOfInputArtifact` or `DescendantOfInputArtifact` or `FragmentOfInputArtifact` would be a better distinction.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+
+        public TransformationResult build() {
+            ImmutableList<TransformationOutput> transformationOutputs = builder.build();
+            return onlyProducedOutputs
+                ? new OnlyProducedOutputTransformationResult(convertToProducedOutputLocations(transformationOutputs))
+                : new DefaultTransformationResult(transformationOutputs);
+        }
+
+        private interface TransformationOutput {
```
Comment (lptr) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java:69]: I think some Javadoc here explaining the three kinds of outputs that we handle would be nice.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java [hunk 8]
```diff
@@ -0,0 +1,144 @@
...
+        boolean onlyProducedOutputs = true;
+
+        public void addInputArtifact(String relativePath) {
+            onlyProducedOutputs = false;
+            builder.add(new InInputArtifact(relativePath));
+        }
+
+        public void addInputArtifact() {
+            onlyProducedOutputs = false;
+            builder.add(new InputArtifact());
```
Comment (lptr) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java:55]: Nit: this could use a constant instance.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java [hunk 9]
```diff
@@ -0,0 +1,144 @@
...
+
+        public void addOutput(File outputLocation) {
+            builder.add(new ProducedOutput(outputLocation));
+        }
+
+        public TransformationResult build() {
+            ImmutableList<TransformationOutput> transformationOutputs = builder.build();
+            return onlyProducedOutputs
+                ? new OnlyProducedOutputTransformationResult(convertToProducedOutputLocations(transformationOutputs))
+                : new DefaultTransformationResult(transformationOutputs);
```
Comment (lptr) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java:66]: I think the difference here is that one is a `ResolvingTrnasformationResult` while the other is an `(Already)ResolvedTransformationResult`. What I don't like with the current names is the `Default`.

File: subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformProjectBuilderTest.groovy [hunk 10]
```diff
@@ -0,0 +1,177 @@
...
+        inputArtifact1.text = "Hello"
+
+        def inputArtifact2 = file("input2.txt")
+        inputArtifact2.text = "Hello"
+
+        expect:
+        invoke(transformer, inputArtifact1).get() == [inputArtifact1]
+        invoke(transformer, inputArtifact2).get() == [inputArtifact2]
+        INVOCATION_COUNT.get() == 1
+    }
```
Comment (lptr) [inline subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformProjectBuilderTest.groovy:65]: I really like these tests!

File: subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformProjectBuilderTest.groovy [hunk 11]
```diff
@@ -0,0 +1,177 @@
...
+        def selectedFile1 = inputArtifact1.file(SELECTED_PATH)
+        selectedFile1.text = "Hello"
+
+        def inputArtifact2 = file("input2.txt")
+
+        def selectedFile2 = inputArtifact2.file(SELECTED_PATH)
+        selectedFile2.text = "Hello"
+
+        expect:
+        invoke(transformer, inputArtifact1).get() == [selectedFile1]
```
Comment (lptr) [inline subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformProjectBuilderTest.groovy:81]: Reading this test I think we could make it a bit more clear that `invoke()` is something relevant to this test only, not something that comes from a superclass for example. Say, by calling it `transform()` or `invokeTransform()`.

File: subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformProjectBuilderTest.groovy [hunk 12]
```diff
@@ -0,0 +1,177 @@
...
+        invoke(transformer, inputArtifact2).get() == [selectedFile2]
+    }
+
+    def "the order is retained when mixing input artifacts and produced artifacts"() {
+        def transformer = registerTransform(MixedTransform)
```
Comment (lptr) [inline subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformProjectBuilderTest.groovy:86]: I think we should call these `transform`s not `transformer`s.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java [hunk 13]
```diff
@@ -348,39 +348,52 @@ public InputFingerprinter getInputFingerprinter() {
...
-                        builder.add(new File(inputArtifact, path.substring(2)));
+                        String relativePathString = path.substring(2);
+                        if (relativePathString.isEmpty()) {
+                            builder.addInputArtifact();
+                        } else {
+                            builder.addInputArtifact(relativePathString);
+                        }
                     } else {
                         throw new IllegalStateException("Cannot parse result path string: " + path);
                     }
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java]: I moved it to a separate class.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java [hunk 14]
```diff
@@ -0,0 +1,144 @@
...
+     */
+    ImmutableList<File> resolveOutputsForInputArtifact(File inputArtifact);
+
+    static Builder builder() {
+        return new Builder();
+    }
+
+    class Builder {
+        private final ImmutableList.Builder<TransformationOutput> builder = ImmutableList.builder();
+        boolean onlyProducedOutputs = true;
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java]: Done.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java (hunk 6 above)
Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java:137]: Renamed.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java (hunk 7 above)
Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java:79]: I added some Javadoc.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java (hunk 8 above)
Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java]: Added.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java (hunk 9 above)
Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java]: I renamed the classes to `AlreadyResolvedTransformationResult` and `ResolvingTransformationResult`.

File: subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformProjectBuilderTest.groovy (hunk 12 above)
Comment (wolfs) [reply subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformProjectBuilderTest.groovy]: Renamed.

File: subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformProjectBuilderTest.groovy (hunk 11 above)
Comment (wolfs) [reply subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformProjectBuilderTest.groovy]: I renamed the method to `invokeTransform`.

**Comment by wolfs** [comment]
@lptr PTAL!

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResultWriter.java [hunk 15]
```diff
@@ -0,0 +1,103 @@
...
+import java.io.IOException;
+import java.nio.charset.StandardCharsets;
+import java.nio.file.Files;
+import java.nio.file.Path;
+import java.util.ArrayList;
+import java.util.List;
+
+import static org.gradle.internal.UncheckedException.unchecked;
+
+public class TransformationResultWriter {
```
Comment (lptr) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResultWriter.java:33]: Given that the class can both read and write transform results, I think it's more like a serializer than a writer.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java [hunk 16]
```diff
@@ -309,7 +298,8 @@ public TransformationResult call(BuildOperationContext context) {
                     File workspace = executionRequest.getWorkspace();
                     InputChangesInternal inputChanges = executionRequest.getInputChanges().orElse(null);
                     ImmutableList<File> result = transformer.transform(inputArtifactProvider, getOutputDir(workspace), dependencies, inputChanges);
-                    return writeResultsFile(workspace, result);
+                    TransformationResultWriter resultWriter = new TransformationResultWriter(inputArtifact, getOutputDir(workspace));
+                    return resultWriter.writeToFile(getResultsFile(workspace), result);
```
Comment (lptr) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java:302]: Creating an instance of this type just to throw it away immediately seems wrong to me. We could either keep around a long-existing instance, perhaps as a field of the `DefaultTransformerInvocationFactory` itself, and reuse that; or make the whole thing static and pass in all the parameters.

File: subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformationResultWriterTest.groovy [hunk 17]
```diff
@@ -0,0 +1,137 @@
...
+
+        when:
+        def writerWithNewOutputDir = new TransformationResultWriter(inputArtifact, newOutputDir)
+        def loadedResults = writerWithNewOutputDir.readResultsFile(resultFile)
+        then:
+        loadedResults.resolveOutputsForInputArtifact(inputArtifact) == resultInNewOutputDir
+    }
+
+    private void assertCanWriteAndReadResult(File... files) {
+        def writer = new TransformationResultWriter(inputArtifact, outputDir)
```
Comment (lptr) [inline subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformationResultWriterTest.groovy:124]: This could be a field instead of created for each test individually.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResultWriter.java (hunk 15 above)
Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResultWriter.java]: I renamed it to `*Serializer`.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java (hunk 16 above)
Comment (wolfs) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java]: I would prefer to leave it as is right now. Let's revisit when we move the building of the transformation result to `DefaultTransformOutputs`.

File: subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformationResultWriterTest.groovy (hunk 17 above)
Comment (wolfs) [reply subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformationResultWriterTest.groovy]: Made it a field.

**Comment by wolfs** [comment]
@lptr PTAL!

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge
