### PR TITLE
Expose the ProviderFactory in settings.gradle.

### LINKED ISSUE #14465: Providers are not available in settings.gradle
### Expected Behavior
Attempting to access the `providers` keyword should work within the `settings.gradle` file.  Otherwise there is no way to implement configuration-cache-friendly property access.

### Current Behavior

Currently, attempting to use `providers` results in the error
```* What went wrong:
A problem occurred evaluating settings 'fitbitandroid'.
> Could not get unknown property 'providers' for settings 'fitbitandroid' of type org.gradle.initialization.DefaultSettings.
```

### Context

In our settings.gradle, the Gradle Enterprise block is configurable via system properties.  For example: 
```def scanOverride = Boolean.parseBoolean(System.getProperty("fitbit.alwaysPublishGradleScan", false.toString()))```

Converted to provider-usage that becomes: 
```def scanOverride = Boolean.parseBoolean(providers.systemProperty("fitbit.alwaysPublishGradleScan").forUseAtConfigurationTime().orElse("false"))```

That value is then used in our buildScan block as:
```
gradleEnterprise.buildScan {
    server = "${gradle_enterprise_url}"
    allowUntrustedServer = true
    captureTaskInputFiles = true
    publishAlwaysIf(onInternalNetwork && scanOverride))
}
```

### PR DESCRIPTION
**Pull request by simtel12**
This will allow the configuration-cache-safe access of properties,
environment variables, etc. in the Settings.

Issue: #14465

Signed-off-by: Gregorios Leach <optikflux@gmail.com>

Fixes #14465

### Context

Access to properties/etc can be important for configuring a project's Settings - without this change they'll be forced to use APIs that are not compatible with the configuration cache.

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [X] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

* Note: No unit tests were added to `/src/test` as no new logic was introduced.

### CODE REVIEW

File: subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java [hunk 1]
```diff
@@ -208,6 +211,24 @@
...
+    /**
+     * Creates a {@code Provider} implementation based on the provided value.
+     *
+     * @param value The {@code java.util.concurrent.Callable} use to calculate the value.
+     * @return The provider. Never returns null.
+     * @throws org.gradle.api.InvalidUserDataException If the provided value is null.
+     * @see org.gradle.api.provider.ProviderFactory#provider(Callable)
+     * @since 6.8
+     */
+    <T> Provider<T> provider(Callable<T> value);
```
Comment (eskatos) [inline subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java:223]: :x: Let's not add this method to `Settings` as part of this change. The same can be done using `providers.provider {}`.

File: subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java [hunk 2]
```diff
@@ -54,7 +54,7 @@
  *     <li>Calling {@link #map(Transformer)} to create a new provider from an existing provider.</li>
  *     <li>Using the return value of {@link org.gradle.api.tasks.TaskContainer#register(String)}, which is a provider that represents the task instance.</li>
  *     <li>Using the methods on {@link org.gradle.api.file.Directory} and {@link org.gradle.api.file.DirectoryProperty} to produce file providers.</li>
- *     <li>By calling {@link ProviderFactory#provider(Callable)} or {@link org.gradle.api.Project#provider(Callable)} to create a new provider from a {@link Callable}.</li>
+ *     <li>By calling {@link ProviderFactory#provider(Callable)}, {@link org.gradle.api.initialization.Settings#provider(Callable)}, or {@link org.gradle.api.Project#provider(Callable)} to create a new provider from a {@link Callable}.</li>
```
Comment (eskatos) [inline subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java:57]: Once `Settings.provider {}` removed this should be updated. Maybe as a separate bullet point.

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy [hunk 3]
```diff
@@ -1114,4 +1115,45 @@ class ConfigurationCacheIntegrationTest extends AbstractConfigurationCacheIntegr
         then:
         outputContains("value = value")
     }
+
+    @Issue("gradle/gradle#14465")
+    def "configuration is cacheable when providers are used in settings"() {
```
Comment (eskatos) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy:1120]: :x: Those tests would be better in `ConfigurationCacheBuildOptionsIntegrationTest`

File: subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java [hunk 4]
```diff
@@ -208,6 +211,24 @@
...
+
+    /**
+     * Provides access to methods to create various kinds of {@link Provider} instances.
+     *
+     * @since 6.8
+     */
+    ProviderFactory getProviders();
```
Comment (eskatos) [inline subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java:230]: :x: Newly introduced methods should be `@Incubating`

**Review by eskatos — CHANGES_REQUESTED** [review]
Hi @simtel12, thank you for the PR and the nice tests!

I requested a few changes including to the API. Once done, please drop the accepted public API changes and run `checkBinaryCompatibility` again.

File: subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java (hunk 4 above)
Comment (simtel12) [reply subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java:230]: Sounds good.  I just made the guess that because ProviderFactory wasn't incubating anymore that accessor functions for it wouldn't be either.  😅

File: subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java (hunk 1 above)
Comment (simtel12) [reply subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java:223]: I was trying to mimic the API used in `Project` - is that not the ideal API?  (For the record, I agree, the helper method isn't necessary)

File: subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java (hunk 4 above)
Comment (simtel12) [reply subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java:230]: Sounds good.  I just made the guess that because ProviderFactory wasn't incubating anymore that accessor functions for it wouldn't be either.  😅

File: subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java (hunk 1 above)
Comment (simtel12) [reply subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java]: Done.

File: subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java (hunk 2 above)
Comment (simtel12) [reply subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java]: Removed `Settings.provider(Callable)` as well as this reference.  I didn't add anything else to the Javadocs in `Provider` as I couldn't think of anything relevant to `Settings.getProviders()` - it's more relevant in `ProviderFactory`.  Thoughts?

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy (hunk 3 above)
Comment (simtel12) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy]: Moved.

File: subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java (hunk 2 above)
Comment (eskatos) [reply subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java]: LGTM

**Comment by eskatos** [comment]
@bot-gradle test this

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy [hunk 5]
```diff
@@ -742,6 +743,47 @@ class ConfigurationCacheBuildOptionsIntegrationTest extends AbstractConfiguratio
         configurationCache.assertStateStored()
     }
 
+    @Issue("gradle/gradle#14465")
+    def "configuration is cacheable when providers are used in settings"() {
+
+        given:
```
Comment (eskatos) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy:749]:
```suggestion
        given:
        def configurationCache = newConfigurationCacheFixture()
```

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy [hunk 6]
```diff
@@ -742,6 +743,47 @@ class ConfigurationCacheBuildOptionsIntegrationTest extends AbstractConfiguratio
...
+        settingsFile << """
+            providers.systemProperty("org.gradle.booleanProperty").forUseAtConfigurationTime().orElse(false).get()
+        """
+        configurationCacheRun "help", "-Dorg.gradle.booleanProperty=true"
+        def firstRunOutput = removeVfsLogOutput(result.normalizedOutput)
+            .replaceAll(/Calculating task graph as no configuration cache is available for tasks: help\n/, '')
+            .replaceAll(/Configuration cache entry stored.\n/, '')
```
Comment (eskatos) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy:756]:
```suggestion

        when:
        configurationCacheRun "help", "-Dorg.gradle.booleanProperty=true"
        
        then:
        configurationCache.assertStateStored()
```

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy [hunk 7]
```diff
@@ -742,6 +743,47 @@ class ConfigurationCacheBuildOptionsIntegrationTest extends AbstractConfiguratio
...
+
+        when:
+        configurationCacheRun "help", "-Dorg.gradle.booleanProperty=true"
+        def secondRunOutput = removeVfsLogOutput(result.normalizedOutput)
+            .replaceAll(/Reusing configuration cache.\n/, '')
+            .replaceAll(/Configuration cache entry reused.\n/, '')
+
+        then:
+        firstRunOutput == secondRunOutput
```
Comment (eskatos) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy:765]:
```suggestion

        then:
        configurationCache.assertStateLoaded()
```

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy [hunk 8]
```diff
@@ -742,6 +743,47 @@ class ConfigurationCacheBuildOptionsIntegrationTest extends AbstractConfiguratio
...
+    }
+
+    @Issue("gradle/gradle#14465")
+    def "configuration cache is invalidated after property change when providers are used in settings"() {
+
+        given:
```
Comment (eskatos) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy:771]:
```suggestion
        given:
        def configurationCache = newConfigurationCacheFixture()
```

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy [hunk 9]
```diff
@@ -742,6 +743,47 @@ class ConfigurationCacheBuildOptionsIntegrationTest extends AbstractConfiguratio
...
+        configurationCacheRun "help", "-Dorg.gradle.booleanProperty=true"
+
+        when:
+        configurationCacheRun "help", "-Dorg.gradle.booleanProperty=false"
+        def secondRunOutput = result.normalizedOutput
+        println(secondRunOutput)
+
+        then:
+        secondRunOutput.contains("Configuration cache entry stored.")
+        secondRunOutput.contains("Calculating task graph as configuration cache cannot be reused because system property 'org.gradle.booleanProperty' has changed.")
```
Comment (eskatos) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy:784]:
```suggestion

        then:
        configurationCache.assertStateStored()
        output.contains("because system property 'org.gradle.booleanProperty' has changed.")
```

**Review by eskatos — CHANGES_REQUESTED** [review]
Thanks for the changes. It's looking good.

The integration test fails now that it moved to a different class.
I added suggestions to simplify it and make it pass.

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@simtel12 There have been changes to our CI setup. Could you please either rebase your branch on top of `master` or merge `master` into your branch?

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
Thank you @simtel12! This will be in Gradle 6.8

**Comment by simtel12** [comment]
Thanks @eskatos !
