### PR TITLE
Don't report missing task dependencies for disabled tasks

### LINKED ISSUE #16059: Gradle 7: skip dependency validation for disabled tasks
See https://github.com/spring-projects/spring-boot/issues/25126 for more details.
The new validation with messages like shown below seems to also look at disabled tasks, in my case `bootJar { enabled = false }`. As `jar` and` bootJar` share the same output, this is regarded as a dependency misconfiguration.

```
> Task :sub2:compileJava
Validation failed for task ':sub2:compileJava', disabling optimizations:
  - Task ':sub2:compileJava' uses the output of task ':sub1:bootJar', without declaring an explicit dependency (using Task.dependsOn() or Task.mustRunAfter()) or an implicit dependency (declaring task ':sub1:bootJar' as an input). This can lead to incorrect results being produced, depending on what order the tasks are executed.
```

### PR DESCRIPTION
**Pull request by wolfs**
Those tasks won't modify their outputs. For example, in
Spring boot projects the `jar` and the `bootJar` task
both output to the same location, and one of them is being
disabled by the spring boot plugin.

Fixes #16059

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java [hunk 1]
```diff
@@ -127,19 +129,30 @@ public void visitFileTreeBackedByFile(File file, FileTreeInternal fileTree, File
...
     }
 
+    private void collectValidationProblemsForConsumer(LocalTaskNode consumer, TypeValidationContext validationContext, Collection<Node> producers) {
+        producers.stream()
+            .filter(producerNode -> hasNoSpecifiedOrder(producerNode, consumer))
+            .filter(LocalTaskNodeExecutor::isEnabled)
+            .forEach(producerWithoutDependency -> collectValidationProblem(producerWithoutDependency, consumer, validationContext));
+    }
+
+    private static boolean isEnabled(Node node) {
```
Comment (melix) [inline subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java:148]: Would it make sense to have this directly on `LocalTaskNode`?

**Review by melix — APPROVED** [review]

File: subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java (hunk 1 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java:148]: I don't think so. You shouldn't call this method on the node when you build the execution graph, so I wouldn't move this there.
