### PR TITLE
Fall back to hashing the zip entry when ABI extraction fails during fingerprinting

### LINKED ISSUE #20398: Failing to fingerprint the class API should not fail the entire zip/jar
When Gradle fingerprints a zip file with compile classpath normalization, it fingerprints the public API of each class in the zip file.  If there's an error calculating the public API (for instance an ASM error while inspecting the class: #20394), it fails for the entire zip file and it falls back to hashing the entire file.

In such a case, it should fall back to hashing just the zip entry (the class file) rather than failing the entire zip.  This does mean you could get cache misses on implementation changes in the class (rather than only on API changes) but this is better than hashing the entire zip and getting misses on _any_ change whatsoever.

### Expected Behavior
A failure fingerprinting an individual class file should only change the fingerprint for that class file.

### Current Behavior
It falls back to hashing the entire zip.

### PR DESCRIPTION
**Pull request by ghale**
Fixes #20398

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

**Comment by ghale** [comment]
@bot-gradle test this

File: subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaGroovyCompileAvoidanceIntegrationSpec.groovy [hunk 1]
```diff
@@ -802,4 +802,124 @@ abstract class AbstractJavaGroovyCompileAvoidanceIntegrationSpec extends Abstrac
...
+            public class ToolImpl {
+                private Number thing() { return null; }
+                private Object t = this;
+            }
+        """
+
+        then:
+        succeeds ":b:${language.compileTaskName}"
+        executedAndNotSkipped ":a:${language.compileTaskName}"
+        skipped ":b:${language.compileTaskName}"
```
Comment (octylFractal) [inline subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaGroovyCompileAvoidanceIntegrationSpec.groovy:855]: Should these be checking `:a` instead of `:b`? Or maybe both?

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinCompileClasspathFingerprinter.kt [hunk 2]
```diff
@@ -37,7 +37,7 @@ class KotlinCompileClasspathFingerprinter(
     stringInterner: StringInterner
 ) : AbstractFileCollectionFingerprinter(
     ClasspathFingerprintingStrategy.compileClasspath(
-        CachingResourceHasher(AbiExtractingClasspathResourceHasher(KotlinApiClassExtractor()), cacheService),
+        CachingResourceHasher(AbiExtractingClasspathResourceHasher.withoutFallback(KotlinApiClassExtractor()), cacheService),
```
Comment (octylFractal) [inline subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinCompileClasspathFingerprinter.kt:40]: I am curious why Kotlin does not use the fallback here.

**Review by octylFractal — CHANGES_REQUESTED** [review]
Overall looks good, just a minor question on the tests, and a request for further explanation.

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinCompileClasspathFingerprinter.kt (hunk 2 above)
Comment (ghale) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinCompileClasspathFingerprinter.kt:40]: I don't pretend to fully understand, but they have explicit tests to ensure that, for instance, it doesn't recompile scripts in certain scenarios (e.g. bas class file).  With the input fingerprinting which this change targets, we're just changing the nature of the fallback (i.e. fallback to hash just the class instead of hashing the entire zip).  With the kotlin script classpath fingerprinting, there was no existing fallback at all, the exception would just boil up and be handling prior to compilation.  If we add this class-level fallback to the Kotlin script classpath fingerprinting, this would now not error out anymore but would silently hash the inputs and continue.  I assume that this would possibly create a different, more obscure failure message during compilation.

It's entirely possible that the kotlin stuff could/should be made to use this fallback as well, but it seemed like a separate concern from what I was trying to fix here.  So I decided to leave that functionality unchanged for now and figured we could address it later.

File: subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaGroovyCompileAvoidanceIntegrationSpec.groovy (hunk 1 above)
Comment (ghale) [reply subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaGroovyCompileAvoidanceIntegrationSpec.groovy:855]: In this case, a has changed a class file in an ABI-compatible way (change to the signature of a private method) so we expect a to recompile, but b to _not_ recompile, even though a is now slightly different.  Project a also has a poison class file in its outputs, though.  Previously, this would cause the hashing to blow up, fallback to hashing the entire jar, and then cause b to recompile because of the changed private method.  Now, it catches the poison class file, hashes only that class in its entirety and then continues hashing the ABI of the other non-poison class files.  The hash of a's classes therefore does not change and b is skipped as we expect.

I think the conditions above are correct, but it's easy to get confused.  Let me know if I'm missing something.

File: subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinCompileClasspathFingerprinter.kt (hunk 2 above)
Comment (octylFractal) [reply subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinCompileClasspathFingerprinter.kt:40]: Okay, that works for me.

File: subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaGroovyCompileAvoidanceIntegrationSpec.groovy (hunk 1 above)
Comment (octylFractal) [reply subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaGroovyCompileAvoidanceIntegrationSpec.groovy:855]: I think I got mixed up while reviewing, yea. This looks good on second pass.

**Review by octylFractal — APPROVED** [review]

**Comment by ghale** [comment]
@bot-gradle test and merge

**Comment by ghale** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge
