### PR TITLE
Fix manifest attribute evaluation when merging values in jar task

### LINKED ISSUE #14972: archiveVersion does not work in manifest file creation
Gradle 6.7 build complains about
```
The AbstractArchiveTask.version property has been deprecated.
This is scheduled to be removed in Gradle 7.0. Please use the
archiveVersion property instead. See https://docs.gradle.org/6.7/dsl
/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#
org.gradle.api.tasks.bundling.AbstractArchiveTask:version for more details.
```
When changing `build.gradle` according to https://docs.gradle.org/current/userguide/building_java_projects.html#sec:jar_manifest to
```gradle
jar {   
        manifest {
                from("src/main/resources/META-INF/MANIFEST.MF")
                attributes(
                        "Implementation-Title": project.name,
                        "Implementation-Version": archiveVersion)
        }
}
```
the entry in the `MANIFEST.MF` created is
```
Implementation-Version: task ':jar' property 'archiveVersion'
```
With `version` it works as expected.

### Expected Behavior
The entry in the `MANIFEST.MF` should be
```
Implementation-Version: 1.0.0-SNAPSHOT
```

### Current Behavior
The entry in the `MANIFEST.MF`  is
```
Implementation-Version: task ':jar' property 'archiveVersion'
```

### PR DESCRIPTION
**Pull request by donat**
Fixes #14972

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle QFL

**Comment by donat** [comment]
@bot-gradle test QuickFeedbackLinux

File: subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifestMergeDetails.java [hunk 1]
```diff
@@ -55,6 +55,13 @@ public String getMergeValue() {
 
     @Override
     public String getValue() {
+        //todo: issue warning
+        //todo: remove usages from test
+        return value.toString();
```
Comment (donat) [inline subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifestMergeDetails.java:60]: I think this should work as follows:
- if the value is Provider then print warning about early eval and return value.get()
- otherwise, return value.toString()

**Comment by jbartok** [comment]
@bot-gradle test QuickFeedbackLinux

**Comment by jbartok** [comment]
@bot-gradle test QuickFeedbackLinux

**Comment by jbartok** [comment]
@bot-gradle

**Comment by jbartok** [comment]
@bot-gradle test rFM

File: subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/ManifestMergeDetails.java [hunk 2]
```diff
@@ -40,11 +43,24 @@
     String getMergeValue();
 
     /**
-     * Returns the value for the key of the manifest after the merge takes place. By default this is the value
-     * of the source for the merge.
+     * Returns the value for the key of the manifest after the merge takes place. By
+     * default this is the value of the source for the merge.
```
Comment (donat) [inline subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/ManifestMergeDetails.java:47]: Please add `@see #getRawValue()` to the javadoc.

File: subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifestMergeDetails.java [hunk 3]
```diff
@@ -55,6 +57,18 @@ public String getMergeValue() {
 
     @Override
     public String getValue() {
+        if (value instanceof Provider) {
+            DeprecationLogger.deprecateMethod(ManifestMergeDetails.class, "getValue()")
+                .withAdvice("Please use #getRawValue() instead.")
+                .willBeRemovedInGradle8()
```
Comment (donat) [inline subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifestMergeDetails.java:63]: Instead of deprecating, we might want to change this to `willbecomeAnErrorInGradle8`.

@big-guy WDYT?

**Review by donat — COMMENTED** [review]
Looks good. Just a couple of thoughts.

**Comment by jbartok** [comment]
@bot-gradle test rFM

File: subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifestMergeDetails.java (hunk 3 above)
Comment (jbartok) [reply subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifestMergeDetails.java]: You are absolutely right Sterling. After some more investigation I realise now what confused me. 

It was the observation that when you have no merging going on (ie. no template manifest file to merge with), then what comes out of `DefaultManifest.getEffectiveManifestInternal(...)` contain `Providers` and not materialised values. And then I thought that if we force the materialisation sooner, that's going to be an early evaluation. 

But what I failed to notice was that the `Providers` coming out of `DefaultManifest.getEffectiveManifestInternal(...)` are being made to materialise their values right after it, so it doesn't matter if we do that a bit sooner in the code.

So yes, your fix is much simpler, makes more sense and solves the problem. I'll adopt it.

**Comment by jbartok** [comment]
@bot-gradle test rFM

File: subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifestMergeSpec.java [hunk 4]
```diff
@@ -117,16 +118,28 @@ private void mergeSection(String section, DefaultManifest mergedManifest, Attrib
             }
             addMergeDetailToManifest(section, mergedManifest, mergeDetails);
         }
+
+        System.out.println();
```
Comment (donat) [inline subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifestMergeSpec.java:122]: Some leftover

**Comment by jbartok** [comment]
@bot-gradle test rFM

**Comment by jbartok** [comment]
@bot-gradle test rFM
