### PR TITLE
Cache default PgpSignatory when in-memory signing is used

### LINKED ISSUE #26154: 8.1 configuration is stuck at 100% for a while when signing is enabled
### Current Behavior

Follow up from [this slack thread](https://www.linen.dev/s/gradle-community/t/14160073/any-insights-what-could-explain-the-build-staying-stuck-just#dd0c57a4-d53b-4811-b821-0d4c63234182)

The configuration bar stays at 100% for minutes when trying to publish [our project](https://github.com/apollographql/apollo-kotlin):

```
<=============> 100% CONFIGURING [1m 35s]
> IDLE
```

When publishing all our modules, it goes up to 15min and more. You can see an example for 1 module in [this build scan](https://scans.gradle.com/s/7br4uchy5dvlw/timeline)

Upon investigation, this seems to be a regression in Gradle 8.1. A lot of time is spent in `computeCachedSignatures`, maybe [this commit about Signing + CC](https://github.com/gradle/gradle/pull/23262/files#diff-7300cc50bfad93a6bc8e7e7502550734c23b9798f476a2f1ecb3ae16c2dd75c3)?

Trying to publish a single module with 8.0 brings back the "stuck" time from ~1min (without CC) to ~10s (without CC) (which is already a lot but maybe there's not other way?)

We're using 2048 bit RSA keys for signing.

### Expected Behavior

Get the performance back to 8.0

Additionally, it'd be nice if:
* there was something output in the build instead of just `Configuring 100%`
* the "stuck" time was down to ~0? What is the reason to compute the signatures during configuration? Or looks like it's loading the private key several times? 

### Context (optional)

async-profiler output with SVG flame graph:

[profile-out-9.zip](https://github.com/gradle/gradle/files/12398096/profile-out-9.zip)

Screenshot 2023-08-21 at 17 36 54

### Steps to Reproduce

Publish a large project with signing enabled. 

You can try with [apollo-kotlin](https://github.com/apollographql/apollo-kotlin):

```
export GPG_PRIVATE_KEY='-----BEGIN PGP PRIVATE KEY BLOCK-----
...
-----END PGP PRIVATE KEY BLOCK-----
'
GPG_PRIVATE_KEY_PASSWORD=foobar
./gradlew publishToMavenLocal
```

### Gradle version

8.3

### Gradle version that used to work

8.0

### Build scan URL (optional)

https://scans.gradle.com/s/7br4uchy5dvlw

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by mlopatkin**
Computing a PGPSecretKey from armored text representation is suprisingly expensive. If in-memory PGP key is used, `getDefaultSignatory` gets called a lot when deducing task dependencies, fingerprinting task inputs, and storing the configuration cache, so caching is a good improvement.

This commit improves signing performance of the reproducer project with 5 signing tasks and about a dozen artifacts from 68s to 5s.

Fixes #26154.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, PT

File: subprojects/security/src/main/java/org/gradle/security/internal/pgp/BaseInMemoryPgpSignatoryProvider.java [hunk 1]
```diff
@@ -43,26 +44,24 @@ public class BaseInMemoryPgpSignatoryProvider implements BaseSignatoryProvider<P
...
         this(null, defaultSecretKey, defaultPassword);
     }
 
     public BaseInMemoryPgpSignatoryProvider(String defaultKeyId, String defaultSecretKey, String defaultPassword) {
-        this.defaultKeyId = defaultKeyId;
-        this.defaultSecretKey = defaultSecretKey;
-        this.defaultPassword = defaultPassword;
+        this.defaultSignatory = Lazy.locking().of(() -> {
+            if (defaultSecretKey != null && defaultPassword != null) {
+                return createSignatory("default", defaultKeyId, defaultSecretKey, defaultPassword);
```
Comment (bamboo) [inline subprojects/security/src/main/java/org/gradle/security/internal/pgp/BaseInMemoryPgpSignatoryProvider.java:56]: ❓ Should we try to prevent mutation of `defaultSecretKey` and `defaultPassword` after the signature has been computed?

File: subprojects/security/src/main/java/org/gradle/security/internal/pgp/BaseInMemoryPgpSignatoryProvider.java [hunk 2]
```diff
@@ -43,26 +44,24 @@ public class BaseInMemoryPgpSignatoryProvider implements BaseSignatoryProvider<P
 
     private final PgpSignatoryFactory factory = new PgpSignatoryFactory();
     private final Map<String, PgpSignatory> signatories = new LinkedHashMap<>();
-    private final String defaultKeyId;
-    private final String defaultSecretKey;
-    private final String defaultPassword;
+    private final Lazy<PgpSignatory> defaultSignatory;
```
Comment (bamboo) [inline subprojects/security/src/main/java/org/gradle/security/internal/pgp/BaseInMemoryPgpSignatoryProvider.java:47]: ❓ Should the signatory be stored in the configuration cache?

File: subprojects/security/src/main/java/org/gradle/security/internal/pgp/BaseInMemoryPgpSignatoryProvider.java (hunk 1 above)
Comment (mlopatkin) [reply subprojects/security/src/main/java/org/gradle/security/internal/pgp/BaseInMemoryPgpSignatoryProvider.java:56]: >Should we try to prevent mutation of defaultSecretKey and defaultPassword after the signature has been computed?

I don't fully understand your point. The key and password stored in this class could not be mutated before, and cannot be mutated now. You can change the default signature but it would replace the provider in `SigningExtension`.

You can, in theory, change the signature between sign task actions and get surprising result, but I feel that addressing that possibility is out of scope of this issue.

Comment (bamboo) [reply subprojects/security/src/main/java/org/gradle/security/internal/pgp/BaseInMemoryPgpSignatoryProvider.java:56]: Nevermind, I was reading these as task fields, not as final fields of an utility class.

File: subprojects/security/src/main/java/org/gradle/security/internal/pgp/BaseInMemoryPgpSignatoryProvider.java (hunk 2 above)
Comment (bamboo) [reply subprojects/security/src/main/java/org/gradle/security/internal/pgp/BaseInMemoryPgpSignatoryProvider.java:47]: Got it.

**Comment by mlopatkin** [comment]
I looked at other signing options. `GnupgSignatory` is lightweight, it only does heavy lifting when actually signing. The property-based codepath is affected by the slowdown, unfortunately.

**Comment by mlopatkin** [comment]
> I looked at other signing options. `GnupgSignatory` is lightweight, it only does heavy lifting when actually signing. The property-based codepath is affected by the slowdown, unfortunately.

I filed #26256 to follow-up for the property-based codepath. At least, fixing in-memory use case gives people a workaround.

**Review by abstratt — APPROVED** [review]
Short and sweet!

**Comment by bamboo** [comment]
@gradle/bt-jvm anything against merging this?

**Comment by abstratt** [comment]
@bot-gradle test PRF, PT

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
@bot-gradle test and merge
