### PR TITLE
Capture broken builds for all exceptions in ResilientGradleBuildBuilder

### LINKED ISSUE #35319: Handle runtime failures with ResilientGradleBuildBuilder
In https://github.com/gradle/gradle/pull/34488 we introduced ResilientGradleBuildBuilder that returns `GradleBuild` model even on failures. But it looks like we handle only compilation issues and not runtime issues.

We handle exceptions here:
- https://github.com/gradle/gradle/blob/9dbfa9db30e2315f2c0b7dbf42e57af0712b5b23/platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/ResilientGradleBuildBuilder.java#L118
- https://github.com/gradle/gradle/blob/9dbfa9db30e2315f2c0b7dbf42e57af0712b5b23/subprojects/core/src/main/java/org/gradle/initialization/ScriptEvaluatingSettingsProcessor.java#L75

We should relax exception type and handle also runtime exceptions, e.g. when build scripts configuration fails or applying plugin fails.
We should also add integration tests for that case.

### PR DESCRIPTION
**Pull request by reinsch82**
Fixes #35319 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by reinsch82** [comment]
@bot-gradle test this

File: platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r930/ResilientGradleBuildSyncCrossVersionSpec.groovy [hunk 1]
```diff
@@ -59,6 +59,19 @@ class ResilientGradleBuildSyncCrossVersionSpec extends ToolingApiSpecification {
         model.failures.toString().contains("Script compilation error")
     }
 
+    def "receive root project with throwing settings file"() {
```
Comment (asodja) [inline platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r930/ResilientGradleBuildSyncCrossVersionSpec.groovy]: ❓ Is this name of a test correct? It seems that in this case we get only exception but no root project

File: platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r930/ResilientGradleBuildSyncCrossVersionSpec.groovy [hunk 2]
```diff
@@ -59,6 +59,19 @@ class ResilientGradleBuildSyncCrossVersionSpec extends ToolingApiSpecification {
...
+        given:
+        settingsKotlinFile << """
+            throw GradleException("Gradle exception boom !!!")
+        """
+
+        when:
+        def model = runFetchModelAction()
+
+        then:
+        model.failures.toString().contains("Gradle exception boom !!!")
```
Comment (asodja) [inline platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r930/ResilientGradleBuildSyncCrossVersionSpec.groovy:76]: ❓ Can we also assert that there is no models for projects here?

File: platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r930/ResilientKotlinDslScriptsModelBuilderCrossVersionSpec.groovy [hunk 3]
```diff
@@ -649,13 +647,13 @@ class ResilientKotlinDslScriptsModelBuilderCrossVersionSpec extends ToolingApiSp
 
         when:
         settingsPlugin << """ broken !!! """
-        fails {
+        def mod = succeeds {
```
Comment (asodja) [inline platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r930/ResilientKotlinDslScriptsModelBuilderCrossVersionSpec.groovy]: 💅 Could we use a better name, maybe `result` or `model`?

File: platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r930/ResilientKotlinDslScriptsModelBuilderCrossVersionSpec.groovy [hunk 4]
```diff
@@ -649,13 +647,13 @@ class ResilientKotlinDslScriptsModelBuilderCrossVersionSpec extends ToolingApiSp
...
             action(KotlinModelAction.resilientModel(ROOT_PROJECT_FIRST)).withArguments("-Dorg.gradle.internal.resilient-model-building=true").run()
         }
 
         then:
-        def e = thrown(GradleConnectionException)
-        e.message.startsWith("The supplied build action failed with an exception.")
+        mod.failures.size() == 2
+        mod.scriptModels.size() == 3
```
Comment (asodja) [inline platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r930/ResilientKotlinDslScriptsModelBuilderCrossVersionSpec.groovy]: ❓ Can we also compare this model with original similarly as in other tests? Otherwise we should remove original model query, but I rather see that we compare the content if we can

File: subprojects/core/src/main/java/org/gradle/internal/service/scopes/BrokenBuildsCapturingListener.java [hunk 5]
```diff
@@ -51,12 +51,30 @@ public Map<BuildState, Failure> getBrokenBuilds() {
...
     @Override
     public Map<SettingsInternal, Failure> getBrokenSettings() {
         return brokenSettings;
     }
+
+    @Override
+    public boolean isHandled(GradleException e) {
+        // Check if the exception or any of its causes are in the broken builds or settings
+        Throwable current = e;
+        while (current != null) {
```
Comment (asodja) [inline subprojects/core/src/main/java/org/gradle/internal/service/scopes/BrokenBuildsCapturingListener.java]: ❓ What exactly are we doing here and why we need this?

File: platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r930/ResilientGradleBuildSyncCrossVersionSpec.groovy (hunk 2 above)
Comment (reinsch82) [reply platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r930/ResilientGradleBuildSyncCrossVersionSpec.groovy:76]: I can actually assert that there is a model :)

**Comment by reinsch82** [comment]
@bot-gradle test this

File: platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/ResilientGradleBuildBuilder.java [hunk 6]
```diff
@@ -115,12 +120,7 @@ protected void ensureProjectsLoaded(BuildState target) {
             try {
                 target.ensureProjectsLoaded();
             } catch (GradleException e) {
-                if (e.getCause() instanceof org.gradle.kotlin.dsl.support.ScriptCompilationException) {
-                    this.brokenBuilds.putAll(failedIncludedBuildsRegistry.getBrokenBuilds());
-                    this.brokenSettings.putAll(failedIncludedBuildsRegistry.getBrokenSettings());
-                    return;
-                }
-                throw e;
+                failures.add(failureFactory.create(e));
```
Comment (asodja) [inline platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/ResilientGradleBuildBuilder.java:123]: 👍

File: subprojects/core/src/main/java/org/gradle/initialization/ScriptEvaluatingSettingsProcessor.java [hunk 7]
```diff
@@ -72,8 +71,8 @@ public SettingsState process(
         settings.getCaches().finalizeConfiguration(gradle);
         try {
             applySettingsScript(settingsScript, settings);
-        } catch (LocationAwareException e) {
-            buildIncludeListener.settingsScriptFailed(state.getSettings(), e);
+        } catch (Exception e) {
+            buildIncludeListener.settingsScriptFailed(settings, e);
```
Comment (asodja) [inline subprojects/core/src/main/java/org/gradle/initialization/ScriptEvaluatingSettingsProcessor.java]: ❓ Where we use these exceptions after? Can we just capture settings object?

File: subprojects/core/src/main/java/org/gradle/internal/composite/DefaultBuildIncluder.java [hunk 8]
```diff
@@ -66,12 +68,7 @@ public CompositeBuildParticipantBuildState includeBuild(IncludedBuildSpec includ
         BuildDefinition buildDefinition = toBuildDefinition(includedBuildSpec, gradle);
         if (includedBuildSpec.rootDir.equals(rootBuild.getBuildRootDir())) {
             buildRegistry.onRootBuildInclude(rootBuild, gradle.getOwner(), buildDefinition.isPluginBuild());
-            try {
-                coordinator.prepareRootBuildForInclusion();
-            } catch (Exception e) {
-                buildIncludeListener.buildInclusionFailed(rootBuild, e);
-                throw e;
-            }
+            coordinator.prepareRootBuildForInclusion();
```
Comment (asodja) [inline subprojects/core/src/main/java/org/gradle/internal/composite/DefaultBuildIncluder.java:71]: ❓ Why we can remove this?

Comment (asodja) [reply subprojects/core/src/main/java/org/gradle/internal/composite/DefaultBuildIncluder.java:71]: Is because `coordinator.prepareRootBuildForInclusion();` can't throw exception?

File: subprojects/core/src/main/java/org/gradle/internal/service/scopes/BrokenBuildsCapturingListener.java [hunk 9]
```diff
@@ -40,9 +38,8 @@ public BrokenBuildsCapturingListener(
     }
 
     @Override
-    public void buildInclusionFailed(BuildState buildState, @Nullable Exception exception) {
-        Failure failure = failureFactory.create(exception);
-        brokenBuilds.put(buildState, failure);
+    public void buildInclusionFailed(BuildState buildState, Exception exception) {
+        brokenBuilds.put(buildState, failureFactory.create(exception));
```
Comment (asodja) [inline subprojects/core/src/main/java/org/gradle/internal/service/scopes/BrokenBuildsCapturingListener.java]: ❓ Do we still need to store exception? It seems it's not used anywhere

File: subprojects/core/src/main/java/org/gradle/internal/service/scopes/BrokenBuildsCapturingListener.java [hunk 10]
```diff
@@ -51,7 +48,7 @@ public Map<BuildState, Failure> getBrokenBuilds() {
     }
 
     @Override
-    public void settingsScriptFailed(SettingsInternal settingsScript, LocationAwareException e) {
+    public void settingsScriptFailed(SettingsInternal settingsScript, Exception e) {
         getBrokenSettings().put(settingsScript, failureFactory.create(e));
```
Comment (asodja) [inline subprojects/core/src/main/java/org/gradle/internal/service/scopes/BrokenBuildsCapturingListener.java]: ❓ Also here: Do we still need to store exception? It seems it's not used anywhere

File: subprojects/core/src/main/java/org/gradle/internal/composite/DefaultBuildIncluder.java (hunk 8 above)
Comment (reinsch82) [reply subprojects/core/src/main/java/org/gradle/internal/composite/DefaultBuildIncluder.java:71]: There is only one [implementation](https://github.com/gradle/gradle/blob/ec655c321e5ccb0af2a090d8f29e114a66b6dce3/subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildInclusionCoordinator.java#L91) and it can't throw

File: platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/ResilientGradleBuildBuilder.java [hunk 11]
```diff
@@ -132,17 +132,20 @@ protected DefaultGradleBuild convert(BuildState targetBuild) {
...
             all.put(targetBuild, model);
 
-            // Make sure the project tree has been loaded and can be queried (but not necessarily configured)
             ensureProjectsLoaded(targetBuild);
 
-            Failure failure = brokenBuilds.get(targetBuild);
-            if (failure == null && !brokenSettings.isEmpty()) {
-                Map.Entry<SettingsInternal, Failure> settingsEntry = brokenSettings.entrySet().iterator().next();
-                ProjectDescriptor rootProject = settingsEntry.getKey().getRootProject();
+            Failure failure = failedIncludedBuildsRegistry.getBrokenBuilds().get(targetBuild);
```
Comment (asodja) [inline platforms/ide/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/ResilientGradleBuildBuilder.java]: 💅 Do we need this failure anywhere? Or could we just do:
```
failedIncludedBuildsRegistry.getBrokenBuilds().contains(targetBuild)
```

and remove failure from `BuildIncludeListener`?

File: subprojects/core/src/main/java/org/gradle/internal/service/scopes/BrokenBuildsCapturingListener.java [hunk 12]
```diff
@@ -51,12 +50,12 @@ public Map<BuildState, Failure> getBrokenBuilds() {
...
     @Override
-    public void settingsScriptFailed(SettingsInternal settingsScript, LocationAwareException e) {
-        getBrokenSettings().put(settingsScript, failureFactory.create(e));
+    public void settingsScriptFailed(SettingsInternal settingsScript) {
+        getBrokenSettings().add(settingsScript);
     }
 
     @Override
-    public Map<SettingsInternal, Failure> getBrokenSettings() {
+    public Collection<SettingsInternal> getBrokenSettings() {
```
Comment (asodja) [inline subprojects/core/src/main/java/org/gradle/internal/service/scopes/BrokenBuildsCapturingListener.java]: 💅 Since we use a Set, we could also just return `Set` type to be more specific

**Review by asodja — APPROVED** [review]
LGTM
