### PR TITLE
Log location of JVM crash log

### LINKED ISSUE #12345: Show path of hs_err_pid file when daemon disappears
### Expected Behavior

When the Gradle daemon crashes, it would be great if the Gradle client would print the filepath of the hs_pid_file generated by the Gradle daemon (assuming that that file exists).
It would also be nice to print the first ~80 lines of that file too.

### Current Behavior

Currently when the Gradle daemon crashes, the Gradle client doesn't mention the existence of an hs_err_pid file to the user.

### Context

The AndroidX team has been observing our Gradle daemon to be crashing itermittently : http://issuetracker.google.com/issues/146217083 . Because our crashes occur nearly exclusively on continuous integration servers, we don't see the hs_err_pid files when they are generated (they're created in the working directory from which Gradle was executed, which is a directory that we otherwise wouldn't need to inspect).

However, we found it was super useful to inspect the hs_err_pid file: http://issuetracker.google.com/issues/146217083#comment39 .

If Gradle would display the filepath of the hs_err_pid file, it would be easier for developers to think to look for it and to make sure that the builder copies it into a location where it will be visible after the build completes.

Thanks

### PR DESCRIPTION
**Pull request by wolfs**
on Daemon crash if found.

Fixes #12345

### CODE REVIEW

File: subprojects/launcher/src/main/java/org/gradle/launcher/daemon/client/DaemonClient.java [hunk 1]
```diff
@@ -239,9 +243,23 @@ private Result handleDaemonDisappearance(Build build, DaemonDiagnostics diagnost
...
+            LOGGER.error("JVM crash log found: " + new ConsoleRenderer().asClickableFileUrl(crashLogFile))
+        );
         throw new DaemonDisappearedException();
     }
 
+    private Optional<File> findCrashLogFile(Build build, DaemonDiagnostics diagnostics) {
+        String crashLogFileName = "hs_err_pid" + diagnostics.getPid() + ".log";
+        List<File> candidates = ImmutableList.of(
+            new File(build.getParameters().getCurrentDir(), crashLogFileName),
+            new File(diagnostics.getDaemonLog().getParent(), crashLogFileName)
```
Comment (lptr) [inline subprojects/launcher/src/main/java/org/gradle/launcher/daemon/client/DaemonClient.java]: We should also look in the temp directory according to https://stackoverflow.com/a/5154619/104894:

> Where possible the file is created in the working directory of the process. In the event that the file cannot be created in the working directory (insufficient space, permission problem, or other issue) **then the file is created in the temporary directory for the operating system.** On Solaris and Linux the temporary directory is /tmp. On Windows the temporary directory is specified by the value of the TMP environment variable, or if that is not defined, the value of the TEMP environment variable.

Comment (wolfs) [reply subprojects/launcher/src/main/java/org/gradle/launcher/daemon/client/DaemonClient.java]: I am looking at the temp directory as well. Please have another look!
