### PR TITLE
Fix using inner classes in precompiled buildscripts

### LINKED ISSUE #33528: Inner classes that reference external plugin classes cannot be used in precompiled buildscripts
### Current Behavior

Given a precompiled buildscript like this:
```groovy
            plugins {
                id("parent")
            }

            new ParentThing() {
            }
```,
assuming a parent plugin with the given id and a class `ParentThing` in its JAR, it fails to compile with the following message:
```
Could not compile script '<root>/src/main/groovy/test.gradle'.
> startup failed:
  script '<root>/src/main/groovy/test.gradle': 6: unable to resolve class ParentThing
   @ line 6, column 31.
                 new ParentThing() {
                                   ^
  
  1 error
```

### Expected Behavior

It should compile fine, as the class exists in the parent plugin.

### Context (optional)

This issue was originally found in the DV build.

### Self-contained Reproducer Project

None, a test will be provided with a forthcoming PR.

### Gradle version

9.0.0-milestone-8

### Gradle version that used to work

8.14

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #33528 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/extensibility/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/PrecompiledGroovyPluginsIntegrationTest.groovy [hunk 1]
```diff
@@ -677,6 +678,48 @@ class PrecompiledGroovyPluginsIntegrationTest extends AbstractIntegrationSpec {
...
+
+        buildFile(getBuildFile(GradleDsl.GROOVY, "parent"), """
+            plugins {
+                id("groovy-gradle-plugin")
+            }
+        """)
+        file("src/main/groovy/parent.gradle") << """
+        """
+        file("src/main/groovy/ParentThing.groovy") << """
+            abstract class ParentThing {}
```
Comment (big-guy) [inline platforms/extensibility/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/PrecompiledGroovyPluginsIntegrationTest.groovy:713]: Did this have to be in a separate project or could this be in the same project?

File: subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/SubsetScriptTransformer.java [hunk 2]
```diff
@@ -90,8 +91,14 @@ public void call(SourceUnit source) throws CompilationFailedException {
         // Remove all the classes other than the main class
         source.getAST().getClasses().removeIf(classNode -> classNode != scriptClass);
 
-        // Remove all the methods from the main class
+        // Remove all the inner classes and methods from the main class
         if (scriptClass != null) {
+            Iterator<InnerClassNode> innerClasses = scriptClass.getInnerClasses();
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/SubsetScriptTransformer.java:96]: What's changed on the Groovy side that's made the inner classes appear as part of the build script now?  Were they being removed in some other way or were inner classes not considered inner classes before?

**Review by big-guy — COMMENTED** [review]
questions

File: subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/SubsetScriptTransformer.java (hunk 2 above)
Comment (octylFractal) [reply subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/SubsetScriptTransformer.java:96]: Groovy 4 began to pull on inner classes during compilation in a way that requires they be resolved: https://github.com/apache/groovy/commit/2eb76dde8857c3f81926022e180a2541ecdbb509#diff-274fc4fc6bae462698463f05c0a81fea010871186eb70ddf5ae7f337cba3e90dR1343

**Review by big-guy — APPROVED** [review]
