### PR TITLE
Fix null handling when mapping `AssertionFailedError`

### LINKED ISSUE #27871: "Failed to map supported failure" message when using JUnit `Assertions.fail`
### Current Behavior

When using `Assertions.fail` in my code, I receive the following message in the Gradle test output:

> Failed to map supported failure 'org.opentest4j.AssertionFailedError: - sample failure' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@2d9df336': Cannot invoke "Object.getClass()" because "obj" is null

The `OpenTestAssertionFailedMapper` assumes that any `AssertionFailedError` must have `actual` and `expected` values, so it throws an NPE when [calling getClass](https://github.com/gradle/gradle/blob/master/platforms/jvm/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/mappers/OpenTestAssertionFailedMapper.java#L50) on the expected value.

### Expected Behavior

No mapping error message should be printed to the output.

### Context (optional)

`AssertionFailedError` can have no `expected` or `actual` value when using several of the JUnit assertions e.g. `assertDoesNotThrow`, `assertTimeout`.

### Steps to Reproduce

Use `Assertions.fail` or one of the other affected assertions in a JUnit 5 test.

### Gradle version

8.5

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by hegyibalint**
Fixes #27871

### CODE REVIEW

**Comment by hegyibalint** [comment]
@bot-gradle test RFM

File: platforms/jvm/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/TestFailureMapper.java [hunk 1]
```diff
@@ -80,9 +81,29 @@ public boolean supports(Class<?> cls) {
     /**
      * Utility method to invoke a method on an object by reflective means.
      */
-    protected static <T> T invokeMethod(Object obj, String methodName, Class<T> targetClass) throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
+    @Nullable
+    protected static <T> T invokeMethod(@Nullable Object obj, String methodName, Class<T> targetClass) throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
```
Comment (jvandort) [inline platforms/jvm/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/TestFailureMapper.java:85]: Does it make sense to check if `obj` is null before calling this method instead of making this method accept `null`?

**Review by marcphilipp — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle merge
