### PR TITLE
Fix CC serialization issues caused by AccessTracking classes

### LINKED ISSUE #32564: Configuration cache error: Class 'org.gradle.internal.classpath.Instrumented$$Lambda$2709/0x00000098020e55e0' cannot be encoded
### Current Behavior

Configuration cache error: Build file 'build.gradle.kts': Class 'org.gradle.internal.classpath.Instrumented$$Lambda$2709/0x00000098020e55e0' cannot be encoded because class loader 'VisitableURLClassLoader(ant-and-gradle-loader)' of type 'org.gradle.internal.classloader.VisitableURLClassLoader' could not be encoded and the class is not available through the default class loader.

### Expected Behavior

No error.

### Context (optional)

_No response_

### Self-contained Reproducer Project

[project.zip](https://github.com/user-attachments/files/19011349/project.zip)

```kotlin
// build.gradle.kts

abstract class SystemGetEnvSource :
  ValueSource<Map<String, String?>, ValueSourceParameters.None> {

  override fun obtain(): Map<String, String?> = System.getenv()
}

val currentVars: Provider<Map<String, String?>> = providers.of(SystemGetEnvSource::class.java) { }

println("got ${currentVars.get().size} env vars")
```

Run `./gradlew help`

Observe configuration cache storage problem:

```
Parallel Configuration Cache is an incubating feature.
Calculating task graph as no cached configuration is available for tasks: help

> Configure project :
got 58 env vars

> Task :help

Welcome to Gradle 8.13.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see more detail about a task, run gradlew help --task <task>

To see a list of command-line options, run gradlew --help

For more detail on using Gradle, see https://docs.gradle.org/8.13/userguide/command_line_interface.html

For troubleshooting, visit https://help.gradle.org

[Incubating] Problems report is available at: file:///Users/dev/projects/tmp/gradle-classloader-error-weird/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Build file 'build.gradle.kts': Class 'org.gradle.internal.classpath.Instrumented$$Lambda$2709/0x00000098020e55e0' cannot be encoded because class loader 'VisitableURLClassLoader(ant-and-gradle-loader)' of type 'org.gradle.internal.classloader.VisitableURLClassLoader' could not be encoded and the class is not available through the default class loader.
These are the known class loaders:
	- VisitableURLClassLoader(ClassLoaderScopeIdentifier.Id{coreAndPlugins:settings[:]:buildSrc[:]:root-project[:]:kotlin-dsl:/Users/dev/projects/tmp/gradle-classloader-error-weird/build.gradle.kts:Project/TopLevel/stage2(local)})
	- VisitableURLClassLoader(ClassLoaderScopeIdentifier.Id{coreAndPlugins:kotlin-dsl:/Users/dev/projects/tmp/gradle-classloader-error-weird/settings.gradle.kts:Settings/TopLevel/stage1(local)})
	- VisitableURLClassLoader(ClassLoaderScopeIdentifier.Id{coreAndPlugins:settings[:]:buildSrc[:]:kotlin-dsl:/Users/dev/projects/tmp/gradle-classloader-error-weird/build.gradle.kts:Project/TopLevel/stage1(local)})
Please report this error, run './gradlew --stop' and try again.

See the complete report at file:///Users/dev/projects/tmp/gradle-classloader-error-weird/build/reports/configuration-cache/bz7dzvjm2ewa3cqfxqbu4wptt/92foduwdx2d92cbjlly4vqi58/configuration-cache-report.html
> Class 'org.gradle.internal.classpath.Instrumented$$Lambda$2709/0x00000098020e55e0' not found in Gradle runtime class loader 'MixInLegacyTypesClassLoader(legacy-mixin-loader)' of type 'org.gradle.initialization.MixInLegacyTypesClassLoader'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 331ms
1 actionable task: 1 executed
Configuration cache entry discarded with 1 problem.
```

### Gradle version

8.13

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by mlopatkin**
They or their views can be used wholesale as task inputs, so they must be CC-serializable to some extent. Prior to this commit we were trying to serialize the getenv() result or views, like keySet(), as beans and failed because of non-serializable lambdas or JDK-internal classes inside.

This commit doesn't make the lambda serializable, but instead introduces serialization doubles. For starters, serializing the map or its view means that we're making everything a CC input. This means we don't need to track accesses in the deserialized value, and thus we can just store the contents, with some workarounds for CC serialization quirks.

We have to add another `--add-opens` because of
`System.getProperties().getEntries()`. Serializing the entries requires accessing the private `ConcurrentHashMap.MapEntry` class.

Fixes #32564.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle test this

File: platforms/core-configuration/input-tracking/src/integTest/groovy/org/gradle/internal/configuration/inputs/InputTrackingIntegrationTest.groovy [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+                @Input
+                Object toPrint
+
+                @TaskAction
+                def action() {
+                    println String.valueOf(toPrint)
+                }
+            }
+
+            tasks.register("printMap", PrintMapTask) {
```
Comment (alllex) [inline platforms/core-configuration/input-tracking/src/integTest/groovy/org/gradle/internal/configuration/inputs/InputTrackingIntegrationTest.groovy:43]: 💅 Rename to `printEnv` or something, since we print various data structures

File: platforms/core-configuration/input-tracking/src/main/java/org/gradle/internal/configuration/inputs/AccessTrackingProperties.java
Comment (alllex) [inline platforms/core-configuration/input-tracking/src/main/java/org/gradle/internal/configuration/inputs/AccessTrackingProperties.java:1]: While at it, can we drop this TODO, which seems to have been resolved?

https://github.com/gradle/gradle/blob/890137c1fad1e2effb3690e1d10d30539eb74c44/platforms/core-configuration/input-tracking/src/main/java/org/gradle/internal/configuration/inputs/AccessTrackingProperties.java#L99

File: platforms/core-configuration/input-tracking/src/integTest/groovy/org/gradle/internal/configuration/inputs/InputTrackingIntegrationTest.groovy [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+
+        then:
+        outputContains(expectedSecondResult)
+
+        where:
+        value                          | expectedFirstResult   | expectedSecondResult
+        "System.getenv()"              | "SOME_PROPERTY=value" | "SOME_PROPERTY=other"
+        "System.getenv().entrySet()"   | "SOME_PROPERTY=value" | "SOME_PROPERTY=other"
+        "System.getenv().keySet()"     | "SOME_PROPERTY"       | "SOME_PROPERTY"
+        "System.getenv().values()"     | "value"               | "other"
```
Comment (alllex) [inline platforms/core-configuration/input-tracking/src/integTest/groovy/org/gradle/internal/configuration/inputs/InputTrackingIntegrationTest.groovy:67]: 💭  We are printing out whatever happens to be in the env of the test executor. Should we make the expected sub-string to be a bit more unique?

**Review by alllex — APPROVED** [review]
LGTM!

Left a couple of tiny suggestions
