### PR TITLE
Make `JacocoReportAggregationPlugin` artifact views cc compatible

### LINKED ISSUE #26922: "JaCoCo Report Aggregation Plugin" fails when configuration cache is enabled (gradle plugin project)
### Current Behavior

Build failed with an exception:
```
* What went wrong:
Could not load the value of field `elements` of `org.gradle.configurationcache.serialization.codecs.ResolutionBackedFileCollectionSpec` bean found in field `classDirectories` of task `:testCodeCoverageReport` of type `org.gradle.testing.jacoco.tasks.JacocoReport`.
> org.gradle.testing.jacoco.plugins.JacocoReportAggregationPlugin$$Lambda$1936/0x000000f801396530
```

### Expected Behavior

Aggregated report is successfully created.

### Context (optional)

Getting a aggregated report on test coverage in a multi-module gradle plugin project.

### Steps to Reproduce

1. Clone project https://github.com/rmarma/jacoco-report-aggregation-problem
2. Run:
```
./gradlew :testCodeCoverageReport 
```
----------
Running with `--no-configuration-cache` completes successfully.

When changing plugin `kotlin-dsl` to `kotlin-dsl-base` in a project that is added to `jacocoAggregation`, the build also completes successfully with the configuration cache.

### Gradle version

8.4

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by bamboo**
By making the given component filter specs are serializable.

Fixes #26922

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test ACC

File: platforms/jvm/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoConfigurationCacheIntegrationTest.groovy [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+                }
+            }
+
+            dependencies {
+                jacocoAggregation(project(":plugin"))
+            }
+        '''
+        createDir('plugin') {
+            file('build.gradle.kts') << '''
+                plugins { `kotlin-dsl` }
```
Comment (jvandort) [inline platforms/jvm/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoConfigurationCacheIntegrationTest.groovy:59]: Do we really need to apply `kotlin-dsl` to replicate this issue? 

The linked issue states:

"When changing plugin kotlin-dsl to kotlin-dsl-base in a project that is added to jacocoAggregation, the build also completes successfully with the configuration cache."

What happens between kotlin-dsl and kotlin-dsl-base that causes this problem? Can we test that directly?

Comment (bamboo) [reply platforms/jvm/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoConfigurationCacheIntegrationTest.groovy:59]: Yes, `kotlin-dsl` is needed.

I haven't investigated what's the difference between the two plugins that could explain the problem but I think that can be done after the fix has been merged.

Comment (bamboo) [reply platforms/jvm/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoConfigurationCacheIntegrationTest.groovy]: The issue is actually triggered by `java-gradle-plugin`. It seems the publications it creates cause the component filters to be necessary (thus serialized to the configuration cache).

Comment (jvandort) [reply platforms/jvm/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoConfigurationCacheIntegrationTest.groovy]: Can we go deeper and manually reproduce what `java-gradle-plugin` does?

I'm worried that if the java-gradle-plugin implementation changes that this test will no longer actually test what we want

Comment (bamboo) [reply platforms/jvm/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoConfigurationCacheIntegrationTest.groovy]: That makes sense. I don't have the bandwidth right now though so I'm tempted to merge this as is (after adding an issue to the cc backlog to review the test coverage).

**Review by jvandort — APPROVED** [review]

File: platforms/jvm/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoConfigurationCacheIntegrationTest.groovy (hunk 1 above)
Comment (bamboo) [reply platforms/jvm/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoConfigurationCacheIntegrationTest.groovy]: Thanks

Comment (bamboo) [reply platforms/jvm/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoConfigurationCacheIntegrationTest.groovy]: FTR: [the issue](https://github.com/orgs/gradle/projects/63/views/7?filterQuery=subproject%3A%22Adoption%22+jacoco&pane=issue&itemId=46923389)
