### PR TITLE
Always coerce non-String attributes upon get() to handle classloader problems with included builds

### LINKED ISSUE #28695: Fetching an Attribute from an AttributeContainer returns `null`, even though the Attribute _is_ present.
### Current Behavior

`AttributeContainer#getAttribute` returns null for an attribute. However, the attribute _is_ present, and is shown as being present when all AttributeContainer keys and values are logged.

### Expected Behavior

It is possible to fetch Attributes from an AttributeContainer, if they are present.

### Context (optional)

I am trying to workaround a Gradle issue, where Gradle will sometimes ignore attributes.

Without fetching attributes it is not possible to aggregate files across subprojects.

Gradle does not provide a reasonable way of aggregating files across subprojects, which results in strange and confusing workarounds.

### Steps to Reproduce

1. [project.zip](https://github.com/gradle/gradle/files/14882375/project.zip)
2. Run `./gradlew :aggregation:dokkatoo:d2Reproducer`
3. Note that [`DokkatooFormatAttribute` has ID `dev.adamko.dokkatoo.format`](https://github.com/adamko-dev/dokkatoo/blob/f043cff987fbd11d51f467734ec8b7d95bf40d18/modules/dokkatoo-plugin/src/main/kotlin/dependencies/DokkatooAttribute.kt#L31-L32).
4. Observe that the logs show `variantAttrs[DokkatooAttribute.DokkatooFormatAttribute] null`
5. However, the logs also show that `dev.adamko.dokkatoo.format=html`

### Details

In file `aggregation/dokkatoo/build.gradle.kts`, line 69, the code fetches an Attribute from an AttributeContainer:

```kotlin
println("variantAttrs[DokkatooAttribute.DokkatooFormatAttribute] ${variantAttrs[DokkatooAttribute.DokkatooFormatAttribute]}")
```

This prints `variantAttrs[DokkatooAttribute.DokkatooFormatAttribute] null`.

However, on line 71, all contents of the AttributeContainer are logged:

```kotlin
logger.lifecycle("[...] variantAttrs:${variantAttrs.toMap()}")
```

This prints:

```
variantAttrs:{org.gradle.usage=dev.adamko.dokkatoo, dev.adamko.dokkatoo.format=html, dev.adamko.dokkatoo.module-component=ModuleOutputDirectories, artifactType=dokka-module-directory}
```

This demonstrates that the attribute, `dev.adamko.dokkatoo.format`, _is_ present, with a value of `html`.

### Gradle version

8.7

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by tresat**
If an attribute is produced in an included build, and consumed from a different included build, the type of the Attribute won't match, despite having the same name.  So we'll need to coerce these to get the expected attribute lookup behavior.

Fixes #28695.

Also patches a number of other holes in attribute containers, adding tests to ensure desired behavior.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

File: platforms/core-configuration/model-core/src/main/java/org/gradle/internal/snapshot/impl/IsolatedArray.java [hunk 1]
```diff
@@ -57,7 +58,7 @@ public Object[] isolate() {
     @Nullable
     @Override
     public <S> S coerce(Class<S> type) {
-        return null;
```
Comment (tresat) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/internal/snapshot/impl/IsolatedArray.java:60]: 💭 I suspect there aren't many List-valued attributes and this omission was never found.  It showed up in tests only we start coercing more aggresively.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/internal/snapshot/impl/IsolatedList.java [hunk 2]
```diff
@@ -55,6 +56,6 @@ public List<Object> isolate() {
     @Nullable
     @Override
     public <S> S coerce(Class<S> type) {
-        return null;
```
Comment (tresat) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/internal/snapshot/impl/IsolatedList.java:58]: 💭 Ditto here.

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/attributes/FreezableAttributeContainer.java [hunk 3]
```diff
@@ -95,14 +95,26 @@ public boolean contains(Attribute<?> key) {
...
-        return this;
-    }
-
     private void assertMutable() {
         if (delegate instanceof ImmutableAttributes) {
             throw new IllegalStateException(String.format("Cannot change attributes of %s after it has been locked for mutation", owner.getDisplayName()));
         }
     }
+
+    @Override
```
Comment (tresat) [inline platforms/software/dependency-management/src/main/java/org/gradle/api/internal/attributes/FreezableAttributeContainer.java:104]: 💭 Just implementing these to fix IDE warnings.

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java [hunk 4]
```diff
@@ -100,7 +99,7 @@ public boolean equals(Object o) {
         }
 
         for (Map.Entry<Attribute<?>, DefaultImmutableAttributesContainer> entry : hierarchy.entrySet()) {
-            if (!entry.getValue().value.isolate().equals(that.getAttribute(entry.getKey()))) {
+            if (!Objects.requireNonNull(entry.getValue().value.isolate()).equals(that.getAttribute(entry.getKey()))) {
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java:102]: 💭 I corrected a bunch of mislabeled nullability issues in this PR as well.

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java [hunk 5]
```diff
@@ -128,14 +127,21 @@ public <T> AttributeContainer attributeProvider(Attribute<T> key, Provider<? ext
...
+        } else {
+            return isolatable.isolate();
+        }
     }
 
     @Nullable
-    protected <T> Isolatable<T> getIsolatableAttribute(Attribute<T> key) {
-        DefaultImmutableAttributesContainer attributes = hierarchy.get(key);
+    /* package */ <T> Isolatable<T> getIsolatableAttribute(Attribute<T> key) {
+        DefaultImmutableAttributesContainer attributes = hierarchyByName.get(key.getName());
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java:144]: 💭 This is the actual fix.

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java [hunk 6]
```diff
@@ -83,7 +83,7 @@ public interface AttributeContainer extends HasAttributes {
      * @return the attribute value, or null if not found
      */
     @Nullable
-    <T> T getAttribute(Attribute<T> key);
+    <T> T getAttribute(@Nullable Attribute<T> key);
```
Comment (tresat) [inline subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java:86]: 💭 Santa Tracker supplies `null` keys.  I've updated the interface and all impls to make this clear.

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java [hunk 7]
```diff
@@ -128,14 +127,21 @@ public <T> AttributeContainer attributeProvider(Attribute<T> key, Provider<? ext
...
+        } else {
+            return isolatable.isolate();
+        }
     }
 
     @Nullable
-    protected <T> Isolatable<T> getIsolatableAttribute(Attribute<T> key) {
-        DefaultImmutableAttributesContainer attributes = hierarchy.get(key);
+    /* package */ <T> Isolatable<T> getIsolatableAttribute(@Nullable Attribute<T> key) {
+        DefaultImmutableAttributesContainer attributes = key != null ? hierarchyByName.get(key.getName()) : null;
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java:144]: 💭 Added null check here.

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultMutableAttributeContainer.java [hunk 8]
```diff
@@ -125,8 +125,8 @@ private <T> void checkInsertionAllowed(Attribute<T> key) {
      * @param valueType the value type to check
      * @param attribute the attribute containing a type to check against
      */
-    private <T> void assertAttributeTypeIsValid(Class<?> valueType, Attribute<T> attribute) {
-        if (!attribute.getType().isAssignableFrom(valueType)) {
+    private <T> void assertAttributeTypeIsValid(Class<?> valueType, @Nullable Attribute<T> attribute) {
+        if (attribute != null && !attribute.getType().isAssignableFrom(valueType)) {
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultMutableAttributeContainer.java:129]: 💭 Added null check here.

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java [hunk 9]
```diff
@@ -128,14 +127,24 @@ public <T> AttributeContainer attributeProvider(Attribute<T> key, Provider<? ext
...
+        if (isolatable == null) {
+            return null;
+        }
+
+        T value = isolatable.isolate();
+        if (key != null && value != null && value.getClass() != key.getType() && key.getType() != Object.class) {
+            return isolatable.coerce(key.getType());
+        } else {
+            return value;
+        }
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java:142]: 💭 This is the important change: If we've isolated and didn't get a match for the attribute type, we need to coerce to it.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/internal/snapshot/impl/IsolatedArray.java [hunk 10]
```diff
@@ -57,7 +58,7 @@ public Object[] isolate() {
...
+        return Cast.uncheckedCast(elements);
```
Comment (jvandort) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/internal/snapshot/impl/IsolatedArray.java:61]: This seems unsafe. We need to make sure to that the thing we're returning is assignable to type

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java [hunk 11]
```diff
@@ -128,14 +127,24 @@ public <T> AttributeContainer attributeProvider(Attribute<T> key, Provider<? ext
...
+    @Nullable
+    public <T> T getAttribute(@Nullable Attribute<T> key) {
         Isolatable<T> isolatable = getIsolatableAttribute(key);
-        return isolatable == null ? null : isolatable.isolate();
+        if (isolatable == null) {
+            return null;
+        }
+
+        T value = isolatable.isolate();
+        if (key != null && value != null && value.getClass() != key.getType() && key.getType() != Object.class) {
```
Comment (jvandort) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java:138]: Can we document why we check if its not `Object`?

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/UsageCompatibilityHandler.java [hunk 12]
```diff
@@ -34,6 +34,8 @@ class UsageCompatibilityHandler {
     }
 
     public <T> ImmutableAttributes doConcat(DefaultAttributesFactory factory, ImmutableAttributes node, Attribute<T> key, Isolatable<T> value) {
+        factory.assertAttributeNotAlreadyPresent(node, key);
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/UsageCompatibilityHandler.java:37]: 💭 Another potential route to strange failures - we should failfast if we try to add the same attribute twice when concat-ing.

File: subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/AbstractAttributeContainerTest.groovy [hunk 13]
```diff
@@ -0,0 +1,117 @@
...
+import org.gradle.internal.operations.BuildOperationProgressEventEmitter
+import org.gradle.internal.problems.NoOpProblemDiagnosticsFactory
+import org.gradle.util.TestUtil
+import org.junit.Rule
+import spock.lang.Specification
+
+/**
+ * Abstract base class for testing functionality common to all {@link AbstractAttributeContainer} implementations.
+ */
+/* package */ abstract class AbstractAttributeContainerTest extends Specification {
```
Comment (tresat) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/AbstractAttributeContainerTest.groovy:35]: 💭 Establish behavior rules for each type of container here.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
I don't know what's going on with the Smoke test failures here, but it doesn't look related to the new (expected) deprecation warning.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java [hunk 14]
```diff
@@ -29,10 +30,16 @@
...
 import java.util.TreeMap;
 import java.util.concurrent.ConcurrentHashMap;
 
-final class DefaultImmutableAttributesContainer implements ImmutableAttributes, AttributeValue<Object> {
+/**
+ * Note: The fact that this type is both a <em>container</em> and a <em>value stored in a container</em> is strange.  This is
+ * probably something that ought to be addressed, this shouldn't implement {@link AttributeValue}, but it does it in order to
+ * build "linked lists" of immutable containers through concatenation to save memory.
+ */
+public final class DefaultImmutableAttributesContainer extends AbstractAttributeContainer implements ImmutableAttributes, AttributeValue<Object> {
```
Comment (jvandort) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java:42]: 🤔 `DefaultImmutableAttributesContainer` inherits _no_ behavior from `AbstractAttributeContainer`. Having it implement `AbstractAttributeContainer` is more confusing than helpful to me. 

An `DefaultImmutableAttributesContainer` works much differently under the hood than any other attribute container. I would be suspicious if we did inherit any behavior from `AbstractAttributeContainer`

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java [hunk 15]
```diff
@@ -128,14 +133,68 @@ public <T> AttributeContainer attributeProvider(Attribute<T> key, Provider<? ext
...
+        }
+
         Isolatable<T> isolatable = getIsolatableAttribute(key);
-        return isolatable == null ? null : isolatable.isolate();
+        if (isolatable == null) {
+            return null;
+        }
+
+        T value = isolatable.isolate();
+        if (isClassWithSameNameButDifferentType(value, key)) {
```
[the remark this answers is not in the document]
Comment (jvandort) [reply subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java:148]: Looking at one of your test cases (and I commented there), I don't think this is the minimal solution. 

This misses the case where the user-provided key and the isolated value (without coercion) are different.

Currently, we can return a value from this method that is different than the generic type value of the attribute passed in by the user.

This breaks the contract of this method, as defined by the `AttributeContainer` interface

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java [hunk 16]
```diff
@@ -128,14 +133,68 @@ public <T> AttributeContainer attributeProvider(Attribute<T> key, Provider<? ext
...
+        return value != null && value.getClass() != key.getType() && value.getClass().getName().equals(key.getType().getName()) && key.getType() != Object.class;
+    }
+
+    /**
+     * We lookup by name here to avoid issues with attributes with the type class from different classloaders.  This
+     * can only happen with immutable attribute containers, as mutable containers will not cross classloader boundaries
+     * when included builds are used.
+     * <p>
+     * This lookup requires that only a single attribute with a given name is present in this container, this invariant
+     * is enforced by the immutable factory construction logic and verified by
```
Comment (jvandort) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java:193]: and verified by..... ?

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesFactory.java [hunk 17]
```diff
@@ -84,6 +85,7 @@ public <T> ImmutableAttributes concat(ImmutableAttributes node, Attribute<T> key
     }
 
     ImmutableAttributes doConcatIsolatable(ImmutableAttributes node, Attribute<?> key, Isolatable<?> value) {
+        assertAttributeNotAlreadyPresent(node, key);
```
[the remark this answers is not in the document]
Comment (jvandort) [reply subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesFactory.java:88]: I am concerned about the performance implications of this. It seems expensive to iterate over the entire container each time we do a concat.

Plus, there should be more efficient ways to do this sort of thing.

`ImmutableAttributes` already has the `findEntry(String)` which can do this check in O(1) time

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/AttributeValue.java [hunk 18]
```diff
@@ -59,14 +56,20 @@ public Object get() {
 
     /**
      * Returns the value of this attribute.
+     * <p>
+     * This should <strong>NOT</strong> be called on {@link AttributeValue#MISSING}.
```
Comment (jvandort) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/AttributeValue.java:60]:
```suggestion
     * @throws UnsupportedOperationException if this is called on a non-{@link #isPresent present} value.
```

Javadoc should describe the interface, not implementations of the interface. 

Applies below as well.

File: subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java [hunk 19]
```diff
@@ -76,11 +75,14 @@ public interface AttributeContainer extends HasAttributes {
...
-     * Returns the value of an attribute found in this container, or <code>null</code> if
+     * Returns the value of an attribute found in this container, or {@code null} if
      * this container doesn't have it.
+     * <p>
+     * Supplying a {@code null} argument is deprecated and will return {@code null}.
+     *
      * @param <T> the type of the attribute
-     * @param key the attribute key
-     * @return the attribute value, or null if not found
+     * @param key the attribute key (should not be {@code null})
```
Comment (jvandort) [inline subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java:84]: I do not think this is necessary.

Yes, there are existing use cases where build logic is violating the nullity of this method.

But, the Gradle interface is non-null unless otherwise stated. If we followed this pattern everywhere we would pollute the public API javadoc with nullity noise.

For the sake of consistency, I would vote against stating this explicitly.

**Review by jvandort — CHANGES_REQUESTED** [review]
I do not think we should merge this while we have coercing logic that breaks the type safety of `getAttribute`

File: testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy [hunk 20]
```diff
@@ -38,15 +38,17 @@ class AndroidSantaTrackerDeprecationSmokeTest extends AndroidSantaTrackerSmokeTe
...
+            .build()
 
         then:
         if (GradleContextualExecuter.isConfigCache()) {
             result.assertConfigurationCacheStateStored()
         }
 
         where:
-        agpVersion << TestedVersions.androidGradle.versions
+        agpVersion << TestedVersions.androidGradle.versions.findAll { it.startsWith("8.8") }
```
[the remark this answers is not in the document]
Comment (tresat) [reply testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy:51]: This is an oversight, I just added these for quicker testing of one version that was breaking and forgot to remove.  Thanks for flagging.

File: testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy [hunk 21]
```diff
@@ -38,15 +38,17 @@ class AndroidSantaTrackerDeprecationSmokeTest extends AndroidSantaTrackerSmokeTe
         setupCopyOfSantaTracker(checkoutDir)
 
         when:
-        def result = buildLocation(checkoutDir, agpVersion)
+        def result = runnerForLocation(checkoutDir, agpVersion, "assembleDebug")
+            .maybeExpectLegacyDeprecationWarningIf(VersionNumber.parse(agpVersion) >= VersionNumber.parse("8.8.0"), "Using method getAttribute with a null key has been deprecated. This will fail with an error in Gradle 10.0. Don't request attributes from attribute containers using null keys.")
```
[the remark this answers is not in the document]
Comment (jvandort) [reply testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy:42]: We maintain our own fork of stands tracker. I'm not sure agp still maintains it

File: subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultImmutableAttributeContainerTest.groovy [hunk 22]
```diff
@@ -0,0 +1,49 @@
...
+    }
+
+    // This lenient coercing behavior is only available in the immutable container.  The mutable containers shouldn't ever need it
+    def "if there is a string in the container, and you ask for it as a Named, you get back the same value do to coercion"() {
+        given:
+        def container = getContainer([(Attribute.of("test", String)): "value"])
+
+        when:
+        //noinspection GroovyAssignabilityCheck
+        def result = (String) container.getAttribute(Attribute.of("test", Named))
```
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultImmutableAttributeContainerTest.groovy:44]: I'll look into this more.

File: subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/AbstractAttributeContainerTest.groovy [hunk 23]
```diff
@@ -0,0 +1,117 @@
...
+import org.gradle.internal.logging.CollectingTestOutputEventListener
+import org.gradle.internal.logging.ConfigureLogging
+import org.gradle.internal.operations.BuildOperationProgressEventEmitter
+import org.gradle.internal.problems.NoOpProblemDiagnosticsFactory
+import org.gradle.util.TestUtil
+import org.junit.Rule
+import spock.lang.Specification
+
+/**
+ * Abstract base class for testing functionality common to all {@link AbstractAttributeContainer} implementations.
```
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/AbstractAttributeContainerTest.groovy:33]: Sounds reasonable, I'll rename it.

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java (hunk 14 above)
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesContainer.java:42]: Not true:
1. Most importantly, it still needs to check if an attribute is valid in the same way as the other implementations
2. It still needs to override and implement `equals` and `hashCode`
3. It also "benefits" from the implementation of `getAttributes()` in the abstract type (I need to remove this from `DIAC`)

**Comment by tresat** [comment]
> I am concerned about the performance implications of this. It seems expensive to iterate over the entire container each time we do a concat.

This is a container that almost always has a single digit number of elements.  This check ensures the invariants from the interfaces it implements remain valid.  The caching means we should run this check only once per element concatenated to each unique immutable container we create, which shouldn't be very many.

I don't want to worry too much about this unless performance testing shows it to be a problem.  However, switching the implementation to benefit from `findEntry()` if `this` is an immutable sounds reasonable.  I'll make that change.

File: subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java (hunk 19 above)
Comment (tresat) [reply subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java:84]: I'm completely ambivalent here.  I thought it might be nice to note this explicitly for this case, so that if this bug fix (checking for null and failing fast) breaks anyone they might understand why faster.  

But I can remove it if you think it's too much noise.  I'll leave it to you to make the final call.

Comment (jvandort) [reply subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java:84]: I don't think its the end of the world if we include it, but I think its redundant. 

I think the deprecation warning is enough IMO

File: subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/AbstractAttributeContainerTest.groovy (hunk 23 above)
[the remark this answers is not in the document]
Comment (jvandort) [reply subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/AbstractAttributeContainerTest.groovy:33]: I'm fine with the name, its more about the javadoc specifically saying it tests `AbstractAttributeContainer` instead of `AttributeContainer`,

plus the `getContainer` method requires `AbstractAttributeContainer` instead of `AttributeContainer` as a return type

**Comment by tresat** [comment]
> > I am concerned about the performance implications of this. It seems expensive to iterate over the entire container each time we do a concat.
> 
> This is a container that almost always has a single digit number of elements. This check ensures the invariants from the interfaces it implements remain valid. The caching means we should run this check only once per element concatenated to each unique immutable container we create, which shouldn't be very many.
> 
> I don't want to worry too much about this unless performance testing shows it to be a problem. However, switching the implementation to benefit from `findEntry()` if `this` is an immutable sounds reasonable. I'll make that change.

Explore moving this check to the compute block.

File: subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultMutableAttributeContainerTest.groovy [hunk 24]
```diff
@@ -23,40 +23,25 @@ import org.gradle.api.internal.provider.DefaultProvider
...
-    def attributesFactory = AttributeTestUtil.attributesFactory()
-
-    private DefaultMutableAttributeContainer mutable() {
-        return new DefaultMutableAttributeContainer(attributesFactory, AttributeTestUtil.attributeValueIsolator())
+/**
+ * Unit tests for the {@link DefaultMutableAttributeContainer} class.
+ */
+final class DefaultMutableAttributeContainerTest extends AbstractAttributeContainerTest {
+    @Override
+    protected <T> DefaultMutableAttributeContainer getContainer(Map<Attribute<T>, T> attributes = [:]) {
```
Comment (big-guy) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultMutableAttributeContainerTest.groovy:35]: Picky, but what about `createContainer`?

File: subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultAttributesFactoryTest.groovy [hunk 25]
```diff
@@ -180,8 +180,8 @@ class DefaultAttributesFactoryTest extends Specification implements TestsImmutab
 
     def "can detect incompatible attributes with different types when merging"() {
         given:
-        def set1 = factory.concat(factory.of(FOO, "foo1"), factory.of(OTHER_BAR, "bar1"))
-        def set2 = factory.concat(factory.of(FOO, "foo1"), factory.of(BAR, "bar2"))
+        def set1 = factory.concat(factory.of(FOO, "foo1"), factory.of(OTHER_BAR, "bar1")) // Object-typed bar
+        def set2 = factory.concat(factory.of(FOO, "foo1"), factory.of(BAR, "bar2")) // String-typed bar
```
Comment (big-guy) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultAttributesFactoryTest.groovy:184]: Do these still conflict if the value is the same?

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/UsageCompatibilityHandler.java (hunk 12 above)
Comment (big-guy) [reply subprojects/core/src/main/java/org/gradle/api/internal/attributes/UsageCompatibilityHandler.java:37]: Does this trigger any failures in real builds? I don't think it should

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/HierarchicalMutableAttributeContainer.java [hunk 26]
```diff
@@ -33,7 +33,7 @@
  * container will override attributes in the fallback container. All mutation operations are
  * forwarded to the primary container.
  */
-final class HierarchicalMutableAttributeContainer extends AbstractAttributeContainer {
+public final class HierarchicalMutableAttributeContainer extends AbstractAttributeContainer {
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/HierarchicalMutableAttributeContainer.java:36]: why does this need to be public?

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/AbstractAttributeContainer.java [hunk 27]
```diff
@@ -51,4 +53,25 @@ public AttributeContainer getAttributes() {
...
+     * Verifies that the given key is a valid attribute request.
+     * <p>
+     * Requesting null keys is not allowed, and is deprecated.
+     *
+     * @param key the requested attribute to validate
+     * @return {@code true} is valid request; {@code false} otherwise
+     */
+    protected boolean isValidAttributeRequest(@Nullable Attribute<?> key) {
+        if (key == null) {
+            DeprecationLogger.deprecateInvocation("getAttribute with a null key")
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/api/internal/attributes/AbstractAttributeContainer.java:67]: I think this is intended to deprecate a method call, but this is a behavior.

I would use `deprecateBehaviour("Retrieving attribute with a null key")` and avoid making this look like a method is going to be removed.

File: subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java (hunk 19 above)
Comment (big-guy) [reply subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java:84]: Does this show up as non-null for Kotlin?  if it doesn't, we can't change it in 8.x, but we could consider changing it in 9.0.

I'm OK with the extra docs.  I would remove the detail from the `@param` since it's covered in the body.

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesFactory.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (big-guy) [reply subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesFactory.java:88]: Yeah, this looks like it could be quadratic in nature.  Can this be a check that we do later? e.g., once we know we need the whole list and we're using it?

**Review by big-guy — CHANGES_REQUESTED** [review]
Can we add some integration coverage for the end-to-end case? 

I'd try something like:
- create a plugin that defines a new attribute type, creates a Configuration that uses it and another that resolves a Configuration using the attribute
- create a composite build that includes the plugin, build A and 2 subprojects
- apply the plugin to build A and the subprojects
- resolve the variant from build A 
- resolve the variant from the subproject

IIUC, this shouldn't work for the included build without this PR.

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesFactory.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesFactory.java]: I added a quick check using `findEntry` first, so the common case should be much faster.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy [hunk 28]
```diff
@@ -0,0 +1,480 @@
...
+        """)
+
+        expect: "the resolution succeeds (and the attribute value used to resolve can be retrieved from the resolved variant) or fails as expected"
+        if (result) {
+            succeeds(":consumer:resolve")
+            outputContains("Resolved: output.txt")
+            outputContains("Attribute type: myValue")
+        } else {
+            fails("resolve")
+            failure.assertHasErrorOutput("No matching variant of project :producer was found.")
```
Comment (big-guy) [inline subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy:89]: I think conditional logic in a test can really make it hard to understand, especially when the conditions are in the expectations.

I think we care about when the resolution is successful since that shows that we're able to match attributes across boundaries.

I don't think we care about the failure case because it could just as easily be failing because we have a bug that causes this to never match. 

I wouldn't include the failure cases here, which means you can drop the conditional expectations.

There may be something here around testing compatibility or disambiguation rules when they're defined on either side. That captures some of the "what happens if the values aren't _exactly_ the same".  Maybe @jvandort can weigh in on if it's useful to also test compatibility/disambiguation separately in these scenarios.

**Review by big-guy — CHANGES_REQUESTED** [review]

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy (hunk 28 above)
Comment (jvandort) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy:89]: We have tests for this https://github.com/gradle/gradle/blob/master/subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildConfigurationAttributesResolveIntegrationTest.groovy#L484-L693

These two test that a consumer and producer with "different" attributes (according to classloader, but not according to class name) define compatibility and disambiguation rules. The first when the consuming build defines the rules the second when the producing build defines the rules. 

The second of these two tests is broken since we do not do coersion when discovering compatibility/disambiguation rules (ATM)

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/UsageCompatibilityHandler.java (hunk 12 above)
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/attributes/UsageCompatibilityHandler.java:37]: Ignore that last comment.  There is a behavior difference between `concat` and `sateConcat` that is required.  We make use of it when parsing the GMM.  The methods are misnamed, but functioning as desired - I'm adjusting the tests to account for this.

File: subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java (hunk 19 above)
Comment (tresat) [reply subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java:84]: This should show as non-null for Kotlin.  I don't think there is a problem there, as I haven't changed the signature.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy [hunk 29]
```diff
@@ -0,0 +1,480 @@
...
+
+        where:
+        result  | attributeCreationLogic
+        true    | "attribute(ATTRIBUTE_TYPE, objects.named(MyAttributeType.class, 'myValue'))"
+        false   | "attribute(ATTRIBUTE_TYPE, objects.named(MyAttributeType.class, 'incorrectValue'))"
+        true    | "attribute(Attribute.of('myAttribute', String), 'myValue')"
+        false   | "attribute(Attribute.of('myAttribute', String), 'incorrectValue')"
+    }
+
+    def "new attribute type created by producer as an included build, used by consumer as an included build works"() {
```
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy:171]: Will delete.  Just being exhaustive.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy [hunk 30]
```diff
@@ -0,0 +1,480 @@
...
+ */
+@Issue("https://github.com/gradle/gradle/issues/28695")
+final class AttributeCoercionIntegrationTest extends AbstractIntegrationSpec {
+    def "new attribute type created by producer, used by consumer works"() {
+        given:
+        settingsFile("""
+            include 'consumer', 'producer'
+        """)
+
+        and: "a producer that adds a new attribute type; a variant using it, and a resolvable configuration for it"
```
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy:39]: This is confusing.  Removed.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy [hunk 31]
```diff
@@ -0,0 +1,480 @@
...
+        file("producer/output.txt") << "sample output"
+        groovyFile("producer/build.gradle", """
```
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy:41]: Updated to use buildFile throughout.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy [hunk 32]
```diff
@@ -0,0 +1,480 @@
...
+                    myPlugin {
+                        id = 'org.gradle.example.myPlugin'
+                        implementationClass = 'org.gradle.example.MyPlugin'
+                    }
+                }
+            }
+        """)
+    }
+
+    private String defineResolveTask(String configurationName = "myResolver") {
```
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy:460]: Yes.  Let's leave that fixture out of this.  Just checking files and attributes on the resolved artifacts is all that is needed here, we don't need to care about the complete shape of the graph.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy (hunk 28 above)
Comment (tresat) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/attributes/AttributeCoercionIntegrationTest.groovy:89]: Those other tests seem sufficient.  I suppose the resolution failure cases are less interesting, and we have other tests elsewhere covering this behavior.  I'll remove them to simplify this class.

File: subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultAttributesFactoryTest.groovy (hunk 25 above)
Comment (tresat) [reply subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultAttributesFactoryTest.groovy:184]: Yes.

File: subprojects/core/src/main/java/org/gradle/api/internal/attributes/AbstractAttributeContainer.java [hunk 33]
```diff
@@ -51,4 +53,25 @@ public AttributeContainer getAttributes() {
...
+                .withAdvice("Don't request attributes from attribute containers using null keys.")
+                .willBecomeAnErrorInGradle10()
+                .undocumented()
```
[the remark this answers is not in the document]
Comment (tresat) [reply subprojects/core/src/main/java/org/gradle/api/internal/attributes/AbstractAttributeContainer.java:70]: Test was already there `"requesting a null key from an empty container emits a deprecation message"()`, updated to verify the updated message.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@big-guy - The test failures here all seem like intermittent CI issues.  This is ready for review.

File: platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc [hunk 34]
```diff
@@ -48,6 +48,14 @@ The change is driven by the need to interpret such default values in the scope o
 
 === Deprecations
 
+[[null-attribute-lookup]]
+==== Looking up attributes using null keys deprecated ====
```
Comment (lkasso) [inline platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc:52]:
```suggestion
==== Looking up attributes using null keys is deprecated ====
```

File: platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc [hunk 35]
```diff
@@ -48,6 +48,14 @@ The change is driven by the need to interpret such default values in the scope o
...
+
+Providing a null argument to when retrieving attributes from a container using the `getAttribute(Attribute)` method has been explicitly deprecated.
```
Comment (lkasso) [inline platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc:54]:
```suggestion
Providing a `null` argument when retrieving attributes from a container using `getAttribute(Attribute)` is now explicitly deprecated.
```

File: platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc [hunk 36]
```diff
@@ -48,6 +48,14 @@ The change is driven by the need to interpret such default values in the scope o
...
+
+Prior to this change, a `null` lookup silently returned `null`.  Now it will emit a deprecation warning.
```
Comment (lkasso) [inline platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc:56]:
```suggestion
Previously, a `null` lookup silently returned `null`. Now, it emits a deprecation warning.  
```

File: platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc [hunk 37]
```diff
@@ -48,6 +48,14 @@ The change is driven by the need to interpret such default values in the scope o
...
+There should be no need to lookup null values in an `AttributeContainer`.
```
Comment (lkasso) [inline platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc:57]:
```suggestion
There should be no need to look up `null` values in an `AttributeContainer`.
```

**Comment by tresat** [comment]
@bot-gradle test this

File: platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc [hunk 38]
```diff
@@ -48,6 +48,14 @@ The change is driven by the need to interpret such default values in the scope o
 
 === Deprecations
 
+[[null-attribute-lookup]]
+==== Looking up attributes using null keys is deprecated ====
+
+Providing a `null` argument when retrieving attributes from a container using `getAttribute(Attribute)` is now explicitly deprecated.
```
Comment (big-guy) [inline platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc:54]: Can this link to the javadoc?

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test this

File: testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy [hunk 39]
```diff
@@ -137,7 +142,8 @@ class AndroidSantaTrackerLintSmokeTest extends AndroidSantaTrackerSmokeTest {
         )
         SantaTrackerConfigurationCacheWorkaround.beforeBuild(checkoutDir, homeDir)
         runner.withArguments(runner.arguments + "--continue")
```
Comment (mlopatkin) [inline testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy:144]: :x: You're no longer updating the `result` variable, that's why CC asserts the build operations of the previous build.

```suggestion
        result = runner.withArguments(runner.arguments + "--continue")
```

Comment (tresat) [reply testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy]: Thanks for the help with this!

**Comment by tresat** [comment]
@bot-gradle test and merge
