### PR TITLE
Fix `GradleBuildExternalPluginsValidationSmokeTest`

### LINKED ISSUE #16084: Investigate `GradleBuildExternalPluginsValidationSmokeTest` weirdness
The `GradleBuildExternalPluginsValidationSmokeTest` smoke test is slower than it should be, because it triggers the compilation of some projects. There's no good reason for it to do this, so we need to understand why this is happening.

Also, the test is most likely sensitive to ordering (because of `--parallel`) which may have caused a flakiness observed by @ljacomet

### PR DESCRIPTION
**Pull request by melix**
This PR fixes a couple issues with `GradleBuildExternalPluginsValidationSmokeTest`:

- the Gradle build itself was incorrectly configuring _all_ `ValidatePlugins` tasks, including those for external plugins
- there was a potential race condition in verification

Closes #16084

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
Thanks for taking the time to improve this!

File: subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy [hunk 1]
```diff
@@ -96,7 +96,8 @@ class GradleBuildExternalPluginsValidationSmokeTest extends AbstractGradleceptio
 
     void validatePlugins() {
         allPlugins.performValidation([
-            "-Dorg.gradle.internal.validate.external.plugins=true"
+            "-Dorg.gradle.internal.validate.external.plugins=true",
+            "--no-parallel" // make sure we have consistent execution ordering as we skip cached tasks
```
Comment (wolfs) [inline subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy:100]: Is the different execution order/from cache order a problem for the expectations of this test? If it isn't, why do we disable parallel execution?

**Review by wolfs — COMMENTED** [review]
Looks good. I left a comment.

File: subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy (hunk 1 above)
Comment (melix) [reply subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy:100]: It is (look at the commit message): the test relies on the fact we will get duplicates from cache. If the initial task being executed is not the one we expected, there's a race condition.

Comment (wolfs) [reply subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy:100]: Can't we change the test, so it doesn't depend on validation warnings to show up in a single project? We do not really care in which project the warning shows up, just that it shows up, right?

Comment (melix) [reply subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy:100]: It's done this way so that we can make sure that new plugins are verified (like Louis faced this morning, he added a plugin and the test failed because we didn't know about it, as expected). If we don't care about the project, then we need a way to collect all answers from all projects, and a way to list all plugins being validated. This is doable but IMO not worth the effort. There's almost no overhead of doing serially here, the build completes roughly in 2 minutes with or without parallel.

Comment (wolfs) [reply subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy:100]: 👍

**Review by wolfs — APPROVED** [review]
LGTM!
