### PR TITLE
Fix #2999: runPlayBinary needs to be adapted for Play 2.6

### LINKED ISSUE #2999: gradle 4.2 - play 2.6.x - scala 2.11
I have a problem starting with play 2.6, but scala 2.11 just by running gradle playRun:

> Failed to run Play
> org.gradle.internal.UncheckedException: java.lang.NoSuchMethodException: play.core.server.DevServerStart$.mainDevHttpMode(play.core.BuildLink, play.core.BuildDocHandler, int, java.lang.String)
> 

By looking into PlayRunAdapterV26X I see that it just extends PlayRunAdapterV24X which calls that mainDevHttpMode with reflections while using wrong arguments.

In change logs its written that there is a support to 2.6.x play versions, but I cannot just run the server. Maybe I am doing smthg wrong?

### PR DESCRIPTION
**Pull request by marcospereira**
### Context

This fixes two things in Play 2.6 support:

1. Support for Scala 2.12 (which also should be the default when selecting Play 2.6)
2. `runPlayBinary` is broken for Play 2.6 and needs to be changed. That is because `play.core.server.DevServerStart#mainDevHttpMode` has a new signature.

See issues #2991 and #2999.

### Contributor Checklist

- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

Some points here:

1. I was able to run the tests locally using `./gradlew platformPlay:check`, but ran into the following error the first time: https://gist.github.com/marcospereira/14ea17771ac9ba336e12367c9e79c04d. Not sure if this is relevant to you guys.
2. I'm not sure about how to add integration tests for the fix in `runPlayBinary`. Could you please guide me here?

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by oehme** [comment]
@big-guy is this something you could look into? Seems related to #2062.

**Comment by marcospereira** [comment]
@oehme not sure if the issues are related although #2062 looks necessary to better support Play 2.6.x.

**Comment by oehme** [comment]
Yes, I meant this would fit well into a bigger "support Play 2.6" story.

**Comment by marcospereira** [comment]
Hey guys, sorry for bumping this, but there is anything that you need on my side here?

**Comment by blindpirate** [comment]
@marcospereira Thanks for your PR. I've pushed some extra code to remove duplicate methods. Could you please take a look at it?

However, there's an issue unresolved: [this test](https://github.com/marcospereira/gradle/blob/a80786fbbee1f80f5c5e48207658f13f63cd8258/subprojects/platform-play/src/integTest/groovy/org/gradle/play/integtest/PlayPlatformIntegrationTest.groovy#L111) would fail and throw `ClassNotFoundException: scala.util.parsing.input.Positional` after I upgrade `Play 2.6`'s twirl version to `1.3.12` (because `twirl-compiler_2.12:1.1.1` doesn't exist). Since I'm not a scala and play expert, I'd appreciate your opinion here.

**Comment by marcospereira** [comment]
Thank you, @blindpirate.

Some questions:

1. Is there a way to run this single test alone? I tried `./gradlew test --tests org.gradle.play.integtest.PlayPlatformIntegrationTest` and `./gradle :platformPlay:test --tests org.gradle.play.integtest.PlayPlatformIntegrationTest` but both failed with `No tests found for given includes: [org.gradle.play.integtest.PlayPlatformIntegrationTest](--tests filter)`. Running the complete suite every time looks prohibitive to me (since it took too long). Or maybe there is a CI where I can see the test result?
2. How can I create a local dist of Gradle so that I can try it manually?

Again, thanks for helping me here.

**Comment by blindpirate** [comment]
@marcospereira This issue has been solved by adding some extra jar so you don't need to look into it, thanks! Could you review it a bit to see if there's anything inapproriate?

File: subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+    @Override
+    public Iterable<String> getClassLoaderPackages() {
+        return SHARED_PACKAGES;
+    }
+
+    @Override
+    public String[] getDependencyNotation() {
+        if (scalaVersion.startsWith("2.12")) {
+            // We need scala.util.parsing.input.Positional
+            return new String[]{super.getDependencyNotation()[0], "org.scala-lang.modules:scala-parser-combinators_2.12:1.0.6"};
```
Comment (marcospereira) [inline subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java]: This looks a bit fragile to me. I mean, if `super` starts to return an array with more than a single element, this will stop working. So, I would so something like:

```java
String[] dependencyNotation = super.getDepenencyNotation();
String[] result = Arrays.copyOf(dependencyNotation, dependencyNotation.length +1);
result[dependencyNotation.length] = "org.scala-lang.modules:scala-parser-combinators_2.12:1.0.6";
return result;
```

Comment (marcospereira) [reply subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java]: Maybe we can later refactor `getDependencyNotation` to return a list instead (easier to manipulate)  since this is an internal API.

Comment (blindpirate) [reply subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java]: Thanks, let me make it an array.

**Comment by marcospereira** [comment]
@blindpirate thanks for yo help here.

Made two small commits to update Scala 2.11 version and Twirl.

**Comment by blindpirate** [comment]
@marcospereira Thanks a lot. 

You can use `./gradlew install -Pgradle_installPath=/usr/local/gradle-source-build` to create a local dist to test. Here I got an error which you might be more familiar than me:

```
org.gradle.integtests.fixtures.executer.UnexpectedBuildFailure: Gradle execution failed in C:\tcagent1\work\6031ced305d8bea4\subprojects\platform-play\build\tmp\test files\AbstractIntegrationSpec\unknown-test\vmxzo with: cmd [/c, gradle, --daemon, --stacktrace, --gradle-user-home, C:\tcagent1\work\6031ced305d8bea4\intTestHomeDir\worker-1, compilePlayBinaryScala]
Process ExecResult:
{exitValue=1, failure=null}
-----
Output:
:compilePlayBinaryPlayTwirlTemplates
:compilePlayBinaryScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
:compilePlayBinaryScala FAILED
2 actionable tasks: 2 executed

-----
Error:
C:\tcagent1\work\6031ced305d8bea4\subprojects\platform-play\build\tmp\test files\AbstractIntegrationSpec\unknown-test\vmxzo\build\src\play\binary\twirlTemplatesScalaSources\views\csv\test.template.scala:12: not found: type Csv
object test extends _root_.play.twirl.api.BaseScalaTemplate[views.formats.csv.CsvFormat.Appendable,_root_.play.twirl.api.Format[views.formats.csv.CsvFormat.Appendable]](views.formats.csv.CsvFormat) with _root_.play.twirl.api.Template2[String,Csv,views.formats.csv.CsvFormat.Appendable] {
                                                                                                                                                                                                                                                  ^
C:\tcagent1\work\6031ced305d8bea4\subprojects\platform-play\build\tmp\test files\AbstractIntegrationSpec\unknown-test\vmxzo\build\src\play\binary\twirlTemplatesScalaSources\views\csv\test.template.scala:15: not found: type Csv
  def apply/*2.14*/(username: String)(content: Csv):views.formats.csv.CsvFormat.Appendable = {
                                               ^
C:\tcagent1\work\6031ced305d8bea4\subprojects\platform-play\build\tmp\test files\AbstractIntegrationSpec\unknown-test\vmxzo\build\src\play\binary\twirlTemplatesScalaSources\views\csv\test.template.scala:28: not found: type Csv
  def render(username:String,content:Csv): views.formats.csv.CsvFormat.Appendable = apply(username)(content)
                                     ^
C:\tcagent1\work\6031ced305d8bea4\subprojects\platform-play\build\tmp\test files\AbstractIntegrationSpec\unknown-test\vmxzo\build\src\play\binary\twirlTemplatesScalaSources\views\csv\test.template.scala:30: not found: type Csv
  def f:((String) => (Csv) => views.formats.csv.CsvFormat.Appendable) = (username) => (content) => apply(username)(content)
                      ^
four errors found

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compilePlayBinaryScala'.
> Compilation failed
```

You can run the local dist with this project [issue.zip](https://github.com/gradle/gradle/files/1422224/issue.zip) to get the error above.

File: subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java (hunk 1 above)
Comment (blindpirate) [reply subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java]: Sorry, I mean to make it a list.

**Comment by marcospereira** [comment]
@blindpirate okay, let me do that and report back.

**Comment by marcospereira** [comment]
@blindpirate, if you change the `test.scala.csv` file to use the fully qualified class name for `Csv` everything works as expected:

```scala
@(username: String)(content: views.formats.csv.Csv)
```
So, I think the `TwirlSourceSet` is not being added to Twirl additional imports.

**Comment by marcospereira** [comment]
I've noticed some other small stuff while testing locally, for example, the default imports for Twirl are not updated for Play 2.6.x. Since Gradle reads a lot of things using reflection, I think we can also read these imports from here:

https://github.com/playframework/playframework/blob/2.6.0/framework/src/build-link/src/main/java/play/TemplateImports.java

I will add a commit to fix this.

**Comment by marcospereira** [comment]
Also, there is no test to validate the use of additional imports added using the following syntax:

```gradle
sources {
    withType(TwirlSourceSet) {
        addUserTemplateFormat("unused", "views.formats.unused.UnusedFormat", "my.pkg._")
    }
}
```

See [TwirlCompileIntegrationTest.groovy](https://github.com/gradle/gradle/blob/767f60875866591ee5b2b46244ed6bb1f8bda3b8/subprojects/platform-play/src/integTest/groovy/org/gradle/play/tasks/TwirlCompileIntegrationTest.groovy).

@blindpirate you may be better equipped to fix this than I am. :-)

**Comment by blindpirate** [comment]
@marcospereira Thanks for pointing out. Actually there is a test for additional imports, see https://github.com/gradle/gradle/blob/767f60875866591ee5b2b46244ed6bb1f8bda3b8/subprojects/platform-play/src/integTest/groovy/org/gradle/play/tasks/TwirlCompileIntegrationTest.groovy#L488

I've added default imports according to the `TemplateImports.java` you mentioned. And I've fixed all possible issues on my local machine, let's see if it can pass all CI tests. Maybe you can take a look in case there's anything missing.

**Comment by marcospereira** [comment]
@blindpirate, pushed two small changes now. Will made comments where the code change just to explain the rationale behind the changes.

This looks good to me. Thanks for all your help.

File: subprojects/platform-play/src/main/java/org/gradle/play/internal/PlayPlatformResolver.java [hunk 2]
```diff
@@ -25,10 +26,18 @@
...
+import org.gradle.util.CollectionUtils;
 import org.gradle.util.GUtil;
 
+import java.util.Map;
+
 // TODO Resolve the JavaPlatform and ScalaPlatform from their PlatformResolvers, rather than instantiating directly
 public class PlayPlatformResolver implements PlatformResolver<PlayPlatform> {
+    public static final Map<String, String> LATEST_SCALA_VERSIONS =
+        ImmutableMap.of("2.10", "2.10.6",
+            "2.11", "2.11.11",
```
Comment (marcospereira) [inline subprojects/platform-play/src/main/java/org/gradle/play/internal/PlayPlatformResolver.java]: Using Scala 2.11.11 which is the latest version for 2.11 series.

File: subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV10X.java [hunk 3]
```diff
@@ -33,32 +34,42 @@
...
-        "models._",
-        "controllers._",
-        "play.api.templates.PlayMagic._",
-        "play.api.i18n._",
-        "play.api.mvc._",
-        "play.api.data._");
-
-    private final String scalaVersion;
-    private final String twirlVersion;
+    // Default imports are based on:
```
Comment (marcospereira) [inline subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV10X.java]: Literally, copy and paste the code from Play repository here so that we can avoid missing any imports.

File: subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java [hunk 4]
```diff
@@ -0,0 +1,150 @@
...
+    private static List<String> DEFAULT_JAVA_TEMPLATE_IMPORTS;
+    private static List<String> DEFAULT_SCALA_TEMPLATE_IMPORTS;
+
+    private static List<String> DEFAULT_TEMPLATE_IMPORTS = Collections.unmodifiableList(
+        Arrays.asList(
+            "models._",
+            "controllers._",
+            "play.api.i18n._",
+            "play.api.templates.PlayMagic._",
+            // Based on https://github.com/playframework/twirl/blob/1.3.13/compiler/src/main/scala/play/twirl/compiler/TwirlCompiler.scala#L156
```
Comment (marcospereira) [inline subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java]: We need these additional comments to ensure users can write twirl templates like:

```html
@defining(10) { v =>
   The defined value is @v
}
```
This was not working for Play 2.6/Twirl 1.3 because the `defining` function was not imported.

**Comment by marcospereira** [comment]
A followup to this PR is that we need to update Gradle docs to add some details regarding Play 2.6. For example, Guice support was extracted from the core and users now need to add the following dependency:

```gradle
dependencies {
    play "com.typesafe.play:play-guice_$scalaVersion:$playVersion"
}
```

Also, Play 2.6 now comes with a [default set of request filters](https://playframework.com/documentation/2.6.x/Migration26#Default-Filters), but they aren't being added to Gradle since the following dependency is not present:

http://mvnrepository.com/artifact/com.typesafe.play/filters-helpers_2.11

Or maybe this is something we can add to this PR?

**Comment by marcospereira** [comment]
@blindpirate you may also be interested in #3314.

**Comment by big-guy** [comment]
@blindpirate I think the change looks sane overall. There are some sanity check and test failures that I fixed in: https://github.com/gradle/gradle/tree/sg/play/2.6

I kicked off a build for this branch: https://builds.gradle.org/viewQueued.html?itemId=9037272

These integration tests are failing with Play 2.6.7:
https://github.com/gradle/gradle/blob/15811b4aec059f54cd646620a7473c87a3a5483f/subprojects/platform-play/src/integTest/groovy/org/gradle/play/tasks/TwirlCompileIntegrationTest.groovy#L255-L272

> /Users/sterling/gits/gradle/build/tmp/test files/AbstractIntegrationSpec/unknown-test/75duf/build/src/play/binary/twirlJavaScalaSources/html/javaTemplate.template.scala:22: object data is not a member of package play
> import play.data._
>             ^
> /Users/sterling/gits/gradle/build/tmp/test files/AbstractIntegrationSpec/unknown-test/75duf/build/src/play/binary/twirlJavaScalaSources/html/javaTemplate.template.scala:23: object PlayFormsMagicForJava is not a member of package play.core.j
> import play.core.j.PlayFormsMagicForJava._
>                    ^
> two errors found

It seems to be related to the set of default imports for Java.  Maybe there are extra modules that need to be added to the classpath?

**Comment by marcospereira** [comment]
@big-guy thanks for pointing the build failures.

The `play.data` import was actually moved to another dependency, as you said. It is now [part of `play-java-forms`](http://mvnrepository.com/artifact/com.typesafe.play/play-java-forms_2.11) and it only exists for 2.6. It this the right place to add new classpath elements?

https://github.com/gradle/gradle/blob/57149c6905f32641826caa2d573bab2af0dad688/subprojects/platform-play/src/main/java/org/gradle/play/plugins/PlayApplicationPlugin.java#L236-L240

The same dependency will also add `PlayFormsMagicForJava`.

**Comment by marcospereira** [comment]
@big-guy and @blindpirate see https://github.com/gradle/gradle/pull/3018/commits/d394e019461c3046b6ecfcc3d557b3ba33f3ecdc. :-)

**Comment by blindpirate** [comment]
@marcospereira Thanks a lot!

@big-guy I cherry-picked your commits on `sg/play/2.6` here (because I think we should keep our changes in one place) and now looks like all tests have passed, do you wanna a final-check?

**Comment by marcospereira** [comment]
Thank you so much for your help here, @blindpirate.

I think this is ok to be merged.

**Comment by blindpirate** [comment]
@marcospereira Merged, thanks for your excellent wok!

File: subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java [hunk 5]
```diff
@@ -0,0 +1,150 @@
...
+
+import java.io.File;
+import java.lang.reflect.InvocationTargetException;
+import java.util.ArrayList;
+import java.util.Arrays;
+import java.util.Collection;
+import java.util.Collections;
+import java.util.List;
+
+class TwirlCompilerAdapterV13X extends TwirlCompilerAdapterV10X {
```
Comment (benmccann) [inline subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java]: This class could be a lot simpler if you called the Java Twirl API rather than the Scala API

Comment (blindpirate) [reply subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java]: Thanks a lot! Do you mean https://github.com/playframework/twirl/pull/136 ? This is sure our next step plan.

Comment (benmccann) [reply subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV13X.java]: Yep!

**Comment by schmohlio** [comment]
so is this slated for release 4.3.2? thx

**Comment by oehme** [comment]
There will be no 4.3.2. This change will be in 4.4
