### PR TITLE
Simplify version conflict failure handling

### LINKED ISSUE #32279: Show version conflicts in dependencies view when build fails because of failOnVersionConflict()
### Current Behavior

When a user enables `failOnVersionConflict()`, then the Build Scan should help the user to fix the version conflicts after updating a version. Currently, Build Scans do not show the dependencies in the configuration that failed to resolve.

I did a small investigation, and it seems that Gradle tracks the failure on version conflict differently to resolution failures: https://github.com/gradle/gradle/blob/f7070685f05dce8fa19d93d15fef44fbad127915/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/FailOnVersionConflictGraphVisitor.java#L38-L45

The Develocity plugin only shows errors for `UnresolvedDependencyResult`, but not when the whole resolution returns an error.

### Expected Behavior

The version conflict is shown as a failed dependency resolution in the Build Scan.

### Context (optional)

The resolutions that failed because of `failOnVersionConflict()` are not show at all in the Build Scan.

### Self-contained Reproducer Project

See the internal issue.

### Gradle version

8.11

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by jvandort**
Previously failOnVersionConflicts would add a new visitor to the graph which collected version conflicts. These conflicts were handled differently than all other exceptions from graph resolution. As a result, we had to maintain two separate error handling paths, and the one path was only used for version conflicts. Further, this one-off path had a number of special cases which we needed to support only for this use case.

Furthermore, develocity was unable to introspect these failures, as they were not reported through the same path as other failures. Now, version conflict failures are reported as unresolved dependencies, just like all other non-fatal graph resolution failures.

Some slight modifications were made to dependencyInsight reporting, as we no longer receive version conflict failures through the one-off mechanism. There is no longer a special section for version conflict failures and failure resolutions are now properly grouped with the cause that emitted them.

The dependencies task no longer fails fatally when a version conflict exception is thrown.

The build operation is marked as a failure if any dependencies failed to resolve for any reason. The same graph as before is still emitted in the details.

Fixes #32279

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/software/software-diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy [hunk 1]
```diff
@@ -343,111 +340,34 @@ org:leaf:1.0
...
-            repositories {
-                maven { url = "${mavenRepo.uri}" }
-            }
-
-            configurations {
-                conf {
-                    resolutionStrategy.failOnVersionConflict()
-                    incoming.afterResolve {
-                        // If executed, the below will cause the resolution failure on version conflict to be thrown, breaking dependency insight
-                        it.artifacts.artifacts
```
Comment (jvandort) [inline platforms/software/software-diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy:409]: This is technically a breaking change but IMO a very minor one. 

`it.artifacts.artifacts` will throw an exception if the graph has _any_ failures in it. 

Previously, we skipped running `afterResolve` if we had a version conflict failure (but ran it in every other case). 

So, now we always run afterResolve and as such this throws an exception when it didn't previously. 

The new behavior is correct IMO. I would be fine releasing this in a minor as it is more correct and can be considered a bug fix (afterResolve didnt run in certain circumstances). Note, the `ResolutionResult` can still be analyzed leniently in `afterResolve` here without throwing an exception, so there is value to executing `afterResolve` even during failure cases.

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/Conflict.java [hunk 2]
```diff
@@ -16,24 +16,37 @@
...
 
-import org.gradle.api.artifacts.ModuleVersionIdentifier;
+import com.google.common.collect.ImmutableList;
+import org.gradle.api.artifacts.ModuleIdentifier;
+import org.gradle.api.artifacts.result.ComponentSelectionReason;
 
 import java.util.List;
 
+/**
+ * Describes a version conflict between two or more modules in a dependency graph.
```
Comment (jvandort) [inline platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/Conflict.java:26]:
```suggestion
 * Describes a version conflict between two or more versions of a module in a dependency graph.
```

File: platforms/software/software-diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/insight/DependencyInsightReporter.java [hunk 3]
```diff
@@ -172,6 +179,23 @@ private static void collectErrorMessages(Throwable failure, TreeFormatter format
         }
     }
 
+    /**
+     * Multi-cause exceptions by default aggregate the resolutions of their causes.
+     * If a cause has resolutions, skip emitting the parent exception's resolutions,
+     * so we can correctly associate the resolution with the child.
+     */
+    private static boolean shouldSkipResolutions(Throwable throwable) {
```
Comment (jvandort) [inline platforms/software/software-diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/insight/DependencyInsightReporter.java:187]: We should instead print the set of parent resolutions minus the set of all child resolutions, in order to handle cases where the multi cause implementation does not simply aggregate all of its children

File: platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationDependenciesBuildOperationIntegrationTest.groovy [hunk 4]
```diff
@@ -464,7 +462,8 @@ class ResolveConfigurationDependenciesBuildOperationIntegrationTest extends Abst
         failedResolve.assertFailurePresent(failure)
         def op = operations.first(ResolveConfigurationDependenciesBuildOperationType)
         op.details.configurationName == "compile"
-        op.failure == null
+        op.failure != null
```
Comment (wolfs) [inline platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationDependenciesBuildOperationIntegrationTest.groovy:465]: 🤔 If the failure on the operation is non-null, I think that Develocity will not show the configuration in the UI. Can you check by creating a scan from a Gradle distribution with your changes?

Comment (jvandort) [reply platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationDependenciesBuildOperationIntegrationTest.groovy:465]: Using this buildscript:

```
plugins {
    id("java-library")
}

repositories {
    mavenCentral()
}

configurations.runtimeClasspath {
    resolutionStrategy.failOnVersionConflict()
}

dependencies {
    implementation("com.google.guava:guava:33.4.0-jre")
    implementation("com.google.guava:guava:33.0.0-jre")
}

tasks.register("resolve") {
    val files = configurations.runtimeClasspath.get().incoming.files
    doLast {
        println(files.map { it.name })
    }
}
```



https://develocity.grdev.net/s/kaugollbukvow

Comment (jvandort) [reply platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationDependenciesBuildOperationIntegrationTest.groovy:465]: The build scan's dependencies tab was empty. 

This is with changes to make the build operation failure unset.

https://develocity.grdev.net/s/zqfp42doedk4w

The dependencies are shown. 

I'll remove the code that sets the failure

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultConfigurationResolver.java [hunk 5]
```diff
@@ -205,16 +205,16 @@ public ConfigurationFailureResolutions(
...
                 // owningProject is null for settings execution
                 return Collections.emptyList();
             }
 
             String taskPath = owningProject.getBuildTreePath().append(Path.path("dependencyInsight")).getPath();
 
-            ModuleVersionIdentifier identifier = conflicts.iterator().next().getVersions().get(0);
-            String dependencyNotation = identifier.getGroup() + ":" + identifier.getName();
+            ModuleIdentifier moduleId = conflict.getModuleId();
+            String dependencyNotation = moduleId.getGroup() + ":" + moduleId.getName();
```
Comment (big-guy) [inline platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultConfigurationResolver.java:217]: Two thoughts I'm unsure about:
- Will these only ever be external modules (where `group:name` makes sense)?
- What does this look like if there are version conflicts that also include substitutions? 

Would the component identifier's display name be a better identifier here?

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java [hunk 6]
```diff
@@ -176,7 +176,7 @@ void detachFromTargetNodes() {
      * end fail resolution.
      */
     void failWith(Throwable err) {
-        targetNodeSelectionFailure = new ModuleVersionResolveException(dependencyState.getRequested(), err);
+        targetNodeSelectionFailure = new ModuleVersionResolveException(selector.getSelector(), err);
```
Comment (big-guy) [inline platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java:179]: What's the difference between these?

File: platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ScriptDependencyResolveIntegrationTest.groovy [hunk 7]
```diff
@@ -90,7 +90,7 @@ rootProject.name = 'testproject'
 """
         expect:
         fails "help"
-        failureHasCause("Conflict found for the following module:")
+        failureHasCause("Conflict found for module 'org.gradle:test': between versions 1.46 and 1.45")
```
Comment (big-guy) [inline platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ScriptDependencyResolveIntegrationTest.groovy:93]: The colon is a little weird looking here.  Can we drop it? e.g.,
```
        failureHasCause("Conflict found for module 'org.gradle:test' between versions 1.46 and 1.45")
        failureHasCause("Conflict found between versions 1.46 and 1.45 for module 'org.gradle:test'.")
```

File: platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesUseCasesIntegrationTest.groovy [hunk 8]
```diff
@@ -410,7 +410,7 @@ class CapabilitiesUseCasesIntegrationTest extends AbstractModuleDependencyResolv
 
         then:
         if (failOnVersionConflict) {
-            failure.assertHasCause("Conflict found for the following module:\n  - org.ow2.asm:asm latest version of capability asm:asm")
+            failure.assertHasCause("Conflict found for module 'org.ow2.asm:asm': latest version of capability asm:asm")
```
Comment (big-guy) [inline platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesUseCasesIntegrationTest.groovy:413]: The colon is strange here too.  Can this sometimes show multiple lines?

Here are some ideas like above:
```
            failure.assertHasCause("Conflict found for module 'org.ow2.asm:asm' on latest version of capability asm:asm")
            failure.assertHasCause("Conflict found on latest version of capability asm:asm for module 'org.ow2.asm:asm'.")
```

**Review by big-guy — APPROVED** [review]

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ResolutionExecutor.java [hunk 9]
```diff
@@ -361,25 +348,14 @@ public ResolverResults resolveGraph(
 
         // TODO: Failures from dependency locking should be included in the nonFatalFailuresBuilder.
```
[the remark this answers is not in the document]
Comment (jvandort) [reply platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ResolutionExecutor.java:349]: Removed this. A less informed prior me wrote this when I thought the pattern removed in this PR was how we should handle other failures.

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultConfigurationResolver.java (hunk 5 above)
Comment (jvandort) [reply platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultConfigurationResolver.java:217]: Looking at the `DependencyResultSpec` which seems to implement filtering for the `dependencyInsight` task, the `--dependency` filter is based on the _requested_ component selector. This means it operates on a _pre_-substitution basis.

I think from a user perspective, we probably want to allow either the requested (pre-substitution) or attempted (post-substitution) component selector to satisfy the `--dependency` filter. 

These will not necessarily always be external modules. A project can participate in version conflicts. At the moment, a project always has a module version ID though. 

However, I don't think that the module version ID will satisfy the `--dependency` filter on `dependencyInsight` -- meaning we do not recommend the correct command line when project dependencies are involved. 

I think resolving this is a little more complicated than the scope of this PR is -- but I will update the `Conflict` to track the component IDs of the conflicting components, so that we can make improvements here more easily later.

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java (hunk 6 above)
Comment (jvandort) [reply platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java:179]: `dependencyState.getRequested()` is pre-substitution. 
`selector.getSelector()` is post-substitution. 

The value passed in here is used when constructing a `DefaultUnresolvedDependencyResult`, where it is used as the return value for `getAttempted`. `getAttempted` represents the _actual_ component selector we tried to resolve. 

So, we should be constructing this failure with the attempted selector, not the requested selector.

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultConfigurationResolver.java (hunk 5 above)
Comment (jvandort) [reply platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultConfigurationResolver.java:217]: The real difficulty about changing this method is when we have a project and non-project conflict participant. 

In that case, we would want `dependencyInsight` to show _both_ the project and non-project participants. But, from what I can tell, the `--dependency` filter on `dependencyInsight` does not support supplying a _list_ of dependencies to filter for. 

When having both a project and non-project component in conflict, we'd want something like

`dependencyInsight --dependency org:module --dependency :foo`

While this is unsupported, I think the current behavior is best.

File: platforms/software/software-diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy (hunk 1 above)
Comment (wolfs) [reply platforms/software/software-diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy:409]: Is there a difference now for handling version conflicts on lenient configurations? I am not sure, though might it be that before a lenient configuration that failed because of a version conflict would still resolve "normally", resolving the version conflict by the default strategy? And now, the files in the lenient configuration would not contain the artifacts from the dependency that had the version conflict?

I don't think that is necessarily bad, though I am not sure what the bigger effect is.

Comment (jvandort) [reply platforms/software/software-diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy:409]: Yeah without testing it myself I would assume you're right. 

But that's sort of the contract of lenient artifact selection -- where you don't get certain artifacts upon failure. I think this is an acceptable change

**Comment by jvandort** [comment]
Given that the colon in the message is no _worse_ than before, we will leave it in for now.

However, we discussed this a bit and determined that the _selection reason_ as is printed today, is probably not the correct thing to print. We _failed_ on version conflict. There was no valid selection. 

Also, it seems odd that capability conflicts are reported as version conflicts. `failOnVersionConflict` should not fail on capability conflicts, or we should have a more general `failOnConflict` flag.
