### PR TITLE
Fixes #6319

### LINKED ISSUE #6319: project.afterEvaluate can't be called from plugin.apply
In [this plugin](https://github.com/Triple-T/gradle-play-publisher/blob/97397c683876f2ae895dbe8c754ea4a5f8387b86/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt#L195) for example, it crashes. I don't see why that should be disallowed. The 4.10 release notes only mention calling `afterEvaluate` from `tasks.register`.

Project: https://github.com/SUPERCILEX/Robot-Scouter/tree/3986943126d1e8f661b6e3c2f986dc02e7848c9c
Setup: `./gradlew setup`

Test: `./gradlew wrapper --gradle-version 4.10-rc-1 -PdevBuild -s`. (You'll have to comment out `configureGeneral()` in my main build script.)

### PR DESCRIPTION
**Pull request by big-guy**
### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy [hunk 1]
```diff
@@ -1089,4 +1082,32 @@ class DeferredTaskDefinitionIntegrationTest extends AbstractIntegrationSpec {
...
+    @Issue("https://github.com/gradle/gradle/issues/6319")
+    def "can use getTasksByName from a lazy configuration action"() {
+        settingsFile << """
+            include "sub"
+        """
+        buildFile << """
+            plugins {
+                id 'base'
+            }
+            tasks.whenTaskAdded {
```
Comment (ghale) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy]: Help me understand - why is this important for this test?  Why not simply execute `foo` and validate that when it's realized we don't get an exception?

File: subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java [hunk 2]
```diff
@@ -130,11 +93,27 @@ public void assertCrossProjectConfigurationAllowed(String methodName, Project ta
         return new Action<T>() {
             @Override
             public void execute(T t) {
-                nestedActionExecutionCount.set(nestedActionExecutionCount.get() + 1);
+                allowExection.set(false);
                 try {
                     action.execute(t);
                 } finally {
-                    nestedActionExecutionCount.set(nestedActionExecutionCount.get() - 1);
+                    allowExection.set(true);
```
Comment (ghale) [inline subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java]: what if I do:
```
withCrossProjectConfigurationDisabled() {
    callSomethingElse()
    unsafeUserCode()
}

callSomethingElse() {
    withCrossProjectConfigurationDisabled() {
    }
}
```
Won't setting `allowExecution` to true after the inner call allow execution of the unsafe user code in the outer block?  Shouldn't we do something similar to below where we set the flag back to what it was before the call?

File: subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java [hunk 3]
```diff
@@ -25,51 +24,34 @@
...
 import org.gradle.internal.operations.RunnableBuildOperation;
-import org.gradle.util.ConfigureUtil;
 
 import java.util.Collections;
 
 public class BuildOperationCrossProjectConfigurator implements CrossProjectConfigurator {
 
     private final BuildOperationExecutor buildOperationExecutor;
-    private final ThreadLocal<Integer> nestedActionExecutionCount = new ThreadLocal<Integer>() {
+    private final ThreadLocal<Boolean> allowExection = new ThreadLocal<Boolean>() {
```
Comment (ghale) [inline subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java]: typo: `allowExecution`

File: subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java [hunk 4]
```diff
@@ -130,11 +93,27 @@ public void assertCrossProjectConfigurationAllowed(String methodName, Project ta
...
                 } finally {
-                    nestedActionExecutionCount.set(nestedActionExecutionCount.get() - 1);
+                    allowExection.set(true);
+                }
+            }
+        };
+    }
+
+    // TODO: Promote to CrossProjectConfigurator interface if this is needed elsewhere.
+    public <T> Action<T> withCrossProjectConfigurationAllowed(final Action<? super T> action) {
```
Comment (ghale) [inline subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java]: There should probably be some coverage of this method in `BuildOperationCrossProjectConfigurationTest`, too.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy (hunk 1 above)
Comment (big-guy) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy]: It changes the order of project evaluation so that the root project and subprojects are evaluated first and then tasks are realized and then this problem doesn't occur because the subproject was already evaluated by the time we get to `getTasksByName`.  This forces subprojects to be evaluated as part of evaluating the root project while in the register call.

File: subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java (hunk 3 above)
Comment (big-guy) [reply subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java]: done

File: subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java (hunk 4 above)
Comment (big-guy) [reply subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java]: done

File: subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java (hunk 2 above)
Comment (big-guy) [reply subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java]: good catch

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy (hunk 1 above)
Comment (ghale) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy]: 👍
