### PR TITLE
Fix race condition when initializing schemas of an Ivy repository (#23494)

### LINKED ISSUE #23494: Intermittent: "You must specify a base url or at least one artifact pattern for an Ivy repository" even when a base url is specified
There is already a thread in the Gradle discussion forums about this issue, but I'll give a short summary. My project has an Ivy repository configured for node.js dependencies in the settings.gradle's dependencyResolutionManagement. All the configuration is static and a url is configured. On rare occasions, and depending on the set of tasks executed, one or more tasks will fail with this error:
```shell
You must specify a base url or at least one artifact pattern for the Ivy repository 'Node.js(https://our.corporate.repository.com/repository/nodejs/)'
```

There error is intermittent and somewhat self-contradictory: it claims no URL is set, but the URL is shown in the description string.

Thread with full context: https://discuss.gradle.org/t/you-must-specify-a-base-url-or-at-least-one-artifact-pattern-for-an-ivy-repository-error/43900

### Expected Behavior

Gradle should either succeed consistently, if the repository is configured correctly, or fail consistently otherwise.

### Current Behavior
Gradle usually succeeds and rarely fails.

### Context
I think all relevant context is in this thread on the Gradle discussion forums: https://discuss.gradle.org/t/you-must-specify-a-base-url-or-at-least-one-artifact-pattern-for-an-ivy-repository-error/43900

### Steps to Reproduce 

I attempted to create a minimum-reproducible-sample that matches the behavior of my actual project. I got close: in the sample project Gradle will produce a warning intermittently instead of an error. I haven't been able to figure out what escalates the warning to an error in my actual project. Hopefully the sample project is sufficient to demonstrate the race condition, though. I will attach the sample project as a zip file. Although I can't share the code for my actual project, I will attach a thread dump with the threads paused at the moment the race condition occurs (see step 8 in reproduction steps below), since the thread dump contains no sensitive information.

[base-url-issue.zip](https://github.com/gradle/gradle/files/10395960/base-url-issue.zip)

[threads_report_from_actual_project.txt](https://github.com/gradle/gradle/files/10395950/threads_report_from_actual_project.txt)

Note that the issue happens intermittently in practice so reproducing it consistently requires using a debugger to force a specific race condition to occur.

1. Create a directory for the sample project and unpack attached zip file in that directory
2. Open settings.gradle and set the 'pathToThisDir' variable to the absolute path of the directory you unpacked the project into.
3. Set breakpoint on DefaultIvyArtifactRepository lines 163 and 223. Make sure they only suspend the current thread and not all threads. The line numbers here assume Gradle 7.4.2.
4. Run `./gradlew resolveConfiguration -Dorg.gradle.debug=true --no-daemon`
5. Attach debugger on port 5005 and wait until two or more threads stop at 163
6. Resume one thread until it stops again at 223
7. Go back to any other thread and step over the getSchemes() method call
8. (Optional) Generate a thread dump if you want to see the full stack traces
9. Detach debugger

Done correctly, you should get a warning like this:
```shell
$ ./gradlew resolveConfiguration -Dorg.gradle.debug=true --no-daemon
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

> Task :module-1:resolveConfiguration
Execution optimizations have been disabled for task ':module-1:resolveConfiguration' to ensure correctness due to the following reasons:
  - Property '$1' cannot be resolved:  You must specify a base url or at least one artifact pattern for the Ivy repository 'myrepo(file:/path/to/base-url-issue/fake-repo/)'. Reason: An input file collection couldn't be resolved, making it impossible to determine task inputs. Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#unresolvable_input for more details about this problem.

> Task :module-2:resolveConfiguration
/path/to/base-url-issue/fake-repo/v1.0/sometext-v1.0-someclassifier.txt

> Task :module-1:resolveConfiguration
/path/to/base-url-issue/fake-repo/v1.0/sometext-v1.0-someclassifier.txt

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 29s
2 actionable tasks: 2 executed
```

### Your Environment
```shell
$ ./gradlew --version

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_262 (Amazon.com Inc. 25.262-b10)
OS:           Mac OS X 10.16 x86_64

```

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #23494

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- n/a Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- n/a Provide unit tests (under `<subproject>/src/test`) to verify logic
- n/a Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation

### CODE REVIEW

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java [hunk 1]
```diff
@@ -221,9 +221,13 @@ private void validate(Set<String> schemes) {
     private Set<String> getSchemes() {
         if (schemes == null) {
             URI uri = getUrl();
-            schemes = new LinkedHashSet<>();
-            layout.addSchemes(uri, schemes);
-            additionalPatternsLayout.addSchemes(uri, schemes);
+            // use a local variable to prepare the set,
+            // so that other threads do not see the half-initialized
+            // list of schemes and fail in strange ways
```
Comment (octylFractal) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java:226]: This is not sufficient to prevent race conditions, as the variable itself is not `volatile`. I think this should be fine if `schemes` is changed to be `volatile`, as it seems the initialization is pure so running it more than once will produce the same result. If this is not the case, it will need full double-checked locking.

**Review by octylFractal — CHANGES_REQUESTED** [review]

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java (hunk 1 above)
Comment (Vampire) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java:226]: Adding `volatile` would make the threads sync on the value before accessing it.
Like it is currently, if a thread does not see the value another thread already set it will recalculate the value.
Which should not be a problem as the value should be reproducible and not change.
So different threads might use different identical lists but that should be ok, shouldn't it?

Adding `volatile` would reduce the amount of times this initialization is done for the price that the field is synchronized on each read.

The problem with the previous implementation was, that if thread A set the empty list, then thread B is started and thus has that value for the field and sees the empty list.

Don't you think it should be sufficient like it is?

If not, we should probably also use an immutable list as value just to make sure no thread is modifying it as the current instance also is not thread-safe if it would be modified by some code.

Comment (octylFractal) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java:226]: Yes, `volatile` would make the threads sync, though in practice on x86 this isn't very noticeable and on ARM it should be pretty quick still, I don't think this is a highly contested field.

It is necessary to sync because the fields of an object are subject to different memory synchronization than the reference itself, i.e. without `volatile` it is still perfectly legal for thread A to assign the field to the object reference, and finish initializing it _after_ B has read the object reference as per https://shipilev.net/blog/2016/close-encounters-of-jmm-kind/#wishful-benign-is-resilient.

I am all for using an immutable instance, though depending on exactly how it is constructed it may still require `volatile` to ensure thread safety.

Comment (Vampire) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java:228]: Ok, I added `volatile` and the immutability now. :-)

**Review by octylFractal — APPROVED** [review]

**Review by ljacomet — APPROVED** [review]

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by octylFractal** [comment]
Thank you for your contribution!
