### PR TITLE
Respect JavaCompile -sourcepath defined by user for modules

### LINKED ISSUE #18262: JavaCompile ignores custom `-sourcepath` since 7.0
The `-sourcepath` specified in `CompileOptions` for a `JavaCompile` task seems to be ignored starting in Gradle 7.0.

### Expected Behavior

Up to Gradle 6.9.1, the custom source path was passed to the compiler as expected.

### Current Behavior

Starting with 7.0, the task fails with and running with debug logging enabled reveals that `-sourcepath D:\GW2ToolBelt\GW2ML\src\main\java-jdk9` is used instead of `-sourcepath D:\GW2ToolBelt\GW2ML\src\main\java;D:\GW2ToolBelt\GW2ML\src\main\java-jdk9`.

### Context

I ran into this issue while updating from Gradle 6.8.2 to 7.2 in a project that uses a custom `compileJava9` task to compile a module descriptor for a multi-release jar:

```kotlin
val compileJava9 = create<JavaCompile>("compileJava9") {
    destinationDirectory.set(File(buildDir, "classes/java-jdk9/main"))

    val java9Source = fileTree("src/main/java-jdk9") {
        include("**/*.java")
    }

    source = java9Source
    options.sourcepath = files(sourceSets["main"].java.srcDirs) + files(java9Source.dir)

    classpath = files()

    options.release.set(9)

    afterEvaluate {
        options.compilerArgs.add("--module-path")
        options.compilerArgs.add(compileJava.get().classpath.asPath)
    }
}
```

The full project is available at https://github.com/GW2ToolBelt/GW2ML/tree/f7fa2104772345f249ad1d28199376aff7391545.

### Steps to Reproduce 

1. Clone https://github.com/GW2ToolBelt/GW2ML
2. Run `gradlew compileJava9 --debug`

### PR DESCRIPTION
**Pull request by asodja**
From 7.x options.sourcepath were overwritten when modules were used. Now if user specifies options.sourcepath we don't overwrite it.

Fixes #18262

### CODE REVIEW

**Comment by asodja** [comment]
I figured we anyway do full recompilation in case java options change. So I will do it differently.

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java [hunk 1]
```diff
@@ -117,7 +117,9 @@ public JavaCompile() {
     @Override
     @Internal("tracked via stableSources")
     public FileTree getSource() {
-        return super.getSource();
+        return compileOptions.getSourcepath() != null && !compileOptions.getSourcepath().isEmpty()
```
Comment (wolfs) [inline subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java]: I currently don't understand enough about `sourcepath` to know what the right solution is here. If we add the sourcepath as regular sources, why isn't it set to be that in the first place? And if we add the sourcepath here, then we should mark `CompileOptions.getSourcepath()` as `@Internal`, since we don't need to track it as an input any more.

Note that the way it is now, `CompileOptions.getSourcepath()` is not marked as `@Incremental`, so any change to the files there will cause a full recompilation.

**Comment by asodja** [comment]
@bot-gradle test QFL

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java (hunk 1 above)
Comment (asodja) [reply subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java]: I reverted that. I figured that is not the right solution anyway. I changed it so we don't set options.sourcepath ourselves if user set them manually.

I think this is better also now it works in the same way as it did in 6.9.1

Comment (wolfs) [reply subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java]: Ah, so the problem is only if you have some modules on the classpath, right?

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java (hunk 1 above)
Comment (asodja) [reply subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java]: Yeah it looks like it. Without module sourcepath defined by user is passed to javac.

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle help

**Comment by asodja** [comment]
@bot-gradle test AST

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy [hunk 2]
```diff
@@ -1071,4 +1071,36 @@ class JavaCompileIntegrationTest extends AbstractPluginIntegrationTest {
...
+            module com.example {
+                exports com.example;
+            }
+        """
+
+        expect:
+        succeeds("compileCustomJava")
+        file("build/classes/java-custom-path/main/module-info.class").exists()
+        // We compile only classes defined in `source`
+        !file("build/classes/java-custom-path/main/com/example/SourcePathTest.class").exists()
```
Comment (ljacomet) [inline subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy:1104]: There is something I do not follow. Why is that file not compiled? It should be part of `options.sourcepath`, which is custom set and thus to be respected.
Or did I misunderstand something?

Comment (asodja) [reply subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy:1104]: This PR makes `options.sourcepath` work the same way as it did before 7.0. I am not sure why `options.sourcepath` worked that way before. As I understand `-sourcepath` it's very similar to JavaCompile `source` input, it can also have jars and zips though.
We can change behavior of it. But I would also like to better understand why user chose `options.sourcepath` over Gradle's `source` in this case.

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test and merge
