### PR TITLE
Fix outgoing edge reference counting

### LINKED ISSUE #13960: Classpath not correct with platform bom
Running gradle tests fail with a class not found exception, even though the class is on the classpath. Changing `platform` to `enforcedPlatform` allows the tests to pass, even though that should have no impact because there is no conflict.

Also what seems to be related is a failure in IntelliJ to load the project:
```
<ij_msg_gr>Dependency graph model errors<ij_msg_gr><ij_nav>/Users/jameskleeh/IdeaProjects/sample-projects/temp/build.gradle<ij_nav><i><b>root project 'temp'</b><eol>Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':testCompileClasspath'.<eol>Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /private/var/folders/n0/tf0_z4wj0b14g5rdg6qwxhww0000gn/T/gradle5413559650647014364.bin offset 27963 exists? true<eol>Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (123) for constraint apiElements -> io.micronaut:micronaut-messaging:2.0.1</i>
```

That failure also goes away when the change from `platform` to `enforcedPlatform` is done

### Expected Behavior
The tests should pass

### Current Behavior
```

> Task :test FAILED

TempSpec > initializationError FAILED
    io.micronaut.context.exceptions.BeanInstantiationException at DefaultBeanContext.java:1540
        Caused by: io.micronaut.context.exceptions.BeanInstantiationException at DefaultBeanContext.java:1918
            Caused by: java.lang.NoClassDefFoundError at DefaultBeanContext.java:1889
                Caused by: java.lang.ClassNotFoundException at URLClassLoader.java:382

1 test completed, 1 failed

FAILURE: Build failed with an exception.
```

### Context
I'm trying to run tests.

### Steps to Reproduce 
https://github.com/jameskleeh/gradle-bug
Execute `./gradlew test`

### Your Environment
OSX
JDK8
Gradle 6.5.1

### PR DESCRIPTION
**Pull request by melix**
We were systematically decreasing the number of outgoing
edges even if we didn't actually remove an outgoing edge
in some cases. This commit makes sure that the reference
count is correct in this case.

Fixes #13960

### CODE REVIEW

**Comment by melix** [comment]
Candidate for backporting if we do a 6.6.1.

@bot-gradle test this

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/DependencyConstraintsBugsIntegrationTest.groovy [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+        given:
+        buildFile << """
+            plugins {
+                id 'java-library'
+            }
+
+            ${jcenterRepository()}
+
+            dependencies {
+                implementation(platform("io.micronaut:micronaut-bom:2.0.1"))
```
Comment (ljacomet) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/DependencyConstraintsBugsIntegrationTest.groovy:37]: One trick I have used to transform real world issues into minimal graphs is to add metadata rules and start pruning dependencies. At some point you hit a sweet spot: removing one more no longer reproduces.
And then you hope what's left is a couple not a dozens 😉

File: subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/fixtures/publish/ModuleVersionSpec.groovy [hunk 2]
```diff
@@ -129,11 +129,20 @@ class ModuleVersionSpec {
     }
 
     void variant(String name, @DelegatesTo(value = VariantMetadataSpec, strategy = Closure.DELEGATE_FIRST) Closure<?> spec) {
-        def variant = new VariantMetadataSpec(name)
+        def variant = variants.find { it.name == name }
```
Comment (ljacomet) [inline subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/fixtures/publish/ModuleVersionSpec.groovy:132]: This changes are not exercised by the PR. If we were to put it in 6.6.1, I would drop them from the PR.

**Review by ljacomet — APPROVED** [review]
All good, though I am biased on the change 😄 

Two comments, see below.

File: subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/fixtures/publish/ModuleVersionSpec.groovy (hunk 2 above)
Comment (melix) [reply subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/fixtures/publish/ModuleVersionSpec.groovy:132]: Indeed I wrote that as part of trying to write a test case to exercise this problem.

**Comment by ljacomet** [comment]
@melix Once CI passes, can you merge on `release` instead?

**Comment by melix** [comment]
I'd rather cherry pick.

**Comment by melix** [comment]
Cherry picked and pushed to `release`.
