### PR TITLE
Configure TestLauncher's StartParameter on the client side

### LINKED ISSUE #26056: TestLauncher cannot run the same test in different test tasks if configuration cache is enabled
### Current Behavior

Running a test method twice in different test tasks result in the following exception:

```
Reusing configuration cache.
FAILURE: Build failed with an exception.
* What went wrong:
Task with name 'forkingIntegTest' not found in project ':language-java'.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
BUILD FAILED in 353ms
Publishing build scan...
https://ge.gradle.org/s/nnkvf236omh5u
Configuration cache entry reused.
```

### Expected Behavior

No Exception.
The configuration cache entry should not be reused if a different test task is specified via the TestLauncher.

### Context (optional)

IntelliJ IDEA has support for invoking Gradle tests via the `TestLauncher` API that will be eventually turned on by default. I assigned this issue to the next RC1 milestone as fixing this issue later might delay the adoption further.

### Steps to Reproduce

1. Open IntelliJ IDEA 2023.2 and import the gradle/gradle repository
2. In the menu, click Help > Edit Custom Properties... and add `gradle.testLauncherAPI.enabled=true`
3. Restart IDEA
4. Go to `JavaIncrementalCompilationWithCachingIntegrationTest` and run the `incremental state is restored from the build cache` with the green play button. Select the `embeddedIntegTest` task and observe the passing test.
5. Edit the freshly created run configuration and replace `embeddedIntegTest` with `forkingIntegTest`.
6. Execute the modified run configuration and observe the build failure.

### Gradle version

8.4-20230719142735+0000

### Build scan URL (optional)

https://ge.gradle.org/s/nnkvf236omh5u

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by mlopatkin**
Fixes #26056

### CODE REVIEW

**Review by donat — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test RFN

File: subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/action/TestExecutionRequestAction.java [hunk 1]
```diff
@@ -69,14 +73,42 @@ public TestExecutionRequestAction(BuildEventSubscriptions clientSubscriptions,
...
+            startParameter.getTaskNames());
+        if (!taskSpecs.isEmpty()) {
+            List<String> taskPaths = taskSpecs.stream().map(InternalTaskSpec::getTaskPath).collect(Collectors.toList());
+
+            Preconditions.checkArgument(
+                !runDefaultTasks,
+                "Cannot run default tasks when task specs %s are provided",
+                taskPaths);
+
+            startParameter.setTaskRequests(Collections.singletonList(new DefaultTaskExecutionRequest(taskPaths)));
```
Comment (bamboo) [inline subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/action/TestExecutionRequestAction.java:104]: 💅 I'd move this side-effect to the caller and make this method simply return the new list of requests.

**Review by bamboo — APPROVED** [review]

**Comment by mlopatkin** [comment]
@bot-gradle test and merge
