### PR TITLE
Resolve opened file path before notifying configuration cache listener

### LINKED ISSUE #19426: Relative paths for detected file inputs are wrong in the configuration cache report
Consider the following build file:
```groovy
// Creating files is irrelevant to the issue, it is here to make the sample self-contained
new File("provider.txt").text = "provider"
new File("fis.txt").text = "fis"

def provider = providers.fileContents(layout.file(providers.provider { new File("provider.txt") }))
println("provider = ${provider.asText.get()}")

def fis = new FileInputStream("fis.txt")
println("fis = ${fis.text}")
fis.close()
```
executed with configuration cache enabled: `gradle --configuration-cache`
### Expected Behavior
Both file inputs are detected and the configuration cache report shows paths relative to the project directory: `provider.txt` and `fis.txt`.

### Current Behavior
Both file inputs are properly detected but the configuration cache report shows the weird (and wrong) path to the file opened with the FileInputStream:
image

This problem only affects the report, changes to the file are correctly handled.

### Your Environment
Gradle 7.5 nightly (`7.5-20211223145946+0000`)

Build scan URL: https://scans.gradle.com/s/hhdk6ppeghdye

### PR DESCRIPTION
**Pull request by bamboo**
Fixes #19426

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test and merge

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy [hunk 1]
```diff
@@ -30,6 +30,41 @@ import static org.gradle.integtests.fixtures.configurationcache.ConfigurationCac
...
+        given:
+        file('provider.txt').text = 'provider'
+        file('fis-path.txt').text = 'fis-path'
+        file('fis-file.txt').text = 'fis-file'
+        buildFile '''
+            providers.fileContents(layout.projectDirectory.file("provider.txt")).with { provider ->
+                println("provider = ${provider.asText.get()}")
+            }
+
+            new FileInputStream("fis-path.txt").withCloseable { fis ->
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy:43]: IMO, it would be nice to have `FileInputStream(file("...."))` (i.e. with absolute path as an argument) covered there as well. It is somewhat covered in other tests but this one looks more focused.

**Review by mlopatkin — APPROVED** [review]
lgtm, thanks!

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy (hunk 1 above)
Comment (bamboo) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy:43]: Good point. Done.

**Comment by bamboo** [comment]
@bot-gradle test and merge
