### PR TITLE
Only display the build scan hint when the Gradle Enterprise plugin is not applied

### LINKED ISSUE #18956: Help output recommends --scan when build scan already enabled
We enable build scans by default, but error help output includes:

```
* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

Publishing build scan...
https://gradle.netflix.net/s/dcshzq73ran3i
```

If switches are detected this output is suppressed, but this doesn't consider that scans could be enabled already.

### Expected Behavior
The --scan help shouldn't be output when build scans are already enabled.

### Current Behavior
The help is output regardless.

### Context
It's confusing.

### Steps to Reproduce 
1. Cause an error
2. Note the output

### Your Environment
Gradle 7.3

### PR DESCRIPTION
**Pull request by ghale**
Fixes #18956

This changes the error message at the end of a build to only suggest using `--scan` when the Gradle Enterprise plugin has not been applied.

One implication of this is that the `use --scan` suggestion will no longer be printed in scenarios where the GE plugin is applied, but for some reason build scan publishing is disabled.  This is not a situation we could handle without either 1) making Gradle build tool know more about the internals of the GE plugin or 2) allowing the GE plugin to somehow modify the suggestions when there is a failed build.  This seems like an unlikely case given the vast majority of our users configure `publishAlways()`.

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test RFM

File: subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java [hunk 1]
```diff
@@ -66,29 +68,38 @@ public void buildFinished(BuildResult result) {
...
             return;
         }
 
-        renderSingleBuildException(failure);
+        renderSingleBuildException(failure, gradleEnterprisePluginApplied);
+    }
+
+    private boolean isGradleEnterprisePluginApplied(BuildResult result) {
+        GradleInternal gradle = (GradleInternal) result.getGradle();
+        return gradle != null && gradle.getSettings().getPluginManager().hasPlugin(AutoAppliedGradleEnterprisePlugin.ID.getId());
```
Comment (ldaley) [inline subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java:91]: Probably better to use `GradleEnterprisePluginManager.isPresent()` instead, to be more consistent with other sites.

File: subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java [hunk 2]
```diff
@@ -125,11 +136,11 @@ private ExceptionStyle getShowStackTraceOption() {
         }
     }
 
-    private FailureDetails constructFailureDetails(String granularity, Throwable failure) {
+    private FailureDetails constructFailureDetails(String granularity, Throwable failure, boolean gradleEnterprisePluginApplied) {
```
Comment (ldaley) [inline subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java:139]: To avoid spreading this param around, I'd consider passing in some kind of more general strategy object here that can populate the resolution details. Your call though.

**Comment by ghale** [comment]
@bot-gradle test RFM

File: subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java (hunk 1 above)
Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java]: Ah, didn't even see this there.  And the other approach was causing problems under certain conditions, as well.  Changed.

File: subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java (hunk 2 above)
Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java]: Yep, good suggestion.  Done.

**Comment by ghale** [comment]
@bot-gradle test RFM

**Comment by ghale** [comment]
@bot-gradle test RFM

File: subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java [hunk 3]
```diff
@@ -277,6 +231,96 @@ private void writeFailureDetails(StyledTextOutput output, FailureDetails details
...
+                output.text("Run with ");
+                output.withStyle(UserInput).format("--%s", StartParameterBuildOptions.BuildScanOption.LONG_OPTION);
+                output.text(" to get full insights.");
+            });
+        }
+    }
+
+    private static boolean isGradleEnterprisePluginApplied(BuildResult result) {
+        GradleInternal gradle = (GradleInternal) result.getGradle();
+        return gradle != null && gradle.getServices().get(GradleEnterprisePluginManager.class).isPresent();
```
Comment (DPUkyle) [inline subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java:321]: Can `gradle.getServices()` or `gradle.getServices().get(GradleEnterprisePluginManager.class)` ever return null?

**Review by ldaley — APPROVED** [review]
LGTM from a functional perspective.

In terms of code structure, I'd consider creating a BuildLoggerFactory or similar that is dependency injected with the common infrastructure it uses, then using this factory at the use site to create contextualised loggers.

File: subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java (hunk 3 above)
Comment (big-guy) [reply subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java:321]: Instead of getting the service from the build result, could this be injected into the BuildExceptionReporter?

Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java]: I think it's pretty unlikely that `getServices()` would return null.  Or rather, if it did, a bunch of other stuff would go up in flames along with this.  And I don't think we construct a `Gradle` object anywhere that isn't backed by `BuildTreeScopeServices`, but that's maybe a more plausible failure case - that a `GradleEnterprisePluginManager` is not in the service registry.  It wouldn't be null, of course, but `get()` would return an `UnknownServiceException`.

I've changed it to handle such a case gracefully as we'd rather have the build failure than some weird service exception.

**Comment by ghale** [comment]
Yeah, I think turning this into something contextual and dependency injected is the way to go.  I don't see a clear path to it yet, though, since `BuildExceptionReporter` is needed by things so early in the startup.  I'm sure we can get there, I just don't see all the pieces yet.  I'd prefer to merge this as-is and circle back to refactor it as a second piece of work.

**Comment by ghale** [comment]
@bot-gradle test and merge

File: subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java (hunk 3 above)
Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java]: Sorry @big-guy I didn't see your message until after I had already posted my previous reply (wasn't ignoring you).  I think we definitely want to inject this in some way, but `BuildExceptionReporter` is constructed way early, before any service registries or anything are created and all of the context that we care about comes along later and is specific to an individual build itself (just like the build result).  I think we could probably extract some sort of `BuildFailureRenderer` or something like that which is build-specific and travels with the `BuildResult` (and gets injected with what it needs).  Or we could populate the failure details and pass something along with the build result more rich than just a throwable.  It seems like there are some ways to refactor all fo this stuff, but I don't see a clear path just yet.

Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java]: Actually, now that I'm digging through all the layers of this thing, I'm understanding better how this works and grokking @ldaley's comment a lot better.  I was _really_ confused by the name `ToolingBuildTreeScopeServices` (and its package) thinking this only applied to tooling api invocations and didn't realize this was being used in command line invocations as well.  I think I see where to go with this now.

**Comment by ghale** [comment]
@bot-gradle test RFM

File: subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java (hunk 3 above)
Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java]: Man, I completely misunderstood how `BuildExceptionReporter` was being invoked in command line builds and thought it would require a much more significant refactor to get `GradleEnterprisePluginManager` injected in some way.  

_shakes head in disgust_  

In any event, I've reworked this so that this is all getting injected via service infrastructure along the lines of what @ldaley suggested.  Much better now.

**Review by big-guy — APPROVED** [review]
Thanks Gary

**Comment by ghale** [comment]
@bot-gradle test and merge
