### PR TITLE
Let eclipse-wtp remove the "jst.utility" facet in ejb modules

### LINKED ISSUE #17681: eclipse-wtp EJB projects are not compatible with eclipse "jst.ejb" facet
When you want to create an EJB project with gradle and eclipse-wtp, the project, by default, is just defined as _a JEE utility project_.
In order to let eclipse recognize it as an EJB project, you can activate the "jst.ejb" facet as in the configuration below:
```
apply plugin: 'java'
apply plugin: 'eclipse-wtp'
repositories {
    mavenCentral()
}
dependencies {
    compileOnly  group: 'jakarta.platform', name: 'jakarta.jakartaee-api', version: '8.0.0'
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
eclipse.wtp.facet { 
    facet name: 'jst.ejb', version: '3.2'
}
```
However since eclipse-wtp define such a project as an eclipse JEE utility project, the projects has then both facets "jst.utility" and "jst.ejb" installed. 
The these two facet are incompatible for eclipse (as describe in [eclipse wtp proposal](https://www.eclipse.org/webtools/development/proposals/WtpProjectFacets.html))

### Expected Behavior
When you add the "jst.ejb" facet, eclipse-wtp should remove "jst.utility" facet, installed by default

### Current Behavior
The generated eclipse project has both "jst.utility" and "jst.ejb" facets installed.
In the eclipse project properties,  the project facet tab states that "EJB module and Utility module cannot both be selected"

You can manually deselect the utility module checkbox. However, since the eclipse configuration is defined using the eclipse-wtp plugin, the problem will reappear.

### Context
I'm trying to convert JEE eclipse projects as gradle projets.
Developers are using Eclipse IDE and gradle is used in CI/CD.
The CI/CD works great, however the developer aren't happy because the eclipse facets are not well defined.

### Steps to Reproduce 
In eclipse clone and import as a gradle projet the example project, https://github.com/HvB/ExampleEjb 
Open the project properties and go to the facet tab.

### Your Environment
Eclipse 2021.06 (but we have the same problem with previous versions)
gradle 7.1 (we have also the same problem with previous versions)

### PR DESCRIPTION
**Pull request by HvB**
Fixes #17681

### Context

The gradle _eclipse-wtp_ plugin adds an Eclipse `jst.utility` facet to each java project. 
If you want Eclipse IDE to recognize it as  an EJBs project, you have to add a `jst.ejb` facet:

```groovy
eclipse.wtp.facet { 
    facet name: 'jst.ejb', version: '3.2'
}
```
However as `jst.ejb` and `jst.utility` facets are incompatible, Eclipe IDE will complain and state that it is misconfigured.

If you use gradle to build projects but want to use the Eclipse  IDE, then the gradle configuration should be considered as the source of truth. However this implies that the _eclipse_ and _eclipse-wtp_ plugins must configure the corresponding Eclipse projects correctly. 

In addition, to align with the behavior of the Eclipse IDE wizard, the `jst.ejb` facet should also be defined as `fixed`.

This can be done using the `EclipseWTPFacet.file` method:

```groovy
eclipse.wtp.facet.file.whenMerged { it.facets = it.facets.findAll { it.name != 'jst.utility' }}
```
but, in my opinion, this should be reserved for tricky edge cases not basic project configuration.  

That's why I think developers using the Eclipse IDE would benefit from this change.

Relevant forum: https://discuss.gradle.org/t/easily-customize-the-eclipse-wtp-facet-version/8690

#### Remark:

I'm not sure if the `EclipseWTPFacet.facet` method is the right place to add this modification, but I haven't found a better one.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test RFM

File: subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtpFacet.java [hunk 1]
```diff
@@ -138,17 +140,26 @@ public void setFacets(List<Facet> facets) {
...
      * <p>
+     * In the case of a "jst.ejb" facet, the incompatible "jst.utility" installed by default is also removed.
+     * </p>
      * For examples see docs for {@link EclipseWtpFacet}
      *
      * @param args A map that must contain a 'name' and 'version' key with corresponding values.
      */
     public void facet(Map<String, ?> args) {
         Facet newFacet = ConfigureUtil.configureByMap(args, new Facet());
+        List<Facet> newFacets;
```
Comment (donat) [inline subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtpFacet.java:151]: ❌ If the client sets the facets with `setFacets()` then the facet replacement check would not kick in. One could argue that then it's the clients responsibility there, at the same time, it the inconsistency between those methods can be very confusing.

A better place for the facet replacement would be `EclipseWtpFacet.mergeXmlFacet()`. It would be always called and the client would still have the chance to do final adjustments in the `whenMerged` callback.

```java
    public void mergeXmlFacet(WtpFacet xmlFacet) {
        file.getBeforeMerged().execute(xmlFacet);
        xmlFacet.configure(replaceInconsistentFacets(getFacets()));
        file.getWhenMerged().execute(xmlFacet);
    }
}
```

File: subprojects/docs/src/docs/release/notes.md [hunk 2]
```diff
@@ -10,6 +10,8 @@ Include only their name, impactful features should be called out separately belo
 -->
 We would like to thank the following community members for their contributions to this release of Gradle:
 
+[Herbert von Broeuschmeul](https://github.com/HvB)
```
Comment (donat) [inline subprojects/docs/src/docs/release/notes.md:13]: ❌ In the upgrading_version_X.adoc file please list this change under `Potential breaking changes` to let other users know of the altered behavior.

**Review by donat — CHANGES_REQUESTED** [review]
Sorry for the super-late review. The changes make sense, although I think we can do a bit better in terms of consistency. See my comments.

**Comment by stalb** [comment]
@donat I've made the requested modifications.

Do you want a rebase ?

File: subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtpFacet.java (hunk 1 above)
Comment (stalb) [reply subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtpFacet.java:151]: If the verification should be done when the client sets the facets with `setFacets`, we could also put it there: 

```java
    public void setFacets(List<Facet> facets) {
        this.facets = replaceInconsistentFacets(facets);
    }
```

Comment (HvB) [reply subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtpFacet.java:151]: If the replacement should be done when client sets the facets with `setFacets()`, why not put it in the setter ?

```java
    public void setFacets(List<Facet> facets) {
        this.facets = replaceInconsistentFacets(facets);
    }
```

**Comment by HvB** [comment]
@donat I have made the requested modifications.

Do you want a rebase?

File: subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtpFacet.java (hunk 1 above)
Comment (donat) [reply subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtpFacet.java:151]: It's mostly a nitpick from my side, but calling `replaceInconsistentFacets()` in `mergeXmlFacet()` ensures that the filtering/replacement happens exactly once. If you see any downsides then I'm fine with moving it `facets()` and `setFacets()`.

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by donat** [comment]
> Do you want a rebase?

 You don't have to worry about it.

File: subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc [hunk 3]
```diff
@@ -108,6 +108,21 @@ Previously Gradle used to detect if an input file collection annotated with `@Sk
 To ignore directories in Gradle 8.0 and later, the input property needs to be explicitly annotated with `@IgnoreEmptyDirectories`.
 For more information see <<empty_directories_file_tree>>.
 
+==== Project facets generated by the `eclipse wtp' plugin have changed
```
Comment (donat) [inline subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc:111]: Short and clear. 👍 for that!

**Review by donat — APPROVED** [review]

File: subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc (hunk 3 above)
Comment (nathan-contino) [inline subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc:111]:
```suggestion
==== Adding `jst.ejb` with the `eclipse wtp' plugin now removes the `jst.utility` facet
```
Suggestion: the proposed title is short, but I think it could be clearer. Perhaps a reword can provide additional detail without getting too lengthy.

File: subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc [hunk 4]
```diff
@@ -108,6 +108,21 @@ Previously Gradle used to detect if an input file collection annotated with `@Sk
...
+
+A `jst.utility` facet was added to java projects by the `eclipse wtp` plugin. 
+This facet will now be removed when you add a `jst.ejb` facet:
```
Comment (nathan-contino) [inline subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc:114]:
```suggestion
The `eclipse wtp` plugin adds the `jst.utility` facet to java projects.
Now, adding the `jst.ejb` facet implicitly removes the `jst.utility` facet: 
```
Nitpick: use active voice and simpler phrasing when possible.
Suggestion: it might be useful for readers to know why we avoid combining these facets. Consider adding a glue sentence in between that explains that motivation -- "But using the `jst.ejb` and `jst.utility` facets in the same projects led to _____." -- or similar.

**Review by nathan-contino — APPROVED** [review]
Docs LGTM, a couple of suggestions though.

**Comment by donat** [comment]
I've squashed and rebased the branch to the latest master to keep the history clean.

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@HvB Thank you for the contribution!
