### PR TITLE
Report all files in directory as changed for incremental task for non-incremental change

### LINKED ISSUE #4166: If the task is non-incremental, not all files in a directory are reported as outOfDate
Given an incremental Task.
If a property annotated with `@InputFiles` contains directories, then the files in the directory are not reported by `IncrementalTaskInput.outOfDate` if the inputs are non-incremental, but only the directory itself.

This is different to when the inputs are incremental, then all the files in the directory and the directory itself are reported as `outOfDate`.

For the example, let us assume the following build file:

```
task sampleTask(type: SampleTask) {
    sampleTask.inputFiles = files("input")
    outputDir = file("${buildDir}")
}

class SampleTask extends DefaultTask {

    @OutputDirectory
    File outputDir

    @InputFiles
    FileCollection inputFiles

    @TaskAction
    void run(IncrementalTaskInputs inputs) {
        if (!inputs.incremental) {
            println "Task is not incremental"
            project.delete(outputDir.listFiles())
        } else {
            println "Task is incremental"
        }

        inputs.outOfDate { InputFileDetails details ->
            logger.lifecycle '[OUT-OF-DATE] Input file {} added={}, changed={}, removed={}', details.file.name, details.added, details.modified, details.removed
        }

        inputs.removed { InputFileDetails details ->
            logger.lifecycle '[REMOVED] Input file {} added={}, changed={}, removed={}', details.file.name, details.added, details.modified, details.removed
        }

        new File(outputDir, "output.txt").text = "Sample output."
    }
}
```

And a directory structure like this:
```
input
|---- file1.txt
|---- file2.txt
```

### Expected Behavior
When running `gradle sampleTask` for the first time then we get the following output:
```
> Task :sampleTask
Task is not incremental
[OUT-OF-DATE] Input file input added=false, changed=false, removed=false
[OUT-OF-DATE] Input file file1.txt added=false, changed=false, removed=false
[OUT-OF-DATE] Input file file2.txt added=false, changed=false, removed=false
```

### Current Behavior
Only the added directory is reported:
```
> Task :sampleTask
Task is not incremental
[OUT-OF-DATE] Input file input added=false, changed=false, removed=false
```

### Context
The files to be considered as out of date should be consistent for incremental and non-incremental task execution. The current behavior is confusing.

Originally reported in https://github.com/gradle/gradle/issues/4114#issuecomment-359990657.

Note that for input directories, all the files in the directory are reported as `outOfDate` in the first run.

### Steps to Reproduce (for bugs)
See above.

### Your Environment
Gradle 4.5

### LINKED ISSUE #4204: Inconsistent handling of root directories between `@InputFiles` and `@InputDirectory`
Annotation an input property which points to a directory with `@InputFiles` causes a different behavior to annotating the same property with `@InputDirectory`.
See https://github.com/gradle/gradle/issues/4114#issuecomment-361347312.

### Expected Behavior
`@InputFiles` and `@InputDirectory` only differ in validation of the input property, but have the same effect on what files are tracked as input.

### Current Behavior
`@InputFiles` tracks the root directory while `@InputDirectory` does not. If the directory is empty, then changing the actual path causes the task to be out-of-date when using `@InputFiles` and up-to-date when using `@InputDirectory`.

### Context
See https://github.com/gradle/gradle/issues/4114#issuecomment-361347312.

It is not intuitive that these two annotations behave differently in what is tracked. We should make this consistent so it is easier to add the right input annotations.

### Steps to Reproduce (for bugs)
Consider the following build file:
```
abstract class BaseTask : DefaultTask() {
    abstract val input: File

    @OutputFile
    lateinit var output: File

    @TaskAction
    fun doStuff() {
        output.writeText(input.list().joinToString("\n"))
    }
}

open class WithInputFiles : BaseTask() {
    @InputFiles
    override lateinit var input: File
}

open class WithInputDirectory : BaseTask() {
    @InputDirectory
    override lateinit var input: File
}

val inputDir = file("inputDir" + property("select"))
inputDir.mkdirs()

tasks.create<WithInputDirectory>("inputDir") {
    input = inputDir
    output = project.file("build/fromDir.txt")
}
tasks.create<WithInputFiles>("inputFiles") {
    input = inputDir
    output = project.file("build/fromFiles.txt")
}
```

When running `gradle -Pselect=1 inputDir` followed by `gradle -Pselect=2 inputDir`, then the `inputDir` task is up-to-date in the second run.

When running `gradle -Pselect=1 inputFiles` followed by `gradle -Pselect=2 inputFiles`, then the `inputFiles` task is executed and out-of-date in the both runs.

### Your Environment
Build scan URLs:
- Second run with `inputDir`: https://gradle.com/s/gejgkbduxquym
- Second run with `inputFiles`: https://scans.gradle.com/s/gquybhty5udkk

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Fixes #4204, fixes #4166

### CODE REVIEW

**Comment by marcphilipp** [comment]
@SUPERCILEX Thanks for the PR! Could you please look into the test failures on CI?

**Comment by SUPERCILEX** [comment]
@marcphilipp Ok, I think I've got it:
- I disabled hard `optional` checks until Gradle 5.0 as discussed in https://github.com/gradle/gradle/pull/5866#issuecomment-403417420
- `CalculatedTaskInputFileCollection` supports retrieving files without a cache similarly to `CachingTaskInputFileCollection`

**Comment by SUPERCILEX** [comment]
@marcphilipp Ouch, looks like everything is failing earlier now so we'll have to change the tests to look at the right caused by exception. I'm going to be gone for the next 2 weeks (yay! 🍹🌴🕶), but I'll fix this all up when I come back. 👍

**Comment by SUPERCILEX** [comment]
@marcphilipp PS: is there a way to build Gradle without having to install Java 9? This broke a week or so ago.

**Comment by marcphilipp** [comment]
@SUPERCILEX There was a recent change to the build that makes it require Java 9 now. So, I'm afraid you'll have to install it to build locally.

**Comment by SUPERCILEX** [comment]
@marcphilipp Alright, I'm back, but in need of help. Splitting everything into a file tree makes #2463 extremely apparent and breaks stuff because directories show up.

I'm trying to figure out how I can remove directories from showing up as task inputs _only_. It no longer makes sense for directories to be part of task inputs because a deep search is always performed with this PR, meaning if there are files under the directory, they will be included.

I tried a [naive implementation by filtering](https://github.com/gradle/gradle/pull/6019/files#diff-edfeef99fdd02fa0f9b1fdd18d7ed580), but that's obviously the wrong way to do it because it will be bad for performance and it breaks relative path sensitivity. Should I be creating my own custom resolver? Or messing with the file visitor? I'm unsure of how to proceed and would appreciate any help. 😊

**Comment by wolfs** [comment]
@SUPERCILEX Quite some stuff has changed on `master` since you first opened the PR. Can you try and see if #4204 is already fixed on `master`?

**Comment by SUPERCILEX** [comment]
@wolfs It's not going to be fixed because `inputs.dir(...)` uses a `FileTree` whereas `inputs.files(...)` uses a composite collection. This PR is trying to make both use a `FileTree`.

**Comment by SUPERCILEX** [comment]
@wolfs @marcphilipp So actually, I decided to figure the directory stuff in another PR. This one is now green when running `./gradlew core:build`.

**Comment by wolfs** [comment]
@SUPERCILEX I checked myself and #4204 is fixed in 4.10.

**Comment by wolfs** [comment]
@SUPERCILEX What does this PR address? It doesn't seem to address #4204 or #4166, right? Is it trying to address https://github.com/gradle/gradle/issues/2016?

**Comment by SUPERCILEX** [comment]
@wolfs No, I added the optional stuff because I was confused as to why input files didn't have validation, but I'd be happy to remove those changes if you'd like.

This PR does address #4166 because we're using a file tree which does a deep search with the provided root. See b63ddf1 for a test that passes in this PR and fails on master.

**Comment by wolfs** [comment]
In order to fix #4166 I would suggest to change `RebuildIncrementalTaskInputs`, so it doesn't use the `TaskProperties` but instead uses `FileCollectionFingerprint.getFingerprints()` (`CurrentTaskExecution.getInputFingerprints()`). All the fingerprints would then be reported as added. That has the advantage that we don't need to walk the file system again, since we already have the fingerprints of the input files.

Please remove the changes related to `optional` and input file validation from this PR or create a new one.

**Comment by SUPERCILEX** [comment]
@wolfs Ok, I think I've addressed your concerns. 👍

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/changes/RebuildIncrementalTaskInputs.java [hunk 1]
```diff
@@ -29,20 +32,37 @@
...
+            }
+
+            @Override
+            public void postVisitDirectory(PhysicalDirectorySnapshot snapshot) {
+                // No-op
+            }
+        };
+
+        for (CurrentFileCollectionFingerprint fingerprint : execution.getInputFingerprints().values()) {
+            fingerprint.visitRoots(visitor);
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/changedetection/changes/RebuildIncrementalTaskInputs.java]: Please use `fingerprint.getFingerprints()` for the stuff you want to pass to the `outOfDate` action, not the `visitRoots` method. This makes sure that the correct output filtering already happened. Then you also won't need to use a visitor.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/CalculatedTaskInputFileCollection.java [hunk 2]
```diff
@@ -60,7 +60,7 @@ public TaskDependency getBuildDependencies() {
     @Override
     public Set<File> getFiles() {
         if (!taskIsExecuting) {
-            throw new IllegalStateException("Can only query " + calculatedFiles.getDisplayName() + " while task " + taskPath + " is running");
+            return calculatedFiles.getFiles();
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/CalculatedTaskInputFileCollection.java]: These changes shouldn't be necessary any more.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultPropertySpecFactory.java [hunk 3]
```diff
@@ -33,14 +33,19 @@ public DefaultPropertySpecFactory(TaskInternal task, FileResolver resolver) {
     }
 
     @Override
-    public DeclaredTaskInputFileProperty createInputFileSpec(ValidatingValue paths, ValidationAction validationAction) {
-        return new DefaultTaskInputFilePropertySpec(task.getName(), resolver, paths, validationAction);
+    public DeclaredTaskInputFileProperty createInputFileSpec(ValidatingValue path, ValidationAction validator) {
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultPropertySpecFactory.java]: The changes to this file should be reverted as well.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputFilePropertySpec.java [hunk 4]
```diff
@@ -32,17 +32,17 @@
...
     private boolean optional;
     private Class<? extends FileNormalizer> normalizer = AbsolutePathInputNormalizer.class;
     private LifecycleAwareTaskProperty lifecycleAware;
 
-    public DefaultTaskInputFilePropertySpec(String taskName, FileResolver resolver, ValidatingValue paths, ValidationAction validationAction) {
-        this.value = paths;
+    public DefaultTaskInputFilePropertySpec(String taskName, FileResolver resolver, ValidatingValue path, ValidationAction validationAction) {
+        this.value = path;
         this.validationAction = validationAction;
-        this.files = new TaskPropertyFileCollection(taskName, "input", this, resolver, paths);
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputFilePropertySpec.java]: I guess this can be reverted, too.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java [hunk 5]
```diff
@@ -212,6 +212,8 @@ public void visitInputFileProperty(TaskInputFilePropertySpec fileProperty) {
 
     private static final ValidationAction RUNTIME_INPUT_FILE_VALIDATOR = wrapRuntimeApiValidator("file", ValidationActions.INPUT_FILE_VALIDATOR);
 
+    private static final ValidationAction RUNTIME_INPUT_FILES_VALIDATOR = wrapRuntimeApiValidator("files", ValidationActions.INPUT_FILES_VALIDATOR);
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java]: Let's remove that validator and revert all the corresponding changes.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/ValidationActions.java [hunk 6]
```diff
@@ -39,9 +40,15 @@ public void validate(String propertyName, Object value, TaskValidationContext co
             }
         }
     },
+    INPUT_FILES_VALIDATOR {
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/ValidationActions.java]: Let't not introduce a validator for input files.

File: subprojects/core/src/test/groovy/org/gradle/api/internal/file/CalculatedTaskInputFileCollectionTest.groovy [hunk 7]
```diff
@@ -22,22 +22,22 @@ import spock.lang.Specification
 
 
 class CalculatedTaskInputFileCollectionTest extends Specification {
-    def "cannot query value before task has started executing"() {
-        def calculated = Stub(MinimalFileSet)
+    def "querying value before task has started executing does not cache"() {
+        def calculated = Mock(MinimalFileSet)
```
Comment (wolfs) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/file/CalculatedTaskInputFileCollectionTest.groovy]: There should be no changes to this test.

File: subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy [hunk 8]
```diff
@@ -562,13 +562,14 @@ class AnnotationProcessingTaskFactoryTest extends AbstractProjectBuilderSpec {
         TaskWithOutputDir  | 'outputs' | 'missingDir'
     }
 
-    def "registers specified list of inputs on TaskWithInputFiles"() {
+    def "registers and processes specified list of inputs on TaskWithInputFiles"() {
```
Comment (wolfs) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy]: No changes to this test either.

File: subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy [hunk 9]
```diff
@@ -92,19 +92,20 @@ class DefaultTaskInputsTest extends Specification {
     }
 
     def "can register input files"() {
-        when: inputs.files("a", "b")
+        when:
+        inputs.files("a")
         then:
-        inputFiles() == [new File("a"), new File("b")]
```
Comment (wolfs) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy]: There shouldn't be any changes to this test, either.

File: subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy [hunk 10]
```diff
@@ -159,9 +159,12 @@ class ConfigureRuntimeClasspathNormalizationIntegrationTest extends AbstractInte
                 return """
                     task customTask {
                         def outputFile = file("\$temporaryDir/output.txt")
-                        inputs.files("classpath/dirEntry", "library.jar")
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy]: I don't think there is any change necessary here.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskInputFilePropertiesIntegrationTest.groovy [hunk 11]
```diff
@@ -95,7 +95,9 @@ class TaskInputFilePropertiesIntegrationTest extends AbstractIntegrationSpec {
 
             task foo {
                 outputs.file "foo.txt"
-                doFirst {}
+                doFirst {
+                    file("foo.txt").createNewFile()
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskInputFilePropertiesIntegrationTest.groovy]: Why this change?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileProvidersIntegrationTest.groovy [hunk 12]
```diff
@@ -615,7 +615,6 @@ class SomeTask extends DefaultTask {
         fails("consumer")
 
         then:
-        failure.assertHasDescription("Failed to capture fingerprint of input files for task ':consumer' property 'inputFiles' during up-to-date check.")
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileProvidersIntegrationTest.groovy]: That should still exhibit this failure.

**Comment by wolfs** [comment]
@SUPERCILEX Are you going to pick this up again?

**Comment by SUPERCILEX** [comment]
I'll get back to this tomorrow.

**Comment by SUPERCILEX** [comment]
@wolfs should be ready for another round of review!

**Comment by SUPERCILEX** [comment]
@marcphilipp mind triggering a build?

**Comment by marcphilipp** [comment]
Here you go: https://builds.gradle.org/viewQueued.html?itemId=15575932&tab=queuedBuildOverviewTab

**Comment by SUPERCILEX** [comment]
Shucks, looks like I forgot the samples. @marcphilipp could you trigger another one? Thanks!

**Comment by marcphilipp** [comment]
Now I feel like a human build trigger button... 😁

There you go: https://builds.gradle.org/viewQueued.html?itemId=15596026&tab=queuedBuildOverviewTab

**Comment by SUPERCILEX** [comment]
Sorry, can external contributors trigger a build? 😊

**Comment by marcphilipp** [comment]
I'm afraid not. No worries! 🙂

**Comment by SUPERCILEX** [comment]
@wolfs I think this might be good to go. The latest build failed with an execution timeout, but that's not related to my changes (and it says the tests passed).

File: subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/changes/DefaultTaskArtifactStateRepositoryTest.groovy [hunk 13]
```diff
@@ -716,29 +717,25 @@ class DefaultTaskArtifactStateRepositoryTest extends AbstractProjectBuilderSpec
         fileSystemMirror.beforeTaskOutputChanged()
     }
 
+    @EqualsAndHashCode
```
Comment (wolfs) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/changes/DefaultTaskArtifactStateRepositoryTest.groovy]: What advantage does the `EqualsAndHashCode` implementation give here? Are we using the class in a collection?

File: subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ResolveTaskArtifactStateTaskExecuterTest.groovy [hunk 14]
```diff
@@ -63,7 +63,7 @@ class ResolveTaskArtifactStateTaskExecuterTest extends Specification {
 
         then: 'taskContext is initialized with task artifact state'
         1 * taskContext.setTaskProperties(_)
-        1 * repository.getStateFor(task, _) >> taskArtifactState
+        1 * repository.getStateFor(task, _,) >> taskArtifactState
```
Comment (wolfs) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ResolveTaskArtifactStateTaskExecuterTest.groovy]: The comma should not be here.

File: subprojects/docs/src/samples/userguide/tasks/incrementalTask/groovy/build.gradle [hunk 15]
```diff
@@ -62,6 +62,8 @@ class IncrementalReverseTask extends DefaultTask {
 
         // tag::out-of-date-inputs[]
         inputs.outOfDate { change ->
+            if (change.file.directory) return
```
Comment (wolfs) [inline subprojects/docs/src/samples/userguide/tasks/incrementalTask/groovy/build.gradle]: Does that mean that no directories have been returned before?

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalTasksIntegrationTest.groovy [hunk 16]
```diff
@@ -373,6 +375,53 @@ ext.added = ['file3.txt', 'file4.txt']
...
+                    output.text = out.join('\\n')
+                }
+            }           
+            
+            task myTask(type: MyTask) {
+                input = file(inputDir)
+                child = new File(input, "child")
+                output = file("build/output.txt")
+            }          
+            myTask.input.mkdirs()
```
[the remark this answers is not in the document]
Comment (SUPERCILEX) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalTasksIntegrationTest.groovy]: Done

File: subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/changes/DefaultTaskArtifactStateRepositoryTest.groovy (hunk 13 above)
Comment (SUPERCILEX) [reply subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/changes/DefaultTaskArtifactStateRepositoryTest.groovy]: None, removed. `ToString` is the important one here.

File: subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ResolveTaskArtifactStateTaskExecuterTest.groovy (hunk 14 above)
Comment (SUPERCILEX) [reply subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ResolveTaskArtifactStateTaskExecuterTest.groovy]: Done

File: subprojects/docs/src/samples/userguide/tasks/incrementalTask/groovy/build.gradle (hunk 15 above)
Comment (SUPERCILEX) [reply subprojects/docs/src/samples/userguide/tasks/incrementalTask/groovy/build.gradle]: Yeah, though the old behavior was a bug since incremental inputs included directory changes. TBH, I'd like remove all directories from showing up in the inputs.

**Comment by wolfs** [comment]
@SUPERCILEX Thanks again for your time to fix this! Your changes have been merged via https://github.com/gradle/gradle/pull/6906 and will be in Gradle 5.0.
