### PR TITLE
Fix handling of excludes for missing task dependency detection

### LINKED ISSUE #16160: Wrong deprecation warning on using task outputs in another task with no explicit task dependency
When declaring a filtered fileTree as input for a task, gradle emits a deprecation warning about using output from another task even though this output is filtered out explicitly in the tasks inputs declaration.

### Steps to Reproduce
 
With the sample project attached run:

In the script we filter out the `build` folder explicitly from the inputs of myTask (which you can verify by checking the output of the `myTask`.

But running 

```
./gradlew clean compileJava myTask
``` 

still emits this deprecation warning:

```
> Task :myTask
Validation failed for task ':myTask', disabling optimizations:
  - Task ':myTask' uses the output of task ':compileJava', without declaring an explicit dependency (using Task.dependsOn() or Task.mustRunAfter()) or an implicit dependency (declaring task ':compileJava' as an input). This can lead to incorrect results being produced, depending on what order the tasks are executed.
Task ':myTask' uses the output of task ':compileJava', without declaring an explicit dependency (using Task.dependsOn() or Task.mustRunAfter()) or an implicit dependency (declaring task ':compileJava' as an input). This can lead to incorrect results being produced, depending on what order the tasks are executed. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. Execution optimizations are disabled due to the failed validation. See https://docs.gradle.org/7.0-milestone-1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
```

[overlappinginputs.zip](https://github.com/gradle/gradle/files/5983641/overlappinginputs.zip)

### Your Environment

- Running with Gradle 7.0-milestone-1

Build scan URL:
https://gradle.com/s/pz3rqikhptn5g

### PR DESCRIPTION
**Pull request by wolfs**
Excludes on part of sub-trees already exclude the whole subtree. For example `exclude 'foo'` also excludes `foo/some/subdir`. We need to take this into account for missing task dependency detection as well.

Fixes #16160

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java [hunk 1]
```diff
@@ -69,13 +69,30 @@ public void visitChildren(Iterable<NodeAccess> values, Supplier<String> relative
...
 
+    private boolean relativePathMatchesSpec(Spec<FileTreeElement> filter, File element, String relativePathString) {
+        boolean elementIsFile = element.isFile();
+        RelativePath relativePath = RelativePath.parse(elementIsFile, relativePathString);
+        if (!filter.isSatisfiedBy(new ReadOnlyFileTreeElement(element, relativePath, stat))) {
+            return false;
+        }
+        // All parent paths need to match the spec as well, since this is how we implement the file system walking for file tree.
+        File parentFile = element.getParentFile();
+        RelativePath parentRelativePath = relativePath.getParent();
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java:87]: I'd love to fix the nullability of `getParent()` (aka it can return null), though it seems like this can break Kotlin build scripts: https://github.com/gradle/gradle/pull/8975

Can we do something like changing the nullability for a major release?

Comment (melix) [reply subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java:87]: Maybe instead of changing the nullability we could introduce a new method and deprecate this one?

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy [hunk 2]
```diff
@@ -359,6 +359,47 @@ class MissingTaskDependenciesIntegrationTest extends AbstractIntegrationSpec imp
         executedAndNotSkipped(":assemble")
     }
 
+    @Issue("https://github.com/gradle/gradle/issues/16061")
+    def "excludes part of paths works with missing dependency detection"() {
```
Comment (melix) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy:363]: What about "missing dependency detection takes excludes into account"?

File: subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java [hunk 3]
```diff
@@ -69,13 +69,30 @@ public void visitChildren(Iterable<NodeAccess> values, Supplier<String> relative
...
+        for (; parentRelativePath != null && parentRelativePath != RelativePath.EMPTY_ROOT; parentRelativePath = parentRelativePath.getParent(), parentFile = parentFile.getParentFile()) {
```
Comment (melix) [inline subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java:88]: I find this relatively hard to read.

File: subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java [hunk 4]
```diff
@@ -203,7 +218,7 @@ public File getFile() {
 
         @Override
         public boolean isDirectory() {
-            return !isFile;
+            return file.isDirectory();
```
Comment (melix) [inline subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java:221]: Is this related to this bugfix? It looks like it's more a matter of correctness, e.g symlinks, which should be tested?

File: subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy [hunk 5]
```diff
@@ -172,6 +173,31 @@ class ExecutionNodeAccessHierarchyTest extends Specification {
         assertNodesAccessing("/other", root)
     }
 
+    def "can query for nodes accessing using excludes for parts of paths"() {
```
Comment (melix) [inline subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy:176]: the test name reads strange.
Suggestion: "can return nodes accessing some path taking includes and excludes into consideration"

File: subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy [hunk 6]
```diff
@@ -172,6 +173,31 @@ class ExecutionNodeAccessHierarchyTest extends Specification {
...
+        def excluding = Mock(Node)
+        def including = Mock(Node)
+        def includingWithChildren = Mock(Node)
+        def root = "/some/root/"
+
+        hierarchy.recordNodeAccessingFileTree(excluding, root, excludes("child"))
+        hierarchy.recordNodeAccessingFileTree(including, root, includes("child"))
+        hierarchy.recordNodeAccessingFileTree(includingWithChildren, root, includes("child/**"))
+        expect:
+        assertNodesAccessing(root, excluding, including, includingWithChildren)
```
Comment (melix) [inline subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy:196]: I think this test fixture would benefit from separating the root from the assertions, for readability. Not to be done in this PR. Something like:
```
assertNodesAccessing(root) {
    hasNodes(excluding, including, includingWithChildren)
}
```

**Review by melix — APPROVED** [review]

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy (hunk 2 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy]: Changed.

File: subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java (hunk 1 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java:86]: I talked to Paul about this. There is an `@UnderMigration` annotation which we may be able to use. Though that will require some changes in the Kotlin DSL, especially how we compile build scripts.

File: subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java (hunk 3 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java]: I changed this to a while loop. Is it easier to read now?

File: subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java (hunk 4 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java]: I am now using the same implementation as in `DefaultFileTreeElement`: `!relativePath.isFile()`. I don't think this matters much, though.

File: subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy (hunk 5 above)
Comment (wolfs) [reply subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy]: Changed.

File: subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy (hunk 6 above)
Comment (wolfs) [reply subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy:196]: 👍

File: subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java [hunk 7]
```diff
@@ -242,12 +259,12 @@ public String getName() {
...
         public String getPath() {
-            return relativePath;
+            return relativePath.getPathString();
         }
 
         @Override
         public RelativePath getRelativePath() {
-            return RelativePath.parse(isFile, relativePath);
+            return relativePath;
         }
```
Comment (lptr) [inline subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java:268]: These changes don't have a negative impact on performance?

Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java:268]: In what sense? Because we need to check more things? These changes don't have a negative impact on our performance tests, because I don't think we use filtered file trees as inputs anywhere.

They will make it more expensive to check whether there are missing task dependencies with filtered file trees, though only when the roots of filtered file tree inputs overlap with outputs in the first place. Though these changes are necessary to make the check correct.

Comment (lptr) [reply subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java:268]: We are now not creating a new object when you call `getRelativePath()` but we are creating an object when you call `getPath()`. This could have an impact, I was wondering if you saw one, or if there was a reason why there shouldn't be. It could be a positive one, or an "it depends"-kind of impact, too.

Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java:268]: If you use a pattern like `include/blah/**`, then this pattern will always use `getRelativePath()` for matching and not `getPath()`, so this should actually become faster. If you are using a custom matcher relying on `getPath()`, then it will become slower. I expect most folks to use a pattern, so this should become faster for most folks. Though we don't have any performance tests for this use-case, so all of this is just a guess.
