### PR TITLE
Prevent deep recursion in collection properties implementations

### LINKED ISSUE #30656: StackOverflowException when adding Provider<*> entries to ListProperty
### Current Behavior

When I add a lot of instances of Provider<*> to ListProvider I get StackOverflowException.

### Expected Behavior

Same behaviour as with regular Collections. adding a new entry should not grow the stacktrace.

### Context (optional)

_No response_

### Self-contained Reproducer Project

```
abstract class SampleTask: DefaultTask() {
    @get:Input
    val inputs: ListProperty<String> = project.objects.listProperty(String::class.java)

    @TaskAction
    fun action() {
        println(inputs.get().size)
    }
}

tasks.register("sample", SampleTask::class) {
    repeat(100_000) { number ->
        inputs.add(project.provider { "Input #$number" })
    }
}
```

I also got this problem in a build with 1000 KMP projects.

### Gradle version

8.10.1

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by mlopatkin**
When many items are added to `List`-, `Set-`, or `MapProperty`, it led to a deep tree-ish structure of `PlusCollector` being created, which was then traversed recursively when evaluating the property. With enough elements, this caused `StackOverfowError`. 

This PR replaces tree-like structure with a plain list that can be traversed with O(1) stack space.

Fixes #30656.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 1]
```diff
@@ -574,55 +644,40 @@ private ExecutionTimeValue<C> getFixedExecutionTimeValue(List<ExecutionTimeValue
...
+                }
 
-        public CollectingProvider(Class<C> type, List<ProviderInternal<? extends Iterable<? extends T>>> providers, Supplier<ImmutableCollection.Builder<T>> collectionFactory) {
-            this.type = type;
-            this.providers = providers;
-            this.collectionFactory = collectionFactory;
-        }
+                @Override
+                public boolean isKnown() {
+                    return producers.stream().allMatch(ValueProducer::isKnown);
```
Comment (6hundreds) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:656]: 🤔 `PlusProducer` was doing `left.isKnown() || right.isKnown();` Here we have `&&` effectively. Is it intended?

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, APT

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 2]
```diff
@@ -354,11 +360,6 @@ public NoValueSupplier(Value<? extends C> value) {
             this.value = value.asType();
         }
 
-        @Override
-        public CollectionSupplier<T, C> absentIgnoring() {
-            return Cast.uncheckedCast(emptySupplier());
```
Comment (mlopatkin) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:359]: :x: without this `append` to a cleared property doesn't work. A test that reproduces the issue:
```groovy
        property.set(null as Iterable)
        property.append("foo")

        expect:
        assertValueIs(["foo"])
```

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java (hunk 1 above)
Comment (6hundreds) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java]: Although no tests have caught that

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 3]
```diff
@@ -574,55 +689,40 @@ private ExecutionTimeValue<C> getFixedExecutionTimeValue(List<ExecutionTimeValue
...
-            ImmutableCollection.Builder<T> builder = collectionFactory.get();
-            SideEffectBuilder<? super C> sideEffectBuilder = SideEffect.builder();
-            for (ProviderInternal<? extends Iterable<? extends T>> provider : providers) {
-                Value<? extends Iterable<? extends T>> value = provider.calculateValue(consumer);
-                if (value.isMissing()) {
-                    return Value.missing();
+        protected String toStringNoReentrance() {
+            StringBuilder sb = new StringBuilder();
+            getCollectors().forEach(collector -> {
+                if (sb.length() > 0) {
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:720]: 🚀 Consider limiting the size of the produced string.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 4]
```diff
@@ -574,55 +689,40 @@ private ExecutionTimeValue<C> getFixedExecutionTimeValue(List<ExecutionTimeValue
...
+                }
 
-        @Nullable
-        @Override
-        public Class<C> getType() {
-            return type;
-        }
+                @Override
+                public void visitDependencies(TaskDependencyResolveContext context) {
+                    producers.forEach(c -> c.visitDependencies(context));
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:706]: 👍

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 5]
```diff
@@ -574,55 +689,40 @@ private ExecutionTimeValue<C> getFixedExecutionTimeValue(List<ExecutionTimeValue
...
-    }
-
-    /**
-     * A provider for a collection type whose elements are themselves providers.
-     */
-    private static class CollectingProvider<T, C extends Collection<? extends T>> extends AbstractMinimalProvider<C> {
-        private final Class<C> type;
-        private final List<ProviderInternal<? extends Iterable<? extends T>>> providers;
-        private final Supplier<ImmutableCollection.Builder<T>> collectionFactory;
+            List<ValueProducer> producers = getCollectors().stream().map(ValueSupplier::getProducer).collect(toList());
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:692]: ❓ Does it actually need to collect here? From a behavior perspective, collecting here definitely means the returned `ValueProducer` won't reflect newly added elements. That should be sufficient for now but I wonder if it might not be surprising in the future. From a memory consumption perspective it would probably be nicer if the operations below could be Stream-based.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java (hunk 3 above)
Comment (mlopatkin) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:704]: > 🚀 Consider limiting the size of the produced string.

I'd leave it out of this PR. It was working like that before, though hidden in the recursive calls.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java (hunk 5 above)
Comment (mlopatkin) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java]: > ❓ Does it actually need to collect here? From a behavior perspective, collecting here definitely means the returned `ValueProducer` won't reflect newly added elements. That should be sufficient for now but I wonder if it might not be surprising in the future. From a memory consumption perspective it would probably be nicer if the operations below could be Stream-based.

Makes sense, fixed.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 6]
```diff
@@ -477,58 +467,122 @@ public String toString() {
...
         @Override
         public Value<C> calculateValue(ValueConsumer consumer) {
             // TODO - don't make a copy when the collector already produces an immutable collection
             ImmutableCollection.Builder<T> builder = collectionFactory.get();
-            Value<Void> result = value.collectEntries(consumer, valueCollector, builder);
-            if (result.isMissing()) {
-                return result.asType();
+            Value<Void> compositeResult = Value.present();
+            for (Collector<T> collector : getCollectors()) {
+                if (compositeResult.isMissing() && !isAbsentIgnoring(collector)) {
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:536]: 🤔 It seems that keeping the `absent ignoring` behavior makes things harder to understand and less efficient at runtime for little to no benefit or am I missing something?

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java (hunk 3 above)
Comment (bamboo) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:704]: > I'd leave it out of this PR. 

Ok.

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by 6hundreds** [comment]
@bot-gradle test rfn

**Comment by 6hundreds** [comment]
@bamboo It seems RFN results contains only unrelated failures. Do we ready to move forward?

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 7]
```diff
@@ -477,58 +468,128 @@ public String toString() {
...
+            return Value.of(Cast.<C>uncheckedNonnullCast(builder.build())).withSideEffect(SideEffect.fixedFrom(compositeResult));
         }
 
         @Override
-        public CollectionSupplier<T, C> absentIgnoring() {
-            return ignoreAbsent ? this : new CollectingSupplier(value, true);
+        public CollectionSupplier<T, C> plus(Collector<T> addedCollector, boolean ignoreAbsent) {
+            Preconditions.checkState(collectors.size() == size, "Something has been appended to this collector already");
+            collectors.add(ignoreAbsentIfNeeded(addedCollector, ignoreAbsent));
+            return new CollectingSupplier<>(type, collectionFactory, valueCollector, collectors, size + 1);
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:576]: 🤔 This is really confusing, we're adding to the shared `collectors` and also returning a new *value*? Is the point of the value to simply keep track of the invariant in line 574?

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java (hunk 6 above)
Comment (bamboo) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:543]: FTR: I gave it a try in this PR: https://github.com/gradle/gradle/pull/31555

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java (hunk 7 above)
Comment (mlopatkin) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:576]: > 🤔 This is really confusing, we're adding to the shared `collectors` and also returning a new _value_? Is the point of the value to simply keep track of the invariant in line 574?

No, we need the collector to be immutable for shallow copying and, perhaps, convention to work. So this collector is a fixed-length prefix of a shared buffer. This is to avoid copying the array every time and still be able to iterate over it in forward direction efficiently.

Comment (bamboo) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:576]: Ah, I see. I think a more explicitly named factory method instead of the constructor would make the intent clearer here. Nice trick.

**Review by bamboo — APPROVED** [review]
We should definitely take some time to simplify the code after the feature has been merged. In no particular order I'd like us to:
* get rid of the "absence ignoring" code paths (started in https://github.com/gradle/gradle/pull/31555);
* make the `CollectingSupplier` optimization more intent revealing (perhaps encapsulating it with a persistent data structure interface);
* consider the unification of `AbstractCollectionProperty.CollectingSupplier` with `DefaultMapProperty.CollectingSupplier`;

**Review by 6hundreds — APPROVED** [review]

File: testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForIsolatedProjectsExtension.groovy [hunk 8]
```diff
@@ -22,25 +22,32 @@ import org.spockframework.runtime.model.FeatureInfo
...
+        visitAnnotation(annotation, feature)
     }
 
-    private void visitAnnotation(SpecElementInfo specElementInfo) {
+    private void visitAnnotation(ToBeFixedForIsolatedProjects annotation, SpecElementInfo specElementInfo) {
         if (GradleContextualExecuter.isNotIsolatedProjects()) {
             return
         }
 
+        if (annotation.skip() != DO_NOT_SKIP) {
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForIsolatedProjectsExtension.groovy:46]: @cobexer What we do for `ToBeFixedForConfigurationCache` ? Here should be the same I guess

[the remark this answers is not in the document]
Comment (mlopatkin) [reply testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForIsolatedProjectsExtension.groovy:46]: >Should a test marked with ToBeFixedForIsolatedProjects with skip = FLAKY ever run?

I agree with Sergey that we should have the consistent treatment for both `TBFfCC` and `TBFfIP`. I don't recall having anything special for the former, but I don't look into flaky quarantine that often.

However, given that we don't eagerly look into these flaky tests, I doubt we need a regular run to exercise them.
