### PR TITLE
Encode immutable managed value with no state as `null`

### LINKED ISSUE #24405: Gradle crashes when trying to serialize nested extension object on task
Some combination of `@Nested` objects with an unset property sent to a task as a Property and `@OutputDirectory` annotation causes gradle to fail ungracefully.

### Expected Behavior
Gradle doesn't crash when task is configured strangely? It should either not allow it, or fail gracefully?

### Current Behavior
Gradle daemon crashes with:
```
Cannot encode a null string.
```

### Context
I was trying to nest configuration and pass it to a task without copying over each individual item.

### Steps to Reproduce 
I was playing around with nested extension objects are described here: https://docs.gradle.org/current/userguide/implementing_gradle_plugins.html#modeling_dsl_like_apis

I assume I'm doing something I'm not *supposed* to by passing the nested extension object to a task, but crashing the daemon seems like unintended behavior.
```java
public abstract class SiteExtension {
    abstract public RegularFileProperty getOutputDir();
    @Nested
    abstract public CustomData getCustomData();
    public void customData(Action<? super CustomData> action) {
        action.execute(getCustomData());
    }
}

public interface CustomData {
    Property<String> getWebsiteUrl();
    Property<String> getVcsUrl();
}
```

```java
    public void apply(Project project) {
        var ext = project.getExtensions().create("site", SiteExtension.class);
        project.getTasks().register(
            "crashTask",
            CrashTask.class,
           // send a nested extension object over to the task (bad?)
            t -> t.getCustomData().set(ext.getCustomData()));
    }
```
This actually doesn't cause any issues *unless* you have a output annotation on some property in the task
```java
  @OutputDirectory
  @Optional
  abstract DirectoryProperty getOutputDir();
  
  @Input
  abstract Property<CustomData> getCustomData();
```

running this task while some data in `CustomData` is not set, causes a failure somewhere deep in gradle, which also then leaves the daemon in a wierd state (you need to run `./gradlew --stop`)
```groovy
site {
    customData {
        vcsUrl.set("goose");
    }
}
```
```
./gradlew crashTask
...
...
Cannot encode a null string.
```

The full example is here:
https://github.com/loosebazooka/gradle-crash

### Your Environment
linux

### PR DESCRIPTION
**Pull request by bamboo**
A.k.a. `NoValueProvider`.

Resolves #24405

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test rfn

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy [hunk 1]
```diff
@@ -1268,9 +1262,11 @@ class NestedInputIntegrationTest extends AbstractIntegrationSpec implements Dire
         """
 
         expect:
-        // TODO: Remove `requireIsolatedDaemons` once the issue is fixed
-        executer.requireIsolatedDaemons()
         succeeds "crashTask"
+        succeeds "crashTask"
+
+        and:
```
Comment (alllex) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy:1268]: 💭 I think now the `expect/and` pattern does not fit the test anymore. It could be better to change it to two `when/then` pairs.

Also, `succeeds` does not check whether the task was skipped or actually executed. Given that we add a `skipped` assertion here, it may be good to add a symmetrical on for `executed`.

```
        when:
        succeeds "crashTask"
        then:
        executedAndNotSkipped(":crashTask")

        when:
        succeeds "crashTask"
        then:
        skipped(":crashTask")
```

**Review by asodja — APPROVED** [review]
LGTM

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy (hunk 1 above)
Comment (bamboo) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy]: Makes sense, thanks, @alllex.
