### PR TITLE
Fix client OOM when buffering output during user input prompt

### LINKED ISSUE #37228: Client process can OOM when buffering output during user input prompt
### Current Behavior

When a build prompts for user input via `UserInputHandler` while parallel tasks produce significant log output, the client process (wrapper/launcher) crashes with `OutOfMemoryError`. The daemon detects the disconnection and cancels the build. The user sees only the prompt. Buffered output is never replayed.

Also reproducible with `--debug` logging, which increases event volume enough to exhaust the client heap even without parallel execution.

### Expected Behavior

The build completes successfully. Output produced while the prompt is displayed is buffered without exhausting memory and replayed in full after the user responds.

### Context (optional)

`AbstractUserInputRenderer` buffers all incoming `OutputEvent`s in an unbounded `ArrayList` while waiting for user input. With parallel execution, concurrent tasks can easily produce enough output to exceed the client's 64MB heap (e.g., 4 subprojects x 50,000 log lines = ~80MB of buffered events).

### Self-contained Reproducer Project

```groovy
// settings.gradle
include 'sub1', 'sub2', 'sub3', 'sub4'
```

```groovy
// build.gradle
def handler = services.get(org.gradle.api.internal.tasks.userinput.UserInputHandler)
tasks.register('askYesNo') {
    def result = handler.askUser { it.askYesNoQuestion("Continue?") }
    doLast {
        println("Answer: " + result.getOrElse("<no answer>"))
    }
}
```

```groovy
// sub1/build.gradle (same for sub2, sub3, sub4)
tasks.register('verboseTask') {
    doLast {
        50_000.times { i ->
            logger.lifecycle("[$project.name] Output line $i: ${'x' * 180}")
        }
    }
}
```

Run with:
```shell
./gradlew askYesNo verboseTask --parallel
```

The build crashes before the user can respond to the prompt.

### Gradle version

9.5 (and all prior versions; the buffering has been unbounded since `AbstractUserInputRenderer` was introduced)

### Build scan URL (optional)

N/A, the client crashes before the build completes.

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by eskatos**
* Fixes #37228

This PR adds disk overflow to the user input event buffer. Events are kept in memory up to a small threshold (~2,500 events, ~1MB), then spilled to a temporary file using Gradle's existing output events serialization. On resume, in-memory events are replayed first, then events are streamed back from disk one at a time. The overflow file is deleted after replay and registered with `deleteOnExit()` as a safety net.

Client-local timing signals are filtered during pause. `UpdateNowEvent`, `FlushOutputEvent`, and `EndOutputEvent` have no serializers and no value on replay. Skipping them is both necessary and correct.

`AbstractUserInputRenderer` implementations, part of the client output pipeline, are invoked serially behind `ThrottlingOutputEventListener`'s lock.

Because of test logging, `ForkedTestClasspathFactory` is touched to add access to `GradleUserHomeLookup` from `:wrapper-shared` to the testing infrastructure implementation.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

File: platforms/core-runtime/file-temp/src/main/java/org/gradle/api/internal/file/temp/TempFiles.java [hunk 1]
```diff
@@ -21,12 +21,20 @@
...
+import java.nio.file.attribute.PosixFilePermissions;
+import java.util.Set;
 
 /**
  * Security safe API's for creating temporary files.
  */
 public final class TempFiles {
 
+    private static final Set<PosixFilePermission> OWNER_ONLY_PERMISSIONS =
+        PosixFilePermissions.fromString("rw-------");
```
Comment (octylFractal) [inline platforms/core-runtime/file-temp/src/main/java/org/gradle/api/internal/file/temp/TempFiles.java]: 💭 Why use the string which is a bit hard to parse, instead of just `EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE)`?

File: platforms/core-runtime/file-temp/src/main/java/org/gradle/api/internal/file/temp/TempFiles.java [hunk 2]
```diff
@@ -47,6 +55,11 @@ static File createTempFile(@Nullable String prefix, @Nullable String suffix, Fil
         if(prefix.length() <= 3) {
             prefix = "tmp-" + prefix;
         }
-        return File.createTempFile(prefix, suffix, directory);
+        Path dir = directory.toPath();
+        if (Files.getFileStore(dir).supportsFileAttributeView("posix")) {
+            return Files.createTempFile(dir, prefix, suffix,
+                PosixFilePermissions.asFileAttribute(OWNER_ONLY_PERMISSIONS)).toFile();
```
Comment (octylFractal) [inline platforms/core-runtime/file-temp/src/main/java/org/gradle/api/internal/file/temp/TempFiles.java]: 💭 Caching the whole attribute could be worthwhile, if you're going to cache the permissions?

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java [hunk 3]
```diff
@@ -60,13 +90,51 @@ public void onOutput(OutputEvent event) {
...
+        try {
+            if (overflowEncoder == null) {
+                overflowFile = temporaryFileProvider.createTemporaryFile("user-input-overflow-", ".bin");
+                overflowFile.deleteOnExit();
+                overflowEncoder = new KryoBackedEncoder(Files.newOutputStream(overflowFile.toPath()));
+            }
+            outputEventSerializer.write(overflowEncoder, event);
+            overflowEventCount++;
+        } catch (Exception e) {
+            LOGGER.warn("Failed to write overflow event to disk, falling back to in-memory buffer", e);
```
Comment (octylFractal) [inline platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java:131]: ❓ Is this log safe? Isn't there a chance that this logs, causes more output, and comes back to write more events before `overflowFailed` is set? Highly unlikely, but possible.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java [hunk 4]
```diff
@@ -60,13 +90,51 @@ public void onOutput(OutputEvent event) {
...
+            eventQueue.add(event);
+            return;
+        }
+        try {
+            if (overflowEncoder == null) {
+                overflowFile = temporaryFileProvider.createTemporaryFile("user-input-overflow-", ".bin");
+                overflowFile.deleteOnExit();
+                overflowEncoder = new KryoBackedEncoder(Files.newOutputStream(overflowFile.toPath()));
+            }
+            outputEventSerializer.write(overflowEncoder, event);
```
Comment (octylFractal) [inline platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java:128]: ❓ Can we cap the size of the output file? Or at least check how full the disk is and cap it to some amount below that? I don't think we should leave the potential to fill up the disk if someone leaves a build running at some input point.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java [hunk 5]
```diff
@@ -102,6 +170,56 @@ private void replayEvents() {
             delegate.onOutput(iterator.next());
             iterator.remove();
         }
```
Comment (octylFractal) [inline platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java]: 💭 Not for now, but I noticed we're using `remove` on an `ArrayList` from the front, so this is going to repeatedly re-copy the items forwards. It would be better to either iterate over the whole thing, then clear it; or switch it to a proper queue implementation like `ArrayDeque`.

File: platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy [hunk 6]
```diff
@@ -161,6 +170,167 @@ class UserInputConsoleRendererTest extends Specification {
         renderer.eventQueue.empty
     }
 
+    def "overflows to disk and replays all events in order"() {
```
Comment (octylFractal) [inline platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy:173]: ❓ This doesn't look like it tests that it actually overflows to disk, right? If for some reason the `if` wasn't present, wouldn't this test still pass?

I would be satisfied with an assertion before the resume that there is a file in the `tmpDir`.

File: platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy [hunk 7]
```diff
@@ -161,6 +170,167 @@ class UserInputConsoleRendererTest extends Specification {
...
+        renderer.onOutput(new UserInputResumeEvent(123))
+
+        then:
+        1 * console.getBuildProgressArea() >> buildProgressArea
+        1 * console.buildOutputArea >> textArea
+        1 * console.getBuildProgressArea() >> buildProgressArea
+        tmpDir.listFiles().length == 0
+    }
+
+    def "handles multiple pause/resume cycles with overflow"() {
```
Comment (octylFractal) [inline platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy:240]: :x: Likewise, this test also isn't verifying that a file gets created at all. It just asserts there aren't any files afterwards, but that doesn't mean one was ever made.

File: platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy [hunk 8]
```diff
@@ -161,6 +170,167 @@ class UserInputConsoleRendererTest extends Specification {
...
+
+        then:
+        1 * console.getBuildProgressArea() >> buildProgressArea
+        1 * console.buildOutputArea >> textArea
+        1 * console.getBuildProgressArea() >> buildProgressArea
+        replayed.size() == totalEvents
+        tmpDir.listFiles().length == 0
+    }
+
+    def "disk failure recovery across pause/resume cycles"() {
```
Comment (octylFractal) [inline platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy:286]: ❌ This test also isn't verifying that a file gets created at all, or doesn't in the first cycle.

File: platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputStandardOutputRendererTest.groovy
Comment (octylFractal) [inline platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputStandardOutputRendererTest.groovy:1]: :x: Similar concerns as to `UserInputConsoleRendererTest`. Also, this is a lot of test case duplication it seems, is it possible to put them in a common (parent) test class?

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java (hunk 3 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java:131]: It should not be an issue if it happens because this is all running serially behind `ThrottlingOutputEventListener`'s lock. New logging events will get fed to the top of the `OutputEventListener`s pipeline and processed in due time.

File: platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy (hunk 6 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy:173]: Good point! I adjusted all the test cases to assert on the presence/absence of an overflow file. This uncovered a bug on intermittent i/o issues, fixed in the same commit.

File: platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputStandardOutputRendererTest.groovy
Comment (eskatos) [reply platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputStandardOutputRendererTest.groovy:1]: Just like many of the other test cases already duplicated between these two test classes, it is hard because of the mocks stubs and assertions. I did an attempt to extract a base class but it felt way less readable. If we ever have to touch the overflow behavior in the future, the failures in the tests will guide the required changes. I would prefer to keep things like they are.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java (hunk 4 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java:128]: This is a good question. I ruled out dropping events. I think we should simply fail the build in case the cap is hit. However, checking available space might be problematic. It varies over time and might be a slow operation, this could be especially problematic if we want to check regularly. With that in mind, a fixed cap comes to mind but then it is hard to pick a meaningful one.

File: platforms/core-runtime/file-temp/src/main/java/org/gradle/api/internal/file/temp/TempFiles.java (hunk 1 above)
Comment (eskatos) [reply platforms/core-runtime/file-temp/src/main/java/org/gradle/api/internal/file/temp/TempFiles.java]: Done

File: platforms/core-runtime/file-temp/src/main/java/org/gradle/api/internal/file/temp/TempFiles.java (hunk 2 above)
Comment (eskatos) [reply platforms/core-runtime/file-temp/src/main/java/org/gradle/api/internal/file/temp/TempFiles.java]: Done

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java (hunk 5 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java]: Done

File: platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy (hunk 8 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy:286]: Done

File: platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy (hunk 7 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputConsoleRendererTest.groovy:240]: Done

**Comment by eskatos** [comment]
Thank you for the review Octavia, PTAL

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java (hunk 4 above)
Comment (octylFractal) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java:128]: I think 1 or 5 GB is a decent choice, as a first value. A GB tends to be around when people start asking "what is taking up so much space", at least in my experience.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java (hunk 3 above)
Comment (octylFractal) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java:131]: OK, makes sense.

File: platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputStandardOutputRendererTest.groovy
Comment (octylFractal) [reply platforms/core-runtime/logging/src/test/groovy/org/gradle/internal/logging/console/UserInputStandardOutputRendererTest.groovy:1]: Alright.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java (hunk 4 above)
Comment (eskatos) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/console/AbstractUserInputRenderer.java:128]: Thanks. I went ahead and added a 1GB cap.

**Review by octylFractal — APPROVED** [review]
