### PR TITLE
Render problem solutions inline instead of in resolution section

### LINKED ISSUE #36380: Problem resolutions are dissociated from their description in the build failure message
### Current Behavior

The Problems API allows clients to fail the build by throwing an exception with the `ProblemReporter.throwing(..)` methods. 

The build failure message has a specific rendering: the first part renders the description, then separately, there's a dedicated resolution section (ie the `Try:` section) containing the proposed solutions. When the build failure has associated Problems the solutions property from the Problems are also rendered in the resolution section. 

The problem arises when there's more than one Problem associated with the build failure. The solutions are dissociated from the descriptions. See the example build failure message:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/donat/Development/git/gradle/problems-playground/build.gradle.kts' line: 346

* What went wrong:
java.lang.Exception: Boom failure
> Problem 1
    Context for Problem 1
      Details about Problem 1
  Problem 2
    Context for Problem 2
      Details about Problem 2

* Try:
> Solution A
> Solution B
> Run with --scan to generate a Build Scan (powered by Develocity).

BUILD FAILED in 401ms
```

Which solution belongs to Problem 1 and to Problem 2?

### Expected Behavior

There are multiple ways we can fix this problem. One option is simply to get rid of the separation of problems and solutions and render them as a single unit. That is reasonable, however we have to revisit the existing failure template and figure out what to do with the generic advice under the Try section. 

Alternatively, the failure message could i) number the rendered problems and use those as references in the Try  section, ii) inline the solutions into the problem rendering, or something else. The numbering-based approach seems more streamlined: it would not result in a different format in different scenarios (0, 1, or more problem occurrences associated with a build failure). Also numbers can be omitted when there’s exactly one associated problem occurrence, so most build failure messages would be kept unchanged.

### PR DESCRIPTION
**Pull request by donat**
Fixes #36380                                                                                             

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this

File: platforms/ide/problems-rendering/src/main/java/org/gradle/problems/internal/rendering/RenderOptions.java [hunk 1]
```diff
@@ -23,16 +23,13 @@ class RenderOptions {
 
     private final String prefix;
     private final boolean renderId;
-    private final boolean renderSolutions;
```
Comment (donat) [inline platforms/ide/problems-rendering/src/main/java/org/gradle/problems/internal/rendering/RenderOptions.java:26]: Removed as solutions are now rendered unconditionally.

**Comment by donat** [comment]
@bot-gradle test this

File: platforms/core-runtime/build-configuration/src/main/java/org/gradle/internal/buildconfiguration/DaemonJvmPropertiesConfigurator.java [hunk 2]
```diff
@@ -54,7 +54,7 @@ public class DaemonJvmPropertiesConfigurator implements ProjectConfigureAction {
     public void execute(ProjectInternal project) {
         // Only useful for the root project
         if (project.getParent() == null) {
-            ProblemReporter reporter = project.getServices().get(Problems.class).getReporter();
+            ProblemReporterInternal reporter = project.getServices().get(ProblemsInternal.class).getInternalReporter();
```
Comment (eskatos) [inline platforms/core-runtime/build-configuration/src/main/java/org/gradle/internal/buildconfiguration/DaemonJvmPropertiesConfigurator.java]: ❓ Why is the internal API required here?

File: platforms/ide/problems-api/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy [hunk 3]
```diff
@@ -477,9 +477,12 @@ class ProblemsServiceIntegrationTest extends AbstractIntegrationSpec {
...
     Complex build logic like the Problems API usage should be integrated into plugins
-    Solution: Look up the samples index for real-life examples
-    Documentation: https://example.com/some-problem
-    Location: /path/to/script
+
+    Possible solution: Look up the samples index for real-life examples.
+
+    For more information, please refer to https://example.com/some-problem.
+
+    Location: /path/to/script line 20
```
Comment (eskatos) [inline platforms/ide/problems-api/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy:481]: 💅  Why the blank lines?
💅  Why change how the documentation is displayed?

💅 What follows is not strictly about the current changes but triggered by them.

The documentation is about the problem, not the specific solution.
In the HTML report we put the documentation link on the problem label.
Also, in the HTML report we put the solution(s) last, below the location(s), and I think it makes sense.

Maybe it would be better if it looked like this:
```
Problem found: Project is a prototype (id: sample-problems:prototype-project)
  This is a prototype and not a guideline for modeling real-life projects
    Complex build logic like the Problems API usage should be integrated into plugins
    For more information, please refer to https://example.com/some-problem.
    Location: /path/to/script
    Possible solution: Look up the samples index for real-life examples
```

```
Problem found: Project is a prototype (id: sample-problems:prototype-project)
  This is a prototype and not a guideline for modeling real-life projects
    Complex build logic like the Problems API usage should be integrated into plugins
    For more information, please refer to https://example.com/some-problem.
    Location: /path/to/script
    Location: /path/to/another_script
    Possible solutions:
      1. Look up the samples index for real-life examples
      2. Do something else
```

WDYT?

Comment (donat) [reply platforms/ide/problems-api/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy:481]: I chose the formatting ad-hoc, basically to loosely match what we already have for version catalog/type validation. I actually like your proposal better (wo/the extra newlines). 

Re: documentation links. They have the same issue as the solutions: they are hoisted to the `Try: ` section and so it makes sense to inline them as well.

File: platforms/core-runtime/build-configuration/src/main/java/org/gradle/internal/buildconfiguration/DaemonJvmPropertiesConfigurator.java (hunk 2 above)
Comment (donat) [reply platforms/core-runtime/build-configuration/src/main/java/org/gradle/internal/buildconfiguration/DaemonJvmPropertiesConfigurator.java]: To be able to configure a `DocLink` reference to to Problem (see the removal of `getUrl()`) call.

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@eskatos your proposed update on the rendering is implemented. PTAL.

File: platforms/core-runtime/build-configuration/src/main/java/org/gradle/internal/buildconfiguration/DaemonJvmPropertiesConfigurator.java (hunk 2 above)
Comment (eskatos) [reply platforms/core-runtime/build-configuration/src/main/java/org/gradle/internal/buildconfiguration/DaemonJvmPropertiesConfigurator.java]: So, we can avoid the internals by just adding `.getUrl()`, correct?
If yes, I would avoid the internals. It's not worth it.

**Review by eskatos — APPROVED** [review]
Mostly LGTM!

There is just this topic about using internals just for avoiding the creation of URLs upfront.
If this is a real issue (e.g.  performance), then it looks like a signal that we need something in the API that takes a `Supplier<String>` for the documentation URL. But if there is no issue and that's just convenience, I think we should just remove the convenience from the internals. The more we use the public API internally the better.

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this
