### PR TITLE
Fix URI-quoted chars in cached outputs bug

### LINKED ISSUE #3043: Incorrect cache behavior when file name contains special characters
### Current Behavior

I've turned on caching for some tasks that generate dirnames with special characters, and it seems that the gradle cache is escaping the characters (perhaps using URL encoder?)

### Steps to Reproduce (for bugs)

Create the following files:

* `build.gradle`

    ```gradle
    task badCacheTask(type: Exec) {
      inputs.file('foo.sh')
      outputs.dir("output")
      outputs.cacheIf { true }
      commandLine = ['bash', 'foo.sh']
    }
    ```
* `foo.sh` (creates a bunch of files with special chars)
    ```shell
    bad_dir='output/dir/#/special$char'
    bad_file='f!ile .txt'
    mkdir -p "${bad_dir}"
    echo "foo" > "${bad_dir}/${bad_file}"
    ```
* run the following:
    ```shell
    gradle badCacheTask
    mv output good-cache
    gradle badCacheTask
    tree output good-cache
    ```
* The output of the above command looks like:
   ```plain
    output
    └── dir
        └── %23
            └── special$char
                └── f!ile%20.txt
    good-cache
    └── dir
        └── #
            └── special$char
                └── f!ile\ .txt
    ```

As can be seen in the output above. The actual state of the `output` dir after cache restoration is not the same as expected.

* The [cache file contents](https://scans.gradle.com/s/2eytczf3jj74q/timeline?task=63ipnljja4psg) from the cache key `5a1a4e7a01d4080c60ba674aac2cfd8a` are as follows:
    ```plain
    $ tar -ztvf ~/.gradle/caches/build-cache-1/5a1a4e7a01d4080c60ba674aac2cfd8a
    -rw-r--r-- 0/0             342 2017-09-27 21:35 METADATA
    drwxr-xr-x 0/0               0 2017-09-27 21:35 property-$1/
    drwxr-xr-x 0/0               0 2017-09-27 21:35 property-$1/dir//
    drwxr-xr-x 0/0               0 2017-09-27 21:35 property-$1/dir/%23//
    drwxr-xr-x 0/0               0 2017-09-27 21:35 property-$1/dir/%23/special$char//
    -rw-r--r-- 0/0               4 2017-09-27 21:35 property-$1/dir/%23/special$char/f!ile%20.txt
    ```

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/2eytczf3jj74q

### PR DESCRIPTION
**Pull request by lptr**
Fixes #3043

Since using `URI.relativize()` we don't seem to be handling task output file names with URI-quoted characters in them.

### CODE REVIEW

**Comment by lptr** [comment]
Branch build: https://builds.gradle.org/viewQueued.html?itemId=8415330

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy [hunk 1]
```diff
@@ -648,6 +649,36 @@ class CachedCustomTaskExecutionIntegrationTest extends AbstractIntegrationSpec i
...
+    @Issue("https://github.com/gradle/gradle/issues/3043")
+    def "URL-quoted characters in file names are handled properly"() {
+        def weirdOutputPath = 'build/bad&dir/bad! <Dezső> %20.txt'
+        def expectedOutput = file(weirdOutputPath)
+        buildFile << """
+            task weirdOutput {
+                outputs.dir("build")
+                outputs.cacheIf { true }
+                doLast {
+                    mkdir file('$weirdOutputPath').parentFile
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy]: Doesn't the directory now get created automatically? So we can just remove this line?

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy [hunk 2]
```diff
@@ -648,6 +649,36 @@ class CachedCustomTaskExecutionIntegrationTest extends AbstractIntegrationSpec i
...
+        then:
+        executedAndNotSkipped ":weirdOutput"
+        expectedOutput.file
+
+        when:
+        cleanBuildDir()
+        withBuildCache().succeeds "weirdOutput"
+        then:
+        skipped ":weirdOutput"
+        expectedOutput.parentFile.listFiles().each { println it }
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy]: I guess this is a leftover from debugging. Please remove it.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy (hunk 1 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy]: `build` gets created automatically, `build/bad&dir` does not.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy (hunk 2 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy]: Fixed

**Comment by lptr** [comment]
Build: https://builds.gradle.org/viewQueued.html?itemId=8423441

**Comment by lptr** [comment]
No I didn't merge this!
