### PR TITLE
Better error message for circular provider evaluation

### LINKED ISSUE #20932: Prevent or help to diagnose accidental recursion to itself in a property
Property allows to set itself as a value.

```kotlin
val myProperty = "..."

configure<Extension> {
    myProperty.set(myProperty)
}
```

```
java.lang.StackOverflowError
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:174)
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:178)
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:178)
        ...
```

https://github.com/eugene-krivobokov/gradle-reproducer-property-recursion

### Expected Behavior

- Fail-fast check which prevents to refer to itself
- Error message contains the name of the problematic property

### Current Behavior

Property allows to set itself and will fail while configuration.

### Context

The problem is it can be diagnosed only in debugger. It may take a lot of time to reproduce the configuration locally and find the reason. I'd like to avoid this at all.

### PR DESCRIPTION
**Pull request by mlopatkin**
Fixes #20932

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test APT

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 1]
```diff
@@ -486,4 +497,61 @@ public ValueProducer getProducer() {
             return left.getProducer().plus(right.getProducer());
         }
     }
+
+    protected CollectionSupplierGuard<T, C> guardSupplier(CollectionSupplier<T, C> supplier) {
+        return new CollectionSupplierGuard<>(this, supplier);
+    }
+
+    protected static final class CollectionSupplierGuard<T, C extends Collection<T>> implements CollectionSupplier<T, C>, GuardedData<CollectionSupplier<T, C>> {
```
Comment (abstratt) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:505]: `GuardedSupplier` would read better IMO (for this and `MapProperty`'s, which could use the same name).

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/GuardedData.java [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+ * @param <T> the underlying type of the data
+ */
+public interface GuardedData<T> {
+    /**
+     * Returns the owner of the data: the provider which is marked as evaluating while the data is accessed.
+     *
+     * @return the owner of the data or null if the evaluation scope must be explicitly opened to use this data
+     */
+    @Nullable
+    ProviderInternal<?> getOwner();
```
Comment (abstratt) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/GuardedData.java:46]: ❓ 

Do we need to tie cycle detection with providers? Aren't there other structures that are lazily evaluated and could benefit from this mechanism (say, if we did not want to adopt it now, only later)?

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/EvaluationContext.java [hunk 3]
```diff
@@ -0,0 +1,269 @@
...
+                throw prepareException(provider);
+            }
+        }
+
+        private void pop() {
+            ProviderInternal<?> removed = providersStack.remove(providersStack.size() - 1);
+            providersInScope.remove(removed);
+        }
+
+        public PerThreadContext enter(ProviderInternal<?> owner) {
```
Comment (abstratt) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/EvaluationContext.java:188]: Maybe `open` (to match `close()`), or make `AutoCloseable#close()` an on-liner that calls `leave()` or `exit()` (to match `enter()`).

💭

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/EvaluationContext.java [hunk 4]
```diff
@@ -0,0 +1,269 @@
...
+    public interface ScopedEvaluation<R, E extends Exception> {
+        R evaluate() throws E;
+    }
+
+    /**
+     * A scope context. One can obtain an instance by calling {@link #enter(ProviderInternal)}.
+     * Closing this context removes the provider from the evaluation context.
+     * The primary use case is to serve as an argument for the try-with-resources block.
+     * <p>
+     * It is not safe to call {@link #close()} multiple times.
```
Comment (abstratt) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/EvaluationContext.java:54]: Maybe move this to the `#close()` method javadoc?

💭

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 5]
```diff
@@ -486,4 +497,61 @@ public ValueProducer getProducer() {
...
+            }
+        }
+
+        @Override
+        public CollectionSupplierGuard<T, C> plus(Collector<T> collector) {
+            return new CollectionSupplierGuard<>(owner, supplier.plus(collector));
+        }
+
+        @Override
+        public ExecutionTimeValue<? extends C> calculateExecutionTimeValue() {
```
Comment (abstratt) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:537]: ❓ 

This is feedback that should have gone into the spec. Sorry if it is too late. I like the design and implementation of the subsystem for cycle detection, but hard to ignore the size of the design footprint required to prepare evaluation participants to be protected against cycles.  

Please forgive me if I am being overly naive (I often am), but did you consider a design with a smaller footprint, that did not involve decorators?

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java (hunk 1 above)
Comment (mlopatkin) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:505]: >GuardedSupplier would read better IMO (for this and MapProperty's, which could use the same name).

It is indeed, a supplier, but we're losing symmetry with the `ProviderGuard` (which isn't a provider, so this trick won't work there).

**Review by tresat — APPROVED** [review]
Software platform change looks good.

File: platforms/core-configuration/model-core/src/integTest/groovy/org/gradle/api/provider/CollectionPropertyIntegrationTest.groovy [hunk 6]
```diff
@@ -473,4 +473,26 @@ task wrongPropertyElementTypeApi {
...
+            def p = myCollection.map { it.join(", ") }
+            myCollection.add(p)
+
+            myCollection.get()
+
+            tasks.register("verify") {}
+        """
+
+        when:
+        fails "verify"
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/integTest/groovy/org/gradle/api/provider/CollectionPropertyIntegrationTest.groovy:488]: 🧪 I'd call `help` here instead of introducing a new task since the error happens during the configuration phase

File: platforms/core-configuration/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderIntegrationTest.groovy [hunk 7]
```diff
@@ -355,4 +355,30 @@ class ProviderIntegrationTest extends AbstractIntegrationSpec {
         'provider { "baz" }.zip(task.flatMap { it.outDir }) { f, d -> d.file(f) }' | _
         'provider { "baz" }.zip(task.get().outDir) { f, d -> d.file(f) }'          | _
     }
+
+    def "circular evaluation of provider is detected"() {
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderIntegrationTest.groovy:359]:
```suggestion
    def "circular evaluation of mapped provider is detected"() {
```

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 8]
```diff
@@ -486,4 +497,61 @@ public ValueProducer getProducer() {
             return left.getProducer().plus(right.getProducer());
         }
     }
+
+    protected CollectionSupplierGuard<T, C> guardSupplier(CollectionSupplier<T, C> supplier) {
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:501]: 💅 It could be just `guard` in this context.

File: subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ProviderImplementationTest.java [hunk 9]
```diff
@@ -0,0 +1,34 @@
...
+import org.gradle.api.provider.Provider;
+
+import static com.tngtech.archunit.core.domain.JavaClass.Predicates.implement;
+import static com.tngtech.archunit.lang.conditions.ArchConditions.beAssignableTo;
+import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
+
+@AnalyzeClasses(packages = "org.gradle")
+public class ProviderImplementationTest {
+    @ArchTest
+    public static final ArchRule provider_implementations_extend_abstract_minimal_provider = classes().that(implement(Provider.class))
```
Comment (bamboo) [inline subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ProviderImplementationTest.java:32]: 👍

File: platforms/core-configuration/model-core/src/testFixtures/groovy/org/gradle/api/internal/provider/PropertySpec.groovy [hunk 10]
```diff
@@ -1057,7 +1061,8 @@ The value of this provider is derived from:
 
         then:
         1 * function.call() >> {
-            property.get()
+            // Emulate concurrent get() in other thread
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/testFixtures/groovy/org/gradle/api/internal/provider/PropertySpec.groovy:1064]: ❓ Why is this change necessary?

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/EvaluationContext.java [hunk 11]
```diff
@@ -0,0 +1,276 @@
...
+
+        return newContext;
+    }
+
+    private ScopeContext nested() {
+        return setContext(new PerThreadContext(getContext()));
+    }
+
+    private final class PerThreadContext implements ScopeContext {
+        private final Set<EvaluationOwner> objectsInScope = new ReferenceOpenHashSet<>(EXPECTED_MAX_CONTEXT_SIZE);
```
Comment (bamboo) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/EvaluationContext.java:173]: 🚀 I have a gut feeling that persistent collections would work best for this use-case. I'll run an experiment on a separate branch to check that

Comment (mlopatkin) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/EvaluationContext.java:173]: > 🚀 I have a gut feeling that persistent collections would work best for this use-case. I'll run an experiment on a separate branch to check that

Could be. I used `ReferenceOpenHashSet` because it avoids allocations and GC overhead was noticeable in my earlier experiments.

Comment (bamboo) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/EvaluationContext.java:173]: Not really.

I was under the impression that some allocations could be saved but since the context objects are always needed and then reused, their cost is amortized.

FTR, according to the included jmh benchmark:
* replacing `ReferenceArrayList` with `PersistentList` gives about the same performance
* replacing `ReferenceOpenHashSet` with capsule's Immutable set makes it twice as slow

File: build-logic/jvm/src/main/kotlin/gradlebuild.strict-compile.gradle.kts [hunk 12]
```diff
@@ -18,7 +18,7 @@ import gradlebuild.jvm.extension.StrictCompileExtension
 
 extensions.create<StrictCompileExtension>("strictCompile")
 
-val strictCompilerArgs = listOf("-Werror", "-Xlint:all", "-Xlint:-options", "-Xlint:-serial", "-Xlint:-classfile")
+val strictCompilerArgs = listOf("-Werror", "-Xlint:all", "-Xlint:-options", "-Xlint:-serial", "-Xlint:-classfile", "-Xlint:-try")
```
Comment (abstratt) [inline build-logic/jvm/src/main/kotlin/gradlebuild.strict-compile.gradle.kts:21]: If you were curious like me, this avoids 

`warning: [try] auto-closeable resource ignore is never referenced in body of corresponding try statement`

in code like:


```
try (EvaluationContext.ScopeContext ignore = openScope()) {
           // no reference to "ignore" here
}       
```

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java (hunk 8 above)
Comment (abstratt) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java]: Done

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/BuildableBackedProvider.java [hunk 13]
```diff
@@ -45,12 +45,9 @@ public Class<T> getType() {
 
     @Override
     public ValueProducer getProducer() {
+        // not a lambda for readability purposes.
+        //noinspection Convert2Lambda
```
Comment (abstratt) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/BuildableBackedProvider.java:49]: TIL about IDEA's `//noinspection` comments, thanks. 

Not sure I agree this is more readable than the lambda version, but fine with me.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java [hunk 14]
```diff
@@ -51,12 +54,20 @@ public abstract class AbstractCollectionProperty<T, C extends Collection<T>> ext
...
-        return new EmptySupplier();
+    private CollectionSupplierGuard<T, C> emptySupplier() {
+        return guardSupplier(new EmptySupplier());
+    }
+
+    private CollectionSupplierGuard<T, C> noValueSupplier() {
+        return guardSupplier(Cast.uncheckedCast(NO_VALUE));
+    }
+
+    private void setSupplier(CollectionSupplier<T, C> unguardedSupplier) {
```
Comment (abstratt) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:65]: It seems this produces two levels of guards, for instance (or maybe specifically), when invoked from `addCollector()`. 

Should a helper method that only wraps a collection supplier into a `CollectionSupplierGuard` if the given collection supplier is not a `CollectionSupplierGuard` itself add any noticeable overhead?

Comment (abstratt) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java:65]: I take it back, please ignore me.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/ValueSupplier.java [hunk 15]
```diff
@@ -55,8 +55,6 @@ default boolean isKnown() {
             return true;
         }
 
-        boolean isProducesDifferentValueOverTime();
```
Comment (abstratt) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/ValueSupplier.java:58]: I guess this was unused

File: platforms/core-configuration/model-core/src/integTest/groovy/org/gradle/api/provider/CollectionPropertyIntegrationTest.groovy (hunk 6 above)
Comment (abstratt) [reply platforms/core-configuration/model-core/src/integTest/groovy/org/gradle/api/provider/CollectionPropertyIntegrationTest.groovy]: Turns out that task (if we moved the property evaluation somewhere below the task registration) fails to be registered with:

> Cannot add task 'verify' as a task with that name already exists.

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ProviderCodecs.kt [hunk 16]
```diff
@@ -447,3 +449,30 @@ class MapPropertyCodec(
...
     }
 }
+
+
+internal
+object GuardedDataCodec : Codec<GuardedData<*>> {
+    private
+    const val NO_OWNER = -1
+
+    override suspend fun WriteContext.encode(value: GuardedData<*>) {
```
Comment (bamboo) [inline platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ProviderCodecs.kt:459]: ❓ Are `GuardedData` instances ever shared? In other words, should the codec care about their identities?

Comment (bamboo) [reply platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ProviderCodecs.kt:459]: It seems that could be the case with the newly introduced _shallow copies_

Comment (abstratt) [reply platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ProviderCodecs.kt:459]: It seems we care for identities for properties and configurable file collections, but not for providers, right? Guarded data are more akin to providers (and wrap one), right?

Do you see any problems?

**Review by abstratt — APPROVED** [review]
Looks good to me!

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
@bot-gradle test APT

**Comment by abstratt** [comment]
@bot-gradle test APT

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
Made a mistake of choosing a baseline commit that would not compile correctly. Force pushed a proper commit reference.

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
@bot-gradle merge

**Comment by abstratt** [comment]
@bot-gradle merge

**Comment by abstratt** [comment]
Leaked file handles prevented merge...
