### PR TITLE
Fix circular dependencies when project have the same name

### LINKED ISSUE #847: Projects with same name lead to unintended conflict resolution
```
include 'a:foo'
include 'b:foo'
```

```
allprojects {
  apply plugin: 'java'
  group 'org.test'
}

project(':a:foo') {
  dependencies {
    compile project(':b:foo')
  }
}
```
### Expected Behavior
`:a:foo` depends on `:b:foo`. 

### Current Behavior

`:a:foo` depends on itself.

Changing the artifactId using the maven-publish plugin does not help. 

### Context
This effectively prevents users from using short names for projects like `api` or `jdk6`. This will become less of a problem once we support multi-variant projects, but currently it is a common idiom to have separate projects for these concerns.

### Steps to Reproduce (for bugs)
Run `gradle :a:foo:dependencies` to see the problem.

Build scan: https://scans.gradle.com/s/mtomjihobdkfe/dependencies

### PR DESCRIPTION
**Pull request by melix**
### Context

Before this commit, during dependency resolution, a synthetic
module version identifier was generated by project, using the
group and name of the project. However, it's possible for a
project in gradle to have the same name as another in the
same build, leading to duplicates. In this case the projects
were mixed together and lead to a circular dependency.

This commit fixes the problem by making sure we generate
distinct module version identifiers for such projects, by
using the full project path as the name instead of the short
name.

This also makes it possible to publish valid publications
when using the maven or ivy publish plugins. However, we detect
this problem early and warn the user that they should overwrite
the project identity in this case.

Fixes #847

### CODE REVIEW

File: subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationIdentity.java [hunk 1]
```diff
@@ -64,4 +76,69 @@ public String getRevision() {
...
+            if (!warned.getAndSet(true)) {
+                Project project = projectBackedModule.getProject();
+                List<Project> projectsWithSameId = projectBackedModule.getProjectsWithSameCoordinates();
+                if (!projectsWithSameId.isEmpty()) {
+                    StringBuilder sb = new StringBuilder();
+                    sb.append("Project ")
+                        .append(project.getPath())
+                        .append(" has the same (organisation, module name) as ")
+                        .append(projectsWithSameId.stream().map(Project::getPath).collect(Collectors.joining(" and ")))
+                        .append(". It has been assigned an automatic module name of ")
```
Comment (ljacomet) [inline subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationIdentity.java]: I wonder about the terminology: "automatic module name" has a very specific meaning in Java since 9.
Could we use the Maven terminology of `artifactId` or something else?

File: subprojects/maven/src/main/java/org/gradle/api/publish/maven/plugins/MavenPublishPlugin.java [hunk 2]
```diff
@@ -248,11 +258,60 @@ private void configureDefaultConfigurationsUsedWhenMappingToResolvedVersions(Ver
...
+            if (!warned.getAndSet(true)) {
+                Project project = projectBackedModule.getProject();
+                List<Project> projectsWithSameId = projectBackedModule.getProjectsWithSameCoordinates();
+                if (!projectsWithSameId.isEmpty()) {
+                    StringBuilder sb = new StringBuilder();
+                    sb.append("Project ")
+                        .append(project.getPath())
+                        .append(" has the same (groupId, artifactId) as ")
+                        .append(projectsWithSameId.stream().map(Project::getPath).collect(Collectors.joining(" and ")))
+                        .append(". It has been assigned an automatic artifact id of ")
```
Comment (ljacomet) [inline subprojects/maven/src/main/java/org/gradle/api/publish/maven/plugins/MavenPublishPlugin.java]: Since this is Maven, maybe use `artifactId` instead of two words.

File: subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationIdentity.java (hunk 1 above)
Comment (ljacomet) [reply subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationIdentity.java]: So `module` is Ivy terminology. So why not use something like:
> It has been assigned a synthetic Ivy module name of

Wdyt?

**Comment by melix** [comment]
> This change will end up renaming projects for dependency resolution even if there are no name conflicts in a given graph.

Why? The code explicitly renames _only_ if there's a name conflict in the graph.

**Comment by melix** [comment]
There's a huge impact on performance (which I kind of expected since everything has to be lazy) so don't merge until this is fixed.

File: subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationIdentity.java (hunk 1 above)
Comment (melix) [reply subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationIdentity.java]: nice idea, done

**Comment by melix** [comment]
@ljacomet WDYT now?
