### PR TITLE
Handle invalid memory values from MBean, test MBeanOsMemoryInfo better

### LINKED ISSUE #28348: Gradle does not start on z/OS
### Current Behavior

When attempting to perform any task on Gradle 8.8 on IBM z/OS with Java 8 or Java 11 the build fails immediately with the following error

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'temp'.
> Could not create task ':init'.
   > Could not create service of type MemoryManager using GlobalScopeServices.createMemoryManager().
      > free must be >= 0
```

The ultimate root cause of this is that `MBeanOsMemoryInfo` using the `"FreePhysicalMemorySize"` attribute from the `OperatingSystemMXBean` which is [documented to always return -1 on z/OS as it is not supported](https://eclipse.dev/openj9/docs/api/jdk11/jdk.management/com/ibm/lang/management/OperatingSystemMXBean.html).

I had originally planned to try to fix this by having the `OsMemoryStatus.getPhysicalMemory()` function return a `OsMemoryStatusAspect` instead of an `OsMemoryStatusAspect.Available` and have the physical memory be unavailable on z/OS (or more accurately whenever the `free` or `total` physical memory in `MBeanOsMemoryInfo.getOsSnapshot()` are ever negative. This turned out to have more knock on effects than I had hoped so I figured it was best to raise this defect before to get some expert opinion before committing more effort to this.

### Expected Behavior

The build should not immediately fail with an exception in `MemoryManager`.

### Context (optional)

We are trying to update the Gradle of version used by our z/OS build pipeline.

### Steps to Reproduce

1. Download Gradle to a z/OS machine
2. Export the environment the following environment variable to ensure that the inter-process between parent and child processes in Gradle work
   ```bash
   export OPENJ9_JAVA_OPTIONS="-Dconsole.encoding=ISO8859-1 -Dfile.encoding=ISO8859-1"
   ```
3. Convert the `gradle` script to EBCDIC so it can be run by `bash`:
   ```bash
   iconv -f ISO8859-1 -t IBM-1047 /path/to/gradle/bin/gradle gradle.zos
   chmod +x /path/to/gradle/bin/gradle.zos
   ```
4. Run the converted `gradle` script, piping the output through `iconv` so the output can be understood
   ```bash
   $ /path/to/gradle/bin/gradle.zos init |& iconv -f ISO8859-1 -t IBM-1047
   ```

### Gradle version

8.4 or above

### Gradle version that used to work

8.3

### Build scan URL (optional)

_No response_

### Your Environment (optional)

IBM z/OS 2.4
IBM Java 8

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #28348

### CODE REVIEW

File: platforms/core-runtime/process-services/src/test/groovy/org/gradle/process/internal/health/memory/MBeanOsMemoryInfoTest.groovy [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+        def osMemoryInfo = createMemoryInfo(MemoryAvailability.UNAVAILABLE)
+
+        when:
+        osMemoryInfo.getOsSnapshot().getPhysicalMemory().getTotal()
+
+        then:
+        thrown UnsupportedOperationException
+
+        where:
+        availability << [MemoryAvailability.UNAVAILABLE, MemoryAvailability.INVALID_VALUE]
```
Comment (ghale) [inline platforms/core-runtime/process-services/src/test/groovy/org/gradle/process/internal/health/memory/MBeanOsMemoryInfoTest.groovy:74]: I don't think `availability` is being used.  I think you probably intended to make the `given:` line above `createMemoryInfo(availability)` and remove the  next test because it would then also be covered.

**Review by ghale — CHANGES_REQUESTED** [review]
One issue with the test, but once we fix that, I think this is good to go.

**Comment by octylFractal** [comment]
@bot-gradle test this

**Review by ghale — APPROVED** [review]
