### PR TITLE
Generate opposite task option for BooleanOptionElements

### LINKED ISSUE #4311: Disable boolean `@Option`s from the command line
### Expected Behavior

Boolean-valued command line flags for tasks should allow the option to be disabled.

### Current Behavior

The `@Option(option=<name>)` annotation on a boolean field or method allows the value to be set to `true` by including `--<name>` on the command line.  Boolean-valued flags are explicitly not able to provide a value, eg: `--<name>=true` or `--<name>=false` fails with a message like:

```
FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :test from command line.
> Command-line option '--<name>' does not take an argument.
```

If the option is configurable from both the build file and the command line, it is not directly possible to enable a flag in the build file, but disable it per build from the command line.

### PR DESCRIPTION
**Pull request by FrauBoes**
* Fixes #4311 

### Context
The Gradle documentation states that options that enable behavior have an opposite option, which inverses their behaviour and is specified with `--no-`. These opposite options are currently only auto-generated for build options, for example `--daemon` / `--no-daemon`, see `BooleanBuildOptions`. This change adds the auto-generation of opposite *task* options.

### CODE REVIEW

**Comment by FrauBoes** [comment]
@bot-gradle test this

**Review by eskatos — APPROVED** [review]
Nice!

This should be explained in the user manual in https://docs.gradle.org/current/userguide/custom_tasks.html#sec:declaring_and_using_command_line_options

This is worthy of being present in release notes!

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOptionsSupplier.java [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+            }
+        }
+        return validBuiltInOptions;
+    }
+
+    /**
+     * Builds a map of generated opposite options and
+     * add pairs of mutually exclusive options to the {@link TaskOptions taskOptions}.
+     */
+    private static Map<String, OptionDescriptor> getOppositeOptions(Object target, Map<String, OptionDescriptor> options, TaskOptions taskOptions) {
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOptionsSupplier.java:82]: ❕ I think it's kind of unexpected behavior for a `getXYZ` method to modify an argument.  Could this be reworked to not need to do that? If not, I think it's worth calling out the modification to `taskOptions` in javadoc.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOptionsSupplier.java [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+                        mutuallyExclusiveOptions.add(Pair.of(option, oppositeOption));
+                    }
+                }
+            }
+        }
+        taskOptions.mutuallyExclusiveOptions = Collections.unmodifiableList(mutuallyExclusiveOptions);
+        return oppositeOptions;
+    }
+
+    public static TaskOptions get(Object target, OptionReader optionReader) {
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOptionsSupplier.java:106]: ❕ Public method with `Object` parameter should probably have doc describing what types are appropriate for that param.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOptionsSupplier.java [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+import java.util.Map;
+import java.util.stream.Collectors;
+import java.util.stream.Stream;
+
+/**
+ * This class is responsible for supplying the built-in options and
+ * the {@link BooleanOptionElement mutually exclusive options} of a task,
+ * based on the task options provided by the {@link OptionReader}.
+ */
+public class TaskOptionsSupplier {
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOptionsSupplier.java:47]: 💭 I'd consider renaming this type, as it has a `get` method and the name has a `Supplier` suffix, but it is completely unrelated to `java.util.function.Supplier`.

Maybe `TaskOptionsCreator`?  `TaskOptionsGenerator`?  With the `get` method also renamed to `create`/`generate`/`for`?

File: subprojects/core/src/main/java/org/gradle/execution/commandline/CommandLineTaskConfigurer.java [hunk 4]
```diff
@@ -57,16 +53,15 @@ private List<String> configureTasksNow(Collection<Task> tasks, List<String> argu
...
-            for (OptionDescriptor optionDescriptor : validCommandLineOptions) {
+            TaskOptions taskOptions = TaskOptionsSupplier.get(task, optionReader);
+            List<OptionDescriptor> commandLineOptions = taskOptions.getAll();
+            for (OptionDescriptor optionDescriptor : commandLineOptions) {
                 String optionName = optionDescriptor.getName();
                 org.gradle.cli.CommandLineOption option = parser.option(optionName);
                 option.hasDescription(optionDescriptor.getDescription());
                 option.hasArgument(optionDescriptor.getArgumentType());
             }
+            allowOneOfEach(parser, taskOptions.getMutuallyExclusive());
```
Comment (tresat) [inline subprojects/core/src/main/java/org/gradle/execution/commandline/CommandLineTaskConfigurer.java:64]: 💭 Instead of the `CommandLineTaskConfigurer` calling this method on `taskOptions` and then the `allowOneOfEach` method processing the options to add them to the `CommandLineParser`, could the `TaskOptions` class be given a `void addMutualExclusions(CommandLineParser parser)` and encapsulate this logic there?  This might make this `CommandLineTaskConfigurer` class slightly more cohesive.

**Review by tresat — APPROVED** [review]

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOptionsSupplier.java [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+        }
+        taskOptions.mutuallyExclusiveOptions = Collections.unmodifiableList(mutuallyExclusiveOptions);
+        return oppositeOptions;
+    }
+
+    public static TaskOptions get(Object target, OptionReader optionReader) {
+        TaskOptions taskOptions = new TaskOptions();
+        Map<String, OptionDescriptor> options = optionReader.getOptions(target);
+        options.putAll(getOppositeOptions(target, options, taskOptions));
+        List<OptionDescriptor> sortedOptions = CollectionUtils.sort(options.values());
```
[the remark this answers is not in the document]
Comment (FrauBoes) [reply subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOptionsSupplier.java:110]: Good idea, I created an [issue](https://github.com/gradle/gradle/issues/24704) for that.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOptionsSupplier.java (hunk 1 above)
Comment (FrauBoes) [reply subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOptionsSupplier.java:82]: Good point. I think it makes sense to keep the generation of these two option groups together as one is very much based on the other, but I spelt this out more clearly in the javadoc.

File: subprojects/core/src/main/java/org/gradle/execution/commandline/CommandLineTaskConfigurer.java (hunk 4 above)
Comment (FrauBoes) [reply subprojects/core/src/main/java/org/gradle/execution/commandline/CommandLineTaskConfigurer.java:64]: Thanks for the suggestion, changed it. This is now similar to `BuildOptions`, which call `parser.allowOneOf` in their `configure` method.

File: subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/options/OptionReaderTest.groovy [hunk 6]
```diff
@@ -83,95 +92,115 @@ class OptionReaderTest extends Specification {
...
         then:
-        options.size() == ownOptions + OptionReader.BUILT_IN_OPTIONS.size() - clashingOptions.size()
+        options.size() == ownOptions + builtInOptionCount - clashingOptions.size()
         options[0].name == "rerun"
         options[0].description == "custom clashing option"
         options[1].name == "unique"
         options[1].description == "custom unique option"
     }
 
+    def "task own options shadow generated opposite options"() {
```
[the remark this answers is not in the document]
Comment (FrauBoes) [reply subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/options/OptionReaderTest.groovy:139]: Added this test case to `TaskBooleanOptionIntegrationTest`

**Comment by FrauBoes** [comment]
@bot-gradle test BD

**Review by eskatos — APPROVED** [review]
\o/
