### PR TITLE
Clarify intent of providing a configuration as a dependency

### LINKED ISSUE #13977: Configurations containing a provided configuration are not resolved correctly
Adding a configuration to a configuration through a provider doesn't seem to behave correctly. I used the following script to reproduce:

```
val myConfiguration by configurations.creating

dependencies {
    implementation(kotlin("stdlib"))
    myConfiguration("javax.inject:javax.inject:1")
    if (isLazy) {
        implementation(provider { myConfiguration })
    } else {
        implementation(myConfiguration)
    }
}
```

Adding the configuration directly, the [build scan](https://scans.gradle.com/s/bmh7tqku6qrxq/dependencies?toggled=W1swXSxbMCwzXSxbMCwwXV0) shows that both dependencies are added to the compilation and runtime classpaths, as expected:

image

However, adding the configuration through a `provider` causes `myConfiguration` to be resolved (which is a somewhat unexpected behavioral change), but the [build scan](https://scans.gradle.com/s/2cpbyg7on7vgs/dependencies?toggled=W1swXSxbMCwwXSxbMCw0XSxbMCwzXV0) does not list the resolved dependencies in the compilation or runtime classpaths:

image

This is obviously inaccurate, since the compilation would've failed if the dependency was truly missing. What's worst, the dependency is also missing in the published runtime classpath:

```
diff  ~/.m2/repository/com/twitter/test/incomplete-configuration/0.1.0-direct/incomplete-configuration-0.1.0-direct.module ~/.m2/repository/com/twitter/test/incomplete-configuration/0.1.0-lazy/incomplete-configuration-0.1.0-lazy.module
```

image

I put up a [reproducer](https://github.com/cesar1000/incomplete-configuration) using the latest nightly (6.7-20200731220031).

### PR DESCRIPTION
**Pull request by melix**
The behavior of declaring a `Configuration` as a dependency using
the dependency handler DSL was confusing. Using a direct notation,
this is equivalent to calling `extendsFrom`: it doesn't effectively
_add_ a new dependency to the graph.

However, since we added a `Provider` taking dependency notation,
it was possible to supply a `Configuration` in the provider, in
which case it would be resolved and the _files_ would be added
as dependencies.

This behavior is not intended and certainly confusing. This commit
deprecates the DSL which allows declaring configurations as dependencies,
and makes the build fail if a `Configuration` is used in a `Provider`.

Future Gradle releases may include _different_ DSL methods to support:

- adding a _list_ of dependencies lazily (using a `ListProvider`)
- adding a _file collection_ lazily

Closes #13977

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test RFM

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyNotationIntegrationSpec.groovy [hunk 1]
```diff
@@ -263,4 +263,29 @@ task checkDeps
...
+            }
+
+            dependencies {
+              conf configurations.other
+            }
+
+        """
+
+        when:
+        executer.expectDocumentedDeprecationWarning("Adding a Configuration as a dependency is a confusing behavior which isn't recommended."
```
Comment (bmuskalla) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyNotationIntegrationSpec.groovy:283]: Maybe

```
Adding a Configuration as a dependency is not going to add the dependencies as-is to the target Configuration. This behaviour...
```

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java [hunk 2]
```diff
@@ -123,6 +125,11 @@ public Dependency create(Object dependencyNotation, @Nullable Closure configureC
     @SuppressWarnings("rawtypes")
     private Dependency doAdd(Configuration configuration, Object dependencyNotation, @Nullable Closure configureClosure) {
         if (dependencyNotation instanceof Configuration) {
+            DeprecationLogger.deprecateBehaviour("Adding a Configuration as a dependency is a confusing behavior which isn't recommended.")
+                .withAdvice("You should use Configuration#extendsFrom instead.")
+                .willBeRemovedInGradle8()
```
Comment (bmuskalla) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java:130]: I still think we can do this for 7.0 given this will be part of 6.7

File: subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy [hunk 3]
```diff
@@ -94,7 +94,8 @@ class KotlinPluginSmokeTest extends AbstractSmokeTest {
 
         if (kotlinPluginVersion == TestedVersions.kotlin.latest()
             && androidPluginVersion == TestedVersions.androidGradle.latest()) {
-            expectNoDeprecationWarnings(result)
+            // TODO: re-enable once the Kotlin plugin fixes how it extends configurations
```
Comment (bmuskalla) [inline subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy:97]: Instead of a TODO that is easy forget, how about we assert the current behavior so this breaks once we upgrade to a version that misses the deprecation warning (and gives us a chance to change the assert to what we want it to be)

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java (hunk 2 above)
Comment (melix) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java:130]: I think it's too late for removal in 7.0. A couple releases isn't enough for most users.

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by prenagha** [comment]
Posted [this on StackOverflow](https://stackoverflow.com/questions/69915023/share-configuration-dependencies-using-extendsfrom-with-control-over-order) today regarding using configuration as a dependency so I could control ordering. Pointers if there is some better way to do that using `extendsFrom` or otherwise would be appreciated
