### PR TITLE
Fix project dependency substitution in generated metadata files

### LINKED ISSUE #14039: "maven-publish" ignores substituted projects when generating POM
### Expected Behavior

If a project dependency is substituted via `resolutionStrategy.dependencySubstitution`, and publication's `versionMapping` is set to `fromResolutionResult`, generated POM and module.json should reference target project instead of `requested`.

### Current Behavior

Generated POM and module.json reference original (`requested`) project. At the same time, substituted external dependencies (for example, `"com.squareup.okhttp3:logging-interceptor:4.7.2"`) are referenced correctly.

### Context

I am developing a plugin for cross-building scala projects. It generates new projects in runtime. POM files for their artifacts are not correct.
Note, dependency substitution itself works properly. Project ":a" is in fact substituted with project ":b", but generated POM and and module.json do not reflect this change. Again, if I substitute an external dependency, like "com.squareup.okhttp3:logging-interceptor:4.7.2" with "...:4.8.0", POM will correctly reference version "4.8.0".

### Steps to Reproduce 

Minimal example in Github repository: https://github.com/birukoff/gradle_subst_bug
1) Create multi-module project with Java subprojects ":a", ":b", ":z".
2) In projects ":a" and ":b" apply "maven-publish" plugin and add publications:
```
publishing {
    publications {
        register("jar", MavenPublication::class.java) {
            from(components["java"])
        }
    }
}
```
3) In project ":z" add dependency on project ":a":
```
dependencies {
    implementation(project(":a"))
}
```
4) In project ":z" substitute project ":a" with project ":b":
```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(project(":a")).with(project(":b"))
    }
}
```
5) In project ":z" apply "maven-publish" plugin and add a publication:
```
publishing {
    publications {
        register("jar", MavenPublication::class.java) {
            from(components["java"])
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
        }
    }
}
```
6) Run tasks "./gradlew generatePomFileForJarPublication generateMetadataFileForJarPublication" and look at the output in `z/build/publications/jar`
7) Generated POM contains wrong reference to artifact of project ":a" instead of project ":b":
```
    <dependency>
      <groupId>org.example</groupId>
      <artifactId>a</artifactId> <--- WRONG! Should be "b".
      <version>1</version>
      <scope>runtime</scope>
    </dependency>
```

### Your Environment

Build scan URL: https://scans.gradle.com/s/oyoasbb47pm72
Happens in any environment, any Gradle version I tested.

### PR DESCRIPTION
**Pull request by melix**
This commit adds handling of project dependency substitutions to
other projects. Previously, if a project was substituted with
another project, then when publishing resolved versions, the
substituted project wouldn't be replaced with the target project
in the generated metadata files (pom.xml, ivy.xml and Gradle
Module Metadata). While this is certainly an edge case that
shouldn't be encouraged, this properly handles the bug.

Fixes #14039

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test RFM

**Comment by melix** [comment]
@bot-gradle test this

File: subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishResolvedVersionsJavaIntegTest.groovy [hunk 1]
```diff
@@ -600,6 +601,75 @@ class MavenPublishResolvedVersionsJavaIntegTest extends AbstractMavenPublishInte
         ]
     }
 
+    // This is a weird test case, because why would you have a substitution rule
+    // for a first level dependency? However it may be that you implicitly get a
+    // substitution rule (via a plugin for example) that you are not aware of.
+    // Ideally we should warn when such things happen (linting).
+    @Unroll
```
Comment (ljacomet) [inline subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishResolvedVersionsJavaIntegTest.groovy:608]: Looks like this is not needed

File: subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyPublishResolvedVersionsJavaIntegTest.groovy [hunk 2]
```diff
@@ -590,4 +591,68 @@ $append
         javaLibrary.assertApiDependencies("org:foo:1.1")
         javaLibrary.assertRuntimeDependencies("org:foo:1.0")
     }
+
+    // This is a weird test case, because why would you have a substitution rule
+    // for a first level dependency? However it may be that you implicitly get a
+    // substitution rule (via a plugin for example) that you are not aware of.
+    // Ideally we should warn when such things happen (linting).
+    @Unroll
```
Comment (ljacomet) [inline subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyPublishResolvedVersionsJavaIntegTest.groovy:599]: Not needed either

**Review by ljacomet — APPROVED** [review]
👍 

Two minor comments on the tests, see below

**Comment by melix** [comment]
@bot-gradle test this
