### PR TITLE
6hundreds/load included build properties

### LINKED ISSUE #19793: `ISE: GradleProperties has not been loaded yet` for included build when restoring from the configuration cache
### Expected Behavior
The build succeeds standalone and when included in another build.

### Current Behavior
The build succeeds standalone but fails when included in another build.

### Context
Any included builds that use kapt fail when restoring from the configuration cache. I believe this is a problem with Gradle rather than kapt because the included build runs fine on its own, but I'm happy to file on the Kotlin issue tracker if this is a kapt issue!

### Steps to Reproduce 
Clone https://github.com/PhilGlass/included-build-config-cache-repro and run:

```
./gradlew app:build --scan
./gradlew app:build --scan
```

Note that running the included build on its own (`./gradlew -p included-build build`) always works.

Curiously I get a different failure storing the configuration cache entry the first time I run the build if I omit the `--scan`, but after that it behaves the same. I think this one _is_ a problem with kapt - a read of `Task.project` at execution time - but I can't reproduce it with our real build, only the demo project.

### Your Environment
Gradle **7.4-rc-1**, but it also reproduces with **7.3.3**.

✅ Scan for the first build: https://scans.gradle.com/s/oqe62q4hhhp3y
❌ Scan for the second build (restoring from the configuration cache): https://scans.gradle.com/s/mwyarhfb3qoya

### PR DESCRIPTION
**Pull request by 6hundreds**
Fixes #19793

In order of restoring CC state we should load included builds Gradle properties. Historically loading  Gradle properties and setting System properties was tightly coupled, we wasn't able to load only Gradle properties without set System properties. But seems like we want to do it:

 - To support System properties of included builds as an inputs for CC, we are tracking them via `EnvironmentChangeTracker` in `DefaultGradlePropertiesLoader`. Later System properties restoring in `ConfigurationCacheState` as a `CCEnvironmentChangeTracker.loadFrom`. After load it's prohibited to use `EnvironmentChangeTracker` for further tracking. 

 - After System properties restored, we want to restore Gradle properties for included builds. At this moment we don't want set System properties for them again because it is leads to tracking it via `EnvironmentChangeTracker`, what is prohibited (see above). So we need an ability to conditionally exclude setting System properties from loading Gradle properties.
 
This PR decoupling `DefaultGradlePropertiesLoader` to few single-responsible services and allows `GradlePropertiesController` to orchestrate them in order to load Gradle properties.

Things WIP:
- [x] Test coverage for new API
- [x] BuildSrc support

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/initialization/properties/DefaultProjectPropertiesLoader.java [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+
+    private final StartParameterInternal startParameter;
+
+    public DefaultProjectPropertiesLoader(StartParameterInternal startParameter, Environment environment) {
+        this.environment = environment;
+        this.startParameter = startParameter;
+    }
+
+    @Override
+    public GradlePropertiesInternal loadProjectProperties() {
```
Comment (mlopatkin) [inline subprojects/core/src/main/java/org/gradle/initialization/properties/DefaultProjectPropertiesLoader.java:42]: We're populating the `overrideProperties` only, maybe we can return only these as a `Map` instead? Then, to simplify things further:
- Remove `getDefaultProperties` and `getOverrideProperties` from `GradlePropertiesInternal`
- add `updateDefaultProperties` to `GradlePropertiesInternal` and rename it to `MutableGradleProperties`. This also addresses `GradleProperties` already being in the `internal` package, so `GradlePropertiesInternal` is very internal.
- use the new method in `loadGradlePropertiesFrom`, but only expose the result as `GradleProperties`. 
I don't think we need a truly immutable implementation, though.

File: subprojects/core/src/main/java/org/gradle/initialization/properties/DefaultSystemPropertiesInstaller.java [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+        this.gradleInternal = gradleInternal;
+    }
+
+    @Override
+    public void setSystemPropertiesFrom(GradlePropertiesInternal gradleProperties) {
+        // TODO:configuration-cache What happens when a system property is set from a Gradle property and
+        //    that same system property is then used to set a Gradle property from an included build?
+        //    e.g., included-build/gradle.properties << systemProp.org.gradle.project.fromSystemProp=42
+        setSystemPropertiesFromGradleProperties(gradleProperties.getDefaultProperties());
+        setSystemPropertiesFromGradleProperties(gradleProperties.getOverrideProperties());
```
Comment (mlopatkin) [inline subprojects/core/src/main/java/org/gradle/initialization/properties/DefaultSystemPropertiesInstaller.java:52]: Can we just do `setSystemPropertiesFromGradleProperties(gradleProperties.mergeProperties(emptyMap()))` instead of these two calls? The last one wins anyway. I also vote for introducing `gradleProperties.getProperties` instead of the monstrosity above :) - this would be the third occurrence.

**Review by mlopatkin — CHANGES_REQUESTED** [review]
The result seems good to me overall. I have several comments, mostly nitpicks and suggestions to simplify things. What I strongly suggest to address is:
- Not breaking the Nexus-Publish plugin with interface renaming.
- Not exposing the mutable state from the `GradleProperties`, handling of these is already complex enough. It could be achieved with defensive copying in `GradlePropertiesInternal`, or by adding `MutableGradleProperties` interface and hiding map-exposing getters.

File: subprojects/core/src/main/java/org/gradle/initialization/GradlePropertiesLoader.java [hunk 3]
```diff
@@ -15,11 +15,11 @@
  */
 package org.gradle.initialization;
 
-import org.gradle.api.internal.properties.GradleProperties;
+import org.gradle.initialization.properties.GradlePropertiesInternal;
 
 import java.io.File;
 
-public interface IGradlePropertiesLoader {
```
[the remark this answers is not in the document]
Comment (bamboo) [reply subprojects/core/src/main/java/org/gradle/initialization/GradlePropertiesLoader.java:22]: Let's not deprecate nor change it at this time.

File: subprojects/core/src/main/java/org/gradle/initialization/properties/ProjectPropertiesLoader.java [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+ * limitations under the License.
+ */
+
+package org.gradle.initialization.properties;
+
+public interface ProjectPropertiesLoader {
+
+    String SYSTEM_PROJECT_PROPERTIES_PREFIX = "org.gradle.project.";
+
+    String ENV_PROJECT_PROPERTIES_PREFIX = "ORG_GRADLE_PROJECT_";
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/core/src/main/java/org/gradle/initialization/properties/ProjectPropertiesLoader.java:23]: Yes we do, I'll handle it within improving test coverage

**Comment by 6hundreds** [comment]
@bot-gradle test acc

**Comment by 6hundreds** [comment]
@bot-gradle test acc

File: subprojects/core/src/main/java/org/gradle/initialization/IGradlePropertiesLoader.java [hunk 5]
```diff
@@ -15,20 +15,16 @@
...
+import org.gradle.initialization.properties.MutableGradleProperties;
 
 import java.io.File;
 
 public interface IGradlePropertiesLoader {
 
-    String SYSTEM_PROJECT_PROPERTIES_PREFIX = "org.gradle.project.";
-
-    String ENV_PROJECT_PROPERTIES_PREFIX = "ORG_GRADLE_PROJECT_";
-
```
Comment (mlopatkin) [inline subprojects/core/src/main/java/org/gradle/initialization/IGradlePropertiesLoader.java:27]: I'd suggest to keep these properties and not the copy in `ProjectPropertiesLoader`, as these are actually used in third-party plugins.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt [hunk 6]
```diff
@@ -297,10 +299,21 @@ class ConfigurationCacheState(
...
         // Decode the build state using the contextualized IO service for the build
         return build.gradle.serviceOf<ConfigurationCacheIO>().readIncludedBuildStateFrom(stateFileFor((build.state as NestedBuildState).buildDefinition), build)
     }
 
+    private
+    fun GradleInternal.loadGradleProperties() {
+        val settingDir = serviceOf<BuildLayout>().settingsDir
+        // Load Gradle properties from file but skip applying system properties defined here.
+        // System properties from the file may be mutated by the build logic, and the execution-time values are already restored by the EnvironmentChangeTracker.
+        // Applying properties from file overwrite these modifications.
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt:313]:
```suggestion
        // Load Gradle properties from a file but skip applying system properties defined here.
        // System properties from the file may be mutated by the build logic, and the execution-time values are already restored by the EnvironmentChangeTracker.
        // Applying properties from file overwrites these modifications.
```

**Review by mlopatkin — CHANGES_REQUESTED** [review]
I insist on keeping the `IGradlePropertiesLoader`'s constants intact. Other than that, looks good to me.

**Comment by 6hundreds** [comment]
> I insist on keeping the `IGradlePropertiesLoader`'s constants intact. Other than that, looks good to me.

It's done

**Comment by 6hundreds** [comment]
@bot-gradle test and merge
