### PR TITLE
Full recompilation with annotation processor

### LINKED ISSUE #9871: Disable incremental Groovy compilation when Java annotation processors are present
We don't want to support incremental joint Java/Groovy compilation together with Java annotation processors. Let's deprecate using Java annotation processors together with incremental Groovy compilation and fail the build in Gradle 6.0 if you try doing this.

### PR DESCRIPTION
**Pull request by blindpirate**
### Context

This fixes #9871 

We don't want to support annotation processing with incremental Groovy compilation because there're too many complicated corner cases - we simply disable Groovy incremental compilation if any Java annotation processors detected.

### CODE REVIEW

File: subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/ApiGroovyCompiler.java [hunk 1]
```diff
@@ -74,7 +75,8 @@ public ApiGroovyCompiler(Compiler<JavaCompileSpec> javaCompiler) {
 
     private static abstract class IncrementalCompilationCustomizer extends CompilationCustomizer {
         static IncrementalCompilationCustomizer fromSpec(GroovyJavaJointCompileSpec spec) {
-            if (spec.getCompilationMappingFile() != null) {
+            if (spec.getCompilationMappingFile() != null && !annotationProcessingConfigured(spec)) {
+                DeprecationLogger.nagUserOfDeprecatedBehaviour("Annotation processing is not supported when incremental Groovy compilation is enabled.");
```
Comment (wolfs) [inline subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/ApiGroovyCompiler.java]: We can't do that in the `ApiGroovyCompiler`, we need to do it in `GroovyCompile`. This is running on the compiler daemon - I don't think we will see the deprecation message.

Comment (blindpirate) [reply subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/ApiGroovyCompiler.java]: PTAL!

File: subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/ApiGroovyCompiler.java [hunk 2]
```diff
@@ -284,12 +284,16 @@ public boolean apply(File file) {
         return WorkResults.didWork(true);
     }
 
-    private boolean shouldProcessAnnotations(GroovyJavaJointCompileSpec spec) {
-        return spec.getGroovyCompileOptions().isJavaAnnotationProcessing()
-            && !spec.getAnnotationProcessorPath().isEmpty()
+    public static boolean annotationProcessingConfigured(GroovyJavaJointCompileSpec spec) {
```
Comment (wolfs) [inline subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/ApiGroovyCompiler.java]: I wonder if this method should go to `GroovyJavaJointCompileSpec`.

File: subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java [hunk 3]
```diff
@@ -274,7 +275,10 @@ private boolean enableIncrementalCompilation(GroovyJavaJointCompileSpec spec) {
         if (getOptions().isIncremental() && spec.getSourceRoots().isEmpty()) {
             DeprecationLogger.nagUserOfDeprecatedBehaviour("Unable to infer source roots. Incremental Groovy compilation requires the source roots and has been disabled. Change the configuration of your sources or disable incremental Groovy compilation.");
         }
-        return getOptions().isIncremental() && !spec.getSourceRoots().isEmpty();
+        if (getOptions().isIncremental() && annotationProcessingConfigured(spec)) {
+            DeprecationLogger.nagUserOfDeprecatedBehaviour("Annotation processing is not supported when incremental Groovy compilation is enabled.");
```
Comment (wolfs) [inline subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java]: Should we make the deprecation warning more actionable? What we want to say is two things:
- We now disable incremental compilation since annotation processing is configured
- Having incremental compilation and annotation processing configured is deprecated and will be an error in Gradle 6.0

The options to fix this message are:
- Disable incremental compilation for GroovyCompile
- Remove the annotation processor configuration or use `-proc:none`

I wonder how much should go here and how much should go in the upgrade guide (`upgrading_version_5.adoc`).

Comment (wolfs) [reply subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java]: How about:
```
Incremental Groovy compilation has been disabled since Java annotation processors are configured.
Enabling incremental compilation and configuring Java annotation processors for Groovy compilation has been deprecated and will be removed in Gradle 6.0.
Disable incremental Groovy compilation or remove the Java annotation processor configuration.
```

So we need to use
```
DeprecationLogger.nagUserOfDeprecated("Incremental Groovy compilation has been disabled since Java annotation processors are configured. Enabling incremental compilation and configuring Java annotation processors for Groovy compilation",
"Disable incremental Groovy compilation or remove the Java annotation processor configuration.");
```

Comment (blindpirate) [reply subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java]: Done, PTAL!

File: subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy [hunk 4]
```diff
@@ -77,12 +77,47 @@ abstract class BasicGroovyCompilerIntegrationSpec extends MultiVersionIntegratio
         groovyClassFile('Groovy.class').exists()
         groovyGeneratedSourceFile('Groovy$$Generated.java').exists()
         groovyClassFile('Groovy$$Generated.class').exists()
+        outputDoesNotContain('Annotation processing is not supported when incremental Groovy compilation is enabled.')
```
Comment (wolfs) [inline subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy]: This check also needs updating. I think it can be removed, since the test fixture checks automatically that we are not getting a deprecation warning.

File: subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy [hunk 5]
```diff
@@ -77,12 +77,47 @@ abstract class BasicGroovyCompilerIntegrationSpec extends MultiVersionIntegratio
...
+        enableIncrementalCompilation()
+
+        then:
+        executer.expectDeprecationWarning()
+        succeeds("compileGroovy")
+        groovyClassFile('Groovy.class').exists()
+        groovyGeneratedSourceFile('Groovy$$Generated.java').exists()
+        groovyClassFile('Groovy$$Generated.class').exists()
+        outputContains(
+            ['Incremental Groovy compilation has been disabled since Java annotation processors are configured.',
```
Comment (wolfs) [inline subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy]: I think I would have concatenated the String via `+` instead of using a list and `join`.

File: subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java [hunk 6]
```diff
@@ -274,7 +274,11 @@ private boolean enableIncrementalCompilation(GroovyJavaJointCompileSpec spec) {
         if (getOptions().isIncremental() && spec.getSourceRoots().isEmpty()) {
             DeprecationLogger.nagUserOfDeprecatedBehaviour("Unable to infer source roots. Incremental Groovy compilation requires the source roots and has been disabled. Change the configuration of your sources or disable incremental Groovy compilation.");
         }
-        return getOptions().isIncremental() && !spec.getSourceRoots().isEmpty();
+        if (getOptions().isIncremental() && spec.annotationProcessingConfigured()) {
+            DeprecationLogger.nagUserOfDeprecated("Incremental Groovy compilation has been disabled since Java annotation processors are configured. Enabling incremental compilation and configuring Java annotation processors for Groovy compilation",
```
Comment (wolfs) [inline subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java]: I think the first argument should also be on a new line.

Comment (blindpirate) [reply subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java]: Done.

File: subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy (hunk 5 above)
Comment (blindpirate) [reply subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy]: Done.

**Comment by blindpirate** [comment]
Thanks @wolfs !
