### PR TITLE
Pass more information to top exception on build cache load/store failure

### LINKED ISSUE #17208: Confusing error message when build cache can't clean output directory
Every time the build cache fails to clean an output dir, users tell me that "the cache is broken". This is because the error message reads like this:

```
Failed to load cache entry for task ':compileKotlin'
> Build cache entry xxx from local build cache is invalid
  > Unable to delete directory
``` 
Note how it says that "loading from the cache" failed and that "the cache entry is invalid" and only in the root cause at the very bottom you get the real reason. People usually don't make it that far, especially if you run without `--stacktrace, in which case it just says 

```
Failed to load cache entry for task ':compileKotlin'
```
and they ask "Well why didn't it just run the task then?

### PR DESCRIPTION
**Pull request by asodja**
Now we pass more information to the top-level exception.

If previously exception was like:
```
Failed to load cache entry for task ':compileKotlin'
> Build cache entry xxx from local build cache is invalid
  > Unable to delete directory
```

Then top-level exception message looks like this now for load operation:
```
Failed to load cache entry xxx from local build cache for task ':compileKotlin': Unable to delete directory
```

Also, we don't say anymore: `Build cache entry xxx from local build cache is invalid` since this might be confusing. It is changed to: `Exception occurred while loading cache entry xxx from local build cache`

I also changed the error for store operation to have similarly more information on the top-level as load has.

Fixes #17208

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy [hunk 1]
```diff
@@ -127,7 +130,7 @@ class BuildCacheStepTest extends StepSpec<IncrementalChangesContext> implements
 
         then:
         def ex = thrown Exception
-        ex.message == "Failed to load cache entry for job ':test'"
+        ex.message == "Failed to load cache entry $cacheKeyHashCode from $cacheName for job ':test': unpack failure"
```
Comment (lptr) [inline subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy:133]: Instead of passing the `cacheName` as a parameter, it would be better to pass the whole expected message. That way we can actually verify what the user will see directly, which is less error-prone.

File: subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy [hunk 2]
```diff
@@ -461,6 +461,10 @@ tmpdir is currently ${System.getProperty("java.io.tmpdir")}""")
         failure.assertHasCause(cause)
     }
 
+    protected void failureHasCause(Matcher<? super String> matcher) {
+        failure.assertThatCause(matcher)
+    }
```
Comment (lptr) [inline subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy:466]: I understand that this is nice and general, but for readability I think accepting `Pattern` specifically here would lead to nicer code in the tests itself as you can use the `/regex/` syntax instead.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy [hunk 3]
```diff
@@ -218,7 +220,7 @@ class CacheTaskArchiveErrorIntegrationTest extends AbstractIntegrationSpec {
         when:
         fails "producesLink"
         then:
-        failureHasCause("Failed to store cache entry for task ':producesLink'")
+        failureHasCause(matchesRegexp("Failed to store cache entry [0-9a-z]+ for task ':producesLink': Could not pack tree 'outputDirectory'.*"))
```
Comment (lptr) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy:223]: I don't see a reason why we shouldn't test the whole message here or with the other three problems where we only check the prefix.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy [hunk 4]
```diff
@@ -57,7 +59,7 @@ class CacheTaskArchiveErrorIntegrationTest extends AbstractIntegrationSpec {
         then:
         fails "customTask"
 
-        failureHasCause("Failed to store cache entry for task ':customTask'")
+        failureHasCause(matchesRegexp("Failed to store cache entry [0-9a-z]+ for task ':customTask': Could not pack tree 'output'.*"))
```
Comment (lptr) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy:62]: That cache key regex looks weird to me. If we want to be strict, then it should be `[0-9a-f]+`. If we want to be lenient, `\w+` should suffice. If we want to go with the stricter variant, then extracting it to a constant might make sense, too.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java [hunk 5]
```diff
@@ -124,13 +125,25 @@ public Duration getDuration() {
...
-            });
+            .getOrMapFailure(loadFailure -> mapAndThrowFailure(work, cacheKey, loadFailure));
+    }
+
+    private AfterExecutionResult mapAndThrowFailure(UnitOfWork work, BuildCacheKey cacheKey, Throwable loadFailure) {
+        String cacheName = "build cache";
+        String loadFailureMessage = loadFailure.getMessage();
+        if (loadFailure instanceof BuildCacheLoadException) {
+            cacheName = ((BuildCacheLoadException) loadFailure).getCacheName();
+            loadFailureMessage = loadFailure.getCause().getMessage();
```
Comment (lptr) [inline subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java:136]: Why dp we make up a complicated message in `BuildCacheLoadException` if we do not use it?

What is wrong with always throwing a `RuntimeException` here with what information we add on this level (= work item, cache key) and letting `BuildCacheLoadException` carry the rest of the context (=which cache)?

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/DefaultBuildCacheController.java [hunk 6]
```diff
@@ -100,7 +99,7 @@ public boolean isEmitDebugLogging() {
             try {
                 local.load(command.getKey(), unpack);
             } catch (Exception e) {
-                throw new GradleException("Build cache entry " + command.getKey().getHashCode() + " from local build cache is invalid", e);
+                throw BuildCacheLoadException.forLocalCache(command.getKey().getHashCode(), e);
```
[the remark this answers is not in the document]
Comment (asodja) [reply subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/DefaultBuildCacheController.java]: Yes, this is intentional. Since the original message was that `build cache is invalid`, which might not be always true. For example in the given example from reporter directory could not be deleted, but we reported that `build cache is invalid`.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java [hunk 7]
```diff
@@ -124,13 +125,25 @@ public Duration getDuration() {
...
-                        work.getDisplayName()),
-                    loadFailure
-                );
-            });
+            .getOrMapFailure(loadFailure -> mapAndThrowFailure(work, cacheKey, loadFailure));
+    }
+
+    private AfterExecutionResult mapAndThrowFailure(UnitOfWork work, BuildCacheKey cacheKey, Throwable loadFailure) {
+        String cacheName = "build cache";
+        String loadFailureMessage = loadFailure.getMessage();
```
[the remark this answers is not in the document]
Comment (asodja) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java:129]: fixed

File: subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy (hunk 1 above)
Comment (asodja) [reply subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy:128]: I changed the `$cacheKeyHashCode` to literal. But `$cacheName` is part of `where:` block, so I can hardcode it.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java (hunk 5 above)
Comment (asodja) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java:132]: The message from `BuildCacheLoadException` is seen if you use `--stacktrace`.

The problem is, that if you don't use `--stacktrace` flag, you don't see enough info as reported in the isseue.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (asodja) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java:129]: actually removed

File: subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy (hunk 1 above)
Comment (asodja) [reply subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy:128]: Fixed after removing `BuildCacheLoadException`.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java (hunk 5 above)
Comment (asodja) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java:132]: I simplified this a bit and removed `BuildCacheLoadException`.

File: subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy (hunk 2 above)
Comment (asodja) [reply subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy:466]: Removed and used `Pattern`.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy (hunk 4 above)
Comment (asodja) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy:62]: Used stricter version and moved it to a constant.

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy (hunk 3 above)
Comment (asodja) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy]: done

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy [hunk 8]
```diff
@@ -117,7 +121,7 @@ class CacheTaskArchiveErrorIntegrationTest extends AbstractIntegrationSpec {
 
         then:
         fails("clean", "customTask")
-        failureHasCause("Failed to load cache entry for task ':customTask'")
+        failureHasCause(~/Failed to load cache entry $CACHE_KEY_PATTERN for task ':customTask': Remote build cache load exception: Not in GZIP format/)
```
Comment (lptr) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy:124]: Exception messages should describe what happened that caused the exception. "Remote build cache load exception" describes the type of exception instead. I think something like this would be better:

```suggestion
        failureHasCause(~/Failed to load cache entry $CACHE_KEY_PATTERN for task ':customTask': Could not load from remote cache: Not in GZIP format/)
```

Comment (asodja) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy]: fixed

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy [hunk 9]
```diff
@@ -217,7 +217,7 @@ class BuildCacheStepTest extends StepSpec<IncrementalChangesContext> implements
 
         then:
         def ex = thrown Exception
-        ex.message == "Failed to store cache entry $cacheKeyHashCode for job ':test': store failure"
+        ex.message == "Failed to store cache entry 30a042b90a for job ':test': store failure"
```
Comment (lptr) [inline subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy:220]: Is this intentional? Why not use the variable instead?

Comment (asodja) [reply subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy:220]: Yes, it is. This was not changed when fixing: https://github.com/gradle/gradle/pull/19672#discussion_r790634923

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by asodja** [comment]
@bot-gradle test and merge
