### PR TITLE
Codenarc uses worker api

### LINKED ISSUE #23534: Reintroduce worker api for CodeNarc
We [backed out the changes in 8.0 for codenarc to use the worker api](https://github.com/gradle/gradle/pull/23308) due to a reported regression.  We should fix the underlying issue and reintroduce this in 8.1

### PR DESCRIPTION
**Pull request by ghale**
Uses an IsolatedAntBuilder for all code-quality plugins.  Codenarc now uses the worker api, reimplementing the changes backed out by #23308. 

Fixes #23534

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

File: subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonServer.java [hunk 1]
```diff
@@ -141,6 +148,15 @@ public HashCode getClassLoaderHash(@Nonnull ClassLoader classLoader) {
         DomainObjectCollectionFactory createDomainObjectCollectionFactory(InstantiatorFactory instantiatorFactory, ServiceRegistry services) {
             return new DefaultDomainObjectCollectionFactory(instantiatorFactory, services, CollectionCallbackActionDecorator.NOOP, MutationGuards.identity());
         }
+
+        IsolatedAntBuilder createIsolatedAntBuilder() {
+            DefaultModuleRegistry moduleRegistry = new DefaultModuleRegistry(CurrentGradleInstallation.get());
+            return new DefaultIsolatedAntBuilder(
+                new DefaultClassPathRegistry(new DefaultClassPathProvider(moduleRegistry)),
+                new DefaultClassLoaderFactory(),
```
Comment (big-guy) [inline subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonServer.java:156]: Similarly for these. It looks like maybe these could move up to WorkerSharedUserHomeScopeServices or WorkerSharedGlobalScopeServices?

I'm OK with IsolatedAntBuilder only being available at the build/worker levels separately.

File: subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginToolchainsIntegrationTest.groovy [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+import org.gradle.internal.jvm.Jvm
+import org.gradle.quality.integtest.fixtures.CodeNarcCoverage
+import org.gradle.test.fixtures.file.TestFile
+
+/**
+ * Tests to ensure toolchains specified by the {@code CodeNarcPlugin} and
+ * {@code CodeNarc} tasks behave as expected.
+ */
+@TargetCoverage({ CodeNarcCoverage.getSupportedVersionsByJdk() })
+class CodeNarcPluginToolchainsIntegrationTest extends MultiVersionIntegrationSpec implements JavaToolchainFixture {
```
Comment (big-guy) [inline subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginToolchainsIntegrationTest.groovy:32]: Do we have a test that shows that we can analyze CodeNarc running with Groovy 4 while Gradle is using Groovy 3?

**Review by big-guy — CHANGES_REQUESTED** [review]
A few suggestions and questions.

Do you think it would be useful to add a soak test that would try to check for Ant or Groovy caused memory leaks in the worker?

I was thinking of something like:
- implement a AntWorkAction that intentionally allocates a lot of memory
- create a task that uses that work action
- create that task in 10 subprojects
- execute that task in all subprojects sequentially, so each subproject reuses the same worker

If something goes wrong, then the worker should OOM after a few subprojects.  We can't do this across builds because the worker will be discarded. 

I think we do something like this already in the worker integ tests, but since this worker action is a lot more complicated and we've seen leaks with Ant+Groovy before, it might make sense to explicitly check.

WDYT?

File: subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java [hunk 3]
```diff
@@ -229,4 +233,10 @@ protected void withBasePlugin(Action<Plugin> action) {
     protected JavaPluginExtension getJavaPluginExtension() {
         return project.getExtensions().getByType(JavaPluginExtension.class);
     }
+
+    public static void maybeAddOpensJvmArgs(JavaLauncher javaLauncher, ForkingWorkerSpec spec) {
+        if (JavaVersion.toVersion(javaLauncher.getMetadata().getJavaRuntimeVersion()).isJava9Compatible()) {
+            spec.getForkOptions().jvmArgs("--add-opens", OPEN_MODULES_ARG);
```
[the remark this answers is not in the document]
Comment (ghale) [reply subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java:239]: Because down in the guts of one of the classes `IsolatedAntBuilder` uses, it does [this](https://github.com/gradle/gradle/blob/9a2009ab1cb9ffb347a47c4a9cea16de559a7d82/subprojects/core/src/main/java/org/gradle/api/internal/classloading/PreferenceCleaningGroovySystemLoader.java#L34) which throws a [module access error](https://ge.gradle.org/s/fompyhqajkxpq/tests/:code-quality:embeddedIntegTest/org.gradle.api.plugins.quality.checkstyle.CheckstylePluginVersionIntegrationTest/analyze%20good%20code%207.0?focused-exception-line=0-1-2-3-4-5-6-7-8-0&top-execution=1).

File: subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginToolchainsIntegrationTest.groovy (hunk 2 above)
Comment (ghale) [reply subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginToolchainsIntegrationTest.groovy:32]: Yeah, we added this (`CodeNarcGroovyVersionIntegrationTest`) when we backed out the change previously.  I've updated the test so that we test against both Groovy3 and Groovy4 (so that when we update to Gradle using Groovy4, we'll then be testing with codenarc using Groovy3).

File: subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonServer.java [hunk 4]
```diff
@@ -141,6 +148,15 @@ public HashCode getClassLoaderHash(@Nonnull ClassLoader classLoader) {
         DomainObjectCollectionFactory createDomainObjectCollectionFactory(InstantiatorFactory instantiatorFactory, ServiceRegistry services) {
             return new DefaultDomainObjectCollectionFactory(instantiatorFactory, services, CollectionCallbackActionDecorator.NOOP, MutationGuards.identity());
         }
+
+        IsolatedAntBuilder createIsolatedAntBuilder() {
+            DefaultModuleRegistry moduleRegistry = new DefaultModuleRegistry(CurrentGradleInstallation.get());
```
[the remark this answers is not in the document]
Comment (ghale) [reply subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonServer.java]: Done

File: subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonServer.java (hunk 1 above)
Comment (ghale) [reply subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonServer.java]: I've pulled up everything it makes sense to pull up.  The only thing I didn't pull up is `ClassPathRegistry` as this gets created with additional stuff in `GlobalScopeServices`.  We _could_ just use the same registry in the worker services (with more stuff) but then that would pull some additional services (i.e. `PluginModuleRegistry`) into worker services, which it doesn't need.  Felt better to not pull unnecessary stuff into the worker, so `ClassPathRegistry` is created differently in both places.  I don't feel strongly about this, though.

File: subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcPlugin.java [hunk 5]
```diff
@@ -57,6 +62,11 @@ protected Class<CodeNarc> getTaskType() {
         return CodeNarc.class;
     }
 
+    @Inject
+    protected JavaToolchainService getToolchainService() {
```
[the remark this answers is not in the document]
Comment (ghale) [reply subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcPlugin.java]: Done.

File: subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarc.java [hunk 6]
```diff
@@ -97,13 +118,49 @@ protected ObjectFactory getObjectFactory() {
     }
 
     @Inject
-    public IsolatedAntBuilder getAntBuilder() {
+    protected JavaToolchainService getToolchainService() {
```
[the remark this answers is not in the document]
Comment (ghale) [reply subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarc.java]: Good point.  Done.

**Comment by ghale** [comment]
With respect to testing for memory leaks, we already had a test for this (`IsolatedAntBuilderMemoryLeakIntegrationTest`) but it was testing multiple builds.  I cannibalized this and made it use a multiproject build with 20 projects and max-workers=1.  I believe this should be good enough to catch an issue with a worker.

**Comment by ghale** [comment]
@bot-gradle test this

File: subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcGroovyVersionIntegrationTest.groovy [hunk 7]
```diff
@@ -24,49 +24,65 @@ import org.gradle.util.internal.VersionNumber
...
 
             dependencies {
-                implementation(platform("org.apache.groovy:groovy-bom:${latestGroovy4Version}"))
-                implementation("org.apache.groovy:groovy")
+                implementation(platform("${group}:groovy-bom:${groovyVersion}"))
+                implementation("${group}:groovy")
 
-                codenarc("org.codenarc:CodeNarc:${STABLE_VERSION_WITH_GROOVY4_SUPPORT}")
-                codenarc(platform("org.apache.groovy:groovy-bom:${latestGroovy4Version}"))
+                codenarc("org.codenarc:CodeNarc:${codenarcVersion}")
```
Comment (big-guy) [inline subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcGroovyVersionIntegrationTest.groovy:43]: I think we could change this to setting the version as a tool version? e.g.

`codenarc.toolVersion = "${codenarcVersion}"`

Do we need to align the Groovy versions between CodeNarc and the project for CodeNarc to work? If not, we probably don't need to add the dependency to the groovy-bom in codenarc.

**Review by big-guy — CHANGES_REQUESTED** [review]
Very close, just one comment about public API and if we can make the test a little more idiomatic

File: subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcPlugin.java [hunk 8]
```diff
@@ -43,8 +48,8 @@
 public abstract class CodeNarcPlugin extends AbstractCodeQualityPlugin<CodeNarc> {
 
     public static final String DEFAULT_CODENARC_VERSION = appropriateCodeNarcVersion();
-    private static final String STABLE_VERSION = "3.1.0";
-    private static final String STABLE_VERSION_WITH_GROOVY4_SUPPORT = "3.1.0-groovy-4.0";
+    public static final String STABLE_VERSION = "3.1.0";
+    public static final String STABLE_VERSION_WITH_GROOVY4_SUPPORT = "3.1.0-groovy-4.0";
```
[the remark this answers is not in the document]
Comment (ghale) [reply subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcPlugin.java]: Done.

File: subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcGroovyVersionIntegrationTest.groovy (hunk 7 above)
Comment (ghale) [reply subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcGroovyVersionIntegrationTest.groovy]: I think I copied that from the original defect report, but you're correct, it's not necessary.  I've removed the bom dependency and used the tool version instead.

**Comment by ghale** [comment]
@bot-gradle test and merge
