### PR TITLE
Overhaul incremental compiler

### LINKED ISSUE #4951: Incremental class analysis should be added to the build cache
I'm not sure this is an actual issue, maybe it's more of a question.

I'm testing out the build cache on a Java multi module project. I've noticed that it seems pointless to use the cache for the top-level components in our build because they always need to be fully re-compiled every time a first time change is made after something was retrieved from the cache.

I test like follows:
1. I stop gradle daemon
2. I wipe ~/.gradle
3. I checkout our project to ~/build_area_A and execute ```gradle assemble```
4. I checkout our project to ~/build_area_B and execute ```gradle assemble``` this is much faster than step 3 because all build outputs arrive from the cache.
5. I change a file in ~/build_area_B and execute ```gradle assemble``` again. Now if I changed the wrong file the build time will be as long as in step 3 because gradle states: ```:module:compileJava - is not incremental. No class analysis data available from the previous build.``` for the module changed and all modules depending on it.

I guess I don't get why the class analysis isn't brought in from the cache aswell. It seems to defeat the purpose a bit?

### LINKED ISSUE #9052: Remove custom change detection code from incremental Java compile
With https://github.com/gradle/gradle/pull/8499, the custom alignment code for incremental Java compilation should not be necessary any more and the normal incremental information can be used.

Maybe we should dogfood after we also support better incremental task inputs.

### LINKED ISSUE #9790: Use InputChanges for classpath changes in incremental Groovy compilation
Instead of using the alignment code the Java plugin uses, incremental Groovy compilation should be able to query for classpath changes directly.

Here are classpath changes are processed currently: https://github.com/gradle/gradle/blob/c8eeea38d4250a18e58354254f63aa5a1c03359e/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java#L58-L91

What needs to be done there is to create classpath entry snapshots for `jar`s as we do now. We probably also need to do the class analysis for the individual class files. I think that the changes reported for the individual class files should be enough to update the class analysis, so we probably don't need to analyse all the file in a directory on the classpath again.

When we manage to do the changes here, we can probably solve #9052 in a similar way.

### LINKED ISSUE #13499: Java incremental compilation api/impl usages separation does not work between modules
As I understand, https://github.com/gradle/gradle/pull/10419 was intended to break chains of incremental compilation early by stopping at "private" usages of affected types.

E.g. If `B` privately uses `A` and `C` uses `B`, then a change in `A` should not cause a recompilation of `C`.
```
public class A {
      // uncomment incremental change below
      // public int bar() { return 0; }
}

public class B {
     private A a = null; 
}

public class C {
    B getB() {
           return new B();
     }
}
```
In the example the separation works as intended only when `A`, `B` and `C` are in the same source set. If `C` is in a different subproject, then `C` is recompiled on an ABI change of `A`, which is suboptimal.
In case of the Kotlin project (https://github.com/JetBrains/kotlin) that often results in an effectively non-incremental (i.e. incremental compilation, which recompiles almost everything) recompilation of Java. It might be even slower, than the clean compilation, because of the dependency analysis.

I suspect, that the difference between inter- and intra-source-set IC is a bug.
Also it seems to me, that the problem comes from two places.
First is `ClasspathChangeDependentsFinder.collectDependentsFromClasspath` https://github.com/gradle/gradle/blob/bea6b1cbb4d2507ca3885f825d363ecc55a54124/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/ClasspathChangeDependentsFinder.java#L98
```
    private DependentsSet collectDependentsFromClasspath(Set<String> modified) {
        final Set<String> privateDependentClasses = Sets.newHashSet(modified);
        final Set<String> accessibleDependentClasses = Sets.newHashSet(modified);
        final Deque<String> queue = Lists.newLinkedList(modified);
        while (!queue.isEmpty()) {
            final String dependentClass = queue.poll();
            for (File entry : classpathSnapshot.getEntries()) {
                DependentsSet dependents = collectDependentsFromClasspathEntry(dependentClass, entry);
                if (dependents.isDependencyToAll()) {
                    return dependents;
                } else {
                    for (String intermediate : dependents.getPrivateDependentClasses()) {
                        if (privateDependentClasses.add(intermediate) && !accessibleDependentClasses.contains(intermediate)) {
                            queue.add(intermediate);
                        }
                    }
                    for (String intermediate : dependents.getAccessibleDependentClasses()) {
                        if (accessibleDependentClasses.add(intermediate) && !privateDependentClasses.contains(intermediate)) {
                            queue.add(intermediate);
                        }
                    }
                }
            }
        }
        return DependentsSet.dependentClasses(privateDependentClasses, accessibleDependentClasses);
    }
```
Here private usages are added to the `queue`, so they will be processed just like `modified` entries. Which means that the analisys does not stop at private usages within a classpath.
E.g. for 
```
public class A {
      // public int bar() { return 0; }
}

public class B {
     private A a = null; 
}

public class C {
    private B b = null;
}

public class D {
    public B b = null;
}
```
`B` is added to `privateDependentClasses`, then `C` is also added to `privateDependentClasses` and `D` is added to `accessibleDependentClasses`. However, only `B` should be added to 
`privateDependentClasses`, because `C` & `D` cannot be affected by a change in `A`.

So all transitive usages of a modified class (within a classpath) are considered affected (affected class set is not optimal).
Then `handleModified` finds all dependends of the affected class set.
```
    private DependentsSet handleModified(File classpathEntry, final ClasspathEntrySnapshot previous) {
        final ClasspathEntrySnapshot currentSnapshot = classpathSnapshot.getSnapshot(classpathEntry);
        ClassChanges classChanges = currentSnapshot.getChangedClassesSince(previous);

        if (classpathSnapshot.isAnyClassDuplicated(classChanges.getAdded())) {
            return DependentsSet.dependencyToAll("at least one of the classes of modified classpath entry '" + classpathEntry + "' is already present in the classpath");
        }

        DependentsSet affectedOnClasspath = collectDependentsFromClasspath(Sets.union(classChanges.getModified(), classChanges.getAdded()));
        if (affectedOnClasspath.isDependencyToAll()) {
            return affectedOnClasspath;
        } else {
            Set<String> joined = affectedOnClasspath.getAllDependentClasses(); // <- here joined also contains private usages
            return previousCompilation.getDependents(joined, currentSnapshot.getRelevantConstants(previous, joined));
        }
    }
```
This means, that even if `B` privately uses `A` within a classpath, usages of `B` within a sourceset are still considered affected by an ABI change of `A`. It does not seem right, only usages of `A` should be considered affected.

The described behaviour can be easily reproduced with examples above and Gradle 6.0.1 (I think the bug is reproducible with any 6.+ version, but I tested only with 6.0.1).

### LINKED ISSUE #14917: Gradle always does full recompilation after getting result of compileJava task from Build cache
So it looks like Gradle build cache is not that effective for compileJava task since Gradle will always do full recompilation due to missing source-classes mapping or missing compilation result. I tested with version 6.7 but this issue might be older.

I expect incremental compilation, but I get full recompilation on all occasions. 

### Expected Behavior
Gradle does incremental compilation after getting result for compileJava from build cache.

### Current Behavior
Gradle does full recompilation after getting result for compileJava from build cache.

### Context
Build cache is not that useful for compile Java. This affects work productivity when for example switching branches etc.

### Steps to Reproduce 
1. git clone git@github.com:asodja/gradle-full-recompilation.git
2. `./gradlew compileJava --info` -> Everything will be compiled nicely
3. `./gradlew compileJava --info` -> compileJava will be reported `UP-TO-DATE`
4. `./gradlew clean compileJava --info` -> compileJava will be reported `FROM-CACHE`
5. Add some dummy statement to TestClass1.build(), like `System.out.println("123");`
6. `./gradlew compileJava --info` -> expected incremental compilation, I get `Full recompilation is required because unable to get source-classes mapping relationship from last compilation.` or sometime `Full recompilation is required because no previous compilation result is available.`

### Your spec
Mac OS Catalina 10.15.6
Gradle 6.7
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
(For some reason I don't get build scan activate email right now)

### PR DESCRIPTION
**Pull request by oehme**
This started as an effort to fix #4951, but quickly turned into a total overhaul of the incremental compiler code, which reduced its complexity and also fixed a few other issues. 

Most notably, api/implementation separation wasn't working for classpath changes (#13499), so Gradle was recompiling way too much in multi-module projects. I've added a test to make sure this doesn't break again.

The main change is that the incremental compiler no longer uses absolute paths to identify classpath entries and whether they've changed or been reordered. Instead, the ClassSetAnalysis of all classpath entries is merged into one big analysis, which is then diffed against the analysis of the last build. This analysis is then stored in the build cache, along with the ClassSetAnalysis of the output directory. The serialized form of ClassSetAnalysis is now space-optimized, so that this additional build cache entry remains small enough to be worth the trade-off.

I've also changed the messages that Gradle provides when it does a full recompilation. It is now explicit about which change caused the full recompilation. This should make it easier to understand and debug.

Handling of newly added package-info and module-info files was broken since the introduction of the `SourceFileClassNameConverter`. This is fixed and tested now too.

I've also added some JavaDoc to the most important classes in the incremental compiler and renamed a few of their methods for clarity.

While trying to performance-test this, I had trouble generating a large enough dependency graph, so I also fixed the performance of our test project generator. In the end, it still wasn't a great test, since it creates a very shallow tree. So instead I tested this on `gradle/gradle` itself. Doing an ABI change to `GUtil`, 7.0-milestone-3 takes **~105s** while this branch only takes **~52s** thanks to the fixed classpath change handling. The CPU overhead of the incremental compiler is roughly the same as before and it is now cacheable. The total size of all added analysis outputs is about 24MB or 125KB per subproject. The daemon memory footprint is now smaller, because we only keep the ABI of classpath entries and discard any information about implementation details, since these can't affect downstream classes.

Fixes #4951
Fixes #14917
Fixes #13499
Fixes #9790
Fixes #9052

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by wolfs** [comment]
We have the feature for detecting if something has been added in the middle of the classpath provided by `InputChanges`. Would it be feasible to use this information for what things changed instead trying to diff the two classpaths again?

**Comment by oehme** [comment]
No, because `FileChange` does not tell me what the hash of the old file was, so I can't look up its class analysis.

**Comment by oehme** [comment]
> though it should be possible to somehow go from FileChange to the corresponding ClasspathEntrySnapshot, right

The classpath snapshots are identified by hash (since they go in the build cache) and the `FileChange` API does not tell me the hashes. I would need both the old and new hash of the changed file.

Also, the API would have to distinguish between "content changed" and "order changed". The former can often be done incrementally, the latter can lead to class shadowing and requires a full recompile.

**Comment by wolfs** [comment]
> Also, the API would have to distinguish between "content changed" and "order changed". The former can often be done incrementally, the latter can lead to class shadowing and requires a full recompile.

The API already distinguishes between "Content changed" and "Order changed":
- Content changed: `ChangeType.MODIFIED`
- Order changed: `ChangeType.{ADDED,REMOVED}`

**Comment by wolfs** [comment]
I am not proposing to replace the snapshotting by `InputChanges`, but to replace the diff calculation here by using the data from `InputChanges`: https://github.com/gradle/gradle/blob/bf41177eaeabf70cdff385cf10d8d3226a24fc9c/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java#L63-L96

**Comment by oehme** [comment]
Just discussed via Slack and the above code no longer exists. We could probably use the InputChanges to detect some non-incremental scenarios more quickly, but overall it would not make the code in `CurrentCompilation` any simpler. I'm gonna go ahead and simplify it a little more by always doing a full recompile when the length of the classpath lists is different. The likelihood of getting useful incrementality in that case is small enough that I don't think having that special case is worth it.

File: subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractSourceIncrementalCompilationIntegrationTest.groovy [hunk 1]
```diff
@@ -1099,26 +1099,29 @@ sourceSets {
...
-        when:
-        executer.requireOwnGradleUserHomeDir()
-        source """class B {
-            //some change
-        }"""
+        when: "In-memory and on-disk caches are clean"
+        executer.stop()
+        file("user-home").deleteDir()
+
+        and: "We're no longer using the old dependency"
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractSourceIncrementalCompilationIntegrationTest.groovy:1118]: Otherwise it's in the cache because we analyse it for the CurrentCompilation

File: subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractSourceIncrementalCompilationIntegrationTest.groovy [hunk 2]
```diff
@@ -1099,26 +1099,29 @@ sourceSets {
...
+        buildFile << "dependencies { implementation 'org.apache.commons:commons-lang3:3.9' }"
```
Comment (oehme) [inline subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractSourceIncrementalCompilationIntegrationTest.groovy:1119]: Using this specific dependency, because it has a different hash, but no changes to constants or other full recompile reasons

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalResultStoringCompiler.java [hunk 3]
```diff
@@ -89,27 +86,13 @@ private AnnotationProcessingData getAnnotationProcessingResult(JavaCompileSpec s
...
     private AnnotationProcessingData convertProcessingResult(AnnotationProcessingResult processingResult) {
-        Map<String, Set<String>> generatedTypesByOrigin = processingResult.getGeneratedTypesWithIsolatedOrigin();
-        Map<String, Set<GeneratedResource>> generatedResourcesByOrigin = processingResult.getGeneratedResourcesWithIsolatedOrigin();
-        Set<String> aggregatedTypes = processingResult.getAggregatedTypes();
-        Set<String> aggregatingTypes = processingResult.getGeneratedAggregatingTypes();
-        Set<GeneratedResource> aggregatingResources = processingResult.getGeneratedAggregatingResources();
-        return new AnnotationProcessingData(intern(generatedTypesByOrigin), intern(aggregatedTypes), intern(aggregatingTypes), generatedResourcesByOrigin, aggregatingResources, processingResult.getFullRebuildCause());
-    }
-
-    private Set<String> intern(Set<String> types) {
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalResultStoringCompiler.java:100]: We no longer keep this in an in-memory cache, but on disk, so interning is not necessary.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/BuildCacheClasspathEntrySnapshotCache.java [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+import org.gradle.util.GradleVersion;
+
+import java.io.IOException;
+import java.io.InputStream;
+import java.io.OutputStream;
+
+/**
+ * Stores classpath entry snapshots in the build cache and loads them from there when they can't be found in the given delegate.
+ */
+public class BuildCacheClasspathEntrySnapshotCache implements ClasspathEntrySnapshotCache {
```
Comment (oehme) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/BuildCacheClasspathEntrySnapshotCache.java:38]: @wolfs I'd like your feedback on this class - This pattern could be generalized into a build cache decorator for any kind of expensive data. For example, we could also use this pattern to store the Classpath/CompileClasspath snapshots for external dependencies, so we don't have to recompute them every time (e.g. on ephemeral CI nodes this can cost a lot of time).

**Comment by oehme** [comment]
Going back to draft, since I have some more ideas how to make this simpler and even restore the incremental corner cases mentioned above.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/BuildCacheClasspathEntrySnapshotCache.java (hunk 4 above)
Comment (melix) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/BuildCacheClasspathEntrySnapshotCache.java:38]: You should probably use the new `ExecutionEngine` instead. The idea would be to create a `UnitOfWork` to perform the class analysis. The engine should handle storing in the cache for you, so you don't need to implement your own cache keys for example.

**Comment by lptr** [comment]
> > You should probably use the new ExecutionEngine instead. The idea would be to create a UnitOfWork to perform the class analysis. The engine should handle storing in the cache for you, so you don't need to implement your own cache keys for example.
> 
> I looked at it, but it seems overblown for this use case. I just want to store a tiny piece of data in the cache, not create output files etc.

Take a look at how `UnitOfWork` is implemented for generating project accessors here: https://github.com/gradle/gradle/blob/0f61831dba98d28b62bbaacc06516e2d0c6d4f60/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt#L103-L166

The idea is that this is how you encapsulate any kind of work that needs to be executed as part of the build going forward. It is supposed to be lightweight and simple enough to implement for even small units of work; if you find something that seems overcomplicated as it is now, or some feature is missing for your use case, we can always discuss how to improve things. We should not introduce new caches if we can avoid it, as well as talking directly to the build cache.

Happy to discuss further with you if you want.

File: subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java [hunk 5]
```diff
@@ -177,6 +178,19 @@ protected File getSourceClassesMappingFile() {
         return sourceClassesMappingFile;
     }
 
+    /**
+     * The previous compilation analysis. Internal use only.
+     *
+     * @since 7.1
+     */
+    @OutputFile
+    protected File getPreviousCompilationData() {
```
[the remark this answers is not in the document]
Comment (oehme) [reply subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java:187]: This is auto-computed and not user-configurable, so I don't think we gain anything from using a Property here.

**Comment by oehme** [comment]
I've completely reworked this 
1. The classpath diff is now done by merging all the entries and then comparing the merged result. This unlocked a ton of other simplifications and eventually made me aware that we didn't have abi/impl separation for classpath changes! I've fixed that by making the classpath analysis use the exact same code path we use for the normal class analysis.
2. I removed the need for BuildCache or ExecutionEngine. Instead, all the necessary state is stored in `PreviousCompilationData`. I've made some optimizations so that the data is small enough to make this feasible. This is both simpler and also a better example for other plugin authors looking to implement something similar for their language or tool.

I've tried this branch out on gradle/gradle, making an ABI change to GUtil.java. The results are very exciting: It takes **107s** on 7.0-milestone-3, but only **52s** on this branch. The sum of all analysis files is 25MB (about 100KB per compile task).

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/RelevantProjectsRegistry.kt [hunk 6]
```diff
@@ -31,7 +31,7 @@ class RelevantProjectsRegistry : ProjectAccessHandler {
     fun relevantProjects(nodes: List<Node>): Set<ProjectInternal> =
         targetProjects +
             nodes.mapNotNullTo(mutableListOf()) { node ->
-                node.owningProject?.takeIf { it.parent != null }
```
Comment (oehme) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/RelevantProjectsRegistry.kt:34]: @eskatos was there a reason for this? All tests pass and it fixes a bug where the build directory of the root project would not be restored.

**Comment by oehme** [comment]
The small regression for the largeMonolithicProject is expected - We are storing more state and that project doesn't benefit from it at all, because everything is in a single module. What's the process for accepting such a change from a branch? Do I have to ignore it until it is merged and a new nightly is published?

**Comment by oehme** [comment]
@melix I think this is ready for a serious look from you now. I've updated the title and description to match the scope of the changes. It's probably best to look at them as a whole now, since I've gone back and forth a lot in the individual commits.

**Comment by melix** [comment]
Excellent, thanks, I'll take a look!

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java [hunk 7]
```diff
@@ -282,19 +282,31 @@ private JavaToolchainSpec determineExplicitToolchain() {
...
      *
      * @since 6.5
      */
-    @LocalState
+    @OutputFile
     protected File getSourceClassesMappingFile() {
         if (sourceClassesMappingFile == null) {
-            File tmpDir = getServices().get(TemporaryFileProvider.class).newTemporaryFile(getName());
-            sourceClassesMappingFile = new File(tmpDir, "source-classes-mapping.txt");
+            sourceClassesMappingFile = new File(getTemporaryDir(), "source-classes-mapping.txt");
```
Comment (melix) [inline subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java:292]: :o: I wonder if we should move the file _out_ of the temporary directory, now that it's a real output.

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java [hunk 8]
```diff
@@ -282,19 +282,31 @@ private JavaToolchainSpec determineExplicitToolchain() {
...
 
+    /**
+     * The previous compilation analysis. Internal use only.
+     *
+     * @since 7.1
+     */
+    @OutputFile
+    protected File getPreviousCompilationData() {
+        if (previousCompilationDataFile == null) {
+            previousCompilationDataFile = new File(getTemporaryDir(), "previous-compilation-data.bin");
```
Comment (melix) [inline subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java:305]: :o: Same here, I think we should probably move it out of the temp dir.

**Review by melix — APPROVED** [review]
Thanks a lot for this PR, @oehme ! I looked into it and didn't see anything obviously wrong. I checked out the branch locally, make some experiments and everything looks good!

I left a few minor comments, let me know if you plan to address them or not. I could take over polishing.

File: subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractSourceIncrementalCompilationIntegrationTest.groovy [hunk 9]
```diff
@@ -1079,8 +1079,15 @@ sourceSets {
...
+        file("src/main/${languageName}/annotations/Anno.${languageName}").text = """
+            package annotations;
+            import java.lang.annotation.*;
+            @Retention(RetentionPolicy.RUNTIME)
+            @Target(ElementType.PACKAGE)
+            public @interface Anno {}
+        """
         def packageFile = file("src/main/${languageName}/foo/package-info.${languageName}")
-        packageFile.text = """package foo;"""
+        packageFile.text = """@Deprecated package foo;"""
```
[the remark this answers is not in the document]
Comment (oehme) [reply subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractSourceIncrementalCompilationIntegrationTest.groovy:1090]: Yes, but then the test is the same as "adding a package-info", because a package-info file without any annotations is not compiled into a class file at all.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassDependentsAccumulator.java [hunk 10]
```diff
@@ -29,39 +29,39 @@
 
 public class ClassDependentsAccumulator {
```
[the remark this answers is not in the document]
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassDependentsAccumulator.java:30]: Yes, but that's such a minor issue that I don't think it's worth complicating the code for. The cost of analysis is in actually looking at the classes, not in aggregating the results. We could stop looking at classes as soon as there is a full rebuild cause. But even that is probably not important, because broken jars should be a rare exception.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 11]
```diff
@@ -66,16 +74,46 @@ public ClassSetAnalysis(ClassSetAnalysisData classAnalysis, AnnotationProcessing
...
     }
 
-    public DependentsSet getRelevantDependents(Iterable<String> classes, IntSet constants) {
-        final Set<String> accessibleResultClasses = new LinkedHashSet<>();
-        final Set<String> privateResultClasses = new LinkedHashSet<>();
-        final Set<GeneratedResource> resultResources = new LinkedHashSet<>();
+    /**
+     * An efficient version of {@link #getTransitiveDependents(String, IntSet)} when several classes have changed.
+     */
+    public DependentsSet getTransitiveDependents(Iterable<String> classes, Map<String, IntSet> constants) {
```
[the remark this answers is not in the document]
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:111]: I'll do that because I think it adds a little clarity (that we expect a finite collection), but in my profiling sessions I never ever saw this code taking any time at all :)

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java [hunk 12]
```diff
@@ -66,16 +74,46 @@ public ClassSetAnalysis(ClassSetAnalysisData classAnalysis, AnnotationProcessing
...
+        DependentsSet transitiveChanges = other.getTransitiveDependents(directChanges.getAllDependentClasses(), Collections.emptyMap());
+        if (transitiveChanges.isDependencyToAll()) {
+            return new ClassSetDiff(transitiveChanges, Collections.emptyMap());
+        }
+        DependentsSet allChanges = DependentsSet.merge(Arrays.asList(directChanges, transitiveChanges));
+        Map<String, IntSet> changedConstants = getChangedConstants(other, allChanges);
+        return new ClassSetDiff(allChanges, changedConstants);
+    }
+
+    private Map<String, IntSet> getChangedConstants(ClassSetAnalysis other, DependentsSet affectedClasses) {
```
[the remark this answers is not in the document]
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java:94]: Sure, no problem, I'll align that with your conventions.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/DependentsSet.java [hunk 13]
```diff
@@ -50,6 +52,31 @@ public static DependentsSet empty() {
         return EmptyDependentsSet.INSTANCE;
     }
 
+    public static DependentsSet merge(Collection<DependentsSet> sets) {
```
[the remark this answers is not in the document]
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/DependentsSet.java:55]: Will do.

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java (hunk 7 above)
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java:292]: I think it's fine like this as long as we consider this an internal detail of the task. If we ever make this configurable or let users read our analysis file (effectively making it API), then I'd agree putting it in a more prominent, configurable location.

Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java:292]: Note that the "temp" dir is still in the build folder, not in `/tmp`. So it's not temporary at all :)

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/CurrentCompilationAccess.java [hunk 14]
```diff
@@ -0,0 +1,113 @@
...
+
+    public ClassSetAnalysisData analyzeOutputFolder(File outputFolder) {
+        Timer clock = Time.startTimer();
+        ClassSetAnalysisData snapshot = classSetAnalyzer.analyzeOutputFolder(outputFolder);
+        LOG.info("Class dependency analysis for incremental compilation took {}.", clock.getElapsed());
+        return snapshot;
+    }
+
+
+    public ClassSetAnalysisData getClasspathSnapshot(final Iterable<File> entries) {
```
[the remark this answers is not in the document]
Comment (oehme) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/CurrentCompilationAccess.java:59]: We don't have to use intermediate Lists, the snapshotter could create a Stream out of the Iterable if we wanted to. Also I find the Stream API to be very limiting, e.g. not being able to know the size (even though we do know), whether it's empty etc and only being able to iterate over it once. I think Iterable or Collection are a better default for things that we hold in memory.

**Review by melix — APPROVED** [review]
LGTM!

**Comment by melix** [comment]
@bot-gradle test and merge

**Comment by melix** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by melix** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge
