### PR TITLE
Use Foojay convention plugin when applying toolchains in Build Init

### LINKED ISSUE #24591: `gradle init` with `Generate build using new APIs and behavior` seems to use the wrong toolchain resolver plugin
### Context

I just tried to set up a new Java library project with the Kotlin DSL and toolchain provisioning. Specifically, I executed `gradle init` with Gradle version `8.1-rc-2` on Windows 10 with Java 19. I selected the following non-default initialization options:

- Type of project: 3: library
- DSL: 2: Kotlin
- Java target version: 20
- Generate build using new APIs and behavior: **yes**

These options result in a Gradle project that explicitly configures a toolchain for the included `lib` project. Its `build.gradle.kts` file contains the following block:

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(20))
        }
    }

### Expected Behavior

When looking at the root project `settings.gradle.kts` file, I would expect the following plugin in the `plugins` block:

    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"

In addition, I would expect this toolchain resolver plugin to download the Adoptium JDK 20 and store it in `~/.gradle/jdks` upon running `gradlew build`.

### Current Behavior

Instead of the above plugin, I see `settings.gradle.kts` refers to the following plugin (note how the `-convention` suffix is missing):

    id("org.gradle.toolchains.foojay-resolver") version "0.4.0"

Additionally, `gradlew build` doesn't download the toolchain and fails with the following error:

    Could not determine the dependencies of task ':lib:compileJava'.
    > Could not resolve all dependencies for configuration ':lib:compileClasspath'.
       > Failed to calculate the value of task ':lib:compileJava' property 'javaCompiler'.
          > No matching toolchains found for requested specification: {languageVersion=20, vendor=any, implementation=vendor-specific}.
             > No locally installed toolchains match (see https://docs.gradle.org/8.1-rc-2/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1-rc-2/userguide/toolchains.html#sub:download_repositories).

    * Try:
    > Run with --stacktrace option to get the stack trace.
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.

### Steps to Reproduce

Either:

- Follow the steps described above.

Or:

- Extract the attached archive ([gradle-8.1-rc-2-init.zip](https://github.com/gradle/gradle/files/11129692/gradle-8.1-rc-2-init.zip)).
- Run `gradlew build`.

### Additional Observations

If I do **not** select "Generate build using new APIs and behavior" while initializing the Gradle project, the behavior is as expected. Thus, the use of new APIs seems to be causing trouble here.

### Your Environment

- Windows 10
- Eclipse Adoptium JDK 19.0.2+7

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #24591

### CODE REVIEW

File: subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SimpleGlobalFilesBuildSettingsDescriptor.java [hunk 1]
```diff
@@ -49,10 +49,10 @@ private BuildScriptBuilder builder(InitSettings settings) {
             builder.includePluginsBuild();
         }
 
-        if(settings.getJavaLanguageVersion().isPresent()){
+        if(settings.getJavaLanguageVersion().isPresent()) {
```
Comment (MGaetan89) [inline subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SimpleGlobalFilesBuildSettingsDescriptor.java:52]:
```suggestion
        if (settings.getJavaLanguageVersion().isPresent()) {
```

**Review by ljacomet — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test and merge
