### PR TITLE
Deprecate already joined paths when calling FileCollection.getAsPath

### LINKED ISSUE #19817: Setting bootClasspath can cause build failure with obscure message on Windows only after upgrade to 7.3.x
### Expected Behavior

Any of the following is reasonable

1. Compilation should complete normally (as per behaviour on MacOS and Linux)
2. Attempt to use an illegal value for bootclasspath (or `project.files`) should fail eagerly
3. A more informative error should be thrown at runtime

### Current Behavior

On linux or MacOS, the build completes normally when running under 7.3.x
On Windows, the build completes normally when running under 7.1.1 or 7.2
On Windows, the following exception is throw when a (java) compilation task attempts to execute when running in 7.3.x

```
Execution failed for task ':compileJava'.
> Changes are not tracked, unable determine incremental changes.
```

Running with debug shows the actual error is

```
2022-02-03T11:50:11.258+0000 [INFO] [org.gradle.api.internal.tasks.execution.TaskExecution] Cannot access input property 'options.bootstrapClasspath' of task ':compileJava'
org.gradle.api.UncheckedIOException: Could not stat file C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\jsse.jar;C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\jce.jar;C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\charsets.jar;C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar
        at org.gradle.internal.nativeintegration.filesystem.services.NativePlatformBackedFileMetadataAccessor.stat(NativePlatformBackedFileMetadataAccessor.java:43)
        at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.stat(GenericFileSystem.java:107)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.snapshot(DefaultFileSystemAccess.java:147)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.lambda$readLocation$6(DefaultFileSystemAccess.java:171)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.lambda$readSnapshotFromLocation$7(DefaultFileSystemAccess.java:196)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess$StripedProducerGuard.guardByKey(DefaultFileSystemAccess.java:219)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.lambda$readSnapshotFromLocation$8(DefaultFileSystemAccess.java:193)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.readSnapshotFromLocation(DefaultFileSystemAccess.java:193)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.readSnapshotFromLocation(DefaultFileSystemAccess.java:178)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.readLocation(DefaultFileSystemAccess.java:171)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.read(DefaultFileSystemAccess.java:83)
        at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter$SnapshottingVisitor.visitCollection(DefaultFileCollectionSnapshotter.java:61)
        at org.gradle.api.internal.file.AbstractOpaqueFileCollection.visitContents(AbstractOpaqueFileCollection.java:55)
.
.
.
Caused by: net.rubygrapefruit.platform.NativeException: Could not get file details of C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\jsse.jar;C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\jce.jar;C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\charsets.jar;C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar: could not file attributes (errno 123)
        at net.rubygrapefruit.platform.internal.DefaultWindowsFiles.stat(DefaultWindowsFiles.java:38)
        at net.rubygrapefruit.platform.internal.DefaultWindowsFiles.stat(DefaultWindowsFiles.java:28)
        at org.gradle.internal.nativeintegration.filesystem.services.NativePlatformBackedFileMetadataAccessor.stat(NativePlatformBackedFileMetadataAccessor.java:41)
        ... 105 more
```

### Context

This issue prevents java compilation on Windows when setting the boot classpath

The error occurs when a single string containing n paths (concatenated with pathSeparator) is passed to `project.files` as opposed n strings (1 for each path). Probably this is wrong use of `project.files` however it works without a problem on both Linux and MacOS & Windows with versions <=7.2 so the inconsistency is confusing.

### Steps to Reproduce 

I can't upload to github from here, run the following build on Windows under 7.3.3 then 7.2 

ensure some jdk8 is available at the path specified by bootClasspathRoot

```
apply plugin: 'java'

sourceCompatibility = '8'
targetCompatibility = '8'

def bootClasspathRoot = 'C:/Users/me/dev/libs/openjdk1.8.0_311'
def rtJarFile = project.file("${bootClasspathRoot}/jre/lib/rt.jar")
def extraJars = ['jsse', 'jce', 'charsets']
def extraJarFiles = extraJars.collect { new File(rtJarFile, "${it}.jar").absolutePath }
def bootstrapJars = (extraJarFiles + [rtJarFile])
def bootstrapClasspath1 = project.files(bootstrapJars.join(File.pathSeparator))
def bootstrapClasspath2 = project.files(bootstrapJars)

logger.error("Adding ${bootstrapJars}")

def bootstrapClasspath = hasProperty('breakme') ? bootstrapClasspath1 : bootstrapClasspath2

tasks.withType(JavaCompile).configureEach {
    it.options.bootstrapClasspath = bootstrapClasspath
}
```

with breakme set on 7.3.3
```
gradlew.bat -Pbreakme=true build

> Configure project :
Adding [C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\jsse.jar, C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\jce.jar, C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\charsets.jar, C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar]

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Changes are not tracked, unable determine incremental changes.
```

and without on 7.3.3

```
gradlew.bat clean build

> Configure project :
Adding [C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\jsse.jar, C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\jce.jar, C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\charsets.jar, C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar]

BUILD SUCCESSFUL in 1s
```

and with on 7.2

```
gradlew.bat -Pbreakme=true clean build

> Configure project :
Adding [C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\jsse.jar, C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\jce.jar, C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar\charsets.jar, C:\Users\me\dev\libs\openjdk1.8.0_311\jre\lib\rt.jar]

BUILD SUCCESSFUL in 1s
```

### Your Environment

I can't upload build scans, build is run under java11 on Windows 10 or Windows 7

### PR DESCRIPTION
**Pull request by asodja**
Fixes #19817

~~It's a breaking change, so I set the milestone to 8.0 (I should add also notes to breaking changes).~~

Update: we will first deprecate this in 7.5 and made an error in 8.0.

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/MinimalJavaCompileOptions.java [hunk 1]
```diff
@@ -25,13 +25,15 @@
...
+import java.util.Collections;
 import java.util.List;
+import java.util.Set;
 
 public class MinimalJavaCompileOptions implements Serializable {
     private List<File> sourcepath;
     private List<String> compilerArgs;
     private String encoding;
-    private String bootClasspath;
+    private Set<File> bootClasspath;
```
Comment (wolfs) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/MinimalJavaCompileOptions.java:36]: I don't think this should be a `Set` (or a `List`) at this point. If we already do a breaking change, I would change `FileCollection.getAsPath()` to do the validation.

Even better, we could emit a deprecation warning there right now and fail in Gradle 8.0. WDYT?

**Review by wolfs — CHANGES_REQUESTED** [review]

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/MinimalJavaCompileOptions.java (hunk 1 above)
Comment (asodja) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/MinimalJavaCompileOptions.java:36]: It would definitely work also with other cases. I will change it.

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/MinimalJavaCompileOptions.java (hunk 1 above)
Comment (asodja) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/MinimalJavaCompileOptions.java]: fixed

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy [hunk 2]
```diff
@@ -905,6 +907,29 @@ class JavaCompileIntegrationTest extends AbstractIntegrationSpec {
...
+            tasks.withType(JavaCompile) {
+                options.bootstrapClasspath = project.layout.files("$bootClasspath")
+            }
+        """
+        file('src/main/java/Foo.java') << 'public class Foo {}'
+
+        expect:
+        executer.expectDeprecationWarning("FileCollection 'file collection' that is being mapped to a path contains already concatenated files instead of a collection of single files." +
+            " This can lead to uncontrolled failures. Problematic concatenations are: ${Paths.get(bootClasspath)}." +
+            " This will fail with an error in Gradle 8.0. Add files to a collection as single files instead of manually concatenating them.")
```
Comment (wolfs) [inline subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy:929]:
```suggestion
        executer.expectDeprecationWarning("Converting files to a classpath string when their paths contain the path separator %s has been deprecated." +
            " The path separator is not a valid element of a file path. Problematic paths in 'file collection' are '${Paths.get(bootClasspath)}'." +
            " This will fail with an error in Gradle 8.0. Add the individual files to the file collection instead.")
```

How about something like ☝️ ?

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java [hunk 3]
```diff
@@ -145,6 +147,9 @@ protected void generate() {
         JavaModuleDetector javaModuleDetector = getJavaModuleDetector();
         options.classpath(new ArrayList<>(javaModuleDetector.inferClasspath(isModule, getClasspath()).getFiles()));
         options.modulePath(new ArrayList<>(javaModuleDetector.inferModulePath(isModule, getClasspath()).getFiles()));
+        if (options.getBootClasspath() != null) {
```
Comment (wolfs) [inline subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java:150]: Why is this still here, that should be removed, right?

File: subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocIntegrationTest.groovy [hunk 4]
```diff
@@ -297,4 +301,27 @@ Joe!""")
     private TestFile writeSourceFile() {
         file("src/main/java/Foo.java") << "public class Foo {}"
     }
+
+    // bootclasspath has been removed in Java 9+
+    @Requires(TestPrecondition.JDK8_OR_EARLIER)
+    @Issue("https://github.com/gradle/gradle/issues/19817")
+    def "fails if bootclasspath is provided as a path instead of a single file"() {
```
Comment (wolfs) [inline subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocIntegrationTest.groovy:308]: This test name needs to be adjusted.

File: subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java [hunk 5]
```diff
@@ -175,9 +177,29 @@ public File getSingleFile() throws IllegalStateException {
...
+        if (!filesAsPaths.isEmpty()) {
+            DeprecationLogger.deprecateBehaviour(String.format(
+                    "FileCollection '%s' that is being mapped to a path contains already concatenated files instead of a collection of single files." +
+                        " This can lead to uncontrolled failures. Problematic concatenations are: %s.",
+                    getDisplayName(),
+                    String.join(", ", filesAsPaths))
+                )
+                .withAdvice("Add files to a collection as single files instead of manually concatenating them.")
+                .willBecomeAnErrorInGradle8()
+                .undocumented()
```
Comment (wolfs) [inline subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java:198]: This needs to be documented in the upgrading notes.

**Review by wolfs — COMMENTED** [review]
I think this is better! The message can use some improvement and documentation is missing.

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java (hunk 3 above)
Comment (asodja) [reply subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java:150]: Javadoc does not use file collection. So to keep similar behavior between compile and javadoc I added warning manually also here. What do you think about that?

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy (hunk 2 above)
Comment (asodja) [reply subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy:929]: Works for me

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java (hunk 3 above)
Comment (wolfs) [reply subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java:150]: How about converting the list of files to a file collection and then calling `getAsPath()` on it?

File: subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocIntegrationTest.groovy (hunk 4 above)
Comment (asodja) [reply subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocIntegrationTest.groovy]: removed

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java (hunk 3 above)
Comment (asodja) [reply subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java]: So there is `JavadocOptionFileOption` that is used all over the place with a lot of inheritance, so I think it's not worth it doing that now. And we rather do it when we migrate to providers.

I removed this and the test. WDYT?

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java (hunk 3 above)
Comment (wolfs) [reply subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java]: I am fine with not doing anything for Javadoc. What you could do here is something like this:
```
project.files(object.getBootclasspath()).getAsPath();
```

instead of your custom validation. That would emit the deprecation warning as well.

File: subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java (hunk 5 above)
Comment (asodja) [reply subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java]: fixed

File: subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc [hunk 6]
```diff
@@ -55,6 +55,15 @@ eclipse {
...
 Alternatively, you can adjust or remove classpath attributes in the `eclipse.classpath.file.whenMerged { }` block.
 
+=== Deprecations
+
+[[file_collection_to_classpath]]
+==== Converting files to a classpath where paths contain file separator
+Gradle 7.5+ until 8.0 will emit a deprecation warning when using
+`@link:{javadocPath}/javadoc/org/gradle/api/file/FileCollection.html#getAsPath--[FileCollection.getPath()]` for files with paths that contain a path separator. Allowing paths with the path separator can, in some cases, result in an uncontrolled failure of the build.
+
+In Gradle 8.0 and later this will be an error.
```
Comment (wolfs) [inline subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc:65]:
```suggestion
Java has the concept of a path separator which is used to separate individual paths in a list of paths, for example in a classpath string.
The individual paths must not contain the path separator.
Consequently, using
`@link:{javadocPath}/javadoc/org/gradle/api/file/FileCollection.html#getAsPath--[FileCollection.getPath()]` for files with paths that contain a path separator has been deprecated.
Using a file collection with paths which contain a path separator may lead to incorrect builds, since Gradle doesn't find the files as inputs, or even to build failures when the path containing the path separator is illegal on the operating system.
```

A few comments:
* In documentation, we try to use one-line-per-sentence style, so it is easier to do review comments.
* You don't need to take about the lifecycle of deprecations, since that is already something we document in our user manual.
* It is good to give some context what the feature is about.

I left a suggestion how to make it better. Please take a look and tell me what you think.

Comment (asodja) [reply subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc:65]: I think it's good and gives more context to the user.

I am wondering if we should point out that this will be an error in 8.0, so users are reminded about that. What do you think?

Comment (wolfs) [reply subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc:65]: I don't think it adds much value, though you can if you want to. I looked through the upgrading notes and some deprecations have something about 8.0, while others don't. Given that the default is to fail in Gradle 8.0, I am not sure if pointing that out gives more value.

Comment (asodja) [reply subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc]: I added `, and it will be an error in Gradle 8.0 and later`.

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc [hunk 7]
```diff
@@ -55,6 +55,16 @@ eclipse {
 
 Alternatively, you can adjust or remove classpath attributes in the `eclipse.classpath.file.whenMerged { }` block.
 
+=== Deprecations
+
+[[file_collection_to_classpath]]
+==== Converting files to a classpath where paths contain file separator
+Java has the concept of a path separator which is used to separate individual paths in a list of paths, for example in a classpath string.
```
Comment (wolfs) [inline subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc:62]:
```suggestion
==== Converting files to a classpath where paths contain file separator

Java has the concept of a path separator which is used to separate individual paths in a list of paths, for example in a classpath string.
```

Do you need a newline after the heading?

**Review by wolfs — COMMENTED** [review]
This looks good now! I left one question.

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by asodja** [comment]
@bot-gradle test and merge

**Comment by asodja** [comment]
@bot-gradle test and merge
