### PR TITLE
Fix serialization of provider backed relative files/directories with configuration cache

### LINKED ISSUE #32992: DirectoryProperty and RegularFileProperty resolve relative paths incorrectly when loading from CC
Same as: https://github.com/gradle/gradle/issues/30052 but for `DirectoryProperty` and `RegularFileProperty`

The root cause is that the file resolver is not serialized by CC despite being part of the state of those properties.

There is an additional problem with `DirectoryProperty` in that the `FileCollectionFactory` it carries must be restored correctly as well.

---

There is also a related question about whether these file properties should share an identity:
- https://github.com/gradle/gradle/issues/32591

### PR DESCRIPTION
**Pull request by ghale**
We now retain the configuration of file resolvers in provider-backed properties when the values contain relative directories.

Fixes #32992 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test ACC

File: platforms/core-configuration/file-collections/src/integTest/groovy/org/gradle/api/file/RelativePathFilesIntegrationTest.groovy [hunk 1]
```diff
@@ -97,6 +97,7 @@ class RelativePathFilesIntegrationTest extends AbstractIntegrationSpec {
 
     // TODO: write a similar test for the RegularFileProperty
     @ToBeFixedForConfigurationCache
+    @Issue("https://github.com/gradle/gradle/issues/322591")
```
Comment (alllex) [inline platforms/core-configuration/file-collections/src/integTest/groovy/org/gradle/api/file/RelativePathFilesIntegrationTest.groovy:100]: @ghale, can these todos be removed with your changes?
Also, there is a typo in the issue link

Comment (ghale) [reply platforms/core-configuration/file-collections/src/integTest/groovy/org/gradle/api/file/RelativePathFilesIntegrationTest.groovy:100]: Good catch on the broken link.  I don't think I can remove the TODO because (as I read it) it refers to creating a RegularFileProperty test for #32591.  I didn't addd one for that issue, I just added the `@Issue` annotation on this test to be clear which issue it refers to.  My changes (and the tests I added) relate to a different issue (#32992). 

I've got another PR ready to fix the broken link (#33852).
