### PR TITLE
Only look for worker failures in test descriptors from workers

### LINKED ISSUE #34252: Builds with flaky tests now fail with cryptic "worker failures" when using Develocity
### Current Behavior

The build fails with a message like:
```
> Task :app:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:test'.
> Test process encountered an unexpected problem.
   > AfterSuite goes boom!

* Try:
> Check common problems https://docs.gradle.org/9.0.0-rc-2/userguide/java_testing.html#sec:java_testing_troubleshooting.
```

### Expected Behavior

The build should not fail because the test is retried and succeeds. 

### Context (optional)

_No response_

### Self-contained Reproducer Project

Reproducer
https://github.com/pshevche/reproducers/tree/main/testng-lifecycle-failures

### Gradle version

9.0.0 RC1

### Gradle version that used to work

8.x

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by big-guy**
Fixes #34252

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

File: testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/DevelocityPluginSmokeTest.groovy [hunk 1]
```diff
@@ -16,6 +16,7 @@
 
 package org.gradle.smoketests
 
+
```
Comment (jvandort) [inline testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/DevelocityPluginSmokeTest.groovy]: Extra line

File: testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/DevelocityPluginSmokeTest.groovy [hunk 2]
```diff
@@ -184,6 +186,75 @@ class BuildScanPluginSmokeTest extends AbstractSmokeTest {
...
     }
 
+    @Issue("https://github.com/gradle/gradle/issues/34252")
+    def "does not fail when using TD #version"() {
+        when:
+        usePluginVersion version
+
+        buildFile << """
+            dependencies {
+                testImplementation("org.testng:testng:7.5.1")
```
Comment (jvandort) [inline testing/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/DevelocityPluginSmokeTest.groovy:195]: Is it worth reproducing with junit platform as well/instead?

**Review by ljacomet — APPROVED** [review]
