### PR TITLE
Fix module dependency copy

### LINKED ISSUE #9672: Module dependency copy does not deep copy attributes or capabilities
### Expected Behavior

`AbstractModuleDependency.copy()` should copy attributes and capabilities immutably, such that they can change independently of the original dependency.

### Current Behavior

When doing `AbstractModuleDependency.copy()`, mutating the attributes or capabilities of the copy would also mutate the original dependency.

### Context

Want to copy dependencies and modify their attributes, but ran into the issue above.
Had to [manually wire up the `ImmutableAttributeFactory` and copy `AttributeContainerInternal` using reflection](https://github.com/palantir/gradle-consistent-versions/pull/141/files#diff-3f11fbb18c48f096735ae7340c349471R66) to temporarily get around this.

### Your Environment

Build scan URL:

### PR DESCRIPTION
**Pull request by dansanduleac**
### Context

Fixes #9672

#### Before this PR

`AbstractModuleDependency.copy()` would fail to deep copy attributes and capabilities, such that mutating the copy would also mutate the original dependency.

#### After this PR

`AbstractModuleDependency.copy()` now copies attributes and capabilities immutably, and there are tests to prove it.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by big-guy** [comment]
@ljacomet could you take a look at this?

File: subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependency.java [hunk 1]
```diff
@@ -237,7 +247,8 @@ protected ImmutableAttributesFactory getAttributesFactory() {
     }
 
     void setAttributes(AttributeContainerInternal attributes) {
-        this.attributes = attributes;
+        this.attributes = attributes != null ? attributes.asImmutable() : null;
```
Comment (ljacomet) [inline subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependency.java]: Having the ability to query an `AttributeContainerInternal` for its mutable / immutable state would be best, as it would allow to set that flag to the right value directly and not have to do potentially costly immutable / mutable conversions.
I would recommend adding `AttributeContainerInternal.isImmutable()` to solve that.

Comment (dansanduleac) [reply subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependency.java]: So I actually went with that approach first, but it seemed dirtier to require consumers to check this flag first, and potentially forgetting to do that. Maybe doing that makes it cleaner after all, as right now you might set the field directly and wreck the state, since it's all the same class.

FWIW, the only user of this `setAttributes` is in this same class, and guaranteed to pass it an immutable. On a separate note, we could even consider making it private unless you have any objections to that?

**Comment by dansanduleac** [comment]
@ljacomet ready for review

File: subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependency.java (hunk 1 above)
Comment (ljacomet) [reply subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependency.java]: Ok, I looked deeper at the flow and indeed I would update `setAttributes` to be `private` and call it with an already copied mutable attribute container.

Makes sense?

**Comment by ljacomet** [comment]
@dansanduleac Have you seen my latest comment in the thread above?

File: subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependency.java (hunk 1 above)
Comment (dansanduleac) [reply subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependency.java]: I'm not sure that's always possible.
To copy and make it mutable, you need a factory, but that might be null (technically, I don't know how often this would be the case in practice).
On the other hand, we can always turn a mutable container into an immutable one.

Happy to make setAttributes private though.

Comment (dansanduleac) [reply subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependency.java]: I suppose you must have had an attribute factory if you managed to set any attributes at all (given `setAttributes` is now private), but we'd still have to check if the current `attributes` is null or not, in order to determine whether to create a new mutable one or not.
And given that the logic is currently copy-on-write (when handling the null -> empty mutable case) I thought it makes more sense to keep it that way.

Comment (ljacomet) [reply subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependency.java]: I ended up looking and pushing a change. Let me know if I missed something.

**Comment by dansanduleac** [comment]
@ljacomet thanks for getting this over the line! Looks like tests are passing now, okay to merge?
