### PR TITLE
Fix invalid class generated when extracting ABI from non-static inner-class

### LINKED ISSUE #31416: Invalid class generated when extracting ABI from non-static inner-class
When using the ABI extractor on a non-static inner class, the resulting `.class` file is invalid, and trips up the Java compiler.

Since we only use these generated classes to calculate normalized hashes for compile classpaths, the bug does not have any adverse effects right now. But soon we'd like to expose these classes as the actual compile targets inside Gradle (see #31385 where the problem was discovered).

The error is only reported when trying to compile against the class:

```text
/Users/lptr/Workspace/gradle/gradle-yello/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainer.java:434: error: cannot access AbstractDomainObjectCreatingProvider
    public class NamedDomainObjectCreatingProvider<I extends Configuration> extends AbstractDomainObjectCreatingProvider<I> {
                                                                                    ^
  bad class file: /Users/lptr/Workspace/gradle/gradle-yello/subprojects/core/build/generated/java-abi/org/gradle/api/internal/DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.class
    bad RuntimeInvisibleParameterAnnotations attribute: AbstractDomainObjectCreatingProvider(String,Class<I>,Action<? super I>)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
  where I,T are type-variables:
    I extends T declared in class AbstractDomainObjectCreatingProvider
    T extends Object declared in class DefaultNamedDomainObjectCollection
```

Running `javap -v` on the `.class` file works:

```text
  public org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider(java.lang.String, java.lang.Class<I>, org.gradle.api.Action<? super I>);
    descriptor: (Lorg/gradle/api/internal/DefaultNamedDomainObjectCollection;Ljava/lang/String;Ljava/lang/Class;Lorg/gradle/api/Action;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=2, locals=5, args_size=5
         0: new           #10                 // class java/lang/Error
         3: dup
         4: invokespecial #13                 // Method java/lang/Error."<init>":()V
         7: athrow
    Signature: #8                           // (Ljava/lang/String;Ljava/lang/Class<TI;>;Lorg/gradle/api/Action<-TI;>;)V
    RuntimeVisibleParameterAnnotations:
      parameter 0:
      parameter 1:
      parameter 2:
        0: #14()
          javax.annotation.Nullable
      parameter 3:
```

The problem is that there is an additional entry under `RuntimeVisibleParameterAnnotations` because of how ASM decides the number of entries in that list:

https://gitlab.ow2.org/asm/asm/-/blob/c79a8ca45ee3d05bfb8cf9318fce239c759e0435/asm/src/main/java/org/objectweb/asm/MethodWriter.java#L691-713

```java
  @Override
  public AnnotationVisitor visitParameterAnnotation(
      final int parameter, final String annotationDescriptor, final boolean visible) {
    if (visible) {
      if (lastRuntimeVisibleParameterAnnotations == null) {
        lastRuntimeVisibleParameterAnnotations =
            new AnnotationWriter[Type.getArgumentCount(descriptor)];
      }
      return lastRuntimeVisibleParameterAnnotations[parameter] =
          AnnotationWriter.create(
              symbolTable, annotationDescriptor, lastRuntimeVisibleParameterAnnotations[parameter]);
    } else {
      if (lastRuntimeInvisibleParameterAnnotations == null) {
        lastRuntimeInvisibleParameterAnnotations =
            new AnnotationWriter[Type.getArgumentCount(descriptor)];
      }
      return lastRuntimeInvisibleParameterAnnotations[parameter] =
          AnnotationWriter.create(
              symbolTable,
              annotationDescriptor,
              lastRuntimeInvisibleParameterAnnotations[parameter]);
    }
  }
```

Here `lastRuntimeVisibleParameterAnnotations` is initialized to have as many entries as the method has parameters. But for non-static inner-class constructors it seems that the first parameter is omitted from this list normally, but ASM does not account for that. (Nor can it, since it uses the method descriptor to do the counting.) This results in one extra entry in the list.

Related ASM issue:

- https://gitlab.ow2.org/asm/asm/-/issues/318023

### PR DESCRIPTION
**Pull request by lptr**
Fixes #31416

This fixes the problem with non-static inner-class constructors where the constructor would end up having one more `RuntimeVisibleAnnotations` entry recorded, causing compilation errors when trying to compile against the extracted class.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: build-logic/java-api-extractor/src/test/groovy/org/gradle/internal/tools/api/ApiClassExtractorTestSupport.groovy [hunk 1]
```diff
@@ -116,25 +117,33 @@ class ApiClassExtractorTestSupport extends Specification {
...
+    }
+
+    protected ClassContainer compileTo(File dir, String targetVersion, List<String> packages, Map<String, String> sources, List<File> classpath) {
         dir.mkdirs()
         def fileManager = compiler.getStandardFileManager(null, null, null)
+        fileManager.setLocation(StandardLocation.CLASS_PATH, classpath);
         def diagnostics = new DiagnosticCollector<JavaFileObject>()
         def task = compiler.getTask(
-            new OutputStreamWriter(new ByteArrayOutputStream()),
+            null,
```
Comment (lptr) [inline build-logic/java-api-extractor/src/test/groovy/org/gradle/internal/tools/api/ApiClassExtractorTestSupport.groovy:146]: 💭 This allows showing compiler output on `stderr`. Can be useful while debugging.

File: build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java [hunk 2]
```diff
@@ -80,6 +83,16 @@ public void writeMethod(MethodMember method) {
...
+
+        // Without this parameter annotations for non-static inner class constructors would
+        // end up having one more parameter than they should, because the first parameter
+        // (pointing to `this` of the enclosing type) should not be listed.
+        if (method.getSignature() != null) {
+            int parameterCount = SignatureParameterCounter.countParameters(method.getSignature());
+            mv.visitAnnotableParameterCount(parameterCount, true);
+            mv.visitAnnotableParameterCount(parameterCount, false);
+        }
+
```
Comment (lptr) [inline build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java:95]: 💭 This is the main change. We are now explicitly telling ASM how many annotable parameters there are instead of trusting it to figure it out based on the method descriptor.

File: build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java [hunk 3]
```diff
@@ -80,6 +83,17 @@ public void writeMethod(MethodMember method) {
             method.getExceptions().toArray(new String[0]));
         writeMethodAnnotations(mv, method.getAnnotations());
         writeMethodAnnotations(mv, method.getParameterAnnotations());
+
+        // Without this parameter annotations for non-static inner class constructors would
+        // end up having one more parameter than they should, because the first parameter
+        // (pointing to `this` of the enclosing type) should not be listed.
+        // See https://gitlab.ow2.org/asm/asm/-/issues/318023
+        if (method.getSignature() != null) {
```
Comment (asodja) [inline build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java:91]: ❓ Should we do that only for constructors or is it ok to do for all methods?

Comment (lptr) [reply build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java:91]: That's not actually a problem, because we can always determine the proper list of arguments from the signature.

However, you just made me realize there is another problem. Signatures are only available if there's any generics involved. If I change the example constructor to have no generics, the problem persists. :/

Back to the drawing board I guess.

Comment (asodja) [reply build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java:91]: Hmm, I would expect signature is always present

Comment (lptr) [reply build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java]: It isn't unfortunately (just tested).

File: build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java [hunk 4]
```diff
@@ -74,12 +81,25 @@ public void writeClass(ClassMember classMember, Set<MethodMember> methods, Set<F
...
+        // end up having one more parameter than they should, because the first parameter
+        // (pointing to `this` of the enclosing type) should not be listed.
+        // See https://gitlab.ow2.org/asm/asm/-/issues/318023
+        if (method.getName().equals("<init>")
+            && declaringInnerClass != null
+            && (declaringInnerClass.getAccess() & ACC_STATIC) != ACC_STATIC) {
+            int parameterCount = Type.getArgumentCount(method.getTypeDesc()) - 1;
+            mv.visitAnnotableParameterCount(parameterCount, true);
+            mv.visitAnnotableParameterCount(parameterCount, false);
+        }
```
Comment (lptr) [inline build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java:101]: 💭 Now we are checking explicitly for non-static inner-class constructors.

File: build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/ApiMemberWriter.java [hunk 5]
```diff
@@ -40,7 +40,7 @@ public interface ApiMemberWriter {
 
     void writeClass(ClassMember classMember, Set<MethodMember> methods, Set<FieldMember> fields, Set<InnerClassMember> innerClasses);
 
-    void writeMethod(MethodMember method);
+    void writeMethod(/* Nullable */ InnerClassMember declaringInnerClass, MethodMember method);
```
Comment (lptr) [inline build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/ApiMemberWriter.java:43]: 💭 `/* Nullable */` is something IntelliJ actually tracks in place of `@Nullable`.https://github.com/gradle/gradle/pull/31417

We don't have access to `@Nullable` here, so...

File: build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java [hunk 6]
```diff
@@ -57,8 +60,12 @@ public void writeClass(ClassMember classMember, Set<MethodMember> methods, Set<F
         for (String permittedSubclass : classMember.getPermittedSubclasses()) {
             apiMemberAdapter.visitPermittedSubclass(permittedSubclass);
         }
+        InnerClassMember declaringInnerClass = innerClasses.stream()
```
Comment (asodja) [inline build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java:63]: 🤔 I wonder if we can figure that out from access as here:
https://github.com/gradle/gradle/blob/49c24ac23d9381d646c88e6fd731fb005cef7b3a/build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/ApiMemberSelector.java#L73

Comment (lptr) [reply build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java:63]: I tested that, but I always get `33` (`ACC_PUBLIC` and `ACC_SUPER`) for `access` for the `classMember`.

Comment (lptr) [reply build-logic/java-api-extractor/src/main/java/org/gradle/internal/tools/api/impl/JavaApiMemberWriter.java:63]: :+1: It would be good to do a proper review/refactor on it.
