### PR TITLE
use existing retry logic for maven metadata download

### LINKED ISSUE #27262: Maven publishing retries PUT but doesn't retry metadata download
### Expected Behavior

Using options like 
```
-Dorg.gradle.internal.network.retry.max.attempts=5
-Dorg.gradle.internal.network.retry.initial.backOff=5000
```
will cause maven publisher to retry PUT operations that fail with network errors that appear recoverable but if a server you are publishing to is struggling, the failure can occur while retrieving metadata and that is not retried. If it retried using the same retry logic, that would make publishing more likely to succeed.

### Current Behavior (optional)

_No response_

### Context

When the Apereo CAS project publishes snapshots to the Sonatype Nexus repository there are occasional failures (e.g. a 502 failure presumably from a proxy in front of Nexus when the Nexus server is under load or possibly restarting after a crash). The retry logic in gradle was enabled but then it still failed and the failure occurred during retrieval of existing metadata from the remote maven repository.

### PR DESCRIPTION
**Pull request by hdeadman**
Fixes  #27262

This changes the existing retry logic to use a Callable instead of a Runnable so there can be a return value. Then it uses the retry logic for the maven metadata download.

### CODE REVIEW

File: platforms/software/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/DependencyResolverIvyPublisher.java [hunk 1]
```diff
@@ -43,10 +45,11 @@ public void publish(IvyNormalizedPublication publication, IvyArtifactRepository
     }
 
     private void publish(IvyResolver publisher, IvyArtifact artifact, ModuleComponentArtifactMetadata artifactMetadata) {
-        networkOperationBackOffAndRetry.withBackoffAndRetry(new Runnable() {
+        networkOperationBackOffAndRetry.withBackoffAndRetry(new Callable<String>() {
             @Override
-            public void run() {
+            public String call() {
```
Comment (ov7a) [inline platforms/software/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/DependencyResolverIvyPublisher.java:50]: ❌ Please use `Void` instead of `String` here.

File: platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java [hunk 2]
```diff
@@ -273,10 +286,11 @@ private byte[] createChecksumFile(File src, HashFunction hashFunction) {
         }
 
         private void putResource(ExternalResourceName externalResource, ReadableContent readableContent) {
-            networkOperationRunner.withBackoffAndRetry(new Runnable() {
+            networkOperationCaller.withBackoffAndRetry(new Callable<String>() {
                 @Override
-                public void run() {
+                public String call() {
```
Comment (ov7a) [inline platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java:291]: ❌ Please use `Void` instead of `String` here.

**Review by ov7a — CHANGES_REQUESTED** [review]
Thank you for your contribution!

This PR is complete and simple enough.

***

While it would be nice, I don't think we need tests here: the retry method is covered by its own test, and the publishing process is covered by a functional test.

@hdeadman Please address the comments about the types below and fix the failing tests.

**Comment by hdeadman** [comment]
I fixed the return types to be Void instead of String. The failing test I saw said that internal API had to have the @NonNullApi annotation so I added the annotation to `AbstractMavenPublisher` and it's sub-classes, and adjusted some code based on that contract. I will try to run all the tests locally to see if there are more failing tests.

**Comment by hdeadman** [comment]
Looks like I need to fix the tests, lots of failing maven tests when I run locally so I will work on those.

**Comment by hdeadman** [comment]
`./gradlew :maven:quicktest -Dorg.gradle.ignoreBuildJavaVersionCheck=true` passed locally, and so did `InternalNullabilityTest` which failed before.

**Comment by hdeadman** [comment]
When I would run `./gradlew architecture-test:test -ParchunitRefreeze` it modified all the files in changes\archunit_store by adding a line feed at the end of the file, so I didn't notice that is was adding a few lines to one of the files. I just pushed that change so hopefully the `InternalNullabilityTest` will pass in CI?

File: platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenRemotePublisher.java [hunk 3]
```diff
@@ -49,7 +52,8 @@ public MavenRemotePublisher(Factory<File> temporaryDirFactory, BuildCommencedTim
     }
 
     @Override
-    public void publish(MavenNormalizedPublication publication, MavenArtifactRepository artifactRepository) {
+    public void publish(MavenNormalizedPublication publication, @Nullable MavenArtifactRepository artifactRepository) {
```
Comment (ov7a) [inline platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenRemotePublisher.java:55]: 🤔 That's weird. Why did you declare `artifactRepository` as Nullable to have an assert it being not null on the line below?

**Comment by ov7a** [comment]
> When I would run ./gradlew architecture-test:test -ParchunitRefreeze it modified all the files in changes\archunit_store by adding a line feed at the end of the file, so I didn't notice that is was adding a few lines to one of the files. I just pushed that change so hopefully the InternalNullabilityTest will pass in CI?

Extra empty lines are okay. These text files contain a list of exceptions - if you don't add any new exceptions, it's ok.

File: platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenRemotePublisher.java (hunk 3 above)
Comment (ov7a) [reply platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenRemotePublisher.java:55]: (sorry for the late reply)

Comment (hdeadman) [reply platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenRemotePublisher.java:55]: I had to add the `@NonNullApi` annotation at the class level because one of the CI tests (InternalNullabilityTest?) was failing if I didn't. Since the base `MavenPublisher` interface declares that parameter as `@Nullable`, I had to say it was `@Nullable` in order to make Intellij warning go away. I added the assertion because in this particular implementation of the `MavenPublisher` interface, the parameter cannot be null. Should I remove assert and let it NPE on the next line?

image

Comment (ov7a) [reply platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenRemotePublisher.java:55]: A-ha. Indeed, there is a problem with class hierarchy in that area. I don't think this should prevent this PR from merging. That being said, I think it's ok to merge this.

Thanks @hdeadman!

**Review by ov7a — APPROVED** [review]

**Comment by ov7a** [comment]
@bot-gradle merge
