### PR TITLE
Change a Kotlin source file in incremental Santa Tracker Kotlin performance tests

### LINKED ISSUE #13886: Use Kotlin source in Santa Tracker Kotlin Android performance tests
We currently make changes to a Java source file in the Santa Tracker Android test project's Kotlin variant:

https://github.com/gradle/gradle/blob/65137e91d64210f2c8de0b5a1d993a13376ec5a0/subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidTestProject.groovy#L64-L69

We should use a Kotlin file, and one in the `common` project instead, to better capture the effects on non-ABI changes. A good example could be [`AudioPlayer.kt`](https://github.com/gradle/santa-tracker-android/blob/fb6d5846b9062f17fd3077eb9584169d20e61c6b/common/src/main/java/com/google/android/apps/santatracker/AudioPlayer.kt).

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by lptr**
Fixes #13886

We shouldn't be changing a Java source file.

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test this please.

File: subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidTestProject.groovy [hunk 1]
```diff
@@ -64,7 +64,7 @@ class IncrementalAndroidTestProject extends AndroidTestProject {
     static final SANTA_TRACKER_KOTLIN = new IncrementalAndroidTestProject(
         templateName: 'santaTrackerAndroidBuild',
         memory: '1g',
-        pathToChange: 'snowballrun/src/main/java/com/google/android/apps/santatracker/doodles/snowballrun/BackgroundActor.java',
+        pathToChange: 'common/src/main/java/com/google/android/apps/santatracker/AudioPlayer.kt',
```
Comment (wolfs) [inline subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidTestProject.groovy:67]: That won't work since we are using `ApplyNonAbiChangeToJavaSourceFileMutator` in `configureForNonAbiChange`, which can only change Java files.

**Review by wolfs — CHANGES_REQUESTED** [review]

File: subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidTestProject.groovy (hunk 1 above)
Comment (lptr) [reply subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidTestProject.groovy:67]: Damn you're right.

**Comment by lptr** [comment]
@bot-gradle test this please.

File: subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidTestProject.groovy (hunk 1 above)
Comment (lptr) [reply subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidTestProject.groovy:67]: Should be good now.

**Review by wolfs — APPROVED** [review]
LGTM! Let's wait for the performance test coordinator to finish and check the results.
