### PR TITLE
Fix issue with changing environment variables and compiler daemon reuse

### LINKED ISSUE #25029: Worker Daemon is not reused on Mac OS
### Expected Behavior

I set the `keepAliveMode` to DAEMON and I expect Gradle to reuse the worker daemon when I compile Scala code. 

### Current Behavior

A new worker daemon is spawned each time (running Gradle at -info debug mode):

```
Starting process 'Gradle Worker Daemon 3'. Working directory: /Users/idragos/.gradle/workers Command: /Users/idragos/.asdf/installs/java/liberica-8u342+7/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/idragos/.gradle/caches/8.2-20230422130248+0000/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon 3'
Successfully started process 'Gradle Worker Daemon 3'
Started Gradle worker daemon (0.231 secs) with fork options DaemonForkOptions{executable=/Users/idragos/.asdf/installs/java/liberica-8u342+7/bin/java, minHeapSize=null, maxHeapSize=null, jvmArgs=[], keepAliveMode=DAEMON}.
Compiling with Zinc Scala compiler.
Prepared Zinc Scala inputs: 0.171 secs
compiling 1 Scala source to /Users/idragos/workspace/ge/build-agent-sbt/build/classes/scala/main ...
done compiling
Completed Scala compilation: 2.671 secs
```

Now I have a little army of them
```
❯ jps -l | grep Worker 
91401 worker.org.gradle.process.internal.worker.GradleWorkerMain
8778 worker.org.gradle.process.internal.worker.GradleWorkerMain
89484 worker.org.gradle.process.internal.worker.GradleWorkerMain
24016 worker.org.gradle.process.internal.worker.GradleWorkerMain
22422 worker.org.gradle.process.internal.worker.GradleWorkerMain
90463 worker.org.gradle.process.internal.worker.GradleWorkerMain
24806 worker.org.gradle.process.internal.worker.GradleWorkerMain
85167 worker.org.gradle.process.internal.worker.GradleWorkerMain
87348 worker.org.gradle.process.internal.worker.GradleWorkerMain
```

### Context (optional)

I attached a debugger and noticed that the environment variable that makes it incompatible is a synthetic one that changes name every time: `JAVA_MAIN_CLASS_4686 -> org.gradle.wrapper.GradleWrapperMain`

The name changes every time I invoke `gradlew`

It looks like this was a known thing, and Gradle [tries to fix it on Apple](https://github.com/gradle/gradle/blob/152c8c83b0491dfb809284398571429a99825eca/subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java#L405-L414), except that the [logic to detect Apple JVMs](https://github.com/gradle/gradle/blob/152c8c83b0491dfb809284398571429a99825eca/subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java#L64-L68) is a bit outdated.

### Steps to Reproduce

I'd rather provide the fix in a PR :)

### Gradle version

8.2-20230422130248+0000

### Build scan URL (optional)

_No response_

### Your Environment (optional)

```
------------------------------------------------------------
Gradle 8.2-20230422130248+0000
------------------------------------------------------------

Build time:   2023-04-22 13:02:48 UTC
Revision:     c7ab13564ebdb6bdddc33d71b1f28113250fe211

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.4 (BellSoft 17.0.4+8-LTS)
OS:           Mac OS X 13.2.1 aarch64
```

### PR DESCRIPTION
**Pull request by ghale**
Fixes #25029 
Supersedes #25035

This addresses the issue of changing environment variables by removing some of the vendor-specific handling that was in place and creating a set of known changing environment variables that will be ignored when checking JVM compatibility in _any_ JDK or operating system.  

The previous distinction between IBM vs Apple vs Other JVMs has started to lose meaning since the old IBM JVMs have evolved and can execute on Apple hardware now and have some of the same environment variables that need to be ignored.  
These environment variables are unlikely to be meaningful in any context, so now we just filter them out when checking JVM compatibility on any platform.  We do still need to understand if a JVM is IBM or not since there are differences in initial heap size and garbage collection mbean names, etc.

This PR also adds tests to validate the functionality of the switch in the Scala plugin that enables persistent compiler daemons.

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

**Comment by ghale** [comment]
@bot-gradle test this

File: subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java [hunk 1]
```diff
@@ -354,64 +340,29 @@ private File findToolsJar(File javaHome) {
...
-        AppleJvm(OperatingSystem os) {
-            super(os);
-        }
-
-        /**
-         * {@inheritDoc}
-         */
-        @Override
-        public File getToolsJar() {
-            return null;
```
Comment (jvandort) [inline subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java:398]: Is the behavior change here for `getToolJar` for apple JVMs significant?

**Review by jvandort — APPROVED** [review]

File: subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java (hunk 1 above)
Comment (ghale) [reply subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java:398]: I think this was a minor optimization because it was unlikely to exist on Apple JVMs.  I went ahead and made it so that once it looks for the tools jar once, it caches the "not found" value for subsequent calls.  This only gets called off of `Jvm.current()` in any production code, so this should only get calculated once (and then cached) which shouldn't have any noticeable impact.

File: subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java [hunk 2]
```diff
@@ -354,64 +340,29 @@ private File findToolsJar(File javaHome) {
...
-        }
-
-        @Override
-        public boolean isIbmJvm() {
-            return true;
+    public static Map<String, ?> getInheritableEnvironmentVariables(Map<String, ?> envVars) {
+        Map<String, Object> vars = new HashMap<String, Object>();
+        for (Map.Entry<String, ?> entry : envVars.entrySet()) {
+            // The following are known variables that can change between builds and should not be inherited
+            if (entry.getKey().matches("APP_NAME_\\d+")
```
[the remark this answers is not in the document]
Comment (ghale) [reply subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java]: Not a bad idea.  Done.

**Comment by ghale** [comment]
@bot-gradle test and merge

**Comment by dragos** [comment]
Thanks a lot for the quick fix!
