### PR TITLE
Broken symlinks should be valid in the inputs as well

### LINKED ISSUE #9904: Handle broken symlinks in inputs for incremental build
Continuing https://github.com/gradle/gradle/issues/9708 for inputs

When snapshotting we sometimes fail if we encounter a broken symlink.
We want to change this, and treat a broken symlink as if we encountered a missing file.
In an incremental build, if the broken symlink becomes a non-broken one (or vice versa), we consider that a change similar to changing a file into a directory.

* [x]  task that e.g. takes the name of broken symlinks in the inputs and writes them into a text file output or something

* [x] task's inputs containing broken symlink
  * [x] should succeed
  * [x] should be up-to-date without changes
  * [x] `@SkipWhenEmpty` should not change the broken symlink treatment
  * [x] when broken symlink is changed into non-broken, should be re-executed
    * [x] we need an incremental task variant of the test where we check that this change is properly reported as `ADDED` and `MODIFIED`

* [x] Add test that fails a task with a `@Classpath`/`@CompileClasspath` input containing
   * [x] a broken symlink as a root element
   * [x] a broken symlink as a .class file in a directory

* [ ] update documentation to reflect these changes

---
cc: @gradle/build-cache

### PR DESCRIPTION
**Pull request by paplorinc**
Fixes #9904

### CODE REVIEW

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildSymlinkHandlingIntegrationTest.groovy [hunk 1]
```diff
@@ -122,16 +122,13 @@ task work {
         result.assertTasksSkipped(":work")
     }
 
-    def "symlink may not reference missing input file"() {
+    def "symlink may reference missing input file"() {
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildSymlinkHandlingIntegrationTest.groovy]: An `@InputFile` is not allowed to reference an actually missing file, so I would say it isn't allowed to reference a broken symlink. If you want to test if symlinks are allowed as inputs, I think you should use `@InputFiles`, which does not do any validation.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java [hunk 2]
```diff
@@ -35,7 +38,11 @@ public void doValidate(String propertyName, Object value, TaskValidationContext
         public void doValidate(String propertyName, Object value, TaskValidationContext context) {
             File file = toFile(context, value);
             if (!file.exists()) {
-                context.visitError(String.format("File '%s' specified for property '%s' does not exist.", file, propertyName));
+                if (Files.isSymbolicLink(file.toPath())) {
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java]: Like stated in the test, I don't think we should change the validation. We should handle non-existing files and broken symlinks in the same way, so we need to fail here.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 3]
```diff
@@ -174,6 +174,47 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+        then:
+        executedAndNotSkipped ':inputBrokenLinkNameCollector'
+        output.text == "brokenInputDirectory brokenInputFile [brokenInputFile]"
+        outputContains "Directory '${brokenInputDirectory}' specified for property 'brokenInputDirectory' is a broken symbolic link."
+        outputContains "File '${brokenInputFile}' specified for property 'brokenInputFile' is a broken symbolic link."
+
+        when:
+        run 'inputBrokenLinkNameCollector'
+        then:
+        skipped ':inputBrokenLinkNameCollector'
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Test for changes to the brokenness of the symlinks are missing: So if a symlink is unbroken, then the task needs to be out of date.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java [hunk 4]
```diff
@@ -46,7 +53,11 @@ public void doValidate(String propertyName, Object value, TaskValidationContext
         public void doValidate(String propertyName, Object value, TaskValidationContext context) {
             File directory = toDirectory(context, value);
             if (!directory.exists()) {
-                context.visitError(String.format("Directory '%s' specified for property '%s' does not exist.", directory, propertyName));
+                if (Files.isSymbolicLink(directory.toPath())) {
```
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java]: a broken symlink returns false for `.exists()`, see the test assertions: https://github.com/gradle/gradle/pull/9909/files#diff-6883ad77d490d662e593994e49b90a33R202

[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java]: Yeah, I wanted to delete the comment before submitting the review 🤦‍♂

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java (hunk 2 above)
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java]: Hmm, did I misunderstand what @lptr requested here?

Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java]: What is it that @lptr requested? Today we talked about using `@InputFiles` instead of `@InputFile` since we shouldn't need to adjust the validation. Do I remember that correctly?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 3 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Wanted to handle incremental stuff in a different PT, but can do it here as well

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildSymlinkHandlingIntegrationTest.groovy (hunk 1 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildSymlinkHandlingIntegrationTest.groovy]: Reverted

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java (hunk 2 above)
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java]: Thanks for clarifying, reverted the change, kept only the passing test

**Comment by paplorinc** [comment]
Please re-review, as discussed, I've removed invalid assumptions from the commit history.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 5]
```diff
@@ -174,6 +174,57 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
         outputDirectory.list() == [input.name]
     }
 
+    @Issue('https://github.com/gradle/gradle/issues/9904')
+    def "task with broken symlink in inputs are valid"() {
+        def inputDirectoryWithBrokenLink = file('inputDirectoryWithBrokenLink').createDir()
+        def inputFileTarget = file("brokenInputFileTarget")
+        def inputFile = inputDirectoryWithBrokenLink.file('brokenInputFile').createLink(inputFileTarget)
+        def output = file("output.txt").createFile()
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Let's not create the output file before the task executed. The task should create the output file.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 6]
```diff
@@ -174,6 +174,57 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+
+        // Validation fails with broken links assigned directly to `@InputDirectory` or `@InputFile`
+        buildFile << """
+            class CustomTask extends DefaultTask {                
+                @InputFiles FileCollection brokenInputFile
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: How about `brokenInputFiles`?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 7]
```diff
@@ -174,6 +174,57 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+            task inputBrokenLinkNameCollector(type: CustomTask) {
+                inputDirectoryWithBrokenLink = file '${inputDirectoryWithBrokenLink}'
+                brokenInputFile = files '${inputFile}'
+                output = file '${output}'
+            }
+        """
+        assert inputDirectoryWithBrokenLink.exists() && !inputFile.exists() && output.text.empty
+
+        when:
+        run 'inputBrokenLinkNameCollector', '--info'
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Why do you use `--info` here?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 8]
```diff
@@ -174,6 +174,57 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+        executedAndNotSkipped ':inputBrokenLinkNameCollector'
+        output.text == "[brokenInputFile] inputDirectoryWithBrokenLink [brokenInputFile]"
+
+        when:
+        run 'inputBrokenLinkNameCollector'
+        then:
+        skipped ':inputBrokenLinkNameCollector'
+
+        when:
+        inputFileTarget.createFile()
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: We currently don't know if the change is caused by something detected in the file collection or in the input directory. We should probably change both things separately or have separate tests for each of the cases. A `where` clause would probably work good here.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 5 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Done

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 6 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Done

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 7 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Don't need it anymore, thanks

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 8 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Valid concerns, separated via `where`

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 9]
```diff
@@ -223,6 +203,51 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
         then:
         skipped ':inputBrokenLinkNameCollector'
+
+        where:
+        type             | createBuildFile
+        'InputDirectory' | taskWithInputFiles
+        'InputFiles'     | taskWithInputDirectory
+    }
+
+    static taskWithInputFiles = { AbstractIntegrationSpec context, TestFile inputFileTarget, TestFile output ->
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Those static closures make the test harder to read for me. Maybe creating two tests and having some duplication is better? WDYT?

Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: done

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 10]
```diff
@@ -174,6 +178,222 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+        def inputFileTarget = file("brokenInputFileTarget")
+        def brokenInputFile = file('brokenInputFile').createLink(inputFileTarget)
+        def output = file("output.txt")
+
+        buildFile << """
+            class CustomTask extends DefaultTask {
+
+                @InputFiles FileCollection brokenInputFiles
+
+                @SkipWhenEmpty @InputFiles FileCollection brokenInputFilesWithSkip
```
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: that a collection only containing missing files is not considered empty.
Is that not why you've recommended testing this case?

[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: I think the `SkipEmptySourceFilesTaskExecuter` failed when trying to list broken symlinks in a directory which was annotated with `SkipWhenEmpty`. We should test this, though in a separate test.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 11]
```diff
@@ -174,6 +178,222 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+
+    @PendingFeature
+    @Issue('https://github.com/gradle/gradle/issues/9904')
+    def "fails task with a #classpathType.simpleName File input"() {
+        def brokenInputFile = file('BrokenInputFile.class').createLink("BrokenInputFile.target")
+        def output = file("output.txt")
+
+        buildFile << """
+            class CustomTask extends DefaultTask {
+                @${classpathType.name} File brokenInputFile
```
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Good to know, fixed

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 12]
```diff
@@ -174,6 +178,222 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+        run 'inputBrokenLinkNameCollector'
+        then:
+        executedAndNotSkipped ':inputBrokenLinkNameCollector'
+        output.text == "${[MODIFIED]}"
+    }
+
+    @PendingFeature
+    @Issue('https://github.com/gradle/gradle/issues/9904')
+    def "fails task with a #classpathType.simpleName FileCollection input"() {
+        def brokenInputFile = file('BrokenInputFile.class').createLink("BrokenInputFile.target")
```
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Please see if this is resolved now

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 13]
```diff
@@ -174,6 +178,222 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+                brokenInputFiles = files '${brokenInputFile}'
+                output = file '${output}'
+            }
+        """
+        assert !brokenInputFile.exists()
+
+        when:
+        run 'brokenClasspathInput'
+        then:
+        fails ':brokenClasspathInput'
```
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Done

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 10 above)
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Removed, will add it back in a later commit

File: subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java [hunk 14]
```diff
@@ -154,6 +155,8 @@ public void visitFile(FileSystemLocationSnapshot fileSnapshot) {
                 if (normalizedContent != null) {
                     delegate.visit(fileSnapshot, normalizedContent);
                 }
+            } else if (!relativePathSegmentsTracker.isRoot()) {
+                throw new GradleException(String.format("Could not list contents of '%s'. Couldn't follow symbolic link.", fileSnapshot.getAbsolutePath()));
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java]: This could also be an unavailable file, right? Maybe this would be the right place to check if the file is a symbolic link or an unavailable file? Or we leave it as you have now.

Regarding `Could not list contents of`: the snapshot is not a directory, why are you saying that we couldn't list the contents of it. Maybe `Could not read contents of `. That would be true for unreadable files and broken symlinks, right?

WDYT?

Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java]: I wanted to align it with previous behavior, i.e. https://github.com/gradle/gradle/blob/3903e8fbbc8893fe16c12709dff0f79850425b81/subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java#L99 and https://github.com/gradle/gradle/blob/master/subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/DefaultDirectoryWalker.java#L111

It's not a directory there either, I'll fix the message in those cases as well, okay?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 10 above)
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: @wolfs, could we quickly pair on this tomorrow, I'm not sure what the intent is exactly (i.e. how can the input be empty and still contain elements, if not like this)

File: subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java (hunk 14 above)
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java]: Done

File: subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java [hunk 15]
```diff
@@ -150,13 +151,15 @@ public boolean preVisitDirectory(DirectorySnapshot directorySnapshot) {
 
         @Override
         public void visitFile(FileSystemLocationSnapshot fileSnapshot) {
-            if (fileSnapshot.getType() == FileType.RegularFile) {
+            if (fileSnapshot instanceof RegularFileSnapshot) {
                 HashCode normalizedContent = fingerprintFile((RegularFileSnapshot) fileSnapshot);
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java]: we're casting to it anyway

File: subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java [hunk 16]
```diff
@@ -150,13 +151,15 @@ public boolean preVisitDirectory(DirectorySnapshot directorySnapshot) {
...
                 if (normalizedContent != null) {
                     delegate.visit(fileSnapshot, normalizedContent);
                 }
-            } else if (!relativePathSegmentsTracker.isRoot()) {
-                throw new GradleException(String.format("Couldn't follow symbolic link '%s'.", fileSnapshot.getAbsolutePath()));
+            } else if (fileSnapshot instanceof MissingFileSnapshot) {
+                if (!relativePathSegmentsTracker.isRoot() && ((MissingFileSnapshot) fileSnapshot).isSymbolicLink()) {
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java]: calling `isSymbolicLink` only if every other check fails, since it's expensive

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java [hunk 17]
```diff
@@ -49,4 +53,11 @@ public boolean isContentAndMetadataUpToDate(FileSystemLocationSnapshot other) {
     public void accept(FileSystemSnapshotVisitor visitor) {
         visitor.visitFile(this);
     }
+
+    public boolean isSymbolicLink() {
+        if (isSymbolicLink == null) {
```
Comment (paplorinc) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java]: don't think we need synchronization here, right?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 18]
```diff
@@ -356,16 +352,16 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
         where:
         classpathType << [Classpath, CompileClasspath]
     }
 
-    @PendingFeature
     @Issue('https://github.com/gradle/gradle/issues/9904')
-    def "fails task with a #classpathType.simpleName File input"() {
-        def brokenInputFile = file('BrokenInputFile.class').createLink("BrokenInputFile.target")
+    def "task with a broken #classpathType.simpleName directory input is accepted"() {
+        def classes = file('classes').createDir()
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: does the folder name actually matter here?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 19]
```diff
@@ -174,6 +177,213 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+        then:
+        executedAndNotSkipped ':inputBrokenLinkNameCollector'
+
+        when:
+        run 'inputBrokenLinkNameCollector'
+        then:
+        skipped ':inputBrokenLinkNameCollector'
+    }
+
+    // Validation fails with broken links assigned directly to `@InputFile`
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: I am not sure these comments provide an additional value. Let's add a test for the behaviour (if we already don't have one) and remove the comment.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 20]
```diff
@@ -174,6 +177,213 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+
+    @Issue('https://github.com/gradle/gradle/issues/9904')
+    def "task with a broken #classpathType.simpleName directory input is accepted"() {
+        def classes = file('classes').createDir()
+        def brokenInputFile = classes.file('BrokenInputFile.class').createLink("BrokenInputFile.target")
+        def output = file("output.txt")
+
+        buildFile << """
+            class CustomTask extends DefaultTask {
+                @${classpathType.name} File brokenInputFile
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: It is a little bit surprising for me that the classpath property is called `brokenInputFile`, which the `brokenInputFile` variable above points to a file in the `classes` directory. Maybe this property would better be called `classes` or `classpath`?

File: subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java (hunk 16 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java]: Why don't we fail if the missing file is not a symbolic link? If it is not a symbolic link, then it is an unreadable file. We should fail in that case as well.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java [hunk 21]
```diff
@@ -49,4 +53,11 @@ public boolean isContentAndMetadataUpToDate(FileSystemLocationSnapshot other) {
     public void accept(FileSystemSnapshotVisitor visitor) {
         visitor.visitFile(this);
     }
+
+    public boolean isSymbolicLink() {
```
Comment (wolfs) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java]: We don't need to check for symbolic links except for better error messages. And if it is only for error messages, then we don't need to cache the result. I think the `isSymbolicLink()` should not be on `MissingFileSnapshot`, but when we create an error message we either do it in a general way (`cannot read file ...`) or distinguish between the different kinds there.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 18 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: I does not. It still makes sense to have a nice one.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java (hunk 17 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java]: We don't.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 12 above)
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: It is not. The broken input file should not be called `.class` but either `.jar` or without extension (i.e. a classes directory).

[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: So how would one reference a `.class` file directly in a `@Classpath`?

[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: You can't. Why do you want to do that? You can reference a `.jar` file directly in a `@Classpath`, though. And I think that is what this test is about.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java (hunk 21 above)
Comment (paplorinc) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java]: Reverted: As discussed, we won't yet differentiate between unreadable files in error messages during classpath scanning

File: subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java (hunk 16 above)
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java]: Reworded the error

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 20 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Renamed

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 19 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Added tests for the two cases

File: subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java (hunk 16 above)
Comment (paplorinc) [reply subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java]: Reverted

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 10 above)
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Added testcase

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java (hunk 21 above)
Comment (paplorinc) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java]: Reverted

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 12 above)
[the remark this answers is not in the document]
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Thanks, indeed, direct file reference was only added in [JDK11](https://openjdk.java.net/jeps/330), before that it didn't make sense to include a single file on a classpath.

**Comment by paplorinc** [comment]
Merged, thank you for your reviews and patience :)
