### PR TITLE
Ensure BuildOperationQueue will progress without extra leases

### LINKED ISSUE #37613: Possible deadlock with workers and included builds
### Current Behavior

Following the changes in #36897, there seem to be a path for Gradle to deadlock when assigning work to workers.

### Expected Behavior

Gradle should not deadlock

### Context (optional)

AI Analysis of the deadlock:

```
Here are the relevant thread stacks from the deadlock, annotated by role:

  ---
  1. Thread 9 — holds cache lock, waiting for build-op workers

  "included builds Thread 9" #306 elapsed=177.17s
     WAITING (parking)
          at DefaultBuildOperationQueue.waitForWorkToComplete(DefaultBuildOperationQueue.java:178)    ← waiting for shading work items
          at DefaultWorkerLeaseService.withoutLocksBlocking(DefaultWorkerLeaseService.java:385)       ← released its worker lease
          at DefaultWorkerLeaseService.blocking(DefaultWorkerLeaseService.java:234)
          at DefaultBuildOperationQueue.waitForWorkToComplete(DefaultBuildOperationQueue.java:172)
          at DefaultBuildOperationExecutor.runAll(DefaultBuildOperationExecutor.java:73)
          at RuntimeShadedJarCreator.processFiles(RuntimeShadedJarCreator.java:119)                   ← shading gradle-api JAR
          at RuntimeShadedJarCreator.createFatJar(RuntimeShadedJarCreator.java:108)
          at RuntimeShadedJarFactory$1.run(RuntimeShadedJarFactory.java:81)
          at DefaultGeneratedGradleJarCache.get(DefaultGeneratedGradleJarCache.java:45)               ← inside cache lock
          at DefaultCacheCoordinator.useCache(DefaultCacheCoordinator.java:262)                       ← HOLDS cache lock
          at RuntimeShadedJarFactory.get(RuntimeShadedJarFactory.java:70)
          at DependencyClassPathNotationConverter.relocatedDepsJar(...)
          at ParallelResolveArtifactSet$VisitingSet$StartVisitAction.execute(...)

  Thread 9 holds the DefaultCacheCoordinator lock for DefaultGeneratedGradleJarCache, is inside RuntimeShadedJarCreator.processFiles which calls runAll to shade JAR entries in
  parallel. runAll → waitForWorkToComplete releases its worker lease via withoutLocksBlocking and waits for the build operation workers to finish.

  ---
  2. "Build operations" threads — need worker leases to run the shading work

  "Build operations" #268 elapsed=180.50s
     WAITING (on object monitor)
          at DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:109)
          at DefaultWorkerLeaseService.acquireLocks(DefaultWorkerLeaseService.java:297)               ← can't acquire worker lease
          at DefaultWorkerLeaseService.releaseWorkerLeaseAndWaitFor(DefaultWorkerLeaseService.java:476)
          at DefaultWorkerLeaseService.acquireLocksWithoutWorkerLeaseWhileBlocked(DefaultWorkerLeaseService.java:465)
          at DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:129)
          at DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:287)   ← trying to pick up shading work

  "Build operations Thread 2" has the identical stack. These are the workers that would process Thread 9's shading work items, but they can't acquire worker leases because all 3
  slots (--max-workers=3) are occupied.

  ---
  3. Threads 2 & 3 — hold worker leases, blocked on cache lock

  "included builds Thread 2" #297 elapsed=177.17s
     WAITING (parking)
          at DefaultCacheCoordinator.takeOwnership(DefaultCacheCoordinator.java:286)                  ← BLOCKED on cache lock
          at DefaultCacheCoordinator.useCache(DefaultCacheCoordinator.java:251)
          at DefaultGeneratedGradleJarCache.get(DefaultGeneratedGradleJarCache.java:45)
          at RuntimeShadedJarFactory.get(RuntimeShadedJarFactory.java:70)
          at DependencyClassPathNotationConverter.relocatedDepsJar(...)
          ...task execution pipeline...
          at DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:129)          ← HOLDS worker lease
          at DefaultBuildController.doRun(DefaultBuildController.java:182)

  Thread 3 has the same stack. Both hold a worker lease (acquired via runAsWorkerThread at DefaultBuildController.doRun) and are blocked at DefaultCacheCoordinator.takeOwnership
  waiting for the cache lock that Thread 9 holds.

  ---
  4. Threads 4-8, 10 — waiting for worker leases to even start

  "included builds Thread 4" #299 elapsed=177.17s
     WAITING (on object monitor)
          at DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:109)
          at DefaultWorkerLeaseService.acquireLocks(DefaultWorkerLeaseService.java:297)
          at DefaultWorkerLeaseService.releaseWorkerLeaseAndWaitFor(DefaultWorkerLeaseService.java:476)
          at DefaultWorkerLeaseService.acquireLocksWithoutWorkerLeaseWhileBlocked(DefaultWorkerLeaseService.java:465)
          at DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:129)
          at DefaultBuildController.doRun(DefaultBuildController.java:182)                            ← included build hasn't started

  Threads 5, 6, 7, 8, and 10 all have this identical stack — 7 threads waiting in acquireLocksWithoutWorkerLeaseWhileBlocked to get a worker lease so they can start their included
  build.

  ---
  The Cycle

  Thread 9 (holds CACHE LOCK, released worker lease)
    └→ waits for "Build operations" threads to finish shading work
         └→ "Build operations" threads need WORKER LEASES (all 3 taken)
              └→ Threads 2 & 3 hold 2 of 3 WORKER LEASES
                   └→ blocked on CACHE LOCK (held by Thread 9)  ← DEADLOCK

  The 3rd worker lease is held by Thread 9's included build context (it was released by the blocking() call inside waitForWorkToComplete, but threads 2/3 already held theirs before
  that release could help). Meanwhile threads 4-10 are starved — no leases will ever free up.
```

AI suggest that the regression is likely introduced by the following change #36897 that was merged on March 16:

```
 There it is. Here's the key change visible in the thread dump:

  runBatch (line 287) now calls workerLeases.runAsWorkerThread(...) — meaning each build operation worker thread must acquire a worker lease before it can execute any work item:

  private void runBatch(final T firstOperation) {
      int operationsExecuted;
      if (context.requiresWorkerLease()) {
          operationsExecuted = workerLeases.runAsWorkerThread(() -> executePendingWork(firstOperation));  // ← NEW: needs worker lease
      } else {
          operationsExecuted = executePendingWork(firstOperation);
      }
      completeOperations(operationsExecuted);
  }

  This is the change from PR #36897 — "Implement WorkerThreadPool for DefaultBuildOperationQueue", merged 2026-03-16.

  What changed

  Before: DefaultBuildOperationQueue worker threads ran work items directly — they did not need a worker lease to process batched operations. The thread pool was bounded by
  maxConcurrency but didn't participate in the worker lease system.

  After: WorkerRunnable.runBatch() wraps execution in workerLeases.runAsWorkerThread(...), which must acquire a worker lease from the shared pool (capped at --max-workers). This is
  the stack visible in the "Build operations" threads:

  at DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:129)
  at DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:287)

  Additionally, waitForWorkToComplete now releases the caller's worker lease via withoutLocksBlocking:

  at DefaultWorkerLeaseService.withoutLocksBlocking(DefaultWorkerLeaseService.java:385)
  at DefaultWorkerLeaseService.blocking(DefaultWorkerLeaseService.java:234)
  at DefaultBuildOperationQueue.waitForWorkToComplete(DefaultBuildOperationQueue.java:172)

  Why this creates the deadlock

  With --max-workers=3 and 10 included builds:

  1. Thread 9 holds a cache lock and calls runAll → waitForWorkToComplete, which releases its lease
  2. But runAll's worker threads now need a worker lease via runBatch → runAsWorkerThread
  3. Threads 2 & 3 already hold 2 of the 3 leases, and they're blocked on the cache lock Thread 9 holds
  4. Thread 9's released lease is the 3rd, but it gets picked up by one of threads 4-10 (or the build-op workers can't acquire it due to ordering) — either way, the build-op workers
   never get a lease

  The PR description even hints at the intent: "if we can start using blocking for build cache I/O work then it will allow it to perform more concurrent work" — but the interaction
  with DefaultCacheCoordinator's exclusive lock + composite builds with many included builds wasn't considered.
```

### Self-contained Reproducer Project

A test in a private repository

### Gradle version

9.5.0 RC3

### Gradle version that used to work

9.4.1

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #37613

This is an alternative to reverting #36952.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by octylFractal** [comment]
@bot-gradle test QF

File: subprojects/core/src/test/groovy/org/gradle/internal/operations/DefaultBuildOperationQueueTest.groovy [hunk 1]
```diff
@@ -275,6 +277,59 @@ class DefaultBuildOperationQueueTest extends Specification {
...
+            1,
+            true
+        )
+        operationQueue = new DefaultBuildOperationQueue(false, workerRegistry, executionContext, recordingWorker, null)
+
+        when:
+        operationQueue.add(new Success())
+
+        and:
+        // Wait until the worker has polled the op and is about to block on the lease.
```
Comment (ghale) [inline subprojects/core/src/test/groovy/org/gradle/internal/operations/DefaultBuildOperationQueueTest.groovy]: 💅 The order is different now:
```suggestion
        // Wait until the worker is about to block on the lease and poll for the op
```

**Review by ghale — APPROVED** [review]
LGTM.  One minor issue with a comment if you want to fix it, but it's not a blocking issue at all.

File: subprojects/core/src/test/groovy/org/gradle/internal/operations/DefaultBuildOperationQueueTest.groovy (hunk 1 above)
Comment (octylFractal) [reply subprojects/core/src/test/groovy/org/gradle/internal/operations/DefaultBuildOperationQueueTest.groovy]: I adjusted this wording to remove the mention of polling entirely.

**Comment by octylFractal** [comment]
@bot-gradle test this
