### PR TITLE
Make `DefaultServiceRegistry.OwnServices` partially thread-safe

### LINKED ISSUE #35385: Thread-unsafe code in DefaultServiceRegistry$OwnServices leads to CME
### Current Behavior

A CME occurs occasionally in this class, see this scan from our build: https://ge.gradle.org/s/b7uxt7lw6ckws/failures?expanded-stacktrace=WyIwLTEiXQ#1

### Expected Behavior

No CME should occur.

### Context (optional)

Failed to run a build locally while doing normal work.

This doesn't seem to be a regression as the relevant code hasn't been touched in a while.

This should be fixable by just making `lifecycleHandlers` a `CopyOnWriteArrayList`, if it's indeed low-write high-read like I think it is.

### Self-contained Reproducer Project

I don't know if I can make one of these as the issue is a race condition I only got lucky to hit. The fix seems obvious regardless.

### Gradle version

9.2.0-rc-2

### Build scan URL (optional)

https://ge.gradle.org/s/b7uxt7lw6ckws

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by bamboo**
By serializing the related state transitions of `services` and `lifecycle handlers` via an atomic reference.

Operations on `OwnServices#providersByType` remain thread-unsafe and will be dealt with in a subsequent PR.

Resolves #35385

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test RFN

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java [hunk 1]
```diff
@@ -461,8 +460,8 @@ public void add(SingletonService serviceProvider) {
             assertMutable();
             stoppable.add(serviceProvider);
             collectProvidersForClassHierarchy(inspector, serviceProvider.getDeclaredServiceTypes(), serviceProvider);
```
Comment (alllex) [inline platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:462]: ❓ The change fixes the services list update, but the `providersByType` update remains unsynchronized.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java [hunk 2]
```diff
@@ -518,9 +517,11 @@ public void instanceRealized(List<Class<?>> declaredServiceTypes, Supplier<Strin
         }
 
         void annotationHandlerCreated(AnnotatedServiceLifecycleHandler annotationHandler) {
-            lifecycleHandlers.add(annotationHandler);
-            for (SingletonService candidate : services) {
-                notifyAnnotationHandler(annotationHandler, candidate);
+            ServicesSnapshot snapshot = services.updateAndGet(it -> it.addLifecycleHandler(annotationHandler));
+            @Nullable ServiceList list = snapshot.services;
```
Comment (alllex) [inline platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java]: 💅 IntelliJ says that Nullable annotations on local variables are not applicable. Do we need to keep it here?

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java [hunk 3]
```diff
@@ -1417,4 +1418,47 @@ private boolean locateAnnotation(Class<? extends Annotation> annotation) {
             }
         }
     }
+
+    static class ServicesSnapshot {
```
Comment (alllex) [inline platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java]: 💅 Class visibility can be private

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java [hunk 4]
```diff
@@ -393,8 +393,7 @@ public void visit(Service service) {
     private class OwnServices implements ServiceProvider {
         private final Map<Class<?>, List<ServiceProvider>> providersByType = new HashMap<Class<?>, List<ServiceProvider>>(16, 0.5f);
         private final CompositeStoppable stoppable = CompositeStoppable.stoppable();
-        private final List<SingletonService> services = new ArrayList<SingletonService>();
-        private final List<AnnotatedServiceLifecycleHandler> lifecycleHandlers = new ArrayList<AnnotatedServiceLifecycleHandler>();
+        private final AtomicReference<ServicesSnapshot> services = new AtomicReference<>(ServicesSnapshot.EMPTY);
```
Comment (asodja) [inline platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:396]: 🤔 An alternative approach with similar behaviour could be to use Java's `ConcurrentLinkedQueue` for `services` and `lifecycleHandlers`. With that we could avoid having extra `ServicesSnapshot` class and keep the same structure

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java [hunk 5]
```diff
@@ -1417,4 +1418,47 @@ private boolean locateAnnotation(Class<? extends Annotation> annotation) {
             }
         }
     }
+
+    static class ServicesSnapshot {
+        static final ServicesSnapshot EMPTY = new ServicesSnapshot(null, new AnnotatedServiceLifecycleHandler[0]);
+
+        final @Nullable ServiceList services;
+        final AnnotatedServiceLifecycleHandler[] lifecycleHandlers;
```
Comment (asodja) [inline platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:1435]: ❓  Why we use `ServiceList` for services but we use arrays and `copy-on-write` for `lifecycleHandlers`?

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java [hunk 6]
```diff
@@ -518,9 +517,11 @@ public void instanceRealized(List<Class<?>> declaredServiceTypes, Supplier<Strin
         }
 
         void annotationHandlerCreated(AnnotatedServiceLifecycleHandler annotationHandler) {
-            lifecycleHandlers.add(annotationHandler);
-            for (SingletonService candidate : services) {
-                notifyAnnotationHandler(annotationHandler, candidate);
+            ServicesSnapshot snapshot = services.updateAndGet(it -> it.addLifecycleHandler(annotationHandler));
+            @Nullable ServiceList list = snapshot.services;
+            while (list != null) {
```
Comment (Pankraz76) [inline platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:522]: would like to consider raw recursion up front to point this **delicacy** out. this woud wipe out the nullable as this is the start param to start it.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 4 above)
Comment (asodja) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:396]: Although thinking about it more, it's not obvious that using `ConcurrentLinkedQueue` will result in correct behaviour if we add a service and a lifecycleHandler concurrently

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java [hunk 7]
```diff
@@ -461,8 +460,8 @@ public void add(SingletonService serviceProvider) {
             assertMutable();
             stoppable.add(serviceProvider);
             collectProvidersForClassHierarchy(inspector, serviceProvider.getDeclaredServiceTypes(), serviceProvider);
-            services.add(serviceProvider);
-            for (AnnotatedServiceLifecycleHandler annotationHandler : lifecycleHandlers) {
+            ServicesSnapshot snapshot = services.updateAndGet(it -> it.addService(serviceProvider));
+            for (AnnotatedServiceLifecycleHandler annotationHandler : snapshot.lifecycleHandlers) {
```
Comment (Pankraz76) [inline platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:464]:
```suggestion
            for (AnnotatedServiceLifecycleHandler annotationHandler : snapshot.services.updateAndGet(it -> it.addService(serviceProvider))) {
```
could inline to keep high cohesion promise reduce coupling context. Considering snapshot service will probably provide some snapshot.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 4 above)
Comment (Pankraz76) [inline platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:396]:
```suggestion
        private final AtomicReference<ServicesSnapshot> services = new AtomicReference<>(EMPTY);
```
having ServicesSnapshot already read in first part, again cohesion low coupling.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 5 above)
Comment (bamboo) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:1435]: There are at most 3 lifecycle handler instances per registry and they are iterated on frequently (for every registration).

There are many more services and they are written a lot but iterated very rarely (3 times at most).

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 4 above)
Comment (bamboo) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:396]: > Although thinking about it more, it's not obvious that using `ConcurrentLinkedQueue` will result in correct behaviour if we add a service and a lifecycleHandler concurrently

Yes. That setup could violate the "once-and-only-once" contract for `AnnotatedServiceLifecycleHandler#whenRegistered`.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 2 above)
Comment (bamboo) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java]: I tend to think of `@Nullable` as part of the type declaration, even if the tooling won't help, it seems more precise to me.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 1 above)
Comment (bamboo) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:462]: Indeed. I focused on the concrete reports but I agree it would be better and more reassuring to have complete thread-safety. 

I'll reassess my solution.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 3 above)
Comment (Pankraz76) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java]: could leverage prone to have this automate giving freedom and security at once.

- https://errorprone.info/bugpattern/EffectivelyPrivate

like how many effort have you invested and want to increase in the future on this topic, or kind of fix this global. This is kind of the real question in general, imho.

sorry should have checked before, discovered:

Still it could be reconsidered, if its easy to fix. (default) Scope private is next to immutability (final), a good thing to have for robust software, avoiding to much envy and side effects.

- https://github.com/gradle/gradle/blob/1757939b3bb4bebb6a854ea775db5040244df746/build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.code-quality.gradle.kts#L57

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 2 above)
Comment (alllex) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java]: I would agree if the tooling stayed neutral, but IDEA highlights the `@Nullable` in yellow, making me think there is a problem, where there is none. So tooling is actually actively "unhelpful".

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 5 above)
Comment (mlopatkin) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:1435]: > There are at most 3 lifecycle handler instances per registry and they are iterated on frequently (for every registration).
> 
> There are many more services and they are written a lot but iterated very rarely (3 times at most).

I stumbled upon this as well, so this should be probably a comment.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java [hunk 8]
```diff
@@ -1417,4 +1418,47 @@ private boolean locateAnnotation(Class<? extends Annotation> annotation) {
...
+
+        private static AnnotatedServiceLifecycleHandler[] append(AnnotatedServiceLifecycleHandler[] array, AnnotatedServiceLifecycleHandler annotationHandler) {
+            AnnotatedServiceLifecycleHandler[] newArray = new AnnotatedServiceLifecycleHandler[array.length + 1];
+            System.arraycopy(array, 0, newArray, 0, array.length);
+            newArray[array.length] = annotationHandler;
+            return newArray;
+        }
+    }
+
+    static class ServiceList {
```
Comment (mlopatkin) [inline platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java]: 🤔 Why not use a [PersistentList](https://github.com/gradle/gradle/blob/HEAD/platforms/core-runtime/functional/src/main/java/org/gradle/internal/collect/PersistentList.java)?

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 3 above)
Comment (mlopatkin) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java]: >could leverage prone to have this automate giving freedom and security at once.

AFAIK, this diagnostic goes in other direction: it complains about public stuff on private classes, so it won't help here.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 2 above)
Comment (mlopatkin) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java]: >I would agree if the tooling stayed neutral, but IDEA highlights the @Nullable in yellow, making me think there is a problem, where there is none. So tooling is actually actively "unhelpful".

FWIW, JSpecify folks explicitly advice against nullness annotations on local variables: https://jspecify.dev/docs/user-guide/#local-variables. I don't know the motivation, perhaps they wanted to reduce visual clutter.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 5 above)
Comment (bamboo) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:1435]: > I stumbled upon this as well, so this should be probably a comment.

Will do.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 8 above)
Comment (bamboo) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java]: The `functional` module is currently not available in workers. In its current form it'd also bring `guava` and `fastutil` dependencies so I thought a custom node class was a good compromise.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 2 above)
Comment (bamboo) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java]: Ok.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 1 above)
Comment (bamboo) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:462]: @alllex any objection to extending the solution to `providersByType` in a subsequent PR?

**Review by bamboo — COMMENTED** [review]
Thanks for the feedback. Applied.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 1 above)
Comment (alllex) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:462]: No objection, but then we should update the PR name to note that this is only a partial thread-safety fix, and add a note to the PR description on what is still missing.

**Comment by bamboo** [comment]
> If we merge this as is, we should update the PR name and description to clarify this.

Done.

File: platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java (hunk 1 above)
Comment (alllex) [reply platforms/core-runtime/service-registry-impl/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java:462]: For posterity, this is a follow-up issue that was eventually addressed:
- https://github.com/gradle/gradle/issues/35923
