### PR TITLE
Report JVM information in --version and buildEnvironment

### LINKED ISSUE #29101: Report JVM information for Gradle daemon
### Expected Behavior

It should be easy to understand which version of Java may be used to run a build.

### Current Behavior (optional)

_No response_

### Context

`gradle -v` reports the _current_ JVM used.  This is often the same one used by the daemon, but this can be influenced by two different things:
- `org.gradle.java.home` can specify a completely different Java home to be used by the daemon
- Daemon JVM criteria 

Additionally, once the build is started, there is no easy way to see the actual JVM used to run the build.  This is useful for diagnosing problems caused by running a build with the wrong (or unexpected) version of Java.

Some suggestions:
- Make `gradle -v` report the value of `org.gradle.java.home` or the JVM criteria when set.
- Make `gradle buildEnvironment` or similar task report information about the build's actual JVM

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #29101

### CODE REVIEW

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

File: subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/BuildEnvironmentReportTaskIntegrationTest.groovy [hunk 1]
```diff
@@ -15,12 +15,30 @@
...
+        then:
+        // Not asserting over the exact output, just that important info is printed
+        JvmVendor currentVendor = JvmVendor.fromString(StandardSystemProperty.JAVA_VM_VENDOR.value())
+        output.matches(
+            "(\n|.)*Build JVM: ${Pattern.quote(currentVendor.displayName)} .*${Pattern.quote(StandardSystemProperty.JAVA_VM_VERSION.value())}.*\\n" +
+                ".*Location:\\s+${Pattern.quote(StandardSystemProperty.JAVA_HOME.value())}.*\\n" +
+                ".*Language Version:\\s+${Jvm.current().javaVersionMajor}.*\\n" +
+                ".*Vendor:\\s+${Pattern.quote(currentVendor.displayName)}.*\\n" +
+                ".*Architecture:\\s+${Pattern.quote(StandardSystemProperty.OS_ARCH.value())}.*\\n" +
+                ".*Is JDK:\\s+${Jvm.current().jdk}.*(\\n|.)*"
```
Comment (big-guy) [inline subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/BuildEnvironmentReportTaskIntegrationTest.groovy:40]: Instead of trying to test this exhaustively here, could we instead....

1. Check that there's a build JVM info block in buildEnvironment
2. Check that the Location is seen

I think ToolchainReportRendererTest already checks the format of the message.

File: platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionCreator.java [hunk 2]
```diff
@@ -35,8 +36,11 @@ public interface CommandLineActionCreator {
...
      * Creates an executable action from the given command-line args.
      *
+     * @param parser the parser that was used to parse the command-line args
+     * @param commandLine the parsed command-line args
+     * @param parameters a supplier for the parameters created from the command-line args
      * @return {@code null} if this creator does not know how to create an action from the given command-line args
      */
     @Nullable
-    Action<? super ExecutionListener> createAction(CommandLineParser parser, ParsedCommandLine commandLine);
+    Action<? super ExecutionListener> createAction(CommandLineParser parser, ParsedCommandLine commandLine, Supplier<Parameters> parameters);
```
Comment (big-guy) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionCreator.java:45]: 🤔 I don't quite follow why this is a Supplier? 

It looks like we always call `get()` immediately on it and we're creating the supplier just before the method is called.  Can't we just pass Parameters?  We don't need to memoize them because this is never reused.

**Review by big-guy — CHANGES_REQUESTED** [review]
can you update installation.adoc and troubleshooting.adoc? This has -v output.

And check command_line_interface.adoc if we need to update anything there.

**Review by big-guy — CHANGES_REQUESTED** [review]
Forgot to add...

We also need an integration test that runs `gradle -v` in the three cases:
- Nothing specified
- daemon criteria
- org.gradle.java.home set

File: platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionCreator.java (hunk 2 above)
Comment (octylFractal) [reply platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionCreator.java:45]: It's not always used everywhere, and I wanted to avoid introducing different behavior where it wasn't parsed before. It's probably not that expensive, so I could always build it.

**Comment by octylFractal** [comment]
@bot-gradle test this

File: platforms/core-runtime/launcher/src/integTest/groovy/org/gradle/launcher/CommandLineOutputIntegrationTest.groovy [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+import org.gradle.test.fixtures.file.TestFile
+import org.gradle.test.fixtures.file.TestNameTestDirectoryProvider
+import org.gradle.test.precondition.Requires
+import org.gradle.test.preconditions.IntegTestPreconditions
+import org.junit.Rule
+
+/**
+ * Assertions over the output of certain command line invocations.
+ */
+class CommandLineOutputIntegrationTest extends AbstractIntegrationSpec {
```
Comment (big-guy) [inline platforms/core-runtime/launcher/src/integTest/groovy/org/gradle/launcher/CommandLineOutputIntegrationTest.groovy:31]: ❌ I was thinking something a little simpler.  I don't think we care about the effects of --project-dir or running from another working directory because we're using the same mechanisms that read `gradle.properties` or find the build files.  

If you think these _are_ important, I would slice the tests differently.  When the build's JVM is based on org.gradle.java.home or the launcher, we know the directories can't affect things.  If we want to see what happens with `--project-dir`, we can just test it with the JVM criteria.

Two other more generic things:
1. We should try to avoid disabling tests for the embedded executor unless it really doesn't make sense to run them. This makes it easier for people to just run with the embedded executor most of the time and the tests that need to run outside of it can.  In my example below, that's done by enabling daemons (we don't start daemons for this test, but that's enough to disable the in-process executor).
2. We need to be careful to restrict toolchain discovery tests because they can look everywhere. We have some fixtures that let you limit which JDKs are visible to the tests. My example does this.  It's also good to mark these as requirements for the test and write it in a way that doesn't require a specific JVM version. 

```
class CommandLineOutputIntegrationTest extends AbstractIntegrationSpec implements JavaToolchainFixture, DaemonJvmPropertiesFixture {

    def setup() {
        // forces the tests to fork and not run in-process
        executer.requireDaemon().requireIsolatedDaemons()
    }

    def "displays version message appropriately for Build JVM requested by Launcher JVM"() {
        when:
        succeeds("--version")

        then:
        outputContains("Requested Daemon JVM:  ${Jvm.current().javaHome.absolutePath} (no JDK specified, using Launcher JVM)")
    }

    def "displays version message appropriately for Build JVM requested by org.gradle.java.home"() {
        given:
        file("gradle.properties").writeProperties("org.gradle.java.home": Jvm.current().javaHome.absolutePath)

        when:
        succeeds("--version")

        then:
        outputContains("Requested Daemon JVM:  '${Jvm.current().javaHome.absolutePath}' (from -Dorg.gradle.java.home)")
    }

    @Requires(IntegTestPreconditions.JavaHomeWithDifferentVersionAvailable)
    def "displays version message appropriately for Build JVM requested by build criteria"() {
        def otherJvm = AvailableJavaHomes.differentVersion

        given:
        writeJvmCriteria(otherJvm)

        when:
        withInstallations(otherJvm).succeeds("--version")

        then:
        outputContains("Requested Daemon JVM:  Compatible with Java ${otherJvm.javaVersion.majorVersion} (Daemon JVM criteria from gradle/gradle-daemon-jvm.properties)")
    }
}
```

File: platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/cli/DefaultCommandLineActionFactory.java [hunk 4]
```diff
@@ -192,38 +201,103 @@ public void execute(ExecutionListener executionListener) {
...
-            System.out.println();
+            printAligned(ImmutableList.of(
+                new Line.KeyValue("Build time", currentVersion.getBuildTimestamp()),
+                new Line.KeyValue("Revision", currentVersion.getGitRevision()),
+                new Line.Blank(),
+                new Line.KeyValue("Kotlin", KotlinDslVersion.current().getKotlinVersion()),
+                new Line.KeyValue("Groovy", ReleaseInfo.getVersion()),
+                new Line.KeyValue("Ant", Main.getAntVersion()),
+                new Line.KeyValue("Launcher JVM", Jvm.current().toString()),
+                new Line.KeyValue("Requested Daemon JVM", parameters.getDaemonParameters().getRequestedJvmCriteria().toString()),
```
Comment (big-guy) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/cli/DefaultCommandLineActionFactory.java:228]: 🤔  Now that I've seen some of the output... a couple of tweaks:
- Maybe `Daemon JVM` instead of `Requested Daemon JVM`?
- `(no JDK specified, using Launcher JVM)` -> nothing.  If we say "using Launcher JVM" it sounds like we might be reusing the same process.
- `(from -Dorg.gradle.java.home)` -> `(from org.gradle.java.home)`.  You can specify org.gradle.java.home in multiple ways.
- `(Daemon JVM criteria from gradle/gradle-daemon-jvm.properties)` -> `(from gradle/gradle-daemon-jvm.properties)`

File: platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionCreator.java (hunk 2 above)
Comment (big-guy) [reply platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionCreator.java:45]: IIUC, the only place we don't use Parameters is when we're handling `-h`.  Everything else requires the Parameters to be created.  Is that right?

**Review by big-guy — CHANGES_REQUESTED** [review]

File: platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionCreator.java (hunk 2 above)
Comment (octylFractal) [reply platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionCreator.java:45]: Yeah. I'll change it.

**Comment by octylFractal** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Review by lkasso — APPROVED** [review]
Docs are great.
