### PR TITLE
Fix CMD shell output by installing jansi `AnsiConsole`

### LINKED ISSUE #35953: Colored terminal detection broken on Windows in 9.3.0-rc-1
### Current Behavior

Image

### Expected Behavior

Image

### Context (optional)

_No response_

### Self-contained Reproducer Project

Just any project.

### Gradle version

9.3.0-rc-1

### Gradle version that used to work

9.2.1

### Build scan URL (optional)

_No response_

### Your Environment (optional)

```
gradlew --version
Picked up JAVA_TOOL_OPTIONS: -Xms32M -Xmx256M -XX:+UseG1GC -D-XX:+PrintCommandLineFlags

------------------------------------------------------------
Gradle 9.3.0-rc-1
------------------------------------------------------------

Build time:    2025-11-28 16:38:38 UTC
Revision:      7103de78a66088931f83b1eea19b299af989c114

Kotlin:        2.2.21
Groovy:        4.0.29
Ant:           Apache Ant(TM) version 1.10.15 compiled on August 25 2024
Launcher JVM:  21.0.7 (Oracle Corporation 21.0.7+8-LTS-245)
Daemon JVM:    P:\tools\lang\java-21.0.7-x64-jdk (no Daemon JVM specified, using current Java home)
OS:            Windows 10 10.0 amd64
```

The problem shows up in
* Standalone `cmd` window
* IDEA Terminal view "Command Prompt" (`cmd`)
* IDEA Terminal view "Windows PowerShell"
* Didn't test more, probably more terminals are broken, and/or maybe other OSs too.

When changing the version back to 9.2.1 in the same session (git checkout), it "suddenly" works again.

### PR DESCRIPTION
**Pull request by reinsch82**
This seemingly wasn't necessary in Jansi 1.x (https://github.com/fusesource/jansi/issues/281) despite the doc always claiming it was necessary (https://github.com/fusesource/jansi#example-usage)

Jansi 1.x did eager registration, but with less checks and guard rails involved. There would stll be a deprecated option to eagerly install the streams, but since it is deprecated we don't want to use it.

* Fixes #35953

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Review by eskatos — APPROVED** [review]
Tested live on a Windows machine, confirmed it fixes the regression

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java [hunk 1]
```diff
@@ -122,6 +122,7 @@ private static void configureRichConsole(OutputEventRenderer renderer, ConsoleMe
     }
 
     private static Console consoleFor(OutputStream stream, Supplier<OutputStream> jansiFallback, ConsoleMetaData consoleMetaData, ColorMap colourMap) {
+        org.fusesource.jansi.AnsiConsole.systemInstall();
```
Comment (big-guy) [inline platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: I'm not sure about this because I think this gets called twice (once for stdout and once for stderr). systemInstall does nothing if you call it twice, but it also modifies System.setOut/setErr.

If you just want to make sure the `install()` is called on the underlying print streams, maybe we can call that ourselves?

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test this

File: testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java [hunk 2]
```diff
@@ -289,7 +290,11 @@ protected Factory<BaseExecHandleBuilder> getExecHandleFactory() {
             builder.setWorkingDir(getWorkingDir());
             builder.setExecutable(new File(getJavaHomeLocation(), "bin/java"));
             builder.classpath(getExecHandleFactoryClasspath());
-            builder.jvmArgs(invocation.launcherJvmArgs);
+            List<String> launcherJvmArgs = invocation.launcherJvmArgs;
+            ImmutableList.Builder<Object> launchArgsBuilder = ImmutableList.builderWithExpectedSize(invocation.launcherJvmArgs.size() + 1);
+            launchArgsBuilder.addAll(launcherJvmArgs);
+            launchArgsBuilder.add("-Djansi.mode=force");
```
Comment (reinsch82) [inline testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java]: force jansi to use ansi console in embedded execution.

this makes embedded "console output" behave the same as in external execution.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java [hunk 3]
```diff
@@ -63,16 +63,19 @@ private static ConsoleMetaData getConsoleMetaData() {
     }
 
     private static void configureAutoConsole(OutputEventRenderer renderer, ConsoleMetaData consoleMetaData, OutputStream stdout, OutputStream stderr) {
-        if (consoleMetaData.isStdOut() && consoleMetaData.isStdErr()) {
+        if (consoleMetaData.isStdOutATerminal() || consoleMetaData.isStdErrATerminal()) {
+            org.fusesource.jansi.AnsiConsole.systemInstall();
```
Comment (reinsch82) [inline platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: as partially suggested by @big-guy only call `systemInstall()` once.

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java (hunk 1 above)
Comment (reinsch82) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: I don't think I understand what we gain by calling it ourselves.
But this only gets called and used in the launcher, to my understanding. The launcher goes away anyway, so I don't think it matters how high the `installed` count is at the end.

**Comment by reinsch82** [comment]
@bot-gradle test RFR

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java (hunk 3 above)
Comment (big-guy) [reply platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java]: ❌ I don't think we should be doing this at all.

My concern was more about the calls to setErr and setOut that systemInstall does. We should not be calling `systemInstall` because the only thing it does that we weren't doing before is calling setErr/setOut directly.  AnsiConsole::err and AnsiConsole::out below call `initStreams`, so I don't think there's anything else that systemInstall does that we weren't already doing. 

The docs that say you should call systemInstall are just talking about the easy way to enable this where jansi is responsible for System.out/System.err. Inside Gradle, our logging manager is responsible for this setting these.

IIUC, calling systemInstall all the time is just masking another problem by letting jansi write directly to stdout/stderr. Christophe alludes to some differences here: https://github.com/gradle/gradle/pull/35402/files#r2452421805

Have we reproduced this on our Windows agents?

I don't immediately know what's wrong here, but my suspicion is that we're not wrapping the same outputstream as we were before. e.g., we replaced AnsiConsoleUtil.wrapOutputStream with `org.fusesource.jansi.AnsiConsole#out` and I'm not 100% sure these are equivalent.

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle  test RFN

**Comment by reinsch82** [comment]
@bot-gradle test RFN

File: platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/source/TeePrintStream.java [hunk 4]
```diff
@@ -0,0 +1,349 @@
...
+                return true;
+            }
+        }
+
+        return false;
+    }
+
+    @Override
+    protected void setError() {
+        throw new UnsupportedOperationException("setError");
```
Comment (reinsch82) [inline platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/source/TeePrintStream.java]: 🤔 I assume this might be a behavior change?! How bad is it?

File: testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/NoDaemonGradleExecuter.java [hunk 5]
```diff
@@ -178,6 +184,7 @@ public File getWorkingDir() {
                 builder.environment("JAVA_HOME", "");
                 builder.environment("GRADLE_OPTS", "");
                 builder.environment("JAVA_OPTS", "");
+//                builder.environment("JAVA_OPTS", "-D" + AnsiConsole.JANSI_MODE + "=" + AnsiConsole.JANSI_MODE_FORCE);
```
Comment (reinsch82) [inline testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/NoDaemonGradleExecuter.java]: I will remove this after tests are run

**Review by big-guy — APPROVED** [review]
