### PR TITLE
ScalaDoc task should support maxMemory argument

### LINKED ISSUE #12717: ScalaDoc should support maxMemory argument
Hi folks!

Similar to `Javadoc` (https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html#org.gradle.api.tasks.javadoc.Javadoc:maxMemory), `ScalaDoc` should support `maxMemory` argument

We have seen builds that run OOM when generating `scaladocs`:

```
13:03:50 Caused by: java.lang.reflect.InvocationTargetException
13:03:50 	at org.gradle.api.tasks.scala.internal.GenerateScaladoc.invokeScalaDoc(GenerateScaladoc.java:86)
13:03:50 	at org.gradle.api.tasks.scala.internal.GenerateScaladoc.execute(GenerateScaladoc.java:38)
13:03:50 	... 18 more
13:03:50 Caused by: java.lang.OutOfMemoryError: Java heap space
13:03:50 	at scala.tools.nsc.typechecker.Namers$Namer.typeErrorHandler(Namers.scala:112)
13:03:50 	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1651)
13:03:50 	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:869)
13:03:50 	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:868)
13:03:50 	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:868)
13:03:50 	at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1677)
13:03:50 	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:868)
13:03:50 	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:860)
13:03:50 	at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1799)
13:03:50 	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1807)
13:03:50 	at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1797)
13:03:50 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
13:03:50 	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1680)
13:03:50 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5035)
13:03:50 	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
13:03:50 	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
13:03:50 	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
13:03:50 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
``` 

The worker for this is configured with default memory: https://github.com/gradle/gradle/blob/master/subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java#L143

Setting `maxHeapSize` for the `forkOptions` should be allowed

### PR DESCRIPTION
**Pull request by rpalcolea**
Fixes #12717

### Context
Similar to Javadoc (https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html#org.gradle.api.tasks.javadoc.Javadoc:maxMemory), ScalaDoc should support maxMemory argument

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by rpalcolea** [comment]
If this makes sense, I still need to figure out how to test this change. Any guidance/suggestion would be very welcome

File: subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java [hunk 1]
```diff
@@ -133,6 +135,28 @@ public void setTitle(@Nullable String title) {
...
     }
 
+    /**
+     * Returns the amount of memory allocated to this task.
+     *
+     * @since 6.4
+     */
+    @Internal
+    @Nullable
+    public String getMaxMemory() {
```
Comment (ljacomet) [inline subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java:145]: This should be exposed as a `Property<String>`

Comment (rpalcolea) [reply subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java:145]: Oh interesting. I found that most of properties in `javadoc` and `scaladoc` are not using `Property` provider. More than happy to change that, just want to know which one is the preferred way for consistency

Comment (ljacomet) [reply subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java:145]: Yes, and migrating the existing things is going to be interesting. But the future is clearly with `Property<?>`, so please go ahead with that added one, leaving the other as they stand.

Comment (rpalcolea) [reply subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java]: Hi @ljacomet 

Moved this to property -> https://github.com/gradle/gradle/pull/12718/commits/93c6ed481d928987a391c7639db1aadfa5c2af8c

Also marked it as 6.5 since 6.4-rc-1 is already out 😅

File: subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java [hunk 2]
```diff
@@ -51,6 +53,7 @@
     private FileCollection scalaClasspath;
     private ScalaDocOptions scalaDocOptions = new ScalaDocOptions();
     private String title;
+    private final Property<String> maxMemory = getProject().getObjects().property(String.class);
```
Comment (big-guy) [inline subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java:56]: We want to avoid introducing new places that use `getProject()`, so instead you'll have to do something a little different. We should introduce a public `ScalaDoc(ObjectFactory)` constructor and use `ObjectFactory.property(...)` directly.

File: subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java [hunk 3]
```diff
@@ -133,6 +136,28 @@ public void setTitle(@Nullable String title) {
         this.title = title;
     }
 
+    /**
+     * Returns the amount of memory allocated to this task.
+     *
+     * @since 6.5
+     */
+    @Internal
+    @Nullable
```
Comment (big-guy) [inline subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java:145]: This can't be null

File: subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java [hunk 4]
```diff
@@ -133,6 +136,28 @@ public void setTitle(@Nullable String title) {
...
+    }
+
+    /**
+     * Sets the amount of memory allocated to this task.
+     *
+     * @param maxMemory The amount of memory
+     *
+     * @since 6.5
+     */
+    public void setMaxMemory(String maxMemory) {
```
Comment (big-guy) [inline subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java:157]: This setter needs to be removed.  The Property should be set through `getMaxMemory`

File: subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java [hunk 5]
```diff
@@ -133,6 +136,28 @@ public void setTitle(@Nullable String title) {
         this.title = title;
     }
 
+    /**
+     * Returns the amount of memory allocated to this task.
```
Comment (big-guy) [inline subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java:140]: Can you add an example of what is expected here (1G, 256MB, etc)?

File: subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java (hunk 2 above)
Comment (rpalcolea) [reply subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java]: Makes sense, https://github.com/gradle/gradle/pull/12718/commits/aeddf3e3e20819ce6ab6bb8d21d50466bb068095 should cover this

File: subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java (hunk 3 above)
Comment (rpalcolea) [reply subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java]: Removed 👍

File: subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java (hunk 4 above)
Comment (rpalcolea) [reply subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java]: oh yeah that makes total sense, removed in https://github.com/gradle/gradle/pull/12718/commits/aeddf3e3e20819ce6ab6bb8d21d50466bb068095

File: subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java (hunk 5 above)
Comment (rpalcolea) [reply subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java:146]: This should be resolved now

**Comment by rpalcolea** [comment]
Hi @big-guy ,

Thanks for looking at this

Responded in your comments and also

https://github.com/gradle/gradle/pull/12718/commits/d441b4aa90b1eeee4f7eb4505d630a51be219622 https://github.com/gradle/gradle/pull/12718/commits/6c66493b1a51fe9f286ae7b7840b536465dbbd3d for your asks on adding to the XML file and the integration test

File: subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaDocSpec.groovy [hunk 6]
```diff
@@ -16,21 +16,40 @@
...
+import org.gradle.api.internal.file.TestFiles
+import org.gradle.api.internal.project.taskfactory.TaskInstantiator
+import org.gradle.api.tasks.AbstractConventionTaskTest
+
 import org.gradle.util.WrapUtil
 
 import static org.gradle.api.tasks.compile.AbstractCompileTest.*
 
-class ScalaDocSpec extends AbstractSpockTaskTest {
+class ScalaDocSpec extends AbstractConventionTaskTest {
```
Comment (rpalcolea) [inline subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaDocSpec.groovy:27]: I saw that `GroovydocTest` uses `AbstractConventionTaskTest` and took the opportunity to consolidate that

File: subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaDocSpec.groovy [hunk 7]
```diff
@@ -16,21 +16,40 @@
...
+
     ScalaDoc scalaDoc
 
+    def setup() {
+        scalaDoc = project.services.get(TaskInstantiator).create(TEST_TASK_NAME, ScalaDoc)
```
Comment (rpalcolea) [inline subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaDocSpec.groovy:32]: Hopefully this is the desired way to instantiate the task.

I found that `AbstractSpockTaskTest` had also limitations on this by doing https://github.com/gradle/gradle/blob/master/subprojects/core/src/testFixtures/groovy/org/gradle/api/tasks/AbstractSpockTaskTest.groovy#L55-L59

File: subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaDocSpec.groovy [hunk 8]
```diff
@@ -16,21 +16,40 @@
...
+    }
+
     @Override
     AbstractTask getTask() {
         return scalaDoc
     }
 
-    def setup() {
-        scalaDoc = createTask(ScalaDoc)
+    def "scala classpath must not be empty"() {
```
Comment (rpalcolea) [inline subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaDocSpec.groovy:40]: groovy test does the same so I thought it would be great to have same test

File: subprojects/scala/src/integTest/groovy/org/gradle/scala/scaladoc/ScalaDocIntegrationTest.groovy [hunk 9]
```diff
@@ -71,4 +74,32 @@ class ScalaDocIntegrationTest extends AbstractIntegrationSpec implements Directo
...
+            }
+
+            dependencies {
+                implementation 'org.scala-lang:scala-library:2.11.12'
+            }
+        """
+
+        writeSourceFile()
+        when:
+        ExecutionResult result = run scaladoc, "-d"
```
Comment (rpalcolea) [inline subprojects/scala/src/integTest/groovy/org/gradle/scala/scaladoc/ScalaDocIntegrationTest.groovy:95]: The information on the daemon is not showed with `-i`.

Wondering if that should be changed in the future.

Also, I found that for tasks that use the worker api such as this one do not mention that the default is `512m` wonder if this should be surfaced when the task is executed, adding the worker info level logging would definitely help

**Comment by ljacomet** [comment]
@bot-gradle test RFM
