### PR TITLE
Remove finalization from test framework properties

### LINKED ISSUE #24331: Gradle 8+ breaks actionable "useJUnitPlatform" calls
When using Gradle 8+ (like 8.0.2), changing the `useJUnitPlatform` call from `()` to `{}` produces an error.

For example, this block of code will not work:

```kotlin
subprojects {
    tasks.withType<Test>().configureEach {
        useJUnitPlatform {
            includeEngines("spek")
        }
    }
}
```
```
The value for task ':redacted' property 'testFrameworkProperty' is final and cannot be changed any further.
```
However, this one will work fine:
```
subprojects {
    tasks.withType<Test>().configureEach {
        useJUnitPlatform()
    }
}
```
To demonstrate this, I’ve made a trivial change at detekt/detekt#5906. As you can see, [CI steps there fail](https://github.com/detekt/detekt/actions/runs/4423885495/jobs/7757061009).

I suspect this happens because [the actionable call sets options as a separate step](https://github.com/gradle/gradle/blob/v8.0.2/subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java#L1012-L1015), as such mutating options twice. The overarching issue was described at #18606 but this one seems to be an oversight.

### PR DESCRIPTION
**Pull request by ghale**
Rather than try to capture all of the different possible ways to configure the test framework and handle finalization in the face of those ways, this just removes the finalization, so exceptions won't be thrown, but there could be scenarios where the test framework could be overwritten, potentially losing options.

Fixes #24331

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

File: subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java [hunk 1]
```diff
@@ -1058,15 +1056,13 @@ public void useTestNG(Action<? super TestNGOptions> testFrameworkConfigure) {
...
-            if (currentFramework == newFramework) {
-                // We are setting a finalized framework to its existing value, no-op so as not to trigger a failure here.
-                // We need to allow this especially for the default test task, so that existing builds that configure options and
-                // then call useJunit() afterwards don't fail
-                return;
-            }
+        Class<?> currentFramework = this.testFramework.get().getClass();
+        Class<?> newFramework = testFramework.getClass();
+        if (currentFramework == newFramework) {
+            // We are setting a framework to its existing value, no-op so as not to overwrite existing options here.
```
Comment (tresat) [inline subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java:1062]: 🧐 This might be better as a javadoc on the method now, so it becomes more noticeable.

File: subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java [hunk 2]
```diff
@@ -138,6 +140,24 @@ public List<String> getRuntimeOnlyDependencies() {
         }
     }
 
+    private static class CachingTestFrameworkTransformer implements Transformer<TestFramework, VersionedTestingFramework> {
+        private final Transformer<TestFramework, TestingFramework> mapToTestFramework;
+        private Pair<TestingFramework, TestFramework> currentMapping;
```
Comment (tresat) [inline subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java:145]: 💭 IDK if the use of `Pair` adds much here vs. just storing the input and output directly.  I was also a little confused at first when reading this since our `Transformer` puts the generic OUT param first and the IN param second, which seems backwards to me.  Might be worth a note to clarify that for anyone else expecting the opposite.

**Review by tresat — APPROVED** [review]

File: subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy [hunk 3]
```diff
@@ -537,35 +473,6 @@ class TestSuitesIntegrationTest extends AbstractIntegrationSpec {
         succeeds("assertSameFrameworkInstance")
     }
 
-    def "multiple getTestingFramework() calls on a test suite return same instance even when calling useJUnit"() {
```
[the remark this answers is not in the document]
Comment (ghale) [reply subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy:540]: Yeah, because the value is a mapping from the framework/version to a `VersionedTestingFramework` object.  Previously, this passed because the first call to `get()` finalized the property, so the second one got the finalized value.  Now, it returns a new `VersionedTestingFramework` with the same values every time.  We could fix this, but that object is just metadata, so this test case just didn't seem that important at all.

File: subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy [hunk 4]
```diff
@@ -383,70 +383,6 @@ class TestSuitesIntegrationTest extends AbstractIntegrationSpec {
         succeeds("integTest")
     }
 
-    def "task configuration overrules test suite configuration"() {
```
[the remark this answers is not in the document]
Comment (ghale) [reply subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy:386]: Thanks for bringing it up.  It really wasn't clear to me what these tests were trying to capture previously - it seemed like the description was the opposite of what they were testing.  I've restored them and updated them to what I _think_ they should cover (going the extra step to actually execute a test).

File: subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java (hunk 2 above)
Comment (ghale) [reply subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java]: Ah, yes, I can see why the differing order of the types might be confusing.  I've updated this to change the `Pair` to reflect the same order as `Transformer` and added a note, which hopefully makes this less confusing.  I'd like to keep it a `Pair` just to bake in the idea that these two values are related and cannot be set independently (i.e. these are a _mapping_ with an inherent relationship).  If you feel like the vagueness of a `Pair` is confusing, I don't feel super strongly about it, but I had actually started to remove it and then decided I liked it better as it is.

**Comment by ghale** [comment]
@bot-gradle test and merge
