### PR TITLE
Preserve old operation display names for backward compatibility with IntelliJ

### LINKED ISSUE #24538: Test event in Gradle TAPI has incomplete or incorrect data
I have investigated several cases where Gradle TAPI provides into IntelliJ IDEA incomplete or incorrect information in tests events. I have created [GradleTestEventConverter](https://github.com/JetBrains/intellij-community/blob/7edc9a8ce26efdc1d81005a68c71905943d8d788/plugins/gradle/java/src/execution/test/runner/events/GradleTestEventConverter.kt#L31) which converts and repairs data in events.

I can describe cases which I find:
 - Display name of method, parametrised method, suite, class events are quoted and has prefixes. E.g. `Test name()`, `Test name()(org.example.TestCase)` and `Test suite 'name(org.example.TestCase)'` should be `name`;
 - Display name for JUnit 5 method event by default has information about method arguments. E.g. `test()`, `test(int, String)`, etc should be `test`;
 - Display name for JUnit 4 class event has class with package prefix. E.g. `org.example.TestCase` should be `TestCase`;
 - Display name for parametrised intermediate method event (which class are annotated by `@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)`) has trailing space in name. E.g. `pretty name (int)[1]` should be `pretty name`;
 - Class and method names are absent for JUnit 5 parametrised and Spock intermediate method events;
 - Method name for JUnit 5 parametrised method event has suffix with parameter number.  E.g. `test(int)[1]`, `test(int)[2]`, `test(int)[3]`, etc should be `test`;
 - Method name has unparsed signature of test method. I prefer to see here only method name. E.g. `test()`, `test(int)`, `test(int)[1]`, etc should be `test`;

Method name in case with Junit 5 parametrised intermediate method event and @DisplayName annotation cannot be repaired. Because we don't have methodName and className. Also, displayName nothing describes about original method name.

Note: Intermediate method event is an event which happens between class and leaf method events. These event has non empty suite name.

I prepared project which covered all these cases.
[gradle-junit-project.zip](https://github.com/gradle/gradle/files/11092734/gradle-junit-project.zip)

Seems incorrect display name generates in [backwardsCompatibleDisplayNameOf](https://github.com/gradle/gradle/blob/1d3837010f046965262145f2354f2d45d66c9ef6/subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestOperationMapper.java#L115)

### PR DESCRIPTION
**Pull request by ov7a**
See https://github.com/gradle/gradle/issues/24538#issuecomment-2072828643

Fixes #24538

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ov7a** [comment]
@bot-gradle test ACT

**Comment by ov7a** [comment]
@bot-gradle test ACT

File: platforms/ide/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestOperationMapper.java [hunk 1]
```diff
@@ -103,12 +106,31 @@ private DefaultTestDescriptor toTestDescriptorForTest(OperationIdentifier buildO
...
+        } else {
             operationDisplayName = getLegacyOperationDisplayName(operationDisplayName, originalDescriptor);
         }
         return new DefaultTestDescriptor(buildOperationId, test.getName(), operationDisplayName, test.getDisplayName(), InternalJvmTestDescriptor.KIND_ATOMIC, null, test.getClassName(), test.getName(), parentId, taskTracker.getTaskPath(buildOperationId));
     }
 
+    /**
+     * This is a workaround to preserve backward compatibility with IntelliJ IDEA.
+     * The problem only occurs in IntelliJ IDEA because it parses {@link OperationDescriptor#getDisplayName()} to get test display name.
+     * Once it's code is updated to use {@link org.gradle.tooling.events.test.TestOperationDescriptor#getTestDisplayName()}, the workaround can be removed as well.
```
Comment (MGaetan89) [inline platforms/ide/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestOperationMapper.java:120]:
```suggestion
     * The problem only occurs in IntelliJ IDEA because it parses {@link OperationDescriptor#getDisplayName()} to get the test display name.
     * Once its code is updated to use {@link org.gradle.tooling.events.test.TestOperationDescriptor#getTestDisplayName()}, the workaround can be removed as well.
```

**Review by donat — APPROVED** [review]
