### PR TITLE
Detect special multicause exceptions

### LINKED ISSUE #9487: Suppressed exceptions thrown by tests are not captured in the test report and build scan
Given the following classes, executing `CalculatorTests` using IntelliJ's Platform test runner yields the following exception. Please note the two suppressed exceptions.

```java
package com.example.project;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class CalculatorTests {
	@Test
	void addsTwoNumbers() {
		Calculator calculator = new Calculator();
		assertAll(
				() -> assertEquals(2, calculator.add(1, 1), "1 + 1 should equal 2"),
				() -> assertEquals(2, calculator.add(0, 2), "0 + 2 should equal 2")
		);
	}
}
```
```java
package com.example.project;

public class Calculator {
	public int add(int a, int b) {
		return a - b;
	}
}
```

Failure:

```
org.opentest4j.MultipleFailuresError: Multiple Failures (2 failures)
	1 + 1 should equal 2 ==> expected: <2> but was: <0>
	0 + 2 should equal 2 ==> expected: <2> but was: <-2>

	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:80)
	[...]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	Suppressed: org.opentest4j.AssertionFailedError: 1 + 1 should equal 2 ==> expected: <2> but was: <0>
		at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
		at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
		at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:152)
		at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:542)
		at com.example.project.CalculatorTests.lambda$addsTwoNumbers$0(CalculatorTests.java:29)
		at org.junit.jupiter.api.AssertAll.lambda$assertAll$1(AssertAll.java:68)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
		at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
		at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:77)
		... 55 more
	Suppressed: org.opentest4j.AssertionFailedError: 0 + 2 should equal 2 ==> expected: <2> but was: <-2>
		at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
		at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
		at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:152)
		at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:542)
		at com.example.project.CalculatorTests.lambda$addsTwoNumbers$1(CalculatorTests.java:30)
		at org.junit.jupiter.api.AssertAll.lambda$assertAll$1(AssertAll.java:68)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
		at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
		at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:77)
		... 55 more
```

### Expected Behavior

The suppressed exceptions should be reported to `TestListeners` and make it into the generated XML and HTML reports.

### Current Behavior

The suppressed exceptions and their stracktraces are lost.

### Context

Suppressed exceptions are also used by JUnit in case a test fails and it's `@AfterEach` method also throws an exception etc.

### Steps to Reproduce 

1. clone https://github.com/junit-team/junit5-samples
1. switch to `marc/gradle-suppressed-exceptions` branch
1. `cd junit5-jupiter-starter-gradle`
1. `./gradlew test`

### Your Environment

Build scan URL: https://scans.gradle.com/s/4bzzn22qkm7pc/tests/:test/com.example.project.CalculatorTests/addsTwoNumbers()#1

### PR DESCRIPTION
**Pull request by melix**
This commit fixes an issue where test reports and build scans didn't capture
all the causes of an exception, in case the "multi-cause" exception isn't
a type known of the daemon. By that, we mean a type which is not available
at runtime in the daemon process, but is used in the worker process.

Typically, the `org.opentest4j.MultipleFailuresError` type used by
JUnit is such an example: the type is used in a test process, but
not loaded in Gradle. In such cases, Gradle builds a placeholder
exception type which collects the root cause. But in case the
exception is actually collecting multiple causes like in this test
class, Gradle lost some information in the process.

Therefore, this commit introduces a heuristic to figure out if an
exception is collecting multiple causes instead of a single one.
The heuristic is kept very simple: one has to find a method which
name is either `getCauses` (like for Gradle's own default multi
cause exception) or `getFailures` (like in opentest4j), and it
has to return a collection of failures.

This will not fix all problems but it should capture a good amount
of them.

Fixes #9487

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test RFM

File: subprojects/messaging/src/main/java/org/gradle/internal/serialize/ExceptionPlaceholder.java [hunk 1]
```diff
@@ -206,6 +222,53 @@ private void diagnoseNullPointerException(NullPointerException e) {
         }
     }
 
+    private static Method findCandidateGetCausesMethod(Throwable throwable) {
+        Method[] declaredMethods = throwable.getClass().getDeclaredMethods();
+        for (Method method : declaredMethods) {
+            if (CANDIDATE_GET_CAUSES.contains(method.getName())) {
+                Class<?> returnType = method.getReturnType();
+                if (Collection.class.isAssignableFrom(returnType)) {
```
Comment (jjohannes) [inline subprojects/messaging/src/main/java/org/gradle/internal/serialize/ExceptionPlaceholder.java:230]: Maybe use `Iterable` instead of `Collection`?

Comment (melix) [reply subprojects/messaging/src/main/java/org/gradle/internal/serialize/ExceptionPlaceholder.java:230]: I think it's fine as is. Sure we can make it more generic but I doubt we'd find a real use case. If we did we can revisit.

**Comment by marcphilipp** [comment]
Thanks, @melix! 👍
