### PR TITLE
Demonstrate caching behavior of IvyRepositoryDescriptor and repositor…

### LINKED ISSUE #25362: Setting URL for repository used for publishing "late" is ignored
### Expected Behavior

Changing the URL for the repository is honored (as before 8.2).

### Current Behavior

Changing the URL for the repository is ignored

### Context (optional)

The [Nexus plugin](https://github.com/gradle-nexus/publish-plugin) relies on the existing behavior.

> The nexus plugin works by setting the url of each ivy repo to a provider that will be filled later by a gradle task
This used to work until now, because before uploading the artifact the ivy repository called getUrl hence triggering the provider
From this change onward the resourceArtifact patterns are stored on the IvyResolver's repositoryDescriptor, and the repository descriptor is cached on the first invocation, which is the first time when getUrl is called, at this point the repository is not created yet, it returns a dummy url
Before the artifact patterns were calculated when the resolver was created and at that point all previous tasks were ran already

### Steps to Reproduce

This [commit](https://github.com/gradle/gradle/commit/bcd40fe9c3b68af6b838b3add6fafe2adbf10b08) appears to have changed the behavior.

### Gradle version

8.2-rc-2

### Gradle version that used to work

8.1

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by big-guy**
…y URL

fixes #25362

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java [hunk 1]
```diff
@@ -367,6 +367,17 @@ protected void invalidateDescriptor() {
         schemes = null;
     }
 
+    public boolean hasStandardPattern() {
+        // This is wasteful because we create a descriptor and throw it away immediately.
+        IvyRepositoryDescriptor descriptor = createDescriptor();
```
Comment (jvandort) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java:372]: Does this problem manifest in Maven, too? Which also extends `AbstractResolutionAwareArtifatRepostory`? 

Could we just update the base class to avoid caching?

Comment (big-guy) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java:372]: This is Ivy only

**Review by jvandort — APPROVED** [review]

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java (hunk 1 above)
Comment (big-guy) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java:372]: Unfortunately, it would need to be the other way around.

We call `hasStandardPattern` before task execution, which causes the descriptor to be cached. Later, during task execution, the URL for the repository changes and the descriptor needs to be invalidated.

So instead of caching the descriptor before task execution and having to invalidate it later, we just look at a new descriptor each time.

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test and merge
