### PR TITLE
Sort IgnoredKey entries in gradle/verification-metadata.xml

### LINKED ISSUE #27891: Ignored keys are not sorted in the verification metadata file
### Current Behavior

When Gradle adds ignore keys to the verification metadata file, they are not sorted. This breaks reproducibility of the file.

### Expected Behavior

Gradle should sort ignored keys, similarly to the other section of the verification metadata file.

In addition, there should be documentation on how to manually add a key to the ASCII armored key export file if Gradle failed to download them.

### Context (optional)

_No response_

### Steps to Reproduce

* Take any Gradle build
* Enable dependency verification and generate the file
* Shuffle entries around in different categories, artificially adding ignored keys if needed
* Re-run the generation step
* Observe that all sections have applied sorting except for ignored keys

### Gradle version

8.5 and before

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Fixes #27891 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriter.java [hunk 1]
```diff
@@ -172,9 +172,13 @@ private void writIgnoredKeys(DependencyVerificationConfiguration configuration)
...
-            for (IgnoredKey ignoredKey : ignoredKeys) {
-                writeIgnoredKey(ignoredKey);
-            }
+            ignoredKeys.stream().sorted().forEach(ignoredKey -> {
+                try {
+                    writeIgnoredKey(ignoredKey);
+                } catch (IOException ex) {
+                    throw new UncheckedIOException(ex);
+                }
+            });
```
Comment (tresat) [inline platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriter.java:181]:
```suggestion
            List<IgnoredKey> sortedIgnoredKeys = ignoredKeys.stream().sorted().collect(Collectors.toList());
            for (IgnoredKey ignoredKey : sortedIgnoredKeys) {
                    writeIgnoredKey(ignoredKey);
            }
```

🤔 I think instead of potentially changing the type of exception thrown from this method, it's better to just use non-stream iteration and let the original exception propogate.

**Review by tresat — CHANGES_REQUESTED** [review]

File: platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriter.java (hunk 1 above)
Comment (oleg-nenashev) [reply platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriter.java:181]: @tresat I agree in general, but it is the same pattens as used in the methods above, e.g. in `writeGroupedTrustedKey()`. I would rather do a refactoring in the follow up PR if needed

Comment (tresat) [reply platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriter.java:181]: Sounds good.

**Review by tresat — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@bot-gradle merge
