### PR TITLE
Fix inconsistent resolution ordering

### LINKED ISSUE #13555: Compile classpath configuration is not deterministic
Our main build is hitting an issue where a compile classpath ends up with a different ordering when running the build repeatedly without intervening changes. Here's what I do:

```
gr :lib:core:database:compiler:test --no-build-cache --rerun-tasks
gr :lib:core:database:compiler:test --no-build-cache
```

The second run frequently (but not always) recompiles `:lib:core:database:compiler` even if nothing changed between both builds. The comparison of the build scans reveals that `io.reactivex.rxjava2:rxkotlin` is added to the classpath in different locations. Gradle Enterprise shows that the resolutions are slightly different. In the first run:

image

And in the second run:

image

This second resolution looks wrong, since `org.jetbrains.kotlin:kotlin-stdlib:1.3.40` is a runtime dependency of `io.reactivex.rxjava2:rxkotlin`. More interestingly, the resolution of `:lib:core:util:java:common` in the same build doesn't list `kotlin-stdlib` as a dependency of `rxkotlin`:

image

The issue shows up in different modules each time, but it affects most of our builds. I repro'ed in the current latest nightly, `6.6-20200622220024+0000`.

I collected some extra information and put up the files in a [shared drive](https://drive.google.com/file/d/1nL38MHOOc0tawN-3kD71LWJHxHgmqvRB/view?usp=sharing):

* The build scans for both builds (from which I took the previous screenshots).
* The command line arguments to the compilation task in both cases, which show the different classpaths.
* The full debug outputs from both builds.

### PR DESCRIPTION
**Pull request by melix**
The fix for #12951 introduced by #12957 worked but made a number
of other bugs much more likely to happen: by using the right derivation
strategy in each project, we were properly fetching the component
metadata we wanted to process from the cache.

However, this component metadata was mutable, because of laziness.
In particular, derivation of variants require to set the derivation
strategy on "deemed immutable" metadata. The problem is that when
several configurations are resolved concurrently, we ended up mutating
the same component from different threads, with different derivation
strategies.

The ideal fix would be to have real immutable component metadata from
the cache. However, because of laziness (required for performance), we
can't do that.

The fix in this PR is therefore to create a copy of the module metadata
whenever a different derivation strategy needs to be used.

It also highlighted another bug, which is that when we use cached
component metadata rules, the derivation strategy wasn't part of the
cache key, meaning that we would get whatever was first stored in the
binary cache.

We now properly separate the entries in the cache by amending the cache
key with the name of the strategy. This isn't ideal as we could potentially
have _stateful_ strategies, but for now there are no such things in the
wild. Again in reality we'd like to get rid of the "magic snapshotting"
of rules and do something similar to what transforms do, with proper
declared input types.

Fixes #13555

Fixes #?

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by melix** [comment]
If we do a 6.5.1 this is a serious candidate.

**Comment by melix** [comment]
@bot-gradle test this

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ivy/RealisedIvyModuleResolveMetadata.java [hunk 1]
```diff
@@ -234,7 +236,15 @@ public MutableIvyModuleResolveMetadata asMutable() {
 
     @Override
     public RealisedIvyModuleResolveMetadata withSources(ModuleSources sources) {
-        return new RealisedIvyModuleResolveMetadata(this, sources);
+        return new RealisedIvyModuleResolveMetadata(this, sources, getVariantDerivationStrategy());
+    }
+
+    @Override
+    public ModuleComponentResolveMetadata withDerivationStrategy(VariantDerivationStrategy derivationStrategy) {
+        if (getVariantDerivationStrategy() == derivationStrategy) {
```
Comment (ljacomet) [inline subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ivy/RealisedIvyModuleResolveMetadata.java:244]: I would use `.equals` here. We know today that the instance equality is enough, but if this changes down the line, it might be surprising.

File: subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/caching/ComponentMetadataRuleExecutor.java [hunk 2]
```diff
@@ -39,7 +39,7 @@ public static boolean isMetadataRuleExecutorCache(InMemoryCacheController contro
 
     private static Transformer<Object, ModuleComponentResolveMetadata> getKeyToSnapshotableTransformer() {
         return moduleMetadata -> moduleMetadata.getSources().withSource(ModuleDescriptorHashModuleSource.class, source -> {
-            return source.map(metadataFileSource -> metadataFileSource.getDescriptorHash().toString())
+            return source.map(metadataFileSource -> metadataFileSource.getDescriptorHash().toString() + moduleMetadata.getVariantDerivationStrategy().getClass().getName())
```
Comment (ljacomet) [inline subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/caching/ComponentMetadataRuleExecutor.java:42]: Nice find!

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractModuleComponentResolveMetadata.java [hunk 3]
```diff
@@ -188,6 +193,14 @@ public ModuleComponentArtifactMetadata artifact(String type, @Nullable String ex
         return platformOwners;
     }
 
+    @Override
+    public VariantDerivationStrategy getVariantDerivationStrategy() {
+        if (variantDerivationStrategy == null) {
```
Comment (ljacomet) [inline subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractModuleComponentResolveMetadata.java:198]: I do not understand this getter. It seems linked to the `variantDerivationStrategy = null;` but I am pretty sure we could always figure out a value or always use the value from `getVariantMetadataRules().getVariantDerivationStrategy()`.
In short I think we should make this simpler.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/DefaultComponentMetadataProcessor.java [hunk 4]
```diff
@@ -179,7 +183,7 @@ public ModuleComponentResolveMetadata processMetadata(ModuleComponentResolveMeta
         if (!updatedMetadata.getStatusScheme().contains(updatedMetadata.getStatus())) {
             throw new ModuleVersionResolveException(updatedMetadata.getModuleVersionId(), () -> String.format("Unexpected status '%s' specified for %s. Expected one of: %s", updatedMetadata.getStatus(), updatedMetadata.getId().getDisplayName(), updatedMetadata.getStatusScheme()));
         }
-        return updatedMetadata;
+        return updatedMetadata.withDerivationStrategy(curStrategy);
```
[the remark this answers is not in the document]
Comment (melix) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/DefaultComponentMetadataProcessor.java:186]: That's because of the non-cached rules: when they are processed, they play a "immutable to mutable" dance, which ends up losing the derivation strategy. Then the next time we do the comparison, we think it's using the same strategy when it's not.

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractModuleComponentResolveMetadata.java (hunk 3 above)
Comment (melix) [reply subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractModuleComponentResolveMetadata.java:198]: This is again because of the conversion to mutable metadata, which does _not_ keep the strategy. I chose not to leak the strategy into the mutable version of component metadata (the immutable version is already enough, I think). Alternatively we need to store the derivation strategy in the mutable version too. That's a larger change that can be avoided by this strategy.

**Comment by melix** [comment]
@ljacomet PTAL
@bot-gradle test RFM

**Comment by melix** [comment]
@bot-gradle test RFM

**Comment by melix** [comment]
@bot-gradle test this

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractModuleComponentResolveMetadata.java (hunk 3 above)
Comment (melix) [reply subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractModuleComponentResolveMetadata.java]: I ended up adding it to mutable metadata too, for consistency.

**Comment by melix** [comment]
@bot-gradle test this

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/WrappingComponentMetadataContext.java [hunk 5]
```diff
@@ -66,19 +67,24 @@ public ComponentMetadataDetails getDetails() {
...
-    MutableModuleComponentResolveMetadata getMutableMetadata() {
-        createMutableMetadataIfNeeded();
-        return mutableMetadata;
+    VariantDerivationStrategy getVariantDerivationStrategy() {
+        return metadata.getVariantDerivationStrategy();
     }
 
-    private void createMutableMetadataIfNeeded() {
+    ModuleComponentResolveMetadata getImmutableMetadataWithDerivationStrategy(VariantDerivationStrategy variantDerivationStrategy) {
+        // We need to create a copy or the rules will be added to the wrong container
```
Comment (ljacomet) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/WrappingComponentMetadataContext.java:79]: Indeed!
