### PR TITLE
Track systemProps changes in DefaultGradlePropertiesLoader

### LINKED ISSUE #19184: Configuration cache doesn't load system properties from included build `gradle.properties` files
Related to #15820.

Consider the following build structure:

```
build-logic/
    build.gradle.kts
       println(providers.systemProperty("property").orNull)
    gradle.properties
       systemProp.property=42
settings.gradle.kts
    includeBuild("build-logic")
```

# Expected Behavior

Second run successfully loads from the cache.

# Actual Behavior

Second run fails to load from the cache with:

```
Calculating task graph as configuration cache cannot be reused because system property 'property' has changed.
```

### PR DESCRIPTION
**Pull request by 6hundreds**
Fixes #19184

### CODE REVIEW

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy [hunk 1]
```diff
@@ -179,15 +179,52 @@ class ConfigurationCacheGradlePropertiesIntegrationTest extends AbstractConfigur
...
+        outputDoesNotContain "because system property '$systemProp' has changed"
         outputContains fixture.expectedOutputBeforeChange
         configurationCache.assertStateLoaded()
 
         cleanup:
-        System.clearProperty('fromPropertiesFile')
+        System.clearProperty("$systemProp")
+    }
+
+    def "same system property from multiple included build properties files"() {
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy:194]: I'd add the test checking the command-line override for the system property, as it wins over the `gradle.properties` value. Adding the override should invalidate the configuration cache - but if there are property reads at the configuration time. I'm not sure if the current implementation of the `EvironmentChangeTracker` can handle this correctly, though - some non-trivial amendments may be necessary.

There is a TODO in DefaultGradlePropertiesLoader to test if `included-build/gradle.properties` overrides `gradle.properties` of the root build; it might be a good time and place to add an actual test for this.

One more tricky scenario: what if we read the system property inside the `settings.gradle`? In the root build or in one of the included builds? It affects the output, but shouldn't affect the value used at execution time.

File: subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesLoader.java [hunk 2]
```diff
@@ -97,7 +100,9 @@ private void setSystemPropertiesFromGradleProperties(Map<String, Object> propert
         int prefixLength = prefix.length();
         for (String key : properties.keySet()) {
             if (key.length() > prefixLength && key.startsWith(prefix)) {
-                System.setProperty(key.substring(prefixLength), uncheckedNonnullCast(properties.get(key)));
+                String keyWithoutPrefix = key.substring(prefixLength);
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesLoader.java:103]: Agree

File: subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/services/EnvironmentChangeTrackerTest.kt [hunk 3]
```diff
@@ -23,7 +23,7 @@ import org.junit.Test
 
 class EnvironmentChangeTrackerTest {
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/services/EnvironmentChangeTrackerTest.kt:24]: Sure

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy (hunk 1 above)
Comment (6hundreds) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy:194]: > I'd add the test checking the command-line override for the system property, as it wins over the `gradle.properties` value. Adding the override should invalidate the configuration cache - but if there are property reads at the configuration time. I'm not sure if the current implementation of the `EvironmentChangeTracker` can handle this correctly, though - some non-trivial amendments may be necessary.

But in this case startParameters of build is changed, shouldn't we drop an entry regardless(as we doing with gradleProperties) was systemProp used in config time?

Comment (mlopatkin) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy:194]: Unlike Gradle properties, tracking of system properties is precise, so if no reads of said property happened at configuration time, its value doesn't affect the work graph. We should still respect the value when executing the build itself, I can see how restoring the system property in the EnvironmentChangeTracker can get in the way, overriding the command-line value with the cached one.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/DefaultEnvironmentChangeTracker.kt [hunk 4]
```diff
@@ -105,19 +119,47 @@ class DefaultEnvironmentChangeTracker(private val problemFactory: ProblemFactory
...
+            return (mutatedSystemProperties[key] as? SystemPropertyLoad)?.oldValue
         }
 
         fun getCachedState(): CachedEnvironmentState {
             return CachedEnvironmentState(
                 cleared = systemPropertiesCleared,
-                updates = mutatedSystemProperties.values.filterIsInstance<SystemPropertySet>(),
+                updates = mutatedSystemProperties.values
+                    .filterIsInstance<SystemPropertySet>()
+                    .filter { it !is SystemPropertyOverride },
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/DefaultEnvironmentChangeTracker.kt:138]: You can change `SystemPropertyOverride` to not being a subclass of `SystemPropertySet` to simplify this chain. Or see the other comment.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/DefaultEnvironmentChangeTracker.kt [hunk 5]
```diff
@@ -105,19 +119,47 @@ class DefaultEnvironmentChangeTracker(private val problemFactory: ProblemFactory
...
                 removals = mutatedSystemProperties.values.filterIsInstance<SystemPropertyRemove>()
             )
         }
 
+        fun systemPropertyOverridden(key: Any, value: Any?) {
+            mutatedSystemProperties[key] = SystemPropertyOverride(key, value)
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/DefaultEnvironmentChangeTracker.kt:144]: Can we avoid having `SystemPropertyOverride` at all, and just remove `key` from `mutatedSystemProperties` here? Here's my understanding. You have `SystemPropertyOverride` binding after root build properties evaluation, when you have `-Dfoo`. Its presence doesn't affect reads of the variable. It seems to matter is `systemPropertyLoaded`, when you're redefining the property for a brief moment. However, you'll get the value from `System.getProperties` as an `oldValue` here anyway. And the next step would be calling `systemPropertyOverridden` again. True, it is important for us not to have `key` in the stored state, but we don't have to actually keep track of the overridden property for that, we can just discard the mapping.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/DefaultEnvironmentChangeTracker.kt [hunk 6]
```diff
@@ -105,19 +119,47 @@ class DefaultEnvironmentChangeTracker(private val problemFactory: ProblemFactory
...
+        }
+
+        fun systemPropertyLoadedByRootBuild(key: Any, value: Any?) {
+            mutatedSystemProperties[key] = SystemPropertyRootLoad(key, value)
+        }
+
+        fun systemPropertyLoaded(key: Any, value: Any?, oldValue: Any?) {
+            val loadedOldValue = when (val loadedSystemProperty = mutatedSystemProperties[key]) {
+                is SystemPropertyRootLoad -> loadedSystemProperty.value
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/DefaultEnvironmentChangeTracker.kt:153]: Isn't `oldValue` always equal to the `loadedSystemProperty.value` in this case? I suppose, system properties from root build are restored outside this class, so we don't have to track system properties in this class as well - we just must not store such system properties as `SystemPropertyLoad`.

**Review by mlopatkin — COMMENTED** [review]
Great job! I still need to take a look at the tests, but here are some comments about the core implementation.

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy [hunk 7]
```diff
@@ -179,15 +180,53 @@ class ConfigurationCacheGradlePropertiesIntegrationTest extends AbstractConfigur
...
+        outputDoesNotContain "because system property '$systemProp' has changed"
         outputContains fixture.expectedOutputBeforeChange
         configurationCache.assertStateLoaded()
 
         cleanup:
-        System.clearProperty('fromPropertiesFile')
+        System.clearProperty("$systemProp")
+    }
+
+    def "passing cli override invalidates cache entry only if property was read at configuration time"() {
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy:195]: Can we maybe split this test into two:
- one that has a read at configuration time to check if the value is expected and cache is properly invalidated.
- one that has no reads, and just checks that adding the `-D` doesn't invalidate the cache.

I think this would simplify the assertions.

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy [hunk 8]
```diff
@@ -179,15 +180,53 @@ class ConfigurationCacheGradlePropertiesIntegrationTest extends AbstractConfigur
...
+        String systemProp = "fromPropertiesFile"
+        def configurationCache = newConfigurationCacheFixture()
+        def fixture = spec.createFixtureFor(this, systemProp)
+        fixture.setup()
+
+        when:
+        fixture.cleanPropertyRun()
+
+        then:
+        fixture.assertAfterFirstRun()
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy:206]: IMO, having more fine-grained assertions in the fixture would make the test a bit more readable. For example, this could be expanded into:
```
configurationCache.assertStateStored()
fixture.assertSystemPropertyHadExpectedConfigurationTimeValue()
fixture.assertSystemPropertyHadExpectedExecutionTimeValue()
```
and for overriden run this would be:
```
configurationCache.assertStateStored()
fixture.assertConfigurationCacheInvalidatedBecauseOfPropertyChange()
fixture.assertSystemPropertyHadOverridenConfigurationTimeValue()
fixture.assertSystemPropertyHadOverridenExecutionTimeValue()
```

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy [hunk 9]
```diff
@@ -179,15 +180,53 @@ class ConfigurationCacheGradlePropertiesIntegrationTest extends AbstractConfigur
...
+        then:
+        configurationCache.assertStateLoaded()
+
+        cleanup:
+        System.clearProperty("$systemProp")
+
+        where:
+        spec << SystemPropertiesCompositeBuildFixture.specs()
     }
 }
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy:232]: It would be great to also have a test that covers mutation of system properties at runtime. For example, `settings.gradle` has `System.setProperty("foo", "bar")`, then calls `includeBuild`, and the included build overrides `foo` with its `gradle.properties`. Then the task in the root build prints the value of the property at execution time.

**Review by mlopatkin — CHANGES_REQUESTED** [review]
I think the overall shape of the solution is now fine, but I have some questions about the tests.

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy [hunk 10]
```diff
@@ -0,0 +1,331 @@
...
+            return "overridden property"
+        }
+
+        @Override
+        String toString() {
+            return "Global"
+        }
+    }
+
+    static interface SystemPropertyDefinition {
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy:145]: I'm also not very happy with this name but my logic is that most important thing is a where system property is defined. `Build` itself can exists normally without system property definition or without `gradle.properties` declared.

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy [hunk 11]
```diff
@@ -0,0 +1,331 @@
...
+    }
+
+    static List<Spec> specs() {
+        [
+            definitions(),
+            [new CliOverride()],
+            SystemPropertyAccess.values()
+        ]
+            .combinations()
+            .findAll { List<SystemPropertyDefinition> definitions, SystemPropertyOverride override, SystemPropertyAccess access ->
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy:42]: Agree, we can

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy [hunk 12]
```diff
@@ -0,0 +1,331 @@
...
+                    case SystemPropertyAccess.ROOT_SETTINGS_SCRIPT:
+                        return definitions.any { it instanceof RootBuildDefinition }
+                    case SystemPropertyAccess.BUILDSRC_BUILD_SCRIPT:
+                    case SystemPropertyAccess.BUILDSRC_SETTINGS_SCRIPT:
+                        return definitions.any { it instanceof BuildSrcDefinition }
+                    case SystemPropertyAccess.INCLUDED_BUILD_SCRIPT:
+                    case SystemPropertyAccess.INCLUDED_SETTINGS_SCRIPT:
+                        return definitions.any { it instanceof IncludedBuildDefinition }
+                    default:
+                        return false
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy:54]: Yeah, it was a WIP state of it :)

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CachedEnvironmentStateCodec.kt [hunk 13]
```diff
@@ -55,9 +56,18 @@ object CachedEnvironmentStateCodec : Codec<DefaultEnvironmentChangeTracker.Cache
     override suspend fun ReadContext.decode(): DefaultEnvironmentChangeTracker.CachedEnvironmentState {
         val cleared = readBoolean()
         val updates = readList {
+            val clazz = readClass()
             val key = read() as Any
             val value = read()
-            DefaultEnvironmentChangeTracker.SystemPropertySet(key, value, PropertyTrace.Unknown)
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CachedEnvironmentStateCodec.kt]: Yes, indeed

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy (hunk 8 above)
Comment (6hundreds) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy:206]: Reasonable

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy [hunk 14]
```diff
@@ -0,0 +1,331 @@
...
+import org.gradle.test.fixtures.file.TestFile
+
+class SystemPropertiesCompositeBuildFixture {
+
+    static Set<List<SystemPropertyDefinition>> definitions() {
+        [
+            new RootBuildDefinition() as SystemPropertyDefinition,
+            new BuildSrcDefinition(),
+            new IncludedBuildDefinition("included-build"),
+            new IncludedBuildDefinition("included-build-2")
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy]: This is true, initially didn't want to overcomplicate definitions providing. Improved now

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy [hunk 15]
```diff
@@ -0,0 +1,331 @@
...
+            return "overridden property"
+        }
+
+        @Override
+        String toString() {
+            return "CLI"
+        }
+    }
+
+    static class GlobalOverride implements SystemPropertyOverride {
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy]: No, I don't

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt [hunk 16]
```diff
@@ -102,11 +113,23 @@ class EnvironmentChangeTracker(private val problemFactory: ProblemFactory) {
         }
 
         override fun toRestoring(): Restoring {
-            return Restoring()
+            return Restoring(
+                mutatedSystemProperties
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt:117]: Can you please add a clarifying comment here, when this happens and why it is important to check overridden properties when restoring? We spent quite a lot of time figuring this out, and I'm not sure that the comment in 196 is enough to recall all the details.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt [hunk 17]
```diff
@@ -156,9 +192,14 @@ class EnvironmentChangeTracker(private val problemFactory: ProblemFactory) {
                 System.getProperties().clear()
             }
 
-            storedState.updates.forEach { update ->
-                System.getProperties()[update.key] = update.value
-            }
+            storedState.updates
+                // If property was overridden after storing we don't want to load it with outdated value
+                .filter { update ->
+                    !overriddenSystemProperties.containsKey(update.key)
```
Comment (mlopatkin) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt:198]: I strongly suspect that the `SystemPropertyMutate` should be left intact, as such value indicates the system property overwritten in the build logic. If the last write was from build logic, then `-D` cannot overwrite it. Unless an included build causes start parameter flags to be reapplied :sob:. But I suggest addressing the latter separately.

```suggestion
                    (update.value is SystemPropertyLoad) && !overriddenSystemProperties.containsKey(update.key)
```

I don't think we have a test for this, as most ways to update system properties are also making them inputs. Could you please add one to `UndeclaredBuildInputsIntegrationTest`? You can use `System.getProperties().putAll(...)` to do the update without adding inputs.

**Review by mlopatkin — CHANGES_REQUESTED** [review]
I think we're good now, the only important thing left is overwriting of the mutated properties when `-D` is used.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt (hunk 17 above)
Comment (mlopatkin) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt:198]: Actually, after looking at the test failures, it looks like we need to be even more careful when considering removals and cleanups here.

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy (hunk 10 above)
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/SystemPropertiesCompositeBuildFixture.groovy:187]: Okay, let's have it!

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt [hunk 18]
```diff
@@ -142,7 +178,7 @@ class EnvironmentChangeTracker(private val problemFactory: ProblemFactory) {
     }
 
     private
-    class Restoring : TrackerMode {
+    class Restoring(private val overriddenSystemProperties: Map<Any, SystemPropertyOverride>) : TrackerMode {
```
[the remark this answers is not in the document]
Comment (6hundreds) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt:181]: Indeed

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt (hunk 17 above)
Comment (6hundreds) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt:198]: But correct condition is `update !is SystemPropertyLoad || !overriddenSystemProperties.contains(update.key)` I guess?

**Comment by 6hundreds** [comment]
@bot-gradle test acc

**Comment by 6hundreds** [comment]
@bot-gradle test this

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt (hunk 17 above)
Comment (mlopatkin) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTracker.kt]: Indeed, it is.

**Review by mlopatkin — APPROVED** [review]
lgtm

**Comment by 6hundreds** [comment]
@bot-gradle test and merge
