### PR TITLE
Document minimal guarantees of Providers with Configuration Cache

### LINKED ISSUE #26363: Document which `Provider`s are resolved at store time when configuration cache is used
### Current Behavior

See below

### Expected Behavior

See below

### Context (optional)

_No response_

### Steps to Reproduce

1. Open the attached project: [ProviderResolvedTooEarly.zip](https://github.com/gradle/gradle/files/12598282/ProviderResolvedTooEarly.zip)

It has the following build script:
```
abstract class CustomTask : DefaultTask() {

    @get:InputFiles
    abstract val inputFiles: ListProperty<File>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun run() {
        check(inputFiles.get().isNotEmpty()) { "inputFiles is empty!" }
        outputFile.get().asFile.writeText("Hello")
    }
}

val fooTask by tasks.registering(CustomTask::class) {
    inputFiles.set(project.provider { listOf(project.file("fooInputFile.txt")) })
    outputFile.set(project.layout.buildDirectory.file("fooOutputFile.txt"))
}

val barTask by tasks.registering(CustomTask::class) {
    // Set fooTask's outputFile as barTask's inputFiles
    val regularFiles: Provider<List<File>> = fooTask.map { listOf(it.outputFile.asFile.get()) }
    inputFiles.set(regularFiles.map {
        println("############### Calling File::isFile ###############")
        it.filter(File::isFile)
    })

    outputFile.set(project.layout.buildDirectory.file("barOutputFile.txt"))
}
```

2. Run `rm -rf .gradle/configuration-cache && ./gradlew cleanFooTask && ./gradlew barTask -i --configuration-cache`. The build will fail with:
```
Execution failed for task ':barTask'.
> inputFiles is empty!
```

The reason is that `File::isFile` is called during task graph creation, i.e. `inputFiles` are resolved before the task execution phase.

3. Run the build again without configuration cache: `./gradlew cleanFooTask && ./gradlew barTask -i`. The build will succeed (`inputFiles` are resolved during task execution phase).

### Gradle version

8.3

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by mlopatkin**
Fully specifying the behavior is a tricky task because there are many corner cases. Instead, we provide a basic set of rules that guarantee compatibility. Everything else may still work.

Fixes #26363.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test BD

**Comment by lkasso** [comment]
@mlopatkin, is the word "flattened" standard/widely recognized or described anywhere?
If no, could we use "computer and store" and/or "computed and cached" instead?

**Comment by mlopatkin** [comment]
> @mlopatkin, is the word "flattened" standard/widely recognized or described anywhere? If no, could we use "computer and store" and/or "computed and cached" instead?

We use it internally, but maybe it isn't the best option here. Perhaps "computed and the value cached" works best, though it would be great to have a term for that, as this concept is used often.

**Comment by lkasso** [comment]
> We use it internally, but maybe it isn't the best option here. Perhaps "computed and the value cached" works best, though it would be great to have a term for that, as this concept is used often.

Ok, I checked the rest of our documentation, and we don't use or define the term anywhere as "computed and the value cached". I am making suggestions to reword the PR so that we don't use "flattened".

File: subprojects/core-api/src/main/java/org/gradle/api/Project.java [hunk 1]
```diff
@@ -1001,6 +1001,21 @@ Project project(String path,
      *
      * <p>The provider is live and will call the {@link Callable} each time its value is queried. The {@link Callable} may return {@code null}, in which case the provider is considered to have no value.
      *
+     * <h4>Configuration Cache</h4>
+     * <p>This provider is always <a href="provider/Provider.html#configuration-cache">flattened</a> by the Configuration Cache.
```
Comment (lkasso) [inline subprojects/core-api/src/main/java/org/gradle/api/Project.java]:
```suggestion
     * <p>This provider is always <a href="provider/Provider.html#configuration-cache">computed and its value is cached</a> by the Configuration Cache.
```

File: subprojects/core-api/src/main/java/org/gradle/api/Script.java [hunk 2]
```diff
@@ -330,6 +330,21 @@ public interface Script {
     /**
      * Creates a {@code Provider} implementation based on the provided value.
      *
+     * <h4>Configuration Cache</h4>
+     * <p>This provider is always <a href="provider/Provider.html#configuration-cache">flattened</a> by the Configuration Cache.
```
Comment (lkasso) [inline subprojects/core-api/src/main/java/org/gradle/api/Script.java]:
```suggestion
     * <p>This provider is always <a href="provider/Provider.html#configuration-cache">computed and its value is cached</a> by the Configuration Cache.
```

File: subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java [hunk 3]
```diff
@@ -74,6 +77,57 @@
  * <b>Note:</b> This interface is not intended for implementation by build script or plugin authors.
  * </p>
  *
+ * <h2 id="configuration-cache">Configuration Cache</h2>
+ * <p>
+ * The <a href="https://docs.gradle.org/current/userguide/configuration_cache.html">Configuration Cache</a> handles providers in a special way.
+ * When a provider is discovered to be part of the cached build configuration (e.g. when it is a task input), one of two things happen:
+ * </p>
+ * <ul>
+ *     <li><b>Flattening</b>: the value of the provider is computed and cached. This typically happens if the provider is derived from purely configuration-time data.</li>
```
Comment (lkasso) [inline subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java]: This works here because it is defined so we can leave the word "flatten".

File: subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java [hunk 4]
```diff
@@ -52,6 +52,21 @@ public interface ProviderFactory {
      *
      * <p>The provider is live and will call the {@link Callable} each time its value is queried. The {@link Callable} may return {@code null}, in which case the provider is considered to have no value.
      *
+     * <h4>Configuration Cache</h4>
+     * <p>This provider is always <a href="provider/Provider.html#configuration-cache">flattened</a> by the Configuration Cache.
```
Comment (lkasso) [inline subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java]:
```suggestion
     * <p>This provider is always <a href="provider/Provider.html#configuration-cache">computed and its value is cached</a> by the Configuration Cache.
```

**Comment by mlopatkin** [comment]
@bot-gradle test BD

**Comment by mlopatkin** [comment]
@lkasso, @gradle/bt-cortex PTAL, the PR may even make it into RC3 😄

**Review by tresat — APPROVED** [review]

File: subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java [hunk 5]
```diff
@@ -74,6 +77,64 @@
...
+ * The Configuration Cache operates under the assumption that most of the stored providers will be used at execution time,
+ * so it attempts to cache values of as many providers as possible without introducing more build configuration inputs.
+ * However, the exact definition of which provider to cache is intentionally left underspecified.
+ * For example, even a provider derived from a system property provider may be cached by value if that system property is already an input.
+ * </p>
+ * <p>
+ * Following the rules below ensures that your Providers remain configuration-cache compatible regardless of applied optimizations.
+ * </p>
+ * <ol>
+ *     <li>Providers returned by {@link ProviderFactory#provider(Callable)} are always computed at configuration time.
```
Comment (alllex) [inline subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java:107]: 💭 Should `Project.provider` get a mention here as well?

File: subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java [hunk 6]
```diff
@@ -74,6 +77,64 @@
...
+ *     The {@code Callable} may capture arbitrary data types and freely call configuration-time-only APIs.
+ *     This is the preferred way to bridge non-lazy and lazy APIs, like passing {@link Project#getVersion()} into task's input {@link Property}.
+ *     </li>
+ *     <li>Any value returned (provided) by the provider must conform to the
+ *     <a href="https://docs.gradle.org/current/userguide/configuration_cache_requirements.html#config_cache:requirements">configuration cache requirements</a>.
+ *     This requirement may not be enforced when the value is an intermediate result and the Configuration Cache runs the computation chain to cache the end result.
+ *     </li>
+ *     <li>Any value captured by the computation of the provider (e.g. a variable captured by the {@code Transformer} lambda supplied to {@link #map(Transformer)})
```
Comment (alllex) [inline subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java:115]: 💭  This rule also has an exception when it comes to `ProviderFactory.provider(Callable)`. We call this out in the rest of the list items but not here.

File: subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java [hunk 7]
```diff
@@ -52,6 +52,21 @@ public interface ProviderFactory {
...
      * <p>The provider is live and will call the {@link Callable} each time its value is queried. The {@link Callable} may return {@code null}, in which case the provider is considered to have no value.
      *
+     * <h4>Configuration Cache</h4>
+     * <p>This provider is always <a href="provider/Provider.html#configuration-cache">computed and its value is cached</a> by the Configuration Cache.
+     * If this provider is created at configuration time, the {@link Callable} may call configuration-time only APIs and capture objects of arbitrary types.
+     * <p>This can be useful when you need to lazily compute some value to use at execution time based on configuration-time only data. For example, you can compute an archive name based on the name
+     * of the project:
+     * <pre class='autoTested'>
+     *   tasks.register("createArchive") {
+     *       def archiveNameProvider = providers.provider { project.name + ".jar" }
```
Comment (alllex) [inline subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java:62]: 💭  This is a concise example, but it's not really exemplary, since project name is something that can be operated on at execution time (if extracted first). The `project.name` is artificial in that sense. Maybe there is some other API that is actually configuration-time-only, and extracting which into a variable would not help?

**Review by alllex — COMMENTED** [review]
It's great to have these docs! 🎉

File: subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java (hunk 7 above)
Comment (mlopatkin) [reply subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java:62]: > Maybe there is some other API that is actually configuration-time-only, and extracting which into a variable would not help?

Thanks, we can add the `project.version` here too. It is mutable, so it cannot be safely extracted. I'll do it in a follow-up PR in 9.1.
