### PR TITLE
Do not run other work together with invalid work

### LINKED ISSUE #15348: Disable parallel execution for work failing validation
Follow up to https://github.com/gradle/gradle/pull/15306
Fixes https://github.com/gradle/gradle/issues/15305

Work not passing validation should not be executed in parallel with other work. Note that for the penalties we impose in https://github.com/gradle/gradle/issues/15305 every validation was included. However, the decision about parallel execution happens earlier, and it should be quick. We will therefore only check the work's type (and the types of its (potentially nested) properties), and their annotations. For disabling parallelism we will not observe the actual values.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by lptr**
Fixes #15348

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QFL please.

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java [hunk 1]
```diff
@@ -76,6 +76,8 @@
     private final String displayName;
     private final TaskNodeFactory taskNodeFactory;
     private final TaskDependencyResolver dependencyResolver;
+    private final NodeValidator nodeValidator;
+    private final ResourceLock invalidNodeRunningLock;
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java:80]: Why do you use a `ResourceLock` here and not a simple boolean?

Comment (lptr) [reply subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java]: That's actually a very good point. I guess claiming "historical reasons" on a draft PR is not realistic, right? :) Anyway, using a `boolean` now.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java [hunk 2]
```diff
@@ -590,9 +594,11 @@ private boolean tryAcquireLocksForNode(Node node, WorkerLeaseRegistry.WorkerLeas
             LOGGER.debug("Cannot acquire worker lease lock for node {}", node);
             return false;
             // TODO: convert output file checks to a resource lock
-        } else if (!canRunWithCurrentlyExecutedNodes(node, mutations)) {
+        } else if (!canRunWithCurrentlyExecutedNodes(mutations)) {
             LOGGER.debug("Node {} cannot run with currently running nodes {}", node, runningNodes);
             return false;
+        } else if (doesDestroyNotYetConsumedOutputOfAnotherNode(node, mutations.destroyablePaths)) {
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java:600]: Can you add a debug message here as well? So every reason has some debug output as before?

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java [hunk 3]
```diff
@@ -644,21 +651,28 @@ private boolean allProjectsLocked() {
...
-            Set<String> candidateNodeOutputs = mutations.outputPaths;
-            Set<String> candidateMutations = !candidateNodeOutputs.isEmpty() ? candidateNodeOutputs : candidateNodeDestroyables;
-            if (hasNodeWithOverlappingMutations(candidateMutations)) {
+    private boolean canRunWithCurrentlyExecutedNodes(MutationInfo mutations) {
+        if (mutations.hasValidationProblem) {
+            if (!runningNodes.isEmpty()) {
+                // Invalid work is not allowed to run together with any other work
                 return false;
             }
+            invalidNodeRunning = true;
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java:660]: The node won't necessarily start running here, since there is still a check afterwards: `doesDestroyNotYetConsumedOutputOfAnotherNode`

I think it would be better to flip this boolean when we are about to return the task we are going to run in `selectNextNode`. WDYT?

**Review by wolfs — CHANGES_REQUESTED** [review]
I left some comments. I am still missing an integration test.

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java (hunk 2 above)
Comment (lptr) [reply subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java:600]: We have a debug message here, that's why I didn't add one:

https://github.com/gradle/gradle/blob/08eabb685333ef21023a2c73fdef15ca695e378e/subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java#L703

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java (hunk 3 above)
Comment (lptr) [reply subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java]: Good point, I moved it a bit higher. I think it's in the right place now.

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java (hunk 2 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java:599]: 👍

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java [hunk 4]
```diff
@@ -600,6 +599,9 @@ private boolean tryAcquireLocksForNode(Node node, WorkerLeaseRegistry.WorkerLeas
         } else if (doesDestroyNotYetConsumedOutputOfAnotherNode(node, mutations.destroyablePaths)) {
             return false;
         }
+        if (mutations.hasValidationProblem) {
+            invalidNodeRunning = true;
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java:603]: I don't think this belongs in `tryAcquireLocksForNode`. Moreover, it is not clear to me that we enter `finishedExecuting()`, where we reset the flag, when we skip the node since some dependencies failed. I think we only should set the flag when we are starting to execute a node.

**Review by wolfs — CHANGES_REQUESTED** [review]

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java (hunk 4 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java:603]: Moreover, it seems like there should be a test for that case: A task with a failed dependency which fails validation shouldn't block executing the remaining tasks.

Comment (lptr) [reply subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java]: We do have two tests, one for not starting an invalid work when any other work is running, and another to test that we don't start any work when invalid work is running. What else do you think we need?

I think the test we have is sufficient, and adding an integration test would be too brittle anyway.

Comment (lptr) [reply subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java]: I moved the flag further.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java (hunk 4 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java]: > We do have two tests

We do not have a single integration test (aka E2E test). We have two unit tests, which I don't think is sufficient.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test this please.

File: subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy [hunk 5]
```diff
@@ -454,4 +463,40 @@ class ParallelTaskExecutionIntegrationTest extends AbstractIntegrationSpec {
...
         }
     }
+
+    def "other tasks are not started when an invalid task task is running"() {
+        given:
+        withParallelThreads(2)
+
+        expect:
+        2.times {
+            executer.expectDocumentedDeprecationWarning("Property 'invalidInput' has @Input annotation used on property of type 'File'. " +
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy:473]: Do you think it makes sense to have a `executer.expectTaskValidationWarning()` method, so we need to repeat fewer things?

File: subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy [hunk 6]
```diff
@@ -454,4 +463,40 @@ class ParallelTaskExecutionIntegrationTest extends AbstractIntegrationSpec {
...
+
+            blockingServer.expect(":aInvalidPing")
+            blockingServer.expectConcurrent(":bPing", ":cPing")
+            run ":aInvalidPing", ":bPing", ":cPing"
+        }
+    }
+
+    def "invalid task is not executed in parallel with other task"() {
+        given:
+        withParallelThreads(2)
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy:487]:
```suggestion
        withParallelThreads(3)
```

This needs to be at least `3`, since if it is only `2` the test won't fail since the two parallel execution slots are taken up by `aPing` and `bPing` and we'll never try to schedule `cInvalidPing` anyway.

**Review by wolfs — COMMENTED** [review]
Looks good, apart from a small change necessary for the E2E test.

File: subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy (hunk 5 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy:473]: Maybe it would have made sense in the past, but given that we're going to remove them in 7.0 I don't think we should introduce it now.

File: subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy (hunk 6 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy:487]: Ah, yes, I originally only had two tasks, and forgot to increase this when adding the third.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

File: subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy (hunk 5 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy:473]: 👍

**Review by wolfs — APPROVED** [review]
LGTM!
