### PR TITLE
Set default value to annotationProcessorGeneratedSourcesDirectory

### LINKED ISSUE #4956: Change the default location for annotation processor generated sources to a source directory
The annotation processors default behavior is to write the generated sources to the `/build/classes/java/<sourceSet>/` folder. This pollutes the compiled classes directory and implementation JAR with source code. Also, the sources are not available in the sources JAR file and are not included as source folders in the IDEs (https://github.com/gradle/gradle/issues/4499).

### Expected Behavior
* The `options.annotationProcessorGeneratedSourcesDirectory` should default to a source directory. For example: `build/generated/src/<sourceSet>/java`
* Gradle should automatically create and clean the generated source directories.
* The generated source directories should be included as source folders in sources in the IDEs (https://github.com/gradle/gradle/issues/4499).
* The generated sources should be included in the `*-sources.jar`

### Current Workaround
Example to configure a different output directory for the main source set in `samples/java/incrementalAnnotationProcessing/user/build.gradle`:
```
compileJava {
    String relativePath = "build/generated/src/main/java"
    sourceSets.main.java { srcDir relativePath }
    File generatedSourceDir = project.file("build/generated/src/main/java")
    println "Creating and configuring generated source directory $generatedSourceDir"
    project.mkdir(generatedSourceDir)
    options.annotationProcessorGeneratedSourcesDirectory = generatedSourceDir
    outputs.dir(generatedSourceDir)
    
    doFirst {
        // force a clean of generatedSourceDir to prevent java.lang.IllegalStateException: endPosTable already set. This shouldn't be need if using Gradle 4.8+ or Java 9+.
        project.delete(generatedSourceDir)
        project.mkdir(generatedSourceDir)
    }
}
```

Related: https://github.com/gradle/gradle/issues/2300

### PR DESCRIPTION
**Pull request by tbroyer**
### Context

Fixes #4956

Annotation processor generated sources should not end up into project artifacts.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by tbroyer** [comment]
Closing/reopening to retrigger the correct checks after base branch change.

File: subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/SourceSetUtil.java [hunk 1]
```diff
@@ -52,13 +53,21 @@ public File call() {
...
+    public static void configureAnnotationProcessorPath(final SourceSet sourceSet, SourceDirectorySet sourceDirectorySet, CompileOptions options, final Project target) {
+        final ConventionMapping conventionMapping = new DslObject(options).getConventionMapping();
+        conventionMapping.map("annotationProcessorPath", new Callable<Object>() {
             @Override
             public Object call() {
                 return sourceSet.getAnnotationProcessorPath();
             }
         });
+        final String annotationProcessorGeneratedSourcesChildPath = "generated/sources/annotationProcessor/" + sourceDirectorySet.getName() + "/" + sourceSet.getName();
+        conventionMapping.map("annotationProcessorGeneratedSourcesDirectory", new Callable<Object>() {
```
Comment (tbroyer) [inline subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/SourceSetUtil.java]: Should this use `setAnnotationProcessorGeneratedSourcesDirectory(Provider<File>)` instead of convention mapping?

**Comment by tbroyer** [comment]
@oehme Do you think this is something that could slip into 5.0, or is it too late?

**Comment by tbroyer** [comment]
Ping @oehme, @wolfs Will this also miss the 5.1 train? (any feedback would be better than none)

File: subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSetOutput.java [hunk 2]
```diff
@@ -85,6 +91,11 @@ public void addClassesDir(Callable<File> classesDir) {
         classesDirs.from(classesDir);
     }
 
+    @Override
+    public ConfigurableFileCollection getAnnotationProcessorGeneratedSourcesDirs() {
```
Comment (oehme) [inline subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSetOutput.java]: I think "getGeneratedSourcesDirs" would be better, so we can expand this to other source generators.

File: subprojects/core-api/src/main/java/org/gradle/api/file/SourceDirectorySet.java [hunk 3]
```diff
@@ -130,4 +130,31 @@
...
     void setOutputDir(File outputDir);
+
+    /**
+     * Returns the directory to place source files generated by annotation processors.
+     *
+     * @return The generated sources directory for this set of sources.
+     * @since 5.1
+     */
+    @Incubating
+    File getAnnotationProcessorGeneratedSourcesDirectory();
```
Comment (oehme) [inline subprojects/core-api/src/main/java/org/gradle/api/file/SourceDirectorySet.java]: ❌ These should not be here. Having `setOutputDir` here was a mistake that we still haven't fixed. A SourceDirectorySet is just what the name says - a set of source directories. It shouldn't know anything about output.

File: subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/SourceSetUtil.java [hunk 4]
```diff
@@ -70,12 +76,26 @@ public File call() {
...
+        }));
+
         DefaultSourceSetOutput sourceSetOutput = Cast.cast(DefaultSourceSetOutput.class, sourceSet.getOutput());
         sourceSetOutput.addClassesDir(new Callable<File>() {
             @Override
             public File call() {
                 return sourceDirectorySet.getOutputDir();
             }
         });
+        sourceSetOutput.getAnnotationProcessorGeneratedSourcesDirs().from(new Callable<File>() {
```
Comment (oehme) [inline subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/SourceSetUtil.java]: Here we should instead do a from(compileTask.options.generatedSourcesDir) and leave out the SourceDirectorySet middle man.

Also we should deprecate the three separate methods on `CompileOptions` and replace them with a single `DirectoryProperty getGeneratedSourcesDir`. This would allow us to track the location and the dependency on the task in one object. Right now the code here only tracks the location, but doesn't track that the task needs to be run. I know this is covered by the very broad `dependsOn(sourceSet.outputs)` right now, but we'll wanna get away from that at some point :)

**Comment by tbroyer** [comment]
> Hey @tbroyer, sorry for the late response, we have a very tight schedule for 5.0/5.1. I'm not sure we should do this change in a minor release, have you considered which use cases this might brake? Right now I can only think of users who hard-coded the expectation of the classes dir somewhere, but maybe you have some other ideas.

Yes, only people who expect generated sources in their classes dir (though I believe most people actually *don't* expect this; see #4956).

> We should wire these generated source directories into the IDE plugins, so users don't have to manually configure those as source directories anymore.

This is a complex subject. See https://github.com/gradle/gradle/issues/2300#issuecomment-369941916
In recent versions of IntelliJ IDEA (I think as far as 2016.3), there's an easy workaround: https://github.com/tbroyer/gradle-apt-plugin/blob/3f7b7d49e4ea361ef5333ced26d51142da5a3d25/README.md#do-without-the-plugin
As soon as you want the IDE to do annotation processing, this can quickly become a problem though (e.g. only one output dir for all languages –I suppose at least–, and in Eclipse only one output dir for the project, i.e. both main and test sources; so you'd better use a separate output dir in this case, like this is done for classes already).

> We also need to think about javadoc and source jars. Right now these would not include the generated sources, which may be a problem. If we wanted them to contain those, we'd have to wire the generated directories into `SourceSet.allJava`. That may be surprising to other consumers though, as that would mean this collection suddenly requires compiling your code before it can be consumed.

It would likely break many "code quality" tools, as they'd start analyzing the generated sources. See https://github.com/gradle/gradle/issues/2300#issuecomment-371473196 and https://github.com/gradle/gradle/issues/2300#issuecomment-399422802

**Comment by oehme** [comment]
So we can only add the generated source dirs if the build is delegated to Gradle, not when IDEA does generation itself and we basically can't do it at all for Eclipse. In that case this is probably better handled by the IDEA model builder (cc @nskvortsov)

Regarding analysis, javadoc, source jar etc I guess we'll have to make a case by case decision. For JavaDoc I'm torn. If you have a processor that generates some public API you want to publish, then you'd certainly want that in your docs. But if we make it the default, the `javadoc` task would depend on `compileJava` for everybody. It might also fail if an annotation processor generates some unexpected javadoc syntax. So maybe we should just document how a user can opt in to it instead.

**Comment by nskvortsov** [comment]
Hi @oehme @tbroyer I'm a bit late for all the discussion. Not sure I understand how exactly could we improve IDEA experience here. We already do import the generated folders as described by `org.gradle.plugins.ide.idea.model.IdeaModule`

**Comment by tbroyer** [comment]
Things are:
* if you delegate build to Gradle, then the compilation tasks' `options.annotationProcessorGeneratedSourcesDirectory` (or `options.generatedSourcesDirectory` as suggested in this PR) can be imported as generated sources; note however that the current model cannot associate generated sources with a source set, so if you "create separate module per source set" and have custom source sets (e.g. integration tests), some generated sources can be associated with the wrong source set, and can fail to "compile" in IDEA due to dependency discrepancies.
* if you don't, but you don't somehow configure IDEA to do annotation processing ⇒ same (and the mis-association of generated sources to custom source sets becomes blocking AFAICT)
* if you do annotation processing in IDEA (which you currently have to configure manually: https://youtrack.jetbrains.com/issue/IDEA-187868), then in the presence of multiple languages (Java, Groovy, Scala), Gradle would likely have separate `options.annotationProcessorGeneratedSourcesDirectory` for each compile task (`compileJava` vs. `compileGroovy` vs. `compileScala`) whereas, AFAIK, IDEA would only have one, so the generated sources cannot be configured automatically by Gradle on the `IdeaModule` model, as that would break this usecase.

For the first two cases, there's an easy workaround (configure the generated sources in the Gradle `IdeaModule` model, with the caveats explained above), but it could be better (https://youtrack.jetbrains.com/issue/IDEA-182577). We're introducing a `generatedSourcesDirs` property on `SourceSetOutput` in this PR, so IDEA could take advantage of it instead of chasing the compile tasks' `options.annotationProcessorGeneratedSourcesDirectory`; this would also solve the caveat with custom source sets.

For the third case though, IDEA would have to choose a separate output folder. IIUC, that's already what it does for the classes directory, for the same reason (separate compilation tasks in Gradle, vs. single compilation step in IDEA).

I suppose that once you support the third case, you'd likely conflate it with the second one; i.e. either you delegate the build to Gradle, and you can use its generated sources (from the `output.generatedSourcesDirs` introduced in this PR), or you consider that annotation processing is done in IDEA and you use a separate output folder (at least if there's more than one language).

**Comment by tbroyer** [comment]
> I'm having a hard time finding how to that properly due to the inversion of dependencies here.

How about we only include the first commit (set a default value for `annotationProcessorGeneratedSourcesDirectory`), possibly also introduce `options.generatedSourcesDir`; and postpone the `SourceSetOutput` change to after 5.1?

**Comment by oehme** [comment]
I'm fine with just changing the default and deferring the API changes, yes.

**Comment by tbroyer** [comment]
Do you need me to update the PR to remove the second commit? Or you can do it on your side? (I have no idea what your actual process is wrt merging PRs, so in case you don't merge them through the GitHub UI…)

Wrt documentation, I didn't find anywhere that would need to be updated.

**Comment by oehme** [comment]
Please update the PR. The documentation is [here](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/dsl/org.gradle.api.tasks.compile.CompileOptions.xml#L81).

**Comment by tbroyer** [comment]
> Please update the PR.

Will do asap.

> The documentation is [here](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/dsl/org.gradle.api.tasks.compile.CompileOptions.xml#L81)

Thanks. I see that `annotationProcessorPath` is still described as `null` there though. I'll update it while I'm at it.

**Comment by tbroyer** [comment]
PTAL.

I'll make the other changes in separate PRs (starting with `options.generatedSourcesDir`, it's relatively easy, except for bridging `setAnnotationProcessorGeneratedSourcesDirectory(Provider<File>)` to a `DirectoryProperty`, it's a bit dirty)

**Comment by oehme** [comment]
@tbroyer Can you please rebase your changes onto the `release` branch?

**Comment by tbroyer** [comment]
Done

**Comment by oehme** [comment]
@tbroyer Please have a look at the failing test cases (mostly outdated path assertions)

**Comment by tbroyer** [comment]
@oehme Correct me if I'm wrong, this is a slightly distinct issue, namely that `JavaCompilerArgumentsBuilder` passes `-s` as soon as `annotationProcessorGeneratedSourcesDirectory` is set, without taking into account the target version, contrary to what it does for `annotationProcessorPath` and `-processorpath`/`-proc:none`. I.e. when `annotationProcessorGeneratedSourcesDirectory` was added, it should have been added into the `if` block encompassible `-processorpath`/`-proc:none`.

**Comment by tbroyer** [comment]
Last commit (in addition to not be signed) breaks `JavaCompilerArgumentsBuilderTest`. Will fix asap (working on it, but might not be able to finish today).

**Comment by oehme** [comment]
Thank you @tbroyer! Unfortunately it was a bit too late for 5.1, so the change will be in Gradle 5.2

**Comment by tbroyer** [comment]
:tada: 

> Unfortunately it was a bit too late for 5.1, so the change will be in Gradle 5.2

Yup, saw that as you changed the target branch back to `master`. No problem, that will let us time to work on that `options.generatedSourcesDir`/`sourceSet.output.generatedSourcesDirs` :wink:

**Comment by oehme** [comment]
I'm not sure it works on `@Nested` objects yet. If it doesn't, then you can use `DefaultTask#newOutputDirectory` to create the property object. That should only be a temporary workaround, ideally nested objects should just work.

**Comment by tbroyer** [comment]
Ah, I found https://github.com/gradle/gradle/issues/6619 that confirms it. `DefaultTask#newOutputDirectory` isn't _special_ anymore, so a temporary workaround could be to cast to `ProducerAwareProperty` and explicitly `attachProducer` (this would mean passing the task to the `CompileOptions` instance though).

I think I'll pass on testing the dependency tracking until it's fixed rather than adding workarounds; or maybe pass on adding that `output.generatedSourcesDirectory` property for now, and do `sourceSet.output.generatedSourcesDirs` first.

**Comment by nskvortsov** [comment]
@tbroyer @oehme I was experimenting with importing `sourceSet.output.generatedSourcesDirs` using Idea import and it produces quite a bit of noise in our integration tests, as this directory appears in basically any project with `java` plugin applied.

What would be the proper way to determine if there is any annotation processing configured (and this directory will be used)? 
I thought about looking up dependencies in relevant configuration name (`<cfg_name>AnnotationProcessor` IIUC) but I could be wrong about it.

**Comment by oehme** [comment]
That's a reasonable approximation, since I assume you control the shape of your integration test projects.
