### PR TITLE
Drop duplicates from GMM

### LINKED ISSUE #24037: Maven artifact referenced only in dependency constraints raises `IllegalStateException: Corrupt serialized resolution result`
Initially found using Gradle 8.0 in the AndroidX repository, but we're seeing similar reports from external users on earlier Gradle versions.

### Expected Behavior
When an artifact is referenced only from Gradle metadata dependency constraints but never as a regular dependency, e.g. a task has a dependency tree where the artifact only appears with `(c)`, Gradle correctly resolves dependencies.

For example, `androidx.lifecycle:lifecycle-common-java8:2.6.0 (c)` shows up in:

```
./gradlew :compose:material3:material3:dependencies --no-configuration-cache --stacktrace

debugRuntimeClasspath - Runtime classpath of compilation 'debug' (target  (androidJvm)).

+--- project :compose:foundation:foundation
|    +--- androidx.compose.animation:animation:1.2.1
|    |    +--- androidx.compose.animation:animation-core:1.2.1 -> 1.3.1
|    |    |    +--- androidx.compose.ui:ui:1.2.0 -> project :compose:ui:ui
|    |    |    |    +--- project :compose:ui:ui-text
|    |    |    |    |    +--- androidx.core:core:1.7.0 -> 1.9.0
|    |    |    |    |    |    +--- androidx.lifecycle:lifecycle-runtime:2.3.1 -> 2.6.0
|    |    |    |    |    |    |    +--- androidx.lifecycle:lifecycle-common:2.6.0
|    |    |    |    |    |    |    |    +--- androidx.lifecycle:lifecycle-common-java8:2.6.0 (c)
```

### Current Behavior
Gradle fails to resolve dependencies unless the constraint-only artifact is added as a regular dependency.

```
./gradlew :compose:material3:material3:dependencies --no-configuration-cache --stacktrace

Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':compose:material3:material3:debugRuntimeClasspath'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:107)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getAllComponents(ErrorHandlingConfigurationResolver.java:248)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies$LenientResolutionResult.getAllComponents(DefaultConfiguration.java:2050)
        ...
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /usr/local/google/home/alanv/.gradle/.tmp/gradle7073241088892806121.bin offset 22066 exists? true
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:136)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:190)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
        ...
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (147) for constraint runtimeElements -> androidx.lifecycle:lifecycle-common-java8:2.6.0
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:83)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:240)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:134)
        ... 242 more
```

### Context
Android Jetpack has started publishing dependency constraints to ensure that related artifacts are correctly versioned; however, this yields confusing errors when constrained artifacts are not present as regular dependencies.

Original bug report on Google Issue Tracker: https://issuetracker.google.com/issues/270635903

### Steps to Reproduce 
Generally, create artifact A that references artifact B as a constraint. Use artifact A as a dependency _without_ using artifact B.

Specifically, this can be reproduced in patch set #7 of https://android-review.git.corp.google.com/c/platform/frameworks/support/+/2449500/7 within the AndroidX repository.

I can work on a minimal repro ZIP if that would be more helpful.

### Your Environment
Gradle version: 8.0
Build scan URL: https://ge.androidx.dev/s/cob7tgpyntvik

### PR DESCRIPTION
**Pull request by ljacomet**
When parsing Gradle Module Metadata, Gradle drops duplicate dependencies
 and constraints declarations.
 This is now consistent with the way Maven metadata is handled.

 Note that this only applies to strict duplicates, declaring a
 dependency on different variants or capabilites remain supported.

 Fixes #24037

### CODE REVIEW

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java [hunk 1]
```diff
@@ -321,12 +321,18 @@ public List<Capability> getCapabilities() {
 
         @Override
         public void addDependency(String group, String module, VersionConstraint versionConstraint, List<ExcludeMetadata> excludes, String reason, ImmutableAttributes attributes, List<? extends Capability> requestedCapabilities, boolean endorsing, @Nullable IvyArtifactName artifact) {
-            dependencies.add(new DependencyImpl(group, module, versionConstraint, excludes, reason, attributes, requestedCapabilities, endorsing, artifact));
+            DependencyImpl dependency = new DependencyImpl(group, module, versionConstraint, excludes, reason, attributes, requestedCapabilities, endorsing, artifact);
+            if (!dependencies.contains(dependency)) {
```
Comment (big-guy) [inline subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java:325]: Should we consider switching `dependencies` (and `dependencyConstraints`) to a `LinkedHashSet`? This is changing from amortized O(1) insert to O(n) search + insert.  IIUC, this may only show up as a problem in modules with "lots" of direct dependencies or constraints.

**Comment by ljacomet** [comment]
@bot-gradle test this

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java (hunk 1 above)
Comment (ljacomet) [reply subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java]: Ended up moving the de-duplication logic and using a `LinkedHashSet` in a class where that collection is only needed in a temporary fashion.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParser.java [hunk 2]
```diff
@@ -641,6 +644,33 @@ private static class ModuleDependency {
             this.endorsing = endorsing;
             this.artifact = artifact;
         }
+
+        @Override
+        public boolean equals(Object o) {
```
Comment (tresat) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParser.java:649]: 💭 Since it's important that the `ModuleDependency` and `ModuleDependencyConstraint` types continue to properly identify duplicates, so they can be excluded from the set, is it worth also building unit tests to ensure proper equals/hashcode behavior?

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParser.java
Comment (tresat) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParser.java:1]: ❕ It would be really easy for someone to come along and "optimize" the `consumeX` methods by getting rid of the "extraneous" extra collections and populating an  `ArrayList` to be returned directly, as the code did previously.  

I think there should be javadoc on the `ModuleDependency` and `ModuleDependencyConstraint` types saying they must remain properly hashable in order to make the `consumeX` method work, and javadoc on the `consumeX` methods or comments near the collections saying there are typed as such in order to automatically filter any duplicates which could exist.

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java [hunk 3]
```diff
@@ -526,12 +526,14 @@ public boolean equals(Object o) {
                 && Objects.equal(excludes, that.excludes)
                 && Objects.equal(reason, that.reason)
                 && Objects.equal(attributes, that.attributes)
-                && Objects.equal(requestedCapabilities, that.requestedCapabilities);
+                && Objects.equal(requestedCapabilities, that.requestedCapabilities)
+                && Objects.equal(endorsing, that.endorsing)
+                && Objects.equal(dependencyArtifact, that.dependencyArtifact);
```
Comment (tresat) [inline subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java:531]: ❔ Is it concerning at all that changing the definition of equals here didn't break any tests?

**Review by tresat — APPROVED** [review]
It seems like this change fixes the problem well, but I really think this PR could do more to document the reasons for the change, and provide some breadcrumbs for future devs trying to understand the why of this.

These concerns shouldn't hold up merging, but might be worth circling back to address later.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/PublishedDependencyConstraintsIntegrationTest.groovy [hunk 4]
```diff
@@ -541,4 +542,100 @@ dependencies {
         }
     }
 
+    @Issue("https://github.com/gradle/gradle/issues/24037")
+    @RequiredFeature(feature = GradleMetadataResolveRunner.GRADLE_METADATA, value="true")
+    void "duplicate constraint going back to pending not leave hanging edge"() {
```
[the remark this answers is not in the document]
Comment (ljacomet) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/PublishedDependencyConstraintsIntegrationTest.groovy:547]: "Pending dependencies" is how we name discovered constraints that are not active because there is no concrete dependency to that module. It is used in code, see `PendingDependenciesVisitor`, and test names in multiple places.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/PublishedDependencyConstraintsIntegrationTest.groovy [hunk 5]
```diff
@@ -541,4 +542,100 @@ dependencies {
...
+        when:
+        repository {
```
[the remark this answers is not in the document]
Comment (ljacomet) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/PublishedDependencyConstraintsIntegrationTest.groovy:549]: This is the minimal graph that I could reproduce the issue with. Number of dependencies, and their depth and graph shape all matter in creating the right combination of evaluation.
Maybe a couple constraints are spurious, but the time to figure that out and clean 0 or a couple lines does not feel like a good compromise.

**Comment by ljacomet** [comment]
@tresat What more information would you provide?
I have commit message that link to the issue which has an analysis of the situation.

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java (hunk 3 above)
Comment (ljacomet) [reply subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java:531]: Honestly, I am not sure we use that contract much for that type. It could be a follow up investigation, but I believe we have more specific resolution issues to handle first.

**Comment by ljacomet** [comment]
@tresat I have updated the PR with docs and more tests. Let me know if this matches what you expected.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParser.java [hunk 6]
```diff
@@ -435,6 +444,15 @@ private List<VariantCapability> consumeCapabilities(JsonReader reader, boolean v
         return capabilities.build();
     }
 
+    /**
+     * Consume the dependency constraints of a given variant.
+     * <p>
+     * This method needs to remove any duplicates from said constraints.
+     *
+     * @param reader The Json to read from
+     * @return a list of dependencies
```
Comment (tresat) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParser.java:453]: 🧐 list of constraints

**Review by tresat — APPROVED** [review]
Thanks for the extra docs and tests, I think they're helpful.

**Review by big-guy — APPROVED** [review]

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParser.java (hunk 6 above)
Comment (ljacomet) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParser.java:453]: 🤦

File: subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParserTest.groovy [hunk 7]
```diff
@@ -869,6 +871,32 @@ class GradleModuleMetadataParserTest extends Specification {
...
+        then:
+        newFields == []
+    }
+
+    def "new fields in ModuleDependencyConstraint are added to equals and hashcode"() {
+        when:
+        // If this test fails, you added a field to GradleModuleMetadataParser.ModuleDependencyConstraint, add it here _after_ making sure it is considered by hashcode and equals
+        def knownFields = ["group", "module", "versionConstraint", "reason", "attributes"]
+        def modDepClass = GradleModuleMetadataParser.ModuleDependencyConstraint.class
+        def newFields = Arrays.stream(modDepClass.getDeclaredFields()).filter { !knownFields.contains(it.getName()) }
```
[the remark this answers is not in the document]
Comment (ljacomet) [reply subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParserTest.groovy:892]: Added the hierarchy test, in a similar spirit. I think that's better than adding an extra dependency.

**Comment by ljacomet** [comment]
I have moved this back to 8.1 RC2 since we have confirmation that there is [existing metadata](https://dl.google.com/android/maven2/androidx/lifecycle/lifecycle-runtime-ktx/2.6.0-rc01/lifecycle-runtime-ktx-2.6.0-rc01.module) out there with duplicate constraints.

**Comment by ljacomet** [comment]
@bot-gradle test and merge
