### PR TITLE
Reproduce and fix #34349

### LINKED ISSUE #34349: Gradle 9 (undocumented ?) change: compileJava output automatically updates sourceset destination dir
### Current Behavior

setting compileJava output dir irreversibly changes sourceset destination dir

### Expected Behavior

setting compileJava output dir should not automatically change the  sourceset destination dir or at least there should be a way to prevent or revert that change. See context for details why I think this is needed.

### Context (optional)

I did not find anything concerning this change in the update notes.

(copied from https://discuss.gradle.org/t/gradle-9-regression-cannot-inject-class-file-instrumentation-task-after-compilejava/51357):

How should I make my plugin that adds class file instrumentation to the output of classes compiled by compileJava work in Gradle 9?

Before Gradle 9, this was simple and worked:

- change the compileJava output dir to an intermediate directory
- use that intermediate directory as input directory for my custom task
- use the original output directory (main/classes) as the output directory of my custom task
- finalize compileJava by calling my custom task

This does not work in Gradle 9 anymore because whenever the compileJava output dir is changed, the sourceset main destination dir instantly reflects that change. What happens is that my processed classes are stored in the correct location, but all tasks (for example jar, test) that work on the sourceset main output use the classes from the intermediate dir, which contains the unprocessed classes.

Solutions that do not work:

- process files in place: breaks task caching because only a single task may produce a specific output when task caching is enabled.
- have my task copy the generated class files to an intermediate directory before processing: same as above
- changing the default compile spec: hard coded in a private method
- changing compiler options: I didn’t try yet, but I think the output dir will be set when the compile task is run
- just have compileJava output to a new directory, and have my task write the classes write to the standard directory and then reconfigure every Gradle task that consumes sourceset main output to instead use my tasks output (dirty hack and not realistically doable).
- simply changing the sourceset destination dir after task are created and wired: there’s no method (like setClassesDir()) to do that.

-----

Sorry, I know I should provide a better minimal example, but I have already lost three days trying to figure out what change caused the breakage and then trying to work around this. I have to catch up with my day job first, but I really think this is an important silently breaking change and wanted to make you aware of it before Gradle 9 final is released.

### Self-contained Reproducer Project

https://github.com/xzel23/cabe.git at Commit f84188c

Works on Gradle 8.14.3

### Gradle version

9.0.0-rc-3

### Gradle version that used to work

8.14.3

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by big-guy**
fixes #34349 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

File: platforms/jvm/plugins-java-base/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java [hunk 1]
```diff
@@ -86,7 +86,8 @@ public static void configureOutputDirectoryForSourceSet(final SourceSet sourceSe
         sourceDirectorySet.getDestinationDirectory().convention(target.getLayout().getBuildDirectory().dir(sourceSetChildPath));
 
         DefaultSourceSetOutput sourceSetOutput = Cast.cast(DefaultSourceSetOutput.class, sourceSet.getOutput());
-        sourceSetOutput.getClassesDirs().from(sourceDirectorySet.getClassesDirectory());
+        sourceSetOutput.getClassesDirs().from(sourceDirectorySet.getDestinationDirectory());
```
Comment (tresat) [inline platforms/jvm/plugins-java-base/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java:89]: 💅 Can we leave a comment here linking the issue?  This code seems like a prime candidate for someone to discover and try to simplify in the future.

File: platforms/jvm/plugins-java/src/integTest/groovy/org/gradle/api/plugins/JavaCompilationOutputsIntegrationTest.groovy [hunk 2]
```diff
@@ -0,0 +1,149 @@
...
+                doLast {
+                    if (!classpath.contains(expectedDir.get().asFile)) {
+                        throw new GradleException("Test classpath is not set correctly: " + classpath.asPath)
+                    }
+                }
+            }
+        """
+    }
+    @Issue("https://github.com/gradle/gradle/issues/34349")
+    def "rewiring output of source set and compile tasks sort of works"() {
```
Comment (tresat) [inline platforms/jvm/plugins-java/src/integTest/groovy/org/gradle/api/plugins/JavaCompilationOutputsIntegrationTest.groovy]:
```suggestion
    def "rewiring output of source set and compile tasks works using a direct dependency (not recommended)"() {
```

File: platforms/jvm/plugins-java-base/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java (hunk 1 above)
Comment (ljacomet) [reply platforms/jvm/plugins-java-base/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java:89]: IMO you do that by looking at why it is there and thus the commit comment should be the clue.

File: platforms/jvm/plugins-java/src/integTest/groovy/org/gradle/api/plugins/JavaCompilationOutputsIntegrationTest.groovy (hunk 2 above)
Comment (ljacomet) [reply platforms/jvm/plugins-java/src/integTest/groovy/org/gradle/api/plugins/JavaCompilationOutputsIntegrationTest.groovy]: Applied by hand as otherwise I sign off with the wrong email
