### PR TITLE
Discard `cd` output in unix wrapper shell script

### LINKED ISSUE #25036: The gradle wrapper shell script fails to run when $CDPATH is set (and used to change directoy)
### Expected Behavior

The application should be called by the shell wrapper

### Current Behavior

The shell variable CDPATH is set. The wrapper is called by relative path and fails 
```
gradle-8.1.1$ echo $CDPATH 
.:~
gradle-8.1.1$ LANG=C bin/gradle --help
xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
Error: Could not find or load main class org.gradle.launcher.GradleMain
Caused by: java.lang.ClassNotFoundException: org.gradle.launcher.GradleMain
```
This is caused by the "cd" command used to set the to $APP_HOME (line 86). Indeed when "cd" uses $CDPATH to find the directory it prints the whole path to stdout (and nothing if CDPATH is not used). ie,
```
gradle-8.1.1$ cd bin
/tmp/gradle/gradle-8.1.1/bin
gradle-8.1.1/bin$ cd ..
gradle-8.1.1$ cd ./bin
gradle-8.1.1/bin$ 
```

A simple fix is to discard "cd" output
```
gradle-8.1.1$ diff -u bin/gradle{,.new}
--- bin/gradle	2023-05-10 23:21:08.761627970 +0200
+++ bin/gradle.new	2023-05-11 00:40:18.808035689 +0200
@@ -83,7 +83,7 @@
 # This is normally unused
 # shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
+APP_HOME=$( cd "${APP_HOME:-./}.." > /dev/null && pwd -P ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
``

### Context (optional)

_No response_

### Steps to Reproduce

see above

### Gradle version

8.1.1

### Build scan URL (optional)

_No response_

### Your Environment (optional)

Checked on bash and dash on linux. It should occur too with ksh, zsh, and any shell that supports CDPATH

### PR DESCRIPTION
**Pull request by bdecroix-spiria**
Fixes #25036

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation

### CODE REVIEW

File: subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/UnixStartScriptGeneratorTest.groovy [hunk 1]
```diff
@@ -50,6 +51,20 @@ class UnixStartScriptGeneratorTest extends Specification {
         destination.toString().contains(TextUtil.unixLineSeparator)
     }
 
+    @Issue("https://github.com/gradle/gradle/issues/25036")
+    def "unix script ignores output from cd command"() {
```
Comment (octylFractal) [inline subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/UnixStartScriptGeneratorTest.groovy:55]: I feel like this test is too heavily tied to the implementation of the script. It would be better to actually run a generated copy of the script and see if it produces unwanted output, i.e. test the expected behavior, not the solution.

**Review by octylFractal — COMMENTED** [review]
LGTM, but I think the test should be changed.

File: subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/UnixStartScriptGeneratorTest.groovy (hunk 1 above)
Comment (bdecroix-spiria) [reply subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/UnixStartScriptGeneratorTest.groovy:55]: FYI, this is a regression coming from [this commit](https://github.com/kurahaupo/gradle/commit/e3c8398bc51b48b988cb34846984720db13bddd9#diff-a549a2629a3d96f76e3f043a1526e48fb086e90e9d9d03ae0f7abf6d3e803333L37-R43). You can see the redirection to `/dev/null` was present before the refactor.

Given the complexity of testing this very special case, would it be acceptable to submit a new PR without a test and simply add a comment in the code?

Comment (octylFractal) [reply subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/UnixStartScriptGeneratorTest.groovy:55]: I think making those changes in this PR should be fine.

**Review by ghale — APPROVED** [review]
LGTM

**Comment by octylFractal** [comment]
@bot-gradle test and merge
