### PR TITLE
Avoid storing metadata rules in the in-memory cache

### LINKED ISSUE #13497: Component metadata rules with injected services leak project references
We inject an `ObjectFactory` in a `ComponentMetadataRule`:

```
    static class IvyVariantDerivationRule implements ComponentMetadataRule {

        @Inject
        ObjectFactory getObjects() { }
```

That results in an `__objects__` field on the generated `$Inject` class causing project reference leaks in the daemon:

Screen Shot 2020-06-17 at 2 29 00 PM

We're configuring this by class, as it's intended to be a cachable rule (which I guess would also leak this reference if it weren't on this path):

```
project.dependencies.components.all(IvyVariantDerivationRule)
```

### Expected Behavior
Class-based component metadata rules provide a safe way of using project-scoped services without leaking references to them.

### Current Behavior
Project references are retained causing memory leaks.

### Steps to Reproduce 
- Configure a class based rule, injecting a project scoped service that holds a reference to the project, such as `ObjectFactory`
- Run a build
- Take a heap dump and notice that there are live references to `DefaultProject_Decorated` instances 

### Your Environment
Gradle 6.5

### PR DESCRIPTION
**Pull request by melix**
This commit avoids storing the component metadata rules when
we store component metadata in the in-memory cache. While this
shouldn't be necessary in practice because the in-memory cache
only lives for a build, it's possible that the instance is
actually only freed once we reach enough memory pressure, which
means we can unnecessarily keep project references in memory.

It's more problematic if the rule is a `@CacheableRule` but even in
this case, we retain _weak references_ to the cached metadata.

This commit gives more chances to release the memory of projects
earlier, which may be important for larger projects.

Fixes #13497

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyJvmLibraryArtifactResolutionIntegrationTest.groovy [hunk 1]
```diff
@@ -42,7 +42,7 @@ repositories {
 }
 """
     }
-
+/*
```
Comment (ljacomet) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyJvmLibraryArtifactResolutionIntegrationTest.groovy:45]: I guess these should be reverted

**Comment by melix** [comment]
@bot-gradle test this
