### PR TITLE
Finding Gradle sources intelligently in SourceDistributionProvider

### LINKED ISSUE #27863: SourceDistributionProvider contains hardcoded distributionUrl referring to https://services.gradle.org
### Current Behavior

I reset distributionUrl ,but it  not work correctly in IDEA, but it will build successfully in terminal

image

### Expected Behavior

all to  donwload gradle-x.zip will use my set up distributionUrl  in IDEA 

### Context (optional)

https://youtrack.jetbrains.com/issue/IDEA-344183/Ive-set-up-a-proxy-image-for-gradle-but-IDEA-doesnt-actually-use-proxies-everywhere.

### Steps to Reproduce

https://github.com/aohanhongzhi/JavalinDemo-Kotlin

### Gradle version

8.0 and 8.5

### Build scan URL (optional)

https://gradle.com/s/eqdlih3yq5elk

### Your Environment (optional)

ubuntu , window , macos

### PR DESCRIPTION
**Pull request by kelemen**
Currently Gradle has the `https://services.gradle.org/distributions(-snapshots)` URL hardwired when the IDE is downloading the sources of Gradle. This is a problem for people sitting behind a strict proxy. This PR aims to solve this problem using the following strategy (in preference order):

1. The URL, artifact pattern and credentials can be specified in new Gradle properties which are always used when set.
2. The wrapper URL is read from `gradle-wrapper.properties`, and when its hostname is `services.gradle.org`, then we fallback to the old behavior. This is to take the least risk with currently working setups.
3. If the filename in the wrapper URL matches the same pattern as in the official repository, then we will use the base URL (URL without the filename) as the repository and expect the sources under that URL.

The change also recognizes the credentials set in `gradle.wrapperUser` and `gradle.wrapperPassword`.

* Fixes #27863. 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ljacomet** [comment]
Thank you for your proposed contribution!

This PR has a valid DCO and tests. The relevant team for this area will confirm the design of the implementation choices.

**Comment by eskatos** [comment]
Hi Attila,
Thank for the PR. This is looking good.
Adding new system/gradle properties raises questions. We should be careful not adding too many knobs.
Could you consider reducing this PR to all the other changes as a first step?
Namely 2/ and 3/. They make sense on their own and provide a good enhancement already.

**Comment by kelemen** [comment]
@eskatos Sure, I will remove the system properties from this PR. Do you want me to open a new PR on top of these changes to include system properties so that you can independently consider them?

Also, I have seen that bearer token support was added in the mean time for the Gradle wrapper, so I will add the bearer token support here as well for consistency.

**Comment by kelemen** [comment]
I have updated the PR with the following changes to the previous state:

1. It is not longer possible to customize the source distribution URL via Gradle properties. Either we can automatically transform the distribution URL or fallback to the default.
2. Supports the same authorization mechanism as the wrapper (that is, supports bearer tokens as well). The shared wrapper code was refactored to rely on the same code (as much as possible) to configure the authorization mechanism.
3. While making the authorization configuration shared, I have removed the reflection hack from the wrapper, because the wrapper now requires Java 8 anyway, so `Base64` is always available.
4. I was forced to add some `jspecify` annotations into `wrapper-shared`, I hope that is fine.

As previously mentioned, I can open a separate PR for making the URLs fully customizable on top of these changes if needed.

File: platforms/core-configuration/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/internal/GradleDistRepoDescriptorLocator.kt [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+            val header = credentials.authorizationHeader()
+            name = header.key
+            value = header.value
+        }
+    }
+}
+
+data class GradleDistVersion(
+    val versionStr: String,
+    val snapshot: Boolean = versionStr.contains('+')
```
Comment (eskatos) [inline platforms/core-configuration/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/internal/GradleDistRepoDescriptorLocator.kt]: 💅 Let's name this `isSnapshot`

**Comment by eskatos** [comment]
@bot-gradle test RFN without PTS

**Comment by kelemen** [comment]
I have updated the wrapper jar hash in the tests in a separate commit. Tell me if you want to squash the commits.

**Review by eskatos — APPROVED** [review]
LGTM!

**Comment by eskatos** [comment]
No need to squash, thanks.
I amended with a few refinements.
I'll send this for merge now.

**Comment by eskatos** [comment]
Thank you Attila, this will be in Gradle 9.4.0
