### PR TITLE
Use case insensitive matching in VFS dependent on file system

### LINKED ISSUE #11263: Investigate failure of `AssemblyLanguageIncrementalBuildIntegrationTest.does not re-execute build with no change`
The test started failing after https://github.com/gradle/gradle/pull/10975 has been merged.

### PR DESCRIPTION
**Pull request by wolfs**
Fixes #11263.

### CODE REVIEW

**Comment by wolfs** [comment]
Performance tests are passing, though there are some small regressions which we should accept: https://builds.gradle.org/viewLog.html?buildId=28619191&buildTypeId=Gradle_Check_PerformanceTestCoordinator

@lptr PTAL!

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy [hunk 1]
```diff
@@ -272,28 +272,28 @@ class SnapshotTaskInputsOperationIntegrationTest extends AbstractIntegrationSpec
...
+                        hash != null
+                    }
+                }
+                with(children[1]) {
+                    path == "A.java"
+                    hash != null
+                }
+                with(children[2]) {
+                    path == "B.java"
+                    hash != null
```
Comment (lptr) [inline subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy]: ❓This changed because the ordering of the file walking has changed, right?

File: subprojects/language-native/language-native.gradle.kts [hunk 2]
```diff
@@ -89,3 +89,7 @@ gradlebuildJava {
 classycle {
     excludePatterns.set(listOf("org/gradle/language/nativeplatform/internal/**"))
 }
+
+tasks.named<Test>("integMultiVersionTest").configure {
+    include("org/gradle/language/assembler/AssemblyLanguageIncrementalBuildIntegrationTest.class")
+}
```
Comment (lptr) [inline subprojects/language-native/language-native.gradle.kts]: ❓ Why do we need to list this explicitly?

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 3]
```diff
@@ -20,9 +20,29 @@
...
+import static org.gradle.internal.snapshot.CaseSensitivity.CASE_INSENSITIVE;
+import static org.gradle.internal.snapshot.CaseSensitivity.CASE_SENSITIVE;
+
+/**
+ * Methods for dealing with paths on the file system.
+ *
+ * There are methods for checking equality and for comparing two paths.
+ * All methods for equality and comparing need to be called with the correct case-sensitivity according to the underlying file system.
+ *
+ * For comparing, the order is defined in a way that if a list of paths is sorted on a case-insensitive file system it is also sorted on a case-sensitive file system.
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]:
```suggestion
 * For comparing, a list of paths is sorted in the same order on a case-insensitive and a case-sensitive file system.
```

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 4]
```diff
@@ -74,31 +143,39 @@ static int compareChars(char char1, char char2) {
                 : -1
             : isFileSeparator(char2)
                 ? 1
-                : Character.compare(char1, char2);
+                : char1 - char2;
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: I think it would be better to leave the original code here. It is going to be inlined anyway, yet the code reads much better that way.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 5]
```diff
@@ -74,31 +143,39 @@ static int compareChars(char char1, char char2) {
...
     }
 
-    private static boolean equalChars(char char1, char char2) {
+    @VisibleForTesting
+    static boolean equalChars(char char1, char char2, boolean caseSensitive) {
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Let's use `CaseSensitivity` here, too.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 6]
```diff
@@ -119,28 +196,94 @@ public static int sizeOfCommonPrefix(String path1, String path2, int offset) {
         return lastSeparator;
     }
 
-    public static int compareWithCommonPrefix(String path1, String path2, int offset) {
+    /**
+     * Compares based on the first prefix of two paths.
+     *
+     * The paths must not start with a separator, taking into account the offset
+     *
+     * @return 0 when the two paths have a common prefix, and the comparison of the first prefix if not.
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: This sentence needs clarifying.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 7]
```diff
@@ -119,28 +196,94 @@ public static int sizeOfCommonPrefix(String path1, String path2, int offset) {
         return lastSeparator;
     }
 
-    public static int compareWithCommonPrefix(String path1, String path2, int offset) {
+    /**
+     * Compares based on the first prefix of two paths.
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: I don't understand what this means. Can you elaborate?

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 8]
```diff
@@ -119,28 +196,94 @@ public static int sizeOfCommonPrefix(String path1, String path2, int offset) {
...
         }
         if (path1.length() > path2.length() - offset) {
-            return isFileSeparator(path1.charAt(maxPos)) ? 0 : 1;
+            return isFileSeparator(path1.charAt(maxPos)) ? accumulatedValue : 1;
+        }
+        return isFileSeparator(path2.charAt(maxPos + offset)) ? accumulatedValue : -1;
+    }
+
+    /**
+     * Determines whether a path starting at an offset has the given prefix,
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: It would be good to explain how we use this `String path` + `int offset` thing for optimization. (It would be even better to capture this behavior in a class of its own, and perhaps move many of the methods defined here in `PathUtil` to that class.)

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 9]
```diff
@@ -161,10 +304,10 @@ private static int lastIndexOfSeparator(String absolutePath) {
     }
 
     /**
-     * This uses an optimized version of {@link String#regionMatches(int, String, int, int)}
-     * which does not check for negative indices or integer overflow.
+     * Checks whether the filePath starting at the offset has the given prefix.
      */
-    public static boolean isChildOfOrThis(String filePath, int offset, String prefix) {
+    public static boolean isChildOfOrThis(String prefix, String filePath, int offset, CaseSensitivity caseSensitivity) {
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Can we capture "child-of or this" in a single term somehow? It is used in several places, and it's really confusing.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java [hunk 10]
```diff
@@ -26,44 +26,55 @@
...
+                if (PathUtil.isChildOfOrThis(secondChild.getPathToParent(), filePath, offset, caseSensitivity)) {
+                    return getSnapshotFromChild(filePath, offset, secondChild, caseSensitivity);
                 }
                 return noChildFoundResult.get();
             default:
-                int foundChild = SearchUtil.binarySearch(children, child -> PathUtil.compareToChildOfOrThis(child.getPathToParent(), filePath, offset));
-                return foundChild >= 0
-                    ? getSnapshotFromChild(filePath, offset, children.get(foundChild))
-                    : noChildFoundResult.get();
+                if (numberOfChildren < 10) {
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java]: Magic number should be extracted to constant and documented.

Comment (lptr) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java]: Also, should this be perhaps something that `SearchUtil.binarySearch()` does internally? Maybe rename the method, too?

All we should care about here is to find the thing, how that happens should belong to the search method. Also, if this optimization is useful, then it will be useful for other callers of `SearchUtil`, too.

We could add more cases, like `size = 0`, `size = 1`, `2 <= size < 10`, `default`?

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultVirtualFileSystem.java [hunk 11]
```diff
@@ -43,16 +44,17 @@
...
     private final DirectorySnapshotter directorySnapshotter;
     private final FileHasher hasher;
     private final StripedProducerGuard<String> producingSnapshots = new StripedProducerGuard<>();
 
-    public DefaultVirtualFileSystem(FileHasher hasher, Interner<String> stringInterner, Stat stat, String... defaultExcludes) {
+    public DefaultVirtualFileSystem(FileHasher hasher, Interner<String> stringInterner, Stat stat, boolean caseSensitive, String... defaultExcludes) {
         this.stat = stat;
         this.directorySnapshotter = new DirectorySnapshotter(hasher, stringInterner, defaultExcludes);
         this.hasher = hasher;
+        this.root = new AtomicReference<>(DefaultFileHierarchySet.empty(caseSensitive ? CaseSensitivity.CASE_SENSITIVE : CaseSensitivity.CASE_INSENSITIVE));
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultVirtualFileSystem.java]: Why not take `CaseSensitivity` instead of the `boolean` parameter?

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/FileHierarchySet.java [hunk 12]
```diff
@@ -62,4 +43,7 @@ public FileHierarchySet invalidate(String path) {
 
     @CheckReturnValue
     FileHierarchySet invalidate(String path);
+
+    @CheckReturnValue
+    FileHierarchySet empty();
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/FileHierarchySet.java]: Does this need to be public?

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/UnknownSnapshotTest.groovy [hunk 13]
```diff
@@ -22,12 +22,13 @@ import org.spockframework.mock.IMockInvocation
 import spock.lang.Specification
 
 class UnknownSnapshotTest extends Specification {
+    def caseSensitivity = CaseSensitivity.CASE_SENSITIVE
```
Comment (lptr) [inline subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/UnknownSnapshotTest.groovy]: Why not inline this?

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/AbstractVirtualFileSystemTest.groovy [hunk 14]
```diff
@@ -46,7 +46,7 @@ abstract class AbstractVirtualFileSystemTest extends Specification {
 
     def fileHasher = new AllowingHasher(TestFiles.fileHasher())
     def stat = new AllowingStat(TestFiles.fileSystem())
-    def vfs = new DefaultVirtualFileSystem(fileHasher, new StringInterner(), stat)
+    def vfs = new DefaultVirtualFileSystem(fileHasher, new StringInterner(), stat, true)
```
Comment (lptr) [inline subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/AbstractVirtualFileSystemTest.groovy]: Enums are so much superior!

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy (hunk 1 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy]: Exactly. `A.java` is not before `a` any more, but the other way round.

File: subprojects/language-native/language-native.gradle.kts (hunk 2 above)
Comment (wolfs) [reply subprojects/language-native/language-native.gradle.kts]: We don't need it. I left it for testing something on CI, looks like I forgot to remove it. Reverted.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultVirtualFileSystem.java (hunk 11 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultVirtualFileSystem.java]: Passing `CaseSensitivity` now.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/FileHierarchySet.java (hunk 12 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/FileHierarchySet.java]: It is currently used here: https://github.com/gradle/gradle/blob/7d4f7be09923d3339af87d1ef045b983037e958e/subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultVirtualFileSystem.java#L173

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/UnknownSnapshotTest.groovy (hunk 13 above)
Comment (wolfs) [reply subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/UnknownSnapshotTest.groovy]: Inlined.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 4 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Using `Character.compare` again.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 5 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Done.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java (hunk 10 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java]: The optimization here is useful since
- the method to check equality is substantially faster than the comparison method
- we are only interested in whether we find the child or not and don't require an insertion point.

All the other usages of binary search require an insertion point if the entry isn't found, so binary search will always be faster.

We could add the 0/1/2 child special cases to binary search, though I am not sure if that would make things faster. For the current method, we already have the special cases `size = 0`, `size = 1`, `size = 2`, `3 <= size < 10`, `default`.

Comment (lptr) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java]: 👍Let's just name the number then.

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/CaseInsensitivePathUtilTest.groovy [hunk 15]
```diff
@@ -29,8 +29,8 @@ class CaseInsensitivePathUtilTest extends AbstractCasePathUtilTest {
         char char1 = left as char
         char char2 = right as char
         expect:
-        equalChars(char2, char1, false)
-        equalChars(char1, char2, false)
+        equalChars(char2, char1, CaseSensitivity.CASE_INSENSITIVE)
+        equalChars(char1, char2, CaseSensitivity.CASE_INSENSITIVE)
```
Comment (lptr) [inline subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/CaseInsensitivePathUtilTest.groovy]: Maybe use static import for this? I think it would make sense to do it probably everywhere.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java (hunk 10 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java]: I named the number. I added special cases for 0 and 1 elements in `binarySearch` as well, let's see if that has any effect on performance.

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/CaseInsensitivePathUtilTest.groovy (hunk 15 above)
Comment (wolfs) [reply subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/CaseInsensitivePathUtilTest.groovy]: I added the static import.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 8 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: I introduced a separate class in https://github.com/gradle/gradle/pull/11378. I would prefer to merge this PR, and then do the extraction. WDYT?

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 16]
```diff
@@ -167,13 +172,13 @@ static boolean equalChars(char char1, char char2, CaseSensitivity caseSensitivit
      *
      * The size of the common prefix does not include the last line separator.
      */
-    public static int sizeOfCommonPrefix(String path1, String path2, int offset, CaseSensitivity caseSensitivity) {
+    public static int sizeOfCommonPrefix(String relativePath, String absolutePath, int offset, CaseSensitivity caseSensitivity) {
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: I think calling this `lengthOfCommonPrefix` would clarify things. We usually talk about length not size when it comes to strings.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 17]
```diff
@@ -182,32 +187,41 @@ public static int sizeOfCommonPrefix(String path1, String path2, int offset, Cas
...
         }
         return lastSeparator;
     }
 
     /**
-     * Compares based on the first prefix of two paths.
+     * Compares based on the first segment of two paths.
+     *
+     * Similar to {@link #sizeOfCommonPrefix(String, String, int, CaseSensitivity)},
+     * only that this methods compares the first segment of the paths if there is no common prefix.
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: `methods` -> `method`

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 18]
```diff
@@ -182,32 +187,41 @@ public static int sizeOfCommonPrefix(String path1, String path2, int offset, Cas
...
+            if (pos < absolutePath.length() - offset && isFileSeparator(absolutePath.charAt(pos + offset))) {
                 return pos;
             }
         }
         return lastSeparator;
     }
 
     /**
-     * Compares based on the first prefix of two paths.
+     * Compares based on the first segment of two paths.
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: The term "segment" needs to be defined.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 19]
```diff
@@ -167,13 +172,13 @@ static boolean equalChars(char char1, char char2, CaseSensitivity caseSensitivit
      *
      * The size of the common prefix does not include the last line separator.
      */
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: It would be great to add some examples here, too.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 20]
```diff
@@ -41,6 +41,11 @@
  * - Finally, if both segments are the same ignoring case and have the same length, the case-sensitive comparison is used.
  *
  * For all methods operating on a list of paths, the paths must not have a common, non-trivial prefix.
+ *
+ * Most of the methods take an absolutePath and an offset within the path.
+ * This is a performance optimization so that we don't need to call {@link String#substring(int)} to obtain a relative path from an absolute path.
+ * The absolutePath argument of the method is supposed to be an absolute path and the offset determines the relative path to the examined location.
+ * For example, filePath = /some/foo/bar with offset 6 determines the relative path foo/bar from the location /some.
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: It would be good to state that `offset` should always point after the separator, not to the separator.

Comment (lptr) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Maybe add a `// TODO` about introducing a separate type to capture all this?

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 21]
```diff
@@ -219,51 +233,81 @@ public static int compareWithCommonPrefix(String path1, String path2, int offset
...
+        if (relativePath.length() > absolutePath.length() - offset) {
+            return isFileSeparator(relativePath.charAt(maxPos)) ? accumulatedValue : 1;
+        }
+        return isFileSeparator(absolutePath.charAt(maxPos + offset)) ? accumulatedValue : -1;
+    }
+
+    /**
+     * Checks whether the relative path given by the absolute path and the offset has the given prefix.
+     */
+    public static boolean isPrefix(String prefix, String absolutePath, int offset, CaseSensitivity caseSensitivity) {
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Call it `hasPrefix`?

Comment (lptr) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: BTW, this will be so much more understandable on its own type. Compare having to carry all those three variables around and writing this:

```java
PathUtil.hasPrefix(prefix, absolutePath, offset, caseSensitive)
```

to

```java
relativePath.hasPrefix(prefix)
```

I mean, this is what OOP was invented to do. :)

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 20 above)
Comment (lptr) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Would be good to define "segment" and "prefix" here, too.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 22]
```diff
@@ -219,51 +233,81 @@ public static int compareWithCommonPrefix(String path1, String path2, int offset
...
+     * and returns the comparison of prefix and the path if it has not.
      *
-     * Similar to {@link #isChildOfOrThis}, only that it returns whether the filePath is bigger or smaller than the current prefix.
+     * Similar to {@link #isPrefix}, only that it returns whether the path is bigger or smaller than the prefix.
+     *
+     * Examples:
+     *   some/start == some/start/subpath
+     *   some/start == some/start
+     *   some/a     < some/start
+     *   some/b     > some/a
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Can you add some examples for when the prefix is completely different?

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SearchUtil.java [hunk 23]
```diff
@@ -37,23 +37,37 @@
      *         and only if the key is found.
      */
     public static <T> int binarySearch(List<T> sortedElements, SearchForComparator<T> searchForComparator) {
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SearchUtil.java]: This should be:

```java
public static <T> int binarySearch(List<T> sortedElements, Comparable<T> key) {
```

That would make the code read a lot easier. Also, you already refer to a "search key" in the Javadoc yet without it being present. Making this change introduces an actual key.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SearchUtil.java [hunk 24]
```diff
@@ -37,23 +37,37 @@
...
+            case 0:
+                return -1;
+            case 1:
+                T onlyElement = sortedElements.get(0);
+                int comparedToSearch = searchForComparator.compare(onlyElement);
+                return comparedToSearch == 0
+                    ? 0
+                    : comparedToSearch < 0
+                        ? -2
+                        : -1;
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SearchUtil.java]: This is confusing. Have you considered returning a cheap value object instead? Something like:

```groovy
class SearchResult {
    boolean found;
    int index;
}
```

I think the return value would be inlined by hotspot, so there's no performance impact, and the code would read a lot better.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java [hunk 25]
```diff
@@ -25,6 +25,13 @@
 import java.util.function.Supplier;
 
 public class SnapshotUtil {
+    /**
+     * If a node has fewer children, we use a linear search for the child.
+     * We use this limit since {@link PathUtil#compareToPrefix(String, String, int, CaseSensitivity)}
+     * is about twice as slow as {@link PathUtil#isPrefix(String, String, int, CaseSensitivity)},
+     * so comparing the searched path to all of the children is actually faster than doing a binary search.
+     */
+    private static final int MINIMUM_CHILD_NUMBER_FOR_BINARY_SEARCH = 10;
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java]: `NUMBER` -> `COUNT`

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SearchUtil.java (hunk 24 above)
Comment (lptr) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SearchUtil.java]: I just realized that this is from the contract of `Collections.binarySearch()`. I still think we should consider adding the type.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 21 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Yes, and that is what I have on https://github.com/gradle/gradle/pull/11378.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SearchUtil.java (hunk 23 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SearchUtil.java]: Good point about using a `Comparable<T>` directly. For that to work, I needed to invert the results of the compare methods, since currently the search method uses `child.compareTo(key)` instead of `key.compareTo(child)`.

While at it, I removed `compareToPrefix`, since that comparison is not symmetric and the only usage we had can also be handled by `compareWithCommonPrefix`.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SearchUtil.java (hunk 24 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SearchUtil.java]: I would like to keep the same semantics as `Collections.binarySearch()` for now.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java (hunk 25 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java]: Done.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 22 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: I added a sample.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 20 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Done.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 19 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: I added some samples.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 18 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Done.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java [hunk 26]
```diff
@@ -182,32 +187,41 @@ public static int sizeOfCommonPrefix(String path1, String path2, int offset, Cas
...
      * The paths must not start with a separator, taking into account the offset
      *
-     * @return 0 when the two paths have a common prefix, and the comparison of the first prefix if not.
+     * For example, this method returns:
+     *     some/path == some/other
+     *     some1/path < some2/other
+     *     some/path > some1/other
+     *     some/same == some/same/more
+     *
+     * @return 0 if the two paths have a common prefix, and the comparison of the first segment of each path if not.
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Added.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 17 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Done.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 16 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Renamed.

**Comment by wolfs** [comment]
@lptr PTAL!

File: subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java [hunk 27]
```diff
@@ -156,9 +159,10 @@ VirtualFileSystem createVirtualFileSystem(
                 FileHasher hasher,
                 ListenerManager listenerManager,
                 Stat stat,
+                FileSystem fileSystem,
                 StringInterner stringInterner
             ) {
-                VirtualFileSystem virtualFileSystem = new DefaultVirtualFileSystem(hasher, stringInterner, stat, DirectoryScanner.getDefaultExcludes());
+                VirtualFileSystem virtualFileSystem = new DefaultVirtualFileSystem(hasher, stringInterner, stat, fileSystem.isCaseSensitive() ? CASE_SENSITIVE : CASE_INSENSITIVE, DirectoryScanner.getDefaultExcludes());
```
Comment (lptr) [inline subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java]: Nit: please break this up into multiple lines.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 26 above)
[the remark this answers is not in the document]
Comment (lptr) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: Would it make sense to rename `compareWithCommonPrefix` to `compareCommonPrefix`? It seems that's what we are doing here.

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractCasePathUtilTest.groovy [hunk 28]
```diff
@@ -70,7 +70,7 @@ abstract class AbstractCasePathUtilTest extends Specification{
 
     def "size of common prefix of #prefix with #path at offset #offset is #result"() {
```
Comment (lptr) [inline subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractCasePathUtilTest.groovy]: Should refer to "length" not "size".

File: subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java (hunk 27 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java]: Done.

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractCasePathUtilTest.groovy (hunk 28 above)
Comment (wolfs) [reply subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractCasePathUtilTest.groovy]: Done.

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java (hunk 26 above)
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PathUtil.java]: I renamed it to `compareFirstSegment`.

**Comment by wolfs** [comment]
@lptr PTAL!
