### PR TITLE
Stop worker daemons when the build is canceled

### LINKED ISSUE #29043: Cancelling a build can lead to corrupt build cache entries
### Current Behavior

When cancelling a Gradle Build while compiling Java sources, invalid local build cache entries can be generated. These cache entries do not contain any class files, but are still written to the local build cache. The next time the `compileJava` task is executed, the task is marked as `UP-TO-DATE` and the local build cache entry is used to build the corresponding JAR. When another project is compiled which has a project dependency on the project with the invalid local build cache entry, the Java compiler fails with `cannot find symbol` errors.

After deleting the local build cache and excuting the `clean` task, the project can be built as usual.

### Expected Behavior

Build cache entries should not be persisted after the build is canceled.

### Context (optional)

I think the problem began appearing after we upgraded our project to from Gradle 7.4.2 to Gradle 8.5. I don't recall anyone in our team mentioning this issue prior to the upgrade. Our gradle project has 378 subprojects which are built in parallel with local and remote build caching enabled.

### Steps to Reproduce

Can be reproduced in the Gradle project itself. I checked out git tag `v8.7.0` and opened the project in IntelliJ IDEA 2024.1 Ultimate Edition. After importing the project, I executed the `compileJava` task to check whether the task can be executed after the initial import, which worked just fine. I then deleted the local build cache files unter `%USERPROFILE%\.gradle\caches\build-cache-1` and executed the `clean` task.

I then executed the `compileJava` task again, but canceled the build after about 10 seconds. I reran the `compileJava` task immediately after that and `javac` printed many `cannot find symbol` errors:

```
C:\dev\gradle\platforms\core-runtime\files\src\main\java\org\gradle\api\internal\file\archive\impl\AbstractZipEntry.java:21: error: package org.gradle.internal.io does not exist
import org.gradle.internal.io.IoFunction;
                             ^
C:\dev\gradle\platforms\core-runtime\files\src\main\java\org\gradle\api\internal\file\archive\ZipEntry.java:19: error: package org.gradle.internal.io does not exist
import org.gradle.internal.io.IoFunction;
                             ^
C:\dev\gradle\platforms\core-runtime\files\src\main\java\org\gradle\api\internal\file\archive\ZipEntry.java:62: error: cannot find symbol
    <T> T withInputStream(IoFunction<InputStream, T> action) throws IOException;
                          ^
  symbol:   class IoFunction
  location: interface ZipEntry
C:\dev\gradle\platforms\core-runtime\files\src\main\java\org\gradle\api\internal\file\archive\impl\FileZipInput.java:23: error: package org.gradle.internal.io does not exist
import org.gradle.internal.io.IoFunction;
```

### Gradle version

8.5.0/8.7.0

### Build scan URL (optional)

_No response_

### Your Environment (optional)

* I limited my gradle worker count to a maximum of 6 workers using the `org.gradle.workers.max` property in the `gradle.properties` file in my Gradle home directory
* Oracle JDK 11.0.19
* IntelliJ IDEA 2024.1 Ultimate Edition (the issue can also be reproduced using the command line though)
* Develocity 2024.1 with Develocity Gradle Plugin 3.17.1

### PR DESCRIPTION
**Pull request by ghale**
In #29043, with persistent worker daemons, we are seeing that if a build is canceled while running a worker daemon action (e.g. a compilation) we can get into a situation where the response from the canceled build is still in the communication queue for the worker daemon when the next build executes.  The compile task in the second build then gets the response from the first build and this ends up caching an incorrect result for the compile task.

To combat this, whenever a build is canceled, we immediately stop any worker daemons and remove them from the client manager as we can no longer guarantee that they (or their associated communications) are in a good state.  

This only has an effect on persistent worker daemons, as session scoped daemons are stopped anyways when the build session finishes.

Fixes #29043 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

**Comment by ghale** [comment]
@bot-gradle test this

File: platforms/core-execution/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonFactory.java [hunk 1]
```diff
@@ -29,17 +29,20 @@
...
         this.buildOperationRunner = buildOperationRunner;
+        this.workerDaemonClientCancellationHandler = workerDaemonClientCancellationHandler;
     }
 
     @Override
     public BuildOperationAwareWorker getWorker(WorkerRequirement workerRequirement) {
         return new AbstractWorker(buildOperationRunner) {
             @Override
             public DefaultWorkResult execute(IsolatedParametersActionExecutionSpec<?> spec, BuildOperationRef parentBuildOperation) {
+                workerDaemonClientCancellationHandler.start();
```
Comment (big-guy) [inline platforms/core-execution/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonFactory.java:45]: Could you explain the importance of this? IIUC, this is the magic that makes it so we only kill workers when a build is canceled if that build uses any worker.

**Review by big-guy — APPROVED** [review]
Do you know if we treat a killed client as a build cancellation?

File: platforms/core-execution/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonFactory.java (hunk 1 above)
Comment (ghale) [reply platforms/core-execution/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonFactory.java:45]: The `WorkerDaemonClientManager` is daemon-scoped (GUH-scoped to be precise).  `WorkerDaemonFactory` is project-scoped.  The build cancellation token is session-scoped, however.  We don't have any meaningful worker-related services that are session-scoped, so we need something in the lifecycle to step in at some point and register a the `WorkerDaemonClientCancellationHandler` with the right cancellation token for the current build session.  There is a session listener callback (which we use in `WorkerDaemonClientsManager`) but there's no good way to get the cancellation token when that fires.  On the other hand, the current build session doesn't need to kill workers on cancellation if it doesn't use any workers (i.e. if it doesn't use a worker, then it can't leave it in an unsafe state when cancelled).  The code you referenced is called whenever something (anything) tries to get (or start) a worker daemon.  So, at that point, we know a worker is in use - this then notifies the handler that it should register a callback with the cancellation token for the session.  If the handler has already been registered (i.e. `start()` has already been called during this session) it's just ignored.  We could name the method on `WorkerDaemonClientCancellationHandler` differently, I suppose (`notifyClientInUse()` or some such).  Does that answer your question?

**Comment by ghale** [comment]
> Do you know if we treat a killed client as a build cancellation?

Any time the client disconnects, the daemon triggers a cancellation [here](https://github.com/gradle/gradle/blob/3eda2dd72f9e01f26127f80d01047f4161c4b247/platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/daemon/server/exec/WatchForDisconnection.java#L34).

File: platforms/core-execution/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonFactory.java (hunk 1 above)
Comment (big-guy) [reply platforms/core-execution/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonFactory.java:45]: Ah, sorry.  That's a good explanation. I meant, could you leave a comment about this in the code :)

Comment (ghale) [reply platforms/core-execution/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonFactory.java:45]: The other options here would be to 1) always stop worker daemons on cancellation, regardless of if any were used or not or 2) create some mechanism to track when a worker is actually executing a work item and only stop worker daemons if a cancellation occurs while work execution is in progress.  These are the two extremes of optimization, I think.  I opted for something simple somewhere in the middle.

**Review by big-guy — APPROVED** [review]
