### PR TITLE
Replace classes with instrumented copies when loading

### LINKED ISSUE #22939: Support instrumenting signed build logic JARs
The current implementation of the configuration cache instrumentation doesn't instrument signed JARs, because the instrumentation invalidates the signature. Removing the signature doesn't work well, as some JARs verify it.

An alternative approach would be to use Java agent to do instrumentation "on-the-fly". This way, the bytecode modification doesn't affect signature checking. As a bonus, instrumented classes are no longer accessible to the user code (e.g. through `ProtectionDomain`), so fewer issues with the missing `Instrumented` class in user-constructed classpaths.

### PR DESCRIPTION
**Pull request by mlopatkin**
This is a final piece of the new instrumentation logic. When the agent is enabled, the cached copies of the original jars are provided to the classloader as the classpath, and the instrumented jars are provided separately. When loading a class, the classloader looks up a corresponding instrumented jar, loads bytecode from it and replaces the original code with the instrumented one.

Fixes #22939

This is part 3/3, previous part is in #23264.

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java [hunk 1]
```diff
@@ -50,25 +50,37 @@ class InstrumentingClasspathFileTransformer implements ClasspathFileTransformer
     private final FileLockManager fileLockManager;
     private final ClasspathWalker classpathWalker;
     private final ClasspathBuilder classpathBuilder;
+    private final Policy policy;
     private final CachedClasspathTransformer.Transform transform;
     private final HashCode configHash;
 
+    public interface Policy {
```
Comment (bamboo) [inline subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java:57]: 👍

File: subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultCachedClasspathTransformer.java [hunk 2]
```diff
@@ -92,10 +92,51 @@ public ClassPath transform(ClassPath classPath, StandardTransform transform) {
...
-        return transformFiles(
-            classPath,
-            fileTransformerFor(transform)
-        );
+        return transformPipelineFor(transform).transform(classPath);
+
+    }
+
+    @FunctionalInterface
+    private interface TransformPipeline {
```
Comment (bamboo) [inline subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultCachedClasspathTransformer.java:100]: 👍

File: subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptCompilationHandler.java [hunk 3]
```diff
@@ -390,39 +394,41 @@ protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundE
...
-                Throwable instrumentationException = pendingException.get();
-                if (instrumentationException != null) {
-                    throw new ClassNotFoundException("Failed to instrument class " + name + " in " + getName(), instrumentationException);
-                }
-                return loadedClass;
-            } finally {
-                pendingException.set(null);
+                loadedClass = super.findClass(name);
+            } catch (Throwable e) {
+                throw errorHandler.exitClassLoadingScopeWithException(e);
```
Comment (bamboo) [inline subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptCompilationHandler.java:423]: 👍

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Combinators.kt [hunk 4]
```diff
@@ -279,27 +279,51 @@ internal
 fun Encoder.writeClassPath(classPath: ClassPath) {
     // Ensure that the proper type is going to be restored,
     // because it is important for the equality checks.
-    writeBoolean(classPath is TransformedClassPath)
-    writeCollection(classPath.asFiles) {
-        writeFile(it)
+    if (classPath is TransformedClassPath) {
+        writeBoolean(true)
+        writeCollection(classPath.asFiles.zip(classPath.asTransformedFiles)) {
```
Comment (bamboo) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Combinators.kt:284]: 🎨 At this point I'd extract a `writeTransformedClassPath` and a `writeDefaultClassPath` for symmetry.

File: subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+            return null;
+        }
+        try {
+            return classPath.findTransformedJarFor(new File(originalUrl.toURI()));
+        } catch (URISyntaxException e) {
+            throw new IllegalArgumentException("Cannot parse file URL " + originalUrl, e);
+        }
+    }
+
+    private static class Loader implements Closeable {
```
Comment (bamboo) [inline subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java:106]: 👍

**Review by bamboo — APPROVED** [review]
Eventually we should add more unit tests to cover the TransformedClassPath operations and the error handling behavior but it's looking good 👍

**Comment by mlopatkin** [comment]
@bot-gradle test and merge
