### PR TITLE
Report all files in directory as changed for incremental task for non-incremental change

### LINKED ISSUE #4166: If the task is non-incremental, not all files in a directory are reported as outOfDate
Given an incremental Task.
If a property annotated with `@InputFiles` contains directories, then the files in the directory are not reported by `IncrementalTaskInput.outOfDate` if the inputs are non-incremental, but only the directory itself.

This is different to when the inputs are incremental, then all the files in the directory and the directory itself are reported as `outOfDate`.

For the example, let us assume the following build file:

```
task sampleTask(type: SampleTask) {
    sampleTask.inputFiles = files("input")
    outputDir = file("${buildDir}")
}

class SampleTask extends DefaultTask {

    @OutputDirectory
    File outputDir

    @InputFiles
    FileCollection inputFiles

    @TaskAction
    void run(IncrementalTaskInputs inputs) {
        if (!inputs.incremental) {
            println "Task is not incremental"
            project.delete(outputDir.listFiles())
        } else {
            println "Task is incremental"
        }

        inputs.outOfDate { InputFileDetails details ->
            logger.lifecycle '[OUT-OF-DATE] Input file {} added={}, changed={}, removed={}', details.file.name, details.added, details.modified, details.removed
        }

        inputs.removed { InputFileDetails details ->
            logger.lifecycle '[REMOVED] Input file {} added={}, changed={}, removed={}', details.file.name, details.added, details.modified, details.removed
        }

        new File(outputDir, "output.txt").text = "Sample output."
    }
}
```

And a directory structure like this:
```
input
|---- file1.txt
|---- file2.txt
```

### Expected Behavior
When running `gradle sampleTask` for the first time then we get the following output:
```
> Task :sampleTask
Task is not incremental
[OUT-OF-DATE] Input file input added=false, changed=false, removed=false
[OUT-OF-DATE] Input file file1.txt added=false, changed=false, removed=false
[OUT-OF-DATE] Input file file2.txt added=false, changed=false, removed=false
```

### Current Behavior
Only the added directory is reported:
```
> Task :sampleTask
Task is not incremental
[OUT-OF-DATE] Input file input added=false, changed=false, removed=false
```

### Context
The files to be considered as out of date should be consistent for incremental and non-incremental task execution. The current behavior is confusing.

Originally reported in https://github.com/gradle/gradle/issues/4114#issuecomment-359990657.

Note that for input directories, all the files in the directory are reported as `outOfDate` in the first run.

### Steps to Reproduce (for bugs)
See above.

### Your Environment
Gradle 4.5

### PR DESCRIPTION
**Pull request by wolfs**
Fixes #4166

### CODE REVIEW

**Comment by wolfs** [comment]
Supercedes https://github.com/gradle/gradle/pull/6019.

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/changes/DefaultTaskArtifactStateRepository.java [hunk 1]
```diff
@@ -101,13 +101,18 @@ public IncrementalTaskInputs getInputChanges() {
...
-                taskInputs = instantiator.newInstance(RebuildIncrementalTaskInputs.class, task, history.getCurrentExecution());
+                taskInputs = instantiator.newInstance(RebuildIncrementalTaskInputs.class, task, getInputFileFingerprints());
             } else {
                 taskInputs = instantiator.newInstance(ChangesOnlyIncrementalTaskInputs.class, getStates().getInputFilesChanges());
             }
             return taskInputs;
         }
 
+        @Override
+        public Iterable<? extends FileCollectionFingerprint> getInputFileFingerprints() {
```
Comment (lptr) [inline subprojects/core/src/main/java/org/gradle/api/internal/changedetection/changes/DefaultTaskArtifactStateRepository.java]: Should this be called `getCurrentInputFileFingerprints()`?

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/changes/NoOutputsArtifactState.java [hunk 2]
```diff
@@ -98,6 +99,11 @@ public IncrementalTaskInputs getInputChanges() {
         throw new UnsupportedOperationException();
     }
 
+    @Override
+    public Iterable<? extends FileCollectionFingerprint> getInputFileFingerprints() {
+        throw new UnsupportedOperationException();
+    }
+
```
Comment (lptr) [inline subprojects/core/src/main/java/org/gradle/api/internal/changedetection/changes/NoOutputsArtifactState.java]: I wish we'd be able to get rid of this thing---throwing `UOE` all over the place is hardly a good way of doing things.

Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/api/internal/changedetection/changes/NoOutputsArtifactState.java]: 👍 
I had a quick look what would be necessary. We would need a second way through our chain of executers: https://github.com/gradle/gradle/blob/7f0f09d7cf52c81eb440865e66b30dc66cf93654/subprojects/core/src/main/java/org/gradle/internal/service/scopes/TaskExecutionServices.java#L130-L160

We would need to fork in `ResolveTaskArtifactStateTaskExecuter` - instead of creating a `TaskArtifactState` we would go a different route:
- without `CleanupStaleOutputsExecuter`
- with `FinalizeInputFilePropertiesTaskExecuter`
- a simpler version of `SkipEmptySourceFilesTaskExecuter`
- `ValidatingTaskExecuter`
- a simpler version of `ResolveBuildCacheKeyExecuter` - always returning an invalid build cache key
- a simpler version of `ResolveTaskOutputCachingStateExecuter`, always returning `NO_OUTPUTS_DECLARED` as a reason
- instead of `SkipUpToDateTaskExecuter` we would set a fixed out-of-date reason
- without `SkipCachedTaskExecuter`
- without `OutputDirectoryCreatingTaskExecuter`
- without `SnapshotAfterExecutionTaskExecuter`
- `TimeoutTaskExecuter`, `ActionEventFiringTaskExecuter` and `ExecuteActionsTaskExecuter` would remain unchanged.

With our current structure for the executers, this is not very easy to do. I guess we need to do something about how we use the executers when we introduce caching and up-to-date checks for artifact transforms. We can come back to the problem when we get there.

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/changes/DefaultTaskArtifactStateRepository.java (hunk 1 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/api/internal/changedetection/changes/DefaultTaskArtifactStateRepository.java]: Renamed.

**Comment by wolfs** [comment]
@lptr PTAL
