### PR TITLE
Prevent CMEs when creating Ivy instances

### LINKED ISSUE #6175: ivy concurrent modification exception
Since we've updated to gradle 4.9, we've started seeing an in-deterministic ConcurrentModificationException in Upload tasks.

Full error:
https://gist.github.com/yigit/4e5439ccfad5cc753e173f46b1fdc50e

### Context
Build fails with this error when we try to run a bunch of uploadArchives tasks.

### Steps to Reproduce (for bugs)
we cannot reproduce this properly, it just happens time to time. We've recently updated to 4.9 .
You can try checking out:
https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/README.md
And running:
./gradlew buildOnServer 

I'm seeing the error in this patch, might be related but i can't see how since anything added in this CL is practically no-op besides adding a `onlyIf` block to certain tasks :
https://android-review.googlesource.com/c/platform/frameworks/support/+/723896

### Your Environment
➜  gw --version
------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b04)
OS:           Linux 4.9.0-7-amd64 amd64

### PR DESCRIPTION
**Pull request by oehme**
Ivy iterates over the system properties, which may be
mutated at the same time. This change wraps the Ivy call
so that concurrent modifications are forbidden.

Fixes #6175

### CODE REVIEW

**Comment by oehme** [comment]
I've also changed the way we prevent access so we can even prevent concurrent modification from code that we don't own.

File: subprojects/base-services/src/main/java/org/gradle/internal/SystemProperties.java [hunk 1]
```diff
@@ -133,19 +123,29 @@ public File getJavaHomeDir() {
      * @param factory Instance created by the Factory implementation
      */
     public <T> T withSystemProperty(String propertyName, String value, Factory<T> factory) {
-        lock.lock();
-        String originalValue = System.getProperty(propertyName);
-        System.setProperty(propertyName, value);
+        synchronized (System.getProperties()) {
+            String originalValue = System.getProperty(propertyName);
```
Comment (big-guy) [inline subprojects/base-services/src/main/java/org/gradle/internal/SystemProperties.java]: I think there's another race here that would be hard to prevent. I don't think it's new:

t1:  synchronized(getProperties())
t2: setProperties(newProperties)
t1: getProperty(...) // not the original properties now and factory will be vulnerable to CME again

or in a similar sort of way:

t1:  synchronized(getProperties())
t1: getProperty(...) // getting from original properties
t1: setProperty(...) // setting to original properties
t2: setProperties(newProperties)
t1: factory.create() // sees a different set of properties
t1: finally {} // resets/clears our property on the "wrong" properties

I don't think we need to do anything about this until it becomes a problem.

Comment (oehme) [reply subprojects/base-services/src/main/java/org/gradle/internal/SystemProperties.java]: Oh dear, why would they even allow completely overwriting that field? I agree, this is hard to prevent.
