### PR TITLE
Detect long command lines properly for Linux

### LINKED ISSUE #12453: "error=7, Argument list too long" still an issue on nix
The pathing jar improvements in #11620 have solved 'argument list too long', but the length requirements aren't strict enough.

### Expected Behavior

JavaExec with a ridiculous number of classpath dependencies should not fail.

### Current Behavior

If string length of the classpath is above 131072 (the single arg strlen limit on linux), but the total command length is lower than 2097152, then gradle doesn't attempt to use a pathing jar, and the command fails with "error=7, Argument list too long".

### Steps to Reproduce 

`gradle run` with a project containing a classpath slightly over 132k characters.

### Your Environment

Gradle 6.2

### PR DESCRIPTION
**Pull request by quad**
Long command lines for Linux systems are derived from MAX_ARG_STRLEN (131072 by default)

Fixes #12453 
And [KT-34487](https://youtrack.jetbrains.com/issue/KT-34487) as a bonus!

### Context
We have Windows and macOS lengths. Let's do Linux now too!

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/process/internal/util/LongCommandLineDetectionUtil.java [hunk 1]
```diff
@@ -25,6 +25,8 @@
     public static final int MAX_COMMAND_LINE_LENGTH_WINDOWS = 32767;
     // Derived from default when running getconf ARG_MAX in OSX
     public static final int MAX_COMMAND_LINE_LENGTH_OSX = 262144;
+    // Dervied from MAX_ARG_STRLEN as per http://man7.org/linux/man-pages/man2/execve.2.html
+    public static final int MAX_COMMAND_LINE_LENGTH_LINUX = 131072;
     public static final int MAX_COMMAND_LINE_LENGTH_NIX = 2097152;
```
Comment (sonicsnes) [inline subprojects/core/src/main/java/org/gradle/process/internal/util/LongCommandLineDetectionUtil.java:30]: I suspect this value should be changed rather than using another one. Are there any other nix variants where 2097152 is appropriate?

Comment (quad) [reply subprojects/core/src/main/java/org/gradle/process/internal/util/LongCommandLineDetectionUtil.java:30]: I don't know. I don't have familiarity with Solaris and other platforms. But since OSX is different than Linux, I didn't feel comfortable changing the default.

Comment (quad) [reply subprojects/core/src/main/java/org/gradle/process/internal/util/LongCommandLineDetectionUtil.java:30]: [Actual values for ARG_MAX (or NCARGS)](https://www.in-ulm.de/~mascheck/various/argmax/#results) is an older document that looks comprehensive. tl;dr no. it varies a lot.

Comment (sonicsnes) [reply subprojects/core/src/main/java/org/gradle/process/internal/util/LongCommandLineDetectionUtil.java:30]: Basically all of those are lower than 2097152. Since it shouldn't typically hurt to have /too low/ of a value, defaulting to 131072 seems like it would at least improve the situation.

**Comment by quad** [comment]
OK, I will change this PR to set the MAX_COMMAND_LINE_LENGTH_NIX to 131072.

**Comment by quad** [comment]
Can this be merged now?

**Comment by big-guy** [comment]
This'll be in 6.5, thanks!
