### PR TITLE
Make Isolated Projects setting part of the Configuration Cache key

### LINKED ISSUE #26049: Setting org.gradle.unsafe.isolated-projects not causing recalculation of configuration cache
### Current Behavior

I'm finding that when I run `./gradlew --configuration-cache ${someArguments} && ./gradlew --configuration-cache -Dorg.gradle.unsafe.isolated-projects=true ${someArguments}` , then if the first build succeeds and populates the configuration cache, it prevents the second build from verifying project isolation compatibility: instead it reuses the configuration cache entry created by the first build.

### Expected Behavior

I think it would be nice if `org.gradle.unsafe.isolated-projects` could be declared as an input to the configuration cache so that a previous successful build without project isolation enabled won't cause project isolation validation to be subsequently skipped

### Context (optional)

I'm working towards enabling project isolation (in AndroidX) and we have a large collection of violations.

For the moment, my process is:
1. Run a small subset of the build with project isolation enabled, attempt to fix one project isolation error, and repeat until the specific error appears to be fixed. The build still fails, but it should have fewer errors.
2. Rerun the build without project isolation enabled, to make sure I didn't accidentally break anything.
3. Go back to 1 and try to fix another error

Sometimes step 3 will succeed because step 2 succeeded, making me incorrectly think that I might have fixed the project isolation error when actually the reason is that the configuration phase was skipped.

### Steps to Reproduce

See https://github.com/mathjeff/gradle-samples-2/tree/main/configuration-cache-ignoring-project-isolation

### Gradle version

8.3-rc-1

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by alllex**
Fixes #26049

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt [hunk 1]
```diff
@@ -136,6 +136,9 @@ class ConfigurationCacheStartParameter(
 
     val isNoBuildScan: Boolean
         get() = startParameter.isNoBuildScan
+
+    val isIsolatedProjects: Boolean
+        get() = modelParameters.isIsolatedProjects
```
Comment (alllex) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt:141]: ☁️  I intentionally used the `modelParameters` here to rely on the "more final" value of the Isolated Projects settings. The value in the `StartParameterInternal` is not final, because it can be affected by other build flags.

**Review by h0tk3y — APPROVED** [review]

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheKeyIntegrationTest.groovy [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+    @Issue("https://github.com/gradle/gradle/issues/26049")
+    @IgnoreIf({ GradleContextualExecuter.isolatedProjects }) // Isolated Projects option is explicitly controlled by the test
+    def "isolated projects flag is part of the cache key"() {
+        def isolatedProjects = new IsolatedProjectsFixture(this)
+
+        when:
+        configurationCacheRun "help"
+        then:
+        configurationCache.assertStateStored()
+        countStoredEntries() == 1
```
Comment (bamboo) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheKeyIntegrationTest.groovy:66]: ❓ Why?

Comment (alllex) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheKeyIntegrationTest.groovy:66]: Initially, I wanted to test that the different runs actually use the exact same CC key. However, I found that we do not expose those keys neither in the logs nor in build operations.

Checking the number of CC entry directories is the closest reasonable approximation I found to checking that.

If your question is targeted towards the very first check with `== 1`, it's just for unification, so that we check after every task invocation in the test.

Comment (bamboo) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheKeyIntegrationTest.groovy:66]: > Initially, I wanted to test that the different runs actually use the exact same CC key

In that case I'd add a test to `ConfigurationCacheKeyTest` similar to https://github.com/gradle/gradle/blob/4be5615ce33258a8315ff7ef176df00011da83bd/subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/ConfigurationCacheKeyTest.kt#L91

For integration tests, the `assertStateStored` / `assertStateLoaded` should be enough. I wouldn't make this test depend on the cache layout on disk.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt (hunk 1 above)
Comment (bamboo) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt:141]: 💅 It makes sense to add a similar comment to the code.

**Review by bamboo — CHANGES_REQUESTED** [review]

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheKeyIntegrationTest.groovy (hunk 2 above)
Comment (alllex) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheKeyIntegrationTest.groovy:66]: It makes sense, I'll fix this.

I saw the unit test, but decided against it, because there we would have to start duplicating some logic of computing the `BuildModelParameters` from `StartParameterInternal`. We can do this, but only partially. I think it could be too easy for the production code and the unit test code to desynchronize.

Having said that, having both the integration test and the unit test should be good enough.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt (hunk 1 above)
Comment (alllex) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt:146]: Done

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheKeyIntegrationTest.groovy (hunk 2 above)
Comment (alllex) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheKeyIntegrationTest.groovy]: Added a unit test, and removed the CC layout checks in the integration test

File: subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/ConfigurationCacheKeyTest.kt [hunk 3]
```diff
@@ -136,7 +169,7 @@ class ConfigurationCacheKeyTest {
                 ),
                 startParameter,
                 DefaultInternalOptions(mapOf()),
-                BuildModelParameters(false, false, true, false, false, false, false, false, LogLevel.LIFECYCLE)
+                BuildModelParameters(false, false, true, startParameter.isolatedProjects.get(), false, false, false, false, LogLevel.LIFECYCLE)
```
Comment (bamboo) [inline subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/ConfigurationCacheKeyTest.kt:172]: 👍

**Review by bamboo — APPROVED** [review]
💯

**Comment by alllex** [comment]
@bot-gradle test and merge
