### PR TITLE
Consider all variants when finding artifact transform chains

### LINKED ISSUE #22735: Gradle 8.0-milestone-3 regression: Transform selection algorithm has changed (longer chain is selected)
### Version
Regression in **Gradle 8.0-milestone-3** compared to Gradle 7.5

### Issue
Suppose `:lib` publishes artifact types `A` and `B`, and `:app` has 2 transforms from `A` to `B` and `B` to `C`. 

Scenario 1: If `:app` requests `B`, Gradle will get artifact `B` published from `:lib` directly without running the transform to convert `A` to `B`. This is the case in both Gradle 7.5 and Gradle 8.0-milestone-3.

Scenario 2: If `:app` requests `C`, the behavior in the two versions are different.
  - a) In Gradle 7.5, Gradle will get `B` from `:lib` and run only 1 transform to convert `B` to `C`.
  - b) In Gradle 8.0-milestone-3, Gradle will get `A` from `:lib` and run 2 transforms to convert `A` to `B`, then `B` to `C`. => **This is a behavior change from Gradle 7.5**, it is inconsistent with scenario 1, and it is also inefficient (longer chain is selected). It is breaking one of our tests in AGP when we try to update to Gradle 8.0-milestone-3.
  
### Steps to reproduce
  1. Open the attached project: [MyApplication.zip](https://github.com/gradle/gradle/files/10014520/MyApplication.zip)
  2. Run `./gradlew --stop && ./gradlew clean :app:printArtifacts`. Observe that 2 transforms are executed (this corresponds to scenario 2b above):
```
> Transform full.jar (project :lib) with CustomTransform
Running CustomTransform on MyApplication/lib/build/intermediates/full_jar/debug/full.jar to produce MyApplication/lib/build/.transforms/5423cd115abb5d76cca6a332703a7b9c/transformed/full.jar.transformed

> Transform full.jar (project :lib) with CustomTransform
Running CustomTransform on MyApplication/lib/build/.transforms/5423cd115abb5d76cca6a332703a7b9c/transformed/full.jar.transformed to produce MyApplication/lib/build/.transforms/0814f6542c157e4e9bc67383f208a4f1/transformed/full.jar.transformed.transformed

> Task :app:printArtifacts
artifactFiles contain: [MyApplication/lib/build/.transforms/0814f6542c157e4e9bc67383f208a4f1/transformed/full.jar.transformed.transformed]
```

3. In `gradle-wrapper.properties`, switch to using Gradle 7.5 and run the above command again. Observe that only 1 transform is executed (this corresponds to scenario 2a above):
```
> Transform debug (project :lib) with CustomTransform
Running CustomTransform on MyApplication/lib/build/intermediates/consumer_proguard_dir/debug to produce MyApplication/lib/build/.transforms/a4bb0cfcffa01a919b9e4293031893a2/transformed/debug.transformed

> Task :app:printArtifacts
artifactFiles contain: [MyApplication/lib/build/.transforms/a4bb0cfcffa01a919b9e4293031893a2/transformed/debug.transformed]
```

#### Expected behavior

In scenario 2, case (2a) should happen and case (2b) should not happen for all versions of Gradle.

### PR DESCRIPTION
**Pull request by jvandort**
The previous implementation would attempt to construct artifact transform chains for each variant. This would result in situations where we would construct an inefficient chain where an intermediary transformed variant could be provided by an existing producer variant.

To resolve this, we update the algorithm to consider all producer variants instead of being run against a single producer variant. We update the algorithm to search breadth-first instead of depth-first in order to ensure we prioritize shorter artifact transform chains over longer ones.

Some of the previous disambiguation behavior was maintained.
If two transformed variants have attributes such that for any given key they do not have a different value, we consider those variants to be matching. We perform disambiguation by always choosing the last candidate, and then include any other candidate which is not matching with the last candidate. This in some way hides ambiguity, though we keep this behavior to not affect existing transform chains.

Finally, added functionality to remove transforms from consideration if they have been used previously in a chain. This fixes a bug where two transforms which reference each other's attributes circularly would cause a "Recursive Update" error related to using concurrent hash maps. We would previously otherwise have likely run into a stack overflow error if there was no alternative solution in the transformation graph.

Fixes #22735

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test apt

**Comment by jvandort** [comment]
@bot-gradle help

**Comment by jvandort** [comment]
@bot-gradle test rfn

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test rfn

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test rfn

**Comment by big-guy** [comment]
@wolfs Not looking for a review, but heads up about some changes going on in the dependency management side of finding transform chains.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java [hunk 1]
```diff
@@ -101,130 +96,78 @@ public ResolvedArtifactSet select(ResolvedVariantSet producer, Factory factory)
...
+            candidates = matches;
         }
 
-        List<Pair<ResolvedVariant, MutableConsumerVariantMatchResult.ConsumerVariant>> shortestTransforms = Lists.newArrayListWithExpectedSize(candidates.size());
-        candidates.sort(Comparator.comparingInt(candidate -> candidate.right.depth));
+        List<TransformedVariant> differentTransforms = new ArrayList<>(1);
 
-        // Need to remember if a further element was matched by an earlier one, no need to consider it then
-        boolean[] hasBetterMatch = new boolean[candidates.size()];
+        TransformedVariant last = candidates.get(candidates.size() - 1);
```
Comment (big-guy) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java:154]: Is there anything meaningful about starting with the last candidate?

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java [hunk 2]
```diff
@@ -101,130 +96,78 @@ public ResolvedArtifactSet select(ResolvedVariantSet producer, Factory factory)
...
-        List<AttributeContainerInternal> matches = matcher.matches(candidateAttributes, componentRequested, explanationBuilder);
-        if (matches.size() == 1) {
-            AttributeContainerInternal singleMatch = matches.get(0);
-            return candidates.stream().filter(pair -> pair.getRight().attributes.equals(singleMatch)).collect(Collectors.toList());
-        } else if (matches.size() > 0 && matches.size() < candidates.size()) {
-            // We know all are compatibles, so this is only possible if some disambiguation happens but not getting us to 1 candidate
-            return candidates.stream().filter(pair -> matches.contains(pair.getRight().attributes)).collect(Collectors.toList());
-        }
-        return candidates;
+        return differentTransforms.size() == candidates.size() ? candidates : differentTransforms;
```
Comment (big-guy) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java:165]: When doesn't this return the same thing as the contents of `differentTransforms`?

`differentTransforms.size() > candidates.size()` cannot happen AFAIK.
`differentTransforms.size() < candidates.size()` returns differentTransforms.
`differentTransforms.size() == candidates.size()` returns candidates, but this should be the same as differentTransforms?

**Review by big-guy — COMMENTED** [review]
almost done

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java [hunk 3]
```diff
@@ -101,130 +96,78 @@ public ResolvedArtifactSet select(ResolvedVariantSet producer, Factory factory)
     private ResolvedArtifactSet doSelect(ResolvedVariantSet producer, Factory factory, AttributeMatchingExplanationBuilder explanationBuilder) {
         AttributeMatcher matcher = schema.withProducer(producer.getSchema());
         ImmutableAttributes componentRequested = attributesFactory.concat(requested, producer.getOverriddenAttributes());
-        final Set<ResolvedVariant> variants;
+        final List<ResolvedVariant> variants;
         if (selectFromAllVariants) {
-            variants = producer.getAllVariants();
+            variants = ImmutableList.copyOf(producer.getAllVariants());
```
[the remark this answers is not in the document]
Comment (jvandort) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java:101]: The reason for this change is to get a `List` from a `Set`. `ImmutableList.copyOf` is just an easy way to do that -- though `new ArrayList<>()` is another option. If we want to avoid this copy here, we would need to use a `List` further up

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java (hunk 1 above)
Comment (jvandort) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java:154]: Nope. This is strictly a simplification of the existing algorithm with all logic for comparing depth removed. The old implementation simplifies down to always adding the last element and then comparing the rest of the items to the last. 

I've left this behavior for compatibility. Though, using the last element is strictly arbitrary.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java (hunk 2 above)
Comment (jvandort) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java:165]: They are the same contents. Though if the lists are identical I figured it would be better to return the original list instead of a copy of the original list. If you think this is superfluous this can be simplified to `return differentTransforms`.

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy [hunk 4]
```diff
@@ -1022,6 +1022,98 @@ class ArtifactTransformIntegrationTest extends AbstractHttpDependencyResolutionT
...
+                        attributes {
+                            attribute(artifactType, "intermediate")
+                        }
+                        artifact jar
+                    }
+                }
+            }
+
+            // Provides a default value of `preferred` if a given attribute is not requested.
+            abstract class DefaultingDisambiguationRule implements AttributeDisambiguationRule<String>, org.gradle.api.internal.ReusableAction {
```
[the remark this answers is not in the document]
Comment (jvandort) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy:1052]: Good catch. We would not. Before these changes, the longer path was preferred due to the disambiguation rule. Now, the longer path is not even found when searching. So, this WOULD fail in master, but now with these changes the disambiguation rule is not even necessary. 

I'm inclined to leave this in, just as a regression test against the previous functionality. 

Thinking out loud, the only way we could make this test more relevant to current functionality is to have two transforms of the same length being disambiguated by the disambiguation rule. Though, in that case, the one with the preferred attribute WOULD be selected as opposed to the current test, where the one with the preferred attribute is not selected.

[the remark this answers is not in the document]
Comment (big-guy) [reply subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy:1076]: Agree, let's leave this here.

Here's the test failing with master in the way you described: https://ge.gradle.org/s/wk54kjplibz44/tests/:dependency-management:embeddedIntegTest/org.gradle.integtests.resolve.transform.ArtifactTransformIntegrationTest/transform%20selection%20prioritizes%20shorter%20transforms%20over%20attribute%20schema%20matching?top-execution=1

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java (hunk 2 above)
Comment (big-guy) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java:165]: Yeah, I think just returning `differentTransforms` would be better, since the extra conditional here makes it seem like there's something special going on.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (big-guy) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java:101]: Yeah, maybe this is something to try to cleanup another day.

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformedVariant.java [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+    private final VariantDefinition chain;
+
+    public TransformedVariant(ResolvedVariant root, VariantDefinition chain) {
+        this.root = root;
+        this.chain = chain;
+    }
+
+    @Override
+    public String toString() {
+        return chain.toString();
```
Comment (big-guy) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformedVariant.java:38]: Would it be useful in debugging for this to print the root and target attributes too?
e.g., something like:
```suggestion
        return root.asDescribable().getDisplayName() + " <- " + chain + " = " + getAttributes();
```
which produces:
> test: a:1.0 configuration default <- (1) FileSizer <- (2) FileSizer <- (3) FileSizer = {artifactType=final, org.gradle.status=release}

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerProvidedVariantFinder.java [hunk 6]
```diff
@@ -16,107 +16,293 @@
...
+        this.matcher = new CachingAttributeMatcher(schema.matcher());
+        this.transformationCache = new TransformationCache(this::doFindTransformedVariants);
     }
 
-    public ConsumerVariantMatchResult collectConsumerVariants(AttributeContainerInternal actual, AttributeContainerInternal requested) {
-        AttributeSpecificCache toCache = getCache(requested);
-        return toCache.transforms.computeIfAbsent(actual, attrs -> findProducersFor(actual, requested).asImmutable());
+    /**
+     * Executes the transformation chain detection algorithm given a set of producer variants and the requested
+     * attributes. Only the transforms chains of the shortest transformation depth are returned, and all results are
```
Comment (big-guy) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerProvidedVariantFinder.java:62]:
```suggestion
     * attributes. Only the transform chains of the shortest transformation depth are returned, and all results are
```

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerProvidedVariantFinder.java [hunk 7]
```diff
@@ -16,107 +16,293 @@
...
 
-        for (ArtifactTransformRegistration candidate : candidates) {
-            AttributeContainerInternal requestedPrevious = computeRequestedAttributes(requested, candidate);
-            ConsumerVariantMatchResult inputVariants = collectConsumerVariants(actual, requestedPrevious);
-            if (!inputVariants.hasMatches()) {
-                continue;
+        private List<TransformedVariant> query(
+            List<ResolvedVariant> sources, ImmutableAttributes requested
+        ) {
+            ArrayList<ImmutableAttributes> variantAttributes = new ArrayList<>(sources.size());
```
Comment (big-guy) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerProvidedVariantFinder.java:222]:
```suggestion
            List<ImmutableAttributes> variantAttributes = new ArrayList<>(sources.size());
```

**Review by big-guy — APPROVED** [review]
:shipit:

**Comment by big-guy** [comment]
@bot-gradle test RfR

**Comment by ljacomet** [comment]
@bot-gradle test and merge
