### PR TITLE
Fix potential concurrent modification exception when checking memory

### LINKED ISSUE #2452: DefaultMemoryManager may throw ConcurrentModificationException
Under heavy load, it is possible for `DefaultMemoryManager` to throw a `ConcurrentModificationException`

### Expected Behavior

`DefaultMemoryManager` should be thread-safe

### Current Behavior

I had a couple of builds running which showed the same exception. Basically, when the system is under heavy load, for example when running integration tests in parallel, multiple workers can be spawned, and Gradle may try to recover memory, or shutdown workers. When it does so, a call to `requestFreeMemory` may be done concurrently to removing a `MemoryHolder`, leading to a concurrent modification exception.

### PR DESCRIPTION
**Pull request by melix**
This pull request fixes #2452 . See the issue for details.

### CODE REVIEW

File: subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/DefaultMemoryManager.java [hunk 1]
```diff
@@ -117,7 +117,7 @@ private long doRequestFreeMemory(long requestedFreeMemory, long freeMemory) {
         if (freeMemory < requestedFreeMemory) {
             LOGGER.debug("{} memory requested, {} free", requestedFreeMemory, freeMemory);
             synchronized (holdersLock) {
-                for (MemoryHolder holder : holders) {
+                for (MemoryHolder holder : new ArrayList<MemoryHolder>(holders)) {
```
Comment (eskatos) [inline subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/DefaultMemoryManager.java]: ⭕️  The copy could be done while holding the `holdersLock` and the actual processing out of lock.
