### PR TITLE
Make cache entry-retention settings compatible with configuration-cache

### LINKED ISSUE #30467: Cache-cleanup retention is incorrect when used with configuration-cache
### Current Behavior

When cache-entry retention is [configured via init-script](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home:configure_cache_cleanup), the `removeUnusedEntriesAfterDays` setting is immediately converted to an absolute timestamp. This timestamp is then serialized in the configuration-cache data.

This means that this fixed timestamp will be used on each build that loads from the configuration-cache, rather than re-calculating the timestamp based on the configured days on each build invocation.

### Expected Behavior

If a user sets `caches.buildCache.removeUnusedEntriesAfterDays = 1` in an init-script and later executes a build that loads from configuration-cache, the cache retention interval should be based on the time of execution, not based on the time that the configuration-cache entry was stored.

### Context (optional)

_No response_

### Steps to Reproduce

Reproducer: https://github.com/bigdaz/gradle-30467

I've proved this issue by logging the timestamp passed to the cache-cleanup process.

### Gradle version

8.10

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by bigdaz**
Previously, we were immediately converting the `removeUnusedEntriesAfter` setting
to an absolute timestamp. This timestamp was then persisted in the configuration cache.
This resulted in #30467.

With this change, we retain the `removeUnusedEntriesAfter` as an interval in ms,
and only convert to an absolute timestamp when constructing the cache instance.
This means that the interval is always based on the current build execution, rather
than the time when the configuration was persisted for CC.

To support the force-cleanup mechanism of the `setup-gradle` GitHub Action, a new `removeEntriesUnusedSince` method is added to specify an absolute timestamp for cache-cleanup.

The `entryRetention` property is introduced that holds an `EntryRetention` instance with a timestamp and a flag indicating absolute vs relative.

Fixes #30467

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java [hunk 1]
```diff
@@ -214,35 +224,44 @@ private static <T> Provider<T> providerFromSupplier(Supplier<T> supplier) {
...
+            return entryRetentionTimestamp;
         }
 
+        @Override
+        public Supplier<Long> getEntryRetentionTimestampSupplier() {
+            return () -> {
+                if (entryRetentionTimestamp.isPresent()) {
+                    return entryRetentionTimestamp.get();
+                }
+                return clock.getCurrentTime() - entryRetentionAge.get();
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java:255]: 🤔 In our discussion, we talked about using the build start time here instead of the current time, to make the retention timestamp consistent across caches. Not sure if that is important or not. I suppose it doesn't matter too much, right?

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy [hunk 2]
```diff
@@ -77,20 +120,69 @@ class CacheConfigurationsIntegrationTest extends AbstractIntegrationSpec {
...
+                assert createdResources.entryRetentionAge.get() == ${createdResourcesTimestamp}
+                assert buildCache.entryRetentionAge.get() == ${buildCacheResourcesTimestamp}
+            }
+        """
+
+        expect:
+        succeeds("help")
+    }
+
+    def "can configure caches to a custom entry retention timestamp"() {
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy:146]: ❔ Did you add a test that shows that the retention timestamp takes precedence over the retention age? I didn't see one at first glance.

File: subprojects/core-api/src/main/java/org/gradle/api/cache/CacheResourceConfiguration.java [hunk 3]
```diff
@@ -27,10 +27,9 @@
...
 @HasInternalProtocol
 public interface CacheResourceConfiguration {
-
     /**
-     * Sets the timestamp before which unused entries will be removed to be calculated exactly
-     * the given number of days previous to the current time.
+     * Sets the interval (in days) after which unused entries will be considered stale and removed from the cache.
+     * Any entries not used within this interval will be candidates for eviction.
      */
     void setRemoveUnusedEntriesAfterDays(int removeUnusedEntriesAfterDays);
```
Comment (wolfs) [inline subprojects/core-api/src/main/java/org/gradle/api/cache/CacheResourceConfiguration.java:34]: 🤔 Do you think it makes sense to have another method in the future where you can provide a value and a time unit to set the retention?

**Review by wolfs — APPROVED** [review]

File: subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java (hunk 1 above)
Comment (bigdaz) [reply subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java:255]: I tried to do this, but there was no available service that could be used to inject the build start time into the `CacheConfigurations` service. This makes sense since the cache-cleanup logic lives in the Gradle Daemon and is registered in `GradleUserHomeScopeServices`.

The trigger for cache cleanup isn't necessarily a build starting. It can also run on daemon shutdown. So I think using the current time works: this is no change from the previous behaviour.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy (hunk 2 above)
Comment (bigdaz) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy:146]: I intended to, but I guess that slipped. Do you think a unit test would be sufficient?
(We could verify that the returned `entryRetentionTimestampSupplier` uses the timestamp in preference to the age.

Note that setting the `entryRetentionTimestamp` is still an internal API. We could consider making it public, in which case test coverage will be more important.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy [hunk 4]
```diff
@@ -77,20 +120,69 @@ class CacheConfigurationsIntegrationTest extends AbstractIntegrationSpec {
...
                     cleanup = Cleanup.DISABLED
-                    releasedWrappers.removeUnusedEntriesOlderThan = ${releasedDistTimestamp}
-                    snapshotWrappers.removeUnusedEntriesOlderThan = ${snapshotDistTimestamp}
-                    downloadedResources.removeUnusedEntriesOlderThan = ${downloadedResourcesTimestamp}
-                    createdResources.removeUnusedEntriesOlderThan = ${createdResourcesTimestamp}
+                    releasedWrappers.entryRetentionAge = ${releasedDistTimestamp}L
+                    snapshotWrappers.entryRetentionAge = ${snapshotDistTimestamp}L
+                    downloadedResources.entryRetentionAge = ${downloadedResourcesTimestamp}L
+                    createdResources.entryRetentionAge = ${createdResourcesTimestamp}L
+                    buildCache.entryRetentionAge = ${buildCacheResourcesTimestamp}L
```
Comment (ghale) [inline subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy:127]: 🤔 I wonder if we should even have this test given this is private api.  I think the test was around previously because it was overlooked when we pulled this out of the public api and the magic of groovy just allowed it to continue working.  I suppose it's fine if you want to keep it, but it might make sense to remove it.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy (hunk 2 above)
Comment (ghale) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy:146]: Similar to my previous comment, I think it would be fine to remove this unless we're not testing this functionality elsewhere (i.e. a unit test would be fine IMO).

**Review by ghale — APPROVED** [review]
A few comments, but overall I think this looks good.

File: subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java [hunk 5]
```diff
@@ -214,35 +224,44 @@ private static <T> Provider<T> providerFromSupplier(Supplier<T> supplier) {
...
-        public Supplier<Long> getRemoveUnusedEntriesOlderThanAsSupplier() {
-            return () -> getRemoveUnusedEntriesOlderThan().get();
+        public Property<Long> getEntryRetentionTimestamp() {
+            return entryRetentionTimestamp;
         }
 
+        @Override
+        public Supplier<Long> getEntryRetentionTimestampSupplier() {
+            return () -> {
+                if (entryRetentionTimestamp.isPresent()) {
```
[the remark this answers is not in the document]
Comment (bigdaz) [reply subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java:252]: But you're absolutely correct: having a single Property for `EntryRetention` makes more sense than 2 properties where one trumps the other.
I'll make this change.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy (hunk 4 above)
Comment (bigdaz) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy]: I've removed any integration tests that directly set the `Provder` value, but added/modified one to test the new `removeEntriesUnusedSince` method: while this is internal API (currently), it is clearly user-facing.

We should probably just promote it to public API as `@Incubating`.

File: subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (bigdaz) [reply subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java]: We now have a single `Property<EntryRetention> entryRetention` field. The `EntryRetention` type holds both a millisecond time and a flag indicating relative vs absolute.
