### PR TITLE
Publish all metadata after artifacts

### LINKED ISSUE #28153: maven snapshot publishing broken metadata
### Current Behavior

When updating a "-SNAPSHOT" artifact maven-metadata.xml is updated before the pom and artifact are uploaded leading to a temporary situation where CI's fail as metadata is pointing at something that doesn't exist yet.

### Expected Behavior

When updating a "-SNAPSHOT" artifact maven-metadata.xml is updated after pom and artifact are uploaded.

### Context (optional)

After switching from ivy to maven publishing we started to get intermittent failures saying artifacts don't exist.

### Steps to Reproduce

Run "gradlew publish" on a maven-publish project. Check last modified date on files on artifact repository, or access_log on the repository or a network capture.

### Gradle version

6.9.4

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by ljacomet**
Fixes #28153

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by hadiphn** [comment]
good job

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by gsosm0760** [comment]
Devam ediyor musunuz

File: platforms/software/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy [hunk 1]
```diff
@@ -195,4 +195,46 @@ class MavenPublishSnapshotIntegTest extends AbstractMavenPublishIntegTest {
...
+"""
+        def module = mavenRepo.module('org.gradle', 'snapshotPublish', '1.0-SNAPSHOT')
+
+        when:
+        succeeds 'publish', '-i'
+
+        then:
+        def initialVersion = module.publishArtifactVersion
+        def publishTaskOutputLines = result.getGroupedOutput().task(':publishPubPublicationToMavenRepository').getOutput().split("\\R")
+        def expectedPublishedLog = ["Uploading snapshotPublish-${initialVersion}.jar", "Uploading snapshotPublish-${initialVersion}.pom", "Uploading snapshotPublish-${initialVersion}.module", 'Uploading maven-metadata.xml', 'Uploading maven-metadata.xml']
```
Comment (ov7a) [inline platforms/software/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy:227]: 💅 Isn't there a better way to get that information? E.g. requesting the maven repo for the artifact upload time.

The current way looks fragile to me - logs format may change, and the publishing can be potentially parallelized (meaning races on stdout)

File: platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java [hunk 2]
```diff
@@ -70,31 +70,47 @@ protected void publish(MavenNormalizedPublication publication, ExternalResourceR
         String version = publication.getVersion();
 
         ModuleArtifactPublisher artifactPublisher = new ModuleArtifactPublisher(repository, localRepo, rootUri, groupId, artifactId, version);
+        SnapshotMetadataResult snapshotMetadataResult = computeSnapshotMetadata(publication, repository, localRepo, version, artifactPublisher, groupId, artifactId);
 
+        if (snapshotMetadataResult != null && !localRepo) {
+            // Use the timestamped version for all published artifacts:
+            // The timestamped version is hidden deep in `Metadata.versioning.snapshotVersions`
+            artifactPublisher.artifactVersion = snapshotMetadataResult.snapshotMetadata.getVersioning().getSnapshotVersions().get(0).getVersion();
```
Comment (ov7a) [inline platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java:78]: ❔ Are there guarantees that `.get(0)` _returns_ the _latest_ snapshot?

File: platforms/software/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy (hunk 1 above)
Comment (ljacomet) [reply platforms/software/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy:227]: This test only use a file based repo, so not immediately.

Changes to log format or to parallelization would impact this test. While the former would be noise, it would also not be hard to update. The later would indicate that care must be taken.

File: platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java (hunk 2 above)
Comment (ljacomet) [reply platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java:78]: Refactored the code to isolate this better

**Review by ov7a — APPROVED** [review]

File: platforms/software/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy [hunk 3]
```diff
@@ -195,4 +195,46 @@ class MavenPublishSnapshotIntegTest extends AbstractMavenPublishIntegTest {
             snapshotVersions == ["1.0-SNAPSHOT"]
         }
     }
+
+    def "published metadata after artifacts"() {
+        settingsFile << 'rootProject.name = "snapshotPublish"'
+        buildFile << """
+    apply plugin: 'java'
```
Comment (jvandort) [inline platforms/software/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy:202]: I understand the other tests in this file use the old plugin application syntax, but can we use the plugins block syntax for new tests?

File: platforms/software/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy [hunk 4]
```diff
@@ -195,4 +195,46 @@ class MavenPublishSnapshotIntegTest extends AbstractMavenPublishIntegTest {
...
+        int outputIndex = 0, matchIndex = 0;
+
+        while (outputIndex < publishTaskOutputLines.size() && matchIndex < expectedPublishedLog.size()) {
+            if (publishTaskOutputLines[outputIndex].startsWith(expectedPublishedLog.get(matchIndex))) {
+                matchIndex++
+            }
+            outputIndex++
+        }
+
+        matchIndex == expectedPublishedLog.size();
```
Comment (jvandort) [inline platforms/software/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy:238]: I find something like this easier to follow

```suggestion
        publishTaskOutputLines.collect { it =~ ~/Uploading (\S*).*/ }.findAll().collect { it.group(1) } == [
            "snapshotPublish-${initialVersion}.jar",
            "snapshotPublish-${initialVersion}.pom",
            "snapshotPublish-${initialVersion}.module",
            'maven-metadata.xml',
            'maven-metadata.xml'
        ]
```

**Review by jvandort — APPROVED** [review]

**Comment by gsosm0760** [comment]
def expectedPublishedLog = ["Uploading snapshotPublish-${initialVersion}.jar", "Uploading snapshotPublish-${initialVersion}.pom", "Uploading snapshotPublish-${initialVersion}.module", 'Uploading maven-metadata.xml', 'Uploading maven-metadata.xml']
-
-        int outputIndex = 0, matchIndex = 0;
-
-        while (outputIndex < publishTaskOutputLines.size() && matchIndex < expectedPublishedLog.size()) {
-            if (publishTaskOutputLines[outputIndex].startsWith(expectedPublishedLog.get(matchIndex))) {
-                matchIndex++
-            }
-            outputIndex++
-        }
-
-        matchIndex == expectedPublishedLog.size();
+        publishTaskOutputLines.collect { it =~ ~/Uploading (\S*).*/ }.findAll().collect { it.group(1) } == [
+            "snapshotPublish-${initialVersion}.jar",
+            "snapshotPublish-${initialVersion}.pom",
+            "snapshotPublish-${initialVersion}.module",
+            'maven-metadata.xml',
+            'maven-metadata.xml'
+        ]
—

File: platforms/software/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy (hunk 3 above)
Comment (ljacomet) [reply platforms/software/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy:202]: Looks like it works for this test indeed. I think to do that at a large scale, we will need to review some fixtures to resolve ordering issues.

**Comment by ljacomet** [comment]
@bot-gradle merge
