### PR TITLE
Let Configuration Cache serialize Java 11 collections correctly

### LINKED ISSUE #26942: Configuration cache error with Java11 collections
### Current Behavior

When using Java11 collections Gradle fails with configuration cache with error:
```
org.gradle.api.GradleException: Could not load the value of field `$myList` of `Build_gradle$$$result$1$1` bean found in field `action` of `org.gradle.api.internal.AbstractTask$TaskActionWrapper` bean found in field `actions` of task `:testJava11Collections` of type `org.gradle.api.DefaultTask`.
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:112)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReader.readStateOf(BeanPropertyReader.kt:68)
        at org.gradle.configurationcache.serialization.codecs.BeanCodec.readBeanOf(BeanCodec.kt:72)
        at org.gradle.configurationcache.serialization.codecs.BeanCodec.decode(BeanCodec.kt:47)
        at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$decodeLoop$1.invokeSuspend(Combinators.kt:166)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.configurationcache.serialization.codecs.jos.JavaObjectSerializationCodec.readResolve(JavaObjectSerializationCodec.kt:194)
        at org.gradle.configurationcache.serialization.codecs.jos.JavaObjectSerializationCodec.decode(JavaObjectSerializationCodec.kt:109)
        at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
        at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:269)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:106)
        ... 169 more
Caused by: java.io.InvalidObjectException: null array
        ... 177 more
        ````

### Expected Behavior

There is no error, Gradle works with Java11 collections.

### Context (optional)

Cannot use a plugin that uses Java11 collections.

### Steps to Reproduce

1. git clone git@github.com:asodja/gradle-cc-with-java11-collections.git
2. Use Java11 to run a project
2. Run `./gradlew :testPreJava11Collections --configuration-cache --stacktrace` -> everything works
3. Run `./gradlew :testJava11Collections --configuration-cache --stacktrace` -> exception is thrown

### Gradle version

Any version, reproducer uses `8.6-20231104002619+0000` nightly 

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by bamboo**
By:

1. Allowing objects returned by `writeReplace` to use Java serialization
2. correctly handling objects with both, `writeObject` and `readResolve` methods; this is the case for the `java.util.CollSer` objects used by Java 11 collections as their serialized representation;

Fixes #26942

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test ACC

File: platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/jos/JavaObjectSerializationCodec.kt [hunk 1]
```diff
@@ -159,14 +165,25 @@ class JavaObjectSerializationCodec(
...
+                    replacement is SerializedLambda -> {
+                        writeEnum(Format.SerializedLambda)
+                        SerializedLambdaParametersCheckingCodec.run {
+                            encode(replacement)
+                        }
+                    }
+
+                    replacement::class.java === value::class.java -> {
+                        // Avoid a StackOverflowException when the replacement and value are of the same type.
+                        // TODO:configuration-cache This is likely incorrect when the class also supports the `writeObject` protocol.
```
Comment (abstratt) [inline platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/jos/JavaObjectSerializationCodec.kt:178]: ❓ 

Can't we test for this? (as a `@ToBeImplemented` test, if confirmed)

Comment (bamboo) [reply platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/jos/JavaObjectSerializationCodec.kt:178]: > Can't we test for this? (as a `@ToBeImplemented` test, if confirmed)

We can. I was saving that for another day.

Comment (abstratt) [reply platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/jos/JavaObjectSerializationCodec.kt:178]: Maybe then expand this TODO to include the reason why you think this would be incorrect?

Comment (bamboo) [reply platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/jos/JavaObjectSerializationCodec.kt]: Done.

**Comment by bamboo** [comment]
@bot-gradle test

**Comment by MrG9090** [comment]
.
