### PR TITLE
Fix problems with file tree outputs

### LINKED ISSUE #4353: Stale output file cleanup always cleans up fileTree output
When a task declares an output which is a file tree, then stale output clean always cleans up the output files before the task runs and the task is never up-to-date.

### Expected Behavior
Declaring a fileTree as a task output causes cleanup of the output directory on version change.

When running the task twice with the same Gradle version, then the task should be up-to-date.

### Current Behavior
Stale output cleanup always deletes the output files before the task executes and the task is never up-to-date.

### Context
The CMake task in this [native sample](https://github.com/gradle/native-samples/blob/1abafa5e7bca609f70e954815af1065c53649613/cpp/cmake-library/library/build.gradle#L90-L152) is never up-to-date.

### Steps to Reproduce (for bugs)
Run `gradle cmakeDebug` twice on the native sample linked above.

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/tvwtqlvrtfhgu/timeline?task=coipa7pjrhutw

### PR DESCRIPTION
**Pull request by wolfs**
Fixes #4353.

Build scan showing that the issue is fixed: https://scans.gradle.com/s/3h735rrjelufi/timeline?task=coipa7pjrhutw

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java [hunk 1]
```diff
@@ -379,12 +383,36 @@ private HistoricalTaskExecution loadPreviousExecution(TaskInternal task) {
...
+        FileCollectionInternal outputFiles = (FileCollectionInternal) taskProperties.getOutputFiles();
+        outputFiles.visitRootElements(new FileCollectionVisitor() {
+            @Override
+            public void visitCollection(FileCollectionInternal fileCollection) {
+                addAllPaths(fileCollection, declaredOutputFilePaths, stringInterner);
+            }
+
+            @Override
+            public void visitTree(FileTreeInternal fileTree) {
+                addAllPaths(fileTree, declaredOutputFilePaths, stringInterner);
```
Comment (lptr) [inline subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java]: What will this add for general file trees? The docs say that `FileTree.getFiles()`...

    Returns the contents of this tree as a flattened Set.

Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java]: Yeah, that's exactly what it would do. I don't really know how you would add a `FileTree` as an output that is not a directory tree. I can see people doing something like
```
outputs.files(zipTree('some.jar'))
```
but I wouldn't recommend it.

Do you have any other kinds of file trees in mind?

**Comment by wolfs** [comment]
@lptr please have another look.

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java [hunk 2]
```diff
@@ -379,12 +384,37 @@ private HistoricalTaskExecution loadPreviousExecution(TaskInternal task) {
...
+        FileCollectionInternal outputFiles = (FileCollectionInternal) taskProperties.getOutputFiles();
+        outputFiles.visitRootElements(new FileCollectionVisitor() {
+            @Override
+            public void visitCollection(FileCollectionInternal fileCollection) {
+                addAllPaths(fileCollection, declaredOutputFilePaths, stringInterner);
+            }
+
+            @Override
+            public void visitTree(FileTreeInternal fileTree) {
+                DeprecationLogger.nagUserOfDeprecated("Adding file trees which are not directory trees as output files", "Outputs should always be actual files");
```
Comment (lptr) [inline subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java]: "Outputs should always be actual files" ... or directories? We just said that adding directory trees is okay?

Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java]: I changed the message.

**Comment by wolfs** [comment]
@lptr Please have another look.
