### PR TITLE
Ignore `null` as an argument in `ConfigurableFileCollection` mutation…

### LINKED ISSUE #32553: Filter null file collection items in `UnresolvedItemsCollector.replace`
I upgraded [AbstractCompile#getClasspath()](https://github.com/gradle/gradle/blob/9f8dcb6e8e44766364eca91f0e27a253d3d6e970/platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/AbstractCompile.java#L60) to ConfigurableFileCollection but now this test fails for me: [DeclarativeAgpSmokeSpec.groovy#L29](https://github.com/gradle/gradle/blob/5daf80312c72d6f0de9dd837aba63523b32b88b0/platforms/core-configuration/declarative-dsl-provider/src/integTest/groovy/org/gradle/internal/declarativedsl/agp/DeclarativeAgpSmokeSpec.groovy#L29) with:
```
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
	at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:815)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.replace(DefaultConfigurableFileCollection.java:683)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.replace(DefaultConfigurableFileCollection.java:373)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.addItem(DefaultConfigurableFileCollection.java:656)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.setFrom(DefaultConfigurableFileCollection.java:630)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.<init>(DefaultConfigurableFileCollection.java:578)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$EmptyCollector.setFrom(DefaultConfigurableFileCollection.java:543)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.newValue(DefaultConfigurableFileCollection.java:359)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.newExplicitValue(DefaultConfigurableFileCollection.java:330)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.setFrom(DefaultConfigurableFileCollection.java:249)
	at org.gradle.internal.classpath.generated.AbstractCompile_Adapter.access_set_setClasspath(AbstractCompile_Adapter.java:19)
	at com.android.build.gradle.tasks.JavaCompileUtils.configureProperties(JavaCompileUtils.kt:98)
	at com.android.build.gradle.tasks.JavaCompileCreationAction.configure(JavaCompile.kt:125)
	at com.android.build.gradle.tasks.JavaCompileCreationAction.configure(JavaCompile.kt:57)
	at com.android.build.gradle.internal.tasks.factory.TaskConfigurationActions.execute(TaskFactoryUtils.kt:94)
	at com.android.build.gradle.internal.tasks.factory.TaskConfigurationActions.execute(TaskFactoryUtils.kt:80)
```

It looks like the 4th element in [this AGP logic](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/JavaCompileUtils.kt;drc=f18bcd663ca8a9d6a6b9698d9091ad659861a0c6;l=98) can be null:
```
this.classpath = project.files(
    // classes(e.g. android.jar) that were previously passed through bootstrapClasspath need to be provided
    // through classpath
    creationConfig.global.bootClasspath,
    creationConfig.compileClasspath,
    creationConfig.getBuiltInKotlincOutput(),
    creationConfig.getBuiltInKaptArtifact(InternalArtifactType.BUILT_IN_KAPT_CLASSES_DIR), // <-- this one seems to be null
)
```

We should probably filter `null` in `UnresolvedItemsCollector` or find another solution or report to AGP.

### PR DESCRIPTION
**Pull request by 6hundreds**
Fixes #32553

### CODE REVIEW

**Comment by 6hundreds** [comment]
@bot-gradle test this on linux

**Review by mlopatkin — APPROVED** [review]
LGTM! Why don't have it in 8.14 though :)? @6hundreds can you please rebase it onto `release` branch?

**Comment by 6hundreds** [comment]
@mlopatkin I'm not against to land it to 8.14. Will do

**Comment by 6hundreds** [comment]
@bot-gradle test and merge

File: platforms/core-configuration/file-collections/src/main/java/org/gradle/api/internal/file/collections/DefaultConfigurableFileCollection.java [hunk 1]
```diff
@@ -675,6 +675,9 @@ public List<Object> replace(FileCollectionInternal original, Supplier<FileCollec
             ImmutableList.Builder<Object> builder = ImmutableList.builderWithExpectedSize(items.size());
             boolean hasChanges = false;
             for (Object candidate : items) {
+                if (candidate == null) {
+                    continue;
```
Comment (alllex) [inline platforms/core-configuration/file-collections/src/main/java/org/gradle/api/internal/file/collections/DefaultConfigurableFileCollection.java:679]: 💭  This is a direct source of silent misconfiguration. I know we [decided](https://github.com/gradle/gradle/issues/32553#issuecomment-2687837464) to fix the NPE first and figure out nulls later, but I'd much prefer we state this in a comment that this is more of a workaround, rather than a long-term decision.

It'd be best to have a dedicated issue already.

File: subprojects/core-api/src/main/java/org/gradle/api/file/ConfigurableFileCollection.java [hunk 2]
```diff
@@ -42,14 +42,14 @@ public interface ConfigurableFileCollection extends FileCollection, HasConfigura
     /**
      * Sets the source paths for this collection. The given paths are evaluated as per {@link org.gradle.api.Project#files(Object...)}.
      *
-     * @param paths The paths.
+     * @param paths The paths. {@code null} values are ignored.
```
Comment (alllex) [inline subprojects/core-api/src/main/java/org/gradle/api/file/ConfigurableFileCollection.java:45]: 🤔  There is also a misalignment with the types. The package is non-null-annotated, so these arguments are never supposed to be null. If we were good citizens, we would have actually checked the argument for null and were still throwing NPE, but early.

So, when we figure out what to do with nulls in CFC, it'd be nice to have this consistent with the argument nullability of the API as well.
