### PR TITLE
Do not handle providers special on a PropertyValue level

### LINKED ISSUE #13932: ListProperty value is observed too eagerly when used as a task dependency
I am having issues with ConfigurationCaching
The following code is trying to translate a FileCollection to Provider<List<RegularFile>>
```
    fileCollection.filter { file -> file.isFile }.elements.map {
        it.map {
                fileSystemLocation -> projectDirectory.file(fileSystemLocation.asFile.absolutePath)
        }
    }
```
and I have a Task :
```
    @get:Classpath
    @get:Incremental
    abstract override val jarClasses: ListProperty<RegularFile>
    ... 
    jarClasses.set(... from the result of the filter ...)
```
The translation code is invoked at Configuration time , I have traced it to org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode :
``` 
       @Nullable
        public Object call() {
            Object value = this.valueSupplier.get();
            return value instanceof Provider && !((Provider)value).isPresent() ? null : value;
        }
```

the call to isPresent() is forcing the resolution.

I can provide the full stack trace if this is useful.

### Expected Behavior
I am expecting the Provider<List<RegularFile>> to only be resolved at execution time.

### Current Behavior
Configuration caching verification spots the resolution during configuration time. 

Build scan URL:
https://scans.gradle.com/s/6ybxjmgdgssm2/failure#1

### PR DESCRIPTION
**Pull request by wolfs**
Calling Provider.isPresent() at task graph building time caused the resolution of some dependencies. We don't actually need to call isPresent() to determine the dependencies.

Instead of ignoring absent providers in `PropertyValue`, we now use special file collections which allow absent providers for the input and output file collections.

Fixes #13932.

### CODE REVIEW

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt [hunk 1]
```diff
@@ -287,7 +288,7 @@ suspend fun WriteContext.writeRegisteredPropertiesOf(
     val outputProperties = collectRegisteredOutputsOf(task)
     writeCollection(outputProperties) { property ->
         property.run {
-            val finalValue = DeferredUtil.unpack(propertyValue)
+            val finalValue = DeferredUtil.unpack(AbsentProviderHandling.ALLOW_ABSENT, propertyValue)
```
Comment (lptr) [inline subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt:291]: WDYT about keeping `Object unpack()` to works as it does today (=strict), and add an `unpackIfPresent(Consumer<Object>)` for the lenient case?

File: subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbsentProviderHandling.java [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+ * limitations under the License.
+ */
+
+package org.gradle.api.internal.provider;
+
+import org.gradle.api.provider.Provider;
+
+import javax.annotation.Nullable;
+
+public enum AbsentProviderHandling {
```
Comment (lptr) [inline subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbsentProviderHandling.java:23]: I don't like the word "handling" here. And there's no need to mention "absent" in the name either. This is about how we go about resolving the provider's value, so it's a `ProviderResolutionStrategy` I think.

File: subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbsentProviderHandling.java [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+    },
+    REQUIRE_PRESENT {
+        @Override
+        public <T> T getValue(Provider<T> provider) {
+            return provider.get();
+        }
+    };
+
+    @Nullable
+    public abstract <T> T getValue(Provider<T> provider);
```
Comment (lptr) [inline subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbsentProviderHandling.java:38]: We might consider calling this `resolveValue()`, or just `resolve()`. I know we use that word in many places, but it fits well what we do here I think.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java [hunk 4]
```diff
@@ -135,11 +136,11 @@ private static void resolveCompositeOutputFilePropertySpecs(final String ownerDi
...
-                FileCollectionInternal outputFiles = fileCollectionFactory.resolving(entry.getValue());
+                FileCollectionInternal outputFiles = fileCollectionFactory.resolving(AbsentProviderHandling.REQUIRE_PRESENT, entry.getValue());
                 consumer.accept(new DefaultCacheableOutputFilePropertySpec(propertyName, "." + id, outputFiles, outputType));
             }
         } else {
-            FileCollectionInternal outputFileCollection = fileCollectionFactory.resolving(unpackedValue);
+            FileCollectionInternal outputFileCollection = fileCollectionFactory.resolving(AbsentProviderHandling.REQUIRE_PRESENT, unpackedValue);
             AtomicInteger index = new AtomicInteger(0);
             outputFileCollection.visitStructure(new FileCollectionStructureVisitor() {
                 @Override
```
Comment (lptr) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java:146]: What strikes me here is that all the calls to `fileCollectionFactory.resolving()` in `resolveInputFileValue()` take `ALLOW_ABSENT`, while all the calls in `resolveOutputFilePropertySpecs()` take `REQUIRE_PRESENT`. I wonder if we could somehow remove this redundancy. Something like `fileCollectionFactory.lenient()` giving you a variant of the factory that uses `ALLOW_ABSENT` perhaps?

**Review by lptr — COMMENTED** [review]
I left some comments.

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java (hunk 4 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java]: I added `resolvingIfPresent` to `FileCollectionFactory` and removed the duplication from the to `resolve` methods in `FileParametersUtils`. I think it is clearer now. I don't want to create a full `FileCollectionFactory` which has a lot of lenient methods. So I would need to introduce a new interface with only two methods.

File: subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbsentProviderHandling.java (hunk 3 above)
Comment (wolfs) [reply subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbsentProviderHandling.java]: Renamed.

File: subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbsentProviderHandling.java (hunk 2 above)
Comment (wolfs) [reply subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbsentProviderHandling.java]: Renamed to `ProviderResolutionStrategy`.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt (hunk 1 above)
Comment (wolfs) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt]: I did that.

Comment (lptr) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt]: What you did is somewhat different to what I suggested (which is to handle the unpacked value via a `Consumer`). Your approach could also work, but if we go with it, I think the method should be called `unpackOrNull()` instead.

File: subprojects/file-collections/src/main/java/org/gradle/api/internal/file/FileCollectionFactory.java [hunk 5]
```diff
@@ -96,16 +96,38 @@
...
     FileCollectionInternal resolving(Object sources);
 
+    /**
+     * Creates a {@link FileCollection} with the given files as content.
+     *
+     * <p>The collection is live and resolves the files on each query.
+     *
+     * <p>The collection ignores providers which are not present.
+     */
+    FileCollectionInternal resolvingIfPresent(Object sources);
```
Comment (lptr) [inline subprojects/file-collections/src/main/java/org/gradle/api/internal/file/FileCollectionFactory.java:129]: For me `ifPresent` means that code will only be executed if there is a value, otherwise we'll have a no-op. These new methods don't do that, but instead selectively ignore absent values. Something like `resolvingLeniently()` would capture this behavior better for me.

Comment (wolfs) [reply subprojects/file-collections/src/main/java/org/gradle/api/internal/file/FileCollectionFactory.java]: You are right. I renamed the methods to `resolvingLeniently()`.

File: subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt (hunk 1 above)
Comment (wolfs) [reply subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt]: Right. I renamed the method to `unpackOrNull()`. The consumer variant doesn't work really well, since I mostly need to do something in the `null` case as well.

**Review by lptr — APPROVED** [review]
LGTM.
