### PR TITLE
Fix issue with mustRunAfter and ordinal node dependencies

### LINKED ISSUE #20272: Tasks that show up later on the command line can be mysteriously skipped
There is an issue in the logic introduced in 7.4 to better ensure command line order is honored.  When a task gets pulled in from an earlier command line selector has a `mustRunAfter` relationship to a task that does not get executed, tasks pulled in by later command line selectors can be skipped.

For example, if I run `clean build` on the command line, and clean has `mustRunAfter foo` but the foo task is not a part of the build (i.e. neither clean nor build pull in foo), then the producer tasks pulled in by build will get skipped.

### Expected Behavior
All tasks should execute

### Current Behavior
Tasks from selectors later on the command line simply do not execute

### Steps to Reproduce 
```
plugins {
    id 'java'
}


task foo
clean.mustRunAfter foo
```

Run: `clean build`

### PR DESCRIPTION
**Pull request by ghale**
Fixes #20272

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test rFM

File: subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNode.java [hunk 1]
```diff
@@ -116,4 +119,10 @@ public Type getType() {
     public int getOrdinal() {
         return ordinal;
     }
+
+    public void addDependenciesFrom(TaskNode taskNode) {
+        // Only add hard successors that will actually be executed
+        Stream<Node> executingSuccessors = stream(taskNode.getHardSuccessors().spliterator(), false).filter(Node::isRequired);
```
Comment (DPUkyle) [inline subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNode.java:125]: Let's keep an eye on this in perf tests; do we have any alternatives to opening a stream?

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java [hunk 2]
```diff
@@ -404,8 +404,8 @@ private void createOrdinalRelationships(Node node) {
 
             if (taskClassifier.isDestroyer()) {
                 // Create (or get) a destroyer ordinal node that depends on the dependencies of this task node
-                Node ordinalNode = ordinalNodeAccess.getOrCreateDestroyableLocationNode(taskNode.getOrdinal());
-                taskNode.getHardSuccessors().forEach(ordinalNode::addDependencySuccessor);
+                OrdinalNode ordinalNode = (OrdinalNode) ordinalNodeAccess.getOrCreateDestroyableLocationNode(taskNode.getOrdinal());
```
Comment (DPUkyle) [inline subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java:407]: Is the downcast always safe?

**Review by DPUkyle — APPROVED** [review]
Thanks for the quick turnaround. LGTM pending two questions about the downcast and streams API.

**Comment by DPUkyle** [comment]
@bot-gradle RFM

**Comment by DPUkyle** [comment]
@bot-gradle clean

**Comment by DPUkyle** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java (hunk 2 above)
Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java:407]: Yep.  Should be.  I suppose `OrdinalNodeAccess` should always return `OrdinalNode`s, though.

File: subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNode.java (hunk 1 above)
Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNode.java:125]: I'd be shocked if there was a noticeable impact.  A loop would likely be slightly more performant, but it's only doing this once per task in the graph.  There is most certainly overhead associated with it, but my gut feeling is that it's not significant.  We'll see if the perf tests say otherwise.

**Comment by ghale** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test and merge
