### PR TITLE
DCL: Support any DependencyModifier

### LINKED ISSUE #36173: DCL: Support testFixtures (or any DependencyModifier)
### Expected Behavior

using `id("org.gradle.experimental.kmp-ecosystem").version("0.1.49")`

```kotlin
// build.gradle.dcl
kotlinJvmLibrary {
    javaVersion = 21

    testing {
        dependencies {
            implementation(testFixtures("org.jetbrains.kotlin:kotlin-test:2.3.0"))
        }
    }
}
```

### Current Behavior (optional)

```
    Failures in resolution:
      6:34: unresolved function call signature for 'testFixtures'
      6:19: unresolved function call arguments for 'implementation'
      6:19: unresolved function call signature for 'implementation'
```

### Context

1. `DependencyModifier` is not annotated with `HiddenInDeclaration`: https://github.com/gradle/gradle/blob/948f80eedadd35d036e9d72f067df568e47cbc79/subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyModifier.java#L51

The declarative samples uses PlatformDependencyModifiers https://github.com/gradle/declarative-gradle/blob/main/unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kotlin/testing/KotlinTestDependencies.java#L24, but the interface does not contain any `Declaration` visible methods: https://github.com/gradle/gradle/blob/948f80eedadd35d036e9d72f067df568e47cbc79/subprojects/core-api/src/main/java/org/gradle/api/plugins/jvm/PlatformDependencyModifiers.java#L52

Thats why the test did not fail, but adding `TestFixturesDependencyModifiers` to `KotlinTestDependencies` fails during runtime with the error: 
```
> Illegal 'OUT' variance
    in type argument 'out org.gradle.api.artifacts.MinimalExternalModuleDependency'
    in return value type 'org.gradle.api.provider.Provider<out org.gradle.api.artifacts.MinimalExternalModuleDependency>'
    in member 'fun org.gradle.api.artifacts.dsl.DependencyModifier.modify(org.gradle.api.provider.ProviderConvertible<out org.gradle.api.artifacts.MinimalExternalModuleDependency!>!): org.gradle.api.provider.Provider<out org.gradle.api.artifacts.MinimalExternalModuleDependency!>!'
    in class 'org.gradle.api.plugins.jvm.TestFixturesDependencyModifiers.TestFixturesDependencyModifier'
```
Reason: `DependencyModifier` is not annotated with `HiddenInDeclaration`

2. The kotlin-dsl contains overloads for a custom dependencies block: https://github.com/gradle/gradle/blob/948f80eedadd35d036e9d72f067df568e47cbc79/platforms/core-configuration/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/DependenciesExtensions.kt

DCL does not contain such overloads (yet), so after fixing `DependencyModifier`, the DCL can't resolve the operator invoke method for the `testFixtures` `DependencyModifier`.

### PR DESCRIPTION
**Pull request by hfhbd**
* Fixes #36173

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [X] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by mlopatkin** [comment]
Thank you for your proposed contribution!

This PR has a valid DCO and tests. The relevant team for this area will confirm the implementation choices.

File: platforms/core-configuration/declarative-dsl-provider/src/main/kotlin/org/gradle/internal/declarativedsl/dependencycollectors/DependencyCollectorFunctionExtractorAndRuntimeResolver.kt [hunk 1]
```diff
@@ -85,19 +89,33 @@ class DependencyCollectorFunctionExtractorAndRuntimeResolver(
...
-                addAll(extractModifierSchemaFunctions(host, kClass).map { ExtractionResult.Companion.of(it, FunctionExtractionMetadata(emptyList())) })
+            val members = host.classMembers(kClass).declarativeMembers
+
+            val dependencyModifiers = members.filter { member ->
+                member.returnType.toKType().isSubtypeOf(typeOf<DependencyModifier>())
+            }.map { member ->
+                @Suppress("UNCHECKED_CAST")
+                val getModifier = member.kCallable as KCallable<DependencyModifier>
+                val modifierName = if (member.isJavaBeanGetter) {
+                    member.name.drop(3).replaceFirstChar { it.lowercase() }
```
Comment (eskatos) [inline platforms/core-configuration/declarative-dsl-provider/src/main/kotlin/org/gradle/internal/declarativedsl/dependencycollectors/DependencyCollectorFunctionExtractorAndRuntimeResolver.kt]: 🎨 This would be the second place where we extract a property name from a Java Bean getter according to the contract of `isJavaBeanGetter`.
The other place is here: 

https://github.com/gradle/gradle/blob/1d3ae4cabac93a06fe41016a67266a1b2c6e2559/platforms/core-configuration/declarative-dsl-core/src/main/kotlin/org/gradle/internal/declarativedsl/schemaBuilder/PropertyExtractor.kt#L89-L90

Let's extract an extension function next to the `isJavaBeanGetter` one to have that logic only once and colocated with `isJavaBeanGetter`.

This other place is also inferring a setter name from the getter name, another extension might be in order to complete this.

File: subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyModifier.java [hunk 2]
```diff
@@ -41,12 +42,14 @@
  * @implNote All implementations of {@code modify(...)} delegate to {@link #modifyImplementation(ModuleDependency)}.
  * <p>
  * Changes to this interface may require changes to the
- * {@link org.gradle.api.internal.artifacts.dsl.dependencies.DependenciesExtensionModule extension module for Groovy DSL} or
- * {@link org.gradle.kotlin.dsl.DependenciesExtensions extension functions for Kotlin DSL}.
+ * {@link org.gradle.api.internal.artifacts.dsl.dependencies.DependenciesExtensionModule extension module for Groovy DSL},
+ * {@link org.gradle.kotlin.dsl.DependenciesExtensions extension functions for Kotlin DSL} and
+ * {@link org.gradle.internal.declarativedsl.dependencycollectors.DependencyCollectorFunctionExtractorAndRuntimeResolver for Declarative DSL}.
```
Comment (eskatos) [inline subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyModifier.java]: ❌ Let's not mention this internal type in a public Javadoc. I recommend leaving the Javadoc here untouched.

**Review by eskatos — CHANGES_REQUESTED** [review]
Thanks, this is looking good.

I requested a couple minor changes, PTAL.
Moreover, there are some merge conflicts. Please rebase on `master`.

File: platforms/core-configuration/declarative-dsl-provider/src/main/kotlin/org/gradle/internal/declarativedsl/dependencycollectors/DependencyCollectorFunctionExtractorAndRuntimeResolver.kt (hunk 1 above)
Comment (hfhbd) [reply platforms/core-configuration/declarative-dsl-provider/src/main/kotlin/org/gradle/internal/declarativedsl/dependencycollectors/DependencyCollectorFunctionExtractorAndRuntimeResolver.kt]: You should not use `Locale.getDefault()` or `Locale.US` but `Locale.ROOT` for source code: https://github.com/Kotlin/KEEP/blob/main/proposals/stdlib/KEEP-0223-locale-agnostic-case-conversions.md or https://sam-cooper.medium.com/the-country-that-broke-kotlin-84bdd0afb237 that contains the background.

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by eskatos — APPROVED** [review]
