### PR TITLE
Set Checkstyle Java Launcher to current JDK when CheckstylePlugin is not applied

### LINKED ISSUE #21353: CheckStyle fails because it has no javaLauncher configured
We are having a custom `CheckStyle` task to provide aggregated results from the subprojects. After upgrading to Gradle 7.5 it fails with following reason.

```
* What went wrong:
A problem was found with the configuration of task ':aggregateCheckstyle' (type 'Checkstyle').
  - Type 'org.gradle.api.plugins.quality.Checkstyle' property 'javaLauncher' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'javaLauncher'.
      2. Mark property 'javaLauncher' as optional.
    
    Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#value_not_set for more details about this problem.
```

### Expected Behavior

The Java Launcher is optional and if not configured then the task falls back to the original behavior using `CheckstyleInvoker.invoke(this)`.

### Current Behavior
When the `javaLauncher` is not optional then the root project for our aggregated Checkstyle project would have to apply the Java plugin to get access to the Toolchains and Launcher which does not make any sense.

### Context
The behavior is broken in Gradle 7.5

### Steps to Reproduce 
Clone https://github.com/musketyr/aggregate-checkstyle-issue and run `AggregateCheckstyleReportsPluginSpec` test.

### Your Environment

Build scan URL: https://scans.gradle.com/s/4vfibe753v3fs

### PR DESCRIPTION
**Pull request by asodja**
You can create a Checkstyle task without applying CheckstylePlugin. Due to that and changes in 7.5 we broke some builds, since Java Launcher is not set in this case. It might be a case we shouldn't encourage, but for the backward compatibility I think it's still nice we fix it.

With this fix we now set the Checkstyle Java Launcher convention always to current JDK, in case CheckstylePlugin is not applied.

Fixes #21353.

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle cancel

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle cancel

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java [hunk 1]
```diff
@@ -123,11 +122,12 @@ private void configureReportsConventionMapping(Checkstyle task, final String bas
     }
 
     private void configureToolchains(Checkstyle task) {
-        Provider<JavaLauncher> javaLauncherProvider = getToolchainService().launcherFor(new CurrentJvmToolchainSpec(project.getObjects()));
-        task.getJavaLauncher().convention(javaLauncherProvider);
         project.getPluginManager().withPlugin("java-base", p -> {
             JavaToolchainSpec toolchain = getJavaPluginExtension().getToolchain();
-            task.getJavaLauncher().convention(getToolchainService().launcherFor(toolchain).orElse(javaLauncherProvider));
+            Provider<JavaLauncher> javaLauncherProvider = getToolchainService().launcherFor(toolchain);
+            if (javaLauncherProvider.isPresent()) {
```
Comment (big-guy) [inline subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java:128]: I think this isn't necessary.  It's OK if the convention here overwrites the other one

**Review by big-guy — CHANGES_REQUESTED** [review]

File: subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java (hunk 1 above)
Comment (asodja) [reply subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java]: Effectively that works as before :)

Comment (asodja) [reply subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java]: I reverted that logic to previous one

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test and merge
