### PR TITLE
Refuse connections from non-Gradle processes

### LINKED ISSUE #27801: Socket connections from non-gradle applications crash gradle executors
### Current Behavior

A Gradle executor experiences this exception:
```
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:49184'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
        at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: 
        at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:72)
        at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
        at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
org.gradle.internal.remote.internal.ConnectException: Could not connect to server [4f40fbf1-8d30-4c4a-9ba1-aaa9b723f4ea port:39287, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:67)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedClient.getConnection(MessageHubBackedClient.java:36)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:103)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:122)
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.tryConnect(TcpOutgoingConnector.java:81)
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:54)
	... 5 more
```
And the build fails due to this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':storage:test'.
> Process 'Gradle Test Executor 102' finished with non-zero exit value 1
  This problem might be caused by incorrect test process configuration.
  For more on test execution, please refer to https://docs.gradle.org/8.5/userguide/java_testing.html#sec:test_execution in the Gradle documentation.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
```

### Expected Behavior

The connection should be accepted, and then disconnected once the received data is shown to be invalid. The Gradle executor should continue running and accepting connections until a valid connection has been made. The Gradle executor could keep running indefinitely without a connection, or given a moderate (1min) timeout before the connection is abandoned completely.

### Context (optional)

We use Gradle to build the [Apache Kafka](https://github.com/apache/kafka) project, and received this [bug report](https://issues.apache.org/jira/browse/KAFKA-15343) from one of our contributors.

We have numerous tests which appear to leak clients in this way, and it appears that the particulars of the Gradle protocol and the Kafka protocol happen to cause the Gradle end of the connection to exit ungracefully.

We are also working to reduce the number of leaked clients and network connections in our project to mitigate this failure, but it is very likely that there are downstream users of Kafka clients which could experience the same style of defect in their tests, and have similar build failures. And more generally, any sort of client could happen to connect to the Gradle executor and trigger this failure with a crafted response. This could be happening without Kafka in use at all, theoretically.

This appears similar to the descriptions of #27512, #23602, and #12566 but I thought to open this issue separately with my reproduction case if it turns out to be distinct.

### Steps to Reproduce

1. A test opens a server socket with port 0, and gets assigned a random port N
2. The test starts a client which will continue to reconnect to port N indefinitely if the connection with the server is lost
3. The test stops the server, and port N is released to the OS and allowed to be reassigned
4. The client beings retrying connections to port N
5. A Gradle executor is eventually assigned port N by the OS
6. The client connects to port N, and reaches the Gradle executor unintentionally
7. The Gradle executor is killed due to an exception

Here is a reproducer: https://github.com/gharris1727/gradle-crash-reproducer . For a specific failed build, see https://github.com/gharris1727/gradle-crash-reproducer/actions/runs/7632481625/job/20792782276 .

The reproducer has 4 modules, structured such that the tests for `app-2` start after the tests for `app-1` are already running. `app-1` is continuously searching for ports which it can't bind() the address for, and connecting to them and then immediately closing the connection. This specific reproducer relies on MacOS for sequential port allocation in order to make it more reliable, but I think the same failure is possible on any platform.

Here's the logs from the reproducer, in case the action becomes inaccessible:
```
2024-01-23T22:13:08.059+0000 [DEBUG] [TestEventLogger] Gradle Test Run :app-2:test STARTED
...
2024-01-23T22:13:08.069+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.TcpIncomingConnector] Listening on [77f73e7b-bbe9-4630-8033-0a25e66a99f3 port:58112, addresses:[localhost/127.0.0.1]].
...
2024-01-23T22:13:08.393+0000 [DEBUG] [TestEventLogger] TestWithLeakedClient > test() STANDARD_OUT
2024-01-23T22:13:08.393+0000 [DEBUG] [TestEventLogger]     [58112, 58113, 54322, 54323, 55555, 54324, 55556]
...
Error: -23T22:13:08.406+0000 [ERROR] [org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection] Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:54325'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:140)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:333)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:462)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:279)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:267)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:261)
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:138)
	... 6 more
Error: -23T22:13:08.609+0000 [ERROR] [system.err] org.gradle.internal.remote.internal.ConnectException: Could not connect to server [77f73e7b-bbe9-4630-8033-0a25e66a99f3 port:58112, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].
Error: -23T22:13:08.610+0000 [ERROR] [system.err] 	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:67)
Error: -23T22:13:08.610+0000 [ERROR] [system.err] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedClient.getConnection(MessageHubBackedClient.java:36)
Error: -23T22:13:08.610+0000 [ERROR] [system.err] 	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:103)
Error: -23T22:13:08.610+0000 [ERROR] [system.err] 	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
Error: -23T22:13:08.610+0000 [ERROR] [system.err] 	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
Error: -23T22:13:08.610+0000 [ERROR] [system.err] 	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Error: -23T22:13:08.611+0000 [ERROR] [system.err] Caused by: java.net.ConnectException: Connection refused
Error: -23T22:13:08.611+0000 [ERROR] [system.err] 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
Error: -23T22:13:08.611+0000 [ERROR] [system.err] 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:774)
Error: -23T22:13:08.611+0000 [ERROR] [system.err] 	at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:120)
Error: -23T22:13:08.612+0000 [ERROR] [system.err] 	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.tryConnect(TcpOutgoingConnector.java:81)
Error: -23T22:13:08.612+0000 [ERROR] [system.err] 	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:54)
Error: -23T22:13:08.612+0000 [ERROR] [system.err] 	... 5 more
```

### Gradle version

8.5

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by oehme**
Gradle uses TCP sockets to allow its worker processes to connect back to the daemon. The ports for those sockets are randomly assigned by the operating system and on a busy CI machine, a port might have been used for a different purpose before. There might still be clients programs trying to connect to that port, e.g. because of insufficient cleanup in a previous test. Until now, Gradle's test infrastructure would crash if a non-Gradle program connected to one of these worker ports.

This change makes Gradle more resilient by requiring a special handshake before a connection is accepted.

Fixes #27801

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by oehme** [comment]
I tried this with the reproducer provided by @gharris1727 and it fixes the described problem. The test executor can connect and run the tests while the "stray connections" are logged and ignored.

File: platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java [hunk 1]
```diff
@@ -109,13 +117,34 @@ public void run() {
...
+                                if (read == -1) {
+                                    break;
+                                }
+                                if (read == 0) {
+                                    Thread.sleep(10);
+                                }
+                            }
+                            if (!Arrays.equals(buffer.array(), CONNECTION_PREAMBLE)) {
+                                throw new IOException("Did not receive connection preamble within " + acceptTimeoutSeconds + "s");
+                            }
```
Comment (mar1u50) [inline platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java]: If the buffer didn’t fill completely, buffer.array() may contain zeros (or leftover bytes), and the comparison will fail even if partial data was read. Note: I'm not familiar with this codebase so I may be wrong.

Suggestion:
```
    if (buffer.position() < CONNECTION_PREAMBLE.length ||
        !Arrays.equals(buffer.array(), CONNECTION_PREAMBLE)) {
        throw new IOException("Did not receive valid connection preamble within " + acceptTimeoutSeconds + "s");
    }
```

Comment (oehme) [reply platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java]: >  the comparison will fail even if partial data was read

That's intentional. If we didn't receive the full string in the given time, then we want to fail.

Comment (mar1u50) [reply platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java]: Thank you for clarification.

You’re right - as written, both my suggestion and your original snippet only check the buffer after the loop finishes, i.e. either:
- the buffer filled completely, or
- the timeout expired, or
- the peer closed the connection.

**Comment by hegyibalint** [comment]
Thank you for your proposed contribution!

This PR has a valid DCO and tests. The relevant team for this area will confirm the design of the implementation choices.

File: platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy [hunk 2]
```diff
@@ -321,5 +322,28 @@ class TcpConnectorTest extends ConcurrentSpec {
...
+        def socketChannel = SocketChannel.open()
+        def acceptor = incomingConnector.accept(action, false)
+        def communicationAddress = addressFactory.getLocalBindingAddress()
+        def bindAnyPort = new InetSocketAddress(communicationAddress, 0)
+        def connectAddress = new InetSocketAddress(communicationAddress, acceptor.address.port)
+
+        when:
+        socketChannel.socket().bind(bindAnyPort)
+        socketChannel.socket().connect(connectAddress)
+        acceptor?.stop()
```
Comment (abstratt) [inline platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy]: ❓ 

Null-safety is not required here, right?

Also, is this part of the scenario being tested? If not, can't we just stop the acceptor during `cleanup`?

File: platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy [hunk 3]
```diff
@@ -321,5 +322,28 @@ class TcpConnectorTest extends ConcurrentSpec {
...
+
+        then:
+        !connected
+
+        cleanup:
+        socketChannel.close()
```
Comment (abstratt) [inline platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy]: ❓ 

Don't we need to `acceptor?.stop()` in case we fail during the test?

File: platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java [hunk 4]
```diff
@@ -109,13 +117,34 @@ public void run() {
...
+                            LOGGER.error("Failed connection handshake with {}.", remoteSocketAddress, e);
+                            socket.close();
+                            continue;
+                        }
+
+                        LOGGER.debug("Accepted connection from {} to {}.", socket.socket().getRemoteSocketAddress(), socket.socket().getLocalSocketAddress());
+                        try {
                             action.execute(new SocketConnectCompletion(socket));
                         } catch (Throwable t) {
                             socket.close();
```
Comment (abstratt) [inline platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java:137]: ❓ 

Not introduced via this PR, but I noticed we only close the socket in case of failure. What ensures the socket is closed in case of success?

File: platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy (hunk 2 above)
Comment (oehme) [reply platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy]: I just copied this test from the one above, which also used the null-safe access. No deeper reason :)

And yes, this is part of the scenario, because stopping the acceptor will wait for the outstanding connection requests to be handled. We want to make sure that it is handled before we assert that it was refused.

File: platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy (hunk 3 above)
Comment (oehme) [reply platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy]: True.

File: platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java (hunk 4 above)
Comment (oehme) [reply platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java:137]: In case of success, the caller who provided the `action` is responsible for closing the connection when they are done talking to the other side.

Comment (abstratt) [reply platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java:137]: Thanks. I tried to find evidence of that before asking the question, but couldn't. 

The action is executed synchronously, right? Since `close()` is safe to be called multiple times, I'd suggest we called it from a finally block as a safety measure.

File: platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy (hunk 3 above)
Comment (abstratt) [reply platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy]: In that case, from the cleanup block, it would be best to perform null safe invocation, to avoid a NPE that would mask the original failure.

File: platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy [hunk 5]
```diff
@@ -313,12 +313,37 @@ class TcpConnectorTest extends ConcurrentSpec {
...
         socketChannel.socket().bind(bindAnyPort)
         socketChannel.socket().connect(connectAddress)
+        socketChannel.socket().outputStream.write(TcpOutgoingConnector.CONNECTION_PREAMBLE)
 
         then:
         !outgoingConnector.detectSelfConnect(socketChannel)
 
         cleanup:
-        acceptor?.stop()
+        acceptor.stop()
```
Comment (abstratt) [inline platforms/core-runtime/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy]: 💅 

This should still use a null-safe invocation, since it is a cleanup block

File: platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/daemon/server/DaemonTcpServerConnector.java [hunk 6]
```diff
@@ -51,7 +51,8 @@ public DaemonTcpServerConnector(ExecutorFactory executorFactory, InetAddressFact
         this.incomingConnector = new TcpIncomingConnector(
                 executorFactory,
                 inetAddressFactory,
-                new UUIDGenerator()
+                new UUIDGenerator(),
+            10
```
Comment (abstratt) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/daemon/server/DaemonTcpServerConnector.java]: 💅 

Please fix  indentation

File: platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/services/MessagingServices.java [hunk 7]
```diff
@@ -62,7 +62,8 @@ protected IncomingConnector createIncomingConnector(ExecutorFactory executorFact
         return new TcpIncomingConnector(
                 executorFactory,
                 inetAddressFactory,
-                idGenerator
+                idGenerator,
+            10
```
Comment (abstratt) [inline platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/services/MessagingServices.java]: 💅 
Indentation

**Comment by abstratt** [comment]
@bot-gradle test this

**Comment by abstratt** [comment]
@oehme `DaemonInitialCommunicationFailureIntegrationSpec` is failing with these changes. You should be able to reproduce it locally. Could please look into it?

File: platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java (hunk 4 above)
Comment (oehme) [reply platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/TcpIncomingConnector.java:137]: We can't close the connection here, because the communication doesn't happen synchronously. The `action` only hands off the newly established connection to the code that wants to use it.  See MessageHubBackedServer and DefaultWorkerProcessBuilder. It is that code's responsibility to close the connection once it is done talking to the other side.

**Comment by oehme** [comment]
@abstratt I've changed the test in DaemonInitialCommunicationFailureIntegrationSpec, so that it still triggers the log message ("Unable to receive command from client") in the daemon code that it is checking for. However, in a realistic scenario, this code will not be hit anymore, because we're now handling bad connection attempts earlier, so that it works not just for the daemon, but also for the workers. So another option would be to remove the special log line in the daemon and also remove the expectation for this log line from the test. What do you think?

**Comment by abstratt** [comment]
@bot-gradle test this

**Comment by abstratt** [comment]
> @abstratt I've changed the test in DaemonInitialCommunicationFailureIntegrationSpec, so that it still triggers the log message ("Unable to receive command from client") in the daemon code that it is checking for.

You haven't shared that change yet, right? 

There are two different error conditions that may occur:
1. random client talks to Gradle Daemon/workers
2. a Gradle-aware client sends bad data (causing payload deserialization errors)

Your fix here deals with the first issue. The second issue still could happen, and that test case should be updated to continue to exercise that (by sending the expected preamble first).

**Comment by oehme** [comment]
> You haven't shared that change yet, right?

Yes, I have. https://github.com/gradle/gradle/pull/35175/commits/46ec3752edf2c549b9d08c0af2fa250589046d25#diff-7422e8894f6db83842ca8315400b71aab06623fd63ec8c54e945f61f8bc6c0bbR169

> a Gradle-aware client sends bad data (causing payload deserialization errors)

That seems highly unlikely, given that client and server are part of the same Gradle installation and always tested together. If you look at the test, you can see it was simulating a completely different type of client (HTTP GET request). So I think the intention was handling the case that this PR handles, but it only did so for the daemon, not the workers. Either way, I don't mind :)

**Comment by abstratt** [comment]
I agree with your assessment, but an invalid payload, while less likely, is still a possibility, so I'd rather see a test case that hits that part of the code (as we don't have any other test that does that).  Could you please update the branch backing this PR so it contains that commit?

> given that client and server are part of the same Gradle installation

I was curious about that - so it is never possible for a Gradle client from one version to hit a daemon/worker process from a different version, right?

**Comment by oehme** [comment]
> Could you please update the branch backing this PR so it contains that commit?

Not sure what you mean, it is here already.

> I was curious about that - so it is never possible for a Gradle client from one version to hit a daemon/worker process from a different version, right?

Correct, they are always part of the same Gradle distribution.

**Comment by abstratt** [comment]
@bot-gradle test this

**Comment by oehme** [comment]
Mhh I think those Windows failures were caused by a missing `flush`. I've pushed a fix.

**Comment by abstratt** [comment]
@bot-gradle test this

**Comment by abstratt** [comment]
@oehme  It seems there is still some [flakiness going](https://ge.gradle.org/scans/tests?search.names=gitCommitId&search.tags=CI&search.timeZoneId=America%2FSao_Paulo&search.values=c9767d74e187ef704b99c82c315b110b2b164151&tests.container=org.gradle.launcher.daemon.DaemonInitialCommunicationFailureIntegrationSpec&tests.test=stop%20behaves%20if%20the%20registry%20contains%20connectable%20port%20without%20daemon%20on%20the%20other%20end) on with `DaemonInitialCommunicationFailureIntegrationSpec."stop behaves if the registry contains connectable port without daemon on the other end"` on Windows.

**Comment by oehme** [comment]
Looking into it.

**Comment by oehme** [comment]
I couldn't reproduce it locally, but I think I found it - The logging in that test is triggered only on `ConnectExceptions` and there was one path where we were throwing a plain `RuntimeException` instead. Depending on the timing, we could end up in that path.

**Comment by abstratt** [comment]
@bot-gradle test this

**Comment by oehme** [comment]
Still the same test failure, I'll have another look.

**Comment by abstratt** [comment]
> I couldn't reproduce it locally, but I think I found it - The logging in that test is triggered only on `ConnectExceptions` and there was one path where we were throwing a plain `RuntimeException` instead. Depending on the timing, we could end up in that path.

@oehme Do you mean on your dev machine? Or do you use/have access to a Windows box? I am assuming at ths point this is a Windows-only issue.

**Comment by oehme** [comment]
Yeah, I'm on linux. I've pushed some additional logging to get to the bottom of this on CI.

File: platforms/core-runtime/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonInitialCommunicationFailureIntegrationSpec.groovy [hunk 8]
```diff
@@ -198,18 +202,12 @@ class DaemonInitialCommunicationFailureIntegrationSpec extends DaemonIntegration
...
+                            SocketChannel connection = socket.accept()
+                            connection.write(ByteBuffer.wrap("hello".getBytes(StandardCharsets.UTF_8)))
                         } catch (IOException e) {
                             return
                         }
-                        try {
-                            connection.read(ByteBuffer.allocate(4096))
-                            connection.write(ByteBuffer.wrap("hello".bytes))
-                        } finally {
-                            connection.close()
```
Comment (oehme) [inline platforms/core-runtime/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonInitialCommunicationFailureIntegrationSpec.groovy:211]: Found the problem - The test server was closing the connection right away, even if the client had not yet read the "hello" above. On Linux this seems to work out anyway, but it breaks on Windows.

Fixed by not closing the connection at all - The whole socket is closed at the end of the test, which cleans up all connections.

**Comment by oehme** [comment]
@abstratt this should be ready now - I also ran the "ready for nightly" build to ensure the performance didn't change.

File: platforms/core-runtime/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonInitialCommunicationFailureIntegrationSpec.groovy (hunk 8 above)
Comment (abstratt) [reply platforms/core-runtime/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonInitialCommunicationFailureIntegrationSpec.groovy:211]: Thanks, Stefan!

File: platforms/core-runtime/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonInitialCommunicationFailureIntegrationSpec.groovy [hunk 9]
```diff
@@ -198,18 +202,12 @@ class DaemonInitialCommunicationFailureIntegrationSpec extends DaemonIntegration
                 @Override
                 void run() {
                     while (true) {
-                        SocketChannel connection
                         try {
-                            connection = socket.accept()
+                            SocketChannel connection = socket.accept()
+                            connection.write(ByteBuffer.wrap("hello".getBytes(StandardCharsets.UTF_8)))
```
Comment (abstratt) [inline platforms/core-runtime/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonInitialCommunicationFailureIntegrationSpec.groovy:207]: @oehme Could you please add a comment here explaining why we don't close it yet?

Comment (oehme) [reply platforms/core-runtime/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonInitialCommunicationFailureIntegrationSpec.groovy:207]: Done

**Comment by abstratt** [comment]
This will be in Gradle's next release. 🎉 

Thanks, Stefan, great work!
