### PR TITLE
Make Configuration.copy() work when project dependency constraint is present

### LINKED ISSUE #17179: Making a Configuration Copy throws ClassCastException if Type other than DefaultDependencyConstraint among Constraints
The multi-module project I'm working on uses [version alignment](https://docs.gradle.org/current/userguide/dependency_version_alignment.html). As a result my BOM module holds configurations with submodule constraints. Since I'm working on a custom plugin I need to create editable copies for all configurations in my project. When trying to make a copy of a configuration with submodule constraints the following exception is raised: 

```groovy
"java.lang.ClassCastException: class org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependencyConstraint cannot be cast to class org.gradle.api.internal.artifacts.dependencies.DefaultDependencyConstraint (org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependencyConstraint and org.gradle.api.internal.artifacts.dependencies.DefaultDependencyConstraint are in unnamed module of loader org.gradle.initialization.MixInLegacyTypesClassLoader @7a5ceedd)"
```

I discovered that `DefaultConfiguration` does the following:

https://github.com/gradle/gradle/blob/7286dcd1d9b46297fd62231cc7fbf17d958604aa/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L1141-L1143

In other words, if a `DefaultProjectDependencyConstraint` is among `dependencyConstraints` this won't succeed. From my point of view this behavior can't be intended since the troublesome type is valid among configuration constraints.

Possible solutions:
* remove cast and place `copy()` inside `DependencyConstraint` to have all subtypes override it
* offer `copy(...)` with param `Spec<? super DependencyConstraint> dependencyConstraintSpec` which could be used to filter out constraints not meant to be copied -> still there must be a good reason not to make some constraints copiable.

---

My Gradle version is `6.7.1`.

### PR DESCRIPTION
**Pull request by donat**
Fixes #17179

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test QuickFeedbackLinux

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

File: subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/dependencies/DefaultProjectDependencyConstraintTest.groovy [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+import org.gradle.initialization.ProjectAccessListener
+import org.gradle.util.AttributeTestUtil
+import org.gradle.util.TestUtil
+import spock.lang.Issue
+import spock.lang.Specification
+
+class DefaultProjectDependencyConstraintTest extends Specification {
+
+    @Issue("https://github.com/gradle/gradle/issues/17179")
+    def "can copy project dependency constraint"() {
```
Comment (ljacomet) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/dependencies/DefaultProjectDependencyConstraintTest.groovy:30]: Might be interesting to add a test showing this is a deep copy so that changing one does not change the other.

**Review by ljacomet — APPROVED** [review]
One potential improvement on the testing, see below.

Otherwise LGTM 👍

**Comment by donat** [comment]
@bot-gradle test and merge
