### PR TITLE
Fix incremental compilation for JDK8u301

### LINKED ISSUE #19353: Java compiler constant analysis seems to be broken on 8u301
After upgrading JDK from 8u291 to 8u301, some tests start failing: https://ge.gradle.org/s/upnw3rem6jm4i/tests/overview

There might be some internal change in JDK compiler.

Steps to reproduce:

- Install JDK 8u301.
- `./gradlew -PtestJavaVersion=8 -PtestJavaVendor=oracle :language-java:eIT --tests CrossTaskConstantChangesIncrementalJavaCompilationUsingJarIntegrationTest`

### PR DESCRIPTION
**Pull request by asodja**
Fixes #19353

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java [hunk 1]
```diff
@@ -84,4 +88,18 @@ public void beforeComplete() {
...
     }
+
+    /**
+     * Detects whether the file system has a reliable high precision timestamp.
+     *
+     * In case both timestamp are in millisecond precision,
+     * then the provided file system is definitely reliable, we don't have to discard file hashes, and we will correctly detect file changes.
+     */
+    private boolean isReliableTimestampPrecision(long timestamp) {
+        return isBaseTimestampHighPrecision && isHighTimestampPrecision(timestamp);
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java:99]:
```suggestion
        return isBaseTimestampHighPrecision || isHighTimestampPrecision(timestamp);
```

I thought it is enough that one of the two timestamps is high precision. Then the higher precision one would have detected the change, right?

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java [hunk 2]
```diff
@@ -51,17 +52,20 @@ public void attach(CachingFileHasher fileHasher) {
     public void afterStart() {
         updateOnStartBuild();
         currentTimestamp = currentTimestamp();
+        isBaseTimestampHighPrecision = isHighTimestampPrecision(currentTimestamp);
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java:55]:
```suggestion
        currentTimestampHighPrecision = isHighTimestampPrecision(currentTimestamp);
```

We use `currentTimestamp` as the variable name.

**Review by wolfs — COMMENTED** [review]
I left some comments. In general, I think this change makes the timestamp inspector more robust, given our different file timestamp sources.

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java (hunk 1 above)
Comment (asodja) [reply subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java]: Yes, you are right. If I understand correctly:
- if first is then also second is because we check both sources -> file system is reliable
- if first is not (due to coincidence of being created at exact second), but second is -> file system is reliable

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java [hunk 3]
```diff
@@ -84,4 +89,18 @@ public void beforeComplete() {
             }
         }
     }
+
+    /**
+     * Detects whether the file system has a reliable high precision timestamp.
+     *
+     * In case both timestamp are in millisecond precision,
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java:96]:
```suggestion
     * In case any of the two timestamps is in millisecond precision,
```

Can you also describe why we can detect changes if any of the two timestamps is in millisecond precision?

I think this is because if the currentTimestamp already has millisecond precision, then all file timestamps will have millisecond precision. And the passed in `timestamp` may accidentally fall on a full second.

File: subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java (hunk 1 above)
Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java]: Exactly!

Comment (wolfs) [reply subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java]: Another option is also that the second was read via some other source, like using native platform. So we may still get some low-precision timestamps.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test and merge
