### PR TITLE
Do not store snapshot if tasks changed locations in between

### LINKED ISSUE #20680: Wrong inputs detected when using large filtered file trees
We found this cache miss in our build: https://ge.gradle.org/c/b5vbvdyarkyag/eerzsgcnrt3cy/task-inputs?expanded=WyJsNDV0Z2c3YnNzczNzLWNsYXNzcGF0aCIsIjJ2MjNwaHNwdTduMmMtY2xhc3NwYXRoIl0

It seems like in the compile all build the `file-collections` jar is part of the inputs for `workers:compileJava`, while it isn't in the package build. Here, similarly to https://github.com/gradle/gradle/issues/20391 and https://github.com/gradle/gradle/pull/20366, fingerprinting the inputs of `:distributions-full:srcDistributionZip` starts before and finishes after `file-collections:jar`. When it finishes, it stores an incorrect input snapshot in the VFS which shows that the `file-collection/libs` directory is still empty. This is what is picked up by `workers:compileJava`, and the missing JAR file is ignored for classpath snapshotting. So the captured classpath snapshot is actually wrong.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by wolfs**
Fixes #20680.

### CODE REVIEW

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsWrittenByCurrentBuild.java [hunk 1]
```diff
@@ -17,14 +17,22 @@
...
 import java.util.concurrent.atomic.AtomicReference;
 
 public class LocationsWrittenByCurrentBuild implements FileSystemAccess.WriteListener {
     private final AtomicReference<FileHierarchySet> producedByCurrentBuild = new AtomicReference<>(FileHierarchySet.empty());
+    private final AtomicReference<VersionHierarchy> versionHierarchy;
+    private final AtomicLong currentVersion = new AtomicLong(0);
     private volatile boolean buildRunning;
 
+    public LocationsWrittenByCurrentBuild(CaseSensitivity caseSensitivity) {
+        this.versionHierarchy = new AtomicReference<>(VersionHierarchy.empty(currentVersion.incrementAndGet(), caseSensitivity));
```
Comment (lptr) [inline subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsWrittenByCurrentBuild.java:33]: To me it'd make sense if `VersionHierarchy.empty()` would initialize to `version = 0`, and we'd initialize `currentVersion` from `versionHierarchy.getVersion()`.

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsWrittenByCurrentBuild.java [hunk 2]
```diff
@@ -35,13 +43,26 @@ public void locationsWritten(Iterable<String> locations) {
                 }
                 return newValue;
             });
+            versionHierarchy.updateAndGet(currentValue -> {
+                VersionHierarchy newValue = currentValue;
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsWrittenByCurrentBuild.java]: This has been removed.

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/VersionHierarchy.java [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+package org.gradle.internal.watch.vfs.impl;
+
+import org.gradle.internal.snapshot.CaseSensitivity;
+import org.gradle.internal.snapshot.ChildMap;
+import org.gradle.internal.snapshot.EmptyChildMap;
+import org.gradle.internal.snapshot.VfsRelativePath;
+
+public class VersionHierarchy {
+    private final long version;
+    private final CaseSensitivity caseSensitivity;
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/VersionHierarchy.java]: I moved this to a new class which represents the root, so we don't store a reference in each node.

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsWrittenByCurrentBuild.java [hunk 4]
```diff
@@ -35,13 +43,26 @@ public void locationsWritten(Iterable<String> locations) {
...
+                long newVersion = currentVersion.incrementAndGet();
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsWrittenByCurrentBuild.java]: I made this simpler.

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsWrittenByCurrentBuild.java [hunk 5]
```diff
@@ -17,14 +17,22 @@
...
+import org.gradle.internal.snapshot.CaseSensitivity;
 import org.gradle.internal.vfs.FileSystemAccess;
 
+import java.util.concurrent.atomic.AtomicLong;
 import java.util.concurrent.atomic.AtomicReference;
 
 public class LocationsWrittenByCurrentBuild implements FileSystemAccess.WriteListener {
     private final AtomicReference<FileHierarchySet> producedByCurrentBuild = new AtomicReference<>(FileHierarchySet.empty());
+    private final AtomicReference<VersionHierarchy> versionHierarchy;
+    private final AtomicLong currentVersion = new AtomicLong(0);
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsWrittenByCurrentBuild.java]: Moved to a separate data structure.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/FileSystemAccess.java [hunk 6]
```diff
@@ -64,5 +64,7 @@ public interface FileSystemAccess {
 
     interface WriteListener {
         void locationsWritten(Iterable<String> locations);
+
+        long getVersionFor(String location);
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/FileSystemAccess.java]: I removed this method.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java [hunk 7]
```diff
@@ -157,13 +157,20 @@ private FileSystemLocationSnapshot snapshot(String location, SnapshottingFilter
...
                 AtomicBoolean hasBeenFiltered = new AtomicBoolean(false);
+                long versionBefore = writeListener.getVersionFor(location);
                 FileSystemLocationSnapshot directorySnapshot = directorySnapshotter.snapshot(
                     location,
                     filter.isEmpty() ? null : filter.getAsDirectoryWalkerPredicate(),
                     hasBeenFiltered,
-                    snapshot -> virtualFileSystem.store(snapshot.getAbsolutePath(), snapshot));
+                    snapshot -> {
+                        if (versionBefore == writeListener.getVersionFor(location)) {
+                            virtualFileSystem.store(snapshot.getAbsolutePath(), snapshot);
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java]: I moved the versioning logic to the virtual file system.

File: subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/VersionHierarchy.java [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+            }
+
+            @Override
+            public VersionHierarchy mergeWithExisting(VersionHierarchy child) {
+                return createChild();
+            }
+
+            @Override
+            public VersionHierarchy createChild() {
+                return new VersionHierarchy(EmptyChildMap.getInstance(), newVersion, caseSensitivity);
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/VersionHierarchy.java]: Done.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java [hunk 9]
```diff
@@ -157,13 +157,20 @@ private FileSystemLocationSnapshot snapshot(String location, SnapshottingFilter
...
+                        }
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java]: Yeah, I added some logging here.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java [hunk 10]
```diff
@@ -45,31 +49,58 @@ public Optional<MetadataSnapshot> findMetadata(String absolutePath) {
...
+        }
     }
 
     @Override
     public void invalidate(Iterable<String> locations) {
         LOGGER.debug("Invalidating VFS paths: {}", locations);
         rootReference.update(root -> {
             SnapshotHierarchy result = root;
+            VersionHierarchyRoot newVersionHierarchyRoot = versionHierarchyRoot;
+            long nextVersion = ++currentVersion;
```
Comment (wolfs) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java:81]: Instead of counting here, we also could use `System.nanoTime()` to add more meaning to the version we have in the VFS.

Comment (lptr) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java:81]: Absolute time has no meaning here, and `nanoTime()` actually makes no guarantees about nanosecond resolution (only precision).

> This method provides nanosecond precision, but not necessarily nanosecond resolution (that is, how frequently the value changes) - no guarantees are made except that the resolution is at least as good as that of currentTimeMillis().

A guaranteed monotonic counter is what we need, so an atomically accessed `long` is the right choice here.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java [hunk 11]
```diff
@@ -36,7 +38,13 @@ public interface VirtualFileSystem {
     /**
      * Adds the information of the snapshot at the absolute path to the VFS.
      */
-    void store(String absolutePath, FileSystemLocationSnapshot snapshot);
+    FileSystemLocationSnapshot store(String absolutePath, Supplier<FileSystemLocationSnapshot> snapshotSupplier);
+
+    FileSystemLocationSnapshot store(String baseLocation, StoringAction storingAction);
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java:43]: Let's explain how these methods now work in Javadoc.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java [hunk 12]
```diff
@@ -36,7 +38,13 @@ public interface VirtualFileSystem {
     /**
      * Adds the information of the snapshot at the absolute path to the VFS.
      */
-    void store(String absolutePath, FileSystemLocationSnapshot snapshot);
+    FileSystemLocationSnapshot store(String absolutePath, Supplier<FileSystemLocationSnapshot> snapshotSupplier);
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java:41]: If `store()` fails to actually store the snapshot, the caller now has no idea about that, right? Is this a problem?

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java [hunk 13]
```diff
@@ -106,19 +106,17 @@ public <T> Optional<T> readRegularFileContentHash(String location, Function<Hash
                 }
                 HashCode hash = producingSnapshots.guardByKey(location,
                     () -> virtualFileSystem.findSnapshot(location)
-                        .orElseGet(() -> {
+                        .orElseGet(() -> virtualFileSystem.store(location, () -> {
                             HashCode hashCode = hasher.hash(file, fileMetadata.getLength(), fileMetadata.getLastModified());
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java:110]: Shouldn't we be doing the call to `stat.stat()` in this lambda as well?

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java (hunk 10 above)
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java:81]: I still don't understand why we need a separate `long` to keep track of the version. The version in the root of `versionHierarchyRoot` will by definition always reflect the same number, no? Because when we update the version of any point in the hierarchy, we'll always also update its ancestry, too. Or am I missing something?

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java [hunk 14]
```diff
@@ -45,31 +49,58 @@ public Optional<MetadataSnapshot> findMetadata(String absolutePath) {
...
+            rootReference.update(root -> updateNotifyingListeners(diffListener -> root.store(absolutePath, snapshot, diffListener)));
+        } else {
+            LOGGER.debug("Changes to the virtual file system happened while snapshotting '{}', not storing resulting snapshot", absolutePath);
+        }
     }
 
     @Override
     public void invalidate(Iterable<String> locations) {
         LOGGER.debug("Invalidating VFS paths: {}", locations);
         rootReference.update(root -> {
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java:78]: This is somewhat misleading. Looking at this code I expected this to be calling `AtomicReference.update()` which requires a side-effect-free update function, as it gets re-executed as needed. What is happening here is more of an `updateUnderLock()`.

We could also just inline this type. We don't really need to pass this around, and instead `AbstractVirtualFileSystem` could create the instance in its constructor based on the `caseSensitivity`.

I think doing so would significantly reduce code complexity, and would allow us to remove this somewhat weird type altogether. It would even make the constructor of `AbstractVirtualFileSystem` more symmetric.

**Review by lptr — COMMENTED** [review]
We don't currently repeat snapshotting if `store()` fails, but that could be the idea going down the road. And I don't completely see how we'd adopt to that.

I'd like to see from the current code structure what would be re-executed if we had to repeat the snapshotting, even if we don't make use of this.

**Comment by wolfs** [comment]
> We don't currently repeat snapshotting if store() fails, but that could be the idea going down the road. And I don't completely see how we'd adopt to that.
>
> I'd like to see from the current code structure what would be re-executed if we had to repeat the snapshotting, even if we don't make use of this.

From the current code structure, you'd need to while loop around the parts where we do the snapshotting. I don't see any problems with that. For the version using the `StoringAction`, you'd need to capture whether any of the stores didn't happen, and if that is the case you'd repeat calling `storingAction.snapshot()`. Am I missing something?

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java (hunk 12 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java:41]: I don't think this is a problem. The VFS is a cache after all, so if something doesn't make it into the cache the caller shouldn't care, right?

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java (hunk 10 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java]: I removed that and only keep the version in the root.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java (hunk 11 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java:53]: Done.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java (hunk 13 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java:110]: Yes, it would be better so the whole store action is repeatable. Let's do this in a separate PR though.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java (hunk 14 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java]: I think it makes sense to inline the lock and to guard the whole state of the VFS with this one lock. That is what we have been doing anyway with this method. Let's do that in a follow up PR.

**Comment by wolfs** [comment]
@lptr I created https://github.com/gradle/gradle/issues/20702 to track the follow up work.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java [hunk 15]
```diff
@@ -45,31 +48,57 @@ public Optional<MetadataSnapshot> findMetadata(String absolutePath) {
...
     public void invalidate(Iterable<String> locations) {
         LOGGER.debug("Invalidating VFS paths: {}", locations);
-        rootReference.update(root -> {
+        rootReference.updateUnderLock(root -> {
             SnapshotHierarchy result = root;
+            VersionHierarchyRoot newVersionHierarchyRoot = versionHierarchyRoot;
             for (String location : locations) {
                 SnapshotHierarchy currentRoot = result;
                 result = updateNotifyingListeners(diffListener -> currentRoot.invalidate(location, diffListener));
+                newVersionHierarchyRoot = newVersionHierarchyRoot.increaseVersion(location);
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java:84]: I still don't like the name `increaseVersion()` here. We are making the location be the latest there is in the tree, not increasing its current version. I think a name like `touch()` or even `updateVersion()` would be better.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java [hunk 16]
```diff
@@ -45,31 +48,57 @@ public Optional<MetadataSnapshot> findMetadata(String absolutePath) {
...
+        return snapshot;
+    }
+
+    @Override
+    public FileSystemLocationSnapshot store(String baseLocation, StoringAction storingAction) {
+        long versionBefore = versionHierarchyRoot.getVersionFor(baseLocation);
+        return storingAction.snapshot(snapshot -> updateCheckingVersion(snapshot.getAbsolutePath(), versionBefore, snapshot));
+    }
+
+    private void updateCheckingVersion(String absolutePath, long versionBefore, FileSystemLocationSnapshot snapshot) {
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java]: I am using `storeIfUnchanged` now.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java (hunk 15 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java]: I am using `touch()` if there isn't a version specified and `updateVersion()` if there is.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java [hunk 17]
```diff
@@ -45,31 +48,57 @@ public Optional<MetadataSnapshot> findMetadata(String absolutePath) {
...
-            return root.empty();
-        }));
+        rootReference.updateUnderLock(root -> {
+            versionHierarchyRoot = versionHierarchyRoot.increaseVersionInRoot();
+            return updateNotifyingListeners(diffListener -> {
+                root.rootSnapshots()
+                    .forEach(diffListener::nodeRemoved);
+                return root.empty();
+            });
+        });
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java]: I replaced `invalidateAll()` by `invalidate([ROOT])`.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchy.java [hunk 18]
```diff
@@ -0,0 +1,97 @@
...
+    public static VersionHierarchy empty(long rootVersion) {
+        return new VersionHierarchy(EmptyChildMap.getInstance(), rootVersion);
+    }
+
+    private VersionHierarchy(ChildMap<VersionHierarchy> children, long version) {
+        this.children = children;
+        this.version = version;
+    }
+
+   public long getVersionFor(VfsRelativePath relativePath, CaseSensitivity caseSensitivity) {
```
[the remark this answers is not in the document]
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchy.java]: I am using now `getVersion()`.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchyRoot.java [hunk 19]
```diff
@@ -34,28 +34,20 @@ private VersionHierarchyRoot(VersionHierarchy rootNode, CaseSensitivity caseSens
...
 
     @CheckReturnValue
-    public VersionHierarchyRoot increaseVersion(String path) {
+    public VersionHierarchyRoot touch(String path) {
         long newVersion = rootNode.getVersion() + 1;
         VfsRelativePath relativePath = VfsRelativePath.of(path);
         VersionHierarchy newRootNode = relativePath.isEmpty()
             ? VersionHierarchy.empty(newVersion)
-            : rootNode.increaseVersion(relativePath, newVersion, caseSensitivity);
+            : rootNode.updateVersion(relativePath, newVersion, caseSensitivity);
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchyRoot.java:50]: Is there a reason to call the two methods differently, i.e. `touch()` vs `updateVersion()`?

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy [hunk 20]
```diff
@@ -186,15 +182,15 @@ class DirectorySnapshotterTest extends Specification {
...
+        def snapshot = directorySnapshotter.snapshot(rootDir.absolutePath, null, unfilteredSubSnapshotsCollector) as DirectorySnapshot
         def relativePaths = SnapshotVisitorUtil.getRelativePaths(snapshot)
         then:
         relativePaths == ["some", "some/sub", "some/sub/dir", "some/sub/dir/other", "some/sub/dir/other/text.txt"]
         SnapshotVisitorUtil.getAbsolutePaths(snapshot) == relativePaths.collect { new File(rootDir, it).absolutePath }
         def symlinkedDir = snapshot.children[0].children[0].children[0] as DirectorySnapshot
         symlinkedDir.accessType == AccessType.VIA_SYMLINK
         symlinkedDir.absolutePath == symlink.absolutePath
-        unfilteredSubsnapshots.empty
+        unfilteredSubsnapshots == [snapshot]
```
Comment (lptr) [inline subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy:193]: This seems more correct now.

**Review by lptr — APPROVED** [review]
LGTM, left one small comment.

File: subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchyRoot.java (hunk 19 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchyRoot.java:50]: I named them differently because one takes an actual version as a parameter and updates the version to conform with it, while the other one is about marking that something has been changed at the location. I don't feel very strongly about this, so I'll rename `touch` to `updateVersion`.
