### PR TITLE
Do not restart unnamed property counter

### LINKED ISSUE #4085: Upgrade to 4.5-RC1 failed due to "Multiple input file properties with name '$1'"
I tried to upgrade Gradle from 4.3 to 4.5-RC1, I got below error when I run below command.
seems this error related to https://github.com/gradle/gradle/pull/3720, how can I fix the issue and upgrade to 4.5-RC1 successfully?

@wolfs 

**Command**
./gradlew -S :proto-converter:generateProto

**Result**

```
The :proto-converter:generateProto task failed.
Multiple input file properties with name '$1'
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':proto-converter:generateProto'.Open stacktrace
Caused by: java.lang.IllegalArgumentException: Multiple input file properties with name '$1'Close stacktrace
at org.gradle.api.internal.tasks.properties.GetInputFilesVisitor.visitInputFileProperty(GetInputFilesVisitor.java:44)
at org.gradle.api.internal.tasks.properties.CompositePropertyVisitor.visitInputFileProperty(CompositePropertyVisitor.java:35)
at org.gradle.api.internal.tasks.DefaultTaskInputs.visitRegisteredProperties(DefaultTaskInputs.java:76)
at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:39)
at org.gradle.api.internal.tasks.execution.DefaultTaskProperties.resolve(DefaultTaskProperties.java:77)
at org.gradle.execution.taskgraph.TaskInfo.getTaskProperties(TaskInfo.java:229)
at org.gradle.execution.taskgraph.TaskInfo.getDestroyables(TaskInfo.java:220)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getDestroyablePaths(DefaultTaskExecutionPlan.java:794)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.canRunWithCurrentlyExecutedTasks(DefaultTaskExecutionPlan.java:663)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.access$2600(DefaultTaskExecutionPlan.java:89)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$9.transform(DefaultTaskExecutionPlan.java:593)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$9.transform(DefaultTaskExecutionPlan.java:588)
at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.selectNextTask(DefaultTaskExecutionPlan.java:588)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.access$2300(DefaultTaskExecutionPlan.java:89)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$8.transform(DefaultTaskExecutionPlan.java:562)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$8.transform(DefaultTaskExecutionPlan.java:543)
at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:543)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by lptr**
When unnamed properties are assigned a name like  etc., we now keep track
of the last number assigned, and if more unnamed properties are registered,
we don't restart counting from , resulting in property name collisions.

Fixes #4085.

### CODE REVIEW

**Comment by lptr** [comment]
Build: https://builds.gradle.org/viewQueued.html?itemId=10468062

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetInputFilesVisitor.java [hunk 1]
```diff
@@ -17,79 +17,36 @@
...
-    private ImmutableSortedSet.Builder<TaskInputFilePropertySpec> builder = ImmutableSortedSet.naturalOrder();
-    private Set<String> names = Sets.newHashSet();
+    private final List<TaskInputFilePropertySpec> specs = Lists.newArrayList();
     private boolean hasSourceFiles;
 
     private ImmutableSortedSet<TaskInputFilePropertySpec> fileProperties;
 
-    public GetInputFilesVisitor(String beanName) {
-        this.beanName = beanName;
+    public GetInputFilesVisitor() {
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetInputFilesVisitor.java]: This empty constructor can now be removed.
