### PR TITLE
Instrument directories into directories

### LINKED ISSUE #26650: Large amount of open files after configuration phase of large build (>5000 projects)
### Current Behavior

In a monorepo with > 5000 projects, we are seeing a large number of files left open after the configuration phase (typically after an IDE sync). Mainly we see `cp_proj.jar` and `proj.jar` files left open. This has become problematic for us, as many of the devlopers who work on this project are on MacOS, and seem to be hitting the same issue reported here: https://github.com/gradle/gradle/issues/26115.

I used the file leak detector to capture all the open file descriptors after an IDE sync, and found ~9.4k `proj.jar` and ~9.5k `cp_proj.jar` files left open. Below are the stack traces that is common for the majority of each of these files.

Top 2 stack traces for `cp_proj.jar`
```
#20643 /Users/pablobaxter/.gradle/caches/jars-9/1fb912b78ac4bad43be00f9f4156c4df/cp_proj.jar by thread:Daemon worker on Tue Oct 03 08:27:01 PDT 2023
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1312)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:841)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:785)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:778)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:777)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:747)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:502)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:485)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:484)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:452)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:321)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:424)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ScriptClassLoader.loadClass(DefaultScriptCompilationHandler.java:384)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ClassesDirCompiledScript.loadClass(DefaultScriptCompilationHandler.java:335)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.getScript(DefaultScriptRunnerFactory.java:55)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:86)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:111)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
```

```
#11948 /Users/pablobaxter/.gradle/caches/jars-9/9d6ca55066e0de258e10da287d04d3a2/cp_proj.jar by thread:Daemon worker on Tue Oct 03 08:26:09 PDT 2023
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:173)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:841)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:785)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:778)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:777)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:747)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:502)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:485)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:484)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:452)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:321)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:424)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ScriptClassLoader.loadClass(DefaultScriptCompilationHandler.java:384)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ClassesDirCompiledScript.loadClass(DefaultScriptCompilationHandler.java:335)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.getScript(DefaultScriptRunnerFactory.java:55)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:86)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:111)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
```

Top 2 stack traces for `proj.jar`
```
#17901 /Users/pablobaxter/.gradle/caches/jars-9/f03c7d2e54128011619f95c0c83aec4a/proj.jar by thread:Daemon worker on Tue Oct 03 08:26:44 PDT 2023
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1312)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:841)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:785)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:778)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:777)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:747)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:502)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:485)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:484)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:452)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:321)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:424)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ScriptClassLoader.loadClass(DefaultScriptCompilationHandler.java:384)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ClassesDirCompiledScript.loadClass(DefaultScriptCompilationHandler.java:335)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.getScript(DefaultScriptRunnerFactory.java:55)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:86)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:135)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:79)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:138)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
```

```
#4157 /Users/pablobaxter/.gradle/caches/jars-9/61df8b13771b6445fc7e4906368507cc/proj.jar by thread:Daemon worker on Tue Oct 03 08:24:57 PDT 2023
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:173)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:841)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:785)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:778)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:777)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:747)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:502)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:485)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:484)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:452)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:321)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:424)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ScriptClassLoader.loadClass(DefaultScriptCompilationHandler.java:384)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ClassesDirCompiledScript.loadClass(DefaultScriptCompilationHandler.java:335)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.getScript(DefaultScriptRunnerFactory.java:55)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:86)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:135)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:79)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:138)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
```

### Expected Behavior

File descriptors should be eagerly closed as soon as they are no longer needed. I'm unsure why all these files are required to stay open. If it's for performance, maybe having a flag or method to close them based on a trigger would be something we can work with, as this is causing issues with developers unable to build and/or sync their projects on MacOS.

### Context (optional)

_No response_

### Steps to Reproduce

Attempt to run a task on a very large (>5k project) build.

### Gradle version

8.3

### Build scan URL (optional)

_No response_

### Your Environment (optional)

OS: MacOS 14.0
RAM: 64GB
CPU: Apple M1 Max

### PR DESCRIPTION
**Pull request by mlopatkin**
Fixes #26650.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle help

**Comment by mlopatkin** [comment]
@bot-gradle test QFL without PTS

**Comment by mlopatkin** [comment]
@bot-gradle clean

**Comment by mlopatkin** [comment]
@bot-gradle test PRF without PTS

File: subprojects/core/src/main/java/org/gradle/internal/scripts/BuildScriptCompilationAndInstrumentation.java [hunk 1]
```diff
@@ -96,7 +96,7 @@ public WorkOutput execute(ExecutionRequest executionRequest) {
         File compileOutput = compile(workspace);
         // We should instrument output of classes directory to the classes directory instead of a jar,
         // but currently instrumentation classloader doesn't support that yet.
```
Comment (mlopatkin) [inline subprojects/core/src/main/java/org/gradle/internal/scripts/BuildScriptCompilationAndInstrumentation.java:98]: :x: this comment is now outdated.

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by mlopatkin** [comment]
@bot-gradle test RFN

File: subprojects/core/src/integTest/groovy/org/gradle/internal/classpath/BuildScriptClasspathIntegrationSpec.groovy [hunk 2]
```diff
@@ -242,21 +242,21 @@ class BuildScriptClasspathIntegrationSpec extends AbstractIntegrationSpec implem
         succeeds("showBuildscript")
 
         then:
-        def jar = inJarCache("proj.jar").assertExists()
+        def buildscriptClasses = inJarCache("proj/").assertExists()
```
Comment (asodja) [inline subprojects/core/src/integTest/groovy/org/gradle/internal/classpath/BuildScriptClasspathIntegrationSpec.groovy:245]: 💅 Should we rename also test to "cleans up unused cached **entries** in the Jars cache"?

File: subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java [hunk 3]
```diff
@@ -76,6 +76,12 @@ private static ClasspathFileHasher createFileHasherWithConfig(HashCode configHas
             Hasher hasher = Hashing.newHasher();
             hasher.putHash(configHash);
             hasher.putHash(fileHasher.hashOf(sourceSnapshot));
+            if (sourceSnapshot.getType() == FileType.Directory) {
+                // Prior to 8.7 we were combining instrumented classes from both directories and JARs into JARs.
+                // Now we store instrumented directories as directories, so we invalidate these.
+                // However, transformed JARs should be left intact.
+                hasher.putBoolean(true);
```
Comment (asodja) [inline subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java:83]: 💅  Since we now use artifact transforms/execution engine for most of instrumentation, where caching is bound to Gradle version, I wonder if we can simplify this to just `hasher.putBoolean(sourceSnapshot.getType() == FileType.Directory);`  without any `if`

Comment (asodja) [reply subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java:83]: You can also leave that.

But that is a good reminder that I should do the cleanup soon of this custom instrumentation.

**Review by asodja — APPROVED** [review]
LGTM

File: platforms/core-runtime/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java [hunk 4]
```diff
@@ -227,6 +231,37 @@ private static boolean isTransformed(JarFile jarFile) throws IOException {
...
+        private final File transformedPath;
+
+        public DirectoryLoader(File transformedDirPath) {
+            this.transformedPath = transformedDirPath;
+        }
+
+        @Nullable
+        @Override
+        public byte[] loadTransformedClass(String className) throws IOException {
+            File classFile = new File(transformedPath, classNameToPath(className));
```
[the remark this answers is not in the document]
Comment (mlopatkin) [reply platforms/core-runtime/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java:244]: > ❔ Do we need to handle anything for multi-release jars or that is not needed for directories?

No, directories cannot serve multi-release content.
