### PR TITLE
Fix issue with file hash cache during runtime classpath normalization

### LINKED ISSUE #16144: Build cache miss when jars have been hashed with different normalization configuration
We've received multiple reports of cache misses on runtime normalization input properties for jar files that should be identical.  At least one reporter confirmed that using a different gradle user home resolved the issue.  It turns out some of the changes to runtime classpath normalization in 6.8 don't accurately capture changes to the normalization configuration, which can lead to a sequence of events like the following:

1. CI server runs a build that hashes a 3rd party library in a project without properties file normalization rules.  The hash of this file is cached in the resources cache.
2. Another build runs that does have properties file normalization rules, but when the hasher gets to the library, it does not properly capture the rules when calculating the key for the resources cache and calculates the _same_ key as the build without normalization rules.  Rather than hashing the file again, it gets a hit on the resources cache and incorporates this hash into the task's build cache key.
3. A build on another system that does not have the library's hash in the resources cache runs the build with the properties file normalization rules, gets a miss for that file in the resources cache, and does the fully normalized hash of the library.  The resulting hash is different which results in a different cache key for the task, causing a build cache miss.

### Expected Behavior
We should get.a build cache hit on the task.

### Current Behavior
The build cache key can be incorrectly calculated on one side or the other, causing a miss.

### Context
Poorer build perfomance due to cache misses.

### Steps to Reproduce 
See above.

### PR DESCRIPTION
**Pull request by ghale**
Normalization rules were not being properly captured when calculating the cache key for file hashes during runtime classpath normalization.  This was causing incorrect build cache misses under the right sequence of events.

Fixes #16144

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test RfM please

**Comment by ghale** [comment]
@bot-gradle test RfM please

**Comment by ghale** [comment]
@bot-gradle test RfM please

**Comment by ghale** [comment]
@bot-gradle test RfM please

**Comment by ghale** [comment]
@bot-gradle test RfM please

File: subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy [hunk 1]
```diff
@@ -80,6 +85,7 @@ class ConfigureRuntimeClasspathNormalizationIntegrationTest extends AbstractInte
         'nested in dir jars' | 'ignoredResourceInNestedInDirJar' | 'notIgnoredResourceInNestedInDirJar' | Api.ANNOTATION
     }
 
+    @ToBeFixedForConfigurationCache(because = "classpath normalization")
```
Comment (ghale) [inline subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy:88]: This always should have been failing with config cache because we use classpath normalization in the test.  But there was an issue with how we were formatting the manifest which was causing it to pass incorrectly in that case.  Fixing the manifest caused the test to fail (as it should) so we need the annotation here.

File: subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy [hunk 2]
```diff
@@ -466,16 +472,56 @@ class ConfigureRuntimeClasspathNormalizationIntegrationTest extends AbstractInte
...
+    @Issue('https://github.com/gradle/gradle/issues/16144')
+    def "changing normalization configuration rules changes build cache key (#description)"() {
+        def project = new ProjectWithRuntimeClasspathNormalization(Api.RUNTIME)
+        project.propertiesFileInJar.changeProperty(ALSO_IGNORE_ME, 'some value')
+        project.buildFile << """
+            normalization {
+                runtimeClasspath {
+                    if (project.hasProperty('${enableFilterFlag}')) {
```
Comment (ghale) [inline subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy:483]: We implement it this way, rather than just changing the build script, because we don't want the change in build script to affect the cache hit.  We want the _only_ change to be in the normalization rules so we can be sure that's what's changing the cache key.

File: subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy (hunk 1 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy:88]: Can we point those tests to https://github.com/gradle/gradle/issues/13706, so it is clear there is an issue on the configuration cache side?

File: subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy [hunk 3]
```diff
@@ -235,8 +241,8 @@ class ConfigureRuntimeClasspathNormalizationIntegrationTest extends AbstractInte
         change                      | config                                                    | api
         'ignore file'               | "ignore '**/some-other-file.txt'"                         | Api.RUNTIME
         'ignore file'               | "ignore '**/some-other-file.txt'"                         | Api.ANNOTATION
-        'ignore manifest attribute' | "metaInf { ignoreAttribute 'Implementation-version' }"    | Api.RUNTIME
-        'ignore manifest attribute' | "metaInf { ignoreAttribute 'Implementation-version' }"    | Api.ANNOTATION
+        'ignore manifest attribute' | "metaInf { ignoreAttribute '${IMPLEMENTATION_VERSION}' }"    | Api.RUNTIME
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy:244]: Are the `|` now not aligned any more?

File: subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy (hunk 2 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy:483]: I think that comment belongs to the test code.

**Review by wolfs — COMMENTED** [review]
I think the change looks good. Does the new test fail without the fix of the production code? Can we do something to make sure we don't run into the same problem again?

File: subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy (hunk 1 above)
Comment (ghale) [reply subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy]: Yep - done.

File: subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy (hunk 2 above)
Comment (ghale) [reply subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy:486]: Good point.  Done.

**Comment by ghale** [comment]
@wolfs Yes, this test fails without the fix.  It should, at the least, guard against regressions for the normalization settings we test against.  I'm not 100% convinced it's the _best_ way to test for this problem, but I couldn't figure out a better way to test for it.

**Comment by ghale** [comment]
@bot-gradle test RfM please

**Comment by ghale** [comment]
@bot-gradle test RfM please

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by Sinapse87** [comment]
We encountered this issue, thanks a lot for fixing. Can't wait to test it

**Comment by wolfs** [comment]
@Sinapse87 Please try out `6.8.3-20210219125813+0000`, which is a nightly for the upcoming 6.8.3 release, which contains a fix for the issue.
