### PR TITLE
Fix some VFS retention tests to run with instant execution

### LINKED ISSUE #11835: Investigate why changes are not reported when both VFS retention and Instant Execution is enabled
---
cc: @gradle/build-cache

### PR DESCRIPTION
**Pull request by wolfs**
And comment why the remaining ones don't work, yet.
See gradle/instant-execution#165 and #11689 

Fixes #11835.

----
cc @gradle/build-cache

### CODE REVIEW

File: subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/VirtualFileSystemRetentionIntegrationTest.groovy [hunk 1]
```diff
@@ -165,6 +191,7 @@ class VirtualFileSystemRetentionIntegrationTest extends AbstractIntegrationSpec
         executedAndNotSkipped ":compileJava", ":classes", ":run"
     }
 
+    // The `run` task is not yet supported for instant execution.
     @ToBeFixedForInstantExecution
```
Comment (lptr) [inline subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/VirtualFileSystemRetentionIntegrationTest.groovy]: Should we add a `because` parameter to the annotation?

Comment (wolfs) [reply subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/VirtualFileSystemRetentionIntegrationTest.groovy]: Good idea, added.

**Comment by wolfs** [comment]
@lptr PTAL!
