### PR TITLE
Stop test filters from hiding suite failures

### LINKED ISSUE #12073: Test filters hide underlying issues during test task execution
When specifying test filters using the `--test` option and the test task fails before test execution, the error message always says that no tests where found matching the expected filters. A good example is using JUnit platform for testing but failing to provide a JUnit engine implementation, see e.g. this example project: https://github.com/marcphilipp/gradle-sandbox/tree/master/12073-test-task-failure

### Expected Behavior

No matter whether I run the build with or without filters, it should always report what's going on.

### Current Behavior

Running the build with `./gradlew test --tests "LibraryTest"` results in a build failure with message:

```
> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes: [LibraryTest](--tests filter)
```

Running `./gradlew test` results in a failed test task with a test report containing the following stacktrace:

```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 3.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.junit.platform.commons.PreconditionViolationException: Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:296)
	at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:58)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:91)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:67)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:97)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 25 more
```

### PR DESCRIPTION
**Pull request by marcphilipp**
Prior to this commit, failures on the test suite level, e.g. a failing
worker or a failure on the JUnit Platform engine level, was hidden when
a test filter (e.g. using `--tests`) was active and no test method was
actually executed. The root cause was only visible in the HTML test
report while the task failed with "No tests found". Now, the task fails
with "there were failing tests" and points to the report.

Resolves #12073.

### CODE REVIEW

**Comment by marcphilipp** [comment]
@bot-gradle test this

File: subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy [hunk 1]
```diff
@@ -413,38 +413,38 @@ public class StaticInnerTest {
...
 
         expect:
-        fails('test')
+        fails('test', *extraArgs)
         failureCauseContains('There were failing tests.')
+
+        where:
+        scenario       | extraArgs
+        "w/o filters"  | []
+        "with filters" | ['--tests', 'JUnitJupiterTest']
```
Comment (britter) [inline subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy:448]: ⭕️ Shouldn't this also check whether `oops` is reported on the console output?

File: subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy [hunk 2]
```diff
@@ -413,38 +413,38 @@ public class StaticInnerTest {
         }
     }
 
-    @Issue("https://github.com/junit-team/junit5/issues/2028")
-    def 'properly fails when engine fails during discovery'() {
+    @Unroll
+    @Issue("https://github.com/junit-team/junit5/issues/2028 and https://github.com/junit-team/junit5/issues/12073")
```
Comment (britter) [inline subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy:417]:
```suggestion
    @Issue("https://github.com/junit-team/junit5/issues/2028, https://github.com/junit-team/junit5/issues/12073, adn https://github.com/gradle/gradle/issues/12073")
```

Comment (britter) [inline subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy:417]:
```suggestion
    @Issue("https://github.com/junit-team/junit5/issues/2028 and https://github.com/gradle/gradle/issues/12073")
```

**Comment by blindpirate** [comment]
@marcphilipp You probably need to rebase latest master to make performance test pass.

File: subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy (hunk 1 above)
Comment (marcphilipp) [reply subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy:448]: Ideally, yes. However, that's not how Gradle currently reports suite-level failures, even without active test filters. Thus, I did not change that.

File: subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy (hunk 2 above)
Comment (marcphilipp) [reply subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy:417]: 🤦

**Comment by marcphilipp** [comment]
@bot-gradle test this

File: subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy (hunk 1 above)
Comment (britter) [reply subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy:448]: Okay!

**Comment by learnerEvermore** [comment]
From: noreply@digitalproductdelivery.com
Sent: August 23, 2020 11:05 p.m.
To: asusnjar@hotmail.com
Reply to: support@flightsimsoft.com
Subject: [DPD] Product Keys

Below are your requested product keys for your purchases from FlightSimSoft.com.


  PFPX -Download Edition (PFPX + TOPCAT Bundle): YYMAD-64375-N69UQ
  TOPCAT - Download Edition (PFPX + TOPCAT Bundle): Z2SN8-AG4HT-ZY42U
  PFPX - Server Subscription (365 days): NPMHJ-WYF43
  PFPX - Server Subscription (365 days): Z2XL2-SLTMD
  PFPX - Server Subscription (365 days): XHFS5-KLJU5

If you have any trouble with your product keys or need further support, please
contact us at support@flightsimsoft.com.

Thanks,

FlightSimSoft.com
