### PR TITLE
Make TransformingClassLoader thread-safe

### LINKED ISSUE #36824: TransformedClassLoader is not thread-safe
### Current Behavior

`org.gradle.internal.classloader.TransformingClassLoader` is not thread-safe, because of TOCTOU:
https://github.com/gradle/gradle/blob/6afc9edc8051aa9ae820c1f80076b46ba2808bc8/platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java#L79-L83

If two callsites find the package being absent, they both proceed to define, and the last one will get `IllegalArgumentException`.

### Expected Behavior

`TransformingClassLoader` should be thread-safe, because it is registered as parallel capable.

### Context (optional)

With parallel CC load, some less-used Gradle classes can be loaded concurrently.

### Self-contained Reproducer Project

N/A, reported internally

### Gradle version

8.14

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by mlopatkin**
Fixes #36824

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this without PTS

File: platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java [hunk 1]
```diff
@@ -76,14 +76,29 @@ protected Class<?> findClass(String name) throws ClassNotFoundException {
...
+                // Another thread has beaten us while trying to register this package.
+                // All do it with the same parameters so we can just keep going.
+                // Let's still check that the package is there, just in case.
+                if (getPackage(packageName) == null) {
+                    // This should never happen.
+                    throw new AssertionError("Package '" + packageName + "' cannot be defined but is not registered either in " + this, iae);
+                }
+            }
         }
         return defineClass(name, bytes, 0, bytes.length, codeSource);
```
Comment (big-guy) [inline platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java:93]: Is there a similar danger for defineClass too?

Either defineClass blowing up because you create the same class twice or two threads defining the same class with different instances?

Comment (big-guy) [reply platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java:93]: And could you try to trigger this in some kind of ConcurrentSpec test?

File: platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java [hunk 2]
```diff
@@ -76,14 +76,29 @@ protected Class<?> findClass(String name) throws ClassNotFoundException {
         }
 
         String packageName = StringUtils.substringBeforeLast(name, ".");
-        @SuppressWarnings("deprecation")
         Package p = getPackage(packageName);
         if (p == null) {
-            definePackage(packageName, null, null, null, null, null, null, null);
+            try {
+                definePackage(packageName, null, null, null, null, null, null, null);
+            } catch (IllegalArgumentException iae) {
```
Comment (smplio) [inline platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java:83]: Wouldn't it be computationaly cheaper to use synchronized block here, then relying on rewinding the stack to capture stacktrace?

File: platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java (hunk 1 above)
Comment (mlopatkin) [reply platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java:93]: > Is there a similar danger for defineClass too?

No, that one is protected by a [class-level lock in the caller](https://github.com/openjdk/jdk17u/blob/e47690176cade6a6f8cf97059cfe914f5f67cd87/src/java.base/share/classes/java/lang/ClassLoader.java#L572), even for parallel classloaders.

File: platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java (hunk 2 above)
Comment (mlopatkin) [reply platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java:83]: > Wouldn't it be computationaly cheaper to use synchronized block here, then relying on rewinding the stack to capture stacktrace?

That's a good question, but it the lack of reports suggests that the contention here is relatively uncommon. As a data point, JDK does the same try-catch for its URLClassLoader.

File: platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java (hunk 1 above)
Comment (mlopatkin) [reply platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java:93]: > And could you try to trigger this in some kind of ConcurrentSpec test?

I'm not a big fan of non-deterministic tests, but this one seems to be pretty reliable.

File: platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java [hunk 3]
```diff
@@ -76,14 +76,29 @@ protected Class<?> findClass(String name) throws ClassNotFoundException {
...
+                    // This should never happen.
+                    throw new AssertionError("Package '" + packageName + "' cannot be defined but is not registered either in " + this, iae);
+                }
+            }
         }
         return defineClass(name, bytes, 0, bytes.length, codeSource);
     }
 
+    @Override
+    @SuppressWarnings("deprecation") // We still need to support Java 8 where non-deprecated version is not available.
```
Comment (Toffikk) [inline platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java:97]: im not sure if im understanding this comment correctly but why do we care about Java 8, if gradle is now 17+

Comment (mlopatkin) [reply platforms/core-runtime/classloaders/src/main/java/org/gradle/internal/classloader/TransformingClassLoader.java:97]: > im not sure if im understanding this comment correctly but why do we care about Java 8, if gradle is now 17+

Gradle still needs to run some of its code in Java 8+ processes, in particular, in compilation or test workers. For example, when you use toolchains to run your tests on Java 8 vm, there is a separate process spawned, but it contains some bits of Gradle runtime used to communicate test results back to the Gradle daemon.
