### PR TITLE
Fix bug when matching locations for missing task dependencies

### LINKED ISSUE #16061: Bug in task dependency validation
Given the following build script:

```
plugins {
    base
}

tasks {
    val prepareBuild by registering {
        outputs.file("app/foo.txt")
        doLast {}
    }

    val sources = fileTree("app") {
        include("**/*.txt")
        exclude("**/*generated*")
        builtBy(prepareBuild)
    }

    val generateA by registering {
        inputs.files(sources)
        outputs.file("app/src/generatedA.txt")
        doLast {}
    }

    val generateB by registering {
        inputs.files(sources)
        outputs.file("app/src/generatedB.txt")
        doLast {}
    }

    assemble {
        dependsOn(generateA, generateB)
    }
}
```

When I run `gradle assemble`, I get warned that `generateB` uses the output of `generateA`. This is not true though, because of the exclude in the file tree. Interestingly, this only happens when there is the `prepare` task that also writes something to that file tree. 

Use case: A Javascript code base where lots of tasks collaborate to create one `src` folder. Separate output folders for each tool are planned, but I still think the above is a bug and should be fixed.

### PR DESCRIPTION
**Pull request by wolfs**
This caused the wrong path to be matched which caused arbitrary results.

Fixes #16061

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test QFL

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy [hunk 1]
```diff
@@ -282,6 +283,43 @@ class MissingTaskDependenciesIntegrationTest extends AbstractIntegrationSpec {
...
+                doLast {}
+            }
+
+            def sources = fileTree("app") {
+                include("**/*.txt")
+                exclude("**/*generated*")
+                builtBy(prepareBuild)
+            }
+
+            task generateA {
```
Comment (melix) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy:300]: Just a comment on the readability of the test. It would have helped if instead of `generateA`, the task would have been called `consumesResultOfPrepareBuildAndGeneratesAInSameDirectory` or something like that.

**Review by melix — APPROVED** [review]
