### PR TITLE
Let Kotlin DSL precompiled script plugin support not use compileKotlin.doFirst to configure the Kotlin compiler

### LINKED ISSUE #22091: Kotlin-dsl plugin modifies kotlinOptions.freeCompilerArgs in task action
### Expected Behavior

Gradle `kotlin-dsl` plugin should not modify `kotlinOptions.freeCompilerArgs` in task action (Gradle execution phase)

### Current Behavior

In Gradle 7.3 - 7.5.1 versions `freeCompilerArgs` could be modified in `doFirst` `KotlinCompile` task action inside `buildSrc` project by 'kotlin-dsl' plugin.

### Context

Kotlin Gradle Plugin [was migrated](https://youtrack.jetbrains.com/issue/KT-27301/Expose-compiler-flags-via-Gradle-lazy-properties) to use Gradle Properties API and had to add workaround allowing to modify `kotlinOptions.freeCompilerArgs` on execution phase. Otherwise Gradle build fails with `java.lang.IllegalStateException: The value for property 'freeCompilerArgs' is final and cannot be changed any further.`

### Steps to Reproduce 

Create new project with `buildSrc` module. Inside `buildSrc/build.gradle.kts` add following:
```kt
plugins {
   id("org.jetbrains.kotlin.jvm") version "1.8.0-Beta"
   `kotlin-dsl`
}
```
and add any simple convention plugin written in Kotlin. Build will produce a warning from workaround:
```
kotlinOptions.freeCompilerArgs were changed on task execution phase: -java-parameters, -Xjvm-default=all, -Xjsr305=strict, -XXLanguage:+DisableCompatibilityModeForNewInference, -script-templates, org.gradle.kotlin.dsl.precompile.v1.PrecompiledSettingsScript,org.gradle.kotlin.dsl.precompile.v1.PrecompiledInitScript,org.gradle.kotlin.dsl.precompile.v1.PrecompiledProjectScript, -Xscript-resolver-environment=kotlinDslImplicitImports="org.gradle.BuildAdapter:org.gradle.BuildListener:org.gradle.BuildResult:org.gradle.StartParameter:org.gradle.TaskExecutionRequest:org.gradle.api.Action:org.gradle.api.ActionConfiguration:org.gradle.api.AntBuilder:org.gradle.api.BuildCancelledException:org.gradle.api.Buildable:org.gradle.api.BuildableComponentSpec:org.gradle.api.CheckableComponentSpec:org.gradle.api.CircularReferenceException:org.gradle.api.DefaultTask:org.gradle.api.Describable:org.gradle.api.DomainObjectCollection:org.gradle.api.DomainObjectSet:org.gradle.api.ExtensiblePolymorphicDomainObjectContainer:org.gradle.api.Generated:org.gradle.api.GradleException:org.gradle.api.GradleScriptException:org.gradle.api.HasImplicitReceiver:org.gradle.api.IllegalDependencyNotation:org.gradle.api.Incubating:org.gradle.api.InvalidActionClosureException:org.gradle.api.InvalidUserCodeException:org.gradle.api.InvalidUserDataException:org.gradle.api.JavaVersion:org.gradle.api.Named:org.gradle.api.NamedDomainObjectCollection:org.gradle.api.NamedDomainObjectCollectionSchema:org.gradle.api.NamedDomainObjectContainer:org.gradle.api.NamedDomainObjectFactory:org.gradle.api.NamedDomainObjectList:org.gradle.api.NamedDomainObjectProvider:org.gradle.api.NamedDomainObjectSet:org.gradle.api.Namer:org.gradle.api.NonExtensible:org.gradle.api.NonNullApi:org.gradle.api.PathValidation:org.gradle.api.Plugin:org.gradle.api.PolymorphicDomainObjectContainer:org.gradle.api.Project:org.gradle.api.ProjectConfigurationException:org.gradle.api.ProjectEvaluationListener:org.gradle.api.ProjectState:org.gradle.api.Rule:org.gradle.api.Script:org.gradle.api.Task:org.gradle.api.Transformer:org.gradle.api.UncheckedIOException:org.gradle.api.UnknownDomainObjectException:org.gradle.api.UnknownProjectException:org.gradle.api.UnknownTaskException:org.gradle.api.XmlProvider:org.gradle.api.artifacts.ArtifactCollection:org.gradle.api.artifacts.ArtifactIdentifier:org.gradle.api.artifacts.ArtifactRepositoryContainer:org.gradle.api.artifacts.ArtifactSelectionDetails:org.gradle.api.artifacts.ArtifactView:org.gradle.api.artifacts.CacheableRule:org.gradle.api.artifacts.CapabilitiesResolution:org.gradle.api.artifacts.CapabilityResolutionDetails:org.gradle.api.artifacts.ClientModule:org.gradle.api.artifacts.ComponentMetadata:org.gradle.api.artifacts.ComponentMetadataBuilder:org.gradle.api.artifacts.ComponentMetadataContext:org.gradle.api.artifacts.ComponentMetadataDetails:org.gradle.api.artifacts.ComponentMetadataListerDetails:org.gradle.api.artifacts.ComponentMetadataRule:org.gradle.api.artifacts.ComponentMetadataSupplier:org.gradle.api.artifacts.ComponentMetadataSupplierDetails:org.gradle.api.artifacts.ComponentMetadataVersionLister:org.gradle.api.artifacts.ComponentModuleMetadata:org.gradle.api.artifacts.ComponentModuleMetadataDetails:org.gradle.api.artifacts.ComponentSelection:org.gradle.api.artifacts.ComponentSelectionRules:org.gradle.api.artifacts.ComponentVariantIdentifier:org.gradle.api.artifacts.ConfigurablePublishArtifact:org.gradle.api.artifacts.Configuration:org.gradle.api.artifacts.ConfigurationContainer:org.gradle.api.artifacts.ConfigurationPublications:org.gradle.api.artifacts.ConfigurationVariant:org.gradle.api.artifacts.DependenciesMetadata:org.gradle.api.artifacts.Dependency:org.gradle.api.artifacts.DependencyArtifact:org.gradle.api.artifacts.DependencyArtifactSelector:org.gradle.api.artifacts.DependencyConstraint:org.gradle.api.artifacts.DependencyConstraintMetadata:org.gradle.api.artifacts.DependencyConstraintSet:org.gradle.api.artifacts.DependencyConstraintsMetadata:org.gradle.api.artifacts.DependencyMetadata:org.gradle.api.artifacts.DependencyResolutionListener:org.gradle.api.artifacts.DependencyResolveDetails:org.gradle.api.artifacts.DependencySet:org.gradle.api.artifacts.DependencySubstitution:org.gradle.api.artifacts.DependencySubstitutions:org.gradle.api.artifacts.DirectDependenciesMetadata:org.gradle.api.artifacts.DirectDependencyMetadata:org.gradle.api.artifacts.ExcludeRule:org.gradle.api.artifacts.ExcludeRuleContainer:org.gradle.api.artifacts.ExternalDependency:org.gradle.api.artifacts.ExternalModuleDependency:org.gradle.api.artifacts.ExternalModuleDependencyBundle:org.gradle.api.artifacts.FileCollectionDependency:org.gradle.api.artifacts.LenientConfiguration:org.gradle.api.artifacts.MinimalExternalModuleDependency:org.gradle.api.artifacts.ModuleDependency:org.gradle.api.artifacts.ModuleDependencyCapabilitiesHandler:org.gradle.api.artifacts.ModuleIdentifier:org.gradle.api.artifacts.ModuleVersionIdentifier:org.gradle.api.artifacts.ModuleVersionSelector:org.gradle.api.artifacts.MutableVariantFilesMetadata:org.gradle.api.artifacts.MutableVersionConstraint:org.gradle.api.artifacts.ProjectDependency:org.gradle.api.artifacts.PublishArtifact:org.gradle.api.artifacts.PublishArtifactSet:org.gradle.api.artifacts.PublishException:org.gradle.api.artifacts.ResolutionStrategy:org.gradle.api.artifacts.ResolvableDependencies:org.gradle.api.artifacts.ResolveException:org.gradle.api.artifacts.ResolvedArtifact:org.gradle.api.artifacts.ResolvedConfiguration:org.gradle.api.artifacts.ResolvedDependency:org.gradle.api.artifacts.ResolvedModuleVersion:org.gradle.api.artifacts.SelfResolvingDependency:org.gradle.api.artifacts.UnknownConfigurationException:org.gradle.api.artifacts.UnknownRepositoryException:org.gradle.api.artifacts.UnresolvedDependency:org.gradle.api.artifacts.VariantFileMetadata:org.gradle.api.artifacts.VariantMetadata:org.gradle.api.artifacts.VariantSelectionDetails:org.gradle.api.artifacts.VersionCatalog:org.gradle.api.artifacts.VersionCatalogsExtension:org.gradle.api.artifacts.VersionConstraint:org.gradle.api.artifacts.component.BuildIdentifier:org.gradle.api.artifacts.component.ComponentArtifactIdentifier:org.gradle.api.artifacts.component.ComponentIdentifier:org.gradle.api.artifacts.component.ComponentSelector:org.gradle.api.artifacts.component.LibraryBinaryIdentifier:org.gradle.api.artifacts.component.LibraryComponentSelector:org.gradle.api.artifacts.component.ModuleComponentIdentifier:org.gradle.api.artifacts.component.ModuleComponentSelector:org.gradle.api.artifacts.component.ProjectComponentIdentifier:org.gradle.api.artifacts.component.ProjectComponentSelector:org.gradle.api.artifacts.dsl.ArtifactHandler:org.gradle.api.artifacts.dsl.ComponentMetadataHandler:org.gradle.api.artifacts.dsl.ComponentModuleMetadataHandler:org.gradle.api.artifacts.dsl.DependencyConstraintHandler:org.gradle.api.artifacts.dsl.DependencyHandler:org.gradle.api.artifacts.dsl.DependencyLockingHandler:org.gradle.api.artifacts.dsl.ExternalModuleDependencyVariantSpec:org.gradle.api.artifacts.dsl.LockMode:org.gradle.api.artifacts.dsl.RepositoryHandler:org.gradle.api.artifacts.ivy.IvyExtraInfo:org.gradle.api.artifacts.ivy.IvyModuleDescriptor:org.gradle.api.artifacts.maven.PomModuleDescriptor:org.gradle.api.artifacts.query.ArtifactResolutionQuery:org.gradle.api.artifacts.repositories.ArtifactRepository:org.gradle.api.artifacts.repositories.AuthenticationContainer:org.gradle.api.artifacts.repositories.AuthenticationSupported:org.gradle.api.artifacts.repositories.ExclusiveContentRepository:org.gradle.api.artifacts.repositories.FlatDirectoryArtifactRepository:org.gradle.api.artifacts.repositories.InclusiveRepositoryContentDescriptor:org.gradle.api.artifacts.repositories.IvyArtifactRepository:org.gradle.api.artifacts.repositories.IvyArtifactRepositoryMetaDataProvider:org.gradle.api.artifacts.repositories.IvyPatternRepositoryLayout:org.gradle.api.artifacts.repositories.MavenArtifactRepository:org.gradle.api.artifacts.repositories.MavenRepositoryContentDescriptor:org.gradle.api.artifacts.repositories.MetadataSupplierAware:org.gradle.api.artifacts.repositories.PasswordCredentials:org.gradle.api.artifacts.repositories.RepositoryContentDescriptor:org.gradle.api.artifacts.repositories.RepositoryLayout:org.gradle.api.artifacts.repositories.RepositoryResourceAccessor:org.gradle.api.artifacts.repositories.UrlArtifactRepository:org.gradle.api.artifacts.result.ArtifactResolutionResult:org.gradle.api.artifacts.result.ArtifactResult:org.gradle.api.artifacts.result.ComponentArtifactsResult:org.gradle.api.artifacts.result.ComponentResult:org.gradle.api.artifacts.result.ComponentSelectionCause:org.gradle.api.artifacts.result.ComponentSelectionDescriptor:org.gradle.api.artifacts.result.ComponentSelectionReason:org.gradle.api.artifacts.result.DependencyResult:org.gradle.api.artifacts.result.ResolutionResult:org.gradle.api.artifacts.result.ResolvedArtifactResult:org.gradle.api.artifacts.result.ResolvedComponentResult:org.gradle.api.artifacts.result.ResolvedDependencyResult:org.gradle.api.artifacts.result.ResolvedVariantResult:org.gradle.api.artifacts.result.UnresolvedArtifactResult:org.gradle.api.artifacts.result.UnresolvedComponentResult:org.gradle.api.artifacts.result.UnresolvedDependencyResult:org.gradle.api.artifacts.transform.ArtifactTransform:org.gradle.api.artifacts.transform.ArtifactTransformException:org.gradle.api.artifacts.transform.CacheableTransform:org.gradle.api.artifacts.transform.InputArtifact:org.gradle.api.artifacts.transform.InputArtifactDependencies:org.gradle.api.artifacts.transform.TransformAction:org.gradle.api.artifacts.transform.TransformOutputs:org.gradle.api.artifacts.transform.TransformParameters:org.gradle.api.artifacts.transform.TransformSpec:org.gradle.api.artifacts.transform.VariantTransform:org.gradle.api.artifacts.transform.VariantTransformConfigurationException:org.gradle.api.artifacts.type.ArtifactTypeContainer:org.gradle.api.artifacts.type.ArtifactTypeDefinition:org.gradle.api.artifacts.verification.DependencyVerificationMode:org.gradle.api.attributes.Attribute:org.gradle.api.attributes.AttributeCompatibilityRule:org.gradle.api.attributes.AttributeContainer:org.gradle.api.attributes.AttributeDisambiguationRule:org.gradle.api.attributes.AttributeMatchingStrategy:org.gradle.api.attributes.AttributesSchema:org.gradle.api.attributes.Bundling:org.gradle.api.attributes.Category:org.gradle.api.attributes.CompatibilityCheckDetails:org.gradle.api.attributes.CompatibilityRuleChain:org.gradle.api.attributes.DisambiguationRuleChain:org.gradle.api.attributes.DocsType:org.gradle.api.attributes.HasAttributes:org.gradle.api.attributes.HasConfigurableAttributes:org.gradle.api.attributes.LibraryElements:org.gradle.api.attributes.MultipleCandidatesDetails:org.gradle.api.attributes.Usage:org.gradle.api.attributes.java.TargetJvmEnvironment:org.gradle.api.attributes.java.TargetJvmVersion:org.gradle.api.attributes.plugin.GradlePluginApiVersion:org.gradle.api.capabilities.CapabilitiesMetadata:org.gradle.api.capabilities.Capability:org.gradle.api.capabilities.MutableCapabilitiesMetadata:org.gradle.api.component.AdhocComponentWithVariants:org.gradle.api.component.Artifact:org.gradle.api.component.BuildableComponent:org.gradle.api.component.Component:org.gradle.api.component.ComponentWithCoordinates:org.gradle.api.component.ComponentWithVariants:org.gradle.api.component.ConfigurationVariantDetails:org.gradle.api.component.PublishableComponent:org.gradle.api.component.SoftwareComponent:org.gradle.api.component.SoftwareComponentContainer:org.gradle.api.component.SoftwareComponentFactory:org.gradle.api.component.SoftwareComponentVariant:org.gradle.api.credentials.AwsCredentials:org.gradle.api.credentials.Credentials:org.gradle.api.credentials.HttpHeaderCredentials:org.gradle.api.distribution.Distribution:org.gradle.api.distribution.DistributionContainer:org.gradle.api.distribution.plugins.DistributionPlugin:org.gradle.api.execution.TaskActionListener:org.gradle.api.execution.TaskExecutionAdapter:org.gradle.api.execution.TaskExecutionGraph:org.gradle.api.execution.TaskExecutionGraphListener:org.gradle.api.execution.TaskExecutionListener:org.gradle.api.file.ArchiveOperations:org.gradle.api.file.ConfigurableFileCollection:org.gradle.api.file.ConfigurableFileTree:org.gradle.api.file.ContentFilterable:org.gradle.api.file.CopyProcessingSpec:org.gradle.api.file.CopySourceSpec:org.gradle.api.file.CopySpec:org.gradle.api.file.DeleteSpec:org.gradle.api.file.Directory:org.gradle.api.file.DirectoryProperty:org.gradle.api.file.DirectoryTree:org.gradle.api.file.DuplicateFileCopyingException:org.gradle.api.file.DuplicatesStrategy:org.gradle.api.file.EmptyFileVisitor:org.gradle.api.file.ExpandDetails:org.gradle.api.file.FileCollection:org.gradle.api.file.FileContents:org.gradle.api.file.FileCopyDetails:org.gradle.api.file.FileSystemLocation:org.gradle.api.file.FileSystemLocationProperty:org.gradle.api.file.FileSystemOperations:org.gradle.api.file.FileTree:org.gradle.api.file.FileTreeElement:org.gradle.api.file.FileType:org.gradle.api.file.FileVisitDetails:org.gradle.api.file.FileVisitor:org.gradle.api.file.ProjectLayout:org.gradle.api.file.RegularFile:org.gradle.api.file.RegularFileProperty:org.gradle.api.file.RelativePath:org.gradle.api.file.ReproducibleFileVisitor:org.gradle.api.file.SourceDirectorySet:org.gradle.api.initialization.ConfigurableIncludedBuild:org.gradle.api.initialization.ConfigurableIncludedPluginBuild:org.gradle.api.initialization.IncludedBuild:org.gradle.api.initialization.ProjectDescriptor:org.gradle.api.initialization.Settings:org.gradle.api.initialization.definition.InjectedPluginDependencies:org.gradle.api.initialization.definition.InjectedPluginDependency:org.gradle.api.initialization.dsl.ScriptHandler:org.gradle.api.initialization.dsl.VersionCatalogBuilder:org.gradle.api.initialization.resolve.DependencyResolutionManagement:org.gradle.api.initialization.resolve.MutableVersionCatalogContainer:org.gradle.api.initialization.resolve.RepositoriesMode:org.gradle.api.initialization.resolve.RulesMode:org.gradle.api.invocation.BuildInvocationDetails:org.gradle.api.invocation.Gradle:org.gradle.api.java.archives.Attributes:org.gradle.api.java.archives.Manifest:org.gradle.api.java.archives.ManifestException:org.gradle.api.java.archives.ManifestMergeDetails:org.gradle.api.java.archives.ManifestMergeSpec:org.gradle.api.jvm.ModularitySpec:org.gradle.api.logging.LogLevel:org.gradle.api.logging.Logger:org.gradle.api.logging.Logging:org.gradle.api.logging.LoggingManager:org.gradle.api.logging.LoggingOutput:org.gradle.api.logging.StandardOutputListener:org.gradle.api.logging.configuration.ConsoleOutput:org.gradle.api.logging.configuration.LoggingConfiguration:org.gradle.api.logging.configuration.ShowStacktrace:org.gradle.api.logging.configuration.WarningMode:org.gradle.api.model.ObjectFactory:org.gradle.api.model.ReplacedBy:org.gradle.api.plugins.ApplicationPlugin:org.gradle.api.plugins.ApplicationPluginConvention:org.gradle.api.plugins.AppliedPlugin:org.gradle.api.plugins.BasePlugin:org.gradle.api.plugins.BasePluginConvention:org.gradle.api.plugins.BasePluginExtension:org.gradle.api.plugins.Convention:org.gradle.api.plugins.ExtensionAware:org.gradle.api.plugins.ExtensionContainer:org.gradle.api.plugins.ExtensionsSchema:org.gradle.api.plugins.ExtraPropertiesExtension:org.gradle.api.plugins.FeatureSpec:org.gradle.api.plugins.GroovyBasePlugin:org.gradle.api.plugins.GroovyPlugin:org.gradle.api.plugins.HelpTasksPlugin:org.gradle.api.plugins.InvalidPluginException:org.gradle.api.plugins.JavaApplication:org.gradle.api.plugins.JavaBasePlugin:org.gradle.api.plugins.JavaLibraryDistributionPlugin:org.gradle.api.plugins.JavaLibraryPlugin:org.gradle.api.plugins.JavaPlatformExtension:org.gradle.api.plugins.JavaPlatformPlugin:org.gradle.api.plugins.JavaPlugin:org.gradle.api.plugins.JavaPluginConvention:org.gradle.api.plugins.JavaPluginExtension:org.gradle.api.plugins.JavaResolutionConsistency:org.gradle.api.plugins.JavaTestFixturesPlugin:org.gradle.api.plugins.JvmEcosystemPlugin:org.gradle.api.plugins.JvmTestSuitePlugin:org.gradle.api.plugins.MavenPlugin:org.gradle.api.plugins.ObjectConfigurationAction:org.gradle.api.plugins.PluginAware:org.gradle.api.plugins.PluginCollection:org.gradle.api.plugins.PluginContainer:org.gradle.api.plugins.PluginInstantiationException:org.gradle.api.plugins.PluginManager:org.gradle.api.plugins.ProjectReportsPlugin:org.gradle.api.plugins.ProjectReportsPluginConvention:org.gradle.api.plugins.ReportingBasePlugin:org.gradle.api.plugins.UnknownPluginException:org.gradle.api.plugins.WarPlugin:org.gradle.api.plugins.WarPluginConvention:org.gradle.api.plugins.antlr.AntlrPlugin:org.gradle.api.plugins.antlr.AntlrSourceDirectorySet:org.gradle.api.plugins.antlr.AntlrSourceVirtualDirectory:org.gradle.api.plugins.antlr.AntlrTask:org.gradle.api.plugins.catalog.CatalogPluginExtension:org.gradle.api.plugins.catalog.VersionCatalogPlugin:org.gradle.api.plugins.jvm.JvmComponentDependencies:org.gradle.api.plugins.jvm.JvmTestSuite:org.gradle.api.plugins.jvm.JvmTestSuiteTarget:org.gradle.api.plugins.quality.Checkstyle:org.gradle.api.plugins.quality.CheckstyleExtension:org.gradle.api.plugins.quality.CheckstylePlugin:org.gradle.api.plugins.quality.CheckstyleReports:org.gradle.api.plugins.quality.CodeNarc:org.gradle.api.plugins.quality.CodeNarcExtension:org.gradle.api.plugins.quality.CodeNarcPlugin:org.gradle.api.plugins.quality.CodeNarcReports:org.gradle.api.plugins.quality.CodeQualityExtension:org.gradle.api.plugins.quality.Pmd:org.gradle.api.plugins.quality.PmdExtension:org.gradle.api.plugins.quality.PmdPlugin:org.gradle.api.plugins.quality.PmdReports:org.gradle.api.plugins.quality.TargetJdk:org.gradle.api.plugins.scala.ScalaBasePlugin:org.gradle.api.plugins.scala.ScalaPlugin:org.gradle.api.plugins.scala.ScalaPluginExtension:org.gradle.api.provider.HasConfigurableValue:org.gradle.api.provider.HasMultipleValues:org.gradle.api.provider.ListProperty:org.gradle.api.provider.MapProperty:org.gradle.api.provider.Property:org.gradle.api.provider.Provider:org.gradle.api.provider.ProviderConvertible:org.gradle.api.provider.ProviderFactory:org.gradle.api.provider.SetProperty:org.gradle.api.provider.ValueSource:org.gradle.api.provider.ValueSourceParameters:org.gradle.api.provider.ValueSourceSpec:org.gradle.api.publish.Publication:org.gradle.api.publish.PublicationArtifact:org.gradle.api.publish.PublicationContainer:org.gradle.api.publish.PublishingExtension:org.gradle.api.publish.VariantVersionMappingStrategy:org.gradle.api.publish.VersionMappingStrategy:org.gradle.api.publish.ivy.InvalidIvyPublicationException:org.gradle.api.publish.ivy.IvyArtifact:org.gradle.api.publish.ivy.IvyArtifactSet:org.gradle.api.publish.ivy.IvyConfiguration:org.gradle.api.publish.ivy.IvyConfigurationContainer:org.gradle.api.publish.ivy.IvyDependency:org.gradle.api.publish.ivy.IvyExtraInfoSpec:org.gradle.api.publish.ivy.IvyModuleDescriptorAuthor:org.gradle.api.publish.ivy.IvyModuleDescriptorDescription:org.gradle.api.publish.ivy.IvyModuleDescriptorLicense:org.gradle.api.publish.ivy.IvyModuleDescriptorSpec:org.gradle.api.publish.ivy.IvyPublication:org.gradle.api.publish.ivy.plugins.IvyPublishPlugin:org.gradle.api.publish.ivy.tasks.GenerateIvyDescriptor:org.gradle.api.publish.ivy.tasks.PublishToIvyRepository:org.gradle.api.publish.maven.InvalidMavenPublicationException:org.gradle.api.publish.maven.MavenArtifact:org.gradle.api.publish.maven.MavenArtifactSet:org.gradle.api.publish.maven.MavenDependency:org.gradle.api.publish.maven.MavenPom:org.gradle.api.publish.maven.MavenPomCiManagement:org.gradle.api.publish.maven.MavenPomContributor:org.gradle.api.publish.maven.MavenPomContributorSpec:org.gradle.api.publish.maven.MavenPomDeveloper:org.gradle.api.publish.maven.MavenPomDeveloperSpec:org.gradle.api.publish.maven.MavenPomDistributionManagement:org.gradle.api.publish.maven.MavenPomIssueManagement:org.gradle.api.publish.maven.MavenPomLicense:org.gradle.api.publish.maven.MavenPomLicenseSpec:org.gradle.api.publish.maven.MavenPomMailingList:org.gradle.api.publish.maven.MavenPomMailingListSpec:org.gradle.api.publish.maven.MavenPomOrganization:org.gradle.api.publish.maven.MavenPomRelocation:org.gradle.api.publish.maven.MavenPomScm:org.gradle.api.publish.maven.MavenPublication:org.gradle.api.publish.maven.plugins.MavenPublishPlugin:org.gradle.api.publish.maven.tasks.AbstractPublishToMaven:org.gradle.api.publish.maven.tasks.GenerateMavenPom:org.gradle.api.publish.maven.tasks.PublishToMavenLocal:org.gradle.api.publish.maven.tasks.PublishToMavenRepository:org.gradle.api.publish.plugins.PublishingPlugin:org.gradle.api.publish.plugins.PublishingPluginRules:org.gradle.api.publish.tasks.GenerateModuleMetadata:org.gradle.api.reflect.HasPublicType:org.gradle.api.reflect.InjectionPointQualifier:org.gradle.api.reflect.ObjectInstantiationException:org.gradle.api.reflect.TypeOf:org.gradle.api.reporting.BuildDashboardReports:org.gradle.api.reporting.ConfigurableReport:org.gradle.api.reporting.CustomizableHtmlReport:org.gradle.api.reporting.DirectoryReport:org.gradle.api.reporting.GenerateBuildDashboard:org.gradle.api.reporting.Report:org.gradle.api.reporting.ReportContainer:org.gradle.api.reporting.Reporting:org.gradle.api.reporting.ReportingExtension:org.gradle.api.reporting.SingleFileReport:org.gradle.api.reporting.components.ComponentReport:org.gradle.api.reporting.dependencies.DependencyReportContainer:org.gradle.api.reporting.dependencies.HtmlDependencyReportTask:org.gradle.api.reporting.dependents.DependentComponentsReport:org.gradle.api.reporting.model.ModelReport:org.gradle.api.reporting.plugins.BuildDashboardPlugin:org.gradle.api.resources.MissingResourceException:org.gradle.api.resources.ReadableResource:org.gradle.api.resources.Resource:org.gradle.api.resources.ResourceException:org.gradle.api.resources.ResourceHandler:org.gradle.api.resources.TextResource:org.gradle.api.resources.TextResourceFactory:org.gradle.api.services.BuildService:org.gradle.api.services.BuildServiceParameters:org.gradle.api.services.BuildServiceRegistration:org.gradle.api.services.BuildServiceRegistry:org.gradle.api.services.BuildServiceSpec:org.gradle.api.specs.AndSpec:org.gradle.api.specs.CompositeSpec:org.gradle.api.specs.NotSpec:org.gradle.api.specs.OrSpec:org.gradle.api.specs.Spec:org.gradle.api.specs.Specs:org.gradle.api.tasks.AbstractCopyTask:org.gradle.api.tasks.AbstractExecTask:org.gradle.api.tasks.AntBuilderAware:org.gradle.api.tasks.CacheableTask:org.gradle.api.tasks.Classpath:org.gradle.api.tasks.ClasspathNormalizer:org.gradle.api.tasks.CompileClasspath:org.gradle.api.tasks.CompileClasspathNormalizer:org.gradle.api.tasks.Console:org.gradle.api.tasks.Copy:org.gradle.api.tasks.Delete:org.gradle.api.tasks.Destroys:org.gradle.api.tasks.Exec:org.gradle.api.tasks.FileNormalizer:org.gradle.api.tasks.GradleBuild:org.gradle.api.tasks.GroovyRuntime:org.gradle.api.tasks.GroovySourceDirectorySet:org.gradle.api.tasks.GroovySourceSet:org.gradle.api.tasks.IgnoreEmptyDirectories:org.gradle.api.tasks.Input:org.gradle.api.tasks.InputDirectory:org.gradle.api.tasks.InputFile:org.gradle.api.tasks.InputFiles:org.gradle.api.tasks.Internal:org.gradle.api.tasks.JavaExec:org.gradle.api.tasks.LocalState:org.gradle.api.tasks.Nested:org.gradle.api.tasks.Optional:org.gradle.api.tasks.OutputDirectories:org.gradle.api.tasks.OutputDirectory:org.gradle.api.tasks.OutputFile:org.gradle.api.tasks.OutputFiles:org.gradle.api.tasks.PathSensitive:org.gradle.api.tasks.PathSensitivity:org.gradle.api.tasks.ScalaRuntime:org.gradle.api.tasks.ScalaSourceDirectorySet:org.gradle.api.tasks.ScalaSourceSet:org.gradle.api.tasks.SkipWhenEmpty:org.gradle.api.tasks.SourceSet:org.gradle.api.tasks.SourceSetContainer:org.gradle.api.tasks.SourceSetOutput:org.gradle.api.tasks.SourceTask:org.gradle.api.tasks.StopActionException:org.gradle.api.tasks.StopExecutionException:org.gradle.api.tasks.Sync:org.gradle.api.tasks.TaskAction:org.gradle.api.tasks.TaskCollection:org.gradle.api.tasks.TaskContainer:org.gradle.api.tasks.TaskDependency:org.gradle.api.tasks.TaskDestroyables:org.gradle.api.tasks.TaskExecutionException:org.gradle.api.tasks.TaskFilePropertyBuilder:org.gradle.api.tasks.TaskInputFilePropertyBuilder:org.gradle.api.tasks.TaskInputPropertyBuilder:org.gradle.api.tasks.TaskInputs:org.gradle.api.tasks.TaskInstantiationException:org.gradle.api.tasks.TaskLocalState:org.gradle.api.tasks.TaskOutputFilePropertyBuilder:org.gradle.api.tasks.TaskOutputs:org.gradle.api.tasks.TaskPropertyBuilder:org.gradle.api.tasks.TaskProvider:org.gradle.api.tasks.TaskReference:org.gradle.api.tasks.TaskState:org.gradle.api.tasks.UntrackedTask:org.gradle.api.tasks.Upload:org.gradle.api.tasks.VerificationTask:org.gradle.api.tasks.WorkResult:org.gradle.api.tasks.WorkResults:org.gradle.api.tasks.WriteProperties:org.gradle.api.tasks.ant.AntTarget:org.gradle.api.tasks.application.CreateStartScripts:org.gradle.api.tasks.bundling.AbstractArchiveTask:org.gradle.api.tasks.bundling.Compression:org.gradle.api.tasks.bundling.Jar:org.gradle.api.tasks.bundling.Tar:org.gradle.api.tasks.bundling.War:org.gradle.api.tasks.bundling.Zip:org.gradle.api.tasks.bundling.ZipEntryCompression:org.gradle.api.tasks.compile.AbstractCompile:org.gradle.api.tasks.compile.AbstractOptions:org.gradle.api.tasks.compile.BaseForkOptions:org.gradle.api.tasks.compile.CompileOptions:org.gradle.api.tasks.compile.DebugOptions:org.gradle.api.tasks.compile.ForkOptions:org.gradle.api.tasks.compile.GroovyCompile:org.gradle.api.tasks.compile.GroovyCompileOptions:org.gradle.api.tasks.compile.GroovyForkOptions:org.gradle.api.tasks.compile.JavaCompile:org.gradle.api.tasks.compile.ProviderAwareCompilerDaemonForkOptions:org.gradle.api.tasks.diagnostics.AbstractDependencyReportTask:org.gradle.api.tasks.diagnostics.AbstractReportTask:org.gradle.api.tasks.diagnostics.BuildEnvironmentReportTask:org.gradle.api.tasks.diagnostics.ConventionReportTask:org.gradle.api.tasks.diagnostics.DependencyInsightReportTask:org.gradle.api.tasks.diagnostics.DependencyReportTask:org.gradle.api.tasks.diagnostics.OutgoingVariantsReportTask:org.gradle.api.tasks.diagnostics.ProjectBasedReportTask:org.gradle.api.tasks.diagnostics.ProjectReportTask:org.gradle.api.tasks.diagnostics.PropertyReportTask:org.gradle.api.tasks.diagnostics.ResolutionErrorRenderer:org.gradle.api.tasks.diagnostics.TaskReportTask:org.gradle.api.tasks.incremental.IncrementalTaskInputs:org.gradle.api.tasks.incremental.InputFileDetails:org.gradle.api.tasks.javadoc.Groovydoc:org.gradle.api.tasks.javadoc.Javadoc:org.gradle.api.tasks.options.Option:org.gradle.api.tasks.options.OptionValues:org.gradle.api.tasks.scala.IncrementalCompileOptions:org.gradle.api.tasks.scala.ScalaCompile:org.gradle.api.tasks.scala.ScalaCompileOptions:org.gradle.api.tasks.scala.ScalaDoc:org.gradle.api.tasks.scala.ScalaDocOptions:org.gradle.api.tasks.scala.ScalaForkOptions:org.gradle.api.tasks.testing.AbstractTestTask:org.gradle.api.tasks.testing.JUnitXmlReport:org.gradle.api.tasks.testing.Test:org.gradle.api.tasks.testing.TestDescriptor:org.gradle.api.tasks.testing.TestExecutionException:org.gradle.api.tasks.testing.TestFilter:org.gradle.api.tasks.testing.TestFrameworkOptions:org.gradle.api.tasks.testing.TestListener:org.gradle.api.tasks.testing.TestOutputEvent:org.gradle.api.tasks.testing.TestOutputListener:org.gradle.api.tasks.testing.TestReport:org.gradle.api.tasks.testing.TestResult:org.gradle.api.tasks.testing.TestTaskReports:org.gradle.api.tasks.testing.junit.JUnitOptions:org.gradle.api.tasks.testing.junitplatform.JUnitPlatformOptions:org.gradle.api.tasks.testing.testng.TestNGOptions:org.gradle.api.tasks.util.PatternFilterable:org.gradle.api.tasks.util.PatternSet:org.gradle.api.tasks.wrapper.Wrapper:org.gradle.authentication.Authentication:org.gradle.authentication.aws.AwsImAuthentication:org.gradle.authentication.http.BasicAuthentication:org.gradle.authentication.http.DigestAuthentication:org.gradle.authentication.http.HttpHeaderAuthentication:org.gradle.build.event.BuildEventsListenerRegistry:org.gradle.buildinit.InsecureProtocolOption:org.gradle.buildinit.plugins.BuildInitPlugin:org.gradle.buildinit.plugins.WrapperPlugin:org.gradle.buildinit.tasks.InitBuild:org.gradle.caching.BuildCacheEntryReader:org.gradle.caching.BuildCacheEntryWriter:org.gradle.caching.BuildCacheException:org.gradle.caching.BuildCacheKey:org.gradle.caching.BuildCacheService:org.gradle.caching.BuildCacheServiceFactory:org.gradle.caching.MapBasedBuildCacheService:org.gradle.caching.configuration.AbstractBuildCache:org.gradle.caching.configuration.BuildCache:org.gradle.caching.configuration.BuildCacheConfiguration:org.gradle.caching.http.HttpBuildCache:org.gradle.caching.http.HttpBuildCacheCredentials:org.gradle.caching.local.DirectoryBuildCache:org.gradle.concurrent.ParallelismConfiguration:org.gradle.external.javadoc.CoreJavadocOptions:org.gradle.external.javadoc.JavadocMemberLevel:org.gradle.external.javadoc.JavadocOfflineLink:org.gradle.external.javadoc.JavadocOptionFileOption:org.gradle.external.javadoc.JavadocOutputLevel:org.gradle.external.javadoc.MinimalJavadocOptions:org.gradle.external.javadoc.OptionLessJavadocOptionFileOption:org.gradle.external.javadoc.StandardJavadocDocletOptions:org.gradle.ide.visualstudio.ConfigFile:org.gradle.ide.visualstudio.TextConfigFile:org.gradle.ide.visualstudio.TextProvider:org.gradle.ide.visualstudio.VisualStudioExtension:org.gradle.ide.visualstudio.VisualStudioProject:org.gradle.ide.visualstudio.VisualStudioRootExtension:org.gradle.ide.visualstudio.VisualStudioSolution:org.gradle.ide.visualstudio.XmlConfigFile:org.gradle.ide.visualstudio.plugins.VisualStudioPlugin:org.gradle.ide.visualstudio.plugins.VisualStudioPluginRules:org.gradle.ide.visualstudio.tasks.GenerateFiltersFileTask:org.gradle.ide.visualstudio.tasks.GenerateProjectFileTask:org.gradle.ide.visualstudio.tasks.GenerateSolutionFileTask:org.gradle.ide.xcode.XcodeExtension:org.gradle.ide.xcode.XcodeProject:org.gradle.ide.xcode.XcodeRootExtension:org.gradle.ide.xcode.XcodeWorkspace:org.gradle.ide.xcode.plugins.XcodePlugin:org.gradle.ide.xcode.tasks.GenerateSchemeFileTask:org.gradle.ide.xcode.tasks.GenerateWorkspaceSettingsFileTask:org.gradle.ide.xcode.tasks.GenerateXcodeProjectFileTask:org.gradle.ide.xcode.tasks.GenerateXcodeWorkspaceFileTask:org.gradle.ivy.IvyDescriptorArtifact:org.gradle.ivy.IvyModule:org.gradle.jvm.JvmLibrary:org.gradle.jvm.application.scripts.JavaAppStartScriptGenerationDetails:org.gradle.jvm.application.scripts.ScriptGenerator:org.gradle.jvm.application.scripts.TemplateBasedScriptGenerator:org.gradle.jvm.toolchain.JavaCompiler:org.gradle.jvm.toolchain.JavaInstallationMetadata:org.gradle.jvm.toolchain.JavaLanguageVersion:org.gradle.jvm.toolchain.JavaLauncher:org.gradle.jvm.toolchain.JavaToolchainService:org.gradle.jvm.toolchain.JavaToolchainSpec:org.gradle.jvm.toolchain.JavadocTool:org.gradle.jvm.toolchain.JvmImplementation:org.gradle.jvm.toolchain.JvmVendorSpec:org.gradle.language.BinaryCollection:org.gradle.language.BinaryProvider:org.gradle.language.ComponentDependencies:org.gradle.language.ComponentWithBinaries:org.gradle.language.ComponentWithDependencies:org.gradle.language.ComponentWithOutputs:org.gradle.language.ComponentWithTargetMachines:org.gradle.language.LibraryDependencies:org.gradle.language.ProductionComponent:org.gradle.language.assembler.AssemblerSourceSet:org.gradle.language.assembler.plugins.AssemblerLangPlugin:org.gradle.language.assembler.plugins.AssemblerPlugin:org.gradle.language.assembler.tasks.Assemble:org.gradle.language.base.DependentSourceSet:org.gradle.language.base.FunctionalSourceSet:org.gradle.language.base.LanguageSourceSet:org.gradle.language.base.ProjectSourceSet:org.gradle.language.base.artifact.SourcesArtifact:org.gradle.language.base.compile.CompilerVersion:org.gradle.language.base.plugins.ComponentModelBasePlugin:org.gradle.language.base.plugins.LanguageBasePlugin:org.gradle.language.base.plugins.LifecycleBasePlugin:org.gradle.language.base.sources.BaseLanguageSourceSet:org.gradle.language.c.CSourceSet:org.gradle.language.c.plugins.CLangPlugin:org.gradle.language.c.plugins.CPlugin:org.gradle.language.c.tasks.CCompile:org.gradle.language.c.tasks.CPreCompiledHeaderCompile:org.gradle.language.cpp.CppApplication:org.gradle.language.cpp.CppBinary:org.gradle.language.cpp.CppComponent:org.gradle.language.cpp.CppExecutable:org.gradle.language.cpp.CppLibrary:org.gradle.language.cpp.CppPlatform:org.gradle.language.cpp.CppSharedLibrary:org.gradle.language.cpp.CppSourceSet:org.gradle.language.cpp.CppStaticLibrary:org.gradle.language.cpp.ProductionCppComponent:org.gradle.language.cpp.plugins.CppApplicationPlugin:org.gradle.language.cpp.plugins.CppBasePlugin:org.gradle.language.cpp.plugins.CppLangPlugin:org.gradle.language.cpp.plugins.CppLibraryPlugin:org.gradle.language.cpp.plugins.CppPlugin:org.gradle.language.cpp.tasks.CppCompile:org.gradle.language.cpp.tasks.CppPreCompiledHeaderCompile:org.gradle.language.java.artifact.JavadocArtifact:org.gradle.language.jvm.tasks.ProcessResources:org.gradle.language.nativeplatform.ComponentWithExecutable:org.gradle.language.nativeplatform.ComponentWithInstallation:org.gradle.language.nativeplatform.ComponentWithLinkFile:org.gradle.language.nativeplatform.ComponentWithLinkUsage:org.gradle.language.nativeplatform.ComponentWithNativeRuntime:org.gradle.language.nativeplatform.ComponentWithObjectFiles:org.gradle.language.nativeplatform.ComponentWithRuntimeFile:org.gradle.language.nativeplatform.ComponentWithRuntimeUsage:org.gradle.language.nativeplatform.ComponentWithSharedLibrary:org.gradle.language.nativeplatform.ComponentWithStaticLibrary:org.gradle.language.nativeplatform.HeaderExportingSourceSet:org.gradle.language.nativeplatform.NativeResourceSet:org.gradle.language.nativeplatform.tasks.AbstractNativeCompileTask:org.gradle.language.nativeplatform.tasks.AbstractNativePCHCompileTask:org.gradle.language.nativeplatform.tasks.AbstractNativeSourceCompileTask:org.gradle.language.nativeplatform.tasks.UnexportMainSymbol:org.gradle.language.objectivec.ObjectiveCSourceSet:org.gradle.language.objectivec.plugins.ObjectiveCLangPlugin:org.gradle.language.objectivec.plugins.ObjectiveCPlugin:org.gradle.language.objectivec.tasks.ObjectiveCCompile:org.gradle.language.objectivec.tasks.ObjectiveCPreCompiledHeaderCompile:org.gradle.language.objectivecpp.ObjectiveCppSourceSet:org.gradle.language.objectivecpp.plugins.ObjectiveCppLangPlugin:org.gradle.language.objectivecpp.plugins.ObjectiveCppPlugin:org.gradle.language.objectivecpp.tasks.ObjectiveCppCompile:org.gradle.language.objectivecpp.tasks.ObjectiveCppPreCompiledHeaderCompile:org.gradle.language.plugins.NativeBasePlugin:org.gradle.language.rc.WindowsResourceSet:org.gradle.language.rc.plugins.WindowsResourceScriptPlugin:org.gradle.language.rc.plugins.WindowsResourcesPlugin:org.gradle.language.rc.tasks.WindowsResourceCompile:org.gradle.language.scala.tasks.AbstractScalaCompile:org.gradle.language.scala.tasks.BaseScalaCompileOptions:org.gradle.language.swift.ProductionSwiftComponent:org.gradle.language.swift.SwiftApplication:org.gradle.language.swift.SwiftBinary:org.gradle.language.swift.SwiftComponent:org.gradle.language.swift.SwiftExecutable:org.gradle.language.swift.SwiftLibrary:org.gradle.language.swift.SwiftPlatform:org.gradle.language.swift.SwiftSharedLibrary:org.gradle.language.swift.SwiftStaticLibrary:org.gradle.language.swift.SwiftVersion:org.gradle.language.swift.plugins.SwiftApplicationPlugin:org.gradle.language.swift.plugins.SwiftBasePlugin:org.gradle.language.swift.plugins.SwiftLibraryPlugin:org.gradle.language.swift.tasks.SwiftCompile:org.gradle.maven.MavenModule:org.gradle.maven.MavenPomArtifact:org.gradle.model.ConfigurationCycleException:org.gradle.model.Defaults:org.gradle.model.Each:org.gradle.model.Finalize:org.gradle.model.InvalidModelRuleDeclarationException:org.gradle.model.InvalidModelRuleException:org.gradle.model.Managed:org.gradle.model.Model:org.gradle.model.ModelElement:org.gradle.model.ModelMap:org.gradle.model.ModelRuleBindingException:org.gradle.model.ModelSet:org.gradle.model.ModelViewClosedException:org.gradle.model.Mutate:org.gradle.model.Path:org.gradle.model.ReadOnlyModelViewException:org.gradle.model.RuleInput:org.gradle.model.RuleSource:org.gradle.model.RuleTarget:org.gradle.model.Rules:org.gradle.model.Unmanaged:org.gradle.model.Validate:org.gradle.model.WriteOnlyModelViewException:org.gradle.nativeplatform.BuildType:org.gradle.nativeplatform.BuildTypeContainer:org.gradle.nativeplatform.Flavor:org.gradle.nativeplatform.FlavorContainer:org.gradle.nativeplatform.Linkage:org.gradle.nativeplatform.MachineArchitecture:org.gradle.nativeplatform.NativeBinary:org.gradle.nativeplatform.NativeBinarySpec:org.gradle.nativeplatform.NativeComponentExtension:org.gradle.nativeplatform.NativeComponentSpec:org.gradle.nativeplatform.NativeDependencySet:org.gradle.nativeplatform.NativeExecutable:org.gradle.nativeplatform.NativeExecutableBinary:org.gradle.nativeplatform.NativeExecutableBinarySpec:org.gradle.nativeplatform.NativeExecutableFileSpec:org.gradle.nativeplatform.NativeExecutableSpec:org.gradle.nativeplatform.NativeInstallationSpec:org.gradle.nativeplatform.NativeLibrary:org.gradle.nativeplatform.NativeLibraryBinary:org.gradle.nativeplatform.NativeLibraryBinarySpec:org.gradle.nativeplatform.NativeLibraryRequirement:org.gradle.nativeplatform.NativeLibrarySpec:org.gradle.nativeplatform.ObjectFile:org.gradle.nativeplatform.OperatingSystemFamily:org.gradle.nativeplatform.PrebuiltLibraries:org.gradle.nativeplatform.PrebuiltLibrary:org.gradle.nativeplatform.PrebuiltSharedLibraryBinary:org.gradle.nativeplatform.PrebuiltStaticLibraryBinary:org.gradle.nativeplatform.PreprocessingTool:org.gradle.nativeplatform.Repositories:org.gradle.nativeplatform.SharedLibraryBinary:org.gradle.nativeplatform.SharedLibraryBinarySpec:org.gradle.nativeplatform.StaticLibraryBinary:org.gradle.nativeplatform.StaticLibraryBinarySpec:org.gradle.nativeplatform.TargetMachine:org.gradle.nativeplatform.TargetMachineBuilder:org.gradle.nativeplatform.TargetMachineFactory:org.gradle.nativeplatform.TargetedNativeComponent:org.gradle.nativeplatform.Tool:org.gradle.nativeplatform.platform.Architecture:org.gradle.nativeplatform.platform.NativePlatform:org.gradle.nativeplatform.platform.OperatingSystem:org.gradle.nativeplatform.plugins.NativeComponentModelPlugin:org.gradle.nativeplatform.plugins.NativeComponentPlugin:org.gradle.nativeplatform.tasks.AbstractLinkTask:org.gradle.nativeplatform.tasks.CreateStaticLibrary:org.gradle.nativeplatform.tasks.ExtractSymbols:org.gradle.nativeplatform.tasks.InstallExecutable:org.gradle.nativeplatform.tasks.LinkExecutable:org.gradle.nativeplatform.tasks.LinkMachOBundle:org.gradle.nativeplatform.tasks.LinkSharedLibrary:org.gradle.nativeplatform.tasks.ObjectFilesToBinary:org.gradle.nativeplatform.tasks.PrefixHeaderFileGenerateTask:org.gradle.nativeplatform.tasks.StripSymbols:org.gradle.nativeplatform.test.NativeTestSuiteBinarySpec:org.gradle.nativeplatform.test.NativeTestSuiteSpec:org.gradle.nativeplatform.test.TestComponent:org.gradle.nativeplatform.test.TestSuiteComponent:org.gradle.nativeplatform.test.cpp.CppTestExecutable:org.gradle.nativeplatform.test.cpp.CppTestSuite:org.gradle.nativeplatform.test.cpp.plugins.CppUnitTestPlugin:org.gradle.nativeplatform.test.cunit.CUnitTestSuiteBinarySpec:org.gradle.nativeplatform.test.cunit.CUnitTestSuiteSpec:org.gradle.nativeplatform.test.cunit.plugins.CUnitConventionPlugin:org.gradle.nativeplatform.test.cunit.plugins.CUnitPlugin:org.gradle.nativeplatform.test.cunit.tasks.GenerateCUnitLauncher:org.gradle.nativeplatform.test.googletest.GoogleTestTestSuiteBinarySpec:org.gradle.nativeplatform.test.googletest.GoogleTestTestSuiteSpec:org.gradle.nativeplatform.test.googletest.plugins.GoogleTestConventionPlugin:org.gradle.nativeplatform.test.googletest.plugins.GoogleTestPlugin:org.gradle.nativeplatform.test.plugins.NativeBinariesTestPlugin:org.gradle.nativeplatform.test.plugins.NativeTestingBasePlugin:org.gradle.nativeplatform.test.tasks.RunTestExecutable:org.gradle.nativeplatform.test.xctest.SwiftXCTestBinary:org.gradle.nativeplatform.test.xctest.SwiftXCTestBundle:org.gradle.nativeplatform.test.xctest.SwiftXCTestExecutable:org.gradle.nativeplatform.test.xctest.SwiftXCTestSuite:org.gradle.nativeplatform.test.xctest.plugins.XCTestConventionPlugin:org.gradle.nativeplatform.test.xctest.tasks.InstallXCTestBundle:org.gradle.nativeplatform.test.xctest.tasks.XCTest:org.gradle.nativeplatform.toolchain.Clang:org.gradle.nativeplatform.toolchain.CommandLineToolConfiguration:org.gradle.nativeplatform.toolchain.Gcc:org.gradle.nativeplatform.toolchain.GccCommandLineToolConfiguration:org.gradle.nativeplatform.toolchain.GccCompatibleToolChain:org.gradle.nativeplatform.toolchain.GccPlatformToolChain:org.gradle.nativeplatform.toolchain.NativePlatformToolChain:org.gradle.nativeplatform.toolchain.NativeToolChain:org.gradle.nativeplatform.toolchain.NativeToolChainRegistry:org.gradle.nativeplatform.toolchain.Swiftc:org.gradle.nativeplatform.toolchain.SwiftcPlatformToolChain:org.gradle.nativeplatform.toolchain.VisualCpp:org.gradle.nativeplatform.toolchain.VisualCppPlatformToolChain:org.gradle.nativeplatform.toolchain.plugins.ClangCompilerPlugin:org.gradle.nativeplatform.toolchain.plugins.GccCompilerPlugin:org.gradle.nativeplatform.toolchain.plugins.MicrosoftVisualCppCompilerPlugin:org.gradle.nativeplatform.toolchain.plugins.SwiftCompilerPlugin:org.gradle.normalization.InputNormalization:org.gradle.normalization.InputNormalizationHandler:org.gradle.normalization.MetaInfNormalization:org.gradle.normalization.PropertiesFileNormalization:org.gradle.normalization.RuntimeClasspathNormalization:org.gradle.platform.base.Application:org.gradle.platform.base.ApplicationBinarySpec:org.gradle.platform.base.ApplicationSpec:org.gradle.platform.base.Binary:org.gradle.platform.base.BinaryContainer:org.gradle.platform.base.BinarySpec:org.gradle.platform.base.BinaryTasks:org.gradle.platform.base.BinaryTasksCollection:org.gradle.platform.base.ComponentBinaries:org.gradle.platform.base.ComponentSpec:org.gradle.platform.base.ComponentSpecContainer:org.gradle.platform.base.ComponentType:org.gradle.platform.base.DependencySpec:org.gradle.platform.base.DependencySpecBuilder:org.gradle.platform.base.DependencySpecContainer:org.gradle.platform.base.GeneralComponentSpec:org.gradle.platform.base.InvalidModelException:org.gradle.platform.base.Library:org.gradle.platform.base.LibraryBinaryDependencySpec:org.gradle.platform.base.LibraryBinarySpec:org.gradle.platform.base.LibrarySpec:org.gradle.platform.base.ModelInstantiationException:org.gradle.platform.base.ModuleDependencySpec:org.gradle.platform.base.ModuleDependencySpecBuilder:org.gradle.platform.base.Platform:org.gradle.platform.base.PlatformAwareComponentSpec:org.gradle.platform.base.PlatformContainer:org.gradle.platform.base.ProjectDependencySpec:org.gradle.platform.base.ProjectDependencySpecBuilder:org.gradle.platform.base.SourceComponentSpec:org.gradle.platform.base.ToolChain:org.gradle.platform.base.ToolChainRegistry:org.gradle.platform.base.TransformationFileType:org.gradle.platform.base.TypeBuilder:org.gradle.platform.base.Variant:org.gradle.platform.base.VariantComponent:org.gradle.platform.base.VariantComponentSpec:org.gradle.platform.base.binary.BaseBinarySpec:org.gradle.platform.base.component.BaseComponentSpec:org.gradle.platform.base.plugins.BinaryBasePlugin:org.gradle.platform.base.plugins.ComponentBasePlugin:org.gradle.plugin.devel.GradlePluginDevelopmentExtension:org.gradle.plugin.devel.PluginDeclaration:org.gradle.plugin.devel.plugins.ExternalPluginValidationPlugin:org.gradle.plugin.devel.plugins.IvyPluginPublishingPlugin:org.gradle.plugin.devel.plugins.JavaGradlePluginPlugin:org.gradle.plugin.devel.plugins.MavenPluginPublishPlugin:org.gradle.plugin.devel.tasks.GeneratePluginDescriptors:org.gradle.plugin.devel.tasks.PluginUnderTestMetadata:org.gradle.plugin.devel.tasks.ValidatePlugins:org.gradle.plugin.management.PluginManagementSpec:org.gradle.plugin.management.PluginRequest:org.gradle.plugin.management.PluginResolutionStrategy:org.gradle.plugin.management.PluginResolveDetails:org.gradle.plugin.use.PluginDependenciesSpec:org.gradle.plugin.use.PluginDependency:org.gradle.plugin.use.PluginDependencySpec:org.gradle.plugin.use.PluginId:org.gradle.plugins.ear.Ear:org.gradle.plugins.ear.EarPlugin:org.gradle.plugins.ear.EarPluginConvention:org.gradle.plugins.ear.descriptor.DeploymentDescriptor:org.gradle.plugins.ear.descriptor.EarModule:org.gradle.plugins.ear.descriptor.EarSecurityRole:org.gradle.plugins.ear.descriptor.EarWebModule:org.gradle.plugins.ide.IdeWorkspace:org.gradle.plugins.ide.api.FileContentMerger:org.gradle.plugins.ide.api.GeneratorTask:org.gradle.plugins.ide.api.PropertiesFileContentMerger:org.gradle.plugins.ide.api.PropertiesGeneratorTask:org.gradle.plugins.ide.api.PropertyListGeneratorTask:org.gradle.plugins.ide.api.XmlFileContentMerger:org.gradle.plugins.ide.api.XmlGeneratorTask:org.gradle.plugins.ide.eclipse.EclipsePlugin:org.gradle.plugins.ide.eclipse.EclipseWtpPlugin:org.gradle.plugins.ide.eclipse.GenerateEclipseClasspath:org.gradle.plugins.ide.eclipse.GenerateEclipseJdt:org.gradle.plugins.ide.eclipse.GenerateEclipseProject:org.gradle.plugins.ide.eclipse.GenerateEclipseWtpComponent:org.gradle.plugins.ide.eclipse.GenerateEclipseWtpFacet:org.gradle.plugins.ide.idea.GenerateIdeaModule:org.gradle.plugins.ide.idea.GenerateIdeaProject:org.gradle.plugins.ide.idea.GenerateIdeaWorkspace:org.gradle.plugins.ide.idea.IdeaPlugin:org.gradle.plugins.signing.Sign:org.gradle.plugins.signing.SignOperation:org.gradle.plugins.signing.Signature:org.gradle.plugins.signing.SignatureSpec:org.gradle.plugins.signing.SigningExtension:org.gradle.plugins.signing.SigningPlugin:org.gradle.plugins.signing.signatory.Signatory:org.gradle.plugins.signing.signatory.SignatoryProvider:org.gradle.plugins.signing.signatory.SignatorySupport:org.gradle.plugins.signing.signatory.pgp.PgpKeyId:org.gradle.plugins.signing.signatory.pgp.PgpSignatory:org.gradle.plugins.signing.signatory.pgp.PgpSignatoryFactory:org.gradle.plugins.signing.signatory.pgp.PgpSignatoryProvider:org.gradle.plugins.signing.type.AbstractSignatureType:org.gradle.plugins.signing.type.AbstractSignatureTypeProvider:org.gradle.plugins.signing.type.BinarySignatureType:org.gradle.plugins.signing.type.DefaultSignatureTypeProvider:org.gradle.plugins.signing.type.SignatureType:org.gradle.plugins.signing.type.SignatureTypeProvider:org.gradle.plugins.signing.type.pgp.ArmoredSignatureType:org.gradle.process.BaseExecSpec:org.gradle.process.CommandLineArgumentProvider:org.gradle.process.ExecOperations:org.gradle.process.ExecResult:org.gradle.process.ExecSpec:org.gradle.process.JavaDebugOptions:org.gradle.process.JavaExecSpec:org.gradle.process.JavaForkOptions:org.gradle.process.ProcessForkOptions:org.gradle.swiftpm.Package:org.gradle.swiftpm.Product:org.gradle.swiftpm.plugins.SwiftPackageManagerExportPlugin:org.gradle.swiftpm.tasks.GenerateSwiftPackageManagerManifest:org.gradle.testing.base.TestSuite:org.gradle.testing.base.TestSuiteBinarySpec:org.gradle.testing.base.TestSuiteContainer:org.gradle.testing.base.TestSuiteSpec:org.gradle.testing.base.TestSuiteTarget:org.gradle.testing.base.TestSuiteTaskCollection:org.gradle.testing.base.TestingExtension:org.gradle.testing.base.plugins.TestSuiteBasePlugin:org.gradle.testing.base.plugins.TestingBasePlugin:org.gradle.testing.base.plugins.TestingModelBasePlugin:org.gradle.testing.jacoco.plugins.JacocoPlugin:org.gradle.testing.jacoco.plugins.JacocoPluginExtension:org.gradle.testing.jacoco.plugins.JacocoTaskExtension:org.gradle.testing.jacoco.tasks.JacocoBase:org.gradle.testing.jacoco.tasks.JacocoCoverageVerification:org.gradle.testing.jacoco.tasks.JacocoMerge:org.gradle.testing.jacoco.tasks.JacocoReport:org.gradle.testing.jacoco.tasks.JacocoReportBase:org.gradle.testing.jacoco.tasks.JacocoReportsContainer:org.gradle.testing.jacoco.tasks.rules.JacocoLimit:org.gradle.testing.jacoco.tasks.rules.JacocoViolationRule:org.gradle.testing.jacoco.tasks.rules.JacocoViolationRulesContainer:org.gradle.testkit.runner.BuildTask:org.gradle.testkit.runner.GradleRunner:org.gradle.testkit.runner.InvalidPluginMetadataException:org.gradle.testkit.runner.InvalidRunnerConfigurationException:org.gradle.testkit.runner.TaskOutcome:org.gradle.testkit.runner.UnexpectedBuildFailure:org.gradle.testkit.runner.UnexpectedBuildResultException:org.gradle.testkit.runner.UnexpectedBuildSuccess:org.gradle.testkit.runner.UnsupportedFeatureException:org.gradle.util.ClosureBackedAction:org.gradle.util.CollectionUtils:org.gradle.util.Configurable:org.gradle.util.ConfigureUtil:org.gradle.util.DistributionLocator:org.gradle.util.GFileUtils:org.gradle.util.GUtil:org.gradle.util.GradleVersion:org.gradle.util.NameMatcher:org.gradle.util.NameValidator:org.gradle.util.RelativePathUtil:org.gradle.util.SingleMessageLogger:org.gradle.util.TextUtil:org.gradle.util.VersionNumber:org.gradle.util.WrapUtil:org.gradle.vcs.SourceControl:org.gradle.vcs.VcsMapping:org.gradle.vcs.VcsMappings:org.gradle.vcs.VersionControlRepository:org.gradle.vcs.VersionControlSpec:org.gradle.vcs.git.GitVersionControlSpec:org.gradle.work.ChangeType:org.gradle.work.DisableCachingByDefault:org.gradle.work.FileChange:org.gradle.work.Incremental:org.gradle.work.InputChanges:org.gradle.work.NormalizeLineEndings:org.gradle.workers.ClassLoaderWorkerSpec:org.gradle.workers.ForkMode:org.gradle.workers.ForkingWorkerSpec:org.gradle.workers.IsolationMode:org.gradle.workers.ProcessWorkerSpec:org.gradle.workers.WorkAction:org.gradle.workers.WorkParameters:org.gradle.workers.WorkQueue:org.gradle.workers.WorkerConfiguration:org.gradle.workers.WorkerExecutionException:org.gradle.workers.WorkerExecutor:org.gradle.workers.WorkerSpec:org.gradle.kotlin.dsl.*:org.gradle.kotlin.dsl.plugins.dsl.*:java.util.concurrent.Callable:java.util.concurrent.TimeUnit:java.math.BigDecimal:java.math.BigInteger:java.io.File:javax.inject.Inject:gradle.kotlin.dsl.plugins._e0ed94d0f8df9e4d8b688b2a5791da66.*"
```

### PR DESCRIPTION
**Pull request by eskatos**
* Fixes #22091 

----
The old codepath is kept for folks using previous versions of the `kotlin-dsl` plugin.

This PR also opportunistically 
- removes now not needed test setup ignoring deprecations - not needed since the uprade to Kotlin 1.8,
- introduces `withGroovyBuilder { hasProperty(name) }` - needed in this PR's implementation.
- extends coverage for kotlin versions in `KotlinDslPluginGradlePluginCrossVersionSmokeTest`

----
This should be merged after
* https://github.com/gradle/gradle/pull/23485

which introduce a workaround for this in a test.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by hythloda — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

File: subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt [hunk 1]
```diff
@@ -815,4 +815,20 @@ class PrecompiledScriptPluginIntegrationTest : AbstractPluginIntegrationTest() {
...
         compileKotlin()
     }
+
+    @Test
+    fun `does not add extra task actions to kotlin compilation task`() {
+        assumeNonEmbeddedGradleExecuter()
+        withKotlinDslPlugin().appendText("""
+            gradle.taskGraph.whenReady {
+                val compileKotlinActions = allTasks.single { it.path == ":compileKotlin" }.actions.size
+                require(compileKotlinActions == 1) {
```
Comment (jbartok) [inline subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt:825]: Maybe use `check` instead? Probably `assert` would be best, but I guess it's not safe to assume assertions will always be enabled. `require` feels weird, and out of place.

**Review by jbartok — APPROVED** [review]

File: subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt (hunk 1 above)
Comment (eskatos) [reply subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt:825]: `require` is basically the equivalent of `assert` in Kotlin
We use often it in under-test build scripts.
