### PR TITLE
Remove unnecessary dependency data from TAPI task events

### LINKED ISSUE #28068: Gradle Tooling API takes significant time to deserialize task events for extra large projects
### Current Behavior

User reported that in Android Studio their project up-to-date build (15k tasks) takes 28s based on console output but then UI continues to update for another 30s.

I was investigating this issue from Android Studio side. Detailed tests and profiling showed that the bottleneck is deserialisation of  TAPI task events.

Example stacktrace from TAPI client:
```
"Connection worker Thread 2" #598 prio=4 os_prio=31 cpu=50512.07ms elapsed=208.09s tid=0x000000013f418200 nid=0x393db runnable  [0x00000002aefc4000]
   java.lang.Thread.State: RUNNABLE
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(java.base@17.0.9/Unknown Source)
        at java.io.ObjectStreamClass$FieldReflector.checkObjectFieldValueTypes(java.base@17.0.9/Unknown Source)
        at java.io.ObjectStreamClass.checkObjFieldValueTypes(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream$FieldValues.defaultCheckFieldValues(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readSerialData(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject0(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject(java.base@17.0.9/Unknown Source)
        at java.util.HashSet.readObject(java.base@17.0.9/Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor226.invoke(java.base@17.0.9/Unknown Source)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.9/Unknown Source)
        at java.lang.reflect.Method.invoke(java.base@17.0.9/Unknown Source)
        at java.io.ObjectStreamClass.invokeReadObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readSerialData(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject0(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream$FieldValues.<init>(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readSerialData(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject0(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject(java.base@17.0.9/Unknown Source)
        at java.util.HashSet.readObject(java.base@17.0.9/Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor226.invoke(java.base@17.0.9/Unknown Source)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.9/Unknown Source)
        at java.lang.reflect.Method.invoke(java.base@17.0.9/Unknown Source)
        at java.io.ObjectStreamClass.invokeReadObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readSerialData(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject0(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream$FieldValues.<init>(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readSerialData(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject0(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject(java.base@17.0.9/Unknown Source)
        at java.util.HashSet.readObject(java.base@17.0.9/Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor226.invoke(java.base@17.0.9/Unknown Source)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.9/Unknown Source)
        at java.lang.reflect.Method.invoke(java.base@17.0.9/Unknown Source)
        at java.io.ObjectStreamClass.invokeReadObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readSerialData(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject0(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream$FieldValues.<init>(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readSerialData(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject0(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject(java.base@17.0.9/Unknown Source)
        at java.util.HashSet.readObject(java.base@17.0.9/Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor226.invoke(java.base@17.0.9/Unknown Source)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.9/Unknown Source)
        at java.lang.reflect.Method.invoke(java.base@17.0.9/Unknown Source)
        at java.io.ObjectStreamClass.invokeReadObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readSerialData(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject0(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream$FieldValues.<init>(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readSerialData(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject0(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream$FieldValues.<init>(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readSerialData(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject0(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject(java.base@17.0.9/Unknown Source)
        at java.io.ObjectInputStream.readObject(java.base@17.0.9/Unknown Source)
        at org.gradle.internal.serialize.DefaultSerializer.read(DefaultSerializer.java:48)
        at org.gradle.launcher.daemon.protocol.DaemonMessageSerializer$BuildEventSerializer.read(DaemonMessageSerializer.java:202)
        at org.gradle.launcher.daemon.protocol.DaemonMessageSerializer$BuildEventSerializer.read(DaemonMessageSerializer.java:192)
        at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:164)
        at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:77)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:35)
        at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:233)
        at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:202)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:152)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:98)
        at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:30)
        at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:56)
        at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:224)
        at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:150)
        at org.gradle.tooling.internal.provider.DefaultConnection.getModel(DefaultConnection.java:149)
        at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:54)
        at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:38)
        at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:64)
        at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:49)
        at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:97)
        at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:89)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:143)
        at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
        at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:67)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.9/Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.9/Unknown Source)
        at java.lang.Thread.run(java.base@17.0.9/Unknown Source)
```

Apparently each task event contains full task dependency tree as `DefaultTaskDescriptor` instances contain their dependencies descriptors. Additionally default java serialization is used for TAPI events.

On the client side in `BuildProgressListenerAdapter#toTaskDescriptor` only first level of dependencies is used and they are replaced by cached versions of descriptors, thus restoring the full tree without using the full information from the event.
This means only direct task dependencies needed to be sent with each task event, trimming away everything below will significantly improve TAPI efficiency and fix this issue.

### Expected Behavior

Receiving TAPI Task events should not significantly slow down the build.

### Context (optional)

_No response_

### Steps to Reproduce

It can be easily reproduced with https://github.com/gavra0/android-extra-large-benchmark/tree/2022.9, 500 modules version. e.g. run build all in Android Studio twice for up-to-date build, this generates about 17s lag after 20s build time.

To avoid any impact from Android Studio or IntelliJ internals I managed to reproduce it on a trivial Tooling API client implementation that invokes a build task and only subscribes to task events.

To make it easier testing without Android Studio I also generated an simple Android project containing 500 copies of lib sub-projects.
It is important that there should be deep chains of dependencies between sub-projects so that tasks dependency tree grows in size.

### Gradle version

8.6

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by M-Lazeba**
Deserialization of descriptors dependency tree can take significant time for big projects. Full tree is sent with each event but only first level of dependencies is used on the client in BuildProgressListenerAdapter#toTaskDescriptor, so this can be fixed by trimming data that will not be used.

Fixes #28068

### Context
Extra large projects have big dependency trees for their tasks and IDE takes seconds, some times longer than the build itself, to receive all events.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/daemon/protocol/DaemonMessageSerializer.java [hunk 1]
```diff
@@ -194,7 +200,40 @@ private static class BuildEventSerializer implements Serializer<BuildEvent> {
 
         @Override
         public void write(Encoder encoder, BuildEvent buildEvent) throws Exception {
-            payloadSerializer.write(encoder, buildEvent.getPayload());
+            if (buildEvent.getPayload() instanceof DefaultTaskStartedProgressEvent) {
```
Comment (adammurdoch) [inline platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/daemon/protocol/DaemonMessageSerializer.java:203]: I think it would be better to do the truncation where the objects are created, rather than making a copy here. This avoids baking knowledge of how the descriptor will be used into this serializer, which really should just send whatever data it is given, and also avoids generating a whole bunch of extra garbage in creating the copies.

To do this, I would probably change `OperationDependenciesResolver` to do the truncation, so that we also solve the same problem for the events sent for artifact transforms (there can be many more transforms than tasks).

**Review by adammurdoch — CHANGES_REQUESTED** [review]

File: platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/daemon/protocol/DaemonMessageSerializer.java (hunk 1 above)
Comment (M-Lazeba) [reply platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/daemon/protocol/DaemonMessageSerializer.java:203]: Well, my reasoning is, as I do not know all the internal details of Gradle, that this full information might actually be used somewhere else.
I am only sure that sending all this to the client is 1) inefficient and 2) unnecessary as there it is restored from cached descriptors. That's why I considered it to be a serialization problem.

Thanks for the pointer, I will take a look! If my considerations above prove to be invalid I'll happily move the fix, I don't really like the current 'hack' fix as well.

Comment (M-Lazeba) [reply platforms/core-runtime/launcher/src/main/java/org/gradle/launcher/daemon/protocol/DaemonMessageSerializer.java]: Agreed, it is indeed much more natural to change in the suggested area.
Though I think the most natural is to create two versions of descriptors where we create them and cache the one without dependencies. Please take a look.

**Comment by M-Lazeba** [comment]
No functionality change.
Cross-version tests (TaskDependenciesCrossVersionSpec) should ensure that the transitive dependencies are still available to the tooling client.

**Comment by Badfoob** [comment]
> Deserialization of descriptors dependency tree can take significant time for big projects. Full tree is sent with each event but only first level of dependencies is used on the client in BuildProgressListenerAdapter#toTaskDescriptor, so this can be fixed by trimming data that will not be used.
> 
> Fixes #28068
> 
> ### Context
> Extra large projects have big dependency trees for their tasks and IDE takes seconds, some times longer than the build itself, to receive all events.
> 
> ### Contributor Checklist
> * [x]  [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
> * [x]  Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
> * [x]  Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
> * [x]  Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
> * [ ]  Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
> * [ ]  Provide unit tests (under `<subproject>/src/test`) to verify logic
> * [x]  Update User Guide, DSL Reference, and Javadoc for public-facing changes
> * [x]  Ensure that tests pass sanity check: `./gradlew sanityCheck`
> * [x]  Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`
> 
> ### Reviewing cheatsheet
> Before merging the PR, comments starting with
> 
> * ❌ ❓**must** be fixed
> * 🤔 💅 **should** be fixed
> * 💭 **may** be fixed
> * 🎉 celebrate happy things

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test this
