### PR TITLE
Force non-incremental execution after failed load from build cache

### LINKED ISSUE #8629: UnrecoverableUnpackingException is hidden by DefaultBuildCacheController
We have a special exception for when we fail to clean up the outputs after a failed unpack operation. This exception is supposed to signal a build failure to the `CacheStep`. However, it is [caught and wrapped](https://github.com/gradle/gradle/blob/b76473aa28015e53680f21b16fcba1067621153c/subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/DefaultBuildCacheController.java#L117) in a `GradleException` by the `DefaultBuildCacheController`, so it is never actually handled correctly.

### PR DESCRIPTION
**Pull request by lptr**
Previously when handling a failed load we did clean the outputs of the work, but ended up allowing incremental execution nevertheless. This is now fixed.

Fixes #8629.

### CODE REVIEW

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java [hunk 1]
```diff
@@ -17,121 +17,148 @@
...
-                        public void afterLoadFailedAndWasCleanedUp(Throwable error) {
-                            work.outputsRemovedAfterFailureToLoadFromCache();
-                        }
-                    })
-            );
-        } catch (UnrecoverableUnpackingException e) {
-            // We didn't manage to recover from the unpacking error, there might be leftover
-            // garbage among the task's outputs, thus we must fail the build
-            throw e;
+            return buildCache.load(commandFactory.createLoad(cacheKey, work))
```
Comment (wolfs) [inline subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: This looks a little bit strange. It seems like you actually have a `Try<Optional<LoadMetaData>>` and then want to turn it around by caching the exception yourself instead of using `Try.ofFailable`.

And I think for the `load` method, `Try<Optional<>>` is the right return type, since you always try to load the result.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java [hunk 2]
```diff
@@ -17,121 +17,148 @@
...
+                        FileUtils.forceDelete(root);
+                    }
+                }
+            } catch (IOException ex) {
+                throw new UncheckedIOException(String.format("Failed to clean up files for tree '%s' of %s: %s", name, work.getDisplayName(), root), ex);
+            }
+        });
+    }
+
+    private CurrentSnapshotResult executeWithCache(CacheHandler cacheHandler, IncrementalChangesContext context) {
```
Comment (wolfs) [inline subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: The method name `executeWithCache` confused me a little bit. How about `executeAndStoreInCache`?

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java (hunk 1 above)
Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: It depends on how you want to handle this. Originally we only handled unpack errors, and this is trying to emulate that behavior, i.e. you can only have a failure if you actually tried to load something.

We could change this, and turn this around (I had an implementation like that before), but I wouldn't do it until we simplify the whole build cache logic in 6.0.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java (hunk 2 above)
Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: Alright.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java (hunk 1 above)
Comment (wolfs) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: IIUC, the code is currently catching any error from the `load` method. We don't know if the failure happened while unpacking or in some other point when loading, right?

The `load` method always tries to load and we capture the failure of loading.

Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: You're right, I was thinking of a previous version of the implementation. By turning this logic inside out I actually managed to simplify the code a little. \o/

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java [hunk 3]
```diff
@@ -62,13 +62,14 @@ public CurrentSnapshotResult execute(IncrementalChangesContext context) {
...
-        CacheHandler cacheHandler = context.getWork().createCacheHandler();
+        UnitOfWork work = context.getWork();
+        CacheHandler cacheHandler = work.createCacheHandler();
         return cacheHandler
-            .load(cacheKey -> load(context.getWork(), cacheKey))
-            .map(cacheHit -> cacheHit
-                .map(loadResult -> {
-                    OriginMetadata originMetadata = loadResult.getOriginMetadata();
-                    ImmutableSortedMap<String, CurrentFileCollectionFingerprint> finalOutputs = loadResult.getResultingSnapshots();
+            .load(cacheKey -> Try.ofFailable(() -> buildCache.load(commandFactory.createLoad(cacheKey, work))))
```
Comment (wolfs) [inline subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: I wonder if this would be better:
```java
Try.ofFailable(() -> cacheHandler.load(cacheKey ->
    buildCache.load(commandFactory.createLoad(cacheKey, work))
))
```

Then we don't need to have the `Try` in the signature of the `CacheHandler.load` command.

On the other hand, having the try in the function which loads makes clear that we handle a failure to load.

WDYT?

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java [hunk 4]
```diff
@@ -17,119 +17,141 @@
...
+                    work.getDisplayName(), loadFailure);
+                cleanupTreesAfterLoadFailure(work);
+
+                return executeAndStoreInCache(cacheHandler, new IncrementalChangesContext() {
                     @Override
-                    public Try<ExecutionOutcome> getOutcome() {
-                        return Try.successful(ExecutionOutcome.FROM_CACHE);
+                    public Optional<ExecutionStateChanges> getChanges() {
+                        // Clear change information to avoid incremental execution after failed load
+                        return Optional.empty();
```
Comment (wolfs) [inline subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: ❌ Doesn't clearing the changes mean something else? I thought it meant we don't track the inputs.
I think we need to return `RebuildExecutionStateChanges` here.

An incremental task would fail when the changes are empty.

File: subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/command/BuildCacheCommandFactory.java [hunk 5]
```diff
@@ -178,32 +162,14 @@ public OriginMetadata getOriginMetadata() {
         private void cleanLocalState() {
             entity.visitLocalState(localStateFile -> {
                 try {
-                    remove(localStateFile);
+                    if (localStateFile.exists()) {
+                        FileUtils.forceDelete(localStateFile);
```
Comment (wolfs) [inline subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/command/BuildCacheCommandFactory.java]: We are now removing the directory as well, and not only cleaning it. Is that expected for `localState`?

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java (hunk 3 above)
Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: I think what you recommend is a better solution, and it still manages to capture that it's the load that's fallible.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java (hunk 4 above)
Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: Ah, damn, fixed.

File: subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/command/BuildCacheCommandFactory.java (hunk 5 above)
Comment (lptr) [reply subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/command/BuildCacheCommandFactory.java]: Moved all the behavior to `CacheStep` now, and are removing things the same way as we did before.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java [hunk 6]
```diff
@@ -128,18 +133,20 @@ public UnitOfWork getWork() {
...
-                        FileUtils.cleanDirectory(root);
-                    } else {
-                        FileUtils.forceDelete(root);
+    private static void cleanOutputsAfterLoadFailure(UnitOfWork work) {
+        work.visitOutputProperties((name, type, roots) -> {
+            for (File root : roots) {
+                try {
+                    if (root.exists()) {
+                        if (root.isDirectory()) {
+                            FileUtils.cleanDirectory(root);
```
Comment (wolfs) [inline subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: I think we have a cleaner now which has a better error message when it fails to clean up some file. Should we use this maybe?

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java [hunk 7]
```diff
@@ -128,18 +133,20 @@ public UnitOfWork getWork() {
...
-    private static void cleanupTreesAfterLoadFailure(UnitOfWork work) {
-        work.visitOutputTrees((name, type, root) -> {
-            try {
-                if (root.exists()) {
-                    if (root.isDirectory()) {
-                        FileUtils.cleanDirectory(root);
-                    } else {
-                        FileUtils.forceDelete(root);
+    private static void cleanOutputsAfterLoadFailure(UnitOfWork work) {
+        work.visitOutputProperties((name, type, roots) -> {
```
Comment (wolfs) [inline subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: Why don't you visit the output trees? That seems to be better for cacheable tasks.

Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: I'd like to use the `UnitOfWork` here, and basically divorce it from `CacheableEntity` eventually. They should map to the same properties in the end anyway.

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java (hunk 6 above)
Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: What new cleaner do you have in mind?

**Comment by lptr** [comment]
@wolfs I re-started the build, can you please merge this if it passes?

File: subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java (hunk 6 above)
Comment (wolfs) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: This one: https://github.com/gradle/gradle/blob/21925d22551636a6578cc343118a41e91bc9bb75/subprojects/core/src/main/java/org/gradle/api/internal/file/delete/Deleter.java

Comment (lptr) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: Would you mind opening an issue about this?

Comment (wolfs) [reply subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java]: See https://github.com/gradle/gradle/issues/8829.
