### PR TITLE
Disallow both --module-source-path and -sourcepath

### LINKED ISSUE #2537: gradle 4.0.1 sets javac --source-path option which is not compatible with --module-source-path (JDK9)
gradle 4.0.1 appears to set the --source-path when passing flags to javac.
Since JDK 9 supports the mutually exclusive --module-source-path flag this can lead to
failing builds.

The JavaFX component of JDK 9 has been unable to upgrade the version of gradle it uses to build
JDK 9 since before 3.4 - which seems to be the approximate release that introduced this, since
3.2 works.

### Expected Behavior
For gradle to support JDK 9 and later it needs to handle the --module-source-path option
in some way. Whether it is by not providing the conflicting --source-path option, at least
if the gradle build script is already specifying --module-source-path or by
specifying --module-source-path in some gradle aware way.

### Current Behavior
Build fails with
 javac: cannot specify both --source-path and --module-source-path 
### Context
This is a blocker for using gradle with JDK 9 and above.

### Steps to Reproduce (for bugs)
Download the javafx source from hg.openjdk.java.net/openjfx/9 and try to build
it with current gradle.
Also see https://bugs.openjdk.java.net/browse/JDK-8177778

### PR DESCRIPTION
**Pull request by eljobe**
Java 9 introduces a `--module-source-path` option which is mutually
exclusive with `-sourcepath` or `--source-path`. If they are both
provided, the sourcepath should be stripped and the
`--module-source-path` should remain.

If both have been specified explicitly by the user either as a
`optiions.compilerArgs` argument or, in the case of `sourcepath` as
the `options.sourcepath` property, then a warning should also be
emitted to let the user know that they did something wrong.

Fixes #2537

### CODE REVIEW

File: subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy [hunk 1]
```diff
@@ -670,6 +670,51 @@ class JavaCompileIntegrationTest extends AbstractIntegrationSpec {
         file("build/classes/java/main/io/example/Example.class").exists()
     }
 
+    @Requires(adhoc = {AvailableJavaHomes.getJdk(VERSION_1_9)})
```
Comment (jjohannes) [inline subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy]: Maybe also add `@Issue("https://github.com/gradle/gradle/issues/2537")`

For the Requires annotation: I wonder if it would be better to annotate it with `TestPrecondition.JDK9_OR_LATER`. Now the test will run in all different environments on CI (Java7, Java8, Java9, ...) but will always use the Java9 version it picks itself. So effectively it will be the same environment every time. Which kind of also defeats the point of defining the Java9 version via the `JAVA_9` env variable.

Comment (eljobe) [inline subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy]: Done

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java [hunk 2]
```diff
@@ -191,19 +194,26 @@ private void addUserProvidedArgs(List<String> compilerArgs) {
...
+    private String extractSourcepathFrom(List<String> compilerArgs, boolean silently) {
         Iterator<String> argIterator = compilerArgs.iterator();
         String userProvidedSourcepath = "";
         while (argIterator.hasNext()) {
             String current = argIterator.next();
             if (current.equals("-sourcepath") || current.equals("--source-path")) {
-                DeprecationLogger.nagUserOfDeprecated(
-                    "Specifying the source path in the CompilerOptions compilerArgs property",
-                    "Instead, use the CompilerOptions sourcepath property directly");
+                if (silently) {
```
Comment (eljobe) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java]: Done

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java [hunk 3]
```diff
@@ -191,19 +194,26 @@ private void addUserProvidedArgs(List<String> compilerArgs) {
             return;
         }
         if (compilerArgs != null) {
+            if (compilerArgs.contains("--module-source-path")) {
+                if (!extractSourcepathFrom(args, true).isEmpty()) {
+                    LOGGER.warn("You specified both --module-source-path and a sourcepath. These options are mutually exclusive. Removing sourcepath.");
```
Comment (eljobe) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java]: Done

**Comment by eljobe** [comment]
@jjohannes Changes made.
