### PR TITLE
Fix memory leak and concurrency issue in WeakIdentityHashMap

### LINKED ISSUE #35046: Potential Memory Leaks and Logical Inconsistencies in WeakIdentityHashMap Implementation
### Current Behavior

# Potential Memory Leaks and Logical Inconsistencies in WeakIdentityHashMap Implementation  

## Environment  
- Gradle Version: 8.2+  
- JDK Version: 11+ (reproduced on multiple versions)  

## Description  
The `WeakIdentityHashMap`(https://github.com/gradle/gradle/blob/master/platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/adapter/WeakIdentityHashMap.java) implementation (used as a cache for `ViewGraphDetails` in `ProtocolToModelAdapter`) contains several critical issues that may lead to memory leaks, incorrect cache behavior, and thread safety problems. These issues violate the core design goals of a weak-reference-based identity map (automatic cleanup of stale entries and reliable identity-based key comparison).  

### 1. Missing ReferenceQueue Leads to Permanent Memory Leaks  
The `WeakKey` class extends `WeakReference` but is not associated with a `ReferenceQueue`. When a key (referent) is garbage-collected, the corresponding `WeakKey` instance remains in the underlying `HashMap` as a stale entry. Since `HashMap` holds strong references to its keys, these stale `WeakKey` entries (and their associated values) are never cleaned up, causing memory leaks—especially problematic in long-running Gradle daemon processes.  

This implementation is critical for `ViewGraphDetails` caching in `ProtocolToModelAdapter`, and addressing these issues will improve Gradle’s memory management and cache reliability.  

here is memory dump on Gradle 8.10 
Image

### Expected Behavior

Will there be no memory leaks。

### Context (optional)

_No response_

### Self-contained Reproducer Project

`java
// Reproducer test class
public class WeakIdentityHashMapReproducer {
    public static void main(String[] args) throws InterruptedException {
        testMemoryLeak();
        testEqualsHashCodeInconsistency();
        testThreadSafetyIssue();
    }

    // Test 1: Verify memory leak (entries not cleaned after key GC)
    private static void testMemoryLeak() {
        WeakIdentityHashMap<Object, String> map = new WeakIdentityHashMap<>();
        Object key = new Object(); // Temporary key object

        // Add entry
        map.put(key, "value");
        System.out.println("Test 1 - Size after addition: " + map.size()); // Expected: 1

        // Remove strong reference and trigger GC
        key = null;
        System.gc(); // Hint GC to collect the key object
        try {
            Thread.sleep(1000); // Wait for GC to complete
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        // Check if entries were cleaned (core memory leak indicator)
        System.out.println("Test 1 - Size after GC: " + map.size()); // Actual: 1 (not cleaned), Expected: 0
        System.out.println("Test 1 - Memory leak verification: " + (map.size() == 1 ? "Leak exists" : "Normal"));
        System.out.println("----------------------------------------");
    }

    // Test 2: Verify equals() and hashCode() inconsistency
    private static void testEqualsHashCodeInconsistency() {
        WeakIdentityHashMap<Object, String> map = new WeakIdentityHashMap<>();
        Object key1 = new Object();
        Object key2 = new Object();

        // Add two different keys
        map.put(key1, "value1");
        map.put(key2, "value2");

        // Save corresponding WeakKeys (obtained via keySet)
        WeakIdentityHashMap.WeakKey<Object> weakKey1 = null;
        WeakIdentityHashMap.WeakKey<Object> weakKey2 = null;
        for (WeakIdentityHashMap.WeakKey<Object> key : map.keySet()) {
            if (key.get() == key1) weakKey1 = key;
            if (key.get() == key2) weakKey2 = key;
        }

        // Remove strong references and trigger GC (make WeakKey referents null)
        key1 = null;
        key2 = null;
        System.gc();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        // Verify: When both WeakKeys have null referents, equals() returns true but hashCodes differ
        boolean equals = weakKey1.equals(weakKey2);
        boolean hashCodeEqual = weakKey1.hashCode() == weakKey2.hashCode();
        System.out.println("Test 2 - equals() result for two stale WeakKeys: " + equals); // Actual: true (incorrect)
        System.out.println("Test 2 - Are hashCodes equal for stale WeakKeys: " + hashCodeEqual); // Actual: false (incorrect)
        System.out.println("Test 2 - equals() vs hashCode() inconsistency: " + (equals && !hashCodeEqual ? "Issue exists" : "Normal"));
        System.out.println("----------------------------------------");
    }

    // Test 3: Verify thread safety issues (inconsistencies under concurrent access)
    private static void testThreadSafetyIssue() throws InterruptedException {
        WeakIdentityHashMap<Object, Integer> map = new WeakIdentityHashMap<>();
        Object sharedKey = new Object();
        int threadCount = 10;
        CountDownLatch latch = new CountDownLatch(threadCount);
        int[] result = new int[1]; // Used to store final result

        // Concurrent calls to computeIfAbsent from multiple threads
        for (int i = 0; i < threadCount; i++) {
            new Thread(() -> {
                try {
                    map.computeIfAbsent(sharedKey, () -> {
                        // Simulate computation time to increase concurrency conflicts
                        try {
                            Thread.sleep(10);
                        } catch (InterruptedException e) {
                            Thread.currentThread().interrupt();
                        }
                        return 1; // Expected: Only computed once regardless of thread count
                    });
                } finally {
                    latch.countDown();
                }
            }).start();
        }

        latch.await();
        // Check actual value (should be 1 normally; >1 indicates thread safety issues)
        result[0] = map.get(sharedKey);
        System.out.println("Test 3 - Result of concurrent computeIfAbsent: " + result[0]); // May incorrectly show >1
        System.out.println("Test 3 - Thread safety verification: " + (result[0] == 1 ? "Normal" : "Concurrency issue exists"));
    }
}
`

### Gradle version

8.2+

### Build scan URL (optional)

_No response_

### Your Environment (optional)

Java 11

### PR DESCRIPTION
**Pull request by smplio**
### Context
This PR fixes all three issues stated in #35046:
1. Memory leak fixed by inroducing ReferenceQueue, that is used in constructors of all the WeakKeys that go into the hashMap
2. equals() inconsistency on WeakKeys, whose referents were dereferenced, is fixed by using Object.equals() on WeakKeys when both of their referents are null
3. Potential concurrency issues are fixed by using ConcurrentHashMap instead of HashMap

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ov7a** [comment]
Thank you for your proposed contribution!

This PR has a valid DCO and tests. The relevant team for this area will confirm the implementation choices.

**Comment by eskatos** [comment]
@bot-gradle test RFN without PTS

**Comment by eskatos** [comment]
@bot-gradle test ACT APT

File: platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/adapter/WeakIdentityHashMap.java [hunk 1]
```diff
@@ -16,11 +16,13 @@
 
 package org.gradle.tooling.internal.adapter;
 
+import org.jetbrains.annotations.VisibleForTesting;
```
Comment (reinsch82) [inline platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/adapter/WeakIdentityHashMap.java]: ❌ 
```suggestion
import com.google.common.annotations.VisibleForTesting;
```

**Review by reinsch82 — APPROVED** [review]
