### PR TITLE
Stop throwing exceptions from isPresent() of the Provider.zip() result

### LINKED ISSUE #17644: Provider.zip throws exception on isPresent call when one or both values are missing
### Expected Behavior
If either the `left` or `right` parameters of `Provider.zip` are missing, a call to the zipped result's `isPresent()` method should simply return `false`.

The Javadoc doesn't make it clear what the intended behaviour is here, including whether or not the `combiner` would be called if one of the values is missing but the other is present. It would be great to have that clarified.

### Current Behavior

Calling `Provider.isPresent()` on the zipped provider will throw an `InvalidUserDataException` due to one of the upstream values being missing:

```
org.gradle.api.InvalidUserDataException: Provider has no value: property(java.lang.String, undefined)
	at org.gradle.api.internal.provider.BiProvider.assertHasValue(BiProvider.java:56)
	at org.gradle.api.internal.provider.BiProvider.calculateOwnValue(BiProvider.java:50)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculatePresence(AbstractMinimalProvider.java:79)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.isPresent(AbstractMinimalProvider.java:74)
	at org.spongepowered.gradle.vanilla.TestProviderZip.providerShouldReturnNotPresent(TestProviderZip.java:23)
```

### Context

I'm trying to produce a result based on multiple inputs, and attempting to make sure any necessary dependency information is passed through correctly.

### Steps to Reproduce 

This can be reproduced with a simple test case:

```java
    @Test
    void providerShouldReturnNotPresent() {
        final Project project = ProjectBuilder.builder().build();
        final Property<String> a = project.getObjects().property(String.class);
        final Property<String> b = project.getObjects().property(String.class);
        final Provider<String> zipped = a.zip(b, (valA, valB) -> valA + ' ' + valB);

        a.set("present");

        // a is present, b is not
/*23*/  assertFalse(zipped.isPresent()); // ERROR: This throws an InvalidUserDataException rather than just returning false
    }
```

### Your Environment

Build scan URL: n/a, run in a test environment with Gradle 6.9

### PR DESCRIPTION
**Pull request by mlopatkin**
As a bonus, this CL also adds nicer error messages if long chains of
named properties are used as zip() arguments.

Fixes #17644

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this

File: subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderIntegrationTest.groovy [hunk 1]
```diff
@@ -245,21 +246,31 @@ class ProviderIntegrationTest extends AbstractIntegrationSpec {
...
+            tasks.register("run", MyTask)
         """
 
         when:
         fails 'run'
 
         then:
-        failure.assertHasErrorOutput("Provider has no value: property(java.lang.String, undefined)")
+        failure.assertHasErrorOutput("""
+            > Cannot query the value of this provider because it has no value available.
```
Comment (bamboo) [inline subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderIntegrationTest.groovy:271]: Nice! 👍

File: subprojects/model-core/src/main/java/org/gradle/api/internal/provider/BiProvider.java [hunk 2]
```diff
@@ -46,16 +45,15 @@ private boolean isChangingValue(ProviderInternal<?> provider) {
...
-        Value<? extends A> lv = assertHasValue(left.calculateValue(consumer), left);
-        Value<? extends B> rv = assertHasValue(right.calculateValue(consumer), right);
-        return Value.of(combiner.apply(lv.get(), rv.get()));
-    }
-
-    private <T> Value<? extends T> assertHasValue(Value<? extends T> value, ProviderInternal<?> provider) {
-        if (value.isMissing()) {
-            throw new InvalidUserDataException("Provider has no value: " + provider);
+        Value<? extends A> lv = left.calculateValue(consumer);
+        Value<? extends B> rv = right.calculateValue(consumer);
```
Comment (bamboo) [inline subprojects/model-core/src/main/java/org/gradle/api/internal/provider/BiProvider.java:49]: I think it would be best to avoid the `right.calculateValue` call when the left side is missing.

Comment (mlopatkin) [reply subprojects/model-core/src/main/java/org/gradle/api/internal/provider/BiProvider.java:49]: Nice catch, thanks!

**Review by bamboo — APPROVED** [review]
👍

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
@bot-gradle test and merge
