### PR TITLE
Don't stop searching early for class matches

### LINKED ISSUE #36544: Excluded tests in a suite are no longer being run
### Current Behavior

When using test suites, you can exclude the tests by filtering in the test task to avoid the test being run twice.

With Gradle 9.3.x, the test is no longer run when you exclude it, so you have to choose between running it twice or not running it.

The behaviour is a little different depending on whether you're using JUnit Jupiter or JUnit Vintage:
* With JUnit4, the excluded test is just non being run.
* With JUnit5/6, the test suite fails because it doesn't contain any tests.

### Expected Behavior

I'd expect test suites and exclusion filters to work like in previous versions of Gradle.

### Context (optional)

_No response_

### Self-contained Reproducer Project

https://github.com/ulrikls/gradle-junit4

### Gradle version

9.3.1

### Gradle version that used to work

9.2.1

### Build scan URL (optional)

https://scans.gradle.com/s/f7e5tc2ck3tqg

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #36544

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/jvm/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/AbstractJUnitSuitesIntegrationTest.groovy [hunk 1]
```diff
@@ -85,4 +86,53 @@ abstract class AbstractJUnitSuitesIntegrationTest extends AbstractTestingMultiVe
...
+
+        when:
+        executer.withTasks('test').run()
+
+        then:
+        GenericHtmlTestExecutionResult result = resultsFor()
+        result.assertTestPathsExecuted(
+            ':org.gradle.SomeTestSuite:org.gradle.TestRunBySuite:ok'
+        )
+        result.testPath(":org.gradle.SomeTestSuite:org.gradle.TestRunBySuite:ok").onlyRoot().assertHasResult(TestResult.ResultType.SUCCESS)
```
Comment (tresat) [inline platforms/jvm/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/AbstractJUnitSuitesIntegrationTest.groovy:140]: 💭 I know we have other tests for it, but this will probably be clearer to readers if it also asserted that the excluded test was not run outside of the suite.

**Review by tresat — APPROVED** [review]

File: platforms/jvm/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/AbstractJUnitSuitesIntegrationTest.groovy (hunk 1 above)
Comment (octylFractal) [reply platforms/jvm/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/AbstractJUnitSuitesIntegrationTest.groovy:140]: I added that.
