### PR TITLE
Use Files.setLastModifiedTime to touch files

### LINKED ISSUE #6971: Cache cleanup fails when gc.properties is owned by different user
Originally reported in https://github.com/nebula-plugins/gradle-nebula-integration/issues/36.

### PR DESCRIPTION
**Pull request by marcphilipp**
While, `File.setLastModified` always uses `utimes` on Unix,
`Files.setLastModifiedTime` uses `futimes`, if available, which seems to
be able to set the timestamp for writable files owned by another user.

Resolves #6971.

### CODE REVIEW

File: subprojects/resources/src/main/java/org/gradle/internal/resource/local/ModificationTimeFileAccessTimeJournal.java [hunk 1]
```diff
@@ -17,11 +17,17 @@
...
+import java.nio.file.Files;
+import java.nio.file.attribute.FileTime;
 
 public class ModificationTimeFileAccessTimeJournal implements FileAccessTimeJournal {
     @Override
     public void setLastAccessTime(File file, long millis) {
-        file.setLastModified(millis);
+        try {
+            Files.setLastModifiedTime(file.toPath(), FileTime.fromMillis(millis));
+        } catch (IOException ignore) {
```
Comment (oehme) [inline subprojects/resources/src/main/java/org/gradle/internal/resource/local/ModificationTimeFileAccessTimeJournal.java]: Maybe log at debug level so we know it's happening when analysing a problem?

Comment (marcphilipp) [reply subprojects/resources/src/main/java/org/gradle/internal/resource/local/ModificationTimeFileAccessTimeJournal.java]: Good point! Done in 9c22aac.

**Comment by rpalcolea** [comment]
Hi @marcphilipp , I saw that this is part of 5.0 M1. 

Are there any plans to add this fix to `4.10.x`? 

Thanks for the quick fix on this

**Comment by marcphilipp** [comment]
I'm afraid not. There are currently no plans to release another `4.10.x` version.

**Comment by rpalcolea** [comment]
Oh ok! good to know, thanks again for the fix!
