### PR TITLE
Failing test for #9882

### LINKED ISSUE #9882: Chain of transitives aligned by same platform can lead to broken resolution
For a set of dependencies
```
start:start:1.0 -> org:foo:1.0

org:foo:1.0 -> org:bar:1.0
org:foo:1.1 -> org:bar:1.1
```

If we align the `org` group with a virtual platform, constrain that virtual platform to require `1.1`, and depend on `start:start:1.0`, this situation produces a broken resolution graph in 5.5-rc2 and higher (git bisected this behaviour to https://github.com/gradle/gradle/commit/360949f7e785578195c7fe7e4b6ca2dc566d55c5).

### Expected Behavior

The above situation should resolve to
```
start:start:1.0
\--- org:foo:1.0 -> 1.1
     \--- org:bar:1.1
```

### Current Behavior

It resolves to
```
start:start:1.0
\--- org:foo:1.0 -> 1.1
```

completely losing `foo`'s dependency on `bar`.

### Context
This broke an internal project.

### Steps to Reproduce 

Failing integration test to come shortly.

### Your Environment

* Passing test on commit prior to broken one (https://github.com/gradle/gradle/commit/1adc86b9e7741874a6c9af7949e9e9de4450c77e): https://scans.gradle.com/s/rbawzbecv4vzc/tests
* Failing test on broken commit: https://scans.gradle.com/s/oc4wrrxvfe6io/tests/jguar37wvgdu4-q36tywqagqzy2

### PR DESCRIPTION
**Pull request by dansanduleac**
This is a failing test that exhibits #9882

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by ljacomet** [comment]
@dansanduleac Thanks for the report and test case!
I have pushed a commit that fixes the problem. Would be awesome if you could confirm that fixes the issue in your project?

@melix Because we special case constraints from virtual platforms in `EdgeState#calculateTargetConfigurations`, we can't defer selection for those, so I added a check for that when reporting on pending dependencies activation.

**Comment by dansanduleac** [comment]
amazing! checking now

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/PendingDependencies.java [hunk 1]
```diff
@@ -65,4 +65,13 @@ void decreaseHardEdgeCount() {
         assert hardEdges > 0 : "Cannot remove a hard edge when none recorded";
         hardEdges--;
     }
+
+    public boolean shouldReportActivatePending() {
+        for (NodeState affectedComponent : affectedComponents) {
```
Comment (melix) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/PendingDependencies.java]: :o: let's see but I think this can have a significant impact on performance. You could precompute this flag when affected components are registered.

Comment (ljacomet) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/PendingDependencies.java]: Good point, let me change that.

**Comment by ljacomet** [comment]
@dansanduleac Sorry, I just forced push this branch, reflex based on handling my own branches.

**Comment by ljacomet** [comment]
So there is something else broken that this PR does not fix? Or this PR breaks something else?
Asking to be sure 😉

**Comment by melix** [comment]
One possibility is that the missing dependencies come from _exclusions_ that were missed before.

**Comment by dansanduleac** [comment]
There is something else broken that this PR does not fix. Happy to put that into another issue once I bisect it, but I thought it might be related, as it looks similar in that there is a resolved dep which is missing some transitives.

**Comment by ljacomet** [comment]
Consider filing a different issue, but first try to see if this is not indeed caused by the fixes made to exclude processing for Gradle 5.5

**Comment by dansanduleac** [comment]
@melix you are actually right, just checked and there were some exclusions in the ! good spot
```gradle
    implementation 'io.undertow:undertow-servlet', {
        // Use javax.servlet:javax.servlet-api instead
        exclude group: 'org.jboss.spec.javax.servlet', module: 'jboss-servlet-api_4.0_spec'
        exclude group: 'org.jboss.spec.javax.annotation', module: 'jboss-annotations-api_1.2_spec'
    }
```

However, the exclusion only shows up in the library dependency that required the higher `2.0.22.Final`.
When is the exclusion meant to be picked up? I thought that if at least one incoming edge into a given node doesn't exclude X, then X would still show up as a transitive of that node.

**Comment by melix** [comment]
> When is the exclusion meant to be picked up? I thought that if at least one incoming edge into a given node doesn't exclude X, then X would still show up as a transitive of that node.

No, in Gradle, _all paths_ leading to a dependency must be excluded in order for a dependency to be excluded.  (Shameless plug, we [explain this in the webinar](https://gradle.com/blog/dependency-management-part-2-handling-conflicts/).

**Comment by dansanduleac** [comment]
@melix Yep, that was my understanding too.
And I think I just confused myself, as one of the "dependencies" was actually just another constraint, so the behaviour as you described is in fact correct.
Please can you hotfix 5.5 with this? :)
