### PR TITLE
Ignore failing test with vfs retention enabled

### LINKED ISSUE #12134: The `clean` task does not report changes to VFS
The `CachedPathSensitivityIntegrationTest` tests fail on Windows (and the failure is masked by a VFS drop (see https://github.com/gradle/gradle/issues/11836#issuecomment-582619833) on macOS) because the `clean` builds in the middle of the tests do not properly report changes to the VFS.

---
cc: @gradle/build-cache

### PR DESCRIPTION
**Pull request by wolfs**
Allow to easily ignore test which fail when vfs retention is enabled.

Fixes #12134.

### CODE REVIEW

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedPathSensitivityIntegrationTest.groovy [hunk 1]
```diff
@@ -24,11 +24,7 @@ import spock.lang.Unroll
 class CachedPathSensitivityIntegrationTest extends AbstractPathSensitivityIntegrationSpec implements DirectoryBuildCacheFixture {
     def setup() {
         buildFile << """
-            task clean {
-                doLast {
-                    delete(tasks*.outputs*.files)
-                }
-            }
+            apply plugin: 'base'
```
Comment (lptr) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedPathSensitivityIntegrationTest.groovy]: I've added https://github.com/gradle/gradle/issues/12140 to deal with this pattern in a more general way.
