### PR TITLE
Make improper usage of resolveToStateOrLater throw exceptions

### LINKED ISSUE #21954: Remove DefaultConfiguration#resolveToStateOrLater
This needs to be checked to ensure it doesn't break build imports and some other things besides just Smoke Tests - **a clean Gradle build is necessary but not sufficient** to indicate this is ready to be merged.

Test opening a project in IntelliJ and check with IDE team after this is removed and tests are passing.

### PR DESCRIPTION
**Pull request by tresat**
- Rework and rename some tests which now contain failing builds

Fixes #21954

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java [hunk 1]
```diff
@@ -600,12 +600,8 @@ private ResolveState resolveToStateOrLater(final InternalState requestedState) {
...
             } else {
-                // We don't currently have mutable access to the project, so report a deprecation warning and then continue by attempting to acquire mutable access
-                DeprecationLogger.deprecateBehaviour("Resolution of the configuration " + identityPath.toString() + " was attempted from a context different than the project context. Have a look at the documentation to understand why this is a problem and how it can be resolved.")
-                    .willBeRemovedInGradle8()
-                    .withUserManual("viewing_debugging_dependencies", "sub:resolving-unsafe-configuration-resolution-errors")
-                    .nagUser();
-                return domainObjectContext.getModel().fromMutableState(p -> resolveExclusively(requestedState));
+                String docsLink = documentationRegistry.getDocumentationFor("viewing_debugging_dependencies", "sub:resolving-unsafe-configuration-resolution-errors");
+                throw new IllegalStateException(String.format("Resolution of the configuration " + identityPath.toString() + " was attempted from a context different than the project context. See: %s for more information.", docsLink));
```
Comment (jvandort) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java:604]: What do you think about this saying "current project context" instead of just "project context"?

**Review by jvandort — APPROVED** [review]

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java (hunk 1 above)
Comment (tresat) [reply subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java:604]: I think this is an improvement, but I'm not completely sure it's always meaningful to say current project, especially with the tooling API.  I'd say revisit the wording later and leave the message unchanged in this PR.

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test rfn

**Comment by tresat** [comment]
@bot-gradle test and merge
