### PR TITLE
Fix ValidateTaskProperties producing output in wrong directory

### LINKED ISSUE #3546: Task property validation file is generated outside of project.buildDir when java-gradle-plugin is applied
When using `java-gradle-plugin`, task property validation file `reports/task-properties/report.txt` is always generated at `build/reports/task-properties/report.txt`, even if `project.buildDir` is updated to point somewhere else.

### Expected Behavior
Task property validation file should be generated at `${project.buildDir}/reports/task-properties/report.txt`

### Current Behavior
Task property validation file should is generated at `build/reports/task-properties/report.txt`

### Context
We use `build/` folder to output the final artifact which are meant to to be archived. When we have `java-gradle-plugin` applied and `project.buildDir` to pointing to somewhere else, we are still seeing `build/reports/task-properties/report.txt` being generated and getting archived along with the other artifacts that we manually copy to `build/` directory.

This seems to be due to [this line](https://github.com/gradle/gradle/blame/a1a32e5877c852b3a99f337e0fc07a2c979840a6/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java#L250-L252) which sets the `validator.setOutputFile` using the default value of `project.buildDir` instead of setting it lazily.

### Steps to Reproduce (for bugs)
[javaGradlePluginSample.tar.gz](https://github.com/gradle/gradle/files/1489890/javaGradlePluginSample.tar.gz)

Following is the directory structure after the build: 
```
.
├── build
│   └── reports
│       └── task-properties
│           └── report.txt
├── build.gradle
├── fooBar
│   ├── classes
│   │   └── java
│   │       └── main
│   │           └── org
│   │               └── gradle
│   │                   └── sample
│   │                       └── SimplePlugin.class
│   ├── libs
│   │   └── javaGradlePlugin.jar
│   ├── pluginDescriptors
│   │   └── org.gradle.sample.simple-plugin.properties
│   ├── pluginUnderTestMetadata
│   │   └── plugin-under-test-metadata.properties
│   ├── resources
│   │   └── main
│   │       └── META-INF
│   │           └── gradle-plugins
│   │               └── org.gradle.sample.simple-plugin.properties
│   └── tmp
│       ├── compileJava
│       └── jar
│           └── MANIFEST.MF
└── src
    └── main
        └── java
            └── org
                └── gradle
                    └── sample
                        └── SimplePlugin.java

```
Note: There should not be any `build/` directory when `project.buildDir = 'fooBar'`

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/h6ajwgxvlnq26/

### PR DESCRIPTION
**Pull request by lptr**
Previously the task did not respect if the `buildDir` location was changed.

Fixes #3546.

### CODE REVIEW

File: subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy [hunk 1]
```diff
@@ -54,9 +49,8 @@ class ValidateTaskPropertiesIntegrationTest extends AbstractIntegrationSpec {
                     return count;
                 }
 
-                // Ignored because not a JavaBean getter
                 public long getter() {
```
Comment (wolfs) [inline subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy]: How about we remove the `getter` method completely? It doesn't give any new information in this test, does it?

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java [hunk 2]
```diff
@@ -307,26 +316,52 @@ public boolean getFailOnWarning() {
...
 
     /**
      * Sets the output file to store the report in.
      *
      * @since 4.0
+     *
+     * @deprecated Use {@link #getOutputFile()} instead.
      */
+    @Deprecated
     public void setOutputFile(File outputFile) {
```
Comment (wolfs) [inline subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java]: We automatically create a setter for the `getOutputFile` which takes a `File` and is accessible from Groovy, so you could write:
```
validateTaskProperties.outputFile = new File('some')
```

If we deprecate this setter we cannot use the decoration from Groovy, can we?
OTOH, removing the setter may break statically compiled plugins using this task.
Ideas?

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java [hunk 3]
```diff
@@ -307,26 +316,52 @@ public boolean getFailOnWarning() {
...
      * Sets the output file to store the report in.
+     *
+     * @deprecated Use {@link #getOutputFile()} instead.
      */
-    public void setOutputFile(Object outputFile) {
-        this.outputFile = outputFile;
+    @Deprecated
+    public void setOutputFile(@Nullable final Object outputFile) {
+        DeprecationLogger.nagUserOfReplacedMethod("ValidateTaskProperties.setOutputFile(Object)", "getOutputFile()");
+        this.outputFile.set(new AbstractProvider<RegularFile>() {
```
Comment (wolfs) [inline subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java]: I don't think you need/want to create a new subclass of Provider. If you want to create a Provider, use `Project.provider()`. You may also want to use `Project.layout.file`, which creates a `Provider<RegularFile>` from a `Provider<File>`.

Comment (wolfs) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java]: I am also not sure what we do in terms of DSL decoration for setters of `RegularFileProperty`s. Maybe we add already a setter like this?
I don't quite see the benefit in this setter anyway. Instead of allowing `Object` here as an argument I think we would be better off if the user provided `file(Object)` to this method. If they want to do something lazy, they can now use the `RegularFileProperty` anyway.

File: subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy (hunk 1 above)
Comment (lptr) [reply subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy]: I think it's good information that we detect this as a property called `ter`.

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java (hunk 2 above)
Comment (lptr) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java]: Yes, and removing the setter would break Java compatibility, too. Not that I think either is used.

Comment (lptr) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java]: I'd just let this method expire in 5.0.

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java (hunk 3 above)
Comment (lptr) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java]: This is solely to retain binary compatibility and to print the deprecation warning. I'm also fine breaking binary compatibility, because `@Incubating`.

File: subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java (hunk 2 above)
Comment (lptr) [reply subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java]: OK, together with the other setter I'm convinced we should just remove these guys, since `@Incubating`.

**Comment by lptr** [comment]
Quick build: https://builds.gradle.org/viewQueued.html?itemId=9434380

**Comment by lptr** [comment]
I don't think we want to add that test. We'd need to add a test for every single file task property.
