### PR TITLE
Unsubscribe build services from build event before closing them

### LINKED ISSUE #24887: Race condition between stopping and notifying operation completion listener
### Expected Behavior

A build service may also be registered as a operation completion listener via `BuildEventsListenerRegistry.onTaskCompletion()`. Such listener should either be invoked even after the service is stopped (causing it to be reinstantiated), or not invoked at all. 

### Current Behavior

Right now, there is a race condition in which it is possible that a build service will be stopped while some other thread is trying to invoke `OperationCompletionListener.onFinish()` on the build service. The result is a NullPointerException like this:

 ```
java.lang.NullPointerException: Cannot invoke "org.gradle.internal.Try.get()" because "this.instance" is null	
at org.gradle.api.services.internal.RegisteredBuildServiceProvider.getInstance(RegisteredBuildServiceProvider.java:121)	
at org.gradle.api.services.internal.RegisteredBuildServiceProvider.calculateOwnValue(RegisteredBuildServiceProvider.java:111)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:73)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:93)	
at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer.handle(DefaultBuildEventsListenerRegistry.java:261)	
at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer.handle(DefaultBuildEventsListenerRegistry.java:238)	
at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$AbstractListener.run(DefaultBuildEventsListenerRegistry.java:180)	
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)	
at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)	
 ```
 

### Context (optional)

This method is not thread safe:

```
    private T getInstance() {
        listener.beforeGet(this);
        synchronized (this) {
            if (instance == null) {
                instance = instantiate();
            }
        }
        return instance.get();
    }
```

as we attempt to access a field that is mutated from different threads without synchronization.

Fixing the race condition so the NPE no longer happens would be easy, but it is unclear whether we would want the listener to be invoked while the service is stopped, have the service be reinstantiated, the listener not to be invoked at all, or something else. 

### Steps to Reproduce

This was spotted in Gradle's own builds:

https://ge.gradle.org/s/wiwsly5z2uwty/tests/:configuration-cache:embeddedIntegTest/org.gradle.configurationcache.ConfigurationCacheBuildServiceIntegrationTest/build%20service%20registered%20as%20listener%20in%20an%20included%20build%20with%20no%20work%20is%20not%20restored?expanded-stacktrace=WyIwIiwiMC0xLTIiXQ&top-execution=1

I was only able to reproduce it by tweaking the flaky test to run a thousand times (failed on attempt #684 for me, YMMV) :

```
---
Index: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy
===================================================================
diff --git a/subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy b/subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy
--- a/subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy	(revision 9b74f67f363d2e5a25289f027afa222b869d645c)
+++ b/subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy	(date 1682341864787)
@@ -43,6 +43,7 @@
 import org.gradle.tooling.events.task.TaskFinishEvent
 import spock.lang.IgnoreIf
 import spock.lang.Issue
+import spock.lang.Unroll
 
 import javax.inject.Inject
 import java.util.concurrent.atomic.AtomicInteger
@@ -718,6 +719,7 @@
     }
 
     @Issue("https://github.com/gradle/gradle/issues/23700")
+    @Unroll("test repeated #i time")
     def "build service registered as listener in an included build with no work is not restored"() {
         def onFinishMessage = "You won't see me!"
         withListenerBuildServicePlugin onFinishMessage
@@ -756,5 +758,8 @@
         then:
         configurationCache.assertStateLoaded()
         outputDoesNotContain onFinishMessage
+
+        where:
+        i << (1..1000)
     }
 }

``` 

Not completely sure the use of included builds is required to recreate the issue.

### Gradle version

8.1

### Build scan URL (optional)

https://ge.gradle.org/scans/tests?search.timeZoneId=Europe/Berlin&tests.container=org.gradle.configurationcache.ConfigurationCacheBuildServiceIntegrationTest&tests.test=build%20service%20registered%20as%20listener%20in%20an%20included%20build%20with%20no%20work%20is%20not%20restored

### Your Environment (optional)

_No response_

### LINKED ISSUE #27099: BuildServiceParameters fails with convention plugins
### Current Behavior

BuildServiceParameters fails with convention plugins

`org.gradle.internal.snapshot.impl.IsolationException: Could not isolate value org.example.MyParameters_Decorated@33db25b2 of type MyParameters`

where MyParameters - it is my own interface
```Kotlin
interface MyParameters : BuildServiceParameters {
    val someInt: Property<Int>
}
```

### Expected Behavior

Better to support usage of BuildServiceParameters without workaround

### Context (optional)

I found workaround to call all paratemers in my custom BuildServiceParameters at least once.
All described in reproducer repository.

**Maybe where are some documentation that describe this behavior, or maybe related Issue already created?**

### Steps to Reproduce

Made reproducer here:
https://github.com/dima-avdeev-jb/gradle-build-service-parameters-issue

### Gradle version

8.4

### Build scan URL (optional)

https://gradle.com/s/voqsbvcxhvfcc

### Your Environment (optional)

 - MacOS 13.5.2 (22G91)
 - openjdk 17.0.8 2023-07-18 LTS

### PR DESCRIPTION
**Pull request by mlopatkin**
There are three primary changes:
1. Build services registered as event listeners are now unsubscribed before they are closed. 
2. Closing the build service blocks until all pending build events in its queue are processed. This and the previous item guarantee that the closed service is never revived, and also prevents services from "gone" nested build trees from receiving events.
3. ~Event listeners registry is now Build-scoped. All listeners unsubscribe themselves when the build ends, so it makes no sense for the container to outlive them.~ - withdrawn from 8.9 scope.

Fixes #27099.
Fixes #24887. 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test RfN without PTS

**Comment by mlopatkin** [comment]
@bot-gradle test RfN without PTS

**Comment by mlopatkin** [comment]
@bot-gradle test PRF without PTS

**Comment by mlopatkin** [comment]
@bot-gradle test RfN without PTS

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt [hunk 1]
```diff
@@ -451,7 +446,7 @@ class ConfigurationCacheState(
                 writeGradleState(gradle)
                 val projects = collectProjects(state.projects, scheduledWork.scheduledNodes, gradle.serviceOf())
                 writeProjects(gradle, projects)
-                writeRequiredBuildServicesOf(state, buildTreeState)
+                writeRequiredBuildServicesOf(state, buildEventListenersOf(build.gradle))
```
Comment (abstratt) [inline platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt:449]: More for my education than anything else:

I noticed `buildEventListenersOf()` has a filter to exclude build services for "buildSrc". Is that needed for this case? I guess it was not needed before because the listeners were retrieved by build id? Why don't we need to filter out listeners for other (non-buildSrc) builds?

```
    private
    fun buildEventListenersOf(gradle: GradleInternal) =
        gradle.serviceOf<BuildEventListenerRegistryInternal>()
            .subscriptions
            .filterIsInstance<RegisteredBuildServiceProvider<*, *>>()
            .filter(::isRelevantBuildEventListener)

    private
    fun isRelevantBuildEventListener(provider: RegisteredBuildServiceProvider<*, *>) =
        Path.path(provider.buildIdentifier.buildPath).name != BUILD_SRC
```

File: subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy [hunk 2]
```diff
@@ -33,7 +36,7 @@ class BuildEventsParallelIntegrationTest extends AbstractIntegrationSpec {
     }
 
     def "event handling does not block other work"() {
-        buildFile << """
+        buildFile("""
```
Comment (bamboo) [inline subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy:39]: 💅 Parentheses are unnecessary here

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt [hunk 3]
```diff
@@ -180,10 +180,10 @@ class ConfigurationCacheIO internal constructor(
     }
 
     internal
-    fun writeIncludedBuildStateTo(stateFile: ConfigurationCacheStateFile, buildTreeState: StoredBuildTreeState) {
+    fun writeIncludedBuildStateTo(stateFile: ConfigurationCacheStateFile) {
         writeConfigurationCacheState(stateFile) { cacheState ->
             cacheState.run {
-                writeBuildContent(host.currentBuild, buildTreeState)
```
Comment (bamboo) [inline platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt:186]: Nice! 👍

File: platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt (hunk 1 above)
Comment (mlopatkin) [reply platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt:449]: > I noticed `buildEventListenersOf()` has a filter to exclude build services for "buildSrc". Is that needed for this case? I guess it was not needed before because the listeners were retrieved by build id? Why don't we need to filter out listeners for other (non-buildSrc) builds?

That's a good question, because `buildSrc` is not that different from any other plugin-only build. It might be that later changes to handling of builds without work made this filtering obsolete if not incorrect (as you can now run buildSrc tasks in the root build too).

File: subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy [hunk 4]
```diff
@@ -81,4 +84,68 @@ class BuildEventsParallelIntegrationTest extends AbstractIntegrationSpec {
...
+                dependsOn("a")
+            }
+        """)
+
+        when:
+        def handleA = server.expectAndBlock("handle:a")
+        server.expect("handle:b")
+        server.expect("serviceClosed")
+
+        def build = executer.withTasks("b").startBuildProcessInDebugger(false).start()
```
Comment (bamboo) [inline subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy:138]: 💅 Did you mean to keep the `startBuildProcessInDebugger(false)` call here?

File: subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy [hunk 5]
```diff
@@ -81,4 +84,68 @@ class BuildEventsParallelIntegrationTest extends AbstractIntegrationSpec {
...
+
+        handleA.waitForAllPendingCalls()
+        sleep(1000) // Give a chance for the service to close if there is no proper synchronization.
```
Comment (bamboo) [inline subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy:141]: 🤔

File: subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy [hunk 6]
```diff
@@ -1567,6 +1575,130 @@ Hello, subproject1
         outputContains("Resolving provider")
     }
 
+    @Issue("https://github.com/gradle/gradle/issues/27099")
+    def "can apply service plugin in precompiled script plugins"() {
```
Comment (bamboo) [inline subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy:1579]: 👍

File: subprojects/core/src/main/java/org/gradle/api/services/internal/RegisteredBuildServiceProvider.java [hunk 7]
```diff
@@ -107,6 +114,25 @@ public void keepAlive() {
...
+     * The callback runs even if the service wasn't created.
+     * This provider is used as a callback argument.
+     * <p>
+     * The service will only be stopped after completing all registered callbacks.
+     *
+     * @param stopAction the callback
+     */
+    public void beforeStopping(Consumer<? super RegisteredBuildServiceProvider<T, P>> stopAction) {
+        synchronized (this) {
+            if (stopActions == null) {
```
Comment (bamboo) [inline subprojects/core/src/main/java/org/gradle/api/services/internal/RegisteredBuildServiceProvider.java:128]: 👍 Nice to lazy allocate it

File: subprojects/core/src/main/java/org/gradle/api/services/internal/RegisteredBuildServiceProvider.java [hunk 8]
```diff
@@ -157,8 +183,18 @@ public ExecutionTimeValue<? extends T> calculateExecutionTimeValue() {
         return ExecutionTimeValue.changingValue(this);
     }
 
+    private ImmutableList<Consumer<? super RegisteredBuildServiceProvider<T, P>>> getStopActions() {
+        synchronized (this) {
```
Comment (bamboo) [inline subprojects/core/src/main/java/org/gradle/api/services/internal/RegisteredBuildServiceProvider.java:187]: 🤔 Since the provider reference is exposed to users, should it really synchronize on `this`?

File: subprojects/core/src/test/groovy/org/gradle/api/services/internal/DefaultBuildServicesRegistryTest.groovy [hunk 9]
```diff
@@ -356,12 +360,126 @@ class DefaultBuildServicesRegistryTest extends Specification {
...
+        def provider = registerService("service", ServiceImpl)
+        provider.beforeStopping { throw new UnsupportedOperationException("Don't stop") }
+        when:
+        buildFinished()
+
+        then:
+        thrown(Exception)
+    }
+
+    def "other stop actions run if one of them throws"() {
```
Comment (bamboo) [inline subprojects/core/src/test/groovy/org/gradle/api/services/internal/DefaultBuildServicesRegistryTest.groovy:417]: 👍

Comment (bamboo) [inline subprojects/core/src/test/groovy/org/gradle/api/services/internal/DefaultBuildServicesRegistryTest.groovy:417]: ❓ What about other service providers also registered as listeners, would they be properly stopped as well?

Comment (mlopatkin) [reply subprojects/core/src/test/groovy/org/gradle/api/services/internal/DefaultBuildServicesRegistryTest.groovy:418]: >What about other service providers also registered as listeners, would they be properly stopped as well?

I've added some tests to cover this scenario too.

File: subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy (hunk 2 above)
Comment (mlopatkin) [reply subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy]: > 💅 Parentheses are unnecessary here

Ok, this seems to be a prevalent style in our tests.

File: subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy (hunk 4 above)
Comment (mlopatkin) [reply subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy]: >Did you mean to keep the startBuildProcessInDebugger(false) call here?

Thank you for spotting!

File: subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy (hunk 5 above)
Comment (mlopatkin) [reply subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy]: > 🤔
 
Definitely not my prettiest test, but I'm out of ideas how to make it more precise. I reworded the comment. At least the test should not fail if everything works as designed.

File: subprojects/core/src/main/java/org/gradle/api/services/internal/RegisteredBuildServiceProvider.java (hunk 8 above)
Comment (mlopatkin) [reply subprojects/core/src/main/java/org/gradle/api/services/internal/RegisteredBuildServiceProvider.java]: > should it really synchronize on `this`?

You're right, this might be an issue. I'm reluctant to add stuff to providers after that memory regression with evaluation context wrappers, but it should not be that bad this time.

File: subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy [hunk 10]
```diff
@@ -81,4 +84,69 @@ class BuildEventsParallelIntegrationTest extends AbstractIntegrationSpec {
         then:
         noExceptionThrown()
     }
+
+    @Issue("https://github.com/gradle/gradle/issues/24887")
```
Comment (abstratt) [inline subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy:88]: Good news re: #24887. My test case for that can no longer reproduce it with your changes (I still can frequently reproduce it with master - twice in a thousand iterations).

Comment (abstratt) [reply subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy:88]: Screenshot 2024-06-05 at 19 46 09

**Comment by mlopatkin** [comment]
@bot-gradle test this

File: subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy (hunk 10 above)
Comment (mlopatkin) [reply subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy:88]: Thank you for checking!

Comment (abstratt) [reply subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy:88]: @mlopatkin I believe it would be safe to remove this `@Flaky` annotation: https://github.com/gradle/gradle/blob/master/platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy#L722

Comment (mlopatkin) [reply subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsParallelIntegrationTest.groovy:88]: > @mlopatkin I believe it would be safe to remove this `@Flaky` annotation: [`master`/platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy#L722](https://github.com/gradle/gradle/blob/master/platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy?rgh-link-date=2024-06-06T19%3A44%3A28Z#L722)

Let's do it after 8.9 branch cut?

**Review by bamboo — APPROVED** [review]
Looks good 👍
