### PR TITLE
Set ValidateTaskProperties.failOnWarning = true

### LINKED ISSUE #9083: Fail task validation on warning by default
The `ValidateTaskProperties` task does not fail on warning by default. It probably should. If we want to change the default value, we should do it for 5.0.

### PR DESCRIPTION
**Pull request by wolfs**
Fixes #9083.

### CODE REVIEW

**Comment by wolfs** [comment]
I made `failOnWarning = true` the default.

Moreover, I promoted some validations from warning to error. Please check out if you agree promoting those for 6.0.

**Comment by wolfs** [comment]
@lptr: Do you think we should rename `visitError` to `visitWarning` and `visitErrorStrict` to `visitError`?

**Comment by lptr** [comment]
> @lptr: Do you think we should rename `visitError` to `visitWarning` and `visitErrorStrict` to `visitError`?

Let's do that. If we turn warnings into deprecations then we could use `visitDeprecated()` and `visitError()`, too.

**Comment by wolfs** [comment]
I did the renames.

File: subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy [hunk 1]
```diff
@@ -67,7 +68,7 @@ class DefaultTaskInputsTest extends Specification {
     }
     def cacheFactory = new TestCrossBuildInMemoryCacheFactory()
     def typeAnnotationMetadataStore = new DefaultTypeAnnotationMetadataStore([], [:], [Object, GroovyObject], [Object, GroovyObject], [ConfigurableFileCollection, Property], Internal, { false }, cacheFactory)
-    def walker = new DefaultPropertyWalker(new DefaultTypeMetadataStore([], [], [], typeAnnotationMetadataStore, cacheFactory))
+    def walker = new DefaultPropertyWalker(new DefaultTypeMetadataStore([], [new NoOpPropertyAnnotationHandler(Internal)], [], typeAnnotationMetadataStore, cacheFactory))
```
Comment (lptr) [inline subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy]: Why is this necessary now?

File: subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy [hunk 2]
```diff
@@ -216,12 +216,12 @@ class ValidateTaskPropertiesIntegrationTest extends AbstractIntegrationSpec {
         fails("validateTaskProperties")
         failure.assertHasDescription("Execution failed for task ':validateTaskProperties'.")
         failure.assertHasCause("Task property validation failed. See")
-        failure.assertHasCause("Warning: Type 'MyTask': property 'thing' is annotated with invalid property type @${annotation.simpleName}.")
-        failure.assertHasCause("Warning: Type 'MyTask': property 'options.nestedThing' is annotated with invalid property type @${annotation.simpleName}.")
+        failure.assertHasCause("Error: Type 'MyTask': property 'thing' is annotated with invalid property type @${annotation.simpleName}.")
+        failure.assertHasCause("Error: Type 'MyTask': property 'options.nestedThing' is annotated with invalid property type @${annotation.simpleName}.")
```
Comment (lptr) [inline subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy]: Why make exactly these errors a strict one?

File: subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy (hunk 1 above)
Comment (wolfs) [reply subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy]: Since the test would fail, given that using unknown annotations on properties is now a failure. The classes we use for testing use `@Internal`.

File: subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy (hunk 2 above)
Comment (wolfs) [reply subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy]: I reviewed the warnings and thought the once I selected make sense to be errors now. The most problematic warning is the one about non-annotated properties, since that makes a lot of tasks fail.

Do you disagree with my assessment?

File: subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy (hunk 1 above)
Comment (wolfs) [reply subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy]: We can not promote any warnings to errors at all.

File: subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy (hunk 2 above)
Comment (wolfs) [reply subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy]: We don't have to promote any warnings to errors at all. It seemed that the ones I promoted make sense.

**Comment by wolfs** [comment]
@lptr I added upgrading instructions. PTAL!

**Comment by wolfs** [comment]
@lptr PTAL!
