### PR TITLE
Use URI instead of URLDecoder in file/uri conversion

### LINKED ISSUE #26678: ivy repository URL String parsing broken with 8.3
### Current Behavior

Before gradle 8.3 we could pass our ivy repository url definition like this:

```
repositories {
    // Cloud builds bundle some beats
    ivy {
      name = 'beats'
      url "file://${buildDir}/artifacts/"
      patternLayout {
          artifact '/[organisation]/[module]-[revision]-[classifier].[ext]'
      }
    }
}
```

this is broken with Gradle 8.3 as we have a '+' in our CI project path (eg.: /usr/jenkins/elasticsearch+7.10/) as the plus sign gets interpreted as space. That should not be the case in file urls I think. 

### Expected Behavior

The plus sign in a file url is not interpreted as a special character or as an escape of a space sign.

### Context (optional)

Digging into the gradle sources I found a simple workaround by just passing a File object directly but I still think in general the change in behaviour was not intended and is wrong. 

### Steps to Reproduce

with a simple given build script:

```
repositories {
    // Cloud builds bundle some beats
    ivy {
      name = 'beats'
      url "/dev/jenkins/project+branch"
      println "repo url: $url"
      patternLayout {
          artifact '/[organisation]/[module]-[revision]-[classifier].[ext]'
      }
    }
}
```
if you run that with `./gradlew help` will print "repo url: /dev/jenkins/project branch"

### Gradle version

8.3

### Gradle version that used to work

8.2

### Build scan URL (optional)

_No response_

### Your Environment (optional)

this issue is environment independant

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #26678 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by octylFractal** [comment]
@bot-gradle test QF

File: platforms/core-configuration/file-collections/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java [hunk 1]
```diff
@@ -134,22 +150,15 @@ private static void convertToUrl(String notationString, NotationConvertResult<?
...
-        }
-    }
-
     /**
      * Lenient legacy behavior to fall back to when URI cannot be normally parsed.
-     *
-     * TODO: Deprecate this
      */
     private static String fallbackUrlDecode(String path) {
+        DeprecationLogger.deprecateBehaviour("legacy URL decoding for invalid URLs")
```
Comment (jvandort) [inline platforms/core-configuration/file-collections/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java:157]: We should write an integ test that demonstrates this deprecation warning

File: platforms/core-configuration/file-collections/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java [hunk 2]
```diff
@@ -122,6 +127,17 @@ public void convert(Object notation, NotationConvertResult<? super Object> resul
         }
     }
 
+    private static boolean tryConvertToFile(URI uri, NotationConvertResult<? super Object> result) {
```
Comment (jvandort) [inline platforms/core-configuration/file-collections/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java:130]: IMO passing the `result` into this method makes the control flow difficult to follow. I had originally not seen that this method has side-effects and calls `converted`. I think this would be much easier to follow if this just returned a nullable file and the side-effects were handled outside of this method

**Review by jvandort — CHANGES_REQUESTED** [review]
Some of the logic here is confusing me

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
@bot-gradle test and merge
