### PR TITLE
Fix snapshot filtering

### LINKED ISSUE #29205: DefaultFileSystemAccess.snapshot sometimes ignoring filter
### Current Behavior

I’m finding that in certain circumstances, the filter assigned to a FileCollection is ignored.

In DefaultFileSystemAccess.snapshot there is an early exit [here](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L163) to check for existing FileSystemLocationSnapshots, and if one is found, then the snapshot is used, regardless of whether a [filter was passed](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L155) to the `snapshot()` function

Normally this case doesn’t trigger, because there are other early exits in `readSnapshotFromLocation()` such as [here](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L197) which do [apply the filter](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L198), and [there is a lock](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L196) in `readSnapshotFromLocation()` to try to prevent computing multiple snapshots of the same directory at a time (see [comment](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L195)).

However, if DefaultFileSystemAccess simultaneously tries to load information about a parent and child directory at the same time, then it is possible that [updates](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L181) of the parent directory in the [virtual file system](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java) will also cause corresponding updates of the child directory, even while DefaultFileSystemAccess holds a lock on the child directory. These concurrent updates can then trigger the ignoring of a `FileCollection`'s filter.

### Expected Behavior

It would be nice if the filter assigned to a `FileCollection` weren't ignored

### Context (optional)

In AndroidX we've been observing our `compileKotlin` tasks to be intermittently out-of-date: https://issuetracker.google.com/issues/321949384 and this seems to be the cause

### Steps to Reproduce

I've uploaded a repro case to https://github.com/mathjeff/gradle-samples-2/tree/main/snapshot-wrong

Because reproducing this issue involves a race condition, I've also uploaded a test Gradle change that exacerbates the race condition by adding an additional hard coded sleep for a specific path (the child path) at https://github.com/gradle/gradle/compare/master...mathjeff:gradle:test-exacerbate-snapshot-race-condition

The test.sh script in the repro case takes care of applying this change before running the test

### Gradle version

8.7.0

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by lptr**
Fixes #29205

### Context

In some rare cases Gradle could ignore filters while snapshotting inputs or outputs, leading false positives when checking for changes.

The problem lies in how we reuse already taken snapshots. Gradle only stores unfiltered snapshots in the virtual file system, so when reusing these stored snapshots we should make sure to filter them according to whatever is requested. This was not done in one of several branches. The result was that in some highly concurrent builds we'd return the unfiltered snapshot.

I made the code somewhat simpler, this way eliminating some of the branches, and also removed the opportunity for this bug to manifest.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/core-execution/snapshots/src/main/java/org/gradle/internal/snapshot/impl/FileSystemSnapshotFilter.java [hunk 1]
```diff
@@ -41,14 +41,18 @@ public class FileSystemSnapshotFilter {
...
         DirectorySnapshotBuilder builder = MerkleDirectorySnapshotBuilder.noSortingRequired();
         AtomicBoolean hasBeenFiltered = new AtomicBoolean();
         unfiltered.accept(new RelativePathTracker(), new FilteringVisitor(predicate, builder, hasBeenFiltered));
         if (builder.getResult() == null) {
-            return FileSystemSnapshot.EMPTY;
+            return Optional.empty();
         }
-        return hasBeenFiltered.get() ? builder.getResult() : unfiltered;
+        return Optional.of(hasBeenFiltered.get() ? builder.getResult() : unfiltered);
     }
```
Comment (lptr) [inline platforms/core-execution/snapshots/src/main/java/org/gradle/internal/snapshot/impl/FileSystemSnapshotFilter.java:56]: 💭 Instead of filtering `FileSystemSnapshot` (that can be empty, or contain snapshots from multiple roots) we now specifically filter the snapshot of a single location, and return exactly 0 or 1 snapshot matching the filter. Being more specific here makes it easier to work with the result.

File: platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java [hunk 2]
```diff
@@ -55,7 +55,7 @@ public interface VirtualFileSystem {
      * If the snapshotted location is invalidated while snapshotting,
      * then the snapshot is not stored in the VFS to avoid inconsistent state.
      */
-    <T> T store(String baseLocation, StoringAction<T> storingAction);
+    <T> T storeWithAction(String baseLocation, StoringAction<T> storingAction);
```
Comment (lptr) [inline platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java:58]: 💭 This was to make the tests a bit easier to read.

File: platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java [hunk 3]
```diff
@@ -129,77 +119,89 @@ public Optional<HashCode> readRegularFileContentHash(String location) {
...
                         filter.isEmpty() ? null : filter.getAsDirectoryWalkerPredicate(),
                         previouslyKnownSnapshots,
-                        vfsStorer::store);
+                        vfsStorer::store));
                 default:
                     throw new UnsupportedOperationException();
             }
+            return filterSnapshot(filter, unfilteredSnapshot);
         });
     }
```
Comment (lptr) [inline platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java:203]: 💭 The main change in the PR is to this method. The original `snapshot()` method used to return a mixed bag; if you git a `DirectorySnapshot`, it would be filtered, but if it was a regular file or missing snapshot, it would not, and thus we had more complexity to deal with at the call site. We are now dealing with that difference here.

**Comment by lptr** [comment]
@bot-gradle test this please.

File: platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java [hunk 4]
```diff
@@ -129,77 +119,89 @@ public Optional<HashCode> readRegularFileContentHash(String location) {
...
                 case Missing:
-                    return vfsStorer.store(new MissingFileSnapshot(location, fileMetadata.getAccessType()));
+                    unfilteredSnapshot = vfsStorer.store(new MissingFileSnapshot(location, fileMetadata.getAccessType()));
+                    break;
                 case Directory:
-                    // This will only store the captured snapshot in the VFS if the filter did not match anything
-                    return directorySnapshotter.snapshot(
+                    // This will capture a filtered snapshot, and only store the captured snapshot in the VFS
+                    // if the filter did not filter out anything.
+                    return Optional.of(directorySnapshotter.snapshot(
```
Comment (asodja) [inline platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java:193]: 🤔 Would it also make sense that `directorySnapshotter.snapshot()` would return `unfilteredSnapshot` and we would filter it inside `snapshotAndReuse`?

**Review by asodja — APPROVED** [review]
LGTM

File: platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java (hunk 4 above)
Comment (lptr) [reply platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java:193]: There is a use case where this wouldn't work: if you had wanted to snapshot a large directory, but only capture a some part of it. With the current solution you never have to snapshot the unwanted files.

**Review by wolfs — COMMENTED** [review]
LGTM!
