### PR TITLE
Check if auto-applied plugins are already on classpath

### LINKED ISSUE #22272: Adding the `--scan` option can result in a different version of the GE plugin applied
If a build applies a custom settings plugin that transitively applies the `com.gradle.enterprise` plugin with a particular version, then running the build with `--scan` can result in a _newer_ version of the plugin being used in the build invocation. This occurs whether the custom plugin is sources from a composite build or an external repository.

### Expected Behavior
The `--scan` option should not alter the version of GE plugin applied directly to `Settings`.

### Current Behavior
The `--scan` option can result in the build running with a newer GE plugin version than the one configured in `Settings`.

### Steps to Reproduce 

To see this behaviour, clone https://github.com/bigdaz/duplicate-ge-plugin-application.

##### Custom plugin sourced from included build
- Run `./gradlew noop`: [GE plugin `3.8.1` is applied](https://scans.gradle.com/s/e5twvgtxywagy/plugins#com.gradle.enterprise-14)
- Run `./gradlew noop --scan`: [GE plugin `3.10.2` is applied](https://scans.gradle.com/s/hgffscwglpkz2/plugins#com.gradle.enterprise-14)

##### Custom plugin sourced from repository
- Checkout the `published-plugin` branch.
- Publish the plugin to maven local: `./gradlew -p build-src publishToMavenLocal`
- Run the same 2 builds as above: same behaviour

##### Custom plugin applied using `apply: plugin`
- Checkout the `build-script-block` branch.
- If not already done, publish the plugin to maven local: `./gradlew -p build-src publishToMavenLocal`
- Run the same 2 builds as above: same behaviour

### Context
In summary the logic that detects `--scan` and applies the GE plugin fails to detect a pre-existing GE plugin when that the GE plugin is brought in as a transitive dependency of an applied plugin. I believe this is because the [isAlreadyAppliedOrRequested()](https://github.com/gradle/gradle/blob/412cfdace49a677346c0ee3e0cfd10d1d2f33374/subprojects/plugin-use/src/main/java/org/gradle/plugin/management/internal/autoapply/DefaultAutoAppliedPluginHandler.java#L73-L104) method that is used to avoid duplicate plugin requests relies only on plugin ids and buildscript dependency declarations. If the GE plugin is resolved and applied transitively it will not be detected,  resulting in duplicate plugin application with `--scan`.

Note that the GE plugin already takes care of avoiding duplicate plugin _apply_: if the GE plugin has already been applied then applying another one is short-circuited. The problem here is that adding `--scan` can result in:
1. The wrong GE plugin version being applied
2. Multiple GE plugin versions ending up on the buildscript classpath, resulting in unexpected cache misses.

### LINKED ISSUE #22273: Adding the `--scan` option can produce cache misses due to changed order for the `Settings` buildscript classpath
If a build applies a custom settings plugin that transitively applies the `com.gradle.enterprise` plugin with a particular version, then running the build with `--scan` can result in a different ordering of jars in the `Settings` buildscript classpath. This in turn can result in unexpected cache misses, since the classpath hash is different.

Note that this issue is about `--scan` causing cache misses for a build that already has the GE plugin applied. It is a separate issue that using `--scan` on a project _without_ the GE plugin applied will necessarily change the classpath and result in cache misses.

### Expected Behavior
Running a GE-enabled build with `--scan` can result in unexpected cache misses.

### Current Behavior
Running a GE-enabled build with `--scan` should not change build behaviour beyond publishing a build scan.

### Steps to Reproduce 

To see this behaviour, clone https://github.com/bigdaz/duplicate-ge-plugin-application.

##### Custom plugin sourced from included build
- Run `./gradlew noop`: [GE plugin is last in the classpath](https://scans.gradle.com/s/2diabfjvv7z2w/custom-values)
- Run `./gradlew noop --scan`: [GE plugin is 2nd last in the classpath](https://scans.gradle.com/s/tqjoxf2ezrwhw/custom-values)

##### Custom plugin sourced from repository
- Checkout the `published-plugin` branch.
- Publish the plugin to maven local: `./gradlew -p build-src publishToMavenLocal`
- Run the same 2 builds as above: same behaviour

##### Custom plugin applied using `apply: plugin`
- Checkout the `build-script-block` branch.
- If not already done, publish the plugin to maven local: `./gradlew -p build-src publishToMavenLocal`
- Run the same 2 builds as above: same behaviour

### PR DESCRIPTION
**Pull request by sorin-florea**
Fixes #22273
Fixes #22272

### Context
Split the application of plugins into two parts:
- First, apply requested plugins
- Second, check if the auto-applied plugins are already on the classpath and apply them otherwise

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by sorin-florea** [comment]
@bot-gradle test

**Comment by sorin-florea** [comment]
@bot-gradle test PT

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java [hunk 1]
```diff
@@ -85,63 +88,90 @@ public DefaultPluginRequestApplicator(
...
-                                result.found.getPluginId().getId(),
-                                pluginVersion
-                            );
-                        }
-                    }
-                });
+            applyPlugins(scriptHandler, classLoaderScope, pluginApplyActions, pluginImplsFromOtherLoaders, results);
+        }
+
+        exportBuildLogicClassPathTo(classLoaderScope, scriptHandler.getInstrumentedScriptClassPath());
```
Comment (wolfs) [inline subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:112]: Can we lock the classloader scope already here? Then we'd only resolve it in a locked state for checking whether the auto-applied plugins are there and then either use it or throw it away.

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java [hunk 2]
```diff
@@ -85,63 +88,90 @@ public DefaultPluginRequestApplicator(
...
+
+        if (!autoAppliedPlugins.isEmpty()) {
+            final PluginResolver alreadyOnClasspathIgnoringPluginResolver = new AlreadyOnClasspathIgnoringPluginResolver(effectivePluginResolver,
+                new ClassloaderBackedPluginDescriptorLocator(scriptHandler.getClassLoader())
+            );
+
+            List<Result> autoAppliedPluginResults = resolvePluginRequests(autoAppliedPlugins, alreadyOnClasspathIgnoringPluginResolver);
```
Comment (wolfs) [inline subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:119]: Could we here only check for the auto applied plugins whether they are on the classpath or not instead of trying to apply them already? Or am I misunderstanding here something?

Comment (sorin-florea) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:119]: This is not applying the plugins, it is just resolving them. We could check before and resolve them afterwards, but it will not make any difference since we will check if they are on the classpath before resolving anything.

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java (hunk 1 above)
Comment (sorin-florea) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:112]: I guess we can, but that means we have to unlock it. We cannot throw away the classloader scope, just the internal state. And this would work only for the `DefaultClassLoaderScope`

File: subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultClassLoaderScope.java [hunk 3]
```diff
@@ -123,6 +123,13 @@ private void buildEffectiveLoaders() {
         }
     }
 
+    public void dropClassloaders() {
+        exportingClassLoader = null;
+        effectiveExportClassLoader = null;
+        localClassLoader = null;
+        effectiveLocalClassLoader = null;
```
[the remark this answers is not in the document]
Comment (sorin-florea) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultClassLoaderScope.java:130]: I think we should.

**Comment by sorin-florea** [comment]
@bot-gradle test

**Comment by sorin-florea** [comment]
@bot-gradle test this

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/management/internal/autoapply/DefaultAutoAppliedPluginHandler.java [hunk 4]
```diff
@@ -41,27 +41,26 @@ public DefaultAutoAppliedPluginHandler(AutoAppliedPluginRegistry registry) {
...
+            return autoAppliedPlugins;
         } else if (pluginTarget instanceof Settings) {
             Settings settings = (Settings) pluginTarget;
 
             PluginRequests autoAppliedPlugins = registry.getAutoAppliedPlugins(settings);
             if (autoAppliedPlugins.isEmpty()) {
-                return initialRequests;
+                return PluginRequests.EMPTY;
             }
-            return mergePluginRequests(autoAppliedPlugins, initialRequests, settings.getPlugins(), settings.getBuildscript());
```
Comment (sorin-florea) [inline subprojects/plugin-use/src/main/java/org/gradle/plugin/management/internal/autoapply/DefaultAutoAppliedPluginHandler.java:61]: I should probably still filter out the auto-applied plugins at this point, similar to the previous behavior. I will add it.

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java [hunk 5]
```diff
@@ -85,63 +88,90 @@ public DefaultPluginRequestApplicator(
...
+            if (!autoAppliedPluginResults.isEmpty()) {
+                ((DefaultClassLoaderScope) classLoaderScope).dropClassloaders();
+                ((DefaultClassLoaderScope) classLoaderScope).unlock();
```
Comment (ghale) [inline subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:122]: This is not terrible, but it feels a little dirty.  It seems like we have a couple of choices here:
- We reset the classloader scope after checking if we need to add auto-applied plugins.  This is what this PR is currently doing.
- We change the classloader scope structure such that explicit plugins are resolved separately from auto-applied plugins - for instance, one is the parent of the other.  This might be tricky since the classloader scope that gets passed in here is the classloader scope for the domain object, so adding another layer might have consequences and introduce some complexity.
- We don't use the classloader scope and just construct the classloader that we scan for plugins without any caching (at this level, at least).  I believe this is what effectively happens if we reset the classloader scope - we use it once and then throw away the cached classloader.  The only difference is that we could potentially keep using it if we decide the auto-applied plugin is already on the classpath.  Since there is only one auto-applied plugin in existence currently (enterprise plugin) and it is applied to the settings object, I wonder how inefficient it would actually be to just construct an un-cached classloader for checking if the plugin is already applied?  Then we could not lock the classloader scope until we know exactly what will be in it.  We'd be taking on some technical debt if we ever had more auto-applied plugins, but I don't know when/if we ever will.

Any other ideas?

Comment (wolfs) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:122]: What I want to have is that the usual use-case is optimized. I think there are two of them:
- Without auto-applied plugins (without `--scan`): We should do what we do now and only construct and lock the classloader scope once.
- With auto-applied plugins (with `--scan`), though with the scan plugin already applied: We should do what we do now and only construct and lock the classloader scope once, so we don't incur any performance overhead.

My current assumption is that you'd more often have the enterprise plugin already applied when you use `--scan`, given that publishing to scans.gradle.com is probably not happening so often and the CI injections scripts and any local init scripts apply the plugin already. In that sense, you'd use the `--scan` switch only to switch on publishing a scan and not for applying the enterprise plugin.

Though in the end, it doesn't probably matter very much as long as we keep the case when you don't have `--scan` as fast as it is now.

Comment (ghale) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:122]: I think that makes sense.  Do you think it would be better if, instead of exposing unlock/dropClassLoder methods, we have something more encapsulated, where we can better enforce that this is something we should only do while building the classloader scope?  Something like the following on DefaultClassLoaderScope:

```
    public void lockWith(ModifyingLockActor lockActor) {
        if (locked) {
            throw new IllegalStateException("class loader scope is already locked, scope identifier is " + id)
        } else {
            lock();
        }

        if (lockActor.requiresModification()) {
            dropClassloaders();
            unlock();
            lockActor.modify(this);
            lock();
        }
    }
    
    interface ModifyingLockActor {
        boolean requiresModification();
        void modify(ClassLoaderScope scope);
    }
```

And then in `PluginRequestApplicator` we do something like:

```
classLoaderScope.lockWith(new ClassLoaderScope.ModifyingLockActor() {
                private List<Result> autoAppliedPluginRequests;
                
                @Override
                public boolean requiresModification() {
                    autoAppliedPluginRequests = resolvePluginRequests(autoAppliedPlugins, alreadyOnClasspathIgnoringPluginResolver);
                    return !autoAppliedPluginRequests.isEmpty();
                }

                @Override
                public void modify(ClassLoaderScope scope) {
                    scriptHandler.dropResolvedClassPath();

                    final Map<Result, PluginImplementation<?>> pluginImplementations = newLinkedHashMap();
                    applyPlugins(scriptHandler, classLoaderScope, pluginApplyActions, pluginImplementations, autoAppliedPluginRequests);
                    defineScriptHandlerClassScope(scriptHandler, classLoaderScope, pluginImplementations.values());
                }
            });
```
 I wouldn't want to introduce something that allows someone to just arbitrarily unlock a classloader scope at any point.

Comment (wolfs) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:122]: Yes, I think that would be better. I would prefer to throw away the classloader scope instance, or make a mutable copy of it if we need to modify it instead of trying to unlock things. Though given how the code is currently structured that would make it more complex.

**Comment by sorin-florea** [comment]
@bot-gradle test this

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java (hunk 5 above)
Comment (sorin-florea) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java]: @wolfs @ghale I think we can avoid all this **unlocking/locking/throwing stuff away** without introducing too much complexity. 

```
public class MutableClassLoaderScope implements ClassLoaderScope {

    private ClassLoaderScope delegate;

    public MutableClassLoaderScope(
        ClassLoaderScope delegate
    ) {
        this.delegate = delegate;
    }

   ...

    @Override
    public ClassLoaderScopeId getId() {
        return delegate.getId();
    }

   ...
 
    public void mutate(MutateActor mutateActor) {
        if (mutateActor.requiresMutation()) {
            ClassLoaderScope child = delegate.createChild(delegate.getId() + "-child", null);
            mutateActor.modify(child);
            child.lock();

            delegate = child;
        }
    }


    public interface MutateActor {
        boolean requiresMutation();

        void modify(ClassLoaderScope scope);
    }
}
```

And we would use it like this:

```
        classLoaderScope.mutate(new MutableClassLoaderScope.MutateActor() {
            private List<Result> autoAppliedPluginRequests;

            @Override
            public boolean requiresMutation() {
                final PluginResolver alreadyOnClasspathIgnoringPluginResolver = new AlreadyOnClasspathIgnoringPluginResolver(effectivePluginResolver,
                    new ClassloaderBackedPluginDescriptorLocator(scriptHandler.getClassLoader())
                );

                autoAppliedPluginRequests = resolvePluginRequests(autoAppliedPlugins, alreadyOnClasspathIgnoringPluginResolver);

                return !autoAppliedPluginRequests.isEmpty();
            }

            @Override
            public void modify(ClassLoaderScope scope) {
                scriptHandler.dropResolvedClassPath();

                final Map<Result, PluginImplementation<?>> pluginImplementations = newLinkedHashMap();
                applyPlugins(scriptHandler, classLoaderScope, pluginApplyActions, pluginImplementations, autoAppliedPluginRequests);
                defineScriptHandlerClassScope(scriptHandler, classLoaderScope, pluginImplementations.values());
            }
        });
```

And [wrap](https://github.com/gradle/gradle/blob/ea1f76efda73a4789114a338c0b7719fdbdf7ef8/subprojects/core/src/main/java/org/gradle/api/internal/initialization/AbstractClassLoaderScope.java#L88) the `DefaultClassLoaderScope` in a `MutableClassLoaderScope`.

Even better, we can check if the delegate is locked and either create a child or mutate the delegate based on that.

Comment (wolfs) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java]: I don't think this is a bad idea. Though I wonder if this would confuse some other code since the classloader scope will now suddenly have a different name. Let's see what @ghale thinks about this.

**Comment by sorin-florea** [comment]
@bot-gradle test this

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java (hunk 5 above)
Comment (ghale) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java]: I like it, too.  I think we'll want to be very careful how this gets handled when serializing/unserializing from the configuration cache, and I think we want to use a descriptive name for the child scope (e.g. "-plugins" or something like that) but otherwise I like the idea that it keeps everything tidy inside the scope itself.

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/management/internal/autoapply/DefaultAutoAppliedPluginHandler.java (hunk 4 above)
Comment (sorin-florea) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/management/internal/autoapply/DefaultAutoAppliedPluginHandler.java:61]: Done

**Comment by sorin-florea** [comment]
@bot-gradle test this

**Comment by sorin-florea** [comment]
@bot-gradle test this

**Comment by sorin-florea** [comment]
@bot-gradle test this

**Comment by sorin-florea** [comment]
@bot-gradle test PT

**Review by wolfs — COMMENTED** [review]
I think the production code changes look good now. Now let's add some tests.

**Comment by sorin-florea** [comment]
@bot-gradle test this

**Comment by sorin-florea** [comment]
@bot-gradle test PT

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java [hunk 6]
```diff
@@ -85,61 +88,101 @@ public DefaultPluginRequestApplicator(
     }
 
     @Override
-    public void applyPlugins(final PluginRequests requests, final ScriptHandlerInternal scriptHandler, @Nullable final PluginManagerInternal target, final ClassLoaderScope classLoaderScope) {
-        if (target == null || requests.isEmpty()) {
+    public void applyPlugins(final PluginRequests requests, PluginRequests autoAppliedPlugins, final ScriptHandlerInternal scriptHandler, @Nullable final PluginManagerInternal target, final ClassLoaderScope classLoaderScope) {
```
[the remark this answers is not in the document]
Comment (sorin-florea) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:91]: This would mean we have to cast it everywhere where this method is called or propagate the change. There are a lot of places where this is used, I'm not sure what is the best way to handle it.

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java [hunk 7]
```diff
@@ -85,63 +88,90 @@ public DefaultPluginRequestApplicator(
...
+        if (target == null || (requests.isEmpty() && autoAppliedPlugins.isEmpty())) {
             defineScriptHandlerClassScope(scriptHandler, classLoaderScope, Collections.emptyList());
             return;
         }
 
         PluginArtifactRepositories resolveContext = pluginRepositoriesProvider.createPluginResolveRepositories();
 
         final PluginResolver effectivePluginResolver = wrapInAlreadyInClasspathResolver(classLoaderScope, resolveContext);
-        if (!requests.isEmpty()) {
+        if (!requests.isEmpty() || !autoAppliedPlugins.isEmpty()) {
```
[the remark this answers is not in the document]
Comment (sorin-florea) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java]: Done, does it look better now?

File: subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanAutoApplyClasspathIntegrationTest.groovy [hunk 8]
```diff
@@ -0,0 +1,142 @@
...
+    }
+
+    def "task is fetched from cache when using --scan"() {
+        when:
+        succeeds "cacheableTask"
+
+        then:
+        fixture.appliedOnce(output)
+        fixture.assertAutoApplied(output, false)
+        result.assertTaskExecuted(":cacheableTask")
```
Comment (wolfs) [inline subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanAutoApplyClasspathIntegrationTest.groovy:132]:
```suggestion
        executedAndNotSkipped(":cacheableTask")
```

That should do the trick as well.

File: subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanAutoApplyClasspathIntegrationTest.groovy [hunk 9]
```diff
@@ -0,0 +1,142 @@
...
+    def "transitively applied build scan plugin disables auto-application"() {
+        when:
+        succeeds "cacheableTask", "--${BuildScanOption.LONG_OPTION}"
+
+        then:
+        fixture.appliedOnce(output)
+        fixture.assertAutoApplied(output, false)
+    }
+
+    def "task is fetched from cache when using --scan"() {
```
Comment (wolfs) [inline subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanAutoApplyClasspathIntegrationTest.groovy:125]:
```suggestion
    def "task is up-to-date when using --scan"() {
```

It won't be fetched from the build cache since the build cache is not switched on for your test.

File: subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanAutoApplyClasspathIntegrationTest.groovy [hunk 10]
```diff
@@ -0,0 +1,142 @@
...
+        fixture.assertAutoApplied(output, false)
+        result.assertTaskExecuted(":cacheableTask")
+
+        when:
+        succeeds "cacheableTask", "--${BuildScanOption.LONG_OPTION}"
+
+        then:
+        fixture.appliedOnce(output)
+        fixture.assertAutoApplied(output, false)
+        result.assertTaskSkipped(":cacheableTask")
```
Comment (wolfs) [inline subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanAutoApplyClasspathIntegrationTest.groovy:140]:
```suggestion
        skipped(":cacheableTask")
```

A little bit simpler.

**Comment by sorin-florea** [comment]
@bot-gradle test this

**Comment by sorin-florea** [comment]
@bot-gradle test this

File: subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanAutoApplyClasspathIntegrationTest.groovy [hunk 11]
```diff
@@ -0,0 +1,142 @@
...
+                doLast {
+                    outputFile.text = inputFile.text
+                }
+            }
+        """
+    }
+
+    def "transitively applied build scan plugin disables auto-application"() {
+        when:
+        succeeds "cacheableTask", "--${BuildScanOption.LONG_OPTION}"
```
Comment (alllex) [inline subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanAutoApplyClasspathIntegrationTest.groovy:118]: 💅 I think the integration tests are slightly better readable if we use the option names as literals, rather than referencing the production code fields.

Comment (sorin-florea) [reply subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanAutoApplyClasspathIntegrationTest.groovy]: done

**Comment by sorin-florea** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]

**Comment by sorin-florea** [comment]
@bot-gradle test this

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java [hunk 12]
```diff
@@ -85,61 +88,101 @@ public DefaultPluginRequestApplicator(
...
+                    new ClassloaderBackedPluginDescriptorLocator(scriptHandler.getClassLoader())
+                );
+
+                autoAppliedPluginRequests = resolvePluginRequests(autoAppliedPlugins, alreadyOnClasspathIgnoringPluginResolver);
+
+                return !autoAppliedPluginRequests.isEmpty();
+            }
+
+            @Override
+            public void mutate(ClassLoaderScope scope) {
```
Comment (ghale) [inline subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:137]: This interface doesn't feel quite right anymore.  For instance, the `MutableClassLoaderScope` always delegates to the child.  We pass in the child classloaderScope here, but then we never use it and we just take advantage of the delegation on the parent.  This interface made sense before all the delegation, because it made it more explicitly something to be used while building the classloaderScope.  With the delegation, we've effectively made it safe to mutate the classloaderScope without unlocking things, so the previous concern about making this only something that could be done while building/locking the scope is not as important now.  I think we could just get rid of the `MutateActor` and have a `mutate(String childSuffix)` method to call when you need to mutate the scope after locking, which creates the child and updates the delegation.  

So this becomes:

```
    private void resolveAutoAppliedPlugins(PluginRequests autoAppliedPlugins, ScriptHandlerInternal scriptHandler, ClassLoaderScope classLoaderScope, PluginResolver effectivePluginResolver, List<Consumer<PluginManagerInternal>> pluginApplyActions) {
        final PluginResolver alreadyOnClasspathIgnoringPluginResolver = new AlreadyOnClasspathIgnoringPluginResolver(effectivePluginResolver,
            new ClassloaderBackedPluginDescriptorLocator(scriptHandler.getClassLoader())
        );
        List<Result> autoAppliedPluginRequests = resolvePluginRequests(autoAppliedPlugins, alreadyOnClasspathIgnoringPluginResolver);
        if (!autoAppliedPluginRequests.isEmpty()) {
            ((MutableClassLoaderScope) classLoaderScope).mutate("-plugins");
            scriptHandler.dropResolvedClassPath();

            final Map<Result, PluginImplementation<?>> pluginImplementations = newLinkedHashMap();
            applyPlugins(scriptHandler, classLoaderScope, pluginApplyActions, pluginImplementations, autoAppliedPluginRequests);
            defineScriptHandlerClassScope(scriptHandler, classLoaderScope, pluginImplementations.values());
        }
    }
```
Or something like that.  WDYT?

**Review by ghale — CHANGES_REQUESTED** [review]
I think this looks pretty good, but your good idea about using delegation in `MutableClassLoaderScope` means we can probably simplify some things a little more.

File: subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java (hunk 12 above)
Comment (sorin-florea) [reply subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java:137]: I like this approach. I've added it.

**Comment by sorin-florea** [comment]
@bot-gradle test this

**Review by ghale — APPROVED** [review]

File: subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java [hunk 13]
```diff
@@ -0,0 +1,117 @@
...
+    public void onReuse() {
+        delegate.onReuse();
+    }
+
+    @Override
+    public ClassLoaderScope getOriginalScope() {
+        return delegate;
+    }
+
+    public void mutate(String childSuffix) {
```
Comment (wolfs) [inline subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java:114]: ❌ Can we have a Javadoc on this method to describe what it does? I wonder if `mutate` is still the right work. Maybe `replaceWithMutableChild` or `asMutable` might work. WDYT?

Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java:114]: +1 to `asMutable()`

Comment (snoopcheri) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java:114]: Doesn't `asMutable()` sound like a method returning a mutable object?

Comment (sorin-florea) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java:114]: I agree with @snoopcheri. What about `makeMutable()`?

Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java:114]: We _could_ make `asMutable()` available on `ClassLoaderScope` and have it return a `MutableClassLoaderScope`.  For `DefaultClassLoaderScope` it would create/return a `MutableClassLoaderScope`.  For a `MutableClassLoaderScope`, it would return itself.  For `RootClassLoaderScope` and `ImmutableClassLoaderScope`, it would throw `UnsupportedOperationException`.

I don't feel strongly about this in any case as this isn't user-facing.  `mutate()` and `asMutable()` are my first choices.  I'm not a fan of `replaceWithMutableChild()` or `makeMutable()` but if others feel strongly, I don't object.

Comment (sorin-florea) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java:114]: The only thing I am not so sure about is what should the behavior of `DefaultClassLoaderScope` be. If it is locked, we cannot simply wrap it in a `MutableClassLoaderScope` because it would still not be mutable due to locking. Should we create a child, similar to what we do in `MutableClassLoaderScope`? For now, I think it's fine to throw an `UnsupportedOperationException` and implement it in the future if we need it.

**Comment by sorin-florea** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java (hunk 13 above)
Comment (ghale) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java]: I was thinking `DefaultClassLoaderScope.asMutable()` would return `new MutableClassLoaderScope(this).asMutable()`.  IOW, `asMutable()` might return the same object or a new object, but whatever it returns will be mutable.  Admittedly, it's not quite right, and I'm not in love with the idea, just throwing out options.

I think leaving it unimplemented for now is fine.

**Review by wolfs — APPROVED** [review]
I think the current state is good enough. I think we can keep `asMutable()` with the current meaning.

**Comment by sorin-florea** [comment]
@bot-gradle test PT

**Comment by sorin-florea** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java (hunk 13 above)
Comment (sorin-florea) [reply subprojects/core/src/main/java/org/gradle/api/internal/initialization/MutableClassLoaderScope.java]: @ghale, I will merge this. If you have further feedback I will address it in a subsequent PR.

**Comment by sorin-florea** [comment]
@bot-gradle test and merge
