### PR TITLE
Fix tests that need -XstartOnFirstThread

### LINKED ISSUE #864: Test task and '-XstartOnFirstThread' makes gradle hang
### Expected Behavior

When test has specified the following arguments:

```gradle
test {
    jvmArgs '-XstartOnFirstThread'
}
```

the JUnit test cases should be started on the first thread.

### Current Behavior

The tests do not start on the first thread.

### Context

This is required for SWT tests to run on mac.

As of [May 2016](https://issues.gradle.org/browse/GRADLE-3290?focusedCommentId=21024&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21024), the Gradle test VM is started by `org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor` which uses `org.gradle.process.internal.worker.DefaultWorkerProcessBuilder` to create a `WorkerProcess` and start it.
All this is called from `org.gradle.api.internal.tasks.testing.detection.DefaultTestExecuter`.

### Steps to Reproduce (for bugs)

```
git clone https://github.com/diffplug/durian-swt
cd durian-swt
git checkout macGradleRepro
gradlew test
```

### Your Environment

Any version of macOS.

### PR DESCRIPTION
**Pull request by nedtwigg**
Fixes #864, so that -XstartOnFirstThread for the JVM test runner now works.

### Context

**Problem**

If you are working with OpenGL or SWT on MacOS, then you must:

1. start the JVM with `-XstartOnFirstThread`
2. run your tests on the first thread which the VM starts.

So far, this has been impossible in Gradle because `TestWorker.execute()`  gets called on that special first thread, and then hangs that special thread on `completed.await()` (L75 in the snippet of old code below).

https://github.com/gradle/gradle/blob/0522ebb4cb37b87a03635e3218db5b885337448a/subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java#L62-L75

All of the real work happens in `startProcessing()`, `processTestClass(TestClassRunInfo testClass)`, and `stop()`, which get called from a communication thread which then also ends up being where the tests execute. Because of this, it is impossible for tests to access the special first thread which was created by `-XstartOnFirstThread`

**Solution**
The solution is for the main thread to process arguments from a queue, which gets populated by `startProcessing/processTestClass/stop`.

https://github.com/nedtwigg/gradle/blob/7bcc1f140b53be3b92673b113e0eacfc94c14ab1/subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java#L140-L153

I haven't profiled it, but I think this might be a minor performance improvement, since the tests can execute in parallel with the worker message deserialization, rather than in series with it. 

**Why it is necessary**
Without this change, it is not possible for MacOS users to use Gradle for OpenGL or SWT development.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] **would just be a mac-specific confirmation that test code is running on main thread** Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] **well-tested by existing tests** Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] **N/A** Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java [hunk 1]
```diff
@@ -42,18 +42,25 @@
...
+import java.util.concurrent.LinkedBlockingQueue;
 
 public class TestWorker implements Action<WorkerProcessContext>, RemoteTestClassProcessor, Serializable, Stoppable {
     private static final Logger LOGGER = LoggerFactory.getLogger(TestWorker.class);
     public static final String WORKER_ID_SYS_PROPERTY = "org.gradle.test.worker";
     public static final String WORKER_TMPDIR_SYS_PROPERTY = "org.gradle.internal.worker.tmpdir";
 
     private final WorkerTestClassProcessorFactory factory;
-    private CountDownLatch completed;
+    private LinkedBlockingQueue<TestClassRunInfo> toRun;
```
Comment (nedtwigg) [inline subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java:53]: We could replace the unbounded `LinkedBlockingQueue` with `ArrayBlockingQueue(capacity)`. This would reduce GC pressure a bit, and also cause `processTestClass(TestClassRunInfo testClass)` to sometimes block until the queue has space. Right now `processTestClass` is always able to complete immediately because the unbounded queue can hold the backlog.

**Comment by nedtwigg** [comment]
Anything I can do to help this get merged?

**Comment by ljacomet** [comment]
@nedtwigg Thanks for the contribution. Let me see what CI has to say about this change.
Note that we are close to wrapping Gradle 7.2 so I cannot guarantee this change will make it in.

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by nedtwigg** [comment]
Thanks very much! I just merged latest master to sync up the last ~30 days worth of stuff. @bot-gradle test QF

**Comment by nedtwigg** [comment]
@ljacomet Can you trigger another "test QF"? All test failures were fixed (on my local machine, at least) by 8498205.

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by nedtwigg** [comment]
Thanks for triggering tests! Only one test is failing, in `org.gradle.smoketests`, a test named [`ThirdPartyGradleModuleMetadataSmokeTest.produces expected metadata and can be consumed`](https://github.com/gradle/gradle/blob/master/subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy).

The failed assertion looks like this:

```
trimmedOutput(result) == []
|             |       |
|             |       false
|             <org.gradle.testkit.runner.internal.FeatureCheckBuildResult@242a67d0 delegateBuildResult=org.gradle.testkit.runner.internal.DefaultBuildResult@4301a0ad outputFeatureCheck=org.gradle.testkit.runner.internal.feature.BuildResultOutputFeatureCheck@6c9f9d0c>
[Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01, Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01, Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01, Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01, Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01]

	at org.gradle.smoketests.ThirdPartyGradleModuleMetadataSmokeTest.produces expected metadata and can be consumed(ThirdPartyGradleModuleMetadataSmokeTest.groovy:98)
```

The only file this PR changes is `TestWorker.java`. The test failure is not related to test running at all, only to publishing artifacts.

Should I merge `master` into this PR and then resubmit for an RFM build?

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java [hunk 2]
```diff
@@ -42,18 +42,25 @@
...
     private TestClassProcessor processor;
     private TestResultProcessor resultProcessor;
 
+    private static final TestClassRunInfo SENTINEL_START_STOP = new TestClassRunInfo() {
+        @Override
+        public String getTestClassName() {
+            throw new UnsupportedOperationException();
+        }
+    };
+
```
Comment (ghale) [inline subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java:63]: I don't see a problem with the spirit of the change, but the sentinel object feels pretty awkward.  Did you consider implementing this as a wait/notify loop with a state enum?  (happy to elaborate if it's not clear what I mean by that)

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java (hunk 1 above)
Comment (ghale) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java:53]: I think an unbounded queue is just asking for trouble.  _Someone_ will be running a test suite with a billion small tests and a small worker heap size and they won't have any way to alleviate the issue without just adding heap, which may have other implications.  This should be bounded in some way.

**Review by ghale — CHANGES_REQUESTED** [review]
I left some comments on a few improvements I think we can make before merging.

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java (hunk 1 above)
Comment (nedtwigg) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java]: I think that's smart. I believe the code before this change was equivalent to `ArrayBlockingQueue(1)`. Probably you get a *little* bit of performance help by letting them buffer a bit. Sizing it is a bit arbitrary, but I'll try `128` with this rough reasoning:

`1KiB` allocator block / `8 byte` pointer on 64-bit machines = `128`

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java (hunk 2 above)
Comment (nedtwigg) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java:64]: I did consider a wait/notify loop. That works well enough for marking the `start`, but it doesn't help with marking the end. Maybe something like this?

- wait loop for start (removes need for a start sentinel)
- poll queue for test events
- on stop, do an interrupt rather than send sentinel (removes need for a stop sentinel)

To me, that control flow is harder to read than the existing sentinel logic. If we had Typescript-style union types, I would do `type Event = TestClassRunInfo | "start" | "stop"`, which I think would be the most elegant solution. But since we don't have them, the sentinel seems like the lesser of evils to me, especially since there is only one start and stop and they always happen at the beginning and end.

Happy to revise if I'm misunderstanding or you have a strong preference for a different approach.

**Review by ghale — CHANGES_REQUESTED** [review]

File: subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java (hunk 2 above)
Comment (nedtwigg) [reply subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java:73]: Good call, I think it's smart to have separate start and stop sentinels, and for those sentinels to have helpful `toString()`. I just pushed up a commit which accomplishes this goal without introducing `interface TestProcessingCommand` and `enum StateChange`, like so:

```java
    private static class StateChangeCommandSentinel implements TestClassRunInfo {
        @Override
        public String getTestClassName() {
            throw new UnsupportedOperationException(toString());
        }

        @Override
        public String toString() {
            String kind = this == START_PROCESSING ? "START" : "STOP";
            return "StateChangeCommandSentinel{" + kind + "_PROCESSING}";
        }
    }

    private static final StateChangeCommandSentinel START_PROCESSING = new StateChangeCommandSentinel();
    private static final StateChangeCommandSentinel STOP_PROCESSING = new StateChangeCommandSentinel();
```

Saves a tiny bit of code and a tiny bit of GC pressure for I think the same level of clarity and debuggability, but I'm happy to copy your demo code verbatim if you prefer.

**Comment by Dmytro-Fedoryshyn** [comment]
Hello, @nedtwigg. I am running a JUnit test suite - which is defined by a method annotated with `@TestFactory`. The tests are running in a test worker thread. To display SWT GUI, we also need to run an event loop, something like:
```java
while (!shell.isDisposed()) {
    if (!display.readAndDispatch()) {
        display.sleep();
    }
}
```

As we already know, it has to be done in the test worker thread. This way, the test execution hangs, as both the event loop and tests run in the same thread. Could you please tell me if there is any way to solve this issue?

**Comment by nedtwigg** [comment]
Maybe take a look at this: https://github.com/diffplug/durian-swt/blob/main/durian-swt/src/main/java/com/diffplug/common/swt/InteractiveTest.java
