### PR TITLE
Document incremental change reporting behavior when discarding path information

### LINKED ISSUE #17916: Path sensitivity `NONE` in incremental task causes same file to be added then removed
If you have an incremental task with an input with path sensitivity `NONE` and run that task incrementally, you get two changes in `inputChanges.getFileChanges(inputWithoutPathSensitivity).forEach { ... }`, first an `ADDED` for the changed file, then a `REMOVED` for the same file.

This can of course be appropriate, as I defined I'm not interested in the file path, just in the content.
But it nevertheless confused me majorly that I first got an `ADDED` then a `REMOVED` for the same file.
I would at least have expected to first get `REMOVED`, then `ADDED`.

Or maybe actually even a `MODIFIED`.
Even if I do not have a dependency on the file name, but only on the content, it might be more appropriate to get a `MODIFIED` change, as that is what happened.

At the very least the behavior in the `NONE` case should imho be more clearly documented as I didn't spontaneously find some description of this behavior.

### Steps to Reproduce 
- Have an incremental task with a task input with path sensitivity `NONE`
- Run the task so that all inputs are processed successfully
- Modify one of the input files
- Rerun the task

### Your Environment
Gradle 7.1.1

### PR DESCRIPTION
**Pull request by lptr**
When using `@PathSensitive(PathSensitivity.NONE)` or `@Classpath` on an incremental input, Gradle will not report `MODIFIED` events, but instead will produce a pair of an `ADDED` and a `REMOVED` event, since there is no identity to connect the old state and the new.

Fixes #17916

### CODE REVIEW

File: subprojects/core-api/src/main/java/org/gradle/api/tasks/CompileClasspath.java [hunk 1]
```diff
@@ -35,6 +35,14 @@
  *     <li>Changes to directories, including directory entries in Jars.</li>
  * </ul>
  *
+ * <p>
+ *     When used on an {@literal @}{@link org.gradle.work.Incremental} input, Gradle will not produce any
+ *     {@link org.gradle.work.ChangeType#MODIFIED} events.
```
Comment (wolfs) [inline subprojects/core-api/src/main/java/org/gradle/api/tasks/CompileClasspath.java:40]: ❌ This is not true. If possible, we try to identify elements on classpath inputs via the absolute path to produce modified events. So if, for example, a project JAR changes, we report it as `MODIFIED`. For external dependencies, that doesn't work, though.

See for example this test: https://github.com/gradle/gradle/blob/9bd595ea31b56b19fd2487c928dd37b201c3eb05/subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/changes/ClasspathCompareStrategyTest.groovy#L72-L78

**Review by wolfs — CHANGES_REQUESTED** [review]

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by lptr** [comment]
@bot-gradle test and merge please.
