### PR TITLE
Make help --task config cache compatible

### LINKED ISSUE #21056: Task `help --task help` fails on the second run when configuration cache is enabled
### Expected Behavior
The task runs with the same output.

### Current Behavior
The task runs normally on the first run and fails on the second one with an error:
```
Rustam.Musin@UNIT-2257 gradle-help-task-issue % ./gradlew help --task help
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: help --task help

> Task :help
Detailed task information for help

Path
     :help

Type
     Help (org.gradle.configuration.Help)

Options
     --task     The task to show help for.

Description
     Displays a help message.

Group
     help

0 problems were found storing the configuration cache.

See the complete report at file:///Users/Rustam.Musin/my/gradle-help-task-issue/build/reports/configuration-cache/9mvlkblqk1hawnen5cx3q7g1e/b3tsmfa1prg1pxaqtnzmgrazr/configuration-cache-report.html

BUILD SUCCESSFUL in 744ms
1 actionable task: 1 executed
Configuration cache entry stored.
Rustam.Musin@UNIT-2257 gradle-help-task-issue % ./gradlew help --task help
Configuration cache is an incubating feature.
Reusing configuration cache.
> Task :help FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':help'.
> A problem occurred configuring root project 'gradle-help-task-issue'.
   > Failed to apply plugin 'org.gradle.help-tasks'.
      > Cannot add task 'help' as a task with that name already exists.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 543ms
1 actionable task: 1 executed
Configuration cache entry reused.
Rustam.Musin@UNIT-2257 gradle-help-task-issue % 
```

### Context
Just wanted to try out the configuration cache, and the attempt has been failed :(

### Steps to Reproduce 
0. Use Gradle 7.4.2 on macOS Monterey x86_64
1. Download the project
2. Run `./gradlew help --task help` and see the correct output
3. Run the same command again and see the error

I've attached the sample project
[gradle-help-task-issue.zip](https://github.com/gradle/gradle/files/8948630/gradle-help-task-issue.zip).

### PR DESCRIPTION
**Pull request by abstratt**
Make help task config cache compatible

Collects TaskDetails vanilla POJOs from tasks during configuration,
avoiding relying on Project/Task objects during execution.

Fixes #21056

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by abstratt** [comment]
@bot-gradle test this

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheEnablementIntegrationTest.groovy [hunk 1]
```diff
@@ -98,4 +98,21 @@ class ConfigurationCacheEnablementIntegrationTest extends AbstractConfigurationC
         "long option"     | DISABLE_CLI_OPT
         "system property" | DISABLE_SYS_PROP
     }
+
```
Comment (abstratt) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheEnablementIntegrationTest.groovy:101]: From https://github.com/gradle/gradle/pull/21318

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java [hunk 2]
```diff
@@ -136,6 +137,9 @@ private void printDefaultHelp(StyledTextOutput output, BuildClientMetaData metaD
 
     @Option(option = "task", description = "The task to show help for.")
     public void setTaskPath(String taskPath) {
+        if (StringUtils.isNotEmpty(taskPath)) {
```
Comment (abstratt) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java:140]: As proposed by https://github.com/gradle/gradle/pull/21318

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java [hunk 3]
```diff
@@ -136,6 +136,7 @@ private void printDefaultHelp(StyledTextOutput output, BuildClientMetaData metaD
 
     @Option(option = "task", description = "The task to show help for.")
     public void setTaskPath(String taskPath) {
+        notCompatibleWithConfigurationCache("Task requires access to Gradle model");
```
Comment (abstratt) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java:139]: From https://github.com/gradle/gradle/pull/21318

**Comment by abstratt** [comment]
@bot-gradle help

**Comment by abstratt** [comment]
@bot-gradle test PRF

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy [hunk 4]
```diff
@@ -25,22 +25,29 @@ import spock.lang.Issue
...
         then:
         firstRunOutput == secondRunOutput
+
+        where:
+        task            | options
+        "help"          | []
+        "properties"    | []
+        "dependencies"  | []
+        "help"          | ["--task", "help"]
     }
```
Comment (abstratt) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy:51]: @bamboo I remember you had some feedback about this test. My goal here was to have a cheap check for many help-plugin related tasks for an empty project.

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java [hunk 5]
```diff
@@ -15,24 +15,16 @@
  */
```
Comment (abstratt) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java:15]: Changes in this class are basically replacing usage of Task with TaskDetails

**Comment by abstratt** [comment]
@bot-gradle test PRF

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetails.java [hunk 6]
```diff
@@ -0,0 +1,159 @@
...
+        String path = task.getPath();
+        int projectDepth = StringUtils.countMatches(path, Project.PATH_SEPARATOR);
+        List<OptionDetails> options = optionReader.getOptions(task).stream().map(OptionDetails::from).collect(Collectors.toList());
+        Class<?> declaredTaskType = getDeclaredTaskType(task);
+        String taskType = declaredTaskType.getName();
+        String shortTypeName = declaredTaskType.getSimpleName();
+        return new TaskDetails(path, taskType, shortTypeName, task.getDescription(), task.getGroup(), projectDepth, options);
+    }
+
+    private static Class<?> getDeclaredTaskType(Task original) {
```
Comment (abstratt) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetails.java:151]: From: https://github.com/gradle/gradle/pull/21419/files#diff-aa610447a818dee3818295caf30a9c8b96b75d7cda46eb3f89922c8b31ba6b01L113

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java [hunk 7]
```diff
@@ -92,64 +83,48 @@ public void print(StyledTextOutput output) {
...
-        taskTypes.addAll(collect(tasks, this::getDeclaredTaskType));
-
-        ListMultimap<Class<?>, Task> tasksGroupedByType = ArrayListMultimap.create();
-        for (final Class<?> taskType : taskTypes) {
-            tasksGroupedByType.putAll(taskType, filter(tasks, element -> getDeclaredTaskType(element).equals(taskType)));
-        }
-        return tasksGroupedByType;
-    }
-
-    private Class<?> getDeclaredTaskType(Task original) {
```
Comment (abstratt) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java:113]: Moved to: https://github.com/gradle/gradle/pull/21419/files#diff-3b5e985c51e6e78724054aee90f48c61b3e0425da0cf96cee6c653f9afcdf3c1R151

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java [hunk 8]
```diff
@@ -92,64 +83,48 @@ public void print(StyledTextOutput output) {
...
 
-            if (multipleClasses) {
+            if (multipleTaskTypes) {
                 output.println();
                 output.println("----------------------");
             }
         }
     }
 
-    private ListMultimap<Class<?>, Task> groupTasksByType(List<Task> tasks) {
```
Comment (abstratt) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java:102]: Replaced by: https://github.com/gradle/gradle/pull/21419/files#diff-aa610447a818dee3818295caf30a9c8b96b75d7cda46eb3f89922c8b31ba6b01R93

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java [hunk 9]
```diff
@@ -31,12 +33,21 @@
...
 
+import java.util.stream.Collectors;
+
 import static org.gradle.internal.logging.text.StyledTextOutput.Style.UserInput;
 
 @DisableCachingByDefault(because = "Produces only non-cacheable console output")
 public class Help extends DefaultTask {
     private String taskPath;
 
+    private ListProperty<TaskDetails> tasks = getObjectFactory().listProperty(TaskDetails.class);
```
Comment (abstratt) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java:44]: ListProperty is meant for tracking dynamic additions/removals. Consider using TaskDetailsModel (parent) and regular Property (TaskDetailsModel itself would contain a list of TaskDetail).

Look into finalizeValueOnRead() to cause the value to be computed only once (mapping task selection -> task details model). We will need the value not only during execution, but when storing the cache entry.

**Comment by abstratt** [comment]
@bot-gradle test PRF

**Comment by abstratt** [comment]
@bot-gradle test PRF

**Comment by abstratt** [comment]
@bot-gradle test PRF

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java [hunk 10]
```diff
@@ -35,7 +36,18 @@
 
 @DisableCachingByDefault(because = "Produces only non-cacheable console output")
 public class Help extends DefaultTask {
-    private String taskPath;
+    private final Property<String> taskPath = getObjectFactory().property(String.class);
+
+    private final Property<TaskDetailsModel> taskModel = getObjectFactory().property(TaskDetailsModel.class).convention(taskPath.map(this::mapFromTaskPath));
```
Comment (abstratt) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java:41]: Note that I looked into marking `taskModel` as `finalizeValueOnRead()` in an initialization block, however I am still not clear what the goal of that is in our use case, so I removed that bit. I wondered if it was to avoid having the transformer invoked twice, but in my tests, the transformer was still invoked twice, once during cache storing, and another during execution (maybe that is expected, and the intent is then probably something else).

```
java.lang.Throwable: Mapping showTask
        at org.gradle.configuration.Help.mapFromTaskPath(Help.java:158)
        at org.gradle.api.internal.provider.TransformBackedProvider.mapValue(TransformBackedProvider.java:73)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateExecutionTimeValue(TransformBackedProvider.java:57)
        at org.gradle.api.internal.provider.MappingProvider.calculateExecutionTimeValue(MappingProvider.java:64)
        at org.gradle.configurationcache.serialization.codecs.FixedValueReplacingProviderCodec.encodeProvider(ProviderCodecs.kt:72)
        at org.gradle.configurationcache.serialization.codecs.PropertyCodec.encode(ProviderCodecs.kt:249)
        at org.gradle.configurationcache.serialization.codecs.PropertyCodec.encode(ProviderCodecs.kt:241)
        at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:52)
        at org.gradle.configurationcache.serialization.DefaultWriteContext.write(Contexts.kt:85)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyWriterKt.writeNextProperty(BeanPropertyWriter.kt:96)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyWriter.writeStateOf(BeanPropertyWriter.kt:55)
        ...
```

```
java.lang.Throwable: Mapping showTask
        at org.gradle.configuration.Help.mapFromTaskPath(Help.java:158)
        at org.gradle.api.internal.provider.TransformBackedProvider.mapValue(TransformBackedProvider.java:73)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:65)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:102)
        at org.gradle.api.internal.provider.MappingProvider.calculateOwnValue(MappingProvider.java:55)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:102)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.withFinalValue(AbstractMinimalProvider.java:158)
        at org.gradle.api.internal.provider.DefaultProperty.finalValue(DefaultProperty.java:133)
        at org.gradle.api.internal.provider.DefaultProperty.finalValue(DefaultProperty.java:26)
        at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:240)
        at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:232)
        at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:128)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:83)
        at org.gradle.configuration.Help.printTaskHelp(Help.java:99)
        at org.gradle.configuration.Help.displayHelp(Help.java:92)
...
```

**Comment by abstratt** [comment]
@bot-gradle help

**Comment by abstratt** [comment]
@bot-gradle clean

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy [hunk 11]
```diff
@@ -25,22 +25,74 @@ import spock.lang.Issue
...
+        "properties"    | []
+        "dependencies"  | []
+        "help"          | ["--task", "help"]
+    }
+
+    def "can store task selection success/failure for :help --task"() {
+        def configurationCache = newConfigurationCacheFixture()
+        buildFile.text = """
+        task aTask
+"""
```
Comment (bamboo) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy:57]: 💄 Indentation is off. See how we do on other tests.

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy [hunk 12]
```diff
@@ -25,22 +25,74 @@ import spock.lang.Issue
...
+        configurationCacheFails "help", "--task", "cTask"
+        then:
+        failure.assertHasCause("Task 'cTask' not found in root project")
+        configurationCache.assertStateStored()
+
+        when:
+        configurationCacheFails "help", "--task", "bTask"
+        then:
+        failure.assertHasCause("Task 'bTask' not found in root project")
+        configurationCache.assertStateLoaded()
```
Comment (bamboo) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy:74]: Nice! 👍

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy [hunk 13]
```diff
@@ -25,22 +25,74 @@ import spock.lang.Issue
...
+        when:
+        configurationCacheFails "help", "--task", "cTask"
+        then:
+        failure.assertHasCause("Task 'cTask' not found in root project")
+        configurationCache.assertStateLoaded()
+
+        when:
+        buildFile << """
+        task bTask
+"""
```
Comment (bamboo) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy:91]: 💄 Indentation.

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java (hunk 10 above)
Comment (bamboo) [reply subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java:41]: It should still be marked `finalizeValueOnRead` because that's the intent. The underlying bug will eventually be fixed.

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java [hunk 14]
```diff
@@ -41,48 +33,47 @@
...
     private static final String INDENT = "     ";
-    private final OptionReader optionReader;
 
-    public TaskDetailPrinter(String taskPath, TaskSelection selection, OptionReader optionReader) {
+    public TaskDetailPrinter(String taskPath, Collection<TaskDetails> tasks) {
         this.taskPath = taskPath;
-        this.selection = selection;
-        this.optionReader = optionReader;
+        this.tasks = new ArrayList<>(tasks);
+        Collections.sort(this.tasks, new TaskDetails.Comparator());
```
Comment (bamboo) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java:51]: ❓ Wouldn't it make sense to let the model store a sorted collection already?

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetails.java [hunk 15]
```diff
@@ -0,0 +1,158 @@
...
+
+    public int getProjectDepth() {
+        return projectDepth;
+    }
+
+    public List<OptionDetails> getOptions() {
+        return options;
+    }
+
+    public static TaskDetails from(Task task, OptionReader optionReader) {
```
Comment (bamboo) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetails.java:140]: Nice 👍

**Review by bamboo — COMMENTED** [review]
Looking good!

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java (hunk 10 above)
Comment (abstratt) [reply subprojects/diagnostics/src/main/java/org/gradle/configuration/Help.java:41]: > It should still be marked `finalizeValueOnRead` because that's the intent. The underlying bug will eventually be fixed.

Happy to oblige, however, while I think I understand the mechanics, I still don't get what the intent is for this specific case. What are we aiming to achieve?

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java (hunk 14 above)
Comment (abstratt) [reply subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java:51]: > ❓ Wouldn't it make sense to let the model store a sorted collection already?

I tend to think that is more of a presentation concern, which the printer is responsible for. Could be convinced otherwise.

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy (hunk 11 above)
Comment (abstratt) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy:57]: Indeed, I was following the example of `HelpTaskIntegrationTest`, which I guess does that to avoid the additional tabs/spaces in the last line. Fixing it.

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java (hunk 14 above)
Comment (abstratt) [reply subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailPrinter.java:51]: Again, motivation here was optimization

**Comment by abstratt** [comment]
@bot-gradle test RFN

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailsModel.java [hunk 16]
```diff
@@ -0,0 +1,72 @@
...
+ */
+public class TaskDetailsModel {
+    private final String taskPath;
+    private final List<TaskDetails> tasks;
+    private final TaskSelectionException failure;
+
+    private TaskDetailsModel(String taskPath, List<TaskDetails> tasks) {
+        this.taskPath = taskPath;
+        this.failure = null;
+        this.tasks = new ArrayList<>(tasks);
```
Comment (bamboo) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailsModel.java:41]: 🟡 It seems this defensive copy is unnecessary since the collection is created by this same class just a few lines below, what do you think?

File: subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/HelpTaskIntegrationTest.groovy [hunk 17]
```diff
@@ -466,6 +466,24 @@ BUILD SUCCESSFUL"""
...
+
+        when:
+        fails "help", "--task", "bTask"
+        then:
+        failure.assertHasCause("Task 'bTask' not found in root project '${testDirectory.getName()}'. Some candidates are: 'aTask', 'tasks'")
+
+        when:
+        buildFile << """
+        task bTask
+"""
```
Comment (bamboo) [inline subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/HelpTaskIntegrationTest.groovy:483]: ❌ Indentation is off.

Comment (abstratt) [reply subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/HelpTaskIntegrationTest.groovy:483]: It is consistent with that file though - different subprojects, different conventions?

Comment (bamboo) [reply subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/HelpTaskIntegrationTest.groovy:483]: More likely an oversight or historical reasons.

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailsModel.java (hunk 16 above)
Comment (abstratt) [reply subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetailsModel.java]: Doing the collection to sorted list mapping in the factory method now

**Review by bamboo — APPROVED** [review]
Good stuff! 👍

File: subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetails.java [hunk 18]
```diff
@@ -0,0 +1,156 @@
...
+import java.util.Set;
+import java.util.stream.Collectors;
+
+/**
+ * A configuration-cache friendly view of @{link Task} that only projects information
+ * that is relevant for the @{link Help#} task.
+ */
+@NonNullApi
+class TaskDetails {
+    static Comparator<TaskDetails> DEFAULT_COMPARATOR = (o1, o2) -> {
```
Comment (abstratt) [inline subprojects/diagnostics/src/main/java/org/gradle/configuration/TaskDetails.java:40]: avoiding instantiation of a stateless object

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot test and merge

**Comment by abstratt** [comment]
@bot-gradle help

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
@bot-gradle clean

**Comment by abstratt** [comment]
@bot-gradle cancel

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle cancel

**Comment by abstratt** [comment]
@bot-gradle test and merge
