### PR TITLE
Use CalculatedValue infrastructure to obtain ValueSource's value

### LINKED ISSUE #28566: Gradle build deadlocks when transform input is Property<String> computed from an ArtifactCollection via a ValueSource
*This issue was originally reported at https://issuetracker.google.com/329346760.*

### Gradle version

8.6 (and earlier)

### Steps to reproduce
1. Open [the attached project](https://github.com/gradle/gradle/files/14745995/MyApplication.zip). It is a simple Android project with `app` and `lib`, and has the following additional script in `app/build.gradle.kts` to enable core library desugaring:
```
android {
    compileOptions {
        isCoreLibraryDesugaringEnabled = true
    }
}

dependencies {
    implementation(project(":lib"))
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")
}
```

2. Run `./gradlew assemble -i` one or more times (or `./gradlew :app:mergeLibDexDebug :app:mergeDexRelease -i` to run the mininal tasks that trigger this bug).

3. The deadlock usually happens on the first or second run:
```
Tasks to be executed: [...]
Tasks that were excluded: []
work action Parameters of ClassesDirToClassesTransform (Thread[Execution worker,5,main]) started.
destroyer locations for task group 0 (Thread[Execution worker Thread 9,5,main]) started.
work action Parameters of DexingNoClasspathTransform (Thread[Execution worker,5,main]) started.
Transforming desugar_jdk_libs-2.0.4.jar (com.android.tools:desugar_jdk_libs:2.0.4) with DesugarLibConfigExtractor
Transforming desugar_jdk_libs_configuration-2.0.4.jar (com.android.tools:desugar_jdk_libs_configuration:2.0.4) with DesugarLibConfigExtractor
work action Parameters of DexingNoClasspathTransform (Thread[included builds,5,main]) started.
<-------------> 0% EXECUTING [54s]
> Resolve files of :app:coreLibraryDesugaring
```

### Tracking down the root cause

Attaching the debugger to the Gradle code shows that the deadlock happens on the following threads:

<details>
    <summary>"included builds" @ 27,513 in group "main": MONITOR</summary>

```
obtain:291, DefaultValueSourceProviderFactory$LazilyObtainedValue (org.gradle.api.internal.provider)
calculateOwnValue:256, DefaultValueSourceProviderFactory$ValueSourceProvider (org.gradle.api.internal.provider)
calculateValue:115, AbstractMinimalProvider (org.gradle.api.internal.provider)
calculateOwnValue:81, TransformBackedProvider (org.gradle.api.internal.provider)
getOrNull:105, AbstractMinimalProvider (org.gradle.api.internal.provider)
unpackState:189, AbstractMinimalProvider (org.gradle.api.internal.provider)
processManaged:127, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:98, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processManaged:127, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:98, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processArrayElements:183, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processArray:176, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:92, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processManaged:127, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:98, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
isolate:49, DefaultIsolatableFactory (org.gradle.internal.snapshot.impl)
isolateParametersExclusively:677, DefaultTransform$IsolateTransformParameters (org.gradle.api.internal.artifacts.transform)
doIsolateParameters:668, DefaultTransform$IsolateTransformParameters (org.gradle.api.internal.artifacts.transform)
isolateParameters:662, DefaultTransform$IsolateTransformParameters (org.gradle.api.internal.artifacts.transform)
calculateValue:639, DefaultTransform$IsolateTransformParameters (org.gradle.api.internal.artifacts.transform)
calculateValue:558, DefaultTransform$IsolateTransformParameters (org.gradle.api.internal.artifacts.transform)
lambda$attachValue$0:229, CalculatedValueContainer$CalculationState (org.gradle.internal.model)
call:-1, CalculatedValueContainer$CalculationState$$Lambda$1066/0x00007fe70cd00000 (org.gradle.internal.model)
ofFailable:41, Try (org.gradle.internal)
attachValue:224, CalculatedValueContainer$CalculationState (org.gradle.internal.model)
finalizeIfNotAlready:197, CalculatedValueContainer (org.gradle.internal.model)
run:183, CalculatedValueContainer (org.gradle.internal.model)
execute:94, ActionNode (org.gradle.execution.plan)
execute:27, WorkNodeExecutor (org.gradle.execution.plan)
execute:331, DefaultTaskExecutionGraph$InvokeNodeExecutorsAction (org.gradle.execution.taskgraph)
execute:318, DefaultTaskExecutionGraph$InvokeNodeExecutorsAction (org.gradle.execution.taskgraph)
lambda$execute$0:314, DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction (org.gradle.execution.taskgraph)
run:-1, DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction$$Lambda$2227/0x00007fe70d62d4b0 (org.gradle.execution.taskgraph)
with:80, CurrentBuildOperationRef (org.gradle.internal.operations)
execute:314, DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction (org.gradle.execution.taskgraph)
execute:303, DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction (org.gradle.execution.taskgraph)
execute:463, DefaultPlanExecutor$ExecutorWorker (org.gradle.execution.plan)
run:380, DefaultPlanExecutor$ExecutorWorker (org.gradle.execution.plan)
process:116, DefaultPlanExecutor (org.gradle.execution.plan)
executeWithServices:138, DefaultTaskExecutionGraph (org.gradle.execution.taskgraph)
execute:123, DefaultTaskExecutionGraph (org.gradle.execution.taskgraph)
execute:35, SelectedTaskExecutionAction (org.gradle.execution)
execute:51, DryRunBuildExecutionAction (org.gradle.execution)
call:54, BuildOperationFiringBuildWorkerExecutor$ExecuteTasks (org.gradle.execution)
call:43, BuildOperationFiringBuildWorkerExecutor$ExecuteTasks (org.gradle.execution)
execute:200, DefaultBuildOperationRunner$CallableBuildOperationWorker (org.gradle.internal.operations)
execute:195, DefaultBuildOperationRunner$CallableBuildOperationWorker (org.gradle.internal.operations)
execute:66, DefaultBuildOperationRunner$2 (org.gradle.internal.operations)
execute:59, DefaultBuildOperationRunner$2 (org.gradle.internal.operations)
execute:157, DefaultBuildOperationRunner (org.gradle.internal.operations)
execute:59, DefaultBuildOperationRunner (org.gradle.internal.operations)
call:53, DefaultBuildOperationRunner (org.gradle.internal.operations)
call:64, DefaultBuildOperationExecutor (org.gradle.internal.operations)
execute:40, BuildOperationFiringBuildWorkerExecutor (org.gradle.execution)
lambda$executeTasks$10:313, DefaultBuildLifecycleController (org.gradle.internal.build)
get:-1, DefaultBuildLifecycleController$$Lambda$2217/0x00007fe70d625300 (org.gradle.internal.build)
doTransition:266, StateTransitionController (org.gradle.internal.model)
lambda$tryTransition$8:177, StateTransitionController (org.gradle.internal.model)
create:-1, StateTransitionController$$Lambda$2218/0x00007fe70d625550 (org.gradle.internal.model)
withLock:44, DefaultSynchronizer (org.gradle.internal.work)
tryTransition:177, StateTransitionController (org.gradle.internal.model)
executeTasks:304, DefaultBuildLifecycleController (org.gradle.internal.build)
runWork:220, DefaultBuildWorkGraphController$DefaultBuildWorkGraph (org.gradle.internal.build)
create:-1, DefaultBuildController$$Lambda$2216/0x00007fe70d6284a0 (org.gradle.composite.internal)
withLocks:264, DefaultWorkerLeaseService (org.gradle.internal.work)
runAsWorkerThread:128, DefaultWorkerLeaseService (org.gradle.internal.work)
doRun:181, DefaultBuildController (org.gradle.composite.internal)
access$000:50, DefaultBuildController (org.gradle.composite.internal)
lambda$run$0:198, DefaultBuildController$BuildOpRunnable (org.gradle.composite.internal)
run:-1, DefaultBuildController$BuildOpRunnable$$Lambda$2215/0x00007fe70d628250 (org.gradle.composite.internal)
with:80, CurrentBuildOperationRef (org.gradle.internal.operations)
run:198, DefaultBuildController$BuildOpRunnable (org.gradle.composite.internal)
call:539, Executors$RunnableAdapter (java.util.concurrent)
run:264, FutureTask (java.util.concurrent)
onExecute:64, ExecutorPolicy$CatchAndRecordFailures (org.gradle.internal.concurrent)
run:47, AbstractManagedExecutor$1 (org.gradle.internal.concurrent)
runWorker:1136, ThreadPoolExecutor (java.util.concurrent)
run:635, ThreadPoolExecutor$Worker (java.util.concurrent)
run:840, Thread (java.lang)
```    
</details>

<details>
<summary>"Execution worker" @ 27,534 in group "main": WAIT</summary>

```
wait:-1, Object (java.lang)
wait:338, Object (java.lang)
withStateLock:113, DefaultResourceLockCoordinationService (org.gradle.internal.resources)
run:279, DefaultWorkerLeaseService$2 (org.gradle.internal.work)
measure:533, DefaultWorkerLeaseService$ProjectLockStatisticsImpl (org.gradle.internal.work)
acquireLocks:276, DefaultWorkerLeaseService (org.gradle.internal.work)
releaseWorkerLeaseAndWaitFor:400, DefaultWorkerLeaseService (org.gradle.internal.work)
acquireLocksWithoutWorkerLeaseWhileBlocked:388, DefaultWorkerLeaseService (org.gradle.internal.work)
withoutLocks:338, DefaultWorkerLeaseService (org.gradle.internal.work)
withoutLocks:319, DefaultWorkerLeaseService (org.gradle.internal.work)
blocking:225, DefaultWorkerLeaseService (org.gradle.internal.work)
waitForWorkToComplete:136, DefaultBuildOperationQueue (org.gradle.internal.operations)
waitForCompletion:107, DefaultBuildOperationQueue (org.gradle.internal.operations)
executeInParallel:129, DefaultBuildOperationExecutor (org.gradle.internal.operations)
runAll:88, DefaultBuildOperationExecutor (org.gradle.internal.operations)
visit:66, ParallelResolveArtifactSet$VisitingSet (org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact)
run:61, ResolvedArtifactSetResolver$1 (org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact)
execute:29, DefaultBuildOperationRunner$1 (org.gradle.internal.operations)
execute:26, DefaultBuildOperationRunner$1 (org.gradle.internal.operations)
execute:66, DefaultBuildOperationRunner$2 (org.gradle.internal.operations)
execute:59, DefaultBuildOperationRunner$2 (org.gradle.internal.operations)
execute:157, DefaultBuildOperationRunner (org.gradle.internal.operations)
execute:59, DefaultBuildOperationRunner (org.gradle.internal.operations)
run:47, DefaultBuildOperationRunner (org.gradle.internal.operations)
run:59, DefaultBuildOperationExecutor (org.gradle.internal.operations)
visitArtifacts:58, ResolvedArtifactSetResolver (org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact)
lambda$visitInUnmanagedWorkerThread$0:54, ResolvedArtifactSetResolver (org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact)
run:-1, ResolvedArtifactSetResolver$$Lambda$1146/0x00007fe70cd66f78 (org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact)
runAsUnmanagedWorkerThread:140, DefaultWorkerLeaseService (org.gradle.internal.work)
visitInUnmanagedWorkerThread:54, ResolvedArtifactSetResolver (org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact)
visitArtifacts:59, DefaultSelectedArtifactSet (org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact)
visitFiles:34, SelectedArtifactSet (org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact)
visitContents:72, ResolutionBackedFileCollection (org.gradle.api.internal.artifacts.configurations)
visitStructure:361, AbstractFileCollection (org.gradle.api.internal.file)
lambda$visitContents$0:113, CompositeFileCollection (org.gradle.api.internal.file)
accept:-1, CompositeFileCollection$$Lambda$1555/0x00007fe70cfc5298 (org.gradle.api.internal.file)
add:67, UnpackingVisitor (org.gradle.api.internal.file.collections)
visitContents:595, DefaultConfigurableFileCollection$UnresolvedItemsCollector (org.gradle.api.internal.file.collections)
visitChildren:416, DefaultConfigurableFileCollection (org.gradle.api.internal.file.collections)
visitContents:113, CompositeFileCollection (org.gradle.api.internal.file)
getFiles:124, AbstractFileCollection (org.gradle.api.internal.file)
unpackState:109, DefaultConfigurableFileCollection (org.gradle.api.internal.file.collections)
processManaged:127, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:98, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processArrayElements:183, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processArray:176, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:92, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processManaged:127, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:98, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
isolate:49, DefaultIsolatableFactory (org.gradle.internal.snapshot.impl)
isolateParameters:161, DefaultValueSourceProviderFactory (org.gradle.api.internal.provider)
access$400:44, DefaultValueSourceProviderFactory (org.gradle.api.internal.provider)
source:316, DefaultValueSourceProviderFactory$LazilyObtainedValue (org.gradle.api.internal.provider)
obtain:300, DefaultValueSourceProviderFactory$LazilyObtainedValue (org.gradle.api.internal.provider)
calculateOwnValue:256, DefaultValueSourceProviderFactory$ValueSourceProvider (org.gradle.api.internal.provider)
calculateValue:115, AbstractMinimalProvider (org.gradle.api.internal.provider)
calculateOwnValue:81, TransformBackedProvider (org.gradle.api.internal.provider)
getOrNull:105, AbstractMinimalProvider (org.gradle.api.internal.provider)
unpackState:189, AbstractMinimalProvider (org.gradle.api.internal.provider)
processManaged:127, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:98, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processManaged:127, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:98, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processArrayElements:183, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processArray:176, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:92, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processManaged:127, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
processValue:98, AbstractValueProcessor (org.gradle.internal.snapshot.impl)
isolate:49, DefaultIsolatableFactory (org.gradle.internal.snapshot.impl)
isolateParametersExclusively:677, DefaultTransform$IsolateTransformParameters (org.gradle.api.internal.artifacts.transform)
doIsolateParameters:668, DefaultTransform$IsolateTransformParameters (org.gradle.api.internal.artifacts.transform)
isolateParameters:662, DefaultTransform$IsolateTransformParameters (org.gradle.api.internal.artifacts.transform)
calculateValue:639, DefaultTransform$IsolateTransformParameters (org.gradle.api.internal.artifacts.transform)
calculateValue:558, DefaultTransform$IsolateTransformParameters (org.gradle.api.internal.artifacts.transform)
lambda$attachValue$0:229, CalculatedValueContainer$CalculationState (org.gradle.internal.model)
call:-1, CalculatedValueContainer$CalculationState$$Lambda$1066/0x00007fe70cd00000 (org.gradle.internal.model)
ofFailable:41, Try (org.gradle.internal)
attachValue:224, CalculatedValueContainer$CalculationState (org.gradle.internal.model)
finalizeIfNotAlready:197, CalculatedValueContainer (org.gradle.internal.model)
run:183, CalculatedValueContainer (org.gradle.internal.model)
execute:94, ActionNode (org.gradle.execution.plan)
execute:27, WorkNodeExecutor (org.gradle.execution.plan)
execute:331, DefaultTaskExecutionGraph$InvokeNodeExecutorsAction (org.gradle.execution.taskgraph)
execute:318, DefaultTaskExecutionGraph$InvokeNodeExecutorsAction (org.gradle.execution.taskgraph)
lambda$execute$0:314, DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction (org.gradle.execution.taskgraph)
run:-1, DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction$$Lambda$2227/0x00007fe70d62d4b0 (org.gradle.execution.taskgraph)
with:80, CurrentBuildOperationRef (org.gradle.internal.operations)
execute:314, DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction (org.gradle.execution.taskgraph)
execute:303, DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction (org.gradle.execution.taskgraph)
execute:463, DefaultPlanExecutor$ExecutorWorker (org.gradle.execution.plan)
run:380, DefaultPlanExecutor$ExecutorWorker (org.gradle.execution.plan)
onExecute:64, ExecutorPolicy$CatchAndRecordFailures (org.gradle.internal.concurrent)
run:47, AbstractManagedExecutor$1 (org.gradle.internal.concurrent)
runWorker:1136, ThreadPoolExecutor (java.util.concurrent)
run:635, ThreadPoolExecutor$Worker (java.util.concurrent)
run:840, Thread (java.lang)
```
</details>

The two threads are trying to resolve the parameters of the transforms. With more debugging, I found that the transform parameter of interest is in the Android Gradle plugin:
```
// com.android.build.gradle.internal.dependency.BaseDexingTransform
abstract class BaseDexingTransform<T : BaseDexingTransform.Parameters> : TransformAction<T> {
    interface Parameters : GenericTransformParameters {
        @get:Input
        val libConfiguration: Property<String>
    }
```
where `libConfiguration` is a `Property<String>` computed from an `ArtifactCollection` via a `ValueSource`:
```
// com.android.build.gradle.internal.utils.DesugarLibUtils#getDesugarLibConfig, edited for readability

abstract class DesugarConfigJson : ValueSource<String, DesugarConfigJson.Parameters> {
    interface Parameters : ValueSourceParameters {
        val desugarJson: ConfigurableFileCollection
    }
    override fun obtain(): String? { ... }
}

libConfiguration.set(
    providerFactory.of(DesugarConfigJson::class.java) { 
        it.parameters.desugarJson.setFrom(artifactCollection.artifactFiles)
    }
)
```

So it seems that Gradle is not resolving `ValueSource` in a thread-safe manner. (I tried computing the `Property<String>` from the `ArtifactCollection` directly without going through a `ValueSource`, then the deadlock doesn't happen.)

### PR DESCRIPTION
**Pull request by mlopatkin**
When isolating the ValueSource parameters, obtaining a project(s) lock may be required, for example to isolate a Configuration. However, it is possible that at the same moment another thread holding the lock is
trying to obtain the same ValueSource. Prior to this commit, when a synchronized block was used to guard the ValueSource isolation and computation, it caused a deadlock. The CalculatedValueContainer, which
replaced the monitor, can now yield locks held by a thread if obtaining the ValueSource block. This way, the first thread can proceed with isolation and compute the value source safely. Then the second thread obtains the computed value after it is available.

Perhaps a more granular locking can be employed: as the value source computation is isolated, we can use CalculatedValueContainer to only get the isolated parameters, and use a monitor to run the computation itself. However, the CalculatedValueContainer itself only acquires a ReentrantLock, it is the parameter isolation that requests the project
lock, so the extra granularity is unlikely to yield benefits.

To make the infrastructure available to DefaultValueSourceFactory, some interface classes were moved to `:model-core`. 

`Try` and `CalculatedValueContainer` are now documented to be able to hold `null` values.

Fixes #28566.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this without PTS

**Comment by mlopatkin** [comment]
@bot-gradle test APT

**Comment by mlopatkin** [comment]
@bot-gradle test this

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java [hunk 1]
```diff
@@ -278,33 +286,31 @@ private LazilyObtainedValue(
             this.sourceType = sourceType;
             this.parametersType = parametersType;
             this.parameters = parameters;
+            this.value = calculatedValueFactory.create(Describables.of("ValueSource of type", sourceType), () -> {
```
Comment (mlopatkin) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java:289]: 💭 this is the primary change

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java [hunk 2]
```diff
@@ -278,33 +286,31 @@ private LazilyObtainedValue(
...
-            synchronized (this) {
-                Try<T> cached = value;
-                if (cached != null) {
-                    return cached;
-                }
-                computationBroadcaster.getSource().beforeValueObtained();
-                try {
-                    // TODO - add more information to exceptions
-                    // Fail fast when source can't be instantiated.
-                    source = source();
```
Comment (mlopatkin) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java:300]: 💭  There's a minor behavioral difference. Now the failure to create a ValueSource instance or isolate it parameters is cached too.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java [hunk 3]
```diff
@@ -278,33 +286,31 @@ private LazilyObtainedValue(
...
-                    value = obtained = Try.ofFailable(source::obtain);
-                } finally {
-                    computationBroadcaster.getSource().afterValueObtained();
-                }
+        public Try<@org.jetbrains.annotations.Nullable T> obtain() {
```
Comment (mlopatkin) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java:306]: 💭 Alternatively, we can have a `CalculatedValue<Optional<T>>`, but this introduces an extra wrapper object.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/internal/model/CalculatedValue.java [hunk 4]
```diff
@@ -33,22 +37,15 @@ public interface CalculatedValue<T> {
      */
     T get() throws IllegalStateException;
 
-    /**
-     * Returns the value, or null if it has not been calculated.
-     * Does not calculate the value on demand and does not block if the value is currently being calculated.
-     *
-     * <p>Rethrows any exception that happened while calculating the value</p>
-     */
-    T getOrNull();
```
Comment (mlopatkin) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/internal/model/CalculatedValue.java:42]: 💭 `getOrNull` no longer works reliably if `null` is a valid result of `get`.

**Review by mlopatkin — COMMENTED** [review]
There's a fair bit of yak shaving to move stuff around. The rest of `org.gradle.internal.model` package could probably also live in `model-core`, but these types depend on `:core` types in non-trivial way.

**Comment by mlopatkin** [comment]
@bot-gradle test this

File: platforms/software/dependency-management/src/test/groovy/org/gradle/api/internal/catalog/LibrariesSourceGeneratorTest.groovy [hunk 5]
```diff
@@ -70,12 +70,13 @@ class LibrariesSourceGeneratorTest extends AbstractVersionCatalogTest implements
     final CapabilityNotationParser capabilityNotationParser = new CapabilityNotationParserFactory(false).create()
     final ProviderFactory providerFactory = new DefaultProviderFactory(
         new DefaultValueSourceProviderFactory(
-            new DefaultListenerManager(Scope.Build),
-            TestUtil.instantiatorFactory(),
-            new TestIsolatableFactory(),
-            Stub(GradleProperties),
-            Stub(ExecOperations),
-            TestUtil.services()
+                new DefaultListenerManager(Scope.Build),
```
Comment (bamboo) [inline platforms/software/dependency-management/src/test/groovy/org/gradle/api/internal/catalog/LibrariesSourceGeneratorTest.groovy:73]: 💅 Indentation looks off

**Review by bamboo — APPROVED** [review]
Exemplary!

File: subprojects/core/src/main/java/org/gradle/internal/model/CalculatedValueContainerFactory.java [hunk 6]
```diff
@@ -30,7 +31,7 @@
  * Factory for {@link CalculatedValueContainer}.
  */
 @ServiceScope(Scope.BuildSession.class)
-public class CalculatedValueContainerFactory {
+public class CalculatedValueContainerFactory implements CalculatedValueFactory {
```
[the remark this answers is not in the document]
Comment (mlopatkin) [reply subprojects/core/src/main/java/org/gradle/internal/model/CalculatedValueContainerFactory.java:34]: > 🤔 No strong feeling but I think I'd rename `CalculatedValueContainer => DefaultCalculatedValue` and `CalculatedValueContainerFactory => DefaultCalculatedValueFactory` to make the connections clearer. Clients that require the concrete class interface would be just as expressive IMO.

I'm keeping the names for a moment to keep the PR smaller, I recall this rename doubles its size, and there's another PR in flight that touches these classes.

File: subprojects/core/src/main/java/org/gradle/internal/model/CalculatedValueContainerFactory.java [hunk 7]
```diff
@@ -46,27 +47,21 @@ public <T, S extends ValueCalculator<? extends T>> CalculatedValueContainer<T, S
         return new CalculatedValueContainer<>(displayName, supplier, projectLeaseRegistry, globalContext);
     }
 
-    /**
-     * A convenience to create a calculated value that has no dependencies and that does not access any mutable model state.
-     */
-    public <T> CalculatedValueContainer<T, ?> create(DisplayName displayName, Supplier<? extends T> supplier) {
+    @Override
+    public <T> CalculatedValueContainer<T, ValueCalculator<T>> create(DisplayName displayName, Supplier<? extends T> supplier) {
```
[the remark this answers is not in the document]
Comment (mlopatkin) [reply subprojects/core/src/main/java/org/gradle/internal/model/CalculatedValueContainerFactory.java:51]: > I'm not suggesting that but, an alternative would be to introduce a covariant generic parameter to stand in for `ProjectInternal`.

It might be possible to introduce another abstraction to wrap the Project, but I'd leave this for maintenance day.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java [hunk 8]
```diff
@@ -277,33 +286,31 @@ private LazilyObtainedValue(
...
-                    // TODO - add more information to exceptions
-                    // Fail fast when source can't be instantiated.
-                    source = source();
-                    value = obtained = Try.ofFailable(source::obtain);
-                } finally {
-                    computationBroadcaster.getSource().afterValueObtained();
-                }
+            value.finalizeIfNotAlready();
+            Try<@org.jetbrains.annotations.Nullable T> obtained = value.getValue();
+            ValueSource<T, P> obtainedFrom = sourceRef.getAndSet(null);
```
[the remark this answers is not in the document]
Comment (mlopatkin) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java]: > 🤔 Should the `sourceRef` cleaning be in a finally block just in case?

It doesn't hurt that much, and there's slight possibility of some `RuntimeException(InterruptedException)` popping up from `finalizeIfNotAlready`, so let's have that.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java [hunk 9]
```diff
@@ -231,9 +237,8 @@ public boolean isImmutable() {
             return true;
         }
 
-        @Nullable
-        public Try<T> getObtainedValueOrNull() {
-            return value.value;
```
Comment (mlopatkin) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java:236]: 💭 I had to kill this method, I just couldn't make myself to write `return value.value.getValue()`.

File: platforms/core-configuration/model-core/src/main/java/org/gradle/internal/model/CalculatedValue.java [hunk 10]
```diff
@@ -22,9 +22,13 @@
 
 /**
  * Represents a calculated immutable value that is calculated once and then consumed by multiple threads.
+ * <p>
+ * This class can hold a null value.
  */
 @ThreadSafe
 public interface CalculatedValue<T> {
+    // TODO(https://github.com/gradle/gradle/issues/24767): with JSpecify, the nullable nature of the type argument <T> should be expressed as <T extends @Nullable Object>.
```
Comment (abstratt) [inline platforms/core-configuration/model-core/src/main/java/org/gradle/internal/model/CalculatedValue.java:30]: ❓  Is this different from:

```
public interface Transformer<OUT extends @org.jetbrains.annotations.Nullable Object, IN> {
```

Is it that we'd rather not use JB's `Nullable` annotation?

Comment (abstratt) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/internal/model/CalculatedValue.java:30]: I guess you explain it here.

https://github.com/gradle/gradle/pull/28822/files#diff-575049641757d005928c369350bc3f33168e24dd0a00e208780998ce740f11dcR34

Comment (mlopatkin) [reply platforms/core-configuration/model-core/src/main/java/org/gradle/internal/model/CalculatedValue.java:30]: >Is it that we'd rather not use JB's Nullable annotation?

There just too many false positive warnings in IDEA for this type and `Try` for it to be useful :(. Annotating client sides is enough for now - it shows the necessary warnings upon access, but not when passing `Try<@Nullable Foo>` argument to `Try<Foo>` parameter, unfortunately.
