### PR TITLE
Task with broken output symlink shouldn't fail

### LINKED ISSUE #1365: Gracefully handle symbolic links pointing to non-existing files in output directories
Original issue: https://issues.gradle.org/browse/GRADLE-1843

**Highly voted issue: 21**

### Expected Behavior

Ignore dangling symlinks when calculating the outputs for UP-TO-DATE checking. Potentially introduce a property that allows for configuring if a symlink should be followed.

### Current Behavior

Gradle fails with an exception when a dangling symlink is found.

### Context

Gradle should handle dangling symlinks more gracefully.

### Steps to Reproduce (for bugs)

Given the following tasks:

```
task testCopy(type: Copy) {
    from "test"
    into "$buildDir/test"
}

task testSync(type: Sync) {
    from "test"
    into "$buildDir/test"
}
```

And the following file structure:

```
mkdir -p build/test
[:~/tmp/test] % ln -s ../foo build/test
[:~/tmp/test] % touch build/test/valid
[:~/tmp/test] % ln -s valid build/test/valid_link
[:~/tmp/test] % ls -l build/test test
build/test:
total 0
-rw-r--r-- 1 alpar users 0 Oct 12 11:44 file.txt
lrwxrwxrwx 1 alpar users 6 Oct 12 11:46 foo -> ../foo
-rw-r--r-- 1 alpar users 0 Oct 12 11:46 valid
lrwxrwxrwx 1 alpar users 5 Oct 12 11:46 valid_link -> valid

test:
total 0
-rw-r--r-- 1 alpar users 0 Oct 12 09:18 file.txt
```

The following exception is thrown:

```
[:~/tmp/test] 1 % ./gradlew -s testCopy
* Exception is:
org.gradle.api.GradleException: Could not list contents of '/tmp/alpar/test/build/test/foo'. Couldn't follow symbolic link.
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:79)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:54)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker.walkDir(Jdk7DirectoryWalker.java:54)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.walkDir(DirectoryFileTree.java:146)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visitFrom(DirectoryFileTree.java:130)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visit(DirectoryFileTree.java:115)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visitTreeOrBackingFile(DirectoryFileTree.java:111)
	at org.gradle.api.internal.file.collections.FileTreeAdapter.visitTreeOrBackingFile(FileTreeAdapter.java:114)
	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.visitFiles(DefaultFileCollectionSnapshotter.java:42)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:62)
	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:31)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:100)
	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:31)
	at org.gradle.api.internal.changedetection.state.OutputFilesCollectionSnapshotter.snapshot(OutputFilesCollectionSnapshotter.java:60)
	at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:85)
	at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.<init>(AbstractNamedFileSnapshotTaskStateChanges.java:53)
	at org.gradle.api.internal.changedetection.rules.OutputFilesTaskStateChanges.<init>(OutputFilesTaskStateChanges.java:31)
	at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:54)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:162)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:82)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
	at org.gradle.execution.taskgraph.ParallelTaskPlanExecutor.process(ParallelTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:186)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:183)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:112)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:92)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:79)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:51)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:293)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
```

### PR DESCRIPTION
**Pull request by paplorinc**
Fixes #1365
Related to #9708

### CODE REVIEW

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 1]
```diff
@@ -65,6 +66,59 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
         "project.objects.fileCollection()"   | "project.objects.fileCollection().from(file, symlink, symlinked)"
     }
 
+    // TODO should probably be moved to incremental suite
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: should I move it elsewhere?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 2]
```diff
@@ -65,6 +66,59 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+        delete(target)
+        run 'resolveSymlink'
+        then:
+        noneSkipped()
+        output.text.contains "${link.name} has been removed"
+
+        where:
+        fileType    | inputAnnotation   | create              | delete
+        'file'      | '@InputFile'      | { it.createFile() } | { it.delete() }
+        // TODO 'directory' | '@InputDirectory' | { it.mkdirs() }     | { it.deleteDir() }
```
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: is this supposed to work with `InputChanges`?

File: subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java [hunk 3]
```diff
@@ -35,7 +38,11 @@ public void doValidate(String propertyName, Object value, TaskValidationContext
         public void doValidate(String propertyName, Object value, TaskValidationContext context) {
             File file = toFile(context, value);
             if (!file.exists()) {
-                context.visitError(String.format("File '%s' specified for property '%s' does not exist.", file, propertyName));
+                if (Files.isSymbolicLink(file.toPath())) {
+                    LOGGER.warn("File '{}' specified for property '{}' is a broken symbolic link.", file, propertyName);
```
Comment (paplorinc) [inline subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java]: should the validation ignore the broken links completely, or is it okay to warn?

File: subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFile.java [hunk 4]
```diff
@@ -490,13 +490,15 @@ public String getSha256Hash() {
...
-        createLink(target.getAbsolutePath());
+    public File createLink(String target) {
+        return createLink(new File(target));
     }
 
-    public void createLink(String target) {
-        NativeServices.getInstance().get(FileSystem.class).createSymbolicLink(this, new File(target));
+    public File createLink(File target) {
+        NativeServices.getInstance().get(FileSystem.class)
+            .createSymbolicLink(this, target);
```
Comment (paplorinc) [inline subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFile.java]: what about hard links? (don't think it applies to broken ones, though)

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 1 above)
Comment (paplorinc) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: should I move it elsewhere?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 2 above)
Comment (lptr) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: It should. Can you elaborate on what doesn't work?

Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: The `file` produces an initial change for `allFileChanges` of type `NonIncrementalInputChanges$RebuildFileChange`, the `folder` produces an empty iterable.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 5]
```diff
@@ -65,6 +66,74 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+
+        buildFile << """
+            import java.nio.file.*
+            class ProducesLink extends DefaultTask {
+                @OutputDirectory File outputDirectory // TODO outputfile?
+    
+                @TaskAction execute() {
+                    def link = Paths.get('${link}')
+                    Files.deleteIfExists(link);
+                    Files.createSymbolicLink(link, Paths.get('${target}'));
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Don't we have a problem with masking absolute paths in `${target}`. How about we use

```suggestion
                    Files.createSymbolicLink(link, Paths.get(project.file('${target.name}')));
```

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 6]
```diff
@@ -65,6 +66,74 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+        def target = file("target")
+        def link = root.file("link")
+
+        buildFile << """
+            import java.nio.file.*
+            class ProducesLink extends DefaultTask {
+                @OutputDirectory File outputDirectory // TODO outputfile?
+    
+                @TaskAction execute() {
+                    def link = Paths.get('${link}')
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]:
```suggestion
                    def link = outputDirectory.toPath().resolve('${link.name}'))
```

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java [hunk 7]
```diff
@@ -190,10 +189,6 @@ private String getFilename(Path dir) {
         public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) {
             String internedName = intern(file.getFileName().toString());
             if (shouldVisit(file, internedName, false, attrs, builder.getRelativePath())) {
-                if (attrs.isSymbolicLink()) {
```
Comment (wolfs) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java]: Should we return the missing file snapshot directly here, without waiting for the hashing to fail? I think this would be better in the long run, given that we want to handle unavailable files and broken symlinks slightly different.

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy [hunk 8]
```diff
@@ -155,6 +155,26 @@ class DirectorySnapshotterTest extends Specification {
         ] as Set
     }
 
+    @Requires(TestPrecondition.FILE_PERMISSIONS)
+    def "broken symlinks are snapshotted as missing"() {
+        def rootDir = tmpDir.createDir("root")
+        rootDir.file('brokenSymlink').createLink("linkTarget")
+        assert rootDir.listFiles()*.exists() == [false]
+        def predicate = directoryWalkerPredicate(new PatternSet())
```
Comment (wolfs) [inline subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy]: Why do you use a non-null predicate here?

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 5 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Could you please tell me why you prefer the other?
This is for symlinks only, so we don't have to escape it for Windows.
By using absolute paths, we don't have to define the folder structure twice, but the resulting String will indeed be slightly uglier, is that the concern?
```
def link = Paths.get('/Users/paplorinc/gradle/subprojects/core/build/tmp/test files/FileCollectionSymlinkIntegrationTest/detect_changes_to_b...k_outputs/pdgg/root/link'
```

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 6 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: I'm not yet sure about why absolute paths aren't preferred, please elaborate

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 5 above)
Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Ah, you are right, I didn't realize this doesn't need to work on Windows. My concern is then that if we ever add support for using symlinks on Windows, then this test will break...

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java (hunk 7 above)
Comment (paplorinc) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java]: It doesn't actually get to hashing, the [regular file check](https://github.com/gradle/gradle/blob/a4d285eb3b8006b31b4699aacbde281d99776d60/subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java#L199) should filter it out.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 5 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: It will and they will add the escapes for the paths :)
Is that okay with you, it seems simpler to me this way?

Comment (wolfs) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: It is fine, we can leave it as is for now.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 9]
```diff
@@ -65,6 +66,74 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+    @Issue("https://github.com/gradle/gradle/issues/1365")
+    def "detect changes to broken symlink outputs"() {
+        def root = file("root").createDir()
+        def target = file("target")
+        def link = root.file("link")
+
+        buildFile << """
+            import java.nio.file.*
+            class ProducesLink extends DefaultTask {
+                @OutputDirectory File outputDirectory // TODO outputfile?
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: I think if you add the test for `outputFile` then this PR is good to merge. We should do the improvements (checklist you added to the PR) in a follow up.

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy (hunk 8 above)
Comment (paplorinc) [reply subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy]: Leftover, but it wasn't working with `null` for some reason ... anyway, it seems to be now, fixed :)

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy (hunk 9 above)
Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Great, will do :)

Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Done, please validate if I'm actually reproducing the right thing via the new tests

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy (hunk 8 above)
Comment (paplorinc) [reply subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy]: Done

File: subprojects/docs/src/docs/release/notes.md [hunk 10]
```diff
@@ -27,6 +27,7 @@ Include only their name, impactful features should be called out separately belo
 [Stephan Windmüller](https://github.com/stovocor),
 [Zemian Deng](https://github.com/zemian),
 [Robin Verduijn](https://github.com/robinverduijn),
+[idlsoft](https://github.com/idlsoft),
```
Comment (paplorinc) [inline subprojects/docs/src/docs/release/notes.md]: wrote him an email, in case he wants a different name here

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 11]
```diff
@@ -65,6 +66,100 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
+            task copy(type: Copy) {
+                from '${input.name}'
+                into '${outputDirectory.name}'
+            }
+        """
+
+        when:
+        succeeds 'copy'
+        then:
+        outputDirectory.list().contains input.name
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: I guess we would need to remove the broken symlink from the target directory and check that the copy task stays up-to-date, right?

Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Good idea, done.

File: subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy [hunk 12]
```diff
@@ -155,9 +155,18 @@ class FileCollectionSymlinkIntegrationTest extends AbstractIntegrationSpec {
...
 
         when:
-        succeeds 'copy'
+        run 'copy'
         then:
+        executedAndNotSkipped ':copy'
         outputDirectory.list().contains input.name
+
+        when:
+        run 'copy'
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: We should remove the broken symlink before we run the task again.
```
brokenLink.delete()
run 'copy'
```

Comment (paplorinc) [reply subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy]: Done
