### PR TITLE
Reproduce and fix #36428

### LINKED ISSUE #36428: Breaking change in 9.3.0 regarding cross-project dependency manipulation
### Current Behavior

- have a build with two projects
- put to the root project
  ```kotlin
  subprojects {
      configurations.configureEach {
          allDependencies.configureEach {
          }
      }
  }
  ```
- run `./gradlew dependencies`

Ignoring that this is of course bad-practice cross-project configuration,
this works up to including 9.2.1 but fails with 9.3.0:
```plain
An exception occurred applying plugin request [id: 'org.gradle.java-library']
> Failed to apply plugin class 'org.gradle.api.plugins.JavaPlugin'.
   > Could not create domain object 'java' (JvmSoftwareComponentInternal) in SoftwareComponent container
      > Could not create domain object 'test' (JvmTestSuite) in TestSuite container
         > Could not create an instance of type org.gradle.api.plugins.jvm.internal.DefaultJvmTestSuite.
            > The value for property 'dependencies.compileOnly' property 'dependencies' is final and cannot be changed any further.
```

If that is an intentional new limitation, it should probably go through the usual deprecation cycle.

### Expected Behavior

Not breaking in a minor update

### Gradle version

9.3.0

### Gradle version that used to work

9.2.1

### PR DESCRIPTION
**Pull request by big-guy**
### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/jvm/plugins-jvm-test-suite/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java [hunk 1]
```diff
@@ -101,11 +96,23 @@ public DefaultJvmTestSuite(String name, SourceSetContainer sourceSets, Configura
             toolchain.getParameters().getJupiterVersion().convention(JUnitJupiterTestToolchain.DEFAULT_VERSION);
         }
 
+        // Add test framework dependencies to the dependency collectors BEFORE wiring them to configurations.
```
Comment (hfhbd) [inline platforms/jvm/plugins-jvm-test-suite/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java:99]: Could this explanation also be added to DependencyCollector docs? I had no idea DependencyCollector uses `finalizeValueOnRead` (it is in the sources though)

Comment (big-guy) [reply platforms/jvm/plugins-jvm-test-suite/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java:99]: done, thanks for the suggestion
