### PR TITLE
Fix adding bundles via DependencyHandler#addProvider

### LINKED ISSUE #22552: 7.6 RC1: UnsupportedNotationException for version catalog dependency bundle
### Expected Behavior
* Project that builds successfully when referencing version catalog dependency bundles with Gradle 7.5.1 should continue to do so with Gradle 7.6.
 
### Current Behavior
* Upon upgrading to Gradle 7.6-rc-1, version catalog dependency bundle references result in an `UnsupportedNotationException`.

### Context
* I'm unable to upgrade my project to Gradle 7.6-rc-1.

### Steps to Reproduce 
* Reproducer here: https://github.com/sdkotlin/sd-kotlin-talks/tree/7.6-upgrade.

### Your Environment

Gradle 7.6-rc-1
Build time:   2022-10-28 07:52:11 UTC
Revision:     62973455a8df25d003949f3f573593cd10d083a3

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.17 (Eclipse Adoptium 11.0.17+8)
OS:           Windows 10 10.0 amd64

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #22552

### CODE REVIEW

**Comment by octylFractal** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by octylFractal** [comment]
@bot-gradle test and merge

File: subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy [hunk 1]
```diff
@@ -185,6 +185,44 @@ myBundle = ["lib", "lib2"]
...
+        def lib2 = mavenHttpRepo.module("org.gradle.test", "lib2", "1.0").publish()
+        buildFile << """
+            apply plugin: 'java-library'
+
+            dependencies {
+                addProvider("implementation", libs.bundles.myBundle)
+            }
+        """
+
+        when:
```
Comment (tresat) [inline subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy:208]: Very minor, this seems like it should be removed and the first `then` below be made `when`.

**Review by tresat — APPROVED** [review]
