### PR TITLE
Replace Ant compression library for toolchain archives

### LINKED ISSUE #19382: Error extracting downloaded toolchain for `JvmImplementation.J9`
When choosing the "Open J9" Java Toolchain implementation [as described in the docs](https://docs.gradle.org/current/userguide/toolchains.html#selecting_toolchains_by_their_virtual_machine_implementation), there is an error extracting the the downloaded Toolchain distribution, resulting in a build failure.

### Expected Behavior
The J9 toolchain distribution should be successfully downloaded, provisioned and used.

### Current Behavior
The build fails with this error occurring when extracting the toolchain:
```
* What went wrong:
Execution failed for task ':compileJava'.
> Error while evaluating property 'javaCompiler' of task ':compileJava'
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > Unable to download toolchain matching these requirements: {languageVersion=11, vendor=ADOPTOPENJDK, implementation=J9}
         > Could not copy tar entry /Users/daz/dev/playground/java-tool/HOME/jdks/adoptopenjdk-11-x64-mac.tar.gz!1413453464414134534642/./ to '/Users/daz/dev/playground/java-tool/HOME/.tmp/expandedArchives/adoptopenjdk-11-x64-mac.tar.gz_09fc3ceb3762da51449cb5292ffc4737/1413453464414134534642/.'.
            > Failed to create parent directory '/Users/daz/dev/playground/java-tool/HOME/.tmp/expandedArchives/adoptopenjdk-11-x64-mac.tar.gz_09fc3ceb3762da51449cb5292ffc4737/1413453464414134534642' when creating directory '/Users/daz/dev/playground/java-tool/HOME/.tmp/expandedArchives/adoptopenjdk-11-x64-mac.tar.gz_09fc3ceb3762da51449cb5292ffc4737/1413453464414134534642/.'
```

### Steps to Reproduce 
1. Checkout the `main` branch of https://github.com/bigdaz/gradle-toolchain-issues
2. `./gradlew -g HOME build`

Build scan URL: https://scans.gradle.com/s/ri37b7rtrdmf6/failure#1

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #19382

### CODE REVIEW

**Comment by jbartok** [comment]
So far I've replaced only TAR decompression and have confirmed that it works fine with the problematic Semeru archives. I'm contemplating replacing ZIP too.

One more thing I've discovered is that symbolic link handling inside the archives is not and has not been working. The test for it is wrong.

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
Test failures are related to CI setup, they will be fixed on Monday.

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
Note to myself: transition other archive types too to commons compress library.

**Comment by jbartok** [comment]
Note to myself: test probing on these new, nested archive folders, because I think it doesn't work properly on macOS and our tests aren't catching it.

**Comment by jbartok** [comment]
@bot-gradle

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test qfl

File: subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/archive/TarTestFixture.groovy [hunk 1]
```diff
@@ -26,21 +26,39 @@ import java.util.zip.GZIPInputStream
...
+        long bytesRemaining = entry.getSize();
+        while (bytesRemaining > 0) {
+            int bytesRead = inputStream.read(buf, 0, buf.length);
+            if (bytesRead == -1) {
+                break;
+            }
+            outputStream.write(buf, 0, bytesRead);
+            bytesRemaining -= bytesRead;
+        }
+        new String(outputStream.toByteArray(), contentCharset ?: Charset.defaultCharset().name())
```
Comment (bamboo) [inline subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/archive/TarTestFixture.groovy:62]: ❓ Can we leverage `inputStream.readAllBytes()` or perhaps `IOUtils.readFully(inputStream, entry.size)` here?

**Comment by jbartok** [comment]
@bot-gradle test qfl

**Comment by jbartok** [comment]
@bot-gradle test rfr

**Comment by jbartok** [comment]
@bot-gradle test qfl

**Comment by jbartok** [comment]
@bot-gradle test rfr

**Comment by jbartok** [comment]
@bot-gradle test rfr

File: subprojects/build-cache/src/jmh/java/org/gradle/caching/internal/tasks/AbstractTaskOutputPackagingBenchmark.java [hunk 2]
```diff
@@ -44,17 +44,17 @@ public abstract class AbstractTaskOutputPackagingBenchmark {
...
+        .put("tar.snappy.large", new SnappyPacker(new CommonsTarPacker(64)))
+        .put("tar", new CommonsTarPacker(4))
         .put("tar.commons", new CommonsTarPacker(4))
         .put("tar.jtar", new JTarPacker(4))
-        .put("tar.small", new AntTarPacker(2))
-        .put("tar.large", new AntTarPacker(64))
-        .put("tar.gz", new GzipPacker(new AntTarPacker(4)))
+        .put("tar.small", new CommonsTarPacker(2))
+        .put("tar.large", new CommonsTarPacker(64))
+        .put("tar.gz", new GzipPacker(new CommonsTarPacker(4)))
```
Comment (eskatos) [inline subprojects/build-cache/src/jmh/java/org/gradle/caching/internal/tasks/AbstractTaskOutputPackagingBenchmark.java:57]: @lptr this replaces the Ant TAR packer with the Apache Commons Compress one. Are you ok with this change? Note that this PR also simply deletes `AntTarPacker`.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java [hunk 3]
```diff
@@ -105,6 +113,18 @@ private void visitImpl(FileVisitor visitor, InputStream inputStream) throws IOEx
         }
     }
 
+    private void checkFormat(InputStream inputStream) throws IOException {
+        String format;
+        try {
+            format = ArchiveStreamFactory.detect(inputStream);
+        } catch (ArchiveException e) {
+            throw new IOException("Failed detecting archive format!", e);
```
Comment (eskatos) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java:121]: 💄 
```suggestion
            throw new IOException("Failed to detect archive format", e);
```

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java [hunk 4]
```diff
@@ -105,6 +113,18 @@ private void visitImpl(FileVisitor visitor, InputStream inputStream) throws IOEx
...
+        }
+        if (!TAR.equals(format)) {
+            throw new IOException("Expected tar archive format but found " + format);
```
Comment (eskatos) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java:124]: 💄 
```suggestion
            throw new IOException("Expected TAR archive format but found " + format);
```

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java [hunk 5]
```diff
@@ -105,6 +113,18 @@ private void visitImpl(FileVisitor visitor, InputStream inputStream) throws IOEx
         }
     }
 
+    private void checkFormat(InputStream inputStream) throws IOException {
```
Comment (eskatos) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java:116]: Please add a javadoc to this method to explain why it is required. One reason I remember is that unpacking of invalid TAR files silently stops with Apache Commons Compress.

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java [hunk 6]
```diff
@@ -188,7 +208,7 @@ public InputStream open() {
             if (read && file != null) {
                 return GFileUtils.openInputStream(file);
             }
-            if (read || tar.getCurrent() != entry) {
+            if (read) {
```
Comment (eskatos) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java:211]: ❓ why remove that check?

```suggestion
            if (read || tar.getCurrentEntry() != entry) {
```

**Review by eskatos — CHANGES_REQUESTED** [review]
This is looking good!

Produced archives are different as shown by all the changes of hashes in tests. It would be good to know exactly what changed in those TAR/ZIP/JAR files. A comparison using https://diffoscope.org/ should reveal the differences.

I also left a few comments and suggestions.

**Comment by jbartok** [comment]
@bot-gradle test QFL

File: subprojects/build-cache/src/jmh/java/org/gradle/caching/internal/tasks/AbstractTaskOutputPackagingBenchmark.java (hunk 2 above)
Comment (lptr) [reply subprojects/build-cache/src/jmh/java/org/gradle/caching/internal/tasks/AbstractTaskOutputPackagingBenchmark.java:57]: Sure. But I think we should just remove these benchmarks. It's not like we are using them at all.

Comment (eskatos) [reply subprojects/build-cache/src/jmh/java/org/gradle/caching/internal/tasks/AbstractTaskOutputPackagingBenchmark.java:57]: Thanks for the feedback. We'll leave removing the benchmarks to you.

**Comment by jbartok** [comment]
@bot-gradle test QFL

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java [hunk 7]
```diff
@@ -206,17 +239,101 @@ public int getMode() {
...
         }
+    }
 
-        public TarEntry getCurrent() {
-            return currEntry;
+    /**
+     * Copy of <code>ArchiveStreamFactory.detect(InputStream)</code>, extended to not
+     * throw an exception for empty TAR files (ie. ones with no entries in them).
+     */
+    private static String detectFormat(InputStream inputStream) throws ArchiveException {
```
Comment (eskatos) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java:256]: If we need this code here then we should simplify it to only check for TAR which is the only interesting case here.
Removing the other checks will make it faster.

Comment (jbartok) [reply subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java:256]: Yes, I've thought about it, but had arguments against it too. For example let's say you remove the first part, which can detect other formats quickly. Then you make it potentially slower when the input is of those other formats. But, on the other hand, dealing with a non-TAR format should be a rare event, not the typical one... Yeah, should make sense to simplify. Will do it.

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by eskatos** [comment]
@bot-gradle test QFL

**Review by eskatos — APPROVED** [review]
:+1:

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle help

**Comment by jbartok** [comment]
@bot-gradle clean

**Comment by jbartok** [comment]
@bot-gradle test APT

**Comment by eskatos** [comment]
Performance test results can be seen here:
* Linux
  https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_PerformanceTestTestLinux_Trigger/57510367?buildTab=report_project104062_Performance
* Windows
  https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_PerformanceTest6_Trigger/57510373?buildTab=report_project104062_Performance
* Mac
  https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_PerformanceTest7_Trigger/57510379?buildTab=report_project104062_Performance
* Slow
  https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_PerformanceTestSlowLinux_Trigger/57510410?buildTab=report_project104067_Performance

----

There is one ~4% performance regression on visiting TAR trees

image

And one ~12% performance improvement on visiting ZIP trees

image

Both are visible on very synthetic test scenarios. The impact on real world scenarios is unclear but the results mostly show small improvements here and there. The somewhat faster handling of ZIP archives might help in more realistic scenarios.

We should accept the regression!

**Comment by jbartok** [comment]
@bot-gradle test APT

**Comment by jbartok** [comment]
@bot-gradle cancel

**Comment by jbartok** [comment]
@bot-gradle clean

**Comment by jbartok** [comment]
@bot-gradle test APT

**Comment by jbartok** [comment]
@bot-gradle test APT

File: subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy [hunk 8]
```diff
@@ -40,8 +40,8 @@ class ArchiveTreePerformanceTest extends AbstractCrossVersionPerformanceTest {
         result.assertCurrentVersionHasNotRegressed()
     }
 
-    @RunFor(
-        @Scenario(type = PER_DAY, operatingSystems = [LINUX], testProjects = ["archivePerformanceProject"])
+    /*@RunFor(
+            @Scenario(type = PER_DAY, operatingSystems = [LINUX], testProjects = ["archivePerformanceProject"])
```
Comment (eskatos) [inline subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy:44]: :x: please do not comment the whole test but use `@RunFor([])` instead

**Review by eskatos — CHANGES_REQUESTED** [review]

File: subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy (hunk 8 above)
Comment (jbartok) [reply subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy:44]: I fail to see the difference since I'm going to them back anyways, but ok, will do so, since looks like I need to disable more tests anyways.

**Comment by jbartok** [comment]
@bot-gradle test APT

**Comment by jbartok** [comment]
@bot-gradle clean

**Comment by jbartok** [comment]
@bot-gradle test APT

**Comment by jbartok** [comment]
@bot-gradle test APT

**Review by eskatos — APPROVED** [review]

**Comment by jbartok** [comment]
@bot-gradle test and merge
