### PR TITLE
Fix off-by-one in `LazySortedReferenceHashSetTest#removeIndex`

### LINKED ISSUE #35522: ArrayIndexOutOfBoundsException with a circular shouldRunAfter Task constraint
### Current Behavior

I upgraded one of our builds to Gradle 9.2.0 and when I build one of the projects I now get this exception:

> java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 9 out of bounds for object array[8]
>         at org.gradle.execution.plan.NodeSets$LazySortedReferenceHashSet.removeIndex(NodeSets.java:170)
>         at org.gradle.execution.plan.NodeSets$LazySortedReferenceHashSet.access$300(NodeSets.java:53)
>         at org.gradle.execution.plan.NodeSets$LazySortedReferenceHashSet$1.remove(NodeSets.java:111)
>         at com.google.common.collect.Iterables.removeIf(Iterables.java:203)
>         at org.gradle.execution.plan.DetermineExecutionPlanAction.removeShouldRunAfterSuccessorsIfTheyImposeACycle(DetermineExecutionPlanAction.java:264)
>         at org.gradle.execution.plan.DetermineExecutionPlanAction.processNodeQueue(DetermineExecutionPlanAction.java:163)
>         at org.gradle.execution.plan.DetermineExecutionPlanAction.run(DetermineExecutionPlanAction.java:93)
>         at org.gradle.execution.plan.DefaultExecutionPlan.determineExecutionPlan(DefaultExecutionPlan.java:223)
>         at org.gradle.internal.build.DefaultBuildWorkPreparer.populateWorkGraph(DefaultBuildWorkPreparer.java:43)
>         at org.gradle.internal.build.BuildOperationFiringBuildWorkPreparer$PopulateWorkGraph.populateTaskGraph(BuildOperationFiringBuildWorkPreparer.java:106)
>         at org.gradle.internal.build.BuildOperationFiringBuildWorkPreparer$PopulateWorkGraph.run(BuildOperationFiringBuildWorkPreparer.java:92)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
>         at org.gradle.internal.build.BuildOperationFiringBuildWorkPreparer.populateWorkGraph(BuildOperationFiringBuildWorkPreparer.java:67)
>         at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$populateWorkGraph$8(DefaultBuildLifecycleController.java:189)
>         at org.gradle.internal.model.StateTransitionController.lambda$inState$1(StateTransitionController.java:99)
>         at org.gradle.internal.model.StateTransitionController.lambda$inState$2(StateTransitionController.java:114)
>         at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:45)
>         at org.gradle.internal.model.StateTransitionController.inState(StateTransitionController.java:110)
>         at org.gradle.internal.model.StateTransitionController.inState(StateTransitionController.java:98)
>         at org.gradle.internal.build.DefaultBuildLifecycleController.populateWorkGraph(DefaultBuildLifecycleController.java:189)
>         at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.populateWorkGraph(DefaultBuildWorkGraphController.java:169)
>         at org.gradle.composite.internal.DefaultBuildController.populateWorkGraph(DefaultBuildController.java:76)
>         at org.gradle.composite.internal.DefaultIncludedBuildTaskGraph$DefaultBuildTreeWorkGraphBuilder.withWorkGraph(DefaultIncludedBuildTaskGraph.java:155)
>         at org.gradle.internal.buildtree.DefaultBuildTreeWorkPreparer.lambda$scheduleRequestedTasks$1(DefaultBuildTreeWorkPreparer.java:40)
>         at org.gradle.composite.internal.DefaultIncludedBuildTaskGraph$DefaultBuildTreeWorkGraph$1.run(DefaultIncludedBuildTaskGraph.java:211)

### Expected Behavior

No exception

### Context (optional)

I've narrowed the immediate cause down to a circular shouldRunAfter dependency: I have a list of tasks which I use shouldRunAfter to suggest an ordering on, and one of the entries was in the list twice. Removing the cycle fixes the exception. There are other dependsOn constraints between the tasks in the list.

The same build succeeds on our Windows CI nodes.

### Self-contained Reproducer Project

Sorry, I've spent an hour trying to create a minimal project and I haven't been able to reproduce this outside of the original project, which I'm unable to share. I'm reporting this in the hope that it's useful.

### Gradle version

9.2.0

### Build scan URL (optional)

_No response_

### Your Environment (optional)

macOS 14.8.1 aarch64

### PR DESCRIPTION
**Pull request by bamboo**
Resolves #35522

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test RFN

**Comment by 6hundreds** [comment]
@bamboo This is targeted to master and have a 9.3 milestone, but does it deserve 9.2.x release?

File: subprojects/core/src/main/java/org/gradle/execution/plan/NodeSets.java [hunk 1]
```diff
@@ -84,7 +84,9 @@ public boolean contains(Object o) {
         @Override
         public boolean remove(Object o) {
             if (set.remove(o)) {
-                removeIndex(indexOf(o));
+                int index = indexOf(o);
```
Comment (abstratt) [inline subprojects/core/src/main/java/org/gradle/execution/plan/NodeSets.java:87]: ❓ 

Is this to handle the case the set and the indices got out of sync (multiple threads modifying the set)? If so, isn't a `ConcurrentModificationException` more appropriate?

None of the added tests exercise this change, right?

Also, did you manage to reproduce the issue with `removeIf`? Or do you think the test cases exercise a similar scenario and that is not necessary?

Comment (bamboo) [reply subprojects/core/src/main/java/org/gradle/execution/plan/NodeSets.java:87]: > Is this to handle the case the set and the indices got out of sync (multiple threads modifying the set)?

Yes, though I don't expect it to ever happen in practice. That's why I chose an `assert` instead of the exception.

> If so, isn't a `ConcurrentModificationException` more appropriate?

Well... We might as well have it.

Comment (bamboo) [reply subprojects/core/src/main/java/org/gradle/execution/plan/NodeSets.java:87]: > Also, did you manage to reproduce the issue with removeIf? 

Yes.
