### PR TITLE
Fully support substituting an enforced dependency through a project

### LINKED ISSUE #10808: Class Cast exception from DefaultProjectDependencyMetadata to ModuleDependencyMetadata when using includeBuild and enforcedPlatform
### Summary:
When connecting the gradle project b to the project a with a dependency and also using a enforcedPlatform dependency to determine/enforce the version numbers of the dependent project, everything works fine, when both projects are NOT in a composite build. Once you try to add a `includeBuild '../project_a'` in the settings.gradle of project b, you will run into the class cast exception from DefaultProjectDependencyMetadata to ModuleDependencyMetadata. You can resolve this problem by adding another `includeBuild '../platform_project'` to the composite build, where you point to the corresponding gradle platform_project, but this is not wanted.

### Expected Behavior
It should be possible to use a enforcedPlatform dependency at the same time in the context of a composite build (without being forced to includeBuild also the gradle platform project)

### Current Behavior
When the two project are connected via an includeBuild entry in the settings.gradle file, you will get this exception when starting a gradlew build:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':Common:compileJava'.
> Could not resolve all dependencies for configuration ':Common:compileClasspath'.
   > org.gradle.internal.component.local.model.DefaultProjectDependencyMetadata cannot be cast to org.gradle.i
nternal.component.external.model.ModuleDependencyMetadata
```

### Context
We are trying to use the enforcedPlatform mechanism to use our company BOM file for the version-numbers of our dependency artifacts. At the same time we must be able to use the composite Build feature with eclipse buildShip plugin to create a good workspace for our developers. This will not work, when it is not possible to use enforcedPlatform at the same time with includeBuild. It also makes no sense to force all developers to check out at the same time the platform project when the want to use composite builds.

### Steps to Reproduce 
[forcedPlatformIncludeBuildProblem.zip](https://github.com/gradle/gradle/files/3635546/forcedPlatformIncludeBuildProblem.zip)
Extact all included folders and put them next to each other. Then go into the folder ci_poc_gitflow_platform and first publish with `gradlew pTML` the platform project to the local .m2. Afterwards use `pTML` task on the ci_poc_gitflow_a folder, to publish the a project. Now you will get the class cast exception in the ci_poc_gitflow_b folder when starting gradle with `gradlew build`. 
You can "fix" it, by commenting out the `includeBuild '../ci_poc_gitflow_a'` in the settings.gradle of root-project ci_poc_gitflow_b (=no composite build) or by activating the line `//includeBuild '../ci_poc_gitflow_platform'` to include the platform (=composite build with the gradle platform project)

### Your Environment
https://gradle.com/s/te7vykvm6lgco

I hope this information is enought. Please come back if you need more.

### PR DESCRIPTION
**Pull request by jjohannes**
This caused an exception before, if the enforce platform was sourced from a BOM (pom.xml).

Fixes #10808

### CODE REVIEW

**Comment by jjohannes** [comment]
@bot-gradle test QF

**Comment by jjohannes** [comment]
@bot-gradle test this

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ForcedDependencyMetadataWrapper.java [hunk 1]
```diff
@@ -75,12 +76,20 @@ public ModuleDependencyMetadata withEndorseStrictVersions(boolean endorse) {
...
+            return ((DefaultProjectDependencyMetadata) dependencyMetadata).forced();
+        }
+        return new ForcedDependencyMetadataWrapper((ModuleDependencyMetadata) dependencyMetadata);
     }
 
     @Override
     public DependencyMetadata withTargetAndArtifacts(ComponentSelector target, List<IvyArtifactName> artifacts) {
-        return new ForcedDependencyMetadataWrapper((ModuleDependencyMetadata) delegate.withTargetAndArtifacts(target, artifacts));
+        DependencyMetadata dependencyMetadata = delegate.withTargetAndArtifacts(target, artifacts);
+        if (dependencyMetadata instanceof DefaultProjectDependencyMetadata) {
```
Comment (jjohannes) [inline subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ForcedDependencyMetadataWrapper.java:89]: The structure of the various implementations of `DependencyMetadata` grew into quite a mess over time. It's a mix of inheritance, multiple interfaces and delegation. There is no consistent pattern in that right now. Hence I went for the "simple" fix here that addresses the one special case that was broken, instead of introducing even more abstraction/delegation.

**Review by ljacomet — APPROVED** [review]
LGTM 👍

**Comment by jjohannes** [comment]
@bot-gradle test and merge
