### PR TITLE
Check and fix native access warnings in Java 24

### LINKED ISSUE #31625: Using Java 24+ toolchain emits warning due to restricted method in java.lang.System being called
### Current Behavior

When running a `JavaCompile` or `Checkstyle` task with JDK 24-ea or 25-ea, the following warning is emitted to stderr:

```
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/home/marc/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/native-platform-0.22-milestone-26.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
```

### Expected Behavior

No such warnings should be printed.

### Context (optional)

Configuring the `compileJava` task like this prevents the warning from being omitted:
```kotlin
tasks.compileJava {
    options.forkOptions.jvmArgs = listOf("--enable-native-access=ALL-UNNAMED")
}
```

Origin JEP: https://openjdk.org/jeps/472

### Self-contained Reproducer Project

1. Clone https://github.com/marcphilipp/gradle-sandbox
2. `cd gradle-jdk24-restricted-method-call-reproducer`
3. `./gradlew build --rerun-tasks`

### Gradle version

8.11.1

### Build scan URL (optional)

https://ge.junit.org/s/lfxtjzyxaqejw/console-log?task=:junit-platform-commons:compileJava

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #31625

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: platforms/core-runtime/base-services/src/main/java/org/gradle/internal/jvm/JpmsConfiguration.java [hunk 1]
```diff
@@ -26,10 +26,15 @@
  * Gradle accesses those packages reflectively. On Java versions 9 to 15, the users will get
  * a warning they can do nothing about. On Java 16+, strong encapsulation of JDK internals is
  * enforced and not having the explicit permissions for reflective accesses will result in runtime exceptions.
+ *
+ * <p>
+ * For the {@code --enable-native-access} flag, users will get a warning on Java 24+ if the flag is not present.
+ * There is no enforcement of the flag at the time of writing.
+ * </p>
  */
 public class JpmsConfiguration {
```
Comment (big-guy) [inline platforms/core-runtime/base-services/src/main/java/org/gradle/internal/jvm/JpmsConfiguration.java:35]: For readability, I think it would be nicer if...

1. All of the lists were inside the static block.  This keeps them all together vs scattered
2. All of the static lists should be assigned in the static block.  Some javadoc on these fields can describe what their purpose is
3. The getters should be together with some javadoc. You might also consider a name that looks less like getting a property and more like calculating a value.  e.g., `JpmsConfiguration.forGroovyCompiler(javaVersion)` vs `JpmsConfiguration.getGroovyArgs(javaVersion)` 

WRT the names of the fields, I think we can get away with something like:
`GRADLE_DAEMON_JPMS_ARGS_$javaVersion` and ignore the detail about native services.

File: subprojects/core/src/main/java/org/gradle/process/internal/worker/WorkerProcessBuilder.java [hunk 2]
```diff
@@ -64,6 +64,16 @@ public interface WorkerProcessBuilder extends WorkerProcessSettings {
...
 
+    /**
+     * Set if Gradle should add JPMS-compatibility flags to the worker process when needed.
+     * These are needed on Java 24+ when using native services because they access native libraries.
+     * There may be other cases in the future where different flags are needed in other scenarios.
+     *
+     * @param addJpmsCompatibilityFlags whether to add the flags
+     * @return this
+     */
+    WorkerProcessBuilder setAddJpmsCompatibilityFlags(boolean addJpmsCompatibilityFlags);
```
Comment (big-guy) [inline subprojects/core/src/main/java/org/gradle/process/internal/worker/WorkerProcessBuilder.java:75]: Is this being called from anywhere?

**Review by big-guy — CHANGES_REQUESTED** [review]

File: subprojects/core/src/main/java/org/gradle/process/internal/worker/WorkerProcessBuilder.java (hunk 2 above)
Comment (octylFractal) [reply subprojects/core/src/main/java/org/gradle/process/internal/worker/WorkerProcessBuilder.java:75]: No, I added it in case we needed to call it from somewhere (e.g. testing used to set a similar flag for `--add-opens`).

**Review by big-guy — APPROVED** [review]
