### PR TITLE
Fix bug in TAR format detection

### LINKED ISSUE #23391: 8.0 RC 1 regression:  tartree does not work for .tar.gz files
Tartree seems to be broken in 8.0-RC1

The following code works in gradle 7.6 but throws an error in 8.0-RC1. 

```
plugins {
    id "de.undercouch.download" version "5.3.0"
}

tasks.register("download", Download) {
    src("https://github.com/sass/dart-sass/releases/download/1.57.1/dart-sass-1.57.1-linux-x64.tar.gz")
    dest file("$buildDir")
}

tasks.register("unpack", Copy) {
    dependsOn tasks.named("download")
    from tarTree("$buildDir/dart-sass-1.57.1-linux-x64.tar.gz")
    into file("$buildDir/somefolder")
}
```
`./gradlew unpack`

### Expected Behavior
File should be unpacked

```
### Current Behavior

> Task :download
Download https://github.com/sass/dart-sass/releases/download/1.57.1/dart-sass-1.57.1-linux-x64.tar.gz
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

> Task :unpack FAILED
2 actionable tasks: 2 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unpack'.
> Unable to expand TAR 'C:\proyectos\gradle-jartree\build\dart-sass-1.57.1-linux-x64.tar.gz'
    The tar might be corrupted or it is compressed in an unexpected way.
    By default the tar tree tries to guess the compression based on the file extension.
    If you need to specify the compression explicitly please refer to the DSL reference.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

```

### Steps to Reproduce 
I provided is a minimal reproducer

### Your Environment
Tested in windows and linux, in java 17 and 18
Build scan URL:
https://gradle.com/s/gipau4zcwhi3e

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #23391

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by eskatos** [comment]
@bot-gradle test this

File: subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java [hunk 1]
```diff
@@ -163,11 +163,12 @@ private void checkFormat(InputStream inputStream) throws IOException {
 
         if (signatureLength >= tarHeaderSize) {
             try (TarArchiveInputStream tais = new TarArchiveInputStream(new ByteArrayInputStream(tarHeader))) {
-                if (tais.getNextTarEntry() == null) {
+                TarArchiveEntry tarEntry = tais.getNextTarEntry();
```
Comment (eskatos) [inline subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java:166]: 👍

File: subprojects/soak/src/integTest/groovy/org/gradle/file/archive/TarFileTreeSoakTest.groovy [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+    @Rule
+    public final TestNameTestDirectoryProvider temporaryFolder = new TestNameTestDirectoryProvider(getClass())
+
+    @Issue("https://github.com/gradle/gradle/issues/23391")
+    def "can decompress TAR archive with truncated header"() {
+        given:
+        TestFile tgz = temporaryFolder.file("test.tgz")
+
+        InputStream input = new URL("https://github.com/sass/dart-sass/releases/download/1.57.1/dart-sass-1.57.1-linux-x64.tar.gz").openStream()
+        Files.copy(input, tgz.toPath(), StandardCopyOption.REPLACE_EXISTING)
```
Comment (eskatos) [inline subprojects/soak/src/integTest/groovy/org/gradle/file/archive/TarFileTreeSoakTest.groovy:53]: :x: Better close that resource
```suggestion
        try (InputStream input = new URL("https://github.com/sass/dart-sass/releases/download/1.57.1/dart-sass-1.57.1-linux-x64.tar.gz").openStream()) {
            Files.copy(input, tgz.toPath(), StandardCopyOption.REPLACE_EXISTING)
        }
```

File: subprojects/soak/src/integTest/groovy/org/gradle/file/archive/TarFileTreeSoakTest.groovy [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+
+import java.nio.file.Files
+import java.nio.file.StandardCopyOption
+
+import static org.gradle.api.internal.file.TestFiles.directoryFileTreeFactory
+import static org.gradle.api.internal.file.TestFiles.fileHasher
+import static org.gradle.api.internal.file.TestFiles.fileSystem
+import static org.gradle.util.internal.WrapUtil.toList
+
+class TarFileTreeSoakTest extends Specification {
```
Comment (eskatos) [inline subprojects/soak/src/integTest/groovy/org/gradle/file/archive/TarFileTreeSoakTest.groovy:42]: ❓ Why not reuse `AbstractIntegrationSpec` here? That would allow to get rid of the custom `temporaryFolder` and have the test behave the same as the other ones wrt. temporary files.

**Review by eskatos — CHANGES_REQUESTED** [review]

File: subprojects/soak/src/integTest/groovy/org/gradle/file/archive/TarFileTreeSoakTest.groovy (hunk 3 above)
Comment (jbartok) [reply subprojects/soak/src/integTest/groovy/org/gradle/file/archive/TarFileTreeSoakTest.groovy:42]: My thinking was to not bring in a bunch of unused functionality until not really needing it, but I don't feel strongly about it. Will change it.

**Comment by jbartok** [comment]
@bot-gradle test this

**Review by eskatos — APPROVED** [review]
:+1:

**Comment by jbartok** [comment]
@bot-gradle test and merge
