### PR TITLE
Define ProjectInternal equality to be the project identity 

### LINKED ISSUE #30745: Project equality is now hilariously broken when isolated Projects are enabled
### Current Behavior

Put this line of code anywhere in any build.gradle.kts:
println(project.rootProject == project.rootProject)
it prints true if isolatedProjects are disabled
it prints false if isolated Projects are enabled

### Expected Behavior

That should usually print true right?

### Context (optional)

_No response_

### Self-contained Reproducer Project

println(project.rootProject == project.rootProject)

### Gradle version

8.10.2

### Gradle version that used to work

8.8

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #30745 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java [hunk 1]
```diff
@@ -641,6 +641,20 @@ public int compareTo(Project otherProject) {
...
+    public boolean equals(Object obj) {
+        if (obj instanceof MutableStateAccessAwareProject) {
+            // Unwrap to keep this symmetric with the MutableStateAccessAwareProject equals() method
+            return ((MutableStateAccessAwareProject) obj).getProject().equals(this);
+        }
+        return this == obj;
+    }
+
+    @Override
+    public int hashCode() {
```
Comment (octylFractal) [inline subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java]: This was added to satisfy ErrorProne.

Comment (jvandort) [reply subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java]: Shouldn't we unwrap?

This current implementation allows two instances to be equal but have different hash codes

Comment (jvandort) [reply subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java:654]: Shouldn't we unwrap?

This current implementation allows two instances to be equal but have different hash codes

Comment (octylFractal) [reply subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java]: I am confused what we would unwrap here, this is already the unwrapped project. `MutableStateAccessAwareProject` already unwraps: https://github.com/gradle/gradle/blob/e16096755271f495a1e4c4a9a1cbe13c104c03ac/subprojects/core/src/main/java/org/gradle/api/internal/project/MutableStateAccessAwareProject.java#L144-L146

File: subprojects/core/src/main/java/org/gradle/api/internal/project/MutableStateAccessAwareProject.java [hunk 2]
```diff
@@ -135,14 +135,17 @@ public String toString() {
     }
 
     @Override
-    @SuppressWarnings({"EqualsDoesntCheckParameterClass", "EqualsWhichDoesntCheckParameterClass"})
     public final boolean equals(Object other) {
-        return delegate.equals(other);
```
Comment (6hundreds) [inline subprojects/core/src/main/java/org/gradle/api/internal/project/MutableStateAccessAwareProject.java:140]: ❓ I wonder, why we can't keep it delegated?

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/ProjectIdentityIntegrationTest.groovy [hunk 3]
```diff
@@ -82,6 +82,7 @@ class ProjectIdentityIntegrationTest extends AbstractIntegrationSpec {
         given:
         executer.requireIsolatedDaemons()
         settingsFile """
+            System.gc() // On re-run, encourage collection of the previous project identity
```
Comment (6hundreds) [inline subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/ProjectIdentityIntegrationTest.groovy]: ❓Can you explain why we need this? The test is `project identity doesn't survive build finish`. So it should be the case for the Gradle without additional GC triggering. If the embedded executer makes us to do that, then we should run this test only with forking one I think

File: subprojects/core/src/main/java/org/gradle/api/internal/project/MutableStateAccessAwareProject.java (hunk 2 above)
Comment (octylFractal) [reply subprojects/core/src/main/java/org/gradle/api/internal/project/MutableStateAccessAwareProject.java:140]: We could I suppose, but I think the way it is makes it clearer what the intention is. To me, delegating equals is a warning flag because it implies that the equality may not be symmetric.

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/ProjectIdentityIntegrationTest.groovy (hunk 3 above)
Comment (octylFractal) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/ProjectIdentityIntegrationTest.groovy]: The behavior is dependent on the `WeakHashMap` being cleared after the build finish. Without the GC call, it may not happen and therefore the same identity will be seen on the next run.

I imagine this was originally working because each build created a new project that had a different object identity (i.e., this test didn't really test anything before, it just put two entries in the map). However, we now use the identity path, so we need to make sure that the old `Project` is actually cleaned up.

Comment (octylFractal) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/ProjectIdentityIntegrationTest.groovy]: Alternatively, if it was supposed to check that the two different projects actually have different object identities (not `ProjectIdentity`), then I can re-work this test to just use `IdentityHashMap` instead.

**Review by jvandort — APPROVED** [review]

File: subprojects/core/src/main/java/org/gradle/api/internal/project/MutableStateAccessAwareProject.java (hunk 2 above)
Comment (6hundreds) [reply subprojects/core/src/main/java/org/gradle/api/internal/project/MutableStateAccessAwareProject.java:140]: I agree

File: subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectInternal.java [hunk 4]
```diff
@@ -265,6 +265,23 @@ public interface ProjectInternal extends Project, ProjectIdentifier, HasScriptSe
...
     Object getLifecycleActionsState();
 
+    /**
+     * Two {@link ProjectInternal} instances are considered equal if their {@link #getProjectIdentity() identity} is equal.
+     *
+     * @param o the object to compare with this project
+     * @return true if the given object is a {@link ProjectInternal} with the same identity as this project, false otherwise
+     */
+    @Override
+    boolean equals(Object o);
```
Comment (alllex) [inline subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectInternal.java]: 💅  Align the naming with java.lang.Object
```suggestion
    boolean equals(Object obj);
```

File: subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/ProjectIdentityIntegrationTest.groovy (hunk 3 above)
Comment (6hundreds) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/ProjectIdentityIntegrationTest.groovy]: > I imagine this was originally working because each build created a new project that had a different object identity (i.e., this test didn't really test anything before, it just put two entries in the map).

Right. Honestly, I don't see any value in this test with the current implementation anymore

Comment (octylFractal) [reply subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/ProjectIdentityIntegrationTest.groovy]: Thinking over it more, I think it does have value with the `IdentityHashMap`. It ensures that we don't keep project instances across builds. I removed the other test because I don't think that one is useful, and it doesn't work under IP anyways as we purposefully don't keep the same project object between subprojects, we wrap.
