### PR TITLE
Canonicalize "." and ".." segments in RelativePaths

### LINKED ISSUE #5748: Sync task doesn't handle "." as an "into" subpath correctly
### Expected Behavior
I have a Sync task that looks like this:

```
task mySync(type: Sync) {
  into 'syncDest'
  into('.') {
    from 'srcDir'
  }
}
```

I expect this task to copy the contents of `srcDir` into the `syncDest` folder (removing anything currently in the syncDest folder). This is what a Copy task with the same config would do, and in line with the behavior of a Sync task where `'.'` is replaced with `'foo'`.

### Current Behavior
The above task creates a `syncDest` folder, but does not copy anything into it.

### Context
The sample code I'm using here is a little contrived, but in practice the second block gets added programmatically in a loop among other "into" blocks. Using multiple "into" blocks is generally useful for creating sync tasks that can produce large, complicated directory structures. In our case, some of the files are jars with fine-grained version numbers, so it helps to use Sync instead of Copy to clear out old versions of jars.

I do have a workaround where I use a Copy task with a `doFirst` that deletes the folder.

### Steps to Reproduce (for bugs)
Repro here: https://github.com/AlexLandau/gradle-sync-task/blob/master/build.gradle

You can run `./gradlew myCopy mySync` and compare the contents of the `copyDest` and `syncDest` directories.

### Your Environment
This is in Gradle 4.8. Output of `./gradlew --version`:

```
------------------------------------------------------------
Gradle 4.8
------------------------------------------------------------

Build time:   2018-06-04 10:39:58 UTC
Revision:     9e1261240e412cbf61a5e3a5ab734f232b2f887d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.13.5 x86_64
```

### PR DESCRIPTION
**Pull request by AlexLandau**
Fixes #5748

### Context
As documented in #5748, Sync and Copy tasks can have buggy behaviors (such as deleting copied files) when RelativePath objects refer to the same path but consist of a different list of segments. This can happen in particular when "." and ".." are used in path segments.

Avoid this situation by canonicalizing RelativePaths as they are created, so that "." is not used and ".." only appears at the beginning of a path.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

File: subprojects/core-api/src/main/java/org/gradle/api/file/RelativePath.java [hunk 1]
```diff
@@ -47,17 +48,39 @@ public RelativePath(boolean endsWithFile, String... segments) {
 
     private RelativePath(boolean endsWithFile, @Nullable RelativePath parentPath, String... childSegments) {
         this.endsWithFile = endsWithFile;
-        int targetOffsetForChildSegments;
+        final int expectedLength;
+        final Iterable<String> sourceSegments;
```
Comment (AlexLandau) [inline subprojects/core-api/src/main/java/org/gradle/api/file/RelativePath.java:52]: An alternative here would be to collect a `List<String[]>` containing the `childSegments` and (if present) the `parentPath.segments`. This would add a layer of nested loops, but would allow for a numeric for-loop over the arrays, if desired.

File: subprojects/core-api/src/main/java/org/gradle/api/file/RelativePath.java [hunk 2]
```diff
@@ -47,17 +48,39 @@ public RelativePath(boolean endsWithFile, String... segments) {
...
+            expectedLength = parentPath.segments.length + childSegments.length;
+            sourceSegments = Iterables.concat(Arrays.asList(parentPath.segments),
+                Arrays.asList(childSegments));
         } else {
-            segments = new String[childSegments.length];
-            targetOffsetForChildSegments = 0;
+            expectedLength = childSegments.length;
+            sourceSegments = Arrays.asList(childSegments);
         }
-        copyAndInternSegments(segments, targetOffsetForChildSegments, childSegments);
```
Comment (AlexLandau) [inline subprojects/core-api/src/main/java/org/gradle/api/file/RelativePath.java:60]: Despite the name, this no longer interns the segment strings.

**Comment by ov7a** [comment]
@bot-gradle test and merge

**Comment by AlexLandau** [comment]
I'll take a look and see what I can come up with.

**Comment by AlexLandau** [comment]
No worries, @blindpirate.

I put together https://github.com/gradle/gradle/pull/26874 as a performance improvement for @ov7a to review.

**Comment by ov7a** [comment]
Thanks, @AlexLandau!
