### PR TITLE
Fix dependency reporting tasks for CC

### LINKED ISSUE #22781: Fix dependency reporting tasks to be compatible with configuration caching
@adammurdoch commented on [Sun Dec 19 2021](https://github.com/gradle/configuration-cache/issues/562)

Dogfood using dependency resolution results as task inputs by fixing the reporting tasks to be configuration caching compatible.

### PR DESCRIPTION
**Pull request by abstratt**
Fixes #22781

BTW, Adam suggested we used this as an opportunity to "dogfood using dependency resolution results as task inputs", but I haven't done that yet, though the changes I am assuming would be minor (new input(s) following [this sample](https://docs.gradle.org/current/samples/sample_tasks_with_dependency_resolution_result_inputs.html)).

### CODE REVIEW

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/AbstractConfigurationCacheIntegrationTest.groovy [hunk 1]
```diff
@@ -63,4 +63,13 @@ abstract class AbstractConfigurationCacheIntegrationTest extends AbstractOptInFe
             .testClass(testClass)
             .assertTestsExecuted(testNames)
     }
+
+    protected static String removeVfsLogOutput(String normalizedOutput) {
```
Comment (abstratt) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/AbstractConfigurationCacheIntegrationTest.groovy:67]: Moved from https://github.com/gradle/gradle/pull/23366/files#diff-06bb9cc4ff63081da07c0038b9be9093ae259d14dba313fc7412f24b9a93f55dL190

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/DefaultResolutionResult.java [hunk 2]
```diff
@@ -72,22 +73,7 @@ public void allDependencies(final Closure closure) {
         allDependencies(ConfigureUtil.configureUsing(closure));
     }
 
-    private void eachElement(
```
Comment (abstratt) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/DefaultResolutionResult.java:75]: Moved to https://github.com/gradle/gradle/pull/23366/files#diff-222701e87dcd0e3b204770e5ee498f68855ee0f08cac3742e0ccc451bc9b664fR141

File: subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/internal/JsonProjectDependencyRenderer.java [hunk 3]
```diff
@@ -140,30 +138,13 @@ private void renderProject(Project project, JsonBuilder json) {
...
         projectOut.put("name", project.getName());
         projectOut.put("description", project.getDescription());
-        projectOut.put("configurations", createConfigurations(project));
+        projectOut.put("configurations", createConfigurations(configurations));
         overall.put("project", projectOut);
 
         json.call(overall);
     }
 
-    private List<Configuration> getConfigurationsWhichCouldHaveDependencyInfo(Project project) {
```
Comment (abstratt) [inline subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/internal/JsonProjectDependencyRenderer.java:149]: Done in the caller now: 
https://github.com/gradle/gradle/pull/23366/files#diff-0c32dae86deab611a7c6fff2825d5ebe8b935488a33251962dd11ea0a46858adR189

**Comment by abstratt** [comment]
@bot-gradle test RFN

File: subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/DefaultResolutionResult.java [hunk 4]
```diff
@@ -72,22 +73,7 @@ public void allDependencies(final Closure closure) {
...
-        }
-        moduleAction.execute(node);
-        for (DependencyResult d : node.getDependencies()) {
-            dependencyAction.execute(d);
-            if (d instanceof ResolvedDependencyResult) {
-                eachElement(((ResolvedDependencyResult) d).getSelected(), moduleAction, dependencyAction, visited);
-            }
-        }
-    }
+
```
Comment (bamboo) [inline subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/DefaultResolutionResult.java:76]: 💄 Did you mean to add an empty line here?

File: subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java [hunk 5]
```diff
@@ -66,7 +75,8 @@
  */
 @UntrackedTask(because = "We can't describe the dependency tree of all projects as input")
 public abstract class HtmlDependencyReportTask extends ConventionTask implements Reporting<DependencyReportContainer> {
-    private Set<Project> projects;
+    private Transient<SetProperty<Project>> projects = Transient.of(getObjectFactory().setProperty(Project.class).convention(Providers.of(getProject()).map(it -> Collections.singleton(it))));
```
Comment (bamboo) [inline subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java:78]: ❓ What's the benefit of using a `SetProperty` here?

File: subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectDetails.java [hunk 6]
```diff
@@ -19,12 +19,15 @@
...
 
 import javax.annotation.Nullable;
+import java.util.Objects;
 
 public interface ProjectDetails {
 
     static ProjectDetails of(final Project project) {
         final String displayName = project.getDisplayName();
         final String description = project.getDescription();
+        final String name = project.getName();
```
Comment (bamboo) [inline subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectDetails.java:29]: 🤔 This will make existing uses of `ProjectDetails` require more data to be captured than before, right? I'm not sure consolidating usages of `Project` data in `ProjectDetails` is the best path here, compared to defining separate models for the different tasks needs.

File: subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java (hunk 5 above)
Comment (abstratt) [reply subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java:78]: "Represents a property whose type is a Set of elements of type T."

What is your concern? I remember you mentioning something about additional overhead but do not recall the details so went ahead with the nicer API.

File: subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectDetails.java (hunk 6 above)
Comment (abstratt) [reply subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectDetails.java:29]: I considered that... since the additional payload seemed small enough, I leaned towards reusing it. These are current usages now btw:
image

File: subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java (hunk 5 above)
Comment (abstratt) [reply subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java:78]: Or are you questioning using a `Property` altogether?

Comment (abstratt) [reply subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java:78]: If it is the latter, I just went followed the example of another task. I guess I could have just:

```
private Transient.Var<Set<Project>> projects = Transient.varOf(uncheckedCast(singleton(getProject())));
```

?

Comment (bamboo) [reply subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java:78]: Exactly.

File: subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectDetails.java (hunk 6 above)
Comment (abstratt) [reply subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectDetails.java:29]: @bamboo I am still leaning towards using the same data structure used elsewhere in the report plugins for these tasks. 

Is this good to go in your view?

Comment (abstratt) [reply subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectDetails.java]: @bamboo PTAL: dd46120c6f9aaff4a800c9763a5df7ccf4ed6a15 

This commit uses multiple ProjectDetails variations that contain the data that is required by each task (only HTML Dependency Report task uses the new one which contains project name and path).

**Comment by abstratt** [comment]
@bot-gradle test ACC

File: subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectDetails.java (hunk 6 above)
Comment (bamboo) [reply subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectDetails.java]: Nice! 👍

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProjectReportIntegTest.groovy [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+
+    def setup() {
+        buildFile << """
+            apply plugin: 'project-report'
+        """
+    }
+
+    def "configuration cache for Project Report plugin task '#task' on empty project"() {
+        given:
+        settingsFile.createFile()
```
Comment (bamboo) [inline subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProjectReportIntegTest.groovy:29]: 💄 I'd move this line to `setup` above and write it like `settingsFile << ""` for similarity to how `buildFile` is set.

**Review by bamboo — APPROVED** [review]
Looking good!

File: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProjectReportIntegTest.groovy (hunk 7 above)
Comment (abstratt) [reply subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProjectReportIntegTest.groovy]: Turns out I had no reason to create a settings file, just removed it

**Comment by abstratt** [comment]
@bot-gradle test and merge
