### PR TITLE
Fix Windows path resolution in ArchUnitFixture using URL.toURI()

### LINKED ISSUE #35722: Tests of Gradle fail on Windows due to incorrect URL to path conversion
### Current Behavior

When running the `:architecture-test:test` task on the codebase of Gradle, then a couple of tests fail, because in `ArchUnitFixture`, `Paths.get(codeSource.getLocation().getPath())` is called in the `getClassFile` method. This works on Linux (and similar), but the correct code would be to write `Paths.get(codeSource.getLocation().toURI())` instead (which - as I have verified - solves the test issues on Windows).

### Expected Behavior

Tests should not fail, the path should be converted OS independently.

### Context (optional)

_No response_

### Self-contained Reproducer Project

Just run `gradle :architecture-test:test` on Windows on the Gradle codebase.

### Gradle version

9.4.0: commit: a150bb258e28d60c74be0d88968bcb334949f11a

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by stephan2405**
Fixes #35722 

### Context

On Windows, `codeSource.getLocation().getPath()` produces invalid file paths for architecture tests.  
Switching to `toURI()` resolves the path in an OS-independent way.  
This fixes failing tests when running `gradlew :architecture-test:test` on Windows.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

File: testing/architecture-test/src/test/java/org/gradle/architecture/test/ArchUnitFixture.java [hunk 1]
```diff
@@ -610,6 +610,10 @@ static Path getClassFile(JavaClass javaClass) {
         if (codeSource == null) {
             return null;
         }
-        return Paths.get(codeSource.getLocation().getPath());
+        try {
+            return Paths.get(codeSource.getLocation().toURI());
+        } catch (Exception e){
+            return null;
```
Comment (kelemen) [inline testing/architecture-test/src/test/java/org/gradle/architecture/test/ArchUnitFixture.java]: You shouldn't be catching a generic `Exception` for no reason. Instead, catch `URISyntaxException`.

Also, instead of returning `null`, it should just rethrow the exception (wrapped), because you don't want to hide problems (especially not in tests).

Comment (kelemen) [reply testing/architecture-test/src/test/java/org/gradle/architecture/test/ArchUnitFixture.java]: Also, the formatting is off (no space before "{").

Comment (stephan2405) [reply testing/architecture-test/src/test/java/org/gradle/architecture/test/ArchUnitFixture.java]: Thanks, I applied the suggested changes.

**Review by ov7a — APPROVED** [review]
Thank you for your contribution!

This PR is complete and simple enough, it will be merged immediately.
