### PR TITLE
Wrapper task should test distributionUrl set with --gradle-distribution-url or --gradle-version

### LINKED ISSUE #23865: `FileNotFoundException` when setting capital `RC` when using the `wrapper --gradle-version`
The gradle `wrapper` task incorrectly accepts capitals like `RC` and this eventually results in an `FileNotFoundException`.

```shell
$ ./gradlew wrapper --gradle-version=8.0-RC-5
Configuration on demand is an incubating feature.
Type-safe project accessors is an incubating feature.

> Configure project :jmh-panama
Directory '/Users/brice.dutheil/opensource/jdk/build/macosx-x86_64-server-release/jdk' (system property 'org.gradle.java.installations.paths') used for java installations does not exist

BUILD SUCCESSFUL in 934ms
1 actionable task: 1 executed
```

However when running the first gradle command after results in a `FileNotFoundException`

```shell
$ ./gradlew wrapper --gradle-version=8.0-RC-5
Downloading https://services.gradle.org/distributions/gradle-8.0-RC-5-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions/gradle-8.0-RC-5-bin.zip
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1989)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:109)
        at org.gradle.wrapper.Download.download(Download.java:89)
        at org.gradle.wrapper.Install$1.call(Install.java:83)
        at org.gradle.wrapper.Install$1.call(Install.java:63)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:63)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:109)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:66)
```

Trying to fix that by `./gradlew wrapper --gradle-version=8.0-rc-5`, results in the same `FileNotFoundException`.
The workaround is easy by modifying manually the `gradle/wrapper/gradle-wrapper.properties` and change

```diff
- distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-RC-5-bin.zip
+ distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-rc-5-bin.zip
```

### Expected Behavior

I think there's several leads to fix that usability issue
* The wrapper task should either accept the capitals, but properly change the case of the letters.
* The wrapper task fails when passing capital letters.
* The server that host the gradle distribution could be case insensitive.

### Current Behavior

`FileNotFoundException` on each new gradle command.

### Context

Upgrading gradle from version 7.6.1 to 8.0 RC5

### Steps to Reproduce 

Listed above in the description.

### Your Environment

N/A

### PR DESCRIPTION
**Pull request by FrauBoes**
### Context
The wrapper task should validate a url set by the user by sending a HEAD request before it is written to the `gradle-wrapper.properties` file. This helps the user to catch an invalid url early and can prevent an IO exception at execution time.

If needed, `--offline` can be passed to disable any networking.

Fixes #23865

### CODE REVIEW

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy [hunk 1]
```diff
@@ -158,4 +161,60 @@ class WrapperGenerationIntegrationTest extends AbstractIntegrationSpec {
...
+        then:
+        succeeds()
+    }
+
+    def "wrapper task with gradle version from command-line respects --offline mode"() {
+        when:
+        run "wrapper", "--gradle-version", "8.0-RC-5", "--offline"
+
+        then:
+        succeeds()
```
Comment (eskatos) [inline subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy:218]: :lipstick: it would be nice if these tests would start the http server and assert no requests are being made at all

File: subprojects/docs/src/docs/userguide/reference/gradle_wrapper.adoc [hunk 2]
```diff
@@ -76,7 +76,8 @@ distributionUrl=https\://services.gradle.org/distributions/gradle-{gradleVersion
 All of those aspects are configurable at the time of generating the Wrapper files with the help of the following command line options.
 
 `--gradle-version`::
-The Gradle version used for downloading and executing the Wrapper.
+The Gradle version used for downloading and executing the Wrapper. The resulting distribution url
+is validated with a HEAD request.
```
Comment (eskatos) [inline subprojects/docs/src/docs/userguide/reference/gradle_wrapper.adoc:80]: :lipstick: One sentence per line in `.adoc` files

File: subprojects/docs/src/docs/userguide/reference/gradle_wrapper.adoc [hunk 3]
```diff
@@ -93,7 +94,8 @@ The default value is `bin`.
 `--gradle-distribution-url`::
 The full URL pointing to Gradle distribution ZIP file.
 Using this option makes `--gradle-version` and `--distribution-type` obsolete as the URL already contains this information.
-This option is extremely valuable if you want to host the Gradle distribution inside your company’s network.
+This option is extremely valuable if you want to host the Gradle distribution inside your company’s network. The url is
+validated with a HEAD request.
```
Comment (eskatos) [inline subprojects/docs/src/docs/userguide/reference/gradle_wrapper.adoc:98]: :lipstick: One sentence per line in `.adoc` files

File: subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java [hunk 4]
```diff
@@ -497,4 +518,14 @@ public void setArchiveBase(PathBase archiveBase) {
...
         return networkTimeout;
     }
+
+    /**
+     * Sets the offline mode of the wrapper task.
+     *
+     * @since 8.2
+     */
+    @Incubating
+    public void setIsOffline(boolean isOffline) {
```
Comment (eskatos) [inline subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java:528]: :art: I would have had the task constructor grab the value of `startParameter.isOffline()` in a field. That way if someone registers a new task of type `Wrapper` they would get the correct behavior out of the box. Then there's no need for this setter.

Comment (FrauBoes) [reply subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java:528]: That's much better, thanks!

**Comment by FrauBoes** [comment]
@bot-gradle test this

**Comment by FrauBoes** [comment]
@bot-gradle test this

File: subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java [hunk 5]
```diff
@@ -165,9 +168,17 @@ private void checkProperties(Properties existingProperties) {
...
     private void testDistributionUrl() {
-        if (distributionUrlConfigured && !isOffline) {
+        if (distributionUrlConfigured) {
             try {
-                new Download(new Logger(true), "gradlew", Download.UNKNOWN_VERSION).sendHeadRequest(getDistributionUrl());
+                String url = getDistributionUrl();
+                URI uri = URI.create(url);
+                if (uri.getScheme().equals("file")) {
+                    if (!Files.exists(Paths.get(uri.getPath()).toAbsolutePath())) {
+                        throw new UncheckedIOException(String.format("Test of distribution url %s failed. Please check the values set with --gradle-distribution-url and --gradle-version.", url));
```
Comment (eskatos) [inline subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java:177]: :question: Why generate a exception message with the URL in this case and not in the `http` case?

I think we should make the behavior similar for both schemes.

File: subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java [hunk 6]
```diff
@@ -158,6 +167,26 @@ private void checkProperties(Properties existingProperties) {
...
 
+    private static final String DISTRIBUTION_URL_EXCEPTION_MESSAGE = "Test of distribution url failed. Please check the values set with --gradle-distribution-url and --gradle-version.";
+
+    private void testDistributionUrl() {
+        if (distributionUrlConfigured) {
+            String url = getDistributionUrl();
+            URI uri = URI.create(url);
+            if (uri.getScheme().equals("file")) {
+                if (Files.exists(Paths.get(uri.getPath()).toAbsolutePath())) {
+                    throw new UncheckedIOException(DISTRIBUTION_URL_EXCEPTION_MESSAGE);
```
Comment (eskatos) [inline subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java:178]: Would be nice to add a `FileNotFoundException` to the chain here so the user has a clear idea of why the url test failed.

Comment (FrauBoes) [reply subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java:178]: Right, although `File::exists` might also return false due to missing read permissions. I wonder if `FileNotFoundException` is be misleading in this case.

**Comment by FrauBoes** [comment]
@bot-gradle test this

File: subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java (hunk 6 above)
Comment (eskatos) [reply subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java:178]: Right. My point is mostly about having the file path available somewhere in the error message.

File: subprojects/docs/src/docs/release/notes.md [hunk 7]
```diff
@@ -50,6 +50,14 @@ Example:
...
 vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv -->
 
+### Wrapper task validates distribution url
+
+The wrapper task now validates the configured distribution url before writing it to the gradle-wrapper.properties file.
+If the url scheme is `http` or `https`, a HEAD request is sent.
+If the scheme is `file`, the existence of the file is checked.
+This surfaces invalid urls early and can prevent IO exceptions at execution time.
+
+More details can be found in the dedicated section of the [Gradle Wrapper](gradle_wrapper.html#[adding_the_gradle_wrapper](sec:adding_wrapper)) user manual chapter.
```
Comment (eskatos) [inline subprojects/docs/src/docs/release/notes.md:60]: :x: It would be better to have actually more details in the userguide than in release notes. Especially what the check is about depending on the URL scheme.

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy [hunk 8]
```diff
@@ -158,4 +163,79 @@ class WrapperGenerationIntegrationTest extends AbstractIntegrationSpec {
...
+        httpServer.start()
+        httpServer.expectHeadMissing(path)
+        def url = "${httpServer.uri}" + path
+
+        when:
+        run "wrapper", "--gradle-distribution-url", url
+
+        then:
+        Throwable throwable = thrown(UnexpectedBuildFailure.class)
+        assert throwable.message.contains("Test of distribution url failed. Please check the values set with --gradle-distribution-url and --gradle-version.")
```
Comment (eskatos) [inline subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy:183]: 🤓  Should also assert that the tested URL is displayed in the error

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy [hunk 9]
```diff
@@ -158,4 +163,79 @@ class WrapperGenerationIntegrationTest extends AbstractIntegrationSpec {
...
+        def url = target.toURI().toString()
+        target.delete()
+        target.assertDoesNotExist()
+
+        when:
+        run "wrapper", "--gradle-distribution-url", url
+
+        then:
+        Throwable throwable = thrown(UnexpectedBuildFailure.class)
+        assert throwable.message.contains("Test of distribution url failed. Please check the values set with --gradle-distribution-url and --gradle-version.")
```
Comment (eskatos) [inline subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy:215]: 🤓  Should also assert that the tested URL is displayed in the error

**Review by eskatos — CHANGES_REQUESTED** [review]

File: subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java (hunk 6 above)
Comment (FrauBoes) [reply subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java:178]: Got it, I'll add the url to the exception message in both cases.

**Comment by FrauBoes** [comment]
@bot-gradle test this

File: subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java [hunk 10]
```diff
@@ -158,6 +167,26 @@ private void checkProperties(Properties existingProperties) {
...
+
+    private void testDistributionUrl() {
+        if (distributionUrlConfigured) {
+            String url = getDistributionUrl();
+            URI uri = URI.create(url);
+            if (uri.getScheme().equals("file")) {
+                if (!Files.exists(Paths.get(uri).toAbsolutePath())) {
+                    throw new UncheckedIOException(String.format(DISTRIBUTION_URL_EXCEPTION_MESSAGE, url));
+                }
+            } else if (uri.getScheme().startsWith("http") && !isOffline) {
```
Comment (ljacomet) [inline subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java:180]: 💭 As discussed, let's create an issue that mandates `https` here unless you explicit opt-out

**Review by ljacomet — APPROVED** [review]
LGTM!

Minor docs suggestions

File: subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java (hunk 10 above)
Comment (FrauBoes) [reply subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java:180]: https://github.com/gradle/gradle/issues/24367

File: subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/Download.java [hunk 11]
```diff
@@ -84,6 +85,25 @@ private void configureProxyAuthentication() {
         }
     }
 
+    public void sendHeadRequest(URI uri) throws Exception {
+        URL safeUrl = safeUri(uri).toURL();
+        int responseCode = -1;
+        try {
+            HttpURLConnection conn = (HttpURLConnection)safeUrl.openConnection();
```
Comment (eskatos) [inline subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/Download.java:92]: :x: I think the test connection should be done directly on the provided URI instead of the "safe URI" that is stripped from credentials. Otherwise this will always fail for folks using authenticated URLs here. The "safe URI" should still be used for error reporting though.

**Review by eskatos — CHANGES_REQUESTED** [review]

File: subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/Download.java (hunk 11 above)
Comment (FrauBoes) [reply subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/Download.java:92]: The "safe URI" is what's currently used for downloading (line 117), shouldn't this be consistent? I agree that it should be used for error reporting.

Comment (eskatos) [reply subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/Download.java:92]: Let's keep it as it is then.

**Comment by FrauBoes** [comment]
@bot-gradle test and merge

**Review by eskatos — APPROVED** [review]
👍

**Comment by FrauBoes** [comment]
@bot-gradle test and merge
