### PR TITLE
Copy should succeed if it has named pipe in output that wasn't produces by the task

### LINKED ISSUE #2552: Sync task hangs when output directory contains a named pipe
### Expected Behavior
The Sync task should remove any unexpected files from the destination directory when it runs, even if one of them is a named pipe.

### Current Behavior
When a named pipe exists in the output directory the Sync task gets blocked trying to read from it in order to determine its hash and just hangs indefinitely.

### Context
We have a complicated build with a step where a payload from a given source folder is synced to the application's runtime folder. Under certain circumstances, it is possible for the application to not shut down properly and leave a named pipe around in the destination folder. When the build runs and tries to ensure the runtime folder is up to date, the entire build will hang while Gradle attempts to read from the now-defunct named pipe.

Connecting a debugger to the build at that point indicates it is hanging in the following call stack:

```
Thread [Task worker Thread 5] (Suspended)
    FileInputStream.open0(String) line: not available [native method]
    FileInputStream.open(String) line: 195
    FileInputStream.<init>(File) line: 138
    DefaultFileHasher.hash(File) line: 57
    CachingFileHasher.snapshot(File, long, long) line: 104
    CachingFileHasher.snapshot(FileTreeElement) line: 91
    CachingFileHasher.hash(FileTreeElement) line: 77
    DefaultFileSystemSnapshotter.fileSnapshot(FileTreeElement) line: 189
    DefaultFileSystemSnapshotter.access$600(DefaultFileSystemSnapshotter, FileTreeElement) line: 53
    DefaultFileSystemSnapshotter$FileVisitorImpl.visitFile(FileVisitDetails) line: 223
    Jdk7DirectoryWalker$1.visitFile(Path, BasicFileAttributes) line: 85
    Jdk7DirectoryWalker$1.visitFile(Object, BasicFileAttributes) line: 58
    Files.walkFileTree(Path, Set<FileVisitOption>, int, FileVisitor<Path>) line: 2670
    Jdk7DirectoryWalker.walkDir(File, RelativePath, FileVisitor, Spec<FileTreeElement>, AtomicBoolean, boolean) line: 58
    DirectoryFileTree.walkDir(File, RelativePath, FileVisitor, Spec<FileTreeElement>, AtomicBoolean) line: 155
    DirectoryFileTree.visitFrom(FileVisitor, File, RelativePath) line: 133
    DirectoryFileTree.visit(FileVisitor) line: 118
    DefaultFileSystemSnapshotter.doSnapshot(DirectoryFileTree) line: 165
    DefaultFileSystemSnapshotter.access$500(DefaultFileSystemSnapshotter, DirectoryFileTree) line: 53
    DefaultFileSystemSnapshotter$4.create() line: 147
    DefaultFileSystemSnapshotter$4.create() line: 141
    DefaultProducerGuard<T>.guardByKey(T, Factory<V>) line: 51
    DefaultFileSystemSnapshotter.snapshotDirectoryTree(DirectoryFileTree) line: 141
    AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitDirectoryTree(DirectoryFileTree) line: 95
    AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitCollection(FileCollectionInternal) line: 80
    FileCollectionAdapter(AbstractFileCollection).visitRootElements(FileCollectionVisitor) line: 234
    TaskPropertyFileCollection(CompositeFileCollection).visitRootElements(FileCollectionVisitor) line: 185
    DefaultGenericFileCollectionSnapshotter(AbstractFileCollectionSnapshotter).snapshot(FileCollection, FileCollectionSnapshotBuilder) line: 51
    DefaultGenericFileCollectionSnapshotter.snapshot(FileCollection, TaskFilePropertyCompareStrategy, SnapshotNormalizationStrategy, InputNormalizationStrategy) line: 36
    OutputFilesTaskStateChanges(AbstractNamedFileSnapshotTaskStateChanges).buildSnapshots(String, FileCollectionSnapshotterRegistry, String, SortedSet<TaskFilePropertySpec>) line: 91
    OutputFilesTaskStateChanges(AbstractNamedFileSnapshotTaskStateChanges).<init>(String, TaskExecution, TaskExecution, FileCollectionSnapshotterRegistry, String, ImmutableSortedSet<TaskFilePropertySpec>, InputNormalizationStrategy) line: 58
    OutputFilesTaskStateChanges.<init>(TaskExecution, TaskExecution, TaskInternal, FileCollectionSnapshotterRegistry, OutputFilesSnapshotter, InputNormalizationStrategy) line: 36
    TaskUpToDateState.<init>(TaskInternal, TaskHistoryRepository$History, OutputFilesSnapshotter, FileCollectionSnapshotterRegistry, FileCollectionFactory, ClassLoaderHierarchyHasher, ValueSnapshotter) line: 57
    DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates() line: 178
    DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(Collection<String>) line: 88
    SkipUpToDateTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 53
    ResolveTaskOutputCachingStateExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 54
    ValidatingTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 58
    SkipEmptySourceFilesTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 88
    ResolveTaskArtifactStateTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 52
    SkipTaskWithNoActionsExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 52
    SkipOnlyIfTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 54
    ExecuteAtMostOnceTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 43
    CatchExceptionTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 34
    DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(BuildOperationContext) line: 242
    DefaultBuildOperationExecutor$RunnableBuildOperationWorker<O>.execute(O, BuildOperationContext) line: 317
    DefaultBuildOperationExecutor$RunnableBuildOperationWorker<O>.execute(BuildOperation, BuildOperationContext) line: 309
    DefaultBuildOperationExecutor.execute(O, BuildOperationWorker<O>, DefaultBuildOperationState) line: 185
    DefaultBuildOperationExecutor.run(RunnableBuildOperation) line: 95
    DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(TaskInternal) line: 235
    DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(Object) line: 224
    DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(TaskInfo) line: 121
    DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor$TaskExecutorWorker, TaskInfo) line: 77
    DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(TaskInfo) line: 102
    DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(Object) line: 96
    DefaultTaskExecutionPlan.execute(TaskInfo, WorkerLease, Action<TaskInfo>) line: 612
    DefaultTaskExecutionPlan.executeWithTask(WorkerLease, Action<TaskInfo>) line: 567
    DefaultTaskPlanExecutor$TaskExecutorWorker.run() line: 96
    ExecutorPolicy$CatchAndRecordFailures.onExecute(Runnable) line: 63
    StoppableExecutorImpl$1.run() line: 46
    ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1142
    ThreadPoolExecutor$Worker.run() line: 617
    ThreadFactoryImpl$ManagedThreadRunnable.run() line: 55
    Thread.run() line: 745
```

Looking at some similar questions on StackOverflow, it appears that the hang-on-open behaviour is expected even if it does cause some people to scratch their head over it:

- https://stackoverflow.com/questions/6408099/fileinputstream-blocks-on-the-constructor-when-opening-a-named-pipe
- https://stackoverflow.com/questions/5782279/why-does-a-read-only-open-of-a-named-pipe-block

In the specific case of Gradle's Sync task and given the behaviour of Java when it is asked to read a named pipe which has nothing on the other end writing anything, I wonder if it would be more appropriate to avoid hashing the file. Technically, it isn't even a proper file so perhaps it should be skipped entirely (left alone or outright deleted during the sync).

### Steps to Reproduce (for bugs)

1. Use this `build.gradle` file:

```
task syncTask( type: Sync ) {
  from 'src'
  into 'dest'
}
```

2. Create this `test.sh` file to perform the necessary setup and invoke Gradle:

```
#!/bin/sh

set -e

rm -rf src dest
mkdir -p src dest
touch src/foo.txt

set -x

# Run sync task without the presence of a named pipe
gdl syncTask

# Create a named pipe in the output folder of the sync task
mkdir -p dest/temp
mkfifo dest/temp/named-pipe

# Run the sync task and watch it hang trying to open the named pipe
gdl syncTask
```

3. Invoke `test.sh` and observe it hanging when Gradle is invoked with a destination directory containing a named pipe.

### Workaround

As I was testing this out I found some behaviour I could not explain, but which avoided the I/O blocking entirely. If you use a build.gradle file with a (bogus) `exclude` stanza, no hanging is observed. I.e.:

```
task syncTask( type: Sync ) {
  from 'src'
  into 'dest'
  exclude {
    'non-existent'
  }
}
```

The exclusion pattern doesn't even have to match the name of the pipe; just its presence in the task definition is sufficient to change the Sync behaviour.

With the above build.gradle file, the named pipe under `dest/temp/named-pipe` is left alone by the Sync task and remains under the destination folder. I don't know if that is truly the proper behaviour under those circumstances -- one could argue it should be removed since no such file exists under the `from` folder -- but at least the build does not get blocked trying to scan the destination folder.

### PR DESCRIPTION
**Pull request by paplorinc**
Fixes #2552

Follow-up of https://github.com/gradle/gradle/pull/9878 and https://github.com/gradle/gradle/pull/2691

#9878 already fixed named pipes, this PR adds tests for it and recognizes the author, since he contributed test cases (cc: @robinverduijn)

### CODE REVIEW

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy [hunk 1]
```diff
@@ -178,6 +179,25 @@ class DirectorySnapshotterTest extends Specification {
...
 
+
+    @Requires(TestPrecondition.UNIX_DERIVATIVE)
+    @Issue("https://github.com/gradle/gradle/issues/2552")
+    def "named pipe snapshots to MissingFileSnapshot"() {
+        def rootDir = tmpDir.createDir("root")
+        def pipe = rootDir.file("testPipe").createNamedPipe()
+
+        when:
+        def snapshot = directorySnapshotter.snapshot(rootDir.absolutePath, directoryWalkerPredicate(new PatternSet()), new AtomicBoolean(false))
```
Comment (wolfs) [inline subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy]: You can use `null` as the predicate.

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy [hunk 2]
```diff
@@ -178,6 +179,25 @@ class DirectorySnapshotterTest extends Specification {
...
+        then:
+        assert snapshot instanceof DirectorySnapshot
+        snapshot.children.collectEntries { [it.name, it.class] } == [
+            testPipe: MissingFileSnapshot
+        ]
+
+        cleanup:
+        pipe.delete()
```
Comment (wolfs) [inline subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy]: The `TestNameTestDirectoryProvider` already deletes all the files in the temporary directory. Why do you need to add this extra cleanup?

File: subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopySpecIntegrationSpec.groovy [hunk 3]
```diff
@@ -194,4 +196,28 @@ class CopySpecIntegrationSpec extends AbstractIntegrationSpec {
...
+            }
+        """
+
+        when:
+        run "copy"
+        then:
+        outputDirectory.list().contains input.name
+
+        cleanup:
+        pipe.delete()
```
Comment (wolfs) [inline subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopySpecIntegrationSpec.groovy]: The TestNameTestDirectoryProvider already deletes all the files in the temporary directory. Why do you need to add this extra cleanup?

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy (hunk 2 above)
Comment (wolfs) [reply subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy]: I talked to @paplorinc, and we decided to leave the extra cleanup since the pipe is a special file. So we avoid any problems with the automatic cleanup and other tools.

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy (hunk 1 above)
Comment (paplorinc) [reply subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy]: Indeed, done

**Comment by paplorinc** [comment]
Merged, thanks! :)

File: subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy [hunk 4]
```diff
@@ -178,6 +179,25 @@ class DirectorySnapshotterTest extends Specification {
         rootDir.listFiles()*.makeReadable()
     }
 
+
+    @Requires(TestPrecondition.UNIX_DERIVATIVE)
+    @Issue("https://github.com/gradle/gradle/issues/2552")
+    def "named pipe snapshots to MissingFileSnapshot"() {
+        def rootDir = tmpDir.createDir("root")
+        def pipe = rootDir.file("testPipe").createNamedPipe()
```
Comment (paplorinc) [inline subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy]: image
