### PR TITLE
Exit early for FileSystemNode.hasDescendants

### LINKED ISSUE #15919: Android incremental build times are worse in 6.8.1 from 6.7.1
### Expected Behavior
I'd expect build times to stay the same or get better with a new release.

### Current Behavior
Some incremental builds in our Android project are roughly 12% slower in 6.8.1 than in 6.7.1 as measured with the Gradle Profiler tool.

### Context
I ran routine profiling when updating to 6.8 hoping to see potential improvements to build speeds. I was surprised to see that 6.8.1 was actually slower than 6.7.1.

### Steps to Reproduce 
I unfortunately cannot provide a sample project that reproduces it, as my results are from our large internal Android app.

However, I can say that I measured the build speeds using version 0.15.0 of the gradle profiler (https://github.com/gradle/gradle-profiler/releases/tag/v0.15.0), and the scenario I am profiling makes an ABI change to a class in a base module that many other modules depend on.

It is run with the command
```
gradle-profiler-0.15.0/bin/gradle-profiler --benchmark --profile buildscan --gradle-user-home=$HOME/.gradle --project-dir=/jorb/repo/android --output-dir=/jorb/repo/android/build/profiling/MyFlavorIncrementalBaseAbiChange --scenario-file /tmp/myflavor_assembledebug_with_base_abi_change.scenarios
```

and the scenario in the scenario file is
```
default-scenarios = ["myflavor_assembledebug_with_base_abi_change"]
"myflavor_assembledebug_with_base_abi_change" {
    apply-abi-change-to="base/src/main/java/com/airbnb/android/base/BaseDagger.kt"
    git-checkout {
        build=e3738fe8addc02b110db811453f32ac4b3baa176
    }
    tasks=[
        "flavor.myflavor:assembleDebug"
    ]
    title="myflavor assembleDebug with base abi change"
}
```

This uses 6 warm up iterations and 10 build iterations (the default). I ran this multiple times where the only difference between commits was the gradle version, and the result consistently showed slower builds in 6.8.1

This zip contains the csv and html result files of two runs with the different gradle versions.
[benchmark_results.zip](https://github.com/gradle/gradle/files/5859321/benchmark_results.zip)

### Your Environment
We are using Android Gradle Plugin 4.1.1 and Kotlin 1.4.20. The project has several dozen modules.

### PR DESCRIPTION
**Pull request by wolfs**
So we don't need to iterate the whole VFS.

Fixes #15919.

### CODE REVIEW

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNode.java [hunk 1]
```diff
@@ -153,26 +152,8 @@ public boolean hasDescendants() {
     }
 
     private boolean anyChildMatches(ChildMap<FileSystemNode> children, Predicate<FileSystemNode> predicate) {
```
Comment (lptr) [inline subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNode.java:154]: This could also be `static`.

**Review by lptr — APPROVED** [review]
LGTM.

**Review by melix — APPROVED** [review]

File: subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNode.java (hunk 1 above)
Comment (wolfs) [reply subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNode.java]: I made the method static.
